In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SpatialDropout1D
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

import numpy as np
import pandas as pd
import os
import seaborn as sns
import string
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from lime.lime_text import LimeTextExplainer

## Base Paper's dataset Preprocessing

In [2]:
import pandas as pd

# Load the dataset
paper_dataframe = pd.read_csv('/kaggle/input/humanllm/Final_dataset.csv')

# Replace '\r' and '\n' with an empty string in all columns
paper_dataframe = paper_dataframe.replace({'\r': '', '\n': ''}, regex=True)

In [3]:
paper_dataframe.head()

,uid,text,label
0,[urlsf_subset02]-[113472],Italy's President Sergio Mattarella has dissol...,1
1,[urlsf_subset01]-[60703],Brendan Gallagher's piano career was abruptly ...,1
2,[urlsf_subset04]-[262707],The concept for Wetsleeve(tm) was born out of ...,0
3,[urlsf_subset00]-[119531],Police officers in the United States had a tou...,1
4,[urlsf_subset06]-[188189],A woman has filed a lawsuit seeking more than ...,1

## firstly taking only first 30k datapoints

In [4]:
paper_dataframe =paper_dataframe[:30000]

In [5]:
label_counts = paper_dataframe['label'].value_counts()

# Print the counts
print("Count of label 0:", label_counts.get(0, 0))
print("Count of label 1:", label_counts.get(1, 0))

Count of label 0: 14891
Count of label 1: 15109

In [6]:
# Assuming df is your DataFrame
paper_dataframe.drop(columns=['uid'], inplace=True)

In [7]:
paper_dataframe.head()

                                                text  label
0  Italy's President Sergio Mattarella has dissol...      1
1  Brendan Gallagher's piano career was abruptly ...      1
2  The concept for Wetsleeve(tm) was born out of ...      0
3  Police officers in the United States had a tou...      1
4  A woman has filed a lawsuit seeking more than ...      1

# Loading HC-3 Dataset

In [8]:
# !pip install datasets
from datasets import load_dataset

ds = load_dataset("Hello-SimpleAI/HC3", "all")

# Concatenate inner lists into a single string for each element
concatenated = [' '.join(text_list) for text_list in ds['train']['human_answers']]

# Create a DataFrame with a single column named 'text'
df_human_hc3 = pd.DataFrame(concatenated, columns=['text'])
df_human_hc3['label'] = 0
df_human_hc3 = df_human_hc3[:1000]


concatenated_ = [' '.join(text_list) for text_list in ds['train']['chatgpt_answers']]

# Create a DataFrame with a single column named 'text'
df_ai_hc3 = pd.DataFrame(concatenated_, columns=['text'])
df_ai_hc3['label'] = 1
df_ai_hc3 = df_ai_hc3[:1000]

#concatenate both the dataset
df_HC3 = pd.concat([df_ai_hc3, df_human_hc3])
#shuffle the dataset
df_HC3 = df_HC3.sample(frac=1).reset_index(drop=True)
print(df_HC3.head())

0000.parquet:   0%|          | 0.00/39.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/24322 [00:00<?, ? examples/s]

                                                text  label
0  For compounding interest : If you have an acco...      0
1  Mass is a measure of the amount of matter in a...      1
2  Gold is : * rare , but not too rare * distinct...      0
3  Because it 's more expensive to mass - produce...      0
4  URL_0 is a placeholder that represents a speci...      1

## Our dataset preprocessing

In [9]:
# Define a function to preprocess each text
def preprocess_text(text):
    # Find the index of the first colon
    colon_index = text.find(':')
    # If a colon exists and is within the first 20 words, trim the text
    if colon_index != -1:
        # Get the words up to the colon's position
        words_before_colon = text[:colon_index].split()
        # Check if the colon is within the first 20 words
        if len(words_before_colon) <= 20:
            # Return the text after the colon, trimmed of leading/trailing spaces
            return text[colon_index + 1:].strip()
    # If no colon or colon is outside the first 20 words, return the original text
    return text

In [10]:
ai_df = pd.read_csv("/kaggle/input/3500-datapoints/updated_dataset.csv", encoding='ISO-8859-1')
ai_df = ai_df.replace({'\r': '', '\n': ''}, regex=True)
filtered_df = ai_df[ai_df['ai_generated_text'].notna()]

human_df = pd.DataFrame(filtered_df['text'])
ai_df = pd.DataFrame(filtered_df['ai_generated_text'])
ai_df['ai_generated_text'] = ai_df['ai_generated_text'].apply(preprocess_text)
ai_df.rename(columns = {'ai_generated_text':'text'}, inplace = True)
human_df['label'] = 0
ai_df['label'] = 1

#concatenate the dataset
my_df = pd.concat([human_df, ai_df])
#shuffle the dataset
my_df = my_df.sample(frac=1).reset_index(drop=True)

In [11]:
my_df.head()

                                                text  label
0  Photos: Photos: Emotions run high in Ferguson ...      0
1  The original Stompa designs I saw were a bit t...      1
2  Sensitivity and heterogeneity analysis In this...      0
3  It's been a long time since the Star Wars saga...      1
4  The fact is that, unfair as it may seem, Afric...      0

In [12]:
my_df.shape

(7514, 2)

## Paper's model code

# 1. Distilbert generated

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim
from transformers import DistilBertModel, DistilBertTokenizer

# Assuming 'df' is your dataset with columns ['text', 'label']
# Split the dataset into training and testing sets
print("Splitting the dataset into training and testing sets...")
train_df, test_df = train_test_split(paper_dataframe, test_size=0.2, random_state=42)
print(f"Training set size: {len(train_df)}, Testing set size: {len(test_df)}")

class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        # Extract the text and label from the dataframe
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Create datasets for training and testing
print("Creating datasets...")
train_dataset = TextDataset(train_df)
test_dataset = TextDataset(test_df)

# Create data loaders for batching
print("Creating data loaders...")
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

class Sentinel(nn.Module):
    def __init__(self, distilbert: DistilBertModel, tokenizer: DistilBertTokenizer) -> None:
        super().__init__()
        self.distilbert = distilbert
        # Freeze the parameters of the DistilBERT model
        for param in self.distilbert.parameters():
            param.requires_grad = False
        self.tokenizer = tokenizer

        # Define a fully connected layer for classification
        self.fc = nn.Sequential(
            nn.Linear(768, 768),
            nn.GELU(), nn.Dropout(0.25),
            nn.Linear(768, 2)
        )

    def forward(self, textBatch) -> torch.Tensor:
        # Tokenize and encode the text batch
        encodedText = self.tokenizer(
            textBatch, max_length=512, truncation=True,
            padding="max_length", return_tensors="pt"
        ).to("cuda")

        # Get the last hidden states from DistilBERT
        lastHiddenStates = self.distilbert(**encodedText).last_hidden_state
        # Pass through the fully connected layer to get logits
        logits = self.fc(lastHiddenStates[:, 0, :])
        return logits

# Load the pretrained DistilBERT model and tokenizer
print("Loading DistilBERT model and tokenizer...")
distil_model = DistilBertModel.from_pretrained('distilbert-base-uncased')
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Initialize the Sentinel model
print("Initializing the Sentinel model...")
distil_model = Sentinel(distil_model, tokenizer).to("cuda")

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(distil_model.parameters(), lr=1e-4)

# Set the number of epochs for training
num_epochs = 10
distil_model.train()

print("Starting training...")
for epoch in range(num_epochs):
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for texts, labels in train_loader:
        # Convert texts to a list and move labels to GPU
        texts = list(texts)
        labels = labels.to("cuda")

        # Zero the gradients
        optimizer.zero_grad()
        # Forward pass
        outputs = distil_model(texts)
        # Compute the loss
        loss = criterion(outputs, labels)
        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        # Accumulate the loss
        running_loss += loss.item()
        # Calculate the number of correct predictions
        _, predicted = torch.max(outputs, 1)
        correct_predictions += (predicted == labels).sum().item()
        total_predictions += labels.size(0)

    # Calculate average loss and accuracy for the epoch
    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = correct_predictions / total_predictions
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")

print("Training complete")

# Save the trained model to a file
print("Saving the model...")
torch.save(distil_model.state_dict(), 'distilbert_sentinel.pth')
print("Model saved as 'distilbert_sentinel.pth'")

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

Splitting the dataset into training and testing sets...
Training set size: 24000, Testing set size: 6000
Creating datasets...
Creating data loaders...
Loading DistilBERT model and tokenizer...

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Initializing the Sentinel model...
Starting training...
Epoch 1/10, Loss: 0.3453, Accuracy: 0.8614
Epoch 2/10, Loss: 0.2432, Accuracy: 0.9043
Epoch 3/10, Loss: 0.2308, Accuracy: 0.9079
Epoch 4/10, Loss: 0.2248, Accuracy: 0.9100
Epoch 5/10, Loss: 0.2191, Accuracy: 0.9137
Epoch 6/10, Loss: 0.2171, Accuracy: 0.9140
Epoch 7/10, Loss: 0.2147, Accuracy: 0.9136
Epoch 8/10, Loss: 0.2079, Accuracy: 0.9178
Epoch 9/10, Loss: 0.2080, Accuracy: 0.9179
Epoch 10/10, Loss: 0.2081, Accuracy: 0.9188
Training complete
Saving the model...
Model saved as 'distilbert_sentinel.pth'

In [14]:
# Step 5: Evaluate on the test set
distil_model.eval()
all_labels = []
all_predictions = []

with torch.no_grad():
    for texts, labels in test_loader:
        texts = list(texts)
        labels = labels.to("cuda")

        outputs = distil_model(texts)
        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Classification report
print("Classification Report:")
print(classification_report(all_labels, all_predictions))

# Calculate F1 Score, FNR, and FPR
f1 = f1_score(all_labels, all_predictions, average='weighted')
cm = confusion_matrix(all_labels, all_predictions)
tn, fp, fn, tp = cm.ravel()
fnr = fn / (fn + tp)
fpr = fp / (fp + tn)

print(f"F1 Score: {f1:.4f}")
print(f"False Negative Rate (FNR): {fnr:.4f}")
print(f"False Positive Rate (FPR): {fpr:.4f}")

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.86      0.91      2909
           1       0.88      0.97      0.92      3091

    accuracy                           0.91      6000
   macro avg       0.92      0.91      0.91      6000
weighted avg       0.92      0.91      0.91      6000

F1 Score: 0.9143
False Negative Rate (FNR): 0.0320
False Positive Rate (FPR): 0.1420

# DistilBert model trained on base paper's dataset and testing on our dataset(5k datapoints)

In [15]:
# No need of loading dataset again and again.Use defined our dataframe 'my_df'

# ai_df = pd.read_csv("/kaggle/input/3500-datapoints/updated_dataset.csv", encoding='ISO-8859-1')
# ai_df = ai_df.replace({'\r': '', '\n': ''}, regex=True)
# filtered_df = ai_df[ai_df['ai_generated_text'].notna()]
# human_df = pd.DataFrame(filtered_df['text'])
# ai_df = pd.DataFrame(filtered_df['ai_generated_text'])
# ai_df['ai_generated_text'] = ai_df['ai_generated_text'].apply(preprocess_text)
# ai_df.rename(columns = {'ai_generated_text':'text'}, inplace = True)
# human_df['label'] = 0
# ai_df['label'] = 1
# my_df = pd.concat([human_df[:1000], ai_df[:1000]], ignore_index=True)

my_df= my_df[:5000]



class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label


# ***** we are using our complete dataset for testing????  **************

# Data Loaders
# train_dataset = TextDataset(train_df)
test_dataset = TextDataset(my_df)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [16]:
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report

# Load the saved model weights
# model.load_state_dict(torch.load('/kaggle/input/2_epoch_mix_model/other/default/1/our_ensemble_model.pth'))
distil_model.eval()
# DataLoader for the test dataset

# Evaluate the model on the new dataset
print("Evaluating the model on the our dataset...")
all_labels = []
all_predictions = []

with torch.no_grad():
    for texts, labels in test_loader:
        texts = list(texts)
        labels = labels.to("cuda")

        outputs = distil_model(texts)
        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Classification report
print("Classification Report:")
print(classification_report(all_labels, all_predictions))

# Calculate F1 Score, FNR, and FPR
f1 = f1_score(all_labels, all_predictions, average='weighted')
cm = confusion_matrix(all_labels, all_predictions)
tn, fp, fn, tp = cm.ravel()
fnr = fn / (fn + tp)
fpr = fp / (fp + tn)

print(f"F1 Score: {f1:.4f}")
print(f"False Negative Rate (FNR): {fnr:.4f}")
print(f"False Positive Rate (FPR): {fpr:.4f}")

Evaluating the model on the our dataset...
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.91      0.89      2501
           1       0.90      0.88      0.89      2499

    accuracy                           0.89      5000
   macro avg       0.89      0.89      0.89      5000
weighted avg       0.89      0.89      0.89      5000

F1 Score: 0.8930
False Negative Rate (FNR): 0.1204
False Positive Rate (FPR): 0.0936

# distilbert model trained of base papers's dataset and testing on HC3 dataset(2k datapoints).

In [17]:

class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
# train_dataset = TextDataset(train_df)
# ****** we are using total 2000 data points in testing dataset *********
test_dataset = TextDataset(df_HC3)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [18]:
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report

# Load the saved model weights
# ensemble_model.load_state_dict(torch.load('/kaggle/input/2_epoch_mix_model/other/default/1/our_ensemble_model.pth'))
distil_model.eval()

# DataLoader for the test dataset
# test_loader = DataLoader(df_HC3, batch_size=2, shuffle=False)
# Evaluate the model on the new dataset


print("Evaluating the model on the HC3 dataset...")
all_labels = []
all_predictions = []

with torch.no_grad():
    for texts, labels in test_loader:
        texts = list(texts)
        labels = labels.to("cuda")

        outputs = distil_model(texts)
        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Classification report
print("Classification Report:")
print(classification_report(all_labels, all_predictions))

# Calculate F1 Score, FNR, and FPR
f1 = f1_score(all_labels, all_predictions, average='weighted')
cm = confusion_matrix(all_labels, all_predictions)
tn, fp, fn, tp = cm.ravel()
fnr = fn / (fn + tp)
fpr = fp / (fp + tn)

print(f"F1 Score: {f1:.4f}")
print(f"False Negative Rate (FNR): {fnr:.4f}")
print(f"False Positive Rate (FPR): {fpr:.4f}")

Evaluating the model on the HC3 dataset...
Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.92      0.94      1000
           1       0.92      0.97      0.94      1000

    accuracy                           0.94      2000
   macro avg       0.94      0.94      0.94      2000
weighted avg       0.94      0.94      0.94      2000

F1 Score: 0.9430
False Negative Rate (FNR): 0.0290
False Positive Rate (FPR): 0.0850

# 2. Roberta

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import torch.optim as optim
from transformers import RobertaModel, RobertaTokenizer

# Assuming 'df' is your dataset with columns ['text', 'label']
# Split the dataset into training and testing sets
print("Splitting the dataset into training and testing sets...")
train_df, test_df = train_test_split(paper_dataframe, test_size=0.2, random_state=42)
print(f"Training set size: {len(train_df)}, Testing set size: {len(test_df)}")

class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        # Extract the text and label from the dataframe
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Create datasets for training and testing
print("Creating datasets...")
train_dataset = TextDataset(train_df)
test_dataset = TextDataset(test_df)

# Create data loaders for batching
print("Creating data loaders...")
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

class Sentinel(nn.Module):
    def __init__(self, roberta: RobertaModel, tokenizer: RobertaTokenizer) -> None:
        super().__init__()
        self.roberta = roberta
        # Freeze the parameters of the Roberta model
        for param in self.roberta.parameters():
            param.requires_grad = False
        self.tokenizer = tokenizer

        # Define a fully connected layer for classification
        self.fc = nn.Sequential(
            nn.Linear(768, 768),
            nn.GELU(), nn.Dropout(0.25),
            nn.Linear(768, 2)
        )

    def forward(self, textBatch) -> torch.Tensor:
        # Tokenize and encode the text batch
        encodedText = self.tokenizer(
            textBatch, max_length=512, truncation=True,
            padding="max_length", return_tensors="pt"
        ).to("cuda")

        # Get the last hidden states from Roberta
        lastHiddenStates = self.roberta(**encodedText).last_hidden_state
        # Pass through the fully connected layer to get logits
        logits = self.fc(lastHiddenStates[:, 0, :])
        return logits

# Load the pretrained Roberta model and tokenizer
print("Loading Roberta model and tokenizer...")
roberta_model = RobertaModel.from_pretrained('roberta-base')
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

# Initialize the Sentinel model
print("Initializing the Sentinel model...")
roberta_model = Sentinel(roberta_model, tokenizer).to("cuda")

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(roberta_model.parameters(), lr=1e-4)

# Set the number of epochs for training
num_epochs = 3
roberta_model.train()

print("Starting training...")
for epoch in range(num_epochs):
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for texts, labels in train_loader:
        # Convert texts to a list and move labels to GPU
        texts = list(texts)
        labels = labels.to("cuda")

        # Zero the gradients
        optimizer.zero_grad()
        # Forward pass
        outputs = roberta_model(texts)
        # Compute the loss
        loss = criterion(outputs, labels)
        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        # Accumulate the loss
        running_loss += loss.item()
        # Calculate the number of correct predictions
        _, predicted = torch.max(outputs, 1)
        correct_predictions += (predicted == labels).sum().item()
        total_predictions += labels.size(0)

    # Calculate average loss and accuracy for the epoch
    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = correct_predictions / total_predictions
    print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")

print("Training complete")

# Save the trained model to a file
print("Saving the model...")
torch.save(roberta_model.state_dict(), 'roberta_sentinel.pth')
print("Model saved as 'roberta_sentinel.pth'")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Splitting the dataset into training and testing sets...
Training set size: 24000, Testing set size: 6000
Creating datasets...
Creating data loaders...
Loading Roberta model and tokenizer...
Initializing the Sentinel model...
Starting training...
Epoch 1/3, Loss: 0.5156, Accuracy: 0.8241
Epoch 2/3, Loss: 0.3138, Accuracy: 0.8967
Epoch 3/3, Loss: 0.2650, Accuracy: 0.9058
Training complete
Saving the model...
Model saved as 'roberta_sentinel.pth'

In [21]:
# Step 5: Evaluate on the test set
roberta_model.eval()
all_labels = []
all_predictions = []

with torch.no_grad():
    for texts, labels in test_loader:
        texts = list(texts)
        labels = labels.to("cuda")

        outputs = roberta_model(texts)
        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Classification report
print("Classification Report:")
print(classification_report(all_labels, all_predictions))

# Calculate F1 Score, FNR, and FPR
f1 = f1_score(all_labels, all_predictions, average='weighted')
cm = confusion_matrix(all_labels, all_predictions)
tn, fp, fn, tp = cm.ravel()
fnr = fn / (fn + tp)
fpr = fp / (fp + tn)

print(f"F1 Score: {f1:.4f}")
print(f"False Negative Rate (FNR): {fnr:.4f}")
print(f"False Positive Rate (FPR): {fpr:.4f}")

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.85      0.91      2909
           1       0.87      0.98      0.92      3091

    accuracy                           0.91      6000
   macro avg       0.92      0.91      0.91      6000
weighted avg       0.92      0.91      0.91      6000

F1 Score: 0.9138
False Negative Rate (FNR): 0.0210
False Positive Rate (FPR): 0.1543

# Roberta model on base paper's dataset and testing on our dataset(5k datapoints)

In [22]:
# ai_df = pd.read_csv("/kaggle/input/3500-datapoints/updated_dataset.csv", encoding='ISO-8859-1')
# ai_df = ai_df.replace({'\r': '', '\n': ''}, regex=True)
# filtered_df = ai_df[ai_df['ai_generated_text'].notna()]
# human_df = pd.DataFrame(filtered_df['text'])
# ai_df = pd.DataFrame(filtered_df['ai_generated_text'])
# ai_df['ai_generated_text'] = ai_df['ai_generated_text'].apply(preprocess_text)
# ai_df.rename(columns = {'ai_generated_text':'text'}, inplace = True)
# human_df['label'] = 0
# ai_df['label'] = 1
# my_df = pd.concat([human_df[:1000], ai_df[:1000]], ignore_index=True)


my_df= my_df[:5000]



class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
# train_dataset = TextDataset(train_df)
test_dataset = TextDataset(my_df)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [23]:
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report

# Load the saved model weights
# ensemble_model.load_state_dict(torch.load('/kaggle/working/roberta_sentinel.pth'))

roberta_model.eval()

# DataLoader for the test dataset
# test_loader = DataLoader(df_HC3, batch_size=2, shuffle=False)

# Function to test the model on the test data
# Evaluate the model on the new dataset
print("Evaluating the Roberta model on the our dataset...")
all_labels = []
all_predictions = []

with torch.no_grad():
    for texts, labels in test_loader:
        texts = list(texts)
        labels = labels.to("cuda")

        outputs = roberta_model(texts)
        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Classification report
print("Classification Report:")
print(classification_report(all_labels, all_predictions))

# Calculate F1 Score, FNR, and FPR
f1 = f1_score(all_labels, all_predictions, average='weighted')
cm = confusion_matrix(all_labels, all_predictions)
tn, fp, fn, tp = cm.ravel()
fnr = fn / (fn + tp)
fpr = fp / (fp + tn)

print(f"F1 Score: {f1:.4f}")
print(f"False Negative Rate (FNR): {fnr:.4f}")
print(f"False Positive Rate (FPR): {fpr:.4f}")

Evaluating the Roberta model on the our dataset...
Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.40      0.54      2501
           1       0.60      0.90      0.72      2499

    accuracy                           0.65      5000
   macro avg       0.70      0.65      0.63      5000
weighted avg       0.70      0.65      0.63      5000

F1 Score: 0.6276
False Negative Rate (FNR): 0.1008
False Positive Rate (FPR): 0.5978

# Roberta model trained on base dataset and testing on HC3 dataset(2k datapoints).

In [24]:
# # !pip install datasets
# from datasets import load_dataset

# ds = load_dataset("Hello-SimpleAI/HC3", "all")

# # Concatenate inner lists into a single string for each element
# concatenated = [' '.join(text_list) for text_list in ds['train']['human_answers']]

# # Create a DataFrame with a single column named 'text'
# df_human_hc3 = pd.DataFrame(concatenated, columns=['text'])
# df_human_hc3['label'] = 0
# df_human_hc3 = df_human_hc3[:1000]


# concatenated_ = [' '.join(text_list) for text_list in ds['train']['chatgpt_answers']]

# # Create a DataFrame with a single column named 'text'
# df_ai_hc3 = pd.DataFrame(concatenated_, columns=['text'])
# df_ai_hc3['label'] = 1
# df_ai_hc3 = df_ai_hc3[:1000]



# df_HC3 = pd.concat([df_ai_hc3, df_human_hc3], ignore_index=True)
# df_HC3 = df_HC3[:100]

class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
# train_dataset = TextDataset(train_df)
test_dataset = TextDataset(df_HC3)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [25]:
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report

# Load the saved model weights
# ensemble_model.load_state_dict(torch.load('/kaggle/input/2_epoch_mix_model/other/default/1/our_ensemble_model.pth'))

roberta_model.eval()

# DataLoader for the test dataset
# test_loader = DataLoader(df_HC3, batch_size=2, shuffle=False)

# Evaluate the model on the new dataset
print("Evaluating the Roberta model on the HC3 dataset...")
all_labels = []
all_predictions = []

with torch.no_grad():
    for texts, labels in test_loader:
        texts = list(texts)
        labels = labels.to("cuda")

        outputs = roberta_model(texts)
        _, predicted = torch.max(outputs, 1)

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted.cpu().numpy())

# Classification report
print("Classification Report:")
print(classification_report(all_labels, all_predictions))

# Calculate F1 Score, FNR, and FPR
f1 = f1_score(all_labels, all_predictions, average='weighted')
cm = confusion_matrix(all_labels, all_predictions)
tn, fp, fn, tp = cm.ravel()
fnr = fn / (fn + tp)
fpr = fp / (fp + tn)

print(f"F1 Score: {f1:.4f}")
print(f"False Negative Rate (FNR): {fnr:.4f}")
print(f"False Positive Rate (FPR): {fpr:.4f}")

Evaluating the Roberta model on the HC3 dataset...
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1000
           1       1.00      1.00      1.00      1000

    accuracy                           1.00      2000
   macro avg       1.00      1.00      1.00      2000
weighted avg       1.00      1.00      1.00      2000

F1 Score: 0.9995
False Negative Rate (FNR): 0.0010
False Positive Rate (FPR): 0.0000

# 3. T5

In [26]:
import torch
import torch.nn as nn
from transformers import AutoTokenizer, T5ForConditionalGeneration
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
import pandas as pd
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm


# Split into training and testing datasets
train_df, test_df = train_test_split(paper_dataframe, test_size=0.2, random_state=42)

class TextDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_len):
        self.data = dataframe
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        text = self.data.iloc[index]['text']
        label = self.data.iloc[index]['label']
        return text, label

    def collate_fn(self, batch):
        texts, labels = zip(*batch)
        encoded_texts = self.tokenizer.batch_encode_plus(
            texts, max_length=self.max_len, truncation=True, padding="max_length", return_tensors="pt"
        )
        labels = torch.tensor(labels)
        return encoded_texts.input_ids, encoded_texts.attention_mask, labels

class BinaryClassifier(nn.Module):
    def __init__(self, model_name="t5-small"):
        super().__init__()
        self.t5 = T5ForConditionalGeneration.from_pretrained(model_name)
        self.classifier = nn.Linear(self.t5.config.d_model, 2)

    def forward(self, input_ids, attention_mask):
        outputs = self.t5.encoder(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.last_hidden_state.mean(dim=1)
        logits = self.classifier(pooled_output)
        return logits

# Model, Optimizer, and Loss Setup
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BinaryClassifier().to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

# DataLoader Setup
tokenizer = AutoTokenizer.from_pretrained("t5-small")
train_dataset = TextDataset(train_df, tokenizer, max_len=512)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, collate_fn=train_dataset.collate_fn)
test_dataset = TextDataset(test_df, tokenizer, max_len=512)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, collate_fn=test_dataset.collate_fn)

def train(model, dataloader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    all_preds = []
    all_labels = []

    progress_bar = tqdm(dataloader, desc="Training")
    for input_ids, attention_mask, labels in progress_bar:
        input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

        optimizer.zero_grad()
        logits = model(input_ids, attention_mask)
        loss = criterion(logits, labels)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        preds = torch.argmax(logits, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

        accuracy = accuracy_score(labels.cpu().numpy(), preds.cpu().numpy())
        progress_bar.set_postfix({'loss': f'{loss.item():.4f}', 'acc': f'{accuracy:.4f}'})

    epoch_loss = total_loss / len(dataloader)
    epoch_accuracy = accuracy_score(all_labels, all_preds)
    epoch_f1 = f1_score(all_labels, all_preds, average='weighted')

    return epoch_loss, epoch_accuracy, epoch_f1

def evaluate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for input_ids, attention_mask, labels in tqdm(dataloader, desc="Evaluating"):
            input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

            logits = model(input_ids, attention_mask)
            loss = criterion(logits, labels)

            total_loss += loss.item()

            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    epoch_loss = total_loss / len(dataloader)
    epoch_accuracy = accuracy_score(all_labels, all_preds)
    epoch_f1 = f1_score(all_labels, all_preds, average='weighted')

    return epoch_loss, epoch_accuracy, epoch_f1

# Training and Evaluation
epochs = 3
for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")
    train_loss, train_accuracy, train_f1 = train(model, train_loader, optimizer, criterion, device)
    test_loss, test_accuracy, test_f1 = evaluate(model, test_loader, criterion, device)

    print(f"Train - Loss: {train_loss:.4f}, Accuracy: {train_accuracy:.4f}, F1: {train_f1:.4f}")
    print(f"Test  - Loss: {test_loss:.4f}, Accuracy: {test_accuracy:.4f}, F1: {test_f1:.4f}")
    print("-" * 50)

# Save the trained model
print("Saving the model...")
torch.save(model.state_dict(), 't5_sentinel.pth')
print("Model saved as 't5_sentinel.pth'")

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Epoch 1/3

Training: 100%|██████████| 1500/1500 [10:36<00:00,  2.36it/s, loss=0.0633, acc=1.0000]
Evaluating: 100%|██████████| 375/375 [00:59<00:00,  6.33it/s]

Train - Loss: 0.2719, Accuracy: 0.9017, F1: 0.9016
Test  - Loss: 0.1107, Accuracy: 0.9612, F1: 0.9612
--------------------------------------------------
Epoch 2/3

Training: 100%|██████████| 1500/1500 [10:37<00:00,  2.35it/s, loss=0.1159, acc=0.9375]
Evaluating: 100%|██████████| 375/375 [00:59<00:00,  6.31it/s]

Train - Loss: 0.0959, Accuracy: 0.9671, F1: 0.9671
Test  - Loss: 0.0835, Accuracy: 0.9720, F1: 0.9720
--------------------------------------------------
Epoch 3/3

Training: 100%|██████████| 1500/1500 [10:37<00:00,  2.35it/s, loss=0.0074, acc=1.0000]
Evaluating: 100%|██████████| 375/375 [00:59<00:00,  6.35it/s]

Train - Loss: 0.0716, Accuracy: 0.9758, F1: 0.9758
Test  - Loss: 0.1017, Accuracy: 0.9675, F1: 0.9675
--------------------------------------------------
Saving the model...
Model saved as 't5_sentinel.pth'

In [27]:
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
# import torch
# from torch.utils.data import Dataset, DataLoader
# import torch.nn as nn
# import torch.optim as optim
# from transformers import T5ForConditionalGeneration, T5Tokenizer

# # Assuming 'df' is your dataset with columns ['text', 'label']
# # Split the dataset into training and testing sets
# print("Splitting the dataset into training and testing sets...")
# train_df, test_df = train_test_split(paper_dataframe, test_size=0.2, random_state=42)
# print(f"Training set size: {len(train_df)}, Testing set size: {len(test_df)}")

# class TextDataset(Dataset):
#     def __init__(self, dataframe):
#         self.dataframe = dataframe

#     def __len__(self):
#         return len(self.dataframe)

#     def __getitem__(self, idx):
#         # Extract the text and label from the dataframe
#         text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
#         label = str(self.dataframe.iloc[idx, 1])  # convert label to string for T5
#         return text, label

# # Create datasets for training and testing
# print("Creating datasets...")
# train_dataset = TextDataset(train_df)
# test_dataset = TextDataset(test_df)

# # Create data loaders for batching
# print("Creating data loaders...")
# train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
# test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

# class T5Sentinel(nn.Module):
#     def __init__(self, t5_model: T5ForConditionalGeneration, tokenizer: T5Tokenizer) -> None:
#         super().__init__()
#         self.t5 = t5_model
#         self.tokenizer = tokenizer

#     def forward(self, text_batch, labels=None):
#         # Tokenize and encode the text batch
#         encoded_input = self.tokenizer(
#             text_batch, max_length=512, truncation=True,
#             padding="max_length", return_tensors="pt"
#         ).to(self.t5.device)

#         # Prepare target labels as text, e.g., "0" or "1"
#         if labels is not None:
#             encoded_labels = self.tokenizer(
#                 labels, max_length=2, truncation=True, 
#                 padding="max_length", return_tensors="pt"
#             ).input_ids.to(self.t5.device)
#         else:
#             encoded_labels = None

#         # Get the model output (logits for the sequence)
#         output = self.t5(
#             input_ids=encoded_input['input_ids'],
#             attention_mask=encoded_input['attention_mask'],
#             labels=encoded_labels
#         )

#         return output

# # Load the pretrained T5 model and tokenizer
# print("Loading T5 model and tokenizer...")
# t5_model = T5ForConditionalGeneration.from_pretrained('t5-small')
# tokenizer = T5Tokenizer.from_pretrained('t5-small')

# # Initialize the T5Sentinel model
# print("Initializing the T5Sentinel model...")
# t5_model = T5Sentinel(t5_model, tokenizer).to("cuda")

# # Define the loss function and optimizer
# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(t5_model.parameters(), lr=1e-4)

# # Set the number of epochs for training
# num_epochs = 10
# t5_model.train()

# print("Starting training...")
# for epoch in range(num_epochs):
#     running_loss = 0.0
#     correct_predictions = 0
#     total_predictions = 0

#     for texts, labels in train_loader:
#         # Convert texts to a list and move labels to GPU
#         texts = list(texts)
#         labels = [str(label) for label in labels]  # Convert integer labels to strings

#         # Zero the gradients
#         optimizer.zero_grad()
#         # Forward pass with the model
#         outputs = t5_model(texts, labels)
#         # Compute the loss using logits and labels
#         loss = outputs.loss
#         # Backward pass and optimization
#         loss.backward()
#         optimizer.step()

#         # Accumulate the loss
#         running_loss += loss.item()

#         # Generate predictions by decoding the output
#         generated_tokens = outputs.logits.argmax(dim=-1)
#         predictions = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

#         # Compare predictions with labels for accuracy
#         correct_predictions += sum(p.strip() == l for p, l in zip(predictions, labels))
#         total_predictions += len(labels)

#     # Calculate average loss and accuracy for the epoch
#     epoch_loss = running_loss / len(train_loader)
#     epoch_accuracy = correct_predictions / total_predictions
#     print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")

# print("Training complete")


# # Save the trained model to a file
# print("Saving the model...")
# torch.save(t5_model.state_dict(), 't5_sentinel.pth')
# print("Model saved as 't5_sentinel.pth'")

In [28]:
# t5_model.eval()

# # Evaluate the model on the new dataset
# def evaluate(model, dataloader, device):
#     model.eval()
#     all_preds = []
#     all_labels = []

#     with torch.no_grad():
#         for input_ids, attention_mask, labels in tqdm(dataloader, desc="Evaluating"):
#             input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

#             logits = model(input_ids, attention_mask)
#             preds = torch.argmax(logits, dim=1)

#             all_preds.extend(preds.cpu().numpy())
#             all_labels.extend(labels.cpu().numpy())

#     accuracy = accuracy_score(all_labels, all_preds)
#     f1 = f1_score(all_labels, all_preds, average='weighted')
#     report = classification_report(all_labels, all_preds)

#     return accuracy, f1, report

# # Run the evaluation
# print("Evaluating the model on the new dataset...")
# accuracy, f1, report = evaluate(t5_model, test_loader, device)

# # Print the evaluation results
# print(f"Accuracy: {accuracy:.4f}")
# print(f"F1 Score: {f1:.4f}")
# print("Classification Report:")
# print(report)

In [29]:
# import torch
# from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
# from torch.utils.data import DataLoader

# # Load the trained model
# print("Loading the trained T5 model...")
# t5_model = T5Sentinel(t5_model=T5ForConditionalGeneration.from_pretrained('t5-small'), tokenizer=T5Tokenizer.from_pretrained('t5-small'))
# t5_model.load_state_dict(torch.load('t5_sentinel.pth'))
# t5_model.to("cuda")
# t5_model.eval()

# # Create a DataLoader for the test dataset
# test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)

# all_labels = []
# all_predictions = []

# with torch.no_grad():
#     print("Evaluating the model on the test dataset...")
#     for texts, labels in test_loader:
#         texts = list(texts)  # Convert to list if needed
#         labels = [str(label) for label in labels]  # Ensure labels are strings

#         # Tokenize and encode the input texts for the T5 model
#         encoded_input = t5_model.tokenizer(
#             texts, max_length=512, truncation=True,
#             padding="max_length", return_tensors="pt"
#         ).to(t5_model.t5.device)  # Move input to the same device as the model

#         # Get model predictions
#         outputs = t5_model(
#             input_ids=encoded_input['input_ids'],
#             attention_mask=encoded_input['attention_mask']
#         )

#         # Generate predictions by decoding the output
#         generated_tokens = outputs.logits.argmax(dim=-1)
#         predictions = t5_model.tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)

#         all_labels.extend(labels)  # Add true labels to the list
#         all_predictions.extend(predictions)  # Add predicted labels to the list

# # Generate the classification report
# print("Classification Report:")
# print(classification_report(all_labels, all_predictions))

# # Calculate accuracy and F1 score
# accuracy = accuracy_score(all_labels, all_predictions)
# f1 = f1_score(all_labels, all_predictions, average='weighted')
# cm = confusion_matrix(all_labels, all_predictions)
# tn, fp, fn, tp = cm.ravel() if cm.size == 4 else (0, 0, 0, 0)  # Handle binary classification

# # Calculate FNR and FPR
# fnr = fn / (fn + tp) if (fn + tp) > 0 else 0  # Avoid division by zero
# fpr = fp / (fp + tn) if (fp + tn) > 0 else 0  # Avoid division by zero

# # Print metrics
# print(f"Accuracy: {accuracy:.4f}")
# print(f"F1 Score: {f1:.4f}")
# print(f"False Negative Rate (FNR): {fnr:.4f}")
# print(f"False Positive Rate (FPR): {fpr:.4f}")

# T5 model on their dataset and testing on our dataset

In [30]:
# # ai_df = pd.read_csv("/kaggle/input/3500-datapoints/updated_dataset.csv", encoding='ISO-8859-1')
# # ai_df = ai_df.replace({'\r': '', '\n': ''}, regex=True)
# # filtered_df = ai_df[ai_df['ai_generated_text'].notna()]
# # human_df = pd.DataFrame(filtered_df['text'])
# # ai_df = pd.DataFrame(filtered_df['ai_generated_text'])
# # ai_df['ai_generated_text'] = ai_df['ai_generated_text'].apply(preprocess_text)
# # ai_df.rename(columns = {'ai_generated_text':'text'}, inplace = True)
# # human_df['label'] = 0
# # ai_df['label'] = 1
# # my_df = pd.concat([human_df[:1000], ai_df[:1000]], ignore_index=True)



# my_df=my_df[:2000]

# class TextDataset(Dataset):
#     def __init__(self, dataframe):
#         self.dataframe = dataframe

#     def __len__(self):
#         return len(self.dataframe)

#     def __getitem__(self, idx):
#         text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
#         label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
#         return text, label

# # Data Loaders
# # train_dataset = TextDataset(train_df)
# test_dataset = TextDataset(my_df)

# # train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
# test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [31]:
# import torch
# from torch.utils.data import DataLoader
# from sklearn.metrics import classification_report

# # Load the saved model weights
# # ensemble_model.load_state_dict(torch.load('/kaggle/working/t5_sentinel.pth'))
# t5_model.eval()

# # DataLoader for the test dataset
# # test_loader = DataLoader(df_HC3, batch_size=2, shuffle=False)

# # Function to test the model on the test data
# # Evaluate the model on the new dataset
# print("Evaluating the T5 model on the our dataset...")
# all_labels = []
# all_predictions = []

# with torch.no_grad():
#     for texts, labels in test_loader:
#         texts = list(texts)
#         labels = labels.to("cuda")

#         outputs = t5_model(texts)
#         _, predicted = torch.max(outputs, 1)

#         all_labels.extend(labels.cpu().numpy())
#         all_predictions.extend(predicted.cpu().numpy())

# # Classification report
# print("Classification Report:")
# print(classification_report(all_labels, all_predictions))

# # Calculate F1 Score, FNR, and FPR
# f1 = f1_score(all_labels, all_predictions, average='weighted')
# cm = confusion_matrix(all_labels, all_predictions)
# tn, fp, fn, tp = cm.ravel()
# fnr = fn / (fn + tp)
# fpr = fp / (fp + tn)

# print(f"F1 Score: {f1:.4f}")
# print(f"False Negative Rate (FNR): {fnr:.4f}")
# print(f"False Positive Rate (FPR): {fpr:.4f}")

# T5 model trained on their dataset and testing on HC3 dataset

In [32]:
# # # !pip install datasets
# # from datasets import load_dataset

# # ds = load_dataset("Hello-SimpleAI/HC3", "all")

# # # Concatenate inner lists into a single string for each element
# # concatenated = [' '.join(text_list) for text_list in ds['train']['human_answers']]

# # # Create a DataFrame with a single column named 'text'
# # df_human_hc3 = pd.DataFrame(concatenated, columns=['text'])
# # df_human_hc3['label'] = 0
# # df_human_hc3 = df_human_hc3[:1000]


# # concatenated_ = [' '.join(text_list) for text_list in ds['train']['chatgpt_answers']]

# # # Create a DataFrame with a single column named 'text'
# # df_ai_hc3 = pd.DataFrame(concatenated_, columns=['text'])
# # df_ai_hc3['label'] = 1
# # df_ai_hc3 = df_ai_hc3[:1000]



# # df_HC3 = pd.concat([df_ai_hc3, df_human_hc3], ignore_index=True)
# # # df_HC3 = df_HC3[:100]

# class TextDataset(Dataset):
#     def __init__(self, dataframe):
#         self.dataframe = dataframe

#     def __len__(self):
#         return len(self.dataframe)

#     def __getitem__(self, idx):
#         text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
#         label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
#         return text, label

# # Data Loaders
# # train_dataset = TextDataset(train_df)
# test_dataset = TextDataset(df_HC3)

# # train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
# test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [33]:
# import torch
# from torch.utils.data import DataLoader
# from sklearn.metrics import classification_report

# # Load the saved model weights
# # ensemble_model.load_state_dict(torch.load('/kaggle/input/2_epoch_mix_model/other/default/1/our_ensemble_model.pth'))
# t5_model.eval()

# # DataLoader for the test dataset
# # test_loader = DataLoader(df_HC3, batch_size=2, shuffle=False)

# # Evaluate the model on the new dataset
# print("Evaluating the T5 model on the HC3 dataset...")
# all_labels = []
# all_predictions = []

# with torch.no_grad():
#     for texts, labels in test_loader:
#         texts = list(texts)
#         labels = labels.to("cuda")

#         outputs = t5_model(texts)
#         _, predicted = torch.max(outputs, 1)

#         all_labels.extend(labels.cpu().numpy())
#         all_predictions.extend(predicted.cpu().numpy())

# # Classification report
# print("Classification Report:")
# print(classification_report(all_labels, all_predictions))

# # Calculate F1 Score, FNR, and FPR
# f1 = f1_score(all_labels, all_predictions, average='weighted')
# cm = confusion_matrix(all_labels, all_predictions)
# tn, fp, fn, tp = cm.ravel()
# fnr = fn / (fn + tp)
# fpr = fp / (fp + tn)

# print(f"F1 Score: {f1:.4f}")
# print(f"False Negative Rate (FNR): {fnr:.4f}")
# print(f"False Positive Rate (FPR): {fpr:.4f}")

# Our code

### Mukund's code

In [ ]:
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from transformers import RobertaModel, RobertaTokenizer, T5ForConditionalGeneration, T5Tokenizer
# from sklearn.model_selection import train_test_split
# from torch.utils.data import DataLoader, Dataset
# from tqdm import tqdm

# # Assuming 'df' is your dataset with columns ['text', 'label']
# train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# # Dataset Class
# class TextDataset(Dataset):
#     def __init__(self, dataframe):
#         self.dataframe = dataframe

#     def __len__(self):
#         return len(self.dataframe)

#     def __getitem__(self, idx):
#         text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
#         label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
#         return text, label

# # Data Loaders
# train_dataset = TextDataset(train_df)
# test_dataset = TextDataset(test_df)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
# test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

# # Function to process chunks and compute weighted probabilities for both models
# def process_chunks(model, tokenizer, texts, classifier, name, max_length=512, max_chunks=4):
#     encoded_texts = tokenizer(
#         texts,
#         truncation=False,
#         padding=True,
#         return_tensors="pt"
#     )

#     input_ids = encoded_texts['input_ids'].cuda()
#     attention_mask = encoded_texts['attention_mask'].cuda()

#     batch_probs = []
#     for i in range(len(input_ids)):
#         input_id = input_ids[i]
#         attention_mask_i = attention_mask[i]
        
#         # print(f"Input text {i} for {name}: {texts[i]}")
        
#         print(f"Processing text {i} with input IDs and attention mask for {name}")
# #         print(f"Text {i}: input IDs : {input_id}")

#         print(f"Text {i}: input IDs shape: {input_id.shape}")

#         # Split the input into chunks of 512 tokens
#         chunks = [input_id[j:j + 512] for j in range(0, len(input_id), 512)]
#         attention_chunks = [attention_mask_i[j:j + 512] for j in range(0, len(input_id), 512)]

#         print(f"Text {i}: number of chunks: {len(chunks)}")  # Debugging line
        
#         if len(chunks) > max_chunks:
#             chunks = chunks[:max_chunks]
#             attention_chunks = attention_chunks[:max_chunks]

#         last_chunk_size = len(chunks[-1])
#         print(f"Last chunk size for text {i}: {last_chunk_size}")  # Debugging line
        
#         if last_chunk_size < 512:
#             padding_length = 512 - last_chunk_size
#             chunks[-1] = torch.cat([chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])
#             attention_chunks[-1] = torch.cat([attention_chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])

#         chunk_probs = []
#         for chunk, mask in zip(chunks, attention_chunks):
#             chunk = chunk.unsqueeze(0).cuda()
#             mask = mask.unsqueeze(0).cuda()

#             # print(f"Getting output from {name} for chunk...")

#             # Get model outputs
#             outputs = model(input_ids=chunk, attention_mask=mask)
#             cls_output = outputs.last_hidden_state[:, 0, :]
#             # print(f"CLS output shape for {name} chunk: {cls_output.shape}")

#             logits = classifier(cls_output)
#             # print(f"Logits from classifier for {name} chunk: {logits}")

#             probabilities = torch.sigmoid(logits)
#             # print(f"Probabilities for {name} chunk: {probabilities}")

#             chunk_probs.append(probabilities)

#         chunk_probs = torch.cat(chunk_probs, dim=0)  # Shape: (num_chunks, 1)
#         # print(f"All chunk probabilities for {name} text {i}: {chunk_probs}")

#         chunk_weights = torch.ones(len(chunks), dtype=torch.float).cuda() * 512
#         chunk_weights[-1] = last_chunk_size
#         chunk_weights = chunk_weights / 512
#         # print(f"Chunk weights for {name} text {i}: {chunk_weights}")

#         weighted_probs = torch.sum(chunk_probs.squeeze() * chunk_weights) / torch.sum(chunk_weights)
#         # print(f"Weighted average probability for {name} text {i}: {weighted_probs}")

#         batch_probs.append(weighted_probs)

#     final_probs = torch.stack(batch_probs)  # Shape: (batch_size,)
#     # print(f"Final probabilities for {name}: {final_probs}")
    
#     return final_probs

# # RoBERTa Model with classifier
# class RobertaSentinel(nn.Module):
#     def __init__(self):
#         super(RobertaSentinel, self).__init__()
#         self.roberta = RobertaModel.from_pretrained('roberta-base')
#         self.classifier = nn.Sequential(
#             nn.Linear(768, 768),
#             nn.ReLU(),
#             nn.Dropout(0.2),
#             nn.Linear(768, 512),
#             nn.ReLU(),
#             nn.Dropout(0.2),
#             nn.Linear(512, 64),
#             nn.ReLU(),
#             nn.Linear(64, 1)
#         )

#     def forward(self, texts, tokenizer):
#         probabilities = process_chunks(self.roberta, tokenizer, texts, self.classifier, 'roberta')
#         return probabilities

# # T5 Model with classifier
# class T5BinaryClassifier(nn.Module):
#     def __init__(self, model_name="t5-small"):
#         super(T5BinaryClassifier, self).__init__()
#         self.t5 = T5ForConditionalGeneration.from_pretrained(model_name)
#         self.classifier = nn.Linear(self.t5.config.d_model, 1)

#     def forward(self, texts, tokenizer):
#         probabilities = process_chunks(self.t5.encoder, tokenizer, texts, self.classifier, 'T5')
#         return probabilities

# # Initialize models and tokenizers
# roberta_model = RobertaSentinel().cuda()
# roberta_tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

# t5_model = T5BinaryClassifier().cuda()
# t5_tokenizer = T5Tokenizer.from_pretrained('t5-small')

# # Ensemble model class
# class EnsembleModel(nn.Module):
#     def __init__(self, roberta_model, t5_model, roberta_tokenizer, t5_tokenizer):
#         super(EnsembleModel, self).__init__()
#         self.roberta_model = roberta_model
#         self.t5_model = t5_model
#         self.roberta_tokenizer = roberta_tokenizer
#         self.t5_tokenizer = t5_tokenizer

#     def forward(self, texts):
#         # Get probabilities from both models
# #         print(f"texts is {texts}")
#         roberta_probs = self.roberta_model(texts, self.roberta_tokenizer)
#         print(f"RoBERTa probabilities: {roberta_probs}")
#         print(f"roberta part over")
        
        
#         # print(f"texts is {texts}")
#         t5_probs = self.t5_model(texts, self.t5_tokenizer)
#         print(f"T5 probabilities: {t5_probs}")
#         print(f"T5 part over")

#         # Assign weights for ensembling
#         roberta_weight = 0.5
#         t5_weight = 0.5
#         print(f"Weights: RoBERTa = {roberta_weight}, T5 = {t5_weight}")

# #         Compute weighted probabilities
#         weighted_probs = (roberta_weight * roberta_probs) + (t5_weight * t5_probs)
#         print(f"Weighted probabilities: {weighted_probs}")

#         return roberta_probs,t5_probs,weighted_probs

# # Initialize the ensemble model
# ensemble_model = EnsembleModel(roberta_model, t5_model, roberta_tokenizer, t5_tokenizer).cuda()

# # Loss and optimizer
# criterion = nn.BCEWithLogitsLoss()
# optimizer = optim.Adam(ensemble_model.parameters(), lr=1e-4)

# # Training loop
# num_epochs = 5
# ensemble_model.train()

# for epoch in range(num_epochs):
#     running_loss = 0.0
#     correct_predictions = 0
#     total_predictions = 0

#     for texts, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
#         texts = list(texts)  # Convert batch of texts to a list
#         labels = labels.to("cuda").float()

#         labels = labels.view(-1, 1)

#         optimizer.zero_grad()

#         # Forward pass through the ensemble model
#         roberta_probs,t5_probs,final_probs = ensemble_model(texts)

#         final_probs = final_probs.view(-1, 1)

#         # Compute the loss
#         loss = criterion(final_probs, labels)

#         # Backward pass and optimization
#         loss.backward()
#         optimizer.step()

#         running_loss += loss.item()
#         ones = [roberta_probs,t5_probs]
#         zeros = [1 - roberta_probs,1 - t5_probs]
        
#         max_ones = torch.max(ones[0], ones[1])  # Find max between (1 - roberta_probs) and (1 - t5_probs)
#         max_zeros = torch.max(zeros[0], zeros[1])  # Find max between roberta_probs and t5_probs
#         maxi = torch.max(max_ones,max_zeros)
#         predicted = (max_ones > 0.5).float()
#         correct_predictions += (predicted == labels).sum().item()
#         total_predictions += labels.size(0)

#         # Debugging logs
#         for i in range(labels.size(0)):
#             actual_class = labels[i].item()
#             final_prob = final_probs[i].item()
#             print(f"data point {i+1} : Actual Class: {actual_class}")
#             print(f"From Roberta for class 1 : {roberta_probs[i]}")
#             print(f"From Roberta for class 0 : { 1 - roberta_probs[i]}")
#             print(f"From T5 for class 1 : {t5_probs[i]}")
#             print(f"From T5 for class 0 : { 1 - t5_probs[i]}")
#             print(f"predicted class is : {predicted[i]}")
#             print(f"probability choosen is: {maxi[i]}")
            
# #             print(f"Data Point {i+1}: Actual Class: {actual_class}, Final Probability for class 1: {final_prob:.4f}, Prediction: {predicted[i].item()}")

#     epoch_loss = running_loss / len(train_loader)
#     epoch_accuracy = correct_predictions / total_predictions
#     print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")

### Himanshu's code

#### 1. Probabilties + logits 
* you don't have to run it. !!! Danger

In [ ]:
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from transformers import  T5ForConditionalGeneration, T5Tokenizer
# from transformers import DistilBertModel, DistilBertTokenizer

# from sklearn.model_selection import train_test_split
# from torch.utils.data import DataLoader, Dataset
# from tqdm import tqdm

# # Assuming 'df' is your dataset with columns ['text', 'label']
# train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# # Dataset Class
# class TextDataset(Dataset):
#     def __init__(self, dataframe):
#         self.dataframe = dataframe

#     def __len__(self):
#         return len(self.dataframe)

#     def __getitem__(self, idx):
#         text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
#         label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
#         return text, label

# # Data Loaders
# train_dataset = TextDataset(train_df)
# test_dataset = TextDataset(test_df)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
# test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

# # Function to process chunks and compute weighted probabilities for both models
# def process_chunks(model, tokenizer, texts, classifier, name, max_length=512, max_chunks=4):
#     encoded_texts = tokenizer(
#         texts,
#         truncation=False,
#         padding=True,
#         return_tensors="pt"
#     )

#     input_ids = encoded_texts['input_ids'].cuda()
#     attention_mask = encoded_texts['attention_mask'].cuda()

#     batch_probs = []
#     batch_logits = []
#     for i in range(len(input_ids)):
#         input_id = input_ids[i]
#         attention_mask_i = attention_mask[i]
        
#         # print(f"Input text {i} for {name}: {texts[i]}")
        
#         print(f"Processing text {i} with input IDs and attention mask for {name}")
# #         print(f"Text {i}: input IDs : {input_id}")

#         print(f"Text {i}: input IDs shape: {input_id.shape}")

#         # Split the input into chunks of 512 tokens
#         chunks = [input_id[j:j + 512] for j in range(0, len(input_id), 512)]
#         attention_chunks = [attention_mask_i[j:j + 512] for j in range(0, len(input_id), 512)]

#         print(f"Text {i}: number of chunks: {len(chunks)}")  # Debugging line
        
#         if len(chunks) > max_chunks:
#             chunks = chunks[:max_chunks]
#             attention_chunks = attention_chunks[:max_chunks]

#         last_chunk_size = len(chunks[-1])
#         print(f"Last chunk size for text {i}: {last_chunk_size}")  # Debugging line

#         if last_chunk_size < 512:
#             padding_length = 512 - last_chunk_size
#             chunks[-1] = torch.cat([chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])
#             attention_chunks[-1] = torch.cat([attention_chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])

#         chunk_probs = []
#         chunk_logits= []
#         for chunk, mask in zip(chunks, attention_chunks):
#             chunk = chunk.unsqueeze(0).cuda()
#             mask = mask.unsqueeze(0).cuda()

#             # print(f"Getting output from {name} for chunk...")

#             # Get model outputs
#             outputs = model(input_ids=chunk, attention_mask=mask)
#             cls_output = outputs.last_hidden_state[:, 0, :]
#             # print(f"CLS output shape for {name} chunk: {cls_output.shape}")

#             logits = classifier(cls_output)
#             chunk_logits.append(logits)
#             # print(f"Logits from classifier for {name} chunk: {logits}")

#             probabilities = torch.sigmoid(logits)
#             # print(f"Probabilities for {name} chunk: {probabilities}")
#             chunk_probs.append(probabilities)

#         chunk_probs = torch.cat(chunk_probs, dim=0)  # Shape: (num_chunks, 1)
#         print(f"All chunk probabilities for {name} text {i}: {chunk_probs}")

#         chunk_logits = torch.cat(chunk_logits, dim=0)
#         # print(f"All chunk logits for {name} text {i}: {chunk_logits}")


#         chunk_weights = torch.ones(len(chunks), dtype=torch.float).cuda() * 512
#         chunk_weights[-1] = last_chunk_size
#         chunk_weights = chunk_weights / 512
#         # print(f"Chunk weights for {name} text {i}: {chunk_weights}")
#         # calculate weighted probabilities
#         weighted_probs = torch.sum(chunk_probs.squeeze() * chunk_weights) / torch.sum(chunk_weights)
#         # print(f"Weighted probability for {name} text {i} : {weighted_probs}")
        
#         #calculate weighted logits(only use if needed other wise just use  mean of all logits)
#         weighted_logits = torch.sum(chunk_logits.squeeze() * chunk_weights) / torch.sum(chunk_weights)
#         ## weighted_logits = torch.mean(torch.stack(chunk_logits), dim=0)

#         batch_probs.append(weighted_probs)
#         batch_logits.append(weighted_logits)

#     final_probs = torch.stack(batch_probs)  # Shape: (batch_size,)
#     final_logits = torch.stack(batch_logits)
#     print(f"Final probabilities for {name}: {final_probs}")
    
#     return final_probs, final_logits

# # RoBERTa Model with classifier
# class DistilSentinel(nn.Module):
#     def __init__(self):
#         super(DistilSentinel, self).__init__()
#         self.distil = DistilBertModel.from_pretrained('distilbert-base-uncased')
#         self.classifier = nn.Sequential(
#             nn.Linear(768, 768),
#             nn.GELU(),
#             nn.Dropout(0.2),
#             nn.Linear(768, 1)
#         )

#     def forward(self, texts, tokenizer):
#         probabilities, logits = process_chunks(self.distil, tokenizer, texts, self.classifier, 'distilbert')
#         return probabilities, logits

# # T5 Model with classifier
# class T5BinaryClassifier(nn.Module):
#     def __init__(self, model_name="t5-small"):
#         super(T5BinaryClassifier, self).__init__()
#         self.t5 = T5ForConditionalGeneration.from_pretrained(model_name)
#         self.classifier = nn.Linear(self.t5.config.d_model, 1)

#     def forward(self, texts, tokenizer):
#         probabilities, logits = process_chunks(self.t5.encoder, tokenizer, texts, self.classifier, 'T5')
#         return probabilities, logits

# # Initialize models and tokenizers
# distil_model = DistilSentinel().cuda()
# distil_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# t5_model = T5BinaryClassifier().cuda()
# t5_tokenizer = T5Tokenizer.from_pretrained('t5-small')

# # Ensemble model class
# class EnsembleModel(nn.Module):
#     def __init__(self, distil_model, t5_model, distil_tokenizer, t5_tokenizer):
#         super(EnsembleModel, self).__init__()
#         self.distil_model = distil_model
#         self.t5_model = t5_model
#         self.distil_tokenizer = distil_tokenizer
#         self.t5_tokenizer = t5_tokenizer

#     def forward(self, texts):
#         # Get probabilities from both models
# #         print(f"texts is {texts}")
#         distil_probs, distil_logits = self.distil_model(texts, self.distil_tokenizer)
#         print(f"Distil probabilities: {distil_probs}")
#         # print(f"Distil logits: {distil_logits}")
#         print(f"Distiil part over")
        
        
#         # print(f"texts is {texts}")
#         t5_probs, t5_logits = self.t5_model(texts, self.t5_tokenizer)
#         print(f"T5 probabilities: {t5_probs}")
#         # print(f"T5 logits: {t5_logits}")
#         print(f"T5 part over")

#         # abb btao logits and probabs kak= kya krna hae

#         # weighted probs ki jrurt hin nhi hae kyuki isee hum loss mae use hinn nhi kr rhe. humiske jagah pe logitsuse krenge
# #         # Assign weights for ensembling
# #         distil_weight = 0.5
# #         t5_weight = 0.5
# #         print(f"Weights: distil = {distil_weight}, T5 = {t5_weight}")

# # #         Compute weighted probabilities
# #         weighted_probs = (distil_weight * distil_probs) + (t5_weight * t5_probs)
# #         print(f"Weighted probabilities: {weighted_probs}")

#         # here we have two options to check for final_logits
#         #1. take average of both logits. we can't take weighted because we want equal contribution from each model.
#         #2. we can try max logits in ditil and t5 logits

#         #Note: try one of the option at a time.
#         #1st method:
#         # final_logits = (distil_logits + t5_logits) / 2

#         #2nd method:
#         final_logits = torch.max(distil_logits, t5_logits)


#         return distil_probs,t5_probs,final_logits

# # Initialize the ensemble model
# ensemble_model = EnsembleModel(distil_model, t5_model, distil_tokenizer, t5_tokenizer).cuda()

# # Loss and optimizer
# criterion = nn.BCEWithLogitsLoss()
# optimizer = optim.Adam(ensemble_model.parameters(), lr=1e-4)

# # Training loop
# num_epochs = 5
# ensemble_model.train()

# for epoch in range(num_epochs):
#     running_loss = 0.0
#     correct_predictions = 0
#     total_predictions = 0

#     for texts, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
#         texts = list(texts)  # Convert batch of texts to a list
#         labels = labels.to("cuda").float()

#         labels = labels.view(-1, 1)

#         optimizer.zero_grad()

#         # Forward pass through the ensemble model
#         distil_probs,t5_probs,final_logits = ensemble_model(texts)

#         final_logits = final_logits.view(-1, 1)
#         # Ensure that labels and logits have the same shape
#         print(f"Labels shape: {labels.shape}, Final logits shape: {final_logits.shape}")

#         # Compute the loss
#         loss = criterion(final_logits, labels)

#         # Backward pass and optimization
#         loss.backward()
#         optimizer.step()

#         running_loss += loss.item()

#         # yeha pe check krna hae ki isme kitni probabs ki value ayegi
#         ones = [distil_probs, t5_probs]
#         zeros = [1 - distil_probs,1 - t5_probs]
#         print(f"ones probability values: {ones}")
#         print(f"zeros probability values: {zeros}")

        
#         max_ones = torch.max(ones[0], ones[1])  # Find max between (1 - roberta_probs) and (1 - t5_probs)
#         max_zeros = torch.max(zeros[0], zeros[1])  # Find max between roberta_probs and t5_probs

#         print(f"MaxOnes values: {max_ones}")
#         print(f"MaxZeros values: {max_zeros}")

#         maxi = torch.max(max_ones,max_zeros)
#         print(f"Maximum value: {maxi}")
#         # predicted = (max_ones > 0.5).float() # i don't know why we are taking max_ones. we should take maxi at place of max_ones
#         #predicted = (maxi > 0.5).float() # this is also bullshit man. 

#         # Compare max_ones and max_zeros to determine the predicted class.
#         # If max_ones > max_zeros, predict class 1; otherwise, predict class 0.
#         predicted = (max_ones > max_zeros).float()
        
#         correct_predictions += (predicted == labels).sum().item()
#         total_predictions += labels.size(0)

#         # Debugging logs
#         for i in range(labels.size(0)):
#             actual_class = labels[i].item()
#             # final_prob = final_probs[i].item()
#             print(f"data point {i+1} : Actual Class: {actual_class}")
#             print(f"From distil for class 1 : {distil_probs[i]}")
#             print(f"From distil for class 0 : { 1 - distil_probs[i]}")
#             print(f"From T5 for class 1 : {t5_probs[i]}")
#             print(f"From T5 for class 0 : { 1 - t5_probs[i]}")
#             print(f"predicted class is : {predicted[i]}")
#             print(f"probability choosen is: {maxi[i]}")
            
# #             print(f"Data Point {i+1}: Actual Class: {actual_class}, Final Probability for class 1: {final_prob:.4f}, Prediction: {predicted[i].item()}")

#     epoch_loss = running_loss / len(train_loader)
#     epoch_accuracy = correct_predictions / total_predictions
#     print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")

## Our Final Architecture

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from transformers import T5ForConditionalGeneration, T5Tokenizer
from transformers import DistilBertModel, DistilBertTokenizer

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

# Assuming 'df' is your dataset with columns ['text', 'label']
train_df, test_df = train_test_split(my_df, test_size=0.2, random_state=42)

# Dataset Class
class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
train_dataset = TextDataset(train_df)
test_dataset = TextDataset(test_df)

train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

# Function to process chunks and compute logits for both models
def process_chunks(model, tokenizer, texts, classifier, name, max_length=512, max_chunks=4):
    encoded_texts = tokenizer(
        texts,
        truncation=False,
        padding=True,
        return_tensors="pt"
    )

    input_ids = encoded_texts['input_ids'].cuda()
    attention_mask = encoded_texts['attention_mask'].cuda()

    batch_logits = []
    for i in range(len(input_ids)):
        input_id = input_ids[i]
        attention_mask_i = attention_mask[i]

        # Split the input into chunks of 512 tokens
        chunks = [input_id[j:j + 512] for j in range(0, len(input_id), 512)]
        attention_chunks = [attention_mask_i[j:j + 512] for j in range(0, len(input_id), 512)]

        if len(chunks) > max_chunks:
            chunks = chunks[:max_chunks]
            attention_chunks = attention_chunks[:max_chunks]

        last_chunk_size = len(chunks[-1])

        if last_chunk_size < 512:
            padding_length = 512 - last_chunk_size
            chunks[-1] = torch.cat([chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])
            attention_chunks[-1] = torch.cat([attention_chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])

        chunk_logits = []
        for chunk, mask in zip(chunks, attention_chunks):
            chunk = chunk.unsqueeze(0).cuda()
            mask = mask.unsqueeze(0).cuda()

            # Get model outputs
            outputs = model(input_ids=chunk, attention_mask=mask)
            cls_output = outputs.last_hidden_state[:, 0, :]

            logits = classifier(cls_output)
            chunk_logits.append(logits)

        chunk_logits = torch.cat(chunk_logits, dim=0)  # Shape: (num_chunks, 1)

        # Calculate weights based on chunk size
        chunk_weights = torch.ones(len(chunks), dtype=torch.float).cuda() * 512
        chunk_weights[-1] = last_chunk_size
        chunk_weights = chunk_weights / 512

        # Compute weighted logits
        weighted_logits = torch.sum(chunk_logits.squeeze() * chunk_weights) / torch.sum(chunk_weights)

        batch_logits.append(weighted_logits)

    final_logits = torch.stack(batch_logits)  # Shape: (batch_size,)
    return final_logits

# RoBERTa Model with classifier
class DistilSentinel(nn.Module):
    def __init__(self):
        super(DistilSentinel, self).__init__()
        self.distil = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.classifier = nn.Sequential(
            nn.Linear(768, 768),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(768, 1)
        )

    def forward(self, texts, tokenizer):
        logits = process_chunks(self.distil, tokenizer, texts, self.classifier, 'distilbert')
        return logits

# T5 Model with classifier
class T5BinaryClassifier(nn.Module):
    def __init__(self, model_name="t5-small"):
        super(T5BinaryClassifier, self).__init__()
        self.t5 = T5ForConditionalGeneration.from_pretrained(model_name)
        self.classifier = nn.Linear(self.t5.config.d_model, 1)

    def forward(self, texts, tokenizer):
        logits = process_chunks(self.t5.encoder, tokenizer, texts, self.classifier, 'T5')
        return logits

# Initialize models and tokenizers
distil_model = DistilSentinel().cuda()
distil_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

t5_model = T5BinaryClassifier().cuda()
t5_tokenizer = T5Tokenizer.from_pretrained('t5-small')

# Ensemble model class
class EnsembleModel(nn.Module):
    def __init__(self, distil_model, t5_model, distil_tokenizer, t5_tokenizer):
        super(EnsembleModel, self).__init__()
        self.distil_model = distil_model
        self.t5_model = t5_model
        self.distil_tokenizer = distil_tokenizer
        self.t5_tokenizer = t5_tokenizer

    def forward(self, texts):
        # Get logits from both models
        distil_logits = self.distil_model(texts, self.distil_tokenizer)
        t5_logits = self.t5_model(texts, self.t5_tokenizer)

        # Compute final logits as average
        final_logits = torch.max(distil_logits, t5_logits)

        return distil_logits, t5_logits, final_logits

# Initialize the ensemble model
ensemble_model = EnsembleModel(distil_model, t5_model, distil_tokenizer, t5_tokenizer).cuda()

# Loss and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(ensemble_model.parameters(), lr=1e-4)

# Training loop
num_epochs = 1
ensemble_model.train()

for epoch in range(num_epochs):
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for texts, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        texts = list(texts)  # Convert batch of texts to a list
        labels = labels.to("cuda").float()

        labels = labels.view(-1, 1)

        optimizer.zero_grad()

        # Forward pass through the ensemble model
        distil_logits, t5_logits, final_logits = ensemble_model(texts)
        final_logits = final_logits.view(-1, 1)
        # Compute the loss
        loss = criterion(final_logits, labels)

        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        
        # Make predictions
        predicted = (final_logits > 0).float()
        correct_predictions += (predicted == labels).sum().item()
        total_predictions += labels.size(0)

        # Debugging logs
        for i in range(labels.size(0)):
            actual_class = labels[i].item()
            final_prob = torch.sigmoid(final_logits[i]).item()
            print(f"Data point {i+1}: Actual Class: {actual_class}, Final Logit: {final_logits[i].item()}, Predicted Probability: {final_prob:.4f}, Prediction: {predicted[i].item()}")

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = correct_predictions / total_predictions
    print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")
# Save the model at the end of each epoch
print("Saving the ensemble model")
torch.save(ensemble_model.state_dict(), f'our_ensemble_model.pth')
print(f"Model saved as 'ensemble_model_epoch.pth'")

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

# Evaluation function
def evaluate_model(model, test_loader, criterion):
    model.eval()  # Set the model to evaluation mode
    all_labels = []
    all_predictions = []
    total_loss = 0.0

    with torch.no_grad():
        for texts, labels in tqdm(test_loader, desc="Evaluating"):
            texts = list(texts)  # Convert batch of texts to a list
            labels = labels.to("cuda").float().view(-1, 1)

            # Forward pass through the ensemble model
            distil_logits, t5_logits, final_logits = model(texts)
            final_logits = final_logits.view(-1, 1)

            # Compute the loss
            loss = criterion(final_logits, labels)
            total_loss += loss.item()

            # Make predictions
            predictions = (final_logits > 0).float()

            # Store the true labels and predictions
            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())

    # Compute average loss over the test set
    avg_loss = total_loss / len(test_loader)

    # Compute accuracy
    accuracy = accuracy_score(all_labels, all_predictions)

    # Generate classification report
    report = classification_report(all_labels, all_predictions, target_names=["Class 0", "Class 1"])

    print(f"Test Loss: {avg_loss:.4f}")
    print(f"Test Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(report)

    return avg_loss, accuracy, report

# Call the evaluation function
criterion = nn.BCEWithLogitsLoss()
test_loss, test_accuracy, classification_report = evaluate_model(ensemble_model, test_loader, criterion)

# Combining base paper dataset and our dataset.

In [34]:
# Define a function to preprocess each text
def preprocess_text(text):
    # Find the index of the first colon
    colon_index = text.find(':')
    # If a colon exists and is within the first 20 words, trim the text
    if colon_index != -1:
        # Get the words up to the colon's position
        words_before_colon = text[:colon_index].split()
        # Check if the colon is within the first 20 words
        if len(words_before_colon) <= 20:
            # Return the text after the colon, trimmed of leading/trailing spaces
            return text[colon_index + 1:].strip()
    # If no colon or colon is outside the first 20 words, return the original text
    return text

In [35]:
import pandas as pd

# Load the dataset
paper_dataframe = pd.read_csv('/kaggle/input/humanllm/Final_dataset.csv')

# Replace '\r' and '\n' with an empty string in all columns
paper_dataframe = paper_dataframe.replace({'\r': '', '\n': ''}, regex=True)


paper_dataframe.drop(columns=['uid'], inplace=True)

paper_dataframe = paper_dataframe[:5000]


ai_df = pd.read_csv("/kaggle/input/3500-datapoints/updated_dataset.csv", encoding='ISO-8859-1')
ai_df = ai_df.replace({'\r': '', '\n': ''}, regex=True)
filtered_df = ai_df[ai_df['ai_generated_text'].notna()]
human_df = pd.DataFrame(filtered_df['text'])
ai_df = pd.DataFrame(filtered_df['ai_generated_text'])
ai_df['ai_generated_text'] = ai_df['ai_generated_text'].apply(preprocess_text)
ai_df.rename(columns = {'ai_generated_text':'text'}, inplace = True)
human_df['label'] = 0
ai_df['label'] = 1
my_df = pd.concat([human_df, ai_df], ignore_index=True)
my_dataset = my_df.sample(frac=1, random_state=42).reset_index(drop=True)


my_dataset = my_dataset[:5000]


new_dataset = pd.concat([my_dataset, paper_dataframe], ignore_index = True)
dataset = new_dataset.sample(frac=1, random_state=42).reset_index(drop=True)

In [36]:
import torch
import torch.nn as nn
import torch.optim as optim
from transformers import T5ForConditionalGeneration, T5Tokenizer
from transformers import DistilBertModel, DistilBertTokenizer

from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

# Assuming 'df' is your dataset with columns ['text', 'label']
train_df, test_df = train_test_split(dataset, test_size=0.2, random_state=42)

# Dataset Class
class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
train_dataset = TextDataset(train_df)
test_dataset = TextDataset(test_df)

train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

# Function to process chunks and compute logits for both models
def process_chunks(model, tokenizer, texts, classifier, name, max_length=512, max_chunks=4):
    encoded_texts = tokenizer(
        texts,
        truncation=False,
        padding=True,
        return_tensors="pt"
    )

    input_ids = encoded_texts['input_ids'].cuda()
    attention_mask = encoded_texts['attention_mask'].cuda()

    batch_logits = []
    for i in range(len(input_ids)):
        input_id = input_ids[i]
        attention_mask_i = attention_mask[i]

        # Split the input into chunks of 512 tokens
        chunks = [input_id[j:j + 512] for j in range(0, len(input_id), 512)]
        attention_chunks = [attention_mask_i[j:j + 512] for j in range(0, len(input_id), 512)]

        if len(chunks) > max_chunks:
            chunks = chunks[:max_chunks]
            attention_chunks = attention_chunks[:max_chunks]

        last_chunk_size = len(chunks[-1])

        if last_chunk_size < 512:
            padding_length = 512 - last_chunk_size
            chunks[-1] = torch.cat([chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])
            attention_chunks[-1] = torch.cat([attention_chunks[-1], torch.zeros(padding_length, dtype=torch.long).cuda()])

        chunk_logits = []
        for chunk, mask in zip(chunks, attention_chunks):
            chunk = chunk.unsqueeze(0).cuda()
            mask = mask.unsqueeze(0).cuda()

            # Get model outputs
            outputs = model(input_ids=chunk, attention_mask=mask)
            cls_output = outputs.last_hidden_state[:, 0, :]

            logits = classifier(cls_output)
            chunk_logits.append(logits)

        chunk_logits = torch.cat(chunk_logits, dim=0)  # Shape: (num_chunks, 1)

        # Calculate weights based on chunk size
        chunk_weights = torch.ones(len(chunks), dtype=torch.float).cuda() * 512
        chunk_weights[-1] = last_chunk_size
        chunk_weights = chunk_weights / 512

        # Compute weighted logits
        weighted_logits = torch.sum(chunk_logits.squeeze() * chunk_weights) / torch.sum(chunk_weights)

        batch_logits.append(weighted_logits)

    final_logits = torch.stack(batch_logits)  # Shape: (batch_size,)
    return final_logits

# RoBERTa Model with classifier
class DistilSentinel(nn.Module):
    def __init__(self):
        super(DistilSentinel, self).__init__()
        self.distil = DistilBertModel.from_pretrained('distilbert-base-uncased')
        self.classifier = nn.Sequential(
            nn.Linear(768, 768),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(768, 1)
        )

    def forward(self, texts, tokenizer):
        logits = process_chunks(self.distil, tokenizer, texts, self.classifier, 'distilbert')
        return logits

# T5 Model with classifier
class T5BinaryClassifier(nn.Module):
    def __init__(self, model_name="t5-small"):
        super(T5BinaryClassifier, self).__init__()
        self.t5 = T5ForConditionalGeneration.from_pretrained(model_name)
        self.classifier = nn.Linear(self.t5.config.d_model, 1)

    def forward(self, texts, tokenizer):
        logits = process_chunks(self.t5.encoder, tokenizer, texts, self.classifier, 'T5')
        return logits

# Initialize models and tokenizers
distil_model = DistilSentinel().cuda()
distil_tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

t5_model = T5BinaryClassifier().cuda()
t5_tokenizer = T5Tokenizer.from_pretrained('t5-small')

# Ensemble model class
class EnsembleModel(nn.Module):
    def __init__(self, distil_model, t5_model, distil_tokenizer, t5_tokenizer):
        super(EnsembleModel, self).__init__()
        self.distil_model = distil_model
        self.t5_model = t5_model
        self.distil_tokenizer = distil_tokenizer
        self.t5_tokenizer = t5_tokenizer

    def forward(self, texts):
        # Get logits from both models
        distil_logits = self.distil_model(texts, self.distil_tokenizer)
        t5_logits = self.t5_model(texts, self.t5_tokenizer)

        # Compute final logits as average
        final_logits = torch.max(distil_logits, t5_logits)

        return distil_logits, t5_logits, final_logits

# Initialize the ensemble model
ensemble_model = EnsembleModel(distil_model, t5_model, distil_tokenizer, t5_tokenizer).cuda()

# Loss and optimizer
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(ensemble_model.parameters(), lr=1e-4)

# Training loop
num_epochs = 3
ensemble_model.train()

for epoch in range(num_epochs):
    running_loss = 0.0
    correct_predictions = 0
    total_predictions = 0

    for texts, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}"):
        texts = list(texts)  # Convert batch of texts to a list
        labels = labels.to("cuda").float()

        labels = labels.view(-1, 1)

        optimizer.zero_grad()

        # Forward pass through the ensemble model
        distil_logits, t5_logits, final_logits = ensemble_model(texts)
        final_logits = final_logits.view(-1, 1)
        # Compute the loss
        loss = criterion(final_logits, labels)

        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        
        # Make predictions
        predicted = (final_logits > 0).float()
        correct_predictions += (predicted == labels).sum().item()
        total_predictions += labels.size(0)

        # Debugging logs
        for i in range(labels.size(0)):
            actual_class = labels[i].item()
            final_prob = torch.sigmoid(final_logits[i]).item()
            print(f"Data point {i+1}: Actual Class: {actual_class}, Final Logit: {final_logits[i].item()}, Predicted Probability: {final_prob:.4f}, Prediction: {predicted[i].item()}")

    epoch_loss = running_loss / len(train_loader)
    epoch_accuracy = correct_predictions / total_predictions
    print(f"Epoch {epoch+1}, Loss: {epoch_loss:.4f}, Accuracy: {epoch_accuracy:.4f}")
# Save the model at the end of each epoch
print("Saving the ensemble model")
torch.save(ensemble_model.state_dict(), f'our_ensemble_model.pth')
print(f"Model saved as 'ensemble_model_epoch.pth'")

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Epoch 1/3:   0%|          | 1/4000 [00:00<24:17,  2.74it/s]Token indices sequence length is longer than the specified maximum sequence length for this model (3674 > 512). Running this sequence through the model will result in indexing errors

Data point 1: Actual Class: 0.0, Final Logit: -0.01138974353671074, Predicted Probability: 0.4972, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.016378028318285942, Predicted Probability: 0.5041, Prediction: 1.0

Token indices sequence length is longer than the specified maximum sequence length for this model (3960 > 512). Running this sequence through the model will result in indexing errors
Epoch 1/3:   0%|          | 2/4000 [00:01<42:47,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.028333699330687523, Predicted Probability: 0.4929, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.03586166724562645, Predicted Probability: 0.5090, Prediction: 1.0

Epoch 1/3:   0%|          | 3/4000 [00:01<31:29,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.010838109999895096, Predicted Probability: 0.4973, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.03300809860229492, Predicted Probability: 0.5083, Prediction: 1.0

Epoch 1/3:   0%|          | 4/4000 [00:01<28:59,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2530556619167328, Predicted Probability: 0.5629, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.015701912343502045, Predicted Probability: 0.5039, Prediction: 1.0

Epoch 1/3:   0%|          | 5/4000 [00:02<37:12,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.544069766998291, Predicted Probability: 0.6328, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.003931254148483276, Predicted Probability: 0.5010, Prediction: 1.0

Epoch 1/3:   0%|          | 6/4000 [00:03<41:14,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.32642805576324463, Predicted Probability: 0.5809, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.050925612449645996, Predicted Probability: 0.5127, Prediction: 1.0

Epoch 1/3:   0%|          | 7/4000 [00:03<37:19,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32583725452423096, Predicted Probability: 0.5807, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.23016004264354706, Predicted Probability: 0.5573, Prediction: 1.0

Epoch 1/3:   0%|          | 8/4000 [00:04<41:52,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.727867603302002, Predicted Probability: 0.6743, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.25588667392730713, Predicted Probability: 0.5636, Prediction: 1.0

Epoch 1/3:   0%|          | 9/4000 [00:04<36:32,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.20140601694583893, Predicted Probability: 0.5502, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2189868539571762, Predicted Probability: 0.5545, Prediction: 1.0

Epoch 1/3:   0%|          | 10/4000 [00:05<33:06,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.22880299389362335, Predicted Probability: 0.5570, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.24358780682086945, Predicted Probability: 0.5606, Prediction: 1.0

Epoch 1/3:   0%|          | 11/4000 [00:05<30:38,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6163221597671509, Predicted Probability: 0.6494, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2584349513053894, Predicted Probability: 0.5643, Prediction: 1.0

Epoch 1/3:   0%|          | 12/4000 [00:06<38:31,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1737414002418518, Predicted Probability: 0.5433, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.20588275790214539, Predicted Probability: 0.5513, Prediction: 1.0

Epoch 1/3:   0%|          | 13/4000 [00:07<43:04,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.19744348526000977, Predicted Probability: 0.5492, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.27570945024490356, Predicted Probability: 0.5685, Prediction: 1.0

Epoch 1/3:   0%|          | 14/4000 [00:08<47:31,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2215297818183899, Predicted Probability: 0.5552, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.17258314788341522, Predicted Probability: 0.5430, Prediction: 1.0

Epoch 1/3:   0%|          | 15/4000 [00:08<40:50,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.13779237866401672, Predicted Probability: 0.5344, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.13446559011936188, Predicted Probability: 0.5336, Prediction: 1.0

Epoch 1/3:   0%|          | 16/4000 [00:08<32:41,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.18378570675849915, Predicted Probability: 0.5458, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.06559696048498154, Predicted Probability: 0.5164, Prediction: 1.0

Epoch 1/3:   0%|          | 17/4000 [00:09<31:40,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.15748797357082367, Predicted Probability: 0.5393, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.14877666532993317, Predicted Probability: 0.5371, Prediction: 1.0

Epoch 1/3:   0%|          | 18/4000 [00:10<37:01,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.17855632305145264, Predicted Probability: 0.5445, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.026433423161506653, Predicted Probability: 0.4934, Prediction: 0.0

Epoch 1/3:   0%|          | 19/4000 [00:10<30:14,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.021265029907226562, Predicted Probability: 0.5053, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.12701909244060516, Predicted Probability: 0.5317, Prediction: 1.0

Epoch 1/3:   0%|          | 20/4000 [00:10<35:22,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.16341309249401093, Predicted Probability: 0.5408, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.043287694454193115, Predicted Probability: 0.4892, Prediction: 0.0

Epoch 1/3:   1%|          | 21/4000 [00:11<33:33,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.06109902635216713, Predicted Probability: 0.5153, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.13620933890342712, Predicted Probability: 0.5340, Prediction: 1.0

Epoch 1/3:   1%|          | 22/4000 [00:12<40:24,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.016234666109085083, Predicted Probability: 0.5041, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.10416543483734131, Predicted Probability: 0.4740, Prediction: 0.0

Epoch 1/3:   1%|          | 23/4000 [00:13<44:45,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.028043359518051147, Predicted Probability: 0.4930, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.07716111093759537, Predicted Probability: 0.4807, Prediction: 0.0

Epoch 1/3:   1%|          | 24/4000 [00:13<45:43,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.252691388130188, Predicted Probability: 0.5628, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.09135403484106064, Predicted Probability: 0.4772, Prediction: 0.0

Epoch 1/3:   1%|          | 25/4000 [00:14<47:24,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2999519109725952, Predicted Probability: 0.5744, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.07367323338985443, Predicted Probability: 0.5184, Prediction: 1.0

Epoch 1/3:   1%|          | 26/4000 [00:15<48:50,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.06725689768791199, Predicted Probability: 0.4832, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.17171433568000793, Predicted Probability: 0.5428, Prediction: 1.0

Epoch 1/3:   1%|          | 27/4000 [00:15<41:34,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.020892679691314697, Predicted Probability: 0.5052, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.008613118901848793, Predicted Probability: 0.5022, Prediction: 1.0

Epoch 1/3:   1%|          | 28/4000 [00:16<43:40,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5618177652359009, Predicted Probability: 0.6369, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.24876271188259125, Predicted Probability: 0.4381, Prediction: 0.0

Epoch 1/3:   1%|          | 29/4000 [00:17<45:20,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.0814799964427948, Predicted Probability: 0.4796, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.024335002526640892, Predicted Probability: 0.5061, Prediction: 1.0

Epoch 1/3:   1%|          | 30/4000 [00:17<46:12,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.19577287137508392, Predicted Probability: 0.5488, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.13312186300754547, Predicted Probability: 0.4668, Prediction: 0.0

Epoch 1/3:   1%|          | 31/4000 [00:18<46:41,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1881362348794937, Predicted Probability: 0.5469, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.20907172560691833, Predicted Probability: 0.4479, Prediction: 0.0

Epoch 1/3:   1%|          | 32/4000 [00:19<47:09,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2825325131416321, Predicted Probability: 0.5702, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.0697060078382492, Predicted Probability: 0.4826, Prediction: 0.0

Epoch 1/3:   1%|          | 33/4000 [00:20<49:36,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.09659973531961441, Predicted Probability: 0.4759, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.11929303407669067, Predicted Probability: 0.4702, Prediction: 0.0

Epoch 1/3:   1%|          | 34/4000 [00:20<42:11,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.08627206832170486, Predicted Probability: 0.5216, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.16112351417541504, Predicted Probability: 0.4598, Prediction: 0.0

Epoch 1/3:   1%|          | 35/4000 [00:20<36:50,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.23919342458248138, Predicted Probability: 0.5595, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.10080566257238388, Predicted Probability: 0.4748, Prediction: 0.0

Epoch 1/3:   1%|          | 36/4000 [00:21<33:17,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.007665665354579687, Predicted Probability: 0.4981, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.028754822909832, Predicted Probability: 0.5072, Prediction: 1.0

Epoch 1/3:   1%|          | 37/4000 [00:21<34:04,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.47855034470558167, Predicted Probability: 0.6174, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.15313172340393066, Predicted Probability: 0.4618, Prediction: 0.0

Epoch 1/3:   1%|          | 38/4000 [00:22<27:53,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.015247448347508907, Predicted Probability: 0.5038, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.1704970896244049, Predicted Probability: 0.5425, Prediction: 1.0

Epoch 1/3:   1%|          | 39/4000 [00:22<35:50,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.1647111475467682, Predicted Probability: 0.4589, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6445850729942322, Predicted Probability: 0.6558, Prediction: 1.0

Epoch 1/3:   1%|          | 40/4000 [00:23<30:23,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.18642504513263702, Predicted Probability: 0.5465, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.1876823753118515, Predicted Probability: 0.5468, Prediction: 1.0

Epoch 1/3:   1%|          | 41/4000 [00:23<28:47,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.32624801993370056, Predicted Probability: 0.5808, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.03636204078793526, Predicted Probability: 0.4909, Prediction: 0.0

Epoch 1/3:   1%|          | 42/4000 [00:23<24:17,  2.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.08276994526386261, Predicted Probability: 0.5207, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.20636627078056335, Predicted Probability: 0.5514, Prediction: 1.0

Epoch 1/3:   1%|          | 43/4000 [00:24<31:52,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3150549530982971, Predicted Probability: 0.5781, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.29748257994651794, Predicted Probability: 0.4262, Prediction: 0.0

Epoch 1/3:   1%|          | 44/4000 [00:25<33:32,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.20291376113891602, Predicted Probability: 0.4494, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.134149432182312, Predicted Probability: 0.4665, Prediction: 0.0

Epoch 1/3:   1%|          | 45/4000 [00:25<30:50,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.028986899182200432, Predicted Probability: 0.5072, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.19362959265708923, Predicted Probability: 0.4517, Prediction: 0.0

Epoch 1/3:   1%|          | 46/4000 [00:26<37:06,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.29290324449539185, Predicted Probability: 0.4273, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.17039698362350464, Predicted Probability: 0.5425, Prediction: 1.0

Epoch 1/3:   1%|          | 47/4000 [00:26<33:18,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2431091070175171, Predicted Probability: 0.4395, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.04022778943181038, Predicted Probability: 0.5101, Prediction: 1.0

Epoch 1/3:   1%|          | 48/4000 [00:27<38:55,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.27687323093414307, Predicted Probability: 0.4312, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.01406889408826828, Predicted Probability: 0.5035, Prediction: 1.0

Epoch 1/3:   1%|          | 49/4000 [00:27<35:59,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.30730903148651123, Predicted Probability: 0.4238, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.03427031263709068, Predicted Probability: 0.5086, Prediction: 1.0

Epoch 1/3:   1%|▏         | 50/4000 [00:28<37:12,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.14154833555221558, Predicted Probability: 0.5353, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.23514942824840546, Predicted Probability: 0.4415, Prediction: 0.0

Epoch 1/3:   1%|▏         | 51/4000 [00:29<41:45,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.21077170968055725, Predicted Probability: 0.4475, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.15858623385429382, Predicted Probability: 0.4604, Prediction: 0.0

Epoch 1/3:   1%|▏         | 52/4000 [00:30<44:51,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.12798941135406494, Predicted Probability: 0.4680, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.28071850538253784, Predicted Probability: 0.4303, Prediction: 0.0

Epoch 1/3:   1%|▏         | 53/4000 [00:30<42:14,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.22532562911510468, Predicted Probability: 0.4439, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1294623166322708, Predicted Probability: 0.4677, Prediction: 0.0

Epoch 1/3:   1%|▏         | 54/4000 [00:31<44:33,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.14118970930576324, Predicted Probability: 0.4648, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2510400414466858, Predicted Probability: 0.4376, Prediction: 0.0

Epoch 1/3:   1%|▏         | 55/4000 [00:31<38:40,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.18002989888191223, Predicted Probability: 0.4551, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.02806510031223297, Predicted Probability: 0.4930, Prediction: 0.0

Epoch 1/3:   1%|▏         | 56/4000 [00:31<31:03,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.26602205634117126, Predicted Probability: 0.4339, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.005470088683068752, Predicted Probability: 0.5014, Prediction: 1.0

Epoch 1/3:   1%|▏         | 57/4000 [00:32<36:17,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.1911696195602417, Predicted Probability: 0.4524, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3060566484928131, Predicted Probability: 0.4241, Prediction: 0.0

Epoch 1/3:   1%|▏         | 58/4000 [00:33<34:08,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.025163760408759117, Predicted Probability: 0.5063, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3531471788883209, Predicted Probability: 0.4126, Prediction: 0.0

Epoch 1/3:   1%|▏         | 59/4000 [00:33<39:30,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2595917582511902, Predicted Probability: 0.4355, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.23280099034309387, Predicted Probability: 0.4421, Prediction: 0.0

Epoch 1/3:   2%|▏         | 60/4000 [00:34<42:42,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3684297800064087, Predicted Probability: 0.4089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.22410477697849274, Predicted Probability: 0.4442, Prediction: 0.0

Epoch 1/3:   2%|▏         | 61/4000 [00:35<40:40,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.12544623017311096, Predicted Probability: 0.4687, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.1331682801246643, Predicted Probability: 0.5332, Prediction: 1.0

Epoch 1/3:   2%|▏         | 62/4000 [00:35<32:26,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.07443487644195557, Predicted Probability: 0.4814, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.02412615716457367, Predicted Probability: 0.5060, Prediction: 1.0

Epoch 1/3:   2%|▏         | 63/4000 [00:36<38:13,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2088279277086258, Predicted Probability: 0.4480, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1847696602344513, Predicted Probability: 0.4539, Prediction: 0.0

Epoch 1/3:   2%|▏         | 64/4000 [00:37<42:20,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.010494157671928406, Predicted Probability: 0.4974, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3291796147823334, Predicted Probability: 0.4184, Prediction: 0.0

Epoch 1/3:   2%|▏         | 65/4000 [00:37<45:33,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.09767740964889526, Predicted Probability: 0.5244, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.23622728884220123, Predicted Probability: 0.4412, Prediction: 0.0

Epoch 1/3:   2%|▏         | 66/4000 [00:38<46:29,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.28552010655403137, Predicted Probability: 0.4291, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.051304835826158524, Predicted Probability: 0.5128, Prediction: 1.0

Epoch 1/3:   2%|▏         | 67/4000 [00:39<47:28,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3617625832557678, Predicted Probability: 0.4105, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.43683910369873047, Predicted Probability: 0.6075, Prediction: 1.0

Epoch 1/3:   2%|▏         | 68/4000 [00:39<40:50,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2544530928134918, Predicted Probability: 0.5633, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.13394048810005188, Predicted Probability: 0.4666, Prediction: 0.0

Epoch 1/3:   2%|▏         | 69/4000 [00:40<36:08,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3215879499912262, Predicted Probability: 0.5797, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.022123735398054123, Predicted Probability: 0.5055, Prediction: 1.0

Epoch 1/3:   2%|▏         | 70/4000 [00:40<40:25,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2906148433685303, Predicted Probability: 0.5721, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.64568030834198, Predicted Probability: 0.6560, Prediction: 1.0

Epoch 1/3:   2%|▏         | 71/4000 [00:41<39:07,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3306739628314972, Predicted Probability: 0.5819, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.716429591178894, Predicted Probability: 0.6718, Prediction: 1.0

Epoch 1/3:   2%|▏         | 72/4000 [00:42<48:14,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3174971342086792, Predicted Probability: 0.5787, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2275606244802475, Predicted Probability: 0.5566, Prediction: 1.0

Epoch 1/3:   2%|▏         | 73/4000 [00:42<41:13,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.15451261401176453, Predicted Probability: 0.5386, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.0825878456234932, Predicted Probability: 0.5206, Prediction: 1.0

Epoch 1/3:   2%|▏         | 74/4000 [00:43<40:58,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.06594659388065338, Predicted Probability: 0.4835, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.8292936682701111, Predicted Probability: 0.6962, Prediction: 1.0

Epoch 1/3:   2%|▏         | 76/4000 [00:44<35:13,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.22220489382743835, Predicted Probability: 0.4447, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.33463090658187866, Predicted Probability: 0.4171, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 0.2963085472583771, Predicted Probability: 0.5735, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.27531254291534424, Predicted Probability: 0.5684, Prediction: 1.0

Epoch 1/3:   2%|▏         | 77/4000 [00:45<39:21,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.29099512100219727, Predicted Probability: 0.4278, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6736106872558594, Predicted Probability: 0.6623, Prediction: 1.0

Epoch 1/3:   2%|▏         | 78/4000 [00:45<34:41,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.32430630922317505, Predicted Probability: 0.5804, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.36713147163391113, Predicted Probability: 0.4092, Prediction: 0.0

Epoch 1/3:   2%|▏         | 79/4000 [00:46<31:48,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.1451990157365799, Predicted Probability: 0.4638, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.09902752190828323, Predicted Probability: 0.4753, Prediction: 0.0

Epoch 1/3:   2%|▏         | 80/4000 [00:46<38:31,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2568104863166809, Predicted Probability: 0.4361, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3933810889720917, Predicted Probability: 0.4029, Prediction: 0.0

Epoch 1/3:   2%|▏         | 81/4000 [00:47<37:29,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.35651183128356934, Predicted Probability: 0.4118, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4560938775539398, Predicted Probability: 0.6121, Prediction: 1.0

Epoch 1/3:   2%|▏         | 82/4000 [00:47<36:47,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.299724280834198, Predicted Probability: 0.4256, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.39764541387557983, Predicted Probability: 0.5981, Prediction: 1.0

Epoch 1/3:   2%|▏         | 83/4000 [00:48<33:09,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3488646149635315, Predicted Probability: 0.5863, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.17018242180347443, Predicted Probability: 0.4576, Prediction: 0.0

Epoch 1/3:   2%|▏         | 84/4000 [00:49<38:57,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4278218150138855, Predicted Probability: 0.3946, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5934669971466064, Predicted Probability: 0.6442, Prediction: 1.0

Epoch 1/3:   2%|▏         | 85/4000 [00:49<38:06,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3667716085910797, Predicted Probability: 0.4093, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5064989924430847, Predicted Probability: 0.6240, Prediction: 1.0

Epoch 1/3:   2%|▏         | 86/4000 [00:50<41:10,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.22320842742919922, Predicted Probability: 0.4444, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.11273699998855591, Predicted Probability: 0.5282, Prediction: 1.0

Epoch 1/3:   2%|▏         | 87/4000 [00:50<32:50,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.25069332122802734, Predicted Probability: 0.5623, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.010056115686893463, Predicted Probability: 0.4975, Prediction: 0.0

Epoch 1/3:   2%|▏         | 88/4000 [00:51<37:47,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31627869606018066, Predicted Probability: 0.4216, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2881225645542145, Predicted Probability: 0.4285, Prediction: 0.0

Epoch 1/3:   2%|▏         | 89/4000 [00:52<40:52,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2899168133735657, Predicted Probability: 0.4280, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9128509759902954, Predicted Probability: 0.7136, Prediction: 1.0

Epoch 1/3:   2%|▏         | 90/4000 [00:52<44:20,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3733290433883667, Predicted Probability: 0.5923, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3321775197982788, Predicted Probability: 0.4177, Prediction: 0.0

Epoch 1/3:   2%|▏         | 91/4000 [00:53<46:11,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.32038381695747375, Predicted Probability: 0.4206, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.23695531487464905, Predicted Probability: 0.4410, Prediction: 0.0

Epoch 1/3:   2%|▏         | 92/4000 [00:54<39:49,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.20699886977672577, Predicted Probability: 0.4484, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.29451078176498413, Predicted Probability: 0.4269, Prediction: 0.0

Epoch 1/3:   2%|▏         | 93/4000 [00:54<42:26,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.592278242111206, Predicted Probability: 0.8309, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.32889610528945923, Predicted Probability: 0.4185, Prediction: 0.0

Epoch 1/3:   2%|▏         | 94/4000 [00:55<33:42,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5104919672012329, Predicted Probability: 0.6249, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5101814270019531, Predicted Probability: 0.6248, Prediction: 1.0

Epoch 1/3:   2%|▏         | 95/4000 [00:55<38:24,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.19968736171722412, Predicted Probability: 0.5498, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4492517113685608, Predicted Probability: 0.3895, Prediction: 0.0

Epoch 1/3:   2%|▏         | 96/4000 [00:56<34:24,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3750617206096649, Predicted Probability: 0.4073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2596624791622162, Predicted Probability: 0.4354, Prediction: 0.0

Epoch 1/3:   2%|▏         | 97/4000 [00:56<31:29,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3341822922229767, Predicted Probability: 0.4172, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2633070945739746, Predicted Probability: 0.4346, Prediction: 0.0

Epoch 1/3:   2%|▏         | 98/4000 [00:57<37:25,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.35522305965423584, Predicted Probability: 0.4121, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.09828224778175354, Predicted Probability: 0.5246, Prediction: 1.0

Epoch 1/3:   2%|▏         | 99/4000 [00:57<38:33,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2579701244831085, Predicted Probability: 0.4359, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.22456909716129303, Predicted Probability: 0.4441, Prediction: 0.0

Epoch 1/3:   2%|▎         | 100/4000 [00:58<37:40,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.09472382813692093, Predicted Probability: 0.5237, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.298088014125824, Predicted Probability: 0.4260, Prediction: 0.0

Epoch 1/3:   3%|▎         | 101/4000 [00:58<35:11,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1650315523147583, Predicted Probability: 0.5412, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.010090015828609467, Predicted Probability: 0.5025, Prediction: 1.0

Epoch 1/3:   3%|▎         | 103/4000 [00:59<26:04,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9420337080955505, Predicted Probability: 0.7195, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.0037104832008481026, Predicted Probability: 0.4991, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 1.2881295680999756, Predicted Probability: 0.7838, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.0911989212036133, Predicted Probability: 0.7486, Prediction: 1.0

Epoch 1/3:   3%|▎         | 104/4000 [00:59<25:42,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1686086654663086, Predicted Probability: 0.7629, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.32692423462867737, Predicted Probability: 0.5810, Prediction: 1.0

Epoch 1/3:   3%|▎         | 105/4000 [01:00<26:50,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6033323407173157, Predicted Probability: 0.6464, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1953336000442505, Predicted Probability: 0.7677, Prediction: 1.0

Epoch 1/3:   3%|▎         | 106/4000 [01:00<24:02,  2.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.937026858329773, Predicted Probability: 0.7185, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1340810060501099, Predicted Probability: 0.7566, Prediction: 1.0

Epoch 1/3:   3%|▎         | 107/4000 [01:01<32:24,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5582948327064514, Predicted Probability: 0.6361, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.082029104232788, Predicted Probability: 0.7469, Prediction: 1.0

Epoch 1/3:   3%|▎         | 108/4000 [01:02<37:44,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7847922444343567, Predicted Probability: 0.6867, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5379250049591064, Predicted Probability: 0.6313, Prediction: 1.0

Epoch 1/3:   3%|▎         | 109/4000 [01:02<41:03,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3545143604278564, Predicted Probability: 0.7949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.37811461091041565, Predicted Probability: 0.5934, Prediction: 1.0

Epoch 1/3:   3%|▎         | 110/4000 [01:03<42:57,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3071081042289734, Predicted Probability: 0.5762, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9030048847198486, Predicted Probability: 0.7116, Prediction: 1.0

Epoch 1/3:   3%|▎         | 111/4000 [01:04<37:17,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.23187430202960968, Predicted Probability: 0.5577, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.8154605031013489, Predicted Probability: 0.6933, Prediction: 1.0

Epoch 1/3:   3%|▎         | 112/4000 [01:04<41:00,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.03537238389253616, Predicted Probability: 0.4912, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.90323406457901, Predicted Probability: 0.7116, Prediction: 1.0

Epoch 1/3:   3%|▎         | 113/4000 [01:05<32:41,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5511854290962219, Predicted Probability: 0.6344, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5688899755477905, Predicted Probability: 0.6385, Prediction: 1.0

Epoch 1/3:   3%|▎         | 114/4000 [01:05<37:51,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4099366664886475, Predicted Probability: 0.8038, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3032608926296234, Predicted Probability: 0.4248, Prediction: 0.0

Epoch 1/3:   3%|▎         | 115/4000 [01:06<40:37,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3425354957580566, Predicted Probability: 0.7929, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4466503858566284, Predicted Probability: 0.3902, Prediction: 0.0

Epoch 1/3:   3%|▎         | 116/4000 [01:06<32:21,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6052667498588562, Predicted Probability: 0.6469, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7314208149909973, Predicted Probability: 0.6751, Prediction: 1.0

Epoch 1/3:   3%|▎         | 117/4000 [01:07<30:15,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.19767025113105774, Predicted Probability: 0.4507, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.003589284373447299, Predicted Probability: 0.5009, Prediction: 1.0

Epoch 1/3:   3%|▎         | 118/4000 [01:07<35:22,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.592036485671997, Predicted Probability: 0.8309, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.40801581740379333, Predicted Probability: 0.3994, Prediction: 0.0

Epoch 1/3:   3%|▎         | 119/4000 [01:08<35:39,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1762319654226303, Predicted Probability: 0.5439, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3570074737071991, Predicted Probability: 0.4117, Prediction: 0.0

Epoch 1/3:   3%|▎         | 120/4000 [01:09<39:55,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6470646858215332, Predicted Probability: 0.8385, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.418504923582077, Predicted Probability: 0.3969, Prediction: 0.0

Epoch 1/3:   3%|▎         | 121/4000 [01:09<38:19,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4296247959136963, Predicted Probability: 0.8068, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2839081585407257, Predicted Probability: 0.4295, Prediction: 0.0

Epoch 1/3:   3%|▎         | 122/4000 [01:10<34:11,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9590921401977539, Predicted Probability: 0.7229, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.08873511850833893, Predicted Probability: 0.4778, Prediction: 0.0

Epoch 1/3:   3%|▎         | 124/4000 [01:10<26:26,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4499081373214722, Predicted Probability: 0.8100, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2562084197998047, Predicted Probability: 0.4363, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.7523589134216309, Predicted Probability: 0.6797, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9680925011634827, Predicted Probability: 0.7247, Prediction: 1.0

Epoch 1/3:   3%|▎         | 125/4000 [01:10<22:23,  2.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6849786639213562, Predicted Probability: 0.6648, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.47197291254997253, Predicted Probability: 0.6159, Prediction: 1.0

Epoch 1/3:   3%|▎         | 126/4000 [01:11<30:01,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3560979962348938, Predicted Probability: 0.4119, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.332979440689087, Predicted Probability: 0.9116, Prediction: 1.0

Epoch 1/3:   3%|▎         | 127/4000 [01:11<26:12,  2.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.48392289876937866, Predicted Probability: 0.6187, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2173292636871338, Predicted Probability: 0.7716, Prediction: 1.0

Epoch 1/3:   3%|▎         | 128/4000 [01:12<25:48,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5660882592201233, Predicted Probability: 0.6379, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.6318918466567993, Predicted Probability: 0.8364, Prediction: 1.0

Epoch 1/3:   3%|▎         | 129/4000 [01:12<25:32,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.1631866693496704, Predicted Probability: 0.4593, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2674121856689453, Predicted Probability: 0.9061, Prediction: 1.0

Epoch 1/3:   3%|▎         | 130/4000 [01:13<32:09,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6336445808410645, Predicted Probability: 0.9330, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.76833438873291, Predicted Probability: 0.9409, Prediction: 1.0

Epoch 1/3:   3%|▎         | 131/4000 [01:13<29:33,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.5204052925109863, Predicted Probability: 0.9256, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.774658203125, Predicted Probability: 0.9413, Prediction: 1.0

Epoch 1/3:   3%|▎         | 132/4000 [01:14<25:43,  2.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.482135534286499, Predicted Probability: 0.9229, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.376051664352417, Predicted Probability: 0.9150, Prediction: 1.0

Epoch 1/3:   3%|▎         | 133/4000 [01:14<25:12,  2.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.022174835205078, Predicted Probability: 0.8831, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.9571470022201538, Predicted Probability: 0.8762, Prediction: 1.0

Epoch 1/3:   3%|▎         | 134/4000 [01:14<24:58,  2.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3265771865844727, Predicted Probability: 0.7903, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4168882369995117, Predicted Probability: 0.8049, Prediction: 1.0

Epoch 1/3:   3%|▎         | 135/4000 [01:15<31:27,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1019195318222046, Predicted Probability: 0.7506, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9807249307632446, Predicted Probability: 0.7273, Prediction: 1.0

Epoch 1/3:   3%|▎         | 136/4000 [01:15<29:45,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6341625452041626, Predicted Probability: 0.6534, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8497557044029236, Predicted Probability: 0.7005, Prediction: 1.0

Epoch 1/3:   3%|▎         | 137/4000 [01:16<31:47,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6262838244438171, Predicted Probability: 0.6516, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.656433641910553, Predicted Probability: 0.6585, Prediction: 1.0

Epoch 1/3:   3%|▎         | 138/4000 [01:17<37:58,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6633577346801758, Predicted Probability: 0.6600, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.556846022605896, Predicted Probability: 0.6357, Prediction: 1.0

Epoch 1/3:   3%|▎         | 139/4000 [01:18<41:47,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6098889112472534, Predicted Probability: 0.6479, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6998385190963745, Predicted Probability: 0.6682, Prediction: 1.0

Epoch 1/3:   4%|▎         | 140/4000 [01:18<36:49,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5869609117507935, Predicted Probability: 0.6427, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6819155812263489, Predicted Probability: 0.6642, Prediction: 1.0

Epoch 1/3:   4%|▎         | 141/4000 [01:18<33:16,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.48688310384750366, Predicted Probability: 0.6194, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5911175608634949, Predicted Probability: 0.6436, Prediction: 1.0

Epoch 1/3:   4%|▎         | 142/4000 [01:19<30:40,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7455114126205444, Predicted Probability: 0.6782, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.667949914932251, Predicted Probability: 0.6610, Prediction: 1.0

Epoch 1/3:   4%|▎         | 143/4000 [01:19<32:02,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.665759265422821, Predicted Probability: 0.6606, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6926605701446533, Predicted Probability: 0.6666, Prediction: 1.0

Epoch 1/3:   4%|▎         | 144/4000 [01:20<36:44,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6040314435958862, Predicted Probability: 0.6466, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6150878071784973, Predicted Probability: 0.6491, Prediction: 1.0

Epoch 1/3:   4%|▎         | 145/4000 [01:21<40:55,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5494065284729004, Predicted Probability: 0.6340, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6228582262992859, Predicted Probability: 0.6509, Prediction: 1.0

Epoch 1/3:   4%|▎         | 146/4000 [01:21<35:53,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5417406558990479, Predicted Probability: 0.6322, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.637831449508667, Predicted Probability: 0.6543, Prediction: 1.0

Epoch 1/3:   4%|▎         | 147/4000 [01:22<40:19,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5873295068740845, Predicted Probability: 0.6428, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5846099853515625, Predicted Probability: 0.6421, Prediction: 1.0

Epoch 1/3:   4%|▎         | 148/4000 [01:23<43:41,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.579453706741333, Predicted Probability: 0.6409, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5319324731826782, Predicted Probability: 0.6299, Prediction: 1.0

Epoch 1/3:   4%|▎         | 149/4000 [01:24<44:52,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5295091867446899, Predicted Probability: 0.6294, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5156237483024597, Predicted Probability: 0.6261, Prediction: 1.0

Epoch 1/3:   4%|▍         | 150/4000 [01:24<36:27,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6548093557357788, Predicted Probability: 0.6581, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6221567988395691, Predicted Probability: 0.6507, Prediction: 1.0

Epoch 1/3:   4%|▍         | 151/4000 [01:25<39:26,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5070285797119141, Predicted Probability: 0.6241, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4586455523967743, Predicted Probability: 0.6127, Prediction: 1.0

Epoch 1/3:   4%|▍         | 152/4000 [01:25<43:41,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.415752649307251, Predicted Probability: 0.6025, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4313703179359436, Predicted Probability: 0.6062, Prediction: 1.0

Epoch 1/3:   4%|▍         | 153/4000 [01:26<44:41,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4405110478401184, Predicted Probability: 0.6084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3303508162498474, Predicted Probability: 0.5818, Prediction: 1.0

Epoch 1/3:   4%|▍         | 154/4000 [01:27<38:21,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6019589304924011, Predicted Probability: 0.6461, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.31461265683174133, Predicted Probability: 0.5780, Prediction: 1.0

Epoch 1/3:   4%|▍         | 155/4000 [01:27<41:23,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3363538980484009, Predicted Probability: 0.5833, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.246910959482193, Predicted Probability: 0.5614, Prediction: 1.0

Epoch 1/3:   4%|▍         | 156/4000 [01:28<37:32,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.43353530764579773, Predicted Probability: 0.6067, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5374165773391724, Predicted Probability: 0.6312, Prediction: 1.0

Epoch 1/3:   4%|▍         | 157/4000 [01:29<42:44,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.31379395723342896, Predicted Probability: 0.5778, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.26240453124046326, Predicted Probability: 0.5652, Prediction: 1.0

Epoch 1/3:   4%|▍         | 158/4000 [01:29<44:27,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.38101083040237427, Predicted Probability: 0.5941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2380691021680832, Predicted Probability: 0.5592, Prediction: 1.0

Epoch 1/3:   4%|▍         | 159/4000 [01:30<44:48,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.17338430881500244, Predicted Probability: 0.5432, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3874325454235077, Predicted Probability: 0.5957, Prediction: 1.0

Epoch 1/3:   4%|▍         | 160/4000 [01:31<45:51,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32209235429763794, Predicted Probability: 0.5798, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1385038197040558, Predicted Probability: 0.5346, Prediction: 1.0

Epoch 1/3:   4%|▍         | 161/4000 [01:32<47:30,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.22714106738567352, Predicted Probability: 0.5565, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.027772175148129463, Predicted Probability: 0.5069, Prediction: 1.0

Epoch 1/3:   4%|▍         | 162/4000 [01:32<47:14,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.07300852239131927, Predicted Probability: 0.5182, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.03407704457640648, Predicted Probability: 0.5085, Prediction: 1.0

Epoch 1/3:   4%|▍         | 163/4000 [01:33<41:47,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1601753532886505, Predicted Probability: 0.5400, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.005288608837872744, Predicted Probability: 0.4987, Prediction: 0.0

Epoch 1/3:   4%|▍         | 164/4000 [01:34<45:31,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.45271405577659607, Predicted Probability: 0.3887, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.26835623383522034, Predicted Probability: 0.4333, Prediction: 0.0

Epoch 1/3:   4%|▍         | 165/4000 [01:34<47:32,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2588834762573242, Predicted Probability: 0.4356, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.36780351400375366, Predicted Probability: 0.4091, Prediction: 0.0

Epoch 1/3:   4%|▍         | 166/4000 [01:35<40:38,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.09679178893566132, Predicted Probability: 0.5242, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.695288360118866, Predicted Probability: 0.6671, Prediction: 1.0

Epoch 1/3:   4%|▍         | 167/4000 [01:36<42:21,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.29446089267730713, Predicted Probability: 0.4269, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.216379314661026, Predicted Probability: 0.4461, Prediction: 0.0

Epoch 1/3:   4%|▍         | 168/4000 [01:36<43:55,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.09926488995552063, Predicted Probability: 0.5248, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.17299498617649078, Predicted Probability: 0.5431, Prediction: 1.0

Epoch 1/3:   4%|▍         | 169/4000 [01:37<46:09,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31310009956359863, Predicted Probability: 0.4224, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2711428701877594, Predicted Probability: 0.5674, Prediction: 1.0

Epoch 1/3:   4%|▍         | 170/4000 [01:38<46:17,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.33793210983276367, Predicted Probability: 0.5837, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.26428866386413574, Predicted Probability: 0.4343, Prediction: 0.0

Epoch 1/3:   4%|▍         | 171/4000 [01:38<36:24,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2259814739227295, Predicted Probability: 0.9026, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.016641169786453247, Predicted Probability: 0.5042, Prediction: 1.0

Epoch 1/3:   4%|▍         | 172/4000 [01:39<39:48,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.20131254196166992, Predicted Probability: 0.4498, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2824365198612213, Predicted Probability: 0.4299, Prediction: 0.0

Epoch 1/3:   4%|▍         | 173/4000 [01:39<35:12,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.002940404461696744, Predicted Probability: 0.5007, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.856685221195221, Predicted Probability: 0.7020, Prediction: 1.0

Epoch 1/3:   4%|▍         | 174/4000 [01:40<39:40,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3169260621070862, Predicted Probability: 0.4214, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.1939505934715271, Predicted Probability: 0.5483, Prediction: 1.0

Epoch 1/3:   4%|▍         | 175/4000 [01:40<34:46,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.18978391587734222, Predicted Probability: 0.4527, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3082830607891083, Predicted Probability: 0.4235, Prediction: 0.0

Epoch 1/3:   4%|▍         | 176/4000 [01:41<37:56,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.44776177406311035, Predicted Probability: 0.3899, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.23352964222431183, Predicted Probability: 0.4419, Prediction: 0.0

Epoch 1/3:   4%|▍         | 177/4000 [01:41<33:36,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.16559399664402008, Predicted Probability: 0.4587, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.12574489414691925, Predicted Probability: 0.4686, Prediction: 0.0

Epoch 1/3:   4%|▍         | 178/4000 [01:42<36:53,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.22627444565296173, Predicted Probability: 0.4437, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3599950075149536, Predicted Probability: 0.4110, Prediction: 0.0

Epoch 1/3:   4%|▍         | 179/4000 [01:43<35:49,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.22322216629981995, Predicted Probability: 0.4444, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2582765817642212, Predicted Probability: 0.4358, Prediction: 0.0

Epoch 1/3:   4%|▍         | 180/4000 [01:43<41:15,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.373418390750885, Predicted Probability: 0.4077, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5332810878753662, Predicted Probability: 0.3698, Prediction: 0.0

Epoch 1/3:   5%|▍         | 181/4000 [01:44<43:34,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.36851269006729126, Predicted Probability: 0.4089, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.24208152294158936, Predicted Probability: 0.4398, Prediction: 0.0

Epoch 1/3:   5%|▍         | 182/4000 [01:45<44:47,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4331614375114441, Predicted Probability: 0.3934, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.19844406843185425, Predicted Probability: 0.4506, Prediction: 0.0

Epoch 1/3:   5%|▍         | 183/4000 [01:46<45:33,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.1587846875190735, Predicted Probability: 0.4604, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.39522942900657654, Predicted Probability: 0.4025, Prediction: 0.0

Epoch 1/3:   5%|▍         | 184/4000 [01:46<41:57,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.17750470340251923, Predicted Probability: 0.4557, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5246413946151733, Predicted Probability: 0.3718, Prediction: 0.0

Epoch 1/3:   5%|▍         | 185/4000 [01:47<44:21,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2800912857055664, Predicted Probability: 0.4304, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3263605535030365, Predicted Probability: 0.4191, Prediction: 0.0

Epoch 1/3:   5%|▍         | 186/4000 [01:48<41:27,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2946488559246063, Predicted Probability: 0.4269, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.22969114780426025, Predicted Probability: 0.4428, Prediction: 0.0

Epoch 1/3:   5%|▍         | 187/4000 [01:48<43:14,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4981495141983032, Predicted Probability: 0.3780, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.18996630609035492, Predicted Probability: 0.4527, Prediction: 0.0

Epoch 1/3:   5%|▍         | 189/4000 [01:49<34:44,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5082322955131531, Predicted Probability: 0.3756, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.27507224678993225, Predicted Probability: 0.4317, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.2022409588098526, Predicted Probability: 0.5504, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.58858323097229, Predicted Probability: 0.6430, Prediction: 1.0

Epoch 1/3:   5%|▍         | 190/4000 [01:50<38:19,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2704436182975769, Predicted Probability: 0.4328, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.491317480802536, Predicted Probability: 0.3796, Prediction: 0.0

Epoch 1/3:   5%|▍         | 191/4000 [01:50<33:48,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6250916123390198, Predicted Probability: 0.6514, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2088988870382309, Predicted Probability: 0.4480, Prediction: 0.0

Epoch 1/3:   5%|▍         | 192/4000 [01:51<38:13,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3058096468448639, Predicted Probability: 0.4241, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.46605950593948364, Predicted Probability: 0.3855, Prediction: 0.0

Epoch 1/3:   5%|▍         | 193/4000 [01:52<41:26,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4570440948009491, Predicted Probability: 0.3877, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.14880841970443726, Predicted Probability: 0.4629, Prediction: 0.0

Epoch 1/3:   5%|▍         | 194/4000 [01:53<42:58,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5198931097984314, Predicted Probability: 0.3729, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.1571231186389923, Predicted Probability: 0.5392, Prediction: 1.0

Epoch 1/3:   5%|▍         | 195/4000 [01:53<37:24,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.586824655532837, Predicted Probability: 0.8302, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.39070627093315125, Predicted Probability: 0.5965, Prediction: 1.0

Epoch 1/3:   5%|▍         | 196/4000 [01:53<33:15,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7544481158256531, Predicted Probability: 0.6801, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3201816082000732, Predicted Probability: 0.7892, Prediction: 1.0

Epoch 1/3:   5%|▍         | 197/4000 [01:54<38:18,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6293360590934753, Predicted Probability: 0.6523, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6162223815917969, Predicted Probability: 0.6494, Prediction: 1.0

Epoch 1/3:   5%|▍         | 198/4000 [01:55<37:15,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5959513187408447, Predicted Probability: 0.6447, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1393285989761353, Predicted Probability: 0.7576, Prediction: 1.0

Epoch 1/3:   5%|▍         | 199/4000 [01:56<41:45,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.016797831282019615, Predicted Probability: 0.4958, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.781796395778656, Predicted Probability: 0.6861, Prediction: 1.0

Epoch 1/3:   5%|▌         | 200/4000 [01:56<36:17,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.21204715967178345, Predicted Probability: 0.5528, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7455906867980957, Predicted Probability: 0.9397, Prediction: 1.0

Epoch 1/3:   5%|▌         | 201/4000 [01:57<39:16,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.06986173987388611, Predicted Probability: 0.4825, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.052370525896549225, Predicted Probability: 0.4869, Prediction: 0.0

Epoch 1/3:   5%|▌         | 202/4000 [01:57<42:49,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.15910151600837708, Predicted Probability: 0.4603, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.24456793069839478, Predicted Probability: 0.5608, Prediction: 1.0

Epoch 1/3:   5%|▌         | 203/4000 [01:58<44:40,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.19614170491695404, Predicted Probability: 0.4511, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.24797400832176208, Predicted Probability: 0.4383, Prediction: 0.0

Epoch 1/3:   5%|▌         | 204/4000 [01:59<41:54,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.4235266447067261, Predicted Probability: 0.3957, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.1615033894777298, Predicted Probability: 0.4597, Prediction: 0.0

Epoch 1/3:   5%|▌         | 205/4000 [02:00<44:55,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2181435376405716, Predicted Probability: 0.4457, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4182247817516327, Predicted Probability: 0.3969, Prediction: 0.0

Epoch 1/3:   5%|▌         | 206/4000 [02:00<46:44,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.4605555236339569, Predicted Probability: 0.3869, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.42125147581100464, Predicted Probability: 0.3962, Prediction: 0.0

Epoch 1/3:   5%|▌         | 207/4000 [02:01<47:17,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.25912824273109436, Predicted Probability: 0.4356, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.48685383796691895, Predicted Probability: 0.3806, Prediction: 0.0

Epoch 1/3:   5%|▌         | 209/4000 [02:02<32:42,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.141156405210495, Predicted Probability: 0.4648, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.27094677090644836, Predicted Probability: 0.4327, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.08275263011455536, Predicted Probability: 0.5207, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.10490832477807999, Predicted Probability: 0.5262, Prediction: 1.0

Epoch 1/3:   5%|▌         | 210/4000 [02:02<33:21,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3955281376838684, Predicted Probability: 0.4024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.22011148929595947, Predicted Probability: 0.4452, Prediction: 0.0

Epoch 1/3:   5%|▌         | 211/4000 [02:03<39:03,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5959466695785522, Predicted Probability: 0.3553, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.539191484451294, Predicted Probability: 0.3684, Prediction: 0.0

Epoch 1/3:   5%|▌         | 212/4000 [02:04<43:03,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5442283153533936, Predicted Probability: 0.3672, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6059902906417847, Predicted Probability: 0.3530, Prediction: 0.0

Epoch 1/3:   5%|▌         | 213/4000 [02:05<45:05,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6117660403251648, Predicted Probability: 0.3517, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.1860266625881195, Predicted Probability: 0.4536, Prediction: 0.0

Epoch 1/3:   5%|▌         | 214/4000 [02:05<38:26,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.13752111792564392, Predicted Probability: 0.4657, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.0026800537016242743, Predicted Probability: 0.4993, Prediction: 0.0

Epoch 1/3:   5%|▌         | 216/4000 [02:06<27:41,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.10718544572591782, Predicted Probability: 0.4732, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.21265500783920288, Predicted Probability: 0.4470, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.03729386627674103, Predicted Probability: 0.5093, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.07848990708589554, Predicted Probability: 0.5196, Prediction: 1.0

Epoch 1/3:   5%|▌         | 217/4000 [02:07<33:42,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.16554662585258484, Predicted Probability: 0.4587, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5868268013000488, Predicted Probability: 0.3574, Prediction: 0.0

Epoch 1/3:   5%|▌         | 218/4000 [02:07<37:26,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.13921129703521729, Predicted Probability: 0.4653, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5814510583877563, Predicted Probability: 0.3586, Prediction: 0.0

Epoch 1/3:   5%|▌         | 219/4000 [02:08<42:33,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5300283432006836, Predicted Probability: 0.3705, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5807212591171265, Predicted Probability: 0.3588, Prediction: 0.0

Epoch 1/3:   6%|▌         | 220/4000 [02:09<43:43,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.16899044811725616, Predicted Probability: 0.4579, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.48146921396255493, Predicted Probability: 0.3819, Prediction: 0.0

Epoch 1/3:   6%|▌         | 221/4000 [02:10<45:42,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5185099244117737, Predicted Probability: 0.3732, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.381023108959198, Predicted Probability: 0.4059, Prediction: 0.0

Epoch 1/3:   6%|▌         | 222/4000 [02:10<45:54,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2693372070789337, Predicted Probability: 0.4331, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5138937830924988, Predicted Probability: 0.3743, Prediction: 0.0

Epoch 1/3:   6%|▌         | 223/4000 [02:11<42:38,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5435662865638733, Predicted Probability: 0.3674, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3316480219364166, Predicted Probability: 0.4178, Prediction: 0.0

Epoch 1/3:   6%|▌         | 224/4000 [02:11<38:17,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.22845149040222168, Predicted Probability: 0.4431, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.1521759331226349, Predicted Probability: 0.5380, Prediction: 1.0

Epoch 1/3:   6%|▌         | 225/4000 [02:12<30:37,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.24276190996170044, Predicted Probability: 0.5604, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.02129010483622551, Predicted Probability: 0.4947, Prediction: 0.0

Epoch 1/3:   6%|▌         | 226/4000 [02:12<36:58,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5869577527046204, Predicted Probability: 0.3573, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5998156070709229, Predicted Probability: 0.3544, Prediction: 0.0

Epoch 1/3:   6%|▌         | 227/4000 [02:13<33:15,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.07701639086008072, Predicted Probability: 0.4808, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.15305748581886292, Predicted Probability: 0.4618, Prediction: 0.0

Epoch 1/3:   6%|▌         | 228/4000 [02:13<27:08,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3152795433998108, Predicted Probability: 0.5782, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.16804192960262299, Predicted Probability: 0.5419, Prediction: 1.0

Epoch 1/3:   6%|▌         | 229/4000 [02:13<25:50,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5949222445487976, Predicted Probability: 0.3555, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1813182234764099, Predicted Probability: 0.5452, Prediction: 1.0

Epoch 1/3:   6%|▌         | 230/4000 [02:14<29:21,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.575036346912384, Predicted Probability: 0.3601, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.018972324207425117, Predicted Probability: 0.4953, Prediction: 0.0

Epoch 1/3:   6%|▌         | 231/4000 [02:14<27:21,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3816584050655365, Predicted Probability: 0.4057, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.04277266189455986, Predicted Probability: 0.5107, Prediction: 1.0

Epoch 1/3:   6%|▌         | 232/4000 [02:15<33:58,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5677688121795654, Predicted Probability: 0.3618, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.020368702709674835, Predicted Probability: 0.4949, Prediction: 0.0

Epoch 1/3:   6%|▌         | 233/4000 [02:16<38:04,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.01605788618326187, Predicted Probability: 0.4960, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6281287670135498, Predicted Probability: 0.3479, Prediction: 0.0

Epoch 1/3:   6%|▌         | 234/4000 [02:16<33:34,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.026206227019429207, Predicted Probability: 0.4934, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.15120014548301697, Predicted Probability: 0.4623, Prediction: 0.0

Epoch 1/3:   6%|▌         | 235/4000 [02:17<30:13,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.09164100885391235, Predicted Probability: 0.5229, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2956926226615906, Predicted Probability: 0.4266, Prediction: 0.0

Epoch 1/3:   6%|▌         | 236/4000 [02:17<25:06,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.223781019449234, Predicted Probability: 0.4443, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1331380009651184, Predicted Probability: 0.5332, Prediction: 1.0

Epoch 1/3:   6%|▌         | 237/4000 [02:17<25:46,  2.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.001578167313709855, Predicted Probability: 0.5004, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4417381286621094, Predicted Probability: 0.3913, Prediction: 0.0

Epoch 1/3:   6%|▌         | 238/4000 [02:18<28:22,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.24670721590518951, Predicted Probability: 0.4386, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2567867934703827, Predicted Probability: 0.4362, Prediction: 0.0

Epoch 1/3:   6%|▌         | 239/4000 [02:18<28:30,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6354025602340698, Predicted Probability: 0.3463, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.1904946267604828, Predicted Probability: 0.4525, Prediction: 0.0

Epoch 1/3:   6%|▌         | 240/4000 [02:19<34:08,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5682103633880615, Predicted Probability: 0.3616, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.016371333971619606, Predicted Probability: 0.5041, Prediction: 1.0

Epoch 1/3:   6%|▌         | 241/4000 [02:19<30:44,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5098404884338379, Predicted Probability: 0.3752, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.09620886296033859, Predicted Probability: 0.5240, Prediction: 1.0

Epoch 1/3:   6%|▌         | 242/4000 [02:20<31:34,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.12013242393732071, Predicted Probability: 0.4700, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3901957869529724, Predicted Probability: 0.4037, Prediction: 0.0

Epoch 1/3:   6%|▌         | 243/4000 [02:20<26:01,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1439417004585266, Predicted Probability: 0.5359, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.12326198071241379, Predicted Probability: 0.5308, Prediction: 1.0

Epoch 1/3:   6%|▌         | 244/4000 [02:21<32:15,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.09844553470611572, Predicted Probability: 0.4754, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6725426316261292, Predicted Probability: 0.3379, Prediction: 0.0

Epoch 1/3:   6%|▌         | 245/4000 [02:21<29:25,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1515471637248993, Predicted Probability: 0.5378, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1706598848104477, Predicted Probability: 0.4574, Prediction: 0.0

Epoch 1/3:   6%|▌         | 246/4000 [02:22<36:32,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.49831217527389526, Predicted Probability: 0.3779, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6157257556915283, Predicted Probability: 0.3508, Prediction: 0.0

Epoch 1/3:   6%|▌         | 247/4000 [02:23<36:06,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4019477963447571, Predicted Probability: 0.4008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.055311527103185654, Predicted Probability: 0.4862, Prediction: 0.0

Epoch 1/3:   6%|▌         | 248/4000 [02:23<40:00,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6550846099853516, Predicted Probability: 0.3418, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2556089460849762, Predicted Probability: 0.4364, Prediction: 0.0

Epoch 1/3:   6%|▌         | 249/4000 [02:24<35:02,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3244589865207672, Predicted Probability: 0.4196, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.07907039672136307, Predicted Probability: 0.4802, Prediction: 0.0

Epoch 1/3:   6%|▋         | 250/4000 [02:25<39:24,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.461853563785553, Predicted Probability: 0.3865, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6932905316352844, Predicted Probability: 0.3333, Prediction: 0.0

Epoch 1/3:   6%|▋         | 251/4000 [02:25<34:27,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.28091537952423096, Predicted Probability: 0.4302, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.0673275887966156, Predicted Probability: 0.5168, Prediction: 1.0

Epoch 1/3:   6%|▋         | 252/4000 [02:25<31:18,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.10396821051836014, Predicted Probability: 0.4740, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.023729803040623665, Predicted Probability: 0.5059, Prediction: 1.0

Epoch 1/3:   6%|▋         | 253/4000 [02:26<28:34,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.03987312689423561, Predicted Probability: 0.4900, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.08385122567415237, Predicted Probability: 0.4790, Prediction: 0.0

Epoch 1/3:   6%|▋         | 254/4000 [02:26<33:35,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6847770810127258, Predicted Probability: 0.3352, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.039148833602666855, Predicted Probability: 0.4902, Prediction: 0.0

Epoch 1/3:   6%|▋         | 255/4000 [02:27<34:07,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.40122994780540466, Predicted Probability: 0.4010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5100115537643433, Predicted Probability: 0.3752, Prediction: 0.0

Epoch 1/3:   6%|▋         | 256/4000 [02:28<34:06,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3373466730117798, Predicted Probability: 0.4165, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.1123577281832695, Predicted Probability: 0.4719, Prediction: 0.0

Epoch 1/3:   6%|▋         | 257/4000 [02:28<30:47,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.14426100254058838, Predicted Probability: 0.5360, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.33171120285987854, Predicted Probability: 0.4178, Prediction: 0.0

Epoch 1/3:   6%|▋         | 258/4000 [02:29<35:07,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.13780434429645538, Predicted Probability: 0.4656, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7084219455718994, Predicted Probability: 0.3299, Prediction: 0.0

Epoch 1/3:   6%|▋         | 259/4000 [02:29<38:32,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.677425742149353, Predicted Probability: 0.3368, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.03562862426042557, Predicted Probability: 0.4911, Prediction: 0.0

Epoch 1/3:   6%|▋         | 260/4000 [02:30<40:30,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.09697538614273071, Predicted Probability: 0.4758, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.669177770614624, Predicted Probability: 0.3387, Prediction: 0.0

Epoch 1/3:   7%|▋         | 261/4000 [02:30<32:08,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.090537428855896, Predicted Probability: 0.4774, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.12480003386735916, Predicted Probability: 0.5312, Prediction: 1.0

Epoch 1/3:   7%|▋         | 262/4000 [02:31<32:39,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8017066717147827, Predicted Probability: 0.3097, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.15284833312034607, Predicted Probability: 0.4619, Prediction: 0.0

Epoch 1/3:   7%|▋         | 263/4000 [02:32<36:53,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.06787745654582977, Predicted Probability: 0.5170, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5547344088554382, Predicted Probability: 0.3648, Prediction: 0.0

Epoch 1/3:   7%|▋         | 264/4000 [02:32<29:45,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.12713739275932312, Predicted Probability: 0.5317, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.19900114834308624, Predicted Probability: 0.4504, Prediction: 0.0

Epoch 1/3:   7%|▋         | 265/4000 [02:33<34:09,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7675186991691589, Predicted Probability: 0.3170, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.05558318644762039, Predicted Probability: 0.5139, Prediction: 1.0

Epoch 1/3:   7%|▋         | 266/4000 [02:33<30:52,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.05640508979558945, Predicted Probability: 0.5141, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.233094722032547, Predicted Probability: 0.4420, Prediction: 0.0

Epoch 1/3:   7%|▋         | 267/4000 [02:34<37:23,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6438150405883789, Predicted Probability: 0.3444, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6067345142364502, Predicted Probability: 0.3528, Prediction: 0.0

Epoch 1/3:   7%|▋         | 268/4000 [02:35<39:55,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.23240165412425995, Predicted Probability: 0.4422, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6636649966239929, Predicted Probability: 0.3399, Prediction: 0.0

Epoch 1/3:   7%|▋         | 269/4000 [02:35<42:10,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.668796181678772, Predicted Probability: 0.3388, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.04972988739609718, Predicted Probability: 0.4876, Prediction: 0.0

Epoch 1/3:   7%|▋         | 270/4000 [02:36<36:31,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.30298709869384766, Predicted Probability: 0.4248, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7034370303153992, Predicted Probability: 0.3311, Prediction: 0.0

Epoch 1/3:   7%|▋         | 271/4000 [02:36<39:59,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8254451751708984, Predicted Probability: 0.3046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.19028380513191223, Predicted Probability: 0.5474, Prediction: 1.0

Epoch 1/3:   7%|▋         | 272/4000 [02:37<36:11,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.11084217578172684, Predicted Probability: 0.4723, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7421883940696716, Predicted Probability: 0.3225, Prediction: 0.0

Epoch 1/3:   7%|▋         | 273/4000 [02:37<35:44,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.08826585859060287, Predicted Probability: 0.4779, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4409118592739105, Predicted Probability: 0.3915, Prediction: 0.0

Epoch 1/3:   7%|▋         | 274/4000 [02:38<40:00,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7548032999038696, Predicted Probability: 0.3198, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3670600354671478, Predicted Probability: 0.4093, Prediction: 0.0

Epoch 1/3:   7%|▋         | 275/4000 [02:39<34:57,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.013070251792669296, Predicted Probability: 0.4967, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.25012636184692383, Predicted Probability: 0.5622, Prediction: 1.0

Epoch 1/3:   7%|▋         | 276/4000 [02:39<31:15,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.004683258943259716, Predicted Probability: 0.5012, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.23837965726852417, Predicted Probability: 0.5593, Prediction: 1.0

Epoch 1/3:   7%|▋         | 277/4000 [02:40<35:24,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6990087032318115, Predicted Probability: 0.3320, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2024725377559662, Predicted Probability: 0.5504, Prediction: 1.0

Epoch 1/3:   7%|▋         | 278/4000 [02:40<28:41,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.06728529930114746, Predicted Probability: 0.4832, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.00415395013988018, Predicted Probability: 0.4990, Prediction: 0.0

Epoch 1/3:   7%|▋         | 279/4000 [02:40<27:07,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1246752142906189, Predicted Probability: 0.5311, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.15859562158584595, Predicted Probability: 0.4604, Prediction: 0.0

Epoch 1/3:   7%|▋         | 280/4000 [02:41<25:53,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1748320609331131, Predicted Probability: 0.5436, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -9.487786883255467e-05, Predicted Probability: 0.5000, Prediction: 0.0

Epoch 1/3:   7%|▋         | 281/4000 [02:41<24:52,  2.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.24815545976161957, Predicted Probability: 0.4383, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.14684157073497772, Predicted Probability: 0.5366, Prediction: 1.0

Epoch 1/3:   7%|▋         | 282/4000 [02:42<30:39,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.14877638220787048, Predicted Probability: 0.5371, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6426181793212891, Predicted Probability: 0.3447, Prediction: 0.0

Epoch 1/3:   7%|▋         | 283/4000 [02:42<28:42,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.07666774094104767, Predicted Probability: 0.4808, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.22798947989940643, Predicted Probability: 0.4432, Prediction: 0.0

Epoch 1/3:   7%|▋         | 284/4000 [02:43<34:39,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6754271388053894, Predicted Probability: 0.3373, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.46875, Predicted Probability: 0.3849, Prediction: 0.0

Epoch 1/3:   7%|▋         | 285/4000 [02:43<28:01,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.23856975138187408, Predicted Probability: 0.5594, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3983567953109741, Predicted Probability: 0.5983, Prediction: 1.0

Epoch 1/3:   7%|▋         | 286/4000 [02:44<33:29,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.58171546459198, Predicted Probability: 0.3585, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.02862704172730446, Predicted Probability: 0.5072, Prediction: 1.0

Epoch 1/3:   7%|▋         | 287/4000 [02:44<30:43,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.10810744017362595, Predicted Probability: 0.4730, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.16106697916984558, Predicted Probability: 0.4598, Prediction: 0.0

Epoch 1/3:   7%|▋         | 288/4000 [02:45<34:50,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.20584087073802948, Predicted Probability: 0.5513, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.249461367726326, Predicted Probability: 0.4380, Prediction: 0.0

Epoch 1/3:   7%|▋         | 289/4000 [02:45<31:21,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2515104115009308, Predicted Probability: 0.4375, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.24608966708183289, Predicted Probability: 0.5612, Prediction: 1.0

Epoch 1/3:   7%|▋         | 290/4000 [02:46<35:38,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.20687632262706757, Predicted Probability: 0.5515, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5746500492095947, Predicted Probability: 0.3602, Prediction: 0.0

Epoch 1/3:   7%|▋         | 291/4000 [02:46<31:47,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2183864712715149, Predicted Probability: 0.5544, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.12369648367166519, Predicted Probability: 0.5309, Prediction: 1.0

Epoch 1/3:   7%|▋         | 292/4000 [02:47<35:41,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5084065198898315, Predicted Probability: 0.3756, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.11029863357543945, Predicted Probability: 0.4725, Prediction: 0.0

Epoch 1/3:   7%|▋         | 293/4000 [02:48<36:18,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2117782086133957, Predicted Probability: 0.4473, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.027308659628033638, Predicted Probability: 0.5068, Prediction: 1.0

Epoch 1/3:   7%|▋         | 295/4000 [02:48<26:09,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.24229156970977783, Predicted Probability: 0.5603, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.686183512210846, Predicted Probability: 0.3349, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 0.30886363983154297, Predicted Probability: 0.5766, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2446427047252655, Predicted Probability: 0.5609, Prediction: 1.0

Epoch 1/3:   7%|▋         | 296/4000 [02:49<31:54,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32958507537841797, Predicted Probability: 0.5817, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3909345865249634, Predicted Probability: 0.4035, Prediction: 0.0

Epoch 1/3:   7%|▋         | 297/4000 [02:50<36:00,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5272944569587708, Predicted Probability: 0.3711, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.21722275018692017, Predicted Probability: 0.5541, Prediction: 1.0

Epoch 1/3:   7%|▋         | 298/4000 [02:50<28:56,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.31462809443473816, Predicted Probability: 0.5780, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3225247859954834, Predicted Probability: 0.5799, Prediction: 1.0

Epoch 1/3:   7%|▋         | 299/4000 [02:51<30:14,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.11667193472385406, Predicted Probability: 0.4709, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1725643277168274, Predicted Probability: 0.5430, Prediction: 1.0

Epoch 1/3:   8%|▊         | 300/4000 [02:51<34:24,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7123864889144897, Predicted Probability: 0.3291, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1538802683353424, Predicted Probability: 0.5384, Prediction: 1.0

Epoch 1/3:   8%|▊         | 301/4000 [02:52<37:30,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6802197694778442, Predicted Probability: 0.3362, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2849469780921936, Predicted Probability: 0.5708, Prediction: 1.0

Epoch 1/3:   8%|▊         | 302/4000 [02:52<30:04,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32475560903549194, Predicted Probability: 0.5805, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.38424333930015564, Predicted Probability: 0.5949, Prediction: 1.0

Epoch 1/3:   8%|▊         | 303/4000 [02:53<27:55,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.14575739204883575, Predicted Probability: 0.4636, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3560364544391632, Predicted Probability: 0.5881, Prediction: 1.0

Epoch 1/3:   8%|▊         | 304/4000 [02:53<23:23,  2.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.17131967842578888, Predicted Probability: 0.5427, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4055081307888031, Predicted Probability: 0.6000, Prediction: 1.0

Epoch 1/3:   8%|▊         | 305/4000 [02:54<31:53,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3152759075164795, Predicted Probability: 0.4218, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6959981918334961, Predicted Probability: 0.3327, Prediction: 0.0

Epoch 1/3:   8%|▊         | 306/4000 [02:54<36:01,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.26431411504745483, Predicted Probability: 0.5657, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6180029511451721, Predicted Probability: 0.3502, Prediction: 0.0

Epoch 1/3:   8%|▊         | 307/4000 [02:55<39:53,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5530253648757935, Predicted Probability: 0.3652, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.17376306653022766, Predicted Probability: 0.5433, Prediction: 1.0

Epoch 1/3:   8%|▊         | 308/4000 [02:56<38:15,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4499833583831787, Predicted Probability: 0.3894, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.14047423005104065, Predicted Probability: 0.5351, Prediction: 1.0

Epoch 1/3:   8%|▊         | 309/4000 [02:56<39:55,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.23255017399787903, Predicted Probability: 0.5579, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5369415879249573, Predicted Probability: 0.3689, Prediction: 0.0

Epoch 1/3:   8%|▊         | 311/4000 [02:57<27:58,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.19144485890865326, Predicted Probability: 0.5477, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.26775968074798584, Predicted Probability: 0.5665, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 0.3276273012161255, Predicted Probability: 0.5812, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.40978842973709106, Predicted Probability: 0.6010, Prediction: 1.0

Epoch 1/3:   8%|▊         | 312/4000 [02:57<23:23,  2.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.27659639716148376, Predicted Probability: 0.5687, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1314997524023056, Predicted Probability: 0.5328, Prediction: 1.0

Epoch 1/3:   8%|▊         | 313/4000 [02:58<26:19,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2504802942276001, Predicted Probability: 0.4377, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.35363897681236267, Predicted Probability: 0.5875, Prediction: 1.0

Epoch 1/3:   8%|▊         | 314/4000 [02:58<25:21,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.004270413424819708, Predicted Probability: 0.4989, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.19349204003810883, Predicted Probability: 0.5482, Prediction: 1.0

Epoch 1/3:   8%|▊         | 315/4000 [02:59<31:04,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.22917203605175018, Predicted Probability: 0.5570, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8541980981826782, Predicted Probability: 0.2986, Prediction: 0.0

Epoch 1/3:   8%|▊         | 316/4000 [03:00<35:13,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.24958771467208862, Predicted Probability: 0.5621, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7508676648139954, Predicted Probability: 0.3206, Prediction: 0.0

Epoch 1/3:   8%|▊         | 317/4000 [03:00<31:51,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1734953671693802, Predicted Probability: 0.5433, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2904127538204193, Predicted Probability: 0.5721, Prediction: 1.0

Epoch 1/3:   8%|▊         | 318/4000 [03:01<32:24,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3824951648712158, Predicted Probability: 0.4055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.08171166479587555, Predicted Probability: 0.5204, Prediction: 1.0

Epoch 1/3:   8%|▊         | 319/4000 [03:01<30:46,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3277278244495392, Predicted Probability: 0.5812, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.04207374528050423, Predicted Probability: 0.4895, Prediction: 0.0

Epoch 1/3:   8%|▊         | 320/4000 [03:01<28:17,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8008703589439392, Predicted Probability: 0.3098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.42705392837524414, Predicted Probability: 0.6052, Prediction: 1.0

Epoch 1/3:   8%|▊         | 321/4000 [03:02<26:34,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4363957345485687, Predicted Probability: 0.6074, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3204177916049957, Predicted Probability: 0.5794, Prediction: 1.0

Epoch 1/3:   8%|▊         | 322/4000 [03:02<25:23,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.05238668620586395, Predicted Probability: 0.5131, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.42947524785995483, Predicted Probability: 0.6057, Prediction: 1.0

Epoch 1/3:   8%|▊         | 324/4000 [03:03<26:46,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5163329243659973, Predicted Probability: 0.3737, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5098463892936707, Predicted Probability: 0.3752, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 0.2561397850513458, Predicted Probability: 0.5637, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3322947323322296, Predicted Probability: 0.5823, Prediction: 1.0

Epoch 1/3:   8%|▊         | 325/4000 [03:04<25:40,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.17827269434928894, Predicted Probability: 0.5445, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3400217890739441, Predicted Probability: 0.5842, Prediction: 1.0

Epoch 1/3:   8%|▊         | 326/4000 [03:04<24:44,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.14221541583538055, Predicted Probability: 0.5355, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.34318745136260986, Predicted Probability: 0.5850, Prediction: 1.0

Epoch 1/3:   8%|▊         | 327/4000 [03:05<30:41,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3769184350967407, Predicted Probability: 0.4069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.26173168420791626, Predicted Probability: 0.5651, Prediction: 1.0

Epoch 1/3:   8%|▊         | 328/4000 [03:05<35:45,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4865878224372864, Predicted Probability: 0.3807, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.03894837200641632, Predicted Probability: 0.4903, Prediction: 0.0

Epoch 1/3:   8%|▊         | 329/4000 [03:06<35:23,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5681687593460083, Predicted Probability: 0.3617, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.23354527354240417, Predicted Probability: 0.4419, Prediction: 0.0

Epoch 1/3:   8%|▊         | 330/4000 [03:07<38:00,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5004014372825623, Predicted Probability: 0.3774, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.13777637481689453, Predicted Probability: 0.5344, Prediction: 1.0

Epoch 1/3:   8%|▊         | 331/4000 [03:07<41:08,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2258179783821106, Predicted Probability: 0.4438, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6018186807632446, Predicted Probability: 0.3539, Prediction: 0.0

Epoch 1/3:   8%|▊         | 332/4000 [03:08<42:31,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.042439937591552734, Predicted Probability: 0.4894, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.48670774698257446, Predicted Probability: 0.3807, Prediction: 0.0

Epoch 1/3:   8%|▊         | 333/4000 [03:09<36:43,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5797110795974731, Predicted Probability: 0.6410, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.052135467529296875, Predicted Probability: 0.4870, Prediction: 0.0

Epoch 1/3:   8%|▊         | 334/4000 [03:09<40:39,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8454866409301758, Predicted Probability: 0.3004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7172187566757202, Predicted Probability: 0.3280, Prediction: 0.0

Epoch 1/3:   8%|▊         | 335/4000 [03:10<41:44,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4039323329925537, Predicted Probability: 0.5996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4729892313480377, Predicted Probability: 0.3839, Prediction: 0.0

Epoch 1/3:   8%|▊         | 336/4000 [03:11<36:07,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.1857161670923233, Predicted Probability: 0.4537, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.36138060688972473, Predicted Probability: 0.5894, Prediction: 1.0

Epoch 1/3:   8%|▊         | 337/4000 [03:11<38:39,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.09507261216640472, Predicted Probability: 0.5238, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7172130942344666, Predicted Probability: 0.3280, Prediction: 0.0

Epoch 1/3:   8%|▊         | 338/4000 [03:12<40:44,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.35721105337142944, Predicted Probability: 0.5884, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6945539712905884, Predicted Probability: 0.3330, Prediction: 0.0

Epoch 1/3:   8%|▊         | 339/4000 [03:12<35:32,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4953342378139496, Predicted Probability: 0.6214, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.6343759298324585, Predicted Probability: 0.3465, Prediction: 0.0

Epoch 1/3:   8%|▊         | 340/4000 [03:13<38:40,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.83339524269104, Predicted Probability: 0.3029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.31771063804626465, Predicted Probability: 0.5788, Prediction: 1.0

Epoch 1/3:   9%|▊         | 341/4000 [03:14<36:41,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5124746561050415, Predicted Probability: 0.3746, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.48102545738220215, Predicted Probability: 0.6180, Prediction: 1.0

Epoch 1/3:   9%|▊         | 342/4000 [03:14<30:40,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5578444600105286, Predicted Probability: 0.6360, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.904609203338623, Predicted Probability: 0.2881, Prediction: 0.0

Epoch 1/3:   9%|▊         | 343/4000 [03:14<31:14,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.284030020236969, Predicted Probability: 0.5705, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3216346502304077, Predicted Probability: 0.4203, Prediction: 0.0

Epoch 1/3:   9%|▊         | 344/4000 [03:15<35:34,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7654260396957397, Predicted Probability: 0.3175, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4779561161994934, Predicted Probability: 0.6173, Prediction: 1.0

Epoch 1/3:   9%|▊         | 345/4000 [03:15<28:40,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.45364826917648315, Predicted Probability: 0.6115, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.19505634903907776, Predicted Probability: 0.5486, Prediction: 1.0

Epoch 1/3:   9%|▊         | 346/4000 [03:16<34:28,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4733622074127197, Predicted Probability: 0.3838, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.0324321985244751, Predicted Probability: 0.4919, Prediction: 0.0

Epoch 1/3:   9%|▊         | 347/4000 [03:17<35:21,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8482450842857361, Predicted Probability: 0.2998, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.45163342356681824, Predicted Probability: 0.6110, Prediction: 1.0

Epoch 1/3:   9%|▊         | 348/4000 [03:17<29:46,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.31953656673431396, Predicted Probability: 0.5792, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.03551815077662468, Predicted Probability: 0.5089, Prediction: 1.0

Epoch 1/3:   9%|▊         | 349/4000 [03:18<35:45,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9184943437576294, Predicted Probability: 0.2853, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.03603850305080414, Predicted Probability: 0.5090, Prediction: 1.0

Epoch 1/3:   9%|▉         | 350/4000 [03:19<40:03,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.15538474917411804, Predicted Probability: 0.4612, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0055961608886719, Predicted Probability: 0.2678, Prediction: 0.0

Epoch 1/3:   9%|▉         | 351/4000 [03:19<38:13,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.6306785345077515, Predicted Probability: 0.3474, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5144142508506775, Predicted Probability: 0.3742, Prediction: 0.0

Epoch 1/3:   9%|▉         | 352/4000 [03:20<36:39,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.44972580671310425, Predicted Probability: 0.3894, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3910095691680908, Predicted Probability: 0.4035, Prediction: 0.0

Epoch 1/3:   9%|▉         | 353/4000 [03:20<29:20,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6330389976501465, Predicted Probability: 0.6532, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5267188549041748, Predicted Probability: 0.6287, Prediction: 1.0

Epoch 1/3:   9%|▉         | 354/4000 [03:21<34:34,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5499304533004761, Predicted Probability: 0.6341, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6569972634315491, Predicted Probability: 0.3414, Prediction: 0.0

Epoch 1/3:   9%|▉         | 355/4000 [03:21<30:54,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4898395836353302, Predicted Probability: 0.3799, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.30458471179008484, Predicted Probability: 0.5756, Prediction: 1.0

Epoch 1/3:   9%|▉         | 356/4000 [03:22<34:56,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7660683393478394, Predicted Probability: 0.3173, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3682146668434143, Predicted Probability: 0.5910, Prediction: 1.0

Epoch 1/3:   9%|▉         | 357/4000 [03:23<37:50,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.4168282449245453, Predicted Probability: 0.6027, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6774208545684814, Predicted Probability: 0.3368, Prediction: 0.0

Epoch 1/3:   9%|▉         | 358/4000 [03:23<33:12,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.504840075969696, Predicted Probability: 0.6236, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5059804320335388, Predicted Probability: 0.6239, Prediction: 1.0

Epoch 1/3:   9%|▉         | 359/4000 [03:23<28:10,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7144845724105835, Predicted Probability: 0.3286, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.48812150955200195, Predicted Probability: 0.6197, Prediction: 1.0

Epoch 1/3:   9%|▉         | 360/4000 [03:24<33:55,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0806716680526733, Predicted Probability: 0.2534, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.619371771812439, Predicted Probability: 0.3499, Prediction: 0.0

Epoch 1/3:   9%|▉         | 361/4000 [03:25<33:26,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.48453572392463684, Predicted Probability: 0.3812, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4573238492012024, Predicted Probability: 0.6124, Prediction: 1.0

Epoch 1/3:   9%|▉         | 362/4000 [03:25<37:27,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.47747406363487244, Predicted Probability: 0.6172, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0135997533798218, Predicted Probability: 0.2663, Prediction: 0.0

Epoch 1/3:   9%|▉         | 363/4000 [03:26<41:17,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3210119903087616, Predicted Probability: 0.4204, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9161127209663391, Predicted Probability: 0.2858, Prediction: 0.0

Epoch 1/3:   9%|▉         | 364/4000 [03:27<38:45,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7281061410903931, Predicted Probability: 0.3256, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.340393990278244, Predicted Probability: 0.4157, Prediction: 0.0

Epoch 1/3:   9%|▉         | 365/4000 [03:27<40:02,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9403465986251831, Predicted Probability: 0.2808, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.45626944303512573, Predicted Probability: 0.6121, Prediction: 1.0

Epoch 1/3:   9%|▉         | 366/4000 [03:28<35:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5936530828475952, Predicted Probability: 0.3558, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.46678128838539124, Predicted Probability: 0.3854, Prediction: 0.0

Epoch 1/3:   9%|▉         | 367/4000 [03:28<34:22,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.20560716092586517, Predicted Probability: 0.4488, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6097188591957092, Predicted Probability: 0.6479, Prediction: 1.0

Epoch 1/3:   9%|▉         | 368/4000 [03:29<37:18,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0095000267028809, Predicted Probability: 0.2671, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.40694302320480347, Predicted Probability: 0.6004, Prediction: 1.0

Epoch 1/3:   9%|▉         | 369/4000 [03:30<32:56,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.007175850216299295, Predicted Probability: 0.4982, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.48609933257102966, Predicted Probability: 0.6192, Prediction: 1.0

Epoch 1/3:   9%|▉         | 371/4000 [03:30<29:22,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5582714080810547, Predicted Probability: 0.6361, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9160839319229126, Predicted Probability: 0.2858, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.5863352417945862, Predicted Probability: 0.6425, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.23314741253852844, Predicted Probability: 0.5580, Prediction: 1.0

Epoch 1/3:   9%|▉         | 372/4000 [03:31<35:08,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0428268909454346, Predicted Probability: 0.2606, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6428431272506714, Predicted Probability: 0.3446, Prediction: 0.0

Epoch 1/3:   9%|▉         | 373/4000 [03:32<37:53,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.084424376487732, Predicted Probability: 0.2527, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4518815875053406, Predicted Probability: 0.6111, Prediction: 1.0

Epoch 1/3:   9%|▉         | 374/4000 [03:33<40:28,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0381486415863037, Predicted Probability: 0.2615, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.04742260277271271, Predicted Probability: 0.5119, Prediction: 1.0

Epoch 1/3:   9%|▉         | 375/4000 [03:34<42:31,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5116819143295288, Predicted Probability: 0.6252, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9947030544281006, Predicted Probability: 0.2700, Prediction: 0.0

Epoch 1/3:   9%|▉         | 376/4000 [03:34<44:30,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2015105485916138, Predicted Probability: 0.2312, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.231050968170166, Predicted Probability: 0.2260, Prediction: 0.0

Epoch 1/3:   9%|▉         | 377/4000 [03:35<37:53,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.6017577648162842, Predicted Probability: 0.3539, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8413560390472412, Predicted Probability: 0.3012, Prediction: 0.0

Epoch 1/3:   9%|▉         | 378/4000 [03:35<33:16,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.04046913608908653, Predicted Probability: 0.5101, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.40409526228904724, Predicted Probability: 0.5997, Prediction: 1.0

Epoch 1/3:   9%|▉         | 379/4000 [03:36<37:03,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1344690322875977, Predicted Probability: 0.2433, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.37687045335769653, Predicted Probability: 0.4069, Prediction: 0.0

Epoch 1/3:  10%|▉         | 380/4000 [03:36<29:38,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3700603246688843, Predicted Probability: 0.5915, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.00492238812148571, Predicted Probability: 0.5012, Prediction: 1.0

Epoch 1/3:  10%|▉         | 381/4000 [03:37<36:12,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.133047103881836, Predicted Probability: 0.2436, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8042830228805542, Predicted Probability: 0.3091, Prediction: 0.0

Epoch 1/3:  10%|▉         | 382/4000 [03:37<29:01,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3975500464439392, Predicted Probability: 0.5981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8727579712867737, Predicted Probability: 0.7053, Prediction: 1.0

Epoch 1/3:  10%|▉         | 383/4000 [03:38<26:58,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6485632658004761, Predicted Probability: 0.6567, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.23730869591236115, Predicted Probability: 0.5591, Prediction: 1.0

Epoch 1/3:  10%|▉         | 384/4000 [03:38<25:31,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.47269749641418457, Predicted Probability: 0.6160, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1812744438648224, Predicted Probability: 0.5452, Prediction: 1.0

Epoch 1/3:  10%|▉         | 385/4000 [03:38<24:41,  2.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8451457619667053, Predicted Probability: 0.3005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5142605900764465, Predicted Probability: 0.3742, Prediction: 0.0

Epoch 1/3:  10%|▉         | 386/4000 [03:39<23:54,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.37495875358581543, Predicted Probability: 0.4073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4577272832393646, Predicted Probability: 0.6125, Prediction: 1.0

Epoch 1/3:  10%|▉         | 387/4000 [03:39<30:54,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.125315546989441, Predicted Probability: 0.2450, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.055377520620822906, Predicted Probability: 0.5138, Prediction: 1.0

Epoch 1/3:  10%|▉         | 388/4000 [03:40<28:18,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7140234708786011, Predicted Probability: 0.3287, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7465776801109314, Predicted Probability: 0.6784, Prediction: 1.0

Epoch 1/3:  10%|▉         | 389/4000 [03:40<26:52,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.403556227684021, Predicted Probability: 0.5995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.47539687156677246, Predicted Probability: 0.3833, Prediction: 0.0

Epoch 1/3:  10%|▉         | 390/4000 [03:41<25:39,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2177744358778, Predicted Probability: 0.4458, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.19351091980934143, Predicted Probability: 0.5482, Prediction: 1.0

Epoch 1/3:  10%|▉         | 391/4000 [03:41<30:52,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4829510450363159, Predicted Probability: 0.6184, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0296096801757812, Predicted Probability: 0.2632, Prediction: 0.0

Epoch 1/3:  10%|▉         | 392/4000 [03:42<36:00,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1185743808746338, Predicted Probability: 0.2463, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.177417278289795, Predicted Probability: 0.2355, Prediction: 0.0

Epoch 1/3:  10%|▉         | 393/4000 [03:43<34:53,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5071496367454529, Predicted Probability: 0.6241, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.791203498840332, Predicted Probability: 0.3119, Prediction: 0.0

Epoch 1/3:  10%|▉         | 394/4000 [03:43<39:08,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0797765254974365, Predicted Probability: 0.2535, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4200630784034729, Predicted Probability: 0.6035, Prediction: 1.0

Epoch 1/3:  10%|▉         | 395/4000 [03:44<34:15,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5580562353134155, Predicted Probability: 0.6360, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4687531590461731, Predicted Probability: 0.6151, Prediction: 1.0

Epoch 1/3:  10%|▉         | 396/4000 [03:45<37:45,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8982048630714417, Predicted Probability: 0.2894, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.07017479836940765, Predicted Probability: 0.4825, Prediction: 0.0

Epoch 1/3:  10%|▉         | 397/4000 [03:45<36:12,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5106698870658875, Predicted Probability: 0.6250, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.21688023209571838, Predicted Probability: 0.4460, Prediction: 0.0

Epoch 1/3:  10%|▉         | 398/4000 [03:45<32:06,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.22436705231666565, Predicted Probability: 0.5559, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3460768163204193, Predicted Probability: 0.4143, Prediction: 0.0

Epoch 1/3:  10%|▉         | 399/4000 [03:46<35:29,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5014729499816895, Predicted Probability: 0.6228, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2758641242980957, Predicted Probability: 0.2183, Prediction: 0.0

Epoch 1/3:  10%|█         | 400/4000 [03:47<38:26,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6031633019447327, Predicted Probability: 0.6464, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.233289122581482, Predicted Probability: 0.2256, Prediction: 0.0

Epoch 1/3:  10%|█         | 401/4000 [03:48<39:59,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0184983015060425, Predicted Probability: 0.2653, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.45439016819000244, Predicted Probability: 0.6117, Prediction: 1.0

Epoch 1/3:  10%|█         | 402/4000 [03:48<36:06,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.12420465052127838, Predicted Probability: 0.5310, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.13193601369857788, Predicted Probability: 0.4671, Prediction: 0.0

Epoch 1/3:  10%|█         | 403/4000 [03:49<38:19,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7586978077888489, Predicted Probability: 0.3189, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5072215795516968, Predicted Probability: 0.6242, Prediction: 1.0

Epoch 1/3:  10%|█         | 404/4000 [03:49<33:56,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.418797105550766, Predicted Probability: 0.6032, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4490601420402527, Predicted Probability: 0.3896, Prediction: 0.0

Epoch 1/3:  10%|█         | 405/4000 [03:49<27:28,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.684274435043335, Predicted Probability: 0.6647, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4961082637310028, Predicted Probability: 0.6215, Prediction: 1.0

Epoch 1/3:  10%|█         | 406/4000 [03:50<33:47,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2624039947986603, Predicted Probability: 0.4348, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1847381591796875, Predicted Probability: 0.2342, Prediction: 0.0

Epoch 1/3:  10%|█         | 407/4000 [03:51<33:11,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.42900073528289795, Predicted Probability: 0.6056, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7449772357940674, Predicted Probability: 0.3219, Prediction: 0.0

Epoch 1/3:  10%|█         | 408/4000 [03:51<26:53,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.8690667748451233, Predicted Probability: 0.7046, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5476941466331482, Predicted Probability: 0.6336, Prediction: 1.0

Epoch 1/3:  10%|█         | 409/4000 [03:52<31:27,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.35678550601005554, Predicted Probability: 0.4117, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3722618520259857, Predicted Probability: 0.5920, Prediction: 1.0

Epoch 1/3:  10%|█         | 410/4000 [03:52<30:12,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.14889350533485413, Predicted Probability: 0.5372, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5702251195907593, Predicted Probability: 0.6388, Prediction: 1.0

Epoch 1/3:  10%|█         | 411/4000 [03:53<34:16,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5802552700042725, Predicted Probability: 0.6411, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6991698145866394, Predicted Probability: 0.3320, Prediction: 0.0

Epoch 1/3:  10%|█         | 412/4000 [03:53<30:45,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5140464901924133, Predicted Probability: 0.6258, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5401228070259094, Predicted Probability: 0.6318, Prediction: 1.0

Epoch 1/3:  10%|█         | 413/4000 [03:54<36:52,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6534926295280457, Predicted Probability: 0.6578, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9754749536514282, Predicted Probability: 0.2738, Prediction: 0.0

Epoch 1/3:  10%|█         | 414/4000 [03:55<33:56,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5426449179649353, Predicted Probability: 0.6324, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.17014376819133759, Predicted Probability: 0.4576, Prediction: 0.0

Epoch 1/3:  10%|█         | 415/4000 [03:55<30:18,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.07129912078380585, Predicted Probability: 0.4822, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7030217051506042, Predicted Probability: 0.6689, Prediction: 1.0

Epoch 1/3:  10%|█         | 416/4000 [03:55<27:51,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4406774640083313, Predicted Probability: 0.6084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.28986838459968567, Predicted Probability: 0.5720, Prediction: 1.0

Epoch 1/3:  10%|█         | 417/4000 [03:56<23:11,  2.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0582011938095093, Predicted Probability: 0.7423, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2799035906791687, Predicted Probability: 0.5695, Prediction: 1.0

Epoch 1/3:  10%|█         | 418/4000 [03:56<19:52,  3.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.009482397697865963, Predicted Probability: 0.5024, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4786117374897003, Predicted Probability: 0.6174, Prediction: 1.0

Epoch 1/3:  10%|█         | 419/4000 [03:56<27:09,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4993339478969574, Predicted Probability: 0.6223, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8812023401260376, Predicted Probability: 0.2929, Prediction: 0.0

Epoch 1/3:  10%|█         | 420/4000 [03:57<22:50,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7818413972854614, Predicted Probability: 0.6861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0760501623153687, Predicted Probability: 0.7457, Prediction: 1.0

Epoch 1/3:  11%|█         | 421/4000 [03:57<29:42,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5784550905227661, Predicted Probability: 0.3593, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.14940759539604187, Predicted Probability: 0.4627, Prediction: 0.0

Epoch 1/3:  11%|█         | 422/4000 [03:58<35:59,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4616157114505768, Predicted Probability: 0.3866, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1238911151885986, Predicted Probability: 0.2453, Prediction: 0.0

Epoch 1/3:  11%|█         | 423/4000 [03:59<38:32,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6970351934432983, Predicted Probability: 0.3325, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.013513579964637756, Predicted Probability: 0.4966, Prediction: 0.0

Epoch 1/3:  11%|█         | 424/4000 [04:00<40:17,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.579437255859375, Predicted Probability: 0.3591, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7981308698654175, Predicted Probability: 0.6896, Prediction: 1.0

Epoch 1/3:  11%|█         | 425/4000 [04:00<34:39,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9447908401489258, Predicted Probability: 0.7201, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.104936957359314, Predicted Probability: 0.7512, Prediction: 1.0

Epoch 1/3:  11%|█         | 426/4000 [04:01<30:55,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32399460673332214, Predicted Probability: 0.5803, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.684977114200592, Predicted Probability: 0.6648, Prediction: 1.0

Epoch 1/3:  11%|█         | 427/4000 [04:01<32:33,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5178342461585999, Predicted Probability: 0.3734, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.060673706233501434, Predicted Probability: 0.4848, Prediction: 0.0

Epoch 1/3:  11%|█         | 428/4000 [04:01<26:26,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6115713715553284, Predicted Probability: 0.6483, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7754296660423279, Predicted Probability: 0.6847, Prediction: 1.0

Epoch 1/3:  11%|█         | 429/4000 [04:02<24:59,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5141887068748474, Predicted Probability: 0.6258, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.514911413192749, Predicted Probability: 0.3740, Prediction: 0.0

Epoch 1/3:  11%|█         | 430/4000 [04:02<24:05,  2.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4840972423553467, Predicted Probability: 0.3813, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.701859176158905, Predicted Probability: 0.6686, Prediction: 1.0

Epoch 1/3:  11%|█         | 431/4000 [04:02<23:37,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7344964742660522, Predicted Probability: 0.6758, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5868609547615051, Predicted Probability: 0.3574, Prediction: 0.0

Epoch 1/3:  11%|█         | 432/4000 [04:03<24:32,  2.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1863551139831543, Predicted Probability: 0.2339, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.07954654842615128, Predicted Probability: 0.5199, Prediction: 1.0

Epoch 1/3:  11%|█         | 433/4000 [04:03<23:48,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3809587061405182, Predicted Probability: 0.5941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2779364585876465, Predicted Probability: 0.5690, Prediction: 1.0

Epoch 1/3:  11%|█         | 434/4000 [04:04<29:36,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5351024866104126, Predicted Probability: 0.3693, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8553025126457214, Predicted Probability: 0.7017, Prediction: 1.0

Epoch 1/3:  11%|█         | 435/4000 [04:05<30:23,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7032489776611328, Predicted Probability: 0.6689, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7409622073173523, Predicted Probability: 0.3228, Prediction: 0.0

Epoch 1/3:  11%|█         | 436/4000 [04:05<25:59,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9449805021286011, Predicted Probability: 0.7201, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9422366619110107, Predicted Probability: 0.2804, Prediction: 0.0

Epoch 1/3:  11%|█         | 437/4000 [04:06<35:25,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3847270607948303, Predicted Probability: 0.5950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3225531578063965, Predicted Probability: 0.2104, Prediction: 0.0

Epoch 1/3:  11%|█         | 438/4000 [04:06<31:50,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6130697131156921, Predicted Probability: 0.6486, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3086131811141968, Predicted Probability: 0.4235, Prediction: 0.0

Epoch 1/3:  11%|█         | 439/4000 [04:06<27:06,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6764606833457947, Predicted Probability: 0.6629, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.45818260312080383, Predicted Probability: 0.3874, Prediction: 0.0

Epoch 1/3:  11%|█         | 440/4000 [04:07<31:55,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.695850670337677, Predicted Probability: 0.6673, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4796815514564514, Predicted Probability: 0.3823, Prediction: 0.0

Epoch 1/3:  11%|█         | 441/4000 [04:08<32:11,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.302999347448349, Predicted Probability: 0.5752, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.13496853411197662, Predicted Probability: 0.5337, Prediction: 1.0

Epoch 1/3:  11%|█         | 442/4000 [04:09<38:44,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0443373918533325, Predicted Probability: 0.2603, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6135681867599487, Predicted Probability: 0.3512, Prediction: 0.0

Epoch 1/3:  11%|█         | 443/4000 [04:09<40:38,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.46780097484588623, Predicted Probability: 0.6149, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1798290014266968, Predicted Probability: 0.2351, Prediction: 0.0

Epoch 1/3:  11%|█         | 444/4000 [04:10<32:14,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8566048741340637, Predicted Probability: 0.7020, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2033004760742188, Predicted Probability: 0.7691, Prediction: 1.0

Epoch 1/3:  11%|█         | 445/4000 [04:10<29:10,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.03126153349876404, Predicted Probability: 0.4922, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.905032217502594, Predicted Probability: 0.7120, Prediction: 1.0

Epoch 1/3:  11%|█         | 446/4000 [04:10<26:52,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9189086556434631, Predicted Probability: 0.7148, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.921431303024292, Predicted Probability: 0.2847, Prediction: 0.0

Epoch 1/3:  11%|█         | 447/4000 [04:11<31:34,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8005191087722778, Predicted Probability: 0.3099, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6535470485687256, Predicted Probability: 0.6578, Prediction: 1.0

Epoch 1/3:  11%|█         | 448/4000 [04:11<28:48,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6343233585357666, Predicted Probability: 0.6535, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.70688396692276, Predicted Probability: 0.6697, Prediction: 1.0

Epoch 1/3:  11%|█         | 449/4000 [04:12<30:59,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.04019174352288246, Predicted Probability: 0.5100, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6972618699073792, Predicted Probability: 0.6676, Prediction: 1.0

Epoch 1/3:  11%|█▏        | 450/4000 [04:13<29:25,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.4296438694000244, Predicted Probability: 0.3942, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7203213572502136, Predicted Probability: 0.6727, Prediction: 1.0

Epoch 1/3:  11%|█▏        | 451/4000 [04:13<34:13,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0350921154022217, Predicted Probability: 0.2621, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4572044610977173, Predicted Probability: 0.6124, Prediction: 1.0

Epoch 1/3:  11%|█▏        | 452/4000 [04:14<30:32,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.07422464340925217, Predicted Probability: 0.5185, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7557268738746643, Predicted Probability: 0.3196, Prediction: 0.0

Epoch 1/3:  11%|█▏        | 453/4000 [04:14<31:04,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.4583284854888916, Predicted Probability: 0.6126, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6003299355506897, Predicted Probability: 0.3543, Prediction: 0.0

Epoch 1/3:  11%|█▏        | 454/4000 [04:15<28:22,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9520640969276428, Predicted Probability: 0.7215, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6748146414756775, Predicted Probability: 0.3374, Prediction: 0.0

Epoch 1/3:  11%|█▏        | 455/4000 [04:15<32:52,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6643690466880798, Predicted Probability: 0.6602, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8981956243515015, Predicted Probability: 0.2894, Prediction: 0.0

Epoch 1/3:  11%|█▏        | 456/4000 [04:16<35:57,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2555642127990723, Predicted Probability: 0.2217, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.631543755531311, Predicted Probability: 0.6528, Prediction: 1.0

Epoch 1/3:  11%|█▏        | 457/4000 [04:17<38:55,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5016087293624878, Predicted Probability: 0.6228, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2836252450942993, Predicted Probability: 0.2169, Prediction: 0.0

Epoch 1/3:  11%|█▏        | 458/4000 [04:17<37:06,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.12726853787899017, Predicted Probability: 0.5318, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7999082803726196, Predicted Probability: 0.3100, Prediction: 0.0

Epoch 1/3:  11%|█▏        | 459/4000 [04:18<35:35,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8038942217826843, Predicted Probability: 0.3092, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0436477661132812, Predicted Probability: 0.7396, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 460/4000 [04:19<37:47,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8142780065536499, Predicted Probability: 0.6930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.191019892692566, Predicted Probability: 0.2331, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 461/4000 [04:19<41:28,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0133472681045532, Predicted Probability: 0.2663, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1123318672180176, Predicted Probability: 0.2474, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 462/4000 [04:20<35:49,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6187103986740112, Predicted Probability: 0.6499, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3993018567562103, Predicted Probability: 0.4015, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 463/4000 [04:21<38:40,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7576846480369568, Predicted Probability: 0.6809, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9389212131500244, Predicted Probability: 0.2811, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 464/4000 [04:21<33:41,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8866278529167175, Predicted Probability: 0.7082, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6253731846809387, Predicted Probability: 0.6514, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 465/4000 [04:22<37:02,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1534223556518555, Predicted Probability: 0.2399, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6836948394775391, Predicted Probability: 0.6646, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 466/4000 [04:22<32:27,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6816865801811218, Predicted Probability: 0.6641, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5322182178497314, Predicted Probability: 0.3700, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 467/4000 [04:23<32:32,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5273618102073669, Predicted Probability: 0.3711, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.18142421543598175, Predicted Probability: 0.4548, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 468/4000 [04:23<36:42,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9524404406547546, Predicted Probability: 0.2784, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1173462867736816, Predicted Probability: 0.2465, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 469/4000 [04:24<32:29,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4735450744628906, Predicted Probability: 0.6162, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9906468391418457, Predicted Probability: 0.7292, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 470/4000 [04:24<27:30,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.0815465450286865, Predicted Probability: 0.7468, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9416600465774536, Predicted Probability: 0.7194, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 471/4000 [04:25<32:09,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5868388414382935, Predicted Probability: 0.6426, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4244707822799683, Predicted Probability: 0.1940, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 472/4000 [04:26<35:50,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4994029998779297, Predicted Probability: 0.1825, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5823948979377747, Predicted Probability: 0.6416, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 473/4000 [04:26<28:39,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7712717652320862, Predicted Probability: 0.6838, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3408835232257843, Predicted Probability: 0.5844, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 475/4000 [04:26<22:13,  2.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8053104281425476, Predicted Probability: 0.3089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.42688554525375366, Predicted Probability: 0.6051, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 0.9308359622955322, Predicted Probability: 0.7172, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7688185572624207, Predicted Probability: 0.6833, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 476/4000 [04:27<29:55,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4670851230621338, Predicted Probability: 0.1874, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4151079654693604, Predicted Probability: 0.1954, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 477/4000 [04:28<34:22,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.12706293165683746, Predicted Probability: 0.5317, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.599376916885376, Predicted Probability: 0.1681, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 478/4000 [04:28<30:40,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9918699860572815, Predicted Probability: 0.7295, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3774273097515106, Predicted Probability: 0.5933, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 479/4000 [04:29<34:44,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3639780282974243, Predicted Probability: 0.4100, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.459436058998108, Predicted Probability: 0.1886, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 480/4000 [04:30<31:00,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.12288901209831238, Predicted Probability: 0.4693, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6100048422813416, Predicted Probability: 0.6479, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 481/4000 [04:30<25:22,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4278620779514313, Predicted Probability: 0.6054, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.533117413520813, Predicted Probability: 0.6302, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 482/4000 [04:30<30:14,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6585174798965454, Predicted Probability: 0.6589, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5688768625259399, Predicted Probability: 0.3615, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 483/4000 [04:31<24:52,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9102185368537903, Predicted Probability: 0.7130, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.001180778257548809, Predicted Probability: 0.5003, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 484/4000 [04:31<32:12,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7150894403457642, Predicted Probability: 0.1525, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4375953674316406, Predicted Probability: 0.1919, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 485/4000 [04:32<29:08,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5075929760932922, Predicted Probability: 0.3758, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3424966037273407, Predicted Probability: 0.4152, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 486/4000 [04:32<30:13,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9217091798782349, Predicted Probability: 0.2846, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3588525950908661, Predicted Probability: 0.5888, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 487/4000 [04:33<36:00,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4176651239395142, Predicted Probability: 0.1950, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0891838073730469, Predicted Probability: 0.2518, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 488/4000 [04:33<28:52,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7736135721206665, Predicted Probability: 0.6843, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3317870497703552, Predicted Probability: 0.4178, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 489/4000 [04:34<34:15,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.627311110496521, Predicted Probability: 0.6519, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.908197283744812, Predicted Probability: 0.2874, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 490/4000 [04:35<30:27,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32830122113227844, Predicted Probability: 0.5813, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.12543326616287231, Predicted Probability: 0.5313, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 491/4000 [04:35<27:47,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5229513049125671, Predicted Probability: 0.6278, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6865532398223877, Predicted Probability: 0.6652, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 492/4000 [04:36<32:42,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2963781356811523, Predicted Probability: 0.2148, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6593018174171448, Predicted Probability: 0.6591, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 493/4000 [04:36<29:25,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6358548998832703, Predicted Probability: 0.6538, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4547346234321594, Predicted Probability: 0.6118, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 494/4000 [04:37<27:09,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.6167774796485901, Predicted Probability: 0.3505, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7639793753623962, Predicted Probability: 0.6822, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 495/4000 [04:37<32:08,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7298231720924377, Predicted Probability: 0.6748, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.16147780418396, Predicted Probability: 0.2384, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 496/4000 [04:38<35:05,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5749193429946899, Predicted Probability: 0.6399, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.432145118713379, Predicted Probability: 0.1928, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 497/4000 [04:39<38:13,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.506259560585022, Predicted Probability: 0.1815, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4351873993873596, Predicted Probability: 0.3929, Prediction: 0.0

Epoch 1/3:  12%|█▏        | 498/4000 [04:39<36:07,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.082956314086914, Predicted Probability: 0.2529, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9278825521469116, Predicted Probability: 0.7166, Prediction: 1.0

Epoch 1/3:  12%|█▏        | 499/4000 [04:40<38:04,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.06632018089294434, Predicted Probability: 0.5166, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1316076517105103, Predicted Probability: 0.2439, Prediction: 0.0

Epoch 1/3:  12%|█▎        | 500/4000 [04:41<39:10,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8837528228759766, Predicted Probability: 0.7076, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0771093368530273, Predicted Probability: 0.2541, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 501/4000 [04:41<35:14,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.24409876763820648, Predicted Probability: 0.5607, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.30873405933380127, Predicted Probability: 0.5766, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 502/4000 [04:42<37:23,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4171850383281708, Predicted Probability: 0.3972, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4677013158798218, Predicted Probability: 0.6148, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 503/4000 [04:43<39:06,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8692424297332764, Predicted Probability: 0.7046, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1754810810089111, Predicted Probability: 0.2359, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 504/4000 [04:43<36:56,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.25866636633872986, Predicted Probability: 0.4357, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.16605520248413086, Predicted Probability: 0.4586, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 505/4000 [04:44<39:37,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.880946159362793, Predicted Probability: 0.2930, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.46272629499435425, Predicted Probability: 0.6137, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 506/4000 [04:45<40:44,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.968233048915863, Predicted Probability: 0.2752, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.0924210473895073, Predicted Probability: 0.4769, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 507/4000 [04:45<41:04,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7551085352897644, Predicted Probability: 0.3197, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8532376289367676, Predicted Probability: 0.7012, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 508/4000 [04:46<38:29,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6429483294487, Predicted Probability: 0.6554, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9087638258934021, Predicted Probability: 0.2873, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 509/4000 [04:46<33:34,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8097006678581238, Predicted Probability: 0.6920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5726235508918762, Predicted Probability: 0.6394, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 510/4000 [04:47<30:13,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.005458950996399, Predicted Probability: 0.7321, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.013075731694698334, Predicted Probability: 0.5033, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 511/4000 [04:48<34:45,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1036627292633057, Predicted Probability: 0.2491, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.051499605178833, Predicted Probability: 0.7411, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 512/4000 [04:48<33:54,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2642080783843994, Predicted Probability: 0.5657, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3160425126552582, Predicted Probability: 0.5784, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 513/4000 [04:49<31:18,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6507998704910278, Predicted Probability: 0.6572, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8746572136878967, Predicted Probability: 0.7057, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 514/4000 [04:49<34:47,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8878439664840698, Predicted Probability: 0.7084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8794181942939758, Predicted Probability: 0.2933, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 515/4000 [04:50<37:37,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0966606140136719, Predicted Probability: 0.2504, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6694256067276001, Predicted Probability: 0.6614, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 516/4000 [04:51<39:34,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3115505576133728, Predicted Probability: 0.5773, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8421074151992798, Predicted Probability: 0.3011, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 517/4000 [04:51<34:14,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0603842735290527, Predicted Probability: 0.7428, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7983665466308594, Predicted Probability: 0.6896, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 518/4000 [04:52<33:46,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7758426070213318, Predicted Probability: 0.3152, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.28915536403656, Predicted Probability: 0.2160, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 519/4000 [04:52<36:42,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.19895601272583, Predicted Probability: 0.2317, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5846502780914307, Predicted Probability: 0.6421, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 520/4000 [04:53<29:16,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.467005968093872, Predicted Probability: 0.8126, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.87387615442276, Predicted Probability: 0.7056, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 522/4000 [04:54<28:52,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.525801658630371, Predicted Probability: 0.1786, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.665478229522705, Predicted Probability: 0.1590, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.9841221570968628, Predicted Probability: 0.7279, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8326452374458313, Predicted Probability: 0.6969, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 523/4000 [04:54<24:01,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8608561754226685, Predicted Probability: 0.7028, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7686667442321777, Predicted Probability: 0.6832, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 524/4000 [04:54<23:08,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9811039566993713, Predicted Probability: 0.7273, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8122351765632629, Predicted Probability: 0.6926, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 525/4000 [04:55<19:43,  2.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.026049448177218437, Predicted Probability: 0.5065, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7022603154182434, Predicted Probability: 0.6687, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 526/4000 [04:55<27:15,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4389851689338684, Predicted Probability: 0.6080, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.367687463760376, Predicted Probability: 0.2030, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 527/4000 [04:56<23:41,  2.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.08107341080904007, Predicted Probability: 0.4797, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.012250304222107, Predicted Probability: 0.2665, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 528/4000 [04:56<29:48,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7707371115684509, Predicted Probability: 0.3163, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9144829511642456, Predicted Probability: 0.7139, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 529/4000 [04:57<30:07,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.8356201648712158, Predicted Probability: 0.6975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.4046052694320679, Predicted Probability: 0.1971, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 530/4000 [04:57<27:40,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1198943853378296, Predicted Probability: 0.7540, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2341549396514893, Predicted Probability: 0.7745, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 531/4000 [04:58<32:19,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5029141902923584, Predicted Probability: 0.1820, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.703737199306488, Predicted Probability: 0.6690, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 532/4000 [04:59<35:09,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1282019317150116, Predicted Probability: 0.5320, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3219237327575684, Predicted Probability: 0.2105, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 533/4000 [04:59<31:12,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3779900074005127, Predicted Probability: 0.4066, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3271675109863281, Predicted Probability: 0.7904, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 534/4000 [05:00<35:00,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.25247055292129517, Predicted Probability: 0.4372, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9533986449241638, Predicted Probability: 0.7218, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 535/4000 [05:00<31:14,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7499639391899109, Predicted Probability: 0.6792, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2414820194244385, Predicted Probability: 0.7758, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 536/4000 [05:01<34:30,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9347556233406067, Predicted Probability: 0.7180, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4748244285583496, Predicted Probability: 0.1862, Prediction: 0.0

Epoch 1/3:  13%|█▎        | 537/4000 [05:01<31:35,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4521780014038086, Predicted Probability: 0.1897, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.100511074066162, Predicted Probability: 0.7504, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 538/4000 [05:02<28:52,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0815953016281128, Predicted Probability: 0.7468, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7223415970802307, Predicted Probability: 0.6731, Prediction: 1.0

Epoch 1/3:  13%|█▎        | 539/4000 [05:02<26:43,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.950433075428009, Predicted Probability: 0.7212, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0369477272033691, Predicted Probability: 0.7383, Prediction: 1.0

Epoch 1/3:  14%|█▎        | 540/4000 [05:03<25:04,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7317349314689636, Predicted Probability: 0.6752, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0942357778549194, Predicted Probability: 0.7492, Prediction: 1.0

Epoch 1/3:  14%|█▎        | 541/4000 [05:03<30:34,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9204944372177124, Predicted Probability: 0.2849, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8144212961196899, Predicted Probability: 0.6931, Prediction: 1.0

Epoch 1/3:  14%|█▎        | 543/4000 [05:04<28:12,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6337084770202637, Predicted Probability: 0.1633, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2860768139362335, Predicted Probability: 0.5710, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -0.06326059997081757, Predicted Probability: 0.4842, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1269339770078659, Predicted Probability: 0.4683, Prediction: 0.0

Epoch 1/3:  14%|█▎        | 544/4000 [05:05<32:46,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0346194505691528, Predicted Probability: 0.2622, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8858486413955688, Predicted Probability: 0.7080, Prediction: 1.0

Epoch 1/3:  14%|█▎        | 545/4000 [05:06<36:11,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.17633855342865, Predicted Probability: 0.7643, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2248398065567017, Predicted Probability: 0.2271, Prediction: 0.0

Epoch 1/3:  14%|█▎        | 546/4000 [05:07<37:58,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.1681363582611084, Predicted Probability: 0.4581, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8153270483016968, Predicted Probability: 0.6932, Prediction: 1.0

Epoch 1/3:  14%|█▎        | 547/4000 [05:07<33:17,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7771879434585571, Predicted Probability: 0.3149, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.16275371611118317, Predicted Probability: 0.4594, Prediction: 0.0

Epoch 1/3:  14%|█▎        | 548/4000 [05:08<38:32,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.31084370613098145, Predicted Probability: 0.5771, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7312090396881104, Predicted Probability: 0.1504, Prediction: 0.0

Epoch 1/3:  14%|█▎        | 549/4000 [05:09<40:26,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6327100992202759, Predicted Probability: 0.6531, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.212083101272583, Predicted Probability: 0.2293, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 550/4000 [05:09<37:36,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1798689365386963, Predicted Probability: 0.2351, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.37953558564186096, Predicted Probability: 0.5938, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 551/4000 [05:10<39:13,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9550086259841919, Predicted Probability: 0.7221, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.63583505153656, Predicted Probability: 0.1630, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 552/4000 [05:11<40:07,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0867786407470703, Predicted Probability: 0.7478, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0806735754013062, Predicted Probability: 0.2534, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 553/4000 [05:11<37:52,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4790394604206085, Predicted Probability: 0.6175, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.29376348853111267, Predicted Probability: 0.4271, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 554/4000 [05:12<39:26,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6813618540763855, Predicted Probability: 0.6640, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.268613338470459, Predicted Probability: 0.2195, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 555/4000 [05:12<31:06,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2066789865493774, Predicted Probability: 0.7697, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4873343706130981, Predicted Probability: 0.8157, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 556/4000 [05:13<34:53,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8250566720962524, Predicted Probability: 0.1388, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9716628789901733, Predicted Probability: 0.7255, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 557/4000 [05:14<39:25,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7967164516448975, Predicted Probability: 0.1423, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7195167541503906, Predicted Probability: 0.1519, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 558/4000 [05:14<34:01,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9335876107215881, Predicted Probability: 0.7178, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4263639450073242, Predicted Probability: 0.8063, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 559/4000 [05:15<36:55,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.977135419845581, Predicted Probability: 0.2735, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7694282531738281, Predicted Probability: 0.6834, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 560/4000 [05:15<32:16,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1053473949432373, Predicted Probability: 0.7513, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.893606960773468, Predicted Probability: 0.7096, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 561/4000 [05:16<29:02,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0610672235488892, Predicted Probability: 0.7429, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1202367544174194, Predicted Probability: 0.7540, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 562/4000 [05:17<33:43,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6296653747558594, Predicted Probability: 0.1639, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6977256536483765, Predicted Probability: 0.6677, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 563/4000 [05:17<30:12,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0638303756713867, Predicted Probability: 0.7434, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1260333061218262, Predicted Probability: 0.7551, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 564/4000 [05:18<33:20,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1323208808898926, Predicted Probability: 0.2437, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6970885396003723, Predicted Probability: 0.6675, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 565/4000 [05:18<29:44,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7976411581039429, Predicted Probability: 0.6895, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1704399585723877, Predicted Probability: 0.7632, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 566/4000 [05:18<27:32,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1432126760482788, Predicted Probability: 0.7583, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0638591051101685, Predicted Probability: 0.7434, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 567/4000 [05:19<31:53,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8303590416908264, Predicted Probability: 0.3036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4931522607803345, Predicted Probability: 0.6208, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 568/4000 [05:19<28:42,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8416430354118347, Predicted Probability: 0.6988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1924124956130981, Predicted Probability: 0.2328, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 569/4000 [05:20<33:00,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8418915271759033, Predicted Probability: 0.1368, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8809536695480347, Predicted Probability: 0.7070, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 570/4000 [05:20<26:35,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8239787817001343, Predicted Probability: 0.8610, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9040308594703674, Predicted Probability: 0.7118, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 571/4000 [05:21<30:46,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1715562343597412, Predicted Probability: 0.7634, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8529407978057861, Predicted Probability: 0.1355, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 572/4000 [05:22<28:09,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8221866488456726, Predicted Probability: 0.6947, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9904407858848572, Predicted Probability: 0.7292, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 573/4000 [05:22<32:03,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9586067795753479, Predicted Probability: 0.2772, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2279748916625977, Predicted Probability: 0.7735, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 574/4000 [05:23<35:17,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5199310183525085, Predicted Probability: 0.6271, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.635680079460144, Predicted Probability: 0.3462, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 575/4000 [05:23<31:17,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.690757155418396, Predicted Probability: 0.6661, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.15957766771316528, Predicted Probability: 0.4602, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 576/4000 [05:24<35:04,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4604548215866089, Predicted Probability: 0.1884, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7382310628890991, Predicted Probability: 0.1495, Prediction: 0.0

Epoch 1/3:  14%|█▍        | 577/4000 [05:25<30:56,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9688248038291931, Predicted Probability: 0.7249, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4410940408706665, Predicted Probability: 0.6085, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 578/4000 [05:25<28:05,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0848448276519775, Predicted Probability: 0.7474, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0355863571166992, Predicted Probability: 0.7380, Prediction: 1.0

Epoch 1/3:  14%|█▍        | 579/4000 [05:26<32:55,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5990362167358398, Predicted Probability: 0.1681, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5977498292922974, Predicted Probability: 0.3549, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 581/4000 [05:27<28:20,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2142032384872437, Predicted Probability: 0.7710, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.6436142921447754, Predicted Probability: 0.3444, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 1.6913796663284302, Predicted Probability: 0.8444, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.24228037893772125, Predicted Probability: 0.4397, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 582/4000 [05:27<32:17,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.1698354482650757, Predicted Probability: 0.7631, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9990997314453125, Predicted Probability: 0.2691, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 583/4000 [05:28<32:54,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9032614827156067, Predicted Probability: 0.2884, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1284795999526978, Predicted Probability: 0.7556, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 584/4000 [05:29<35:41,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.591050624847412, Predicted Probability: 0.1692, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1322731971740723, Predicted Probability: 0.7563, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 585/4000 [05:29<38:00,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.885777235031128, Predicted Probability: 0.1317, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0648844242095947, Predicted Probability: 0.2564, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 586/4000 [05:30<35:47,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.326668620109558, Predicted Probability: 0.7903, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3148520886898041, Predicted Probability: 0.5781, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 587/4000 [05:30<31:15,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5097905397415161, Predicted Probability: 0.8190, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.289833426475525, Predicted Probability: 0.7841, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 588/4000 [05:31<31:21,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5275346040725708, Predicted Probability: 0.3711, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3198093175888062, Predicted Probability: 0.2109, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 589/4000 [05:31<28:06,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7670032978057861, Predicted Probability: 0.8541, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1178526878356934, Predicted Probability: 0.7536, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 590/4000 [05:32<28:47,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4835046529769897, Predicted Probability: 0.8151, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5662819147109985, Predicted Probability: 0.6379, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 591/4000 [05:32<29:15,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.45284193754196167, Predicted Probability: 0.6113, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.05310084670782089, Predicted Probability: 0.4867, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 592/4000 [05:33<33:39,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1938393115997314, Predicted Probability: 0.7674, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8812015056610107, Predicted Probability: 0.1323, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 593/4000 [05:33<29:36,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7167901992797852, Predicted Probability: 0.1523, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.05388811603188515, Predicted Probability: 0.5135, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 594/4000 [05:34<33:13,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.9472354650497437, Predicted Probability: 0.2794, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9942163228988647, Predicted Probability: 0.7299, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 595/4000 [05:34<26:43,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8360447287559509, Predicted Probability: 0.6976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1649538278579712, Predicted Probability: 0.7622, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 596/4000 [05:35<24:50,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.800182819366455, Predicted Probability: 0.8582, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8521486520767212, Predicted Probability: 0.1356, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 597/4000 [05:36<29:48,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7224202156066895, Predicted Probability: 0.1516, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2360210418701172, Predicted Probability: 0.7749, Prediction: 1.0

Epoch 1/3:  15%|█▍        | 598/4000 [05:36<34:40,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0056276321411133, Predicted Probability: 0.1186, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7724108695983887, Predicted Probability: 0.1452, Prediction: 0.0

Epoch 1/3:  15%|█▍        | 599/4000 [05:37<33:46,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6796960830688477, Predicted Probability: 0.6637, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.9159694910049438, Predicted Probability: 0.2858, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 600/4000 [05:38<43:06,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4790685176849365, Predicted Probability: 0.8144, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9518224000930786, Predicted Probability: 0.1244, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 601/4000 [05:38<36:30,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.721042811870575, Predicted Probability: 0.3272, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4206197261810303, Predicted Probability: 0.8054, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 602/4000 [05:39<29:00,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2487436532974243, Predicted Probability: 0.7771, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5006787776947021, Predicted Probability: 0.8177, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 603/4000 [05:39<26:46,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5506328344345093, Predicted Probability: 0.8250, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5406975746154785, Predicted Probability: 0.8236, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 604/4000 [05:40<30:56,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5582244396209717, Predicted Probability: 0.1739, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4059228897094727, Predicted Probability: 0.8031, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 605/4000 [05:40<27:51,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4863369464874268, Predicted Probability: 0.8155, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5416160821914673, Predicted Probability: 0.8237, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 606/4000 [05:40<25:31,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1300894021987915, Predicted Probability: 0.7559, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.39425596594810486, Predicted Probability: 0.5973, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 607/4000 [05:41<31:03,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.003637433052063, Predicted Probability: 0.2682, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2924060821533203, Predicted Probability: 0.2154, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 608/4000 [05:42<28:09,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3030569553375244, Predicted Probability: 0.7863, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.858618438243866, Predicted Probability: 0.7024, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 610/4000 [05:42<21:43,  2.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.353198766708374, Predicted Probability: 0.7947, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9632155895233154, Predicted Probability: 0.8769, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 1.2718024253845215, Predicted Probability: 0.7811, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1347206830978394, Predicted Probability: 0.7567, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 612/4000 [05:43<18:24,  3.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.416783332824707, Predicted Probability: 0.8048, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4958399832248688, Predicted Probability: 0.3785, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 0.07251325249671936, Predicted Probability: 0.5181, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4882416725158691, Predicted Probability: 0.8158, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 613/4000 [05:43<25:07,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.3385822772979736, Predicted Probability: 0.7923, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.114619255065918, Predicted Probability: 0.2470, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 614/4000 [05:44<23:40,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9170169830322266, Predicted Probability: 0.8718, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5487208366394043, Predicted Probability: 0.8247, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 615/4000 [05:44<23:53,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.110164761543274, Predicted Probability: 0.7522, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.04579839110374451, Predicted Probability: 0.4886, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 616/4000 [05:45<28:44,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5382918119430542, Predicted Probability: 0.8232, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6651382446289062, Predicted Probability: 0.1591, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 617/4000 [05:45<26:23,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1245992183685303, Predicted Probability: 0.7548, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5205491781234741, Predicted Probability: 0.1794, Prediction: 0.0

Epoch 1/3:  15%|█▌        | 618/4000 [05:46<28:45,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.0946292877197266, Predicted Probability: 0.2507, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.551827311515808, Predicted Probability: 0.8252, Prediction: 1.0

Epoch 1/3:  15%|█▌        | 619/4000 [05:47<32:18,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2325417846441269, Predicted Probability: 0.5579, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7225159406661987, Predicted Probability: 0.1515, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 620/4000 [05:47<34:56,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.428104281425476, Predicted Probability: 0.1934, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.274978756904602, Predicted Probability: 0.7816, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 621/4000 [05:48<37:08,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7966008186340332, Predicted Probability: 0.6892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.49616050720214844, Predicted Probability: 0.3784, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 622/4000 [05:49<38:48,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.06674467772245407, Predicted Probability: 0.4833, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5463371276855469, Predicted Probability: 0.1756, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 623/4000 [05:50<39:42,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.12862840294837952, Predicted Probability: 0.5321, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.28379181027412415, Predicted Probability: 0.4295, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 624/4000 [05:50<33:59,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.556010365486145, Predicted Probability: 0.8258, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1929014921188354, Predicted Probability: 0.2327, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 625/4000 [05:51<37:16,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4552652835845947, Predicted Probability: 0.8108, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5674290657043457, Predicted Probability: 0.1726, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 626/4000 [05:51<32:34,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1992857456207275, Predicted Probability: 0.7684, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1349362134933472, Predicted Probability: 0.2433, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 627/4000 [05:52<36:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.132765769958496, Predicted Probability: 0.1060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8106571435928345, Predicted Probability: 0.3078, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 628/4000 [05:52<32:03,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8849955797195435, Predicted Probability: 0.8682, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.39043834805488586, Predicted Probability: 0.5964, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 629/4000 [05:53<35:19,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.299694299697876, Predicted Probability: 0.7858, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7029013633728027, Predicted Probability: 0.1541, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 630/4000 [05:54<32:18,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.7552148699760437, Predicted Probability: 0.3197, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.021859776228666306, Predicted Probability: 0.5055, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 631/4000 [05:54<30:01,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7168642282485962, Predicted Probability: 0.8477, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.180755376815796, Predicted Probability: 0.2349, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 632/4000 [05:54<25:37,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6216436624526978, Predicted Probability: 0.8350, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.869138240814209, Predicted Probability: 0.8664, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 633/4000 [05:55<28:32,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.16443365812301636, Predicted Probability: 0.5410, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.198441505432129, Predicted Probability: 0.2318, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 634/4000 [05:56<32:35,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0239362716674805, Predicted Probability: 0.7357, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1502718925476074, Predicted Probability: 0.1043, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 635/4000 [05:56<34:41,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4318922460079193, Predicted Probability: 0.3937, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5048962831497192, Predicted Probability: 0.8183, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 636/4000 [05:57<36:16,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.14315736293792725, Predicted Probability: 0.5357, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6594334840774536, Predicted Probability: 0.1598, Prediction: 0.0

Epoch 1/3:  16%|█▌        | 637/4000 [05:58<34:27,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4544533491134644, Predicted Probability: 0.8107, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.695945143699646, Predicted Probability: 0.6673, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 638/4000 [05:58<30:25,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2919135093688965, Predicted Probability: 0.7845, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.6029938459396362, Predicted Probability: 0.8324, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 639/4000 [05:59<30:42,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4011383354663849, Predicted Probability: 0.5990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.46829792857170105, Predicted Probability: 0.6150, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 640/4000 [05:59<34:26,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9591456651687622, Predicted Probability: 0.1236, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5025707483291626, Predicted Probability: 0.6231, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 641/4000 [06:00<36:51,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0026893615722656, Predicted Probability: 0.1189, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3689398765563965, Predicted Probability: 0.7972, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 642/4000 [06:01<38:13,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8959654569625854, Predicted Probability: 0.1306, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5380429029464722, Predicted Probability: 0.8232, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 643/4000 [06:01<36:01,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8087159395217896, Predicted Probability: 0.1408, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2621134519577026, Predicted Probability: 0.7794, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 644/4000 [06:02<34:17,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6117598414421082, Predicted Probability: 0.6483, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6583939790725708, Predicted Probability: 0.6589, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 645/4000 [06:03<37:13,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7385656833648682, Predicted Probability: 0.1495, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5219165086746216, Predicted Probability: 0.8208, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 646/4000 [06:03<37:54,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.345267415046692, Predicted Probability: 0.2066, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5783603191375732, Predicted Probability: 0.8290, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 647/4000 [06:04<39:44,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3797276020050049, Predicted Probability: 0.2011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1646116971969604, Predicted Probability: 0.7622, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 648/4000 [06:05<40:15,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.491060733795166, Predicted Probability: 0.1838, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6176873445510864, Predicted Probability: 0.6497, Prediction: 1.0

Epoch 1/3:  16%|█▌        | 649/4000 [06:05<34:27,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1042903661727905, Predicted Probability: 0.7511, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7682844400405884, Predicted Probability: 0.8542, Prediction: 1.0

Epoch 1/3:  16%|█▋        | 650/4000 [06:06<37:17,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9602490663528442, Predicted Probability: 0.1234, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8637428879737854, Predicted Probability: 0.2966, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 651/4000 [06:07<35:11,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7754414081573486, Predicted Probability: 0.8551, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7894630432128906, Predicted Probability: 0.1431, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 652/4000 [06:07<37:05,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1330690383911133, Predicted Probability: 0.7564, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5922250747680664, Predicted Probability: 0.1691, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 653/4000 [06:08<32:12,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8157339096069336, Predicted Probability: 0.8601, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7995094060897827, Predicted Probability: 0.3101, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 654/4000 [06:08<29:51,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8228178024291992, Predicted Probability: 0.8609, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8242805004119873, Predicted Probability: 0.1389, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 655/4000 [06:09<34:41,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.7525781393051147, Predicted Probability: 0.1477, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.136174201965332, Predicted Probability: 0.1056, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 656/4000 [06:10<33:14,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4120742082595825, Predicted Probability: 0.8041, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.174781322479248, Predicted Probability: 0.7640, Prediction: 1.0

Epoch 1/3:  16%|█▋        | 657/4000 [06:10<29:25,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.012952718883752823, Predicted Probability: 0.5032, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2876177430152893, Predicted Probability: 0.4286, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 658/4000 [06:11<33:27,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.12020233273506165, Predicted Probability: 0.5300, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1588923931121826, Predicted Probability: 0.1035, Prediction: 0.0

Epoch 1/3:  16%|█▋        | 659/4000 [06:11<35:11,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4134613275527954, Predicted Probability: 0.1957, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.677330732345581, Predicted Probability: 0.8426, Prediction: 1.0

Epoch 1/3:  16%|█▋        | 660/4000 [06:12<30:59,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6889533996582031, Predicted Probability: 0.8441, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6926116943359375, Predicted Probability: 0.1554, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 661/4000 [06:13<34:51,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9804279804229736, Predicted Probability: 0.1213, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.624260425567627, Predicted Probability: 0.8354, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 662/4000 [06:13<30:44,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.019982146099209785, Predicted Probability: 0.5050, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7729840278625488, Predicted Probability: 0.8548, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 663/4000 [06:14<33:33,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.547155737876892, Predicted Probability: 0.8245, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.001682281494140625, Predicted Probability: 0.4996, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 664/4000 [06:14<29:46,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0694544315338135, Predicted Probability: 0.1121, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9480839967727661, Predicted Probability: 0.7207, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 666/4000 [06:15<22:18,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.691504955291748, Predicted Probability: 0.8444, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8232641220092773, Predicted Probability: 0.6949, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 2.131722927093506, Predicted Probability: 0.8939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1430187225341797, Predicted Probability: 0.8950, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 667/4000 [06:15<19:01,  2.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5043282508850098, Predicted Probability: 0.9244, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0685436725616455, Predicted Probability: 0.8878, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 668/4000 [06:15<19:47,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9425581693649292, Predicted Probability: 0.8746, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0544078350067139, Predicted Probability: 0.2584, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 669/4000 [06:16<25:50,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.1996667385101318, Predicted Probability: 0.7685, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.795137643814087, Predicted Probability: 0.1424, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 670/4000 [06:17<30:29,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4748252630233765, Predicted Probability: 0.8138, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.111820697784424, Predicted Probability: 0.1080, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 672/4000 [06:18<26:56,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5694986581802368, Predicted Probability: 0.8277, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7807629108428955, Predicted Probability: 0.1442, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 2.453997850418091, Predicted Probability: 0.9209, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0495855808258057, Predicted Probability: 0.8859, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 673/4000 [06:18<30:58,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.167825222015381, Predicted Probability: 0.1027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.686201810836792, Predicted Probability: 0.8437, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 674/4000 [06:19<34:23,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6179847717285156, Predicted Probability: 0.8345, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1453566551208496, Predicted Probability: 0.1048, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 675/4000 [06:20<36:09,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5683038234710693, Predicted Probability: 0.6384, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4745128154754639, Predicted Probability: 0.1863, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 676/4000 [06:21<38:50,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2554621696472168, Predicted Probability: 0.2218, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.302827000617981, Predicted Probability: 0.2137, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 677/4000 [06:21<39:31,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6277952194213867, Predicted Probability: 0.8359, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.971112072467804, Predicted Probability: 0.2747, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 678/4000 [06:22<34:12,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.549052119255066, Predicted Probability: 0.8248, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.583003044128418, Predicted Probability: 0.8296, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 680/4000 [06:23<26:09,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.23300711810588837, Predicted Probability: 0.5580, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2533153295516968, Predicted Probability: 0.2221, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -1.209133505821228, Predicted Probability: 0.2299, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.8428246974945068, Predicted Probability: 0.8633, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 681/4000 [06:23<30:41,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1248655319213867, Predicted Probability: 0.1067, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.0034197568893432617, Predicted Probability: 0.4991, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 682/4000 [06:24<34:10,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6412888765335083, Predicted Probability: 0.1623, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9143308401107788, Predicted Probability: 0.2861, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 683/4000 [06:24<30:26,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.679056167602539, Predicted Probability: 0.8428, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6602355241775513, Predicted Probability: 0.8403, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 684/4000 [06:25<27:55,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8912948966026306, Predicted Probability: 0.7092, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0687148571014404, Predicted Probability: 0.7444, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 685/4000 [06:26<31:09,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7411162853240967, Predicted Probability: 0.8508, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8922314643859863, Predicted Probability: 0.1310, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 686/4000 [06:26<34:12,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.23848819732666, Predicted Probability: 0.0963, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.159013271331787, Predicted Probability: 0.7612, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 687/4000 [06:27<36:22,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.19467326998710632, Predicted Probability: 0.4515, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.178577423095703, Predicted Probability: 0.1017, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 688/4000 [06:28<37:41,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.373518228530884, Predicted Probability: 0.0852, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6222200393676758, Predicted Probability: 0.8351, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 689/4000 [06:28<34:00,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0622873306274414, Predicted Probability: 0.1128, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2996864318847656, Predicted Probability: 0.7858, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 690/4000 [06:29<29:55,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1804707050323486, Predicted Probability: 0.8985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.086301326751709, Predicted Probability: 0.1104, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 691/4000 [06:30<35:00,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0464224815368652, Predicted Probability: 0.1144, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.368590831756592, Predicted Probability: 0.0856, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 692/4000 [06:30<33:29,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5389316082000732, Predicted Probability: 0.8233, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8415215611457825, Predicted Probability: 0.6988, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 693/4000 [06:31<32:16,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.7525918483734131, Predicted Probability: 0.3203, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2750643491744995, Predicted Probability: 0.7816, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 694/4000 [06:31<35:53,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4514884948730469, Predicted Probability: 0.8102, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3780272006988525, Predicted Probability: 0.0849, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 695/4000 [06:32<37:31,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5323412418365479, Predicted Probability: 0.8223, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.304222583770752, Predicted Probability: 0.0908, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 696/4000 [06:33<38:54,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8937056064605713, Predicted Probability: 0.1308, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7334194183349609, Predicted Probability: 0.6756, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 697/4000 [06:34<39:27,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.464860200881958, Predicted Probability: 0.8123, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8826943635940552, Predicted Probability: 0.1321, Prediction: 0.0

Epoch 1/3:  17%|█▋        | 698/4000 [06:34<35:07,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.300939679145813, Predicted Probability: 0.7860, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0281662940979004, Predicted Probability: 0.7366, Prediction: 1.0

Epoch 1/3:  17%|█▋        | 699/4000 [06:35<33:39,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7419198751449585, Predicted Probability: 0.8509, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4490727186203003, Predicted Probability: 0.8099, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 700/4000 [06:35<35:53,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8570233583450317, Predicted Probability: 0.8649, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.448972702026367, Predicted Probability: 0.0795, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 701/4000 [06:36<37:19,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7981204986572266, Predicted Probability: 0.8579, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4594650268554688, Predicted Probability: 0.1885, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 703/4000 [06:37<23:56,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.27761566638946533, Predicted Probability: 0.5690, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.968660831451416, Predicted Probability: 0.8775, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 2.1106438636779785, Predicted Probability: 0.8919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.771284818649292, Predicted Probability: 0.9411, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 704/4000 [06:37<25:40,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.627929449081421, Predicted Probability: 0.8359, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7048990726470947, Predicted Probability: 0.8462, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 705/4000 [06:37<21:22,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9926141500473022, Predicted Probability: 0.8800, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9974639415740967, Predicted Probability: 0.2694, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 706/4000 [06:38<21:12,  2.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9324164390563965, Predicted Probability: 0.8735, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4717521667480469, Predicted Probability: 0.8133, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 707/4000 [06:38<27:43,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6445400714874268, Predicted Probability: 0.8382, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2980265617370605, Predicted Probability: 0.0913, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 708/4000 [06:39<31:23,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2248111367225647, Predicted Probability: 0.4440, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9921482801437378, Predicted Probability: 0.8800, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 709/4000 [06:40<31:16,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9744434356689453, Predicted Probability: 0.8781, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1242897510528564, Predicted Probability: 0.2452, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 710/4000 [06:40<25:20,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.686908483505249, Predicted Probability: 0.8438, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2540833950042725, Predicted Probability: 0.9050, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 711/4000 [06:40<24:00,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8012744188308716, Predicted Probability: 0.8583, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4762887954711914, Predicted Probability: 0.9225, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 712/4000 [06:41<22:43,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6031572818756104, Predicted Probability: 0.8325, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5585315823554993, Predicted Probability: 0.6361, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 713/4000 [06:42<28:51,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5392227172851562, Predicted Probability: 0.0732, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7260808944702148, Predicted Probability: 0.8489, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 714/4000 [06:42<23:34,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4204158782958984, Predicted Probability: 0.8054, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4977118968963623, Predicted Probability: 0.6219, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 715/4000 [06:42<28:39,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3008315563201904, Predicted Probability: 0.0911, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.12840580940246582, Predicted Probability: 0.4679, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 716/4000 [06:43<31:56,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8093191385269165, Predicted Probability: 0.8593, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.435915470123291, Predicted Probability: 0.0805, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 717/4000 [06:44<28:32,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.097015619277954, Predicted Probability: 0.1094, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6635900139808655, Predicted Probability: 0.6601, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 718/4000 [06:44<29:02,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1962800025939941, Predicted Probability: 0.7679, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.128113254904747, Predicted Probability: 0.4680, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 719/4000 [06:44<26:23,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3029889464378357, Predicted Probability: 0.4248, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.113771677017212, Predicted Probability: 0.8922, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 720/4000 [06:45<30:27,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.500352382659912, Predicted Probability: 0.0758, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.18363237380981445, Predicted Probability: 0.5458, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 722/4000 [06:46<24:26,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.1986597776412964, Predicted Probability: 0.7683, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0402650833129883, Predicted Probability: 0.1150, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -0.8894460797309875, Predicted Probability: 0.2912, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9028705954551697, Predicted Probability: 0.7115, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 723/4000 [06:47<29:37,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.659287691116333, Predicted Probability: 0.8401, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.12550687789917, Predicted Probability: 0.1066, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 724/4000 [06:47<26:59,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3341046869754791, Predicted Probability: 0.5828, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.30578821897506714, Predicted Probability: 0.5759, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 725/4000 [06:48<31:33,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4544358253479004, Predicted Probability: 0.0791, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7147331237792969, Predicted Probability: 0.8474, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 726/4000 [06:48<29:33,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.522050380706787, Predicted Probability: 0.8208, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7807008028030396, Predicted Probability: 0.6858, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 727/4000 [06:49<33:01,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5605058670043945, Predicted Probability: 0.1736, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1699467897415161, Predicted Probability: 0.5424, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 728/4000 [06:50<35:23,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8320911526679993, Predicted Probability: 0.3032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6929309368133545, Predicted Probability: 0.8446, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 729/4000 [06:50<33:41,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.31245332956314087, Predicted Probability: 0.5775, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.007143497467041, Predicted Probability: 0.8815, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 730/4000 [06:51<29:59,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.323859691619873, Predicted Probability: 0.9108, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.843176007270813, Predicted Probability: 0.1367, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 731/4000 [06:52<33:21,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4660229682922363, Predicted Probability: 0.0783, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7949035167694092, Predicted Probability: 0.8575, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 732/4000 [06:52<26:48,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8814455270767212, Predicted Probability: 0.8678, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.4699007272720337, Predicted Probability: 0.8130, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 733/4000 [06:52<24:37,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4892517328262329, Predicted Probability: 0.6199, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9828318357467651, Predicted Probability: 0.8790, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 734/4000 [06:53<30:54,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5256199836730957, Predicted Probability: 0.0741, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.675673484802246, Predicted Probability: 0.8423, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 735/4000 [06:54<30:59,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7198216915130615, Predicted Probability: 0.1519, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3346099853515625, Predicted Probability: 0.9117, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 736/4000 [06:54<28:00,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2328107357025146, Predicted Probability: 0.9032, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5523858666419983, Predicted Probability: 0.6347, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 737/4000 [06:55<31:58,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.432396173477173, Predicted Probability: 0.0807, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7697621583938599, Predicted Probability: 0.8544, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 738/4000 [06:55<28:43,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.639238715171814, Predicted Probability: 0.8374, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.241603374481201, Predicted Probability: 0.0961, Prediction: 0.0

Epoch 1/3:  18%|█▊        | 739/4000 [06:56<32:21,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5051002502441406, Predicted Probability: 0.0755, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6960234642028809, Predicted Probability: 0.8450, Prediction: 1.0

Epoch 1/3:  18%|█▊        | 740/4000 [06:56<28:44,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.590986967086792, Predicted Probability: 0.9303, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3583462238311768, Predicted Probability: 0.0864, Prediction: 0.0

Epoch 1/3:  19%|█▊        | 741/4000 [06:57<32:31,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.364936351776123, Predicted Probability: 0.0859, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5955806970596313, Predicted Probability: 0.8314, Prediction: 1.0

Epoch 1/3:  19%|█▊        | 742/4000 [06:58<32:58,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8345173001289368, Predicted Probability: 0.6973, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2384650707244873, Predicted Probability: 0.0963, Prediction: 0.0

Epoch 1/3:  19%|█▊        | 743/4000 [06:58<34:30,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8553777933120728, Predicted Probability: 0.8648, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.33856046199798584, Predicted Probability: 0.4162, Prediction: 0.0

Epoch 1/3:  19%|█▊        | 744/4000 [06:59<36:01,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3375651836395264, Predicted Probability: 0.0881, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9538896083831787, Predicted Probability: 0.7219, Prediction: 1.0

Epoch 1/3:  19%|█▊        | 745/4000 [07:00<37:28,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2289891242980957, Predicted Probability: 0.0972, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3635497093200684, Predicted Probability: 0.7963, Prediction: 1.0

Epoch 1/3:  19%|█▊        | 746/4000 [07:00<35:08,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9381433725357056, Predicted Probability: 0.7187, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0798667669296265, Predicted Probability: 0.7465, Prediction: 1.0

Epoch 1/3:  19%|█▊        | 747/4000 [07:01<33:26,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.25854602456092834, Predicted Probability: 0.4357, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.651548147201538, Predicted Probability: 0.8391, Prediction: 1.0

Epoch 1/3:  19%|█▊        | 748/4000 [07:02<35:50,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7635055780410767, Predicted Probability: 0.8536, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.318289041519165, Predicted Probability: 0.0896, Prediction: 0.0

Epoch 1/3:  19%|█▊        | 749/4000 [07:02<37:33,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5007379055023193, Predicted Probability: 0.8177, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.443162441253662, Predicted Probability: 0.0799, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 750/4000 [07:03<38:07,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.819638729095459, Predicted Probability: 0.6942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.580874443054199, Predicted Probability: 0.0704, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 751/4000 [07:03<30:08,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.030329465866089, Predicted Probability: 0.1161, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7096735835075378, Predicted Probability: 0.3297, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 752/4000 [07:04<27:10,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1693739891052246, Predicted Probability: 0.8975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2954849004745483, Predicted Probability: 0.7851, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 753/4000 [07:04<31:14,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1450963020324707, Predicted Probability: 0.1048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5480103492736816, Predicted Probability: 0.8246, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 754/4000 [07:05<30:45,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3863853216171265, Predicted Probability: 0.2000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.383971929550171, Predicted Probability: 0.2004, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 755/4000 [07:06<34:40,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8066143989562988, Predicted Probability: 0.8590, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1488382816314697, Predicted Probability: 0.1044, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 756/4000 [07:06<35:37,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1870968341827393, Predicted Probability: 0.7662, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9066420793533325, Predicted Probability: 0.8706, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 757/4000 [07:07<37:04,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.03687751293182373, Predicted Probability: 0.5092, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.42219895124435425, Predicted Probability: 0.6040, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 758/4000 [07:08<38:09,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3014841079711914, Predicted Probability: 0.0910, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7444326877593994, Predicted Probability: 0.8512, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 759/4000 [07:08<32:36,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4535043239593506, Predicted Probability: 0.9208, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.672689437866211, Predicted Probability: 0.0646, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 760/4000 [07:09<35:35,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.110851287841797, Predicted Probability: 0.1080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5736825466156006, Predicted Probability: 0.8283, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 761/4000 [07:09<28:13,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6459526419639587, Predicted Probability: 0.6561, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.90779709815979, Predicted Probability: 0.9482, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 762/4000 [07:10<25:45,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2457306385040283, Predicted Probability: 0.9043, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2975666522979736, Predicted Probability: 0.9087, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 763/4000 [07:10<29:55,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8235695362091064, Predicted Probability: 0.8610, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9621267318725586, Predicted Probability: 0.1232, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 764/4000 [07:11<32:42,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2958741188049316, Predicted Probability: 0.0915, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8209450244903564, Predicted Probability: 0.8607, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 765/4000 [07:12<36:26,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5800652503967285, Predicted Probability: 0.1708, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.338373899459839, Predicted Probability: 0.0880, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 766/4000 [07:13<37:29,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.446652412414551, Predicted Probability: 0.0797, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8146536350250244, Predicted Probability: 0.8599, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 767/4000 [07:14<38:36,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.506636619567871, Predicted Probability: 0.0754, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9528104066848755, Predicted Probability: 0.8758, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 768/4000 [07:14<31:18,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3394311666488647, Predicted Probability: 0.2076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3367669582366943, Predicted Probability: 0.0881, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 769/4000 [07:15<36:19,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.031559139490127563, Predicted Probability: 0.4921, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.467456579208374, Predicted Probability: 0.1873, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 770/4000 [07:15<28:40,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0521769523620605, Predicted Probability: 0.1138, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.923111081123352, Predicted Probability: 0.8725, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 771/4000 [07:16<32:10,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5631840229034424, Predicted Probability: 0.0715, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2981092929840088, Predicted Probability: 0.2145, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 772/4000 [07:16<31:12,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.06666995584964752, Predicted Probability: 0.5167, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4359782934188843, Predicted Probability: 0.3927, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 773/4000 [07:17<34:08,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.04425853490829468, Predicted Probability: 0.4889, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3131818771362305, Predicted Probability: 0.0900, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 774/4000 [07:18<37:06,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0223169326782227, Predicted Probability: 0.1169, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9799726605415344, Predicted Probability: 0.2729, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 775/4000 [07:19<37:53,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5742696523666382, Predicted Probability: 0.8284, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.879029393196106, Predicted Probability: 0.1325, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 776/4000 [07:19<32:31,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8034027814865112, Predicted Probability: 0.1414, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.794115424156189, Predicted Probability: 0.8574, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 777/4000 [07:19<29:00,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6103078126907349, Predicted Probability: 0.1665, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.809654712677002, Predicted Probability: 0.8593, Prediction: 1.0

Epoch 1/3:  19%|█▉        | 778/4000 [07:20<32:17,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.09557920694351196, Predicted Probability: 0.5239, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3946213722229004, Predicted Probability: 0.0836, Prediction: 0.0

Epoch 1/3:  19%|█▉        | 779/4000 [07:20<25:56,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3461625576019287, Predicted Probability: 0.2065, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.16500763595104218, Predicted Probability: 0.5412, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 780/4000 [07:21<30:09,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7782800197601318, Predicted Probability: 0.8555, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.25760555267334, Predicted Probability: 0.0947, Prediction: 0.0

Epoch 1/3:  20%|█▉        | 781/4000 [07:21<26:59,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.278640031814575, Predicted Probability: 0.9071, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1268579959869385, Predicted Probability: 0.8935, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 782/4000 [07:22<25:05,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8310102224349976, Predicted Probability: 0.3034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6110591888427734, Predicted Probability: 0.8336, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 783/4000 [07:22<24:53,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.148930311203003, Predicted Probability: 0.1044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.293682813644409, Predicted Probability: 0.9084, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 784/4000 [07:23<29:52,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4127519130706787, Predicted Probability: 0.0822, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9607663750648499, Predicted Probability: 0.7233, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 785/4000 [07:23<25:12,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.021311979740858078, Predicted Probability: 0.5053, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8891072273254395, Predicted Probability: 0.9473, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 786/4000 [07:24<30:01,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6826019287109375, Predicted Probability: 0.0640, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7101033926010132, Predicted Probability: 0.8468, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 787/4000 [07:25<34:50,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7879133224487305, Predicted Probability: 0.1433, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1603411436080933, Predicted Probability: 0.2386, Prediction: 0.0

Epoch 1/3:  20%|█▉        | 788/4000 [07:26<36:36,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.862992525100708, Predicted Probability: 0.0540, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7469285726547241, Predicted Probability: 0.8516, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 789/4000 [07:26<38:15,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1874135732650757, Predicted Probability: 0.2337, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7904834747314453, Predicted Probability: 0.0578, Prediction: 0.0

Epoch 1/3:  20%|█▉        | 790/4000 [07:27<38:20,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6965922117233276, Predicted Probability: 0.8451, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.6298749446868896, Predicted Probability: 0.8362, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 791/4000 [07:28<39:39,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.562709331512451, Predicted Probability: 0.0716, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6818855404853821, Predicted Probability: 0.6642, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 792/4000 [07:29<40:46,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2675611972808838, Predicted Probability: 0.7803, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5618247389793396, Predicted Probability: 0.6369, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 793/4000 [07:29<34:40,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.48414945602417, Predicted Probability: 0.8152, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5470702052116394, Predicted Probability: 0.6335, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 794/4000 [07:30<36:18,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2553545832633972, Predicted Probability: 0.4365, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6692630052566528, Predicted Probability: 0.6613, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 795/4000 [07:31<37:23,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7522343397140503, Predicted Probability: 0.8522, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.660452365875244, Predicted Probability: 0.0653, Prediction: 0.0

Epoch 1/3:  20%|█▉        | 796/4000 [07:31<40:03,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0273991823196411, Predicted Probability: 0.7364, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9081413745880127, Predicted Probability: 0.0518, Prediction: 0.0

Epoch 1/3:  20%|█▉        | 797/4000 [07:32<35:31,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5987626314163208, Predicted Probability: 0.8318, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0187954902648926, Predicted Probability: 0.1172, Prediction: 0.0

Epoch 1/3:  20%|█▉        | 798/4000 [07:33<37:05,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3255767822265625, Predicted Probability: 0.0890, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8277275562286377, Predicted Probability: 0.8615, Prediction: 1.0

Epoch 1/3:  20%|█▉        | 799/4000 [07:33<38:04,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5497307777404785, Predicted Probability: 0.0724, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3257970809936523, Predicted Probability: 0.7901, Prediction: 1.0

Epoch 1/3:  20%|██        | 800/4000 [07:34<38:30,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6332104206085205, Predicted Probability: 0.8366, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.336087703704834, Predicted Probability: 0.0882, Prediction: 0.0

Epoch 1/3:  20%|██        | 801/4000 [07:35<39:29,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2312278747558594, Predicted Probability: 0.7740, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.755244255065918, Predicted Probability: 0.0598, Prediction: 0.0

Epoch 1/3:  20%|██        | 802/4000 [07:35<33:36,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3362572193145752, Predicted Probability: 0.4167, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3210620880126953, Predicted Probability: 0.9106, Prediction: 1.0

Epoch 1/3:  20%|██        | 803/4000 [07:36<29:33,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9083025455474854, Predicted Probability: 0.8708, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1106998920440674, Predicted Probability: 0.8919, Prediction: 1.0

Epoch 1/3:  20%|██        | 805/4000 [07:37<27:53,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.256291389465332, Predicted Probability: 0.0948, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5445622205734253, Predicted Probability: 0.8241, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 0.274566113948822, Predicted Probability: 0.5682, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6937952041625977, Predicted Probability: 0.9367, Prediction: 1.0

Epoch 1/3:  20%|██        | 806/4000 [07:37<26:43,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8383097648620605, Predicted Probability: 0.8627, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.549156427383423, Predicted Probability: 0.0725, Prediction: 0.0

Epoch 1/3:  20%|██        | 807/4000 [07:38<24:49,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3447329998016357, Predicted Probability: 0.9125, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4709713459014893, Predicted Probability: 0.9221, Prediction: 1.0

Epoch 1/3:  20%|██        | 808/4000 [07:38<29:12,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.600648045539856, Predicted Probability: 0.6458, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.775580406188965, Predicted Probability: 0.0587, Prediction: 0.0

Epoch 1/3:  20%|██        | 809/4000 [07:39<26:39,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.190141201019287, Predicted Probability: 0.8994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.717350721359253, Predicted Probability: 0.0620, Prediction: 0.0

Epoch 1/3:  20%|██        | 810/4000 [07:40<30:40,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.79408597946167, Predicted Probability: 0.8574, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0164408683776855, Predicted Probability: 0.0467, Prediction: 0.0

Epoch 1/3:  20%|██        | 811/4000 [07:40<32:47,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6217423677444458, Predicted Probability: 0.8350, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7216403484344482, Predicted Probability: 0.0617, Prediction: 0.0

Epoch 1/3:  20%|██        | 812/4000 [07:41<27:13,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.3989497423171997, Predicted Probability: 0.1980, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2289873361587524, Predicted Probability: 0.7736, Prediction: 1.0

Epoch 1/3:  20%|██        | 813/4000 [07:41<28:39,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.647935152053833, Predicted Probability: 0.8386, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8765455484390259, Predicted Probability: 0.8672, Prediction: 1.0

Epoch 1/3:  20%|██        | 814/4000 [07:42<29:06,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4752639532089233, Predicted Probability: 0.8139, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0264804363250732, Predicted Probability: 0.7362, Prediction: 1.0

Epoch 1/3:  20%|██        | 815/4000 [07:42<24:40,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.117556571960449, Predicted Probability: 0.9576, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.54923415184021, Predicted Probability: 0.9275, Prediction: 1.0

Epoch 1/3:  20%|██        | 816/4000 [07:43<28:39,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9977620840072632, Predicted Probability: 0.8806, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9696428179740906, Predicted Probability: 0.2750, Prediction: 0.0

Epoch 1/3:  20%|██        | 817/4000 [07:44<32:41,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5205256938934326, Predicted Probability: 0.8206, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2182204723358154, Predicted Probability: 0.0981, Prediction: 0.0

Epoch 1/3:  20%|██        | 818/4000 [07:44<34:08,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9511313438415527, Predicted Probability: 0.1244, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.3000112771987915, Predicted Probability: 0.7858, Prediction: 1.0

Epoch 1/3:  20%|██        | 819/4000 [07:45<36:10,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.05704665184021, Predicted Probability: 0.1133, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3207924365997314, Predicted Probability: 0.7893, Prediction: 1.0

Epoch 1/3:  20%|██        | 820/4000 [07:45<28:42,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7531816959381104, Predicted Probability: 0.9401, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3929312229156494, Predicted Probability: 0.9163, Prediction: 1.0

Epoch 1/3:  21%|██        | 821/4000 [07:46<33:03,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.30368438363075256, Predicted Probability: 0.5753, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3872900009155273, Predicted Probability: 0.1998, Prediction: 0.0

Epoch 1/3:  21%|██        | 822/4000 [07:46<29:02,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7988020181655884, Predicted Probability: 0.3103, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.742419958114624, Predicted Probability: 0.1490, Prediction: 0.0

Epoch 1/3:  21%|██        | 823/4000 [07:47<32:00,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5695812702178955, Predicted Probability: 0.8277, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2435903549194336, Predicted Probability: 0.0959, Prediction: 0.0

Epoch 1/3:  21%|██        | 824/4000 [07:48<35:14,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.6185940504074097, Predicted Probability: 0.8346, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5047636032104492, Predicted Probability: 0.1817, Prediction: 0.0

Epoch 1/3:  21%|██        | 825/4000 [07:48<30:26,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9753347635269165, Predicted Probability: 0.7262, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.438222885131836, Predicted Probability: 0.9197, Prediction: 1.0

Epoch 1/3:  21%|██        | 826/4000 [07:49<33:16,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9837548732757568, Predicted Probability: 0.8791, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4111735820770264, Predicted Probability: 0.0823, Prediction: 0.0

Epoch 1/3:  21%|██        | 827/4000 [07:49<29:14,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3291733264923096, Predicted Probability: 0.9113, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1016865968704224, Predicted Probability: 0.2494, Prediction: 0.0

Epoch 1/3:  21%|██        | 828/4000 [07:50<31:57,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7319564819335938, Predicted Probability: 0.8497, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.703314781188965, Predicted Probability: 0.0628, Prediction: 0.0

Epoch 1/3:  21%|██        | 829/4000 [07:51<34:21,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0705697536468506, Predicted Probability: 0.8880, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8698439598083496, Predicted Probability: 0.0537, Prediction: 0.0

Epoch 1/3:  21%|██        | 830/4000 [07:52<37:59,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7793917655944824, Predicted Probability: 0.0584, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.470001220703125, Predicted Probability: 0.0780, Prediction: 0.0

Epoch 1/3:  21%|██        | 831/4000 [07:52<30:01,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0423407554626465, Predicted Probability: 0.9545, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.187379002571106, Predicted Probability: 0.7663, Prediction: 1.0

Epoch 1/3:  21%|██        | 832/4000 [07:52<26:52,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4981316328048706, Predicted Probability: 0.8173, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3208863735198975, Predicted Probability: 0.9106, Prediction: 1.0

Epoch 1/3:  21%|██        | 833/4000 [07:53<27:33,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8161512613296509, Predicted Probability: 0.8601, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3970770835876465, Predicted Probability: 0.0834, Prediction: 0.0

Epoch 1/3:  21%|██        | 834/4000 [07:53<26:05,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.580443263053894, Predicted Probability: 0.6412, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4943560361862183, Predicted Probability: 0.8167, Prediction: 1.0

Epoch 1/3:  21%|██        | 835/4000 [07:54<30:02,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7858835458755493, Predicted Probability: 0.3131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7170863151550293, Predicted Probability: 0.8478, Prediction: 1.0

Epoch 1/3:  21%|██        | 836/4000 [07:55<29:39,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2898207902908325, Predicted Probability: 0.7841, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8154788017272949, Predicted Probability: 0.6933, Prediction: 1.0

Epoch 1/3:  21%|██        | 837/4000 [07:55<32:07,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7584228515625, Predicted Probability: 0.0596, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1271731853485107, Predicted Probability: 0.8935, Prediction: 1.0

Epoch 1/3:  21%|██        | 838/4000 [07:56<34:25,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.052389621734619, Predicted Probability: 0.0451, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8751063346862793, Predicted Probability: 0.8670, Prediction: 1.0

Epoch 1/3:  21%|██        | 839/4000 [07:56<27:33,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3866752088069916, Predicted Probability: 0.5955, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1847519874572754, Predicted Probability: 0.1011, Prediction: 0.0

Epoch 1/3:  21%|██        | 840/4000 [07:57<30:41,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9610981941223145, Predicted Probability: 0.0492, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8874963521957397, Predicted Probability: 0.8685, Prediction: 1.0

Epoch 1/3:  21%|██        | 841/4000 [07:57<27:26,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8755171298980713, Predicted Probability: 0.8671, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8249220252037048, Predicted Probability: 0.3047, Prediction: 0.0

Epoch 1/3:  21%|██        | 842/4000 [07:58<31:45,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5892648696899414, Predicted Probability: 0.1695, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5041866302490234, Predicted Probability: 0.0756, Prediction: 0.0

Epoch 1/3:  21%|██        | 843/4000 [07:59<35:20,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.639638900756836, Predicted Probability: 0.0666, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.060086727142334, Predicted Probability: 0.8870, Prediction: 1.0

Epoch 1/3:  21%|██        | 844/4000 [08:00<36:44,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.730973243713379, Predicted Probability: 0.8495, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9977123737335205, Predicted Probability: 0.0475, Prediction: 0.0

Epoch 1/3:  21%|██        | 845/4000 [08:01<37:28,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.023074150085449, Predicted Probability: 0.8832, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7518088817596436, Predicted Probability: 0.0600, Prediction: 0.0

Epoch 1/3:  21%|██        | 846/4000 [08:01<37:51,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8170522451400757, Predicted Probability: 0.1398, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9736852645874023, Predicted Probability: 0.8780, Prediction: 1.0

Epoch 1/3:  21%|██        | 847/4000 [08:02<38:41,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.768904209136963, Predicted Probability: 0.0590, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9303762912750244, Predicted Probability: 0.7172, Prediction: 1.0

Epoch 1/3:  21%|██        | 848/4000 [08:03<34:02,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2682061195373535, Predicted Probability: 0.9062, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.311997175216675, Predicted Probability: 0.9099, Prediction: 1.0

Epoch 1/3:  21%|██        | 849/4000 [08:03<30:04,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7985734939575195, Predicted Probability: 0.9426, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2413275241851807, Predicted Probability: 0.9039, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 850/4000 [08:03<25:18,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.041223522275686264, Predicted Probability: 0.5103, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.711033582687378, Predicted Probability: 0.9377, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 851/4000 [08:04<30:13,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0432653427124023, Predicted Probability: 0.1147, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.644901990890503, Predicted Probability: 0.8382, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 852/4000 [08:04<25:29,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1477389335632324, Predicted Probability: 0.8955, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3182212114334106, Predicted Probability: 0.2111, Prediction: 0.0

Epoch 1/3:  21%|██▏       | 853/4000 [08:05<29:00,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7331029772758484, Predicted Probability: 0.3245, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8254406452178955, Predicted Probability: 0.8612, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 854/4000 [08:06<33:26,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6465075016021729, Predicted Probability: 0.3438, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0077357292175293, Predicted Probability: 0.1184, Prediction: 0.0

Epoch 1/3:  21%|██▏       | 855/4000 [08:06<29:10,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3115227222442627, Predicted Probability: 0.9098, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2993686199188232, Predicted Probability: 0.9088, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 856/4000 [08:07<29:54,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.5988024473190308, Predicted Probability: 0.8319, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4143056869506836, Predicted Probability: 0.9179, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 857/4000 [08:07<29:43,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4057955741882324, Predicted Probability: 0.9173, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8197578191757202, Predicted Probability: 0.8605, Prediction: 1.0

Epoch 1/3:  21%|██▏       | 858/4000 [08:08<31:46,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.101313829421997, Predicted Probability: 0.8910, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.742277145385742, Predicted Probability: 0.0605, Prediction: 0.0

Epoch 1/3:  21%|██▏       | 859/4000 [08:09<34:53,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.069847583770752, Predicted Probability: 0.0444, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.202476978302002, Predicted Probability: 0.2310, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 860/4000 [08:10<36:06,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.916860818862915, Predicted Probability: 0.8718, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6713536381721497, Predicted Probability: 0.3382, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 861/4000 [08:10<37:27,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.93916654586792, Predicted Probability: 0.0503, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.10228085517883301, Predicted Probability: 0.4745, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 862/4000 [08:11<37:52,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.913684368133545, Predicted Probability: 0.0515, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.937692642211914, Predicted Probability: 0.8741, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 863/4000 [08:12<38:24,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7353460788726807, Predicted Probability: 0.0609, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0048543214797974, Predicted Probability: 0.2680, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 864/4000 [08:12<35:08,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5696732997894287, Predicted Probability: 0.9289, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.111619472503662, Predicted Probability: 0.8920, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 865/4000 [08:13<35:54,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0574712753295898, Predicted Probability: 0.2578, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.001988172531128, Predicted Probability: 0.7314, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 866/4000 [08:14<36:31,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1184134483337402, Predicted Probability: 0.0424, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.28000450134277344, Predicted Probability: 0.5695, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 867/4000 [08:14<31:25,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0608986616134644, Predicted Probability: 0.7429, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.616367816925049, Predicted Probability: 0.9319, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 868/4000 [08:15<33:32,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0557355880737305, Predicted Probability: 0.0450, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.406773328781128, Predicted Probability: 0.8033, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 869/4000 [08:15<26:44,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7886765003204346, Predicted Probability: 0.1432, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.917391061782837, Predicted Probability: 0.9487, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 870/4000 [08:16<31:16,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.933896541595459, Predicted Probability: 0.0505, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0699667930603027, Predicted Probability: 0.8879, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 871/4000 [08:16<25:03,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7333271503448486, Predicted Probability: 0.8498, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0118861198425293, Predicted Probability: 0.1180, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 872/4000 [08:17<25:54,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0371696949005127, Predicted Probability: 0.7383, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.8599738478660583, Predicted Probability: 0.7027, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 873/4000 [08:17<26:27,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.8137599229812622, Predicted Probability: 0.6929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.852572202682495, Predicted Probability: 0.0545, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 874/4000 [08:18<30:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4232053756713867, Predicted Probability: 0.8058, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.113816261291504, Predicted Probability: 0.0425, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 875/4000 [08:19<32:38,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8050594329833984, Predicted Probability: 0.0571, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0993874073028564, Predicted Probability: 0.7501, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 876/4000 [08:19<34:39,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8228495121002197, Predicted Probability: 0.0561, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8994847536087036, Predicted Probability: 0.1302, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 877/4000 [08:20<35:32,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7621865272521973, Predicted Probability: 0.8535, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0329337120056152, Predicted Probability: 0.0460, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 879/4000 [08:21<24:42,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.729304552078247, Predicted Probability: 0.9387, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.014676094055176, Predicted Probability: 0.8823, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 1.6233576536178589, Predicted Probability: 0.8353, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.7366479635238647, Predicted Probability: 0.8503, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 881/4000 [08:22<21:05,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.278289318084717, Predicted Probability: 0.0929, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.962694764137268, Predicted Probability: 0.8768, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 2.1635231971740723, Predicted Probability: 0.8969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.125166416168213, Predicted Probability: 0.8933, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 882/4000 [08:22<18:58,  2.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.222022771835327, Predicted Probability: 0.0978, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.103646993637085, Predicted Probability: 0.0430, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 883/4000 [08:23<24:44,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9408795833587646, Predicted Probability: 0.0502, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.34893569350242615, Predicted Probability: 0.5864, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 884/4000 [08:23<23:20,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1749279499053955, Predicted Probability: 0.1020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.1453969478607178, Predicted Probability: 0.2413, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 885/4000 [08:23<22:03,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3781373500823975, Predicted Probability: 0.2013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4203715324401855, Predicted Probability: 0.8054, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 886/4000 [08:24<21:24,  2.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.558977484703064, Predicted Probability: 0.1738, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0137510299682617, Predicted Probability: 0.8822, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 887/4000 [08:24<20:44,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4833545684814453, Predicted Probability: 0.9230, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0314157009124756, Predicted Probability: 0.0460, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 888/4000 [08:24<20:32,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7140259742736816, Predicted Probability: 0.8474, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.67832350730896, Predicted Probability: 0.9357, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 889/4000 [08:25<25:21,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7379738092422485, Predicted Probability: 0.8504, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.983154535293579, Predicted Probability: 0.0482, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 890/4000 [08:26<23:46,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.925515055656433, Predicted Probability: 0.8728, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5301988124847412, Predicted Probability: 0.3705, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 891/4000 [08:26<28:17,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.135981798171997, Predicted Probability: 0.8944, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1122310161590576, Predicted Probability: 0.0426, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 892/4000 [08:27<25:33,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6204514503479004, Predicted Probability: 0.9322, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.57337486743927, Predicted Probability: 0.1717, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 893/4000 [08:27<23:26,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.309464931488037, Predicted Probability: 0.9648, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.010958194732666, Predicted Probability: 0.9531, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 894/4000 [08:28<28:31,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31331193447113037, Predicted Probability: 0.4223, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1724278926849365, Predicted Probability: 0.0402, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 895/4000 [08:28<28:21,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.04387476667761803, Predicted Probability: 0.4890, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.295176237821579, Predicted Probability: 0.5733, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 896/4000 [08:29<31:29,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.199537754058838, Predicted Probability: 0.0392, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6365886926651001, Predicted Probability: 0.6540, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 897/4000 [08:30<34:06,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.058823585510254, Predicted Probability: 0.0448, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4168479442596436, Predicted Probability: 0.9181, Prediction: 1.0

Epoch 1/3:  22%|██▏       | 898/4000 [08:30<29:47,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6562589406967163, Predicted Probability: 0.8397, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.021116256713867, Predicted Probability: 0.0465, Prediction: 0.0

Epoch 1/3:  22%|██▏       | 899/4000 [08:30<24:05,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8563427925109863, Predicted Probability: 0.1351, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.437119960784912, Predicted Probability: 0.9688, Prediction: 1.0

Epoch 1/3:  22%|██▎       | 900/4000 [08:31<22:30,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.394425392150879, Predicted Probability: 0.9164, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8939149379730225, Predicted Probability: 0.9475, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 901/4000 [08:32<27:14,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8858743906021118, Predicted Probability: 0.8683, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.964629650115967, Predicted Probability: 0.0490, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 902/4000 [08:32<32:14,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.197331666946411, Predicted Probability: 0.0393, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.893795967102051, Predicted Probability: 0.0525, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 903/4000 [08:33<33:44,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9213433265686035, Predicted Probability: 0.8723, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9920058250427246, Predicted Probability: 0.0478, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 904/4000 [08:33<27:50,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6803324222564697, Predicted Probability: 0.0641, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7748827934265137, Predicted Probability: 0.9413, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 905/4000 [08:34<28:09,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5589451789855957, Predicted Probability: 0.1738, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.322309970855713, Predicted Probability: 0.0348, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 906/4000 [08:34<25:29,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5532150268554688, Predicted Probability: 0.1746, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7671616077423096, Predicted Probability: 0.9409, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 907/4000 [08:35<29:52,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0018835067749023, Predicted Probability: 0.1190, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9469127655029297, Predicted Probability: 0.8751, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 908/4000 [08:35<26:53,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0943992137908936, Predicted Probability: 0.8904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.152329683303833, Predicted Probability: 0.8959, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 909/4000 [08:36<31:14,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0854876041412354, Predicted Probability: 0.0437, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.198326587677002, Predicted Probability: 0.0392, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 910/4000 [08:37<33:17,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.10014009475708, Predicted Probability: 0.0431, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.74674391746521, Predicted Probability: 0.8515, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 911/4000 [08:38<32:58,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7144213318824768, Predicted Probability: 0.3286, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.199476718902588, Predicted Probability: 0.9002, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 912/4000 [08:38<28:40,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.42399391531944275, Predicted Probability: 0.6044, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.522965908050537, Predicted Probability: 0.9257, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 913/4000 [08:39<33:06,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.162421226501465, Predicted Probability: 0.0406, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.589261293411255, Predicted Probability: 0.0698, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 914/4000 [08:39<31:19,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2569360733032227, Predicted Probability: 0.9052, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.35628554224967957, Predicted Probability: 0.5881, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 915/4000 [08:40<25:02,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1166281700134277, Predicted Probability: 0.9576, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.400155782699585, Predicted Probability: 0.0832, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 916/4000 [08:40<24:09,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.04113861545920372, Predicted Probability: 0.4897, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.256218194961548, Predicted Probability: 0.9052, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 918/4000 [08:41<23:49,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.146632671356201, Predicted Probability: 0.8954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4784469604492188, Predicted Probability: 0.0299, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 3.04020357131958, Predicted Probability: 0.9544, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.0011162497103214264, Predicted Probability: 0.5003, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 919/4000 [08:41<19:52,  2.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6445324420928955, Predicted Probability: 0.9337, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8605000972747803, Predicted Probability: 0.9459, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 920/4000 [08:42<22:09,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4617247581481934, Predicted Probability: 0.9214, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.163417100906372, Predicted Probability: 0.8969, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 921/4000 [08:43<27:12,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2464699745178223, Predicted Probability: 0.9043, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.078881025314331, Predicted Probability: 0.0440, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 922/4000 [08:43<30:56,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2548015117645264, Predicted Probability: 0.0372, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4453011453151703, Predicted Probability: 0.6095, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 923/4000 [08:44<34:28,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.074859619140625, Predicted Probability: 0.1116, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1831765174865723, Predicted Probability: 0.0398, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 924/4000 [08:45<30:00,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3826804161071777, Predicted Probability: 0.0845, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.469893217086792, Predicted Probability: 0.9220, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 925/4000 [08:45<26:30,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8834598064422607, Predicted Probability: 0.9470, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5992023944854736, Predicted Probability: 0.9308, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 926/4000 [08:46<30:40,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8768671751022339, Predicted Probability: 0.8673, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.728902816772461, Predicted Probability: 0.0613, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 927/4000 [08:46<32:55,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.962322473526001, Predicted Probability: 0.0492, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0261449813842773, Predicted Probability: 0.8835, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 928/4000 [08:47<34:56,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1506447792053223, Predicted Probability: 0.0411, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6850712895393372, Predicted Probability: 0.6649, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 929/4000 [08:48<35:11,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.956277847290039, Predicted Probability: 0.8761, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.259777307510376, Predicted Probability: 0.9055, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 930/4000 [08:49<37:00,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1615469455718994, Predicted Probability: 0.2384, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.527665138244629, Predicted Probability: 0.9261, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 931/4000 [08:50<38:07,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.133218765258789, Predicted Probability: 0.8941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2735493183135986, Predicted Probability: 0.0933, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 932/4000 [08:50<29:49,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.778144598007202, Predicted Probability: 0.9415, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9806177616119385, Predicted Probability: 0.9517, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 933/4000 [08:50<27:36,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.702725648880005, Predicted Probability: 0.0628, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1113461256027222, Predicted Probability: 0.7524, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 934/4000 [08:51<24:55,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.817383050918579, Predicted Probability: 0.9436, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.413008689880371, Predicted Probability: 0.9178, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 935/4000 [08:51<25:54,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.598195791244507, Predicted Probability: 0.9307, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1010141372680664, Predicted Probability: 0.8910, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 936/4000 [08:52<26:47,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.496600389480591, Predicted Probability: 0.9239, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2616515159606934, Predicted Probability: 0.0943, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 937/4000 [08:52<21:52,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1707286834716797, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3792059421539307, Predicted Probability: 0.9670, Prediction: 1.0

Epoch 1/3:  23%|██▎       | 938/4000 [08:53<26:32,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8404045104980469, Predicted Probability: 0.8630, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2899365425109863, Predicted Probability: 0.0920, Prediction: 0.0

Epoch 1/3:  23%|██▎       | 939/4000 [08:53<31:06,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4252594709396362, Predicted Probability: 0.8062, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7169084548950195, Predicted Probability: 0.0620, Prediction: 0.0

Epoch 1/3:  24%|██▎       | 940/4000 [08:54<27:23,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2605020999908447, Predicted Probability: 0.0944, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.948221206665039, Predicted Probability: 0.9502, Prediction: 1.0

Epoch 1/3:  24%|██▎       | 941/4000 [08:54<25:56,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8411219120025635, Predicted Probability: 0.9449, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3958916664123535, Predicted Probability: 0.9165, Prediction: 1.0

Epoch 1/3:  24%|██▎       | 942/4000 [08:55<29:07,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9909050464630127, Predicted Probability: 0.8798, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9652763605117798, Predicted Probability: 0.1229, Prediction: 0.0

Epoch 1/3:  24%|██▎       | 943/4000 [08:56<32:58,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1020748615264893, Predicted Probability: 0.0430, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.4434043169021606, Predicted Probability: 0.8090, Prediction: 1.0

Epoch 1/3:  24%|██▎       | 944/4000 [08:57<34:42,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.04547917842865, Predicted Probability: 0.7399, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9502971172332764, Predicted Probability: 0.0497, Prediction: 0.0

Epoch 1/3:  24%|██▎       | 945/4000 [08:57<36:35,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6993494033813477, Predicted Probability: 0.0630, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1460464000701904, Predicted Probability: 0.0412, Prediction: 0.0

Epoch 1/3:  24%|██▎       | 946/4000 [08:58<31:24,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.87153959274292, Predicted Probability: 0.8666, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.23114603757858276, Predicted Probability: 0.4425, Prediction: 0.0

Epoch 1/3:  24%|██▎       | 947/4000 [08:58<32:39,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.259845495223999, Predicted Probability: 0.0370, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9638466835021973, Predicted Probability: 0.8769, Prediction: 1.0

Epoch 1/3:  24%|██▎       | 948/4000 [08:59<25:58,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7344887256622314, Predicted Probability: 0.0610, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0728697776794434, Predicted Probability: 0.1118, Prediction: 0.0

Epoch 1/3:  24%|██▎       | 949/4000 [08:59<23:46,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8156168460845947, Predicted Probability: 0.0565, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7645263671875, Predicted Probability: 0.9407, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 950/4000 [09:00<28:24,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.693051815032959, Predicted Probability: 0.8446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9274868965148926, Predicted Probability: 0.0508, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 951/4000 [09:00<25:46,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.990147829055786, Predicted Probability: 0.9521, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1022024154663086, Predicted Probability: 0.9570, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 952/4000 [09:01<26:33,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9447617530822754, Predicted Probability: 0.0500, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.159213066101074, Predicted Probability: 0.1035, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 953/4000 [09:01<29:33,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8412740230560303, Predicted Probability: 0.8631, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.867002010345459, Predicted Probability: 0.0538, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 954/4000 [09:02<26:15,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.165421485900879, Predicted Probability: 0.9595, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0208137035369873, Predicted Probability: 0.8830, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 955/4000 [09:03<29:22,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4861271381378174, Predicted Probability: 0.0297, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7082245349884033, Predicted Probability: 0.8466, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 956/4000 [09:03<32:47,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9867115020751953, Predicted Probability: 0.0480, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1330478191375732, Predicted Probability: 0.0418, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 957/4000 [09:04<26:05,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1704492568969727, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4458351135253906, Predicted Probability: 0.9203, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 958/4000 [09:04<23:55,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1839304268360138, Predicted Probability: 0.5459, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6973891258239746, Predicted Probability: 0.9369, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 959/4000 [09:04<23:38,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.558351993560791, Predicted Probability: 0.9281, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4721930027008057, Predicted Probability: 0.9222, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 960/4000 [09:05<28:14,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1211163997650146, Predicted Probability: 0.0422, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0369882583618164, Predicted Probability: 0.2617, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 961/4000 [09:05<25:41,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.188021421432495, Predicted Probability: 0.8992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3691816329956055, Predicted Probability: 0.9144, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 962/4000 [09:06<31:01,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1994895935058594, Predicted Probability: 0.0392, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.367018938064575, Predicted Probability: 0.0333, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 963/4000 [09:07<29:53,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2391104698181152, Predicted Probability: 0.0963, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0747053623199463, Predicted Probability: 0.8884, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 964/4000 [09:07<26:45,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5994430780410767, Predicted Probability: 0.1681, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8132096529006958, Predicted Probability: 0.8597, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 965/4000 [09:08<29:55,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3652634620666504, Predicted Probability: 0.0334, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7884585857391357, Predicted Probability: 0.8567, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 966/4000 [09:08<27:41,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8440418243408203, Predicted Probability: 0.9450, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2724108695983887, Predicted Probability: 0.9066, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 967/4000 [09:09<31:10,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3094494342803955, Predicted Probability: 0.0352, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7323043346405029, Predicted Probability: 0.3247, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 968/4000 [09:10<33:55,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.400387763977051, Predicted Probability: 0.0323, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1618363857269287, Predicted Probability: 0.8968, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 969/4000 [09:11<34:33,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.23738169670105, Predicted Probability: 0.0378, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3836788535118103, Predicted Probability: 0.5948, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 971/4000 [09:11<22:44,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0720162391662598, Predicted Probability: 0.8882, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.4181381464004517, Predicted Probability: 0.1950, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 1.0258427858352661, Predicted Probability: 0.7361, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.025120973587036, Predicted Probability: 0.1166, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 972/4000 [09:12<27:59,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7449860572814941, Predicted Probability: 0.8513, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.334670066833496, Predicted Probability: 0.0344, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 973/4000 [09:13<30:25,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.25474053621292114, Predicted Probability: 0.5633, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.584046483039856, Predicted Probability: 0.6420, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 974/4000 [09:14<32:55,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2081139087677, Predicted Probability: 0.0389, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.473050594329834, Predicted Probability: 0.8135, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 975/4000 [09:14<34:22,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4049463272094727, Predicted Probability: 0.0321, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6943848133087158, Predicted Probability: 0.8448, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 976/4000 [09:15<30:59,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.069227695465088, Predicted Probability: 0.1121, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6561806201934814, Predicted Probability: 0.9344, Prediction: 1.0

Epoch 1/3:  24%|██▍       | 977/4000 [09:15<28:33,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1281026601791382, Predicted Probability: 0.7555, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.8762197494506836, Predicted Probability: 0.0533, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 978/4000 [09:16<31:37,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4510374069213867, Predicted Probability: 0.0307, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8398593664169312, Predicted Probability: 0.3016, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 979/4000 [09:17<35:07,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3847551345825195, Predicted Probability: 0.0328, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1005163192749023, Predicted Probability: 0.0431, Prediction: 0.0

Epoch 1/3:  24%|██▍       | 980/4000 [09:18<36:02,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2699406147003174, Predicted Probability: 0.0366, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4314858913421631, Predicted Probability: 0.6062, Prediction: 1.0

Epoch 1/3:  25%|██▍       | 981/4000 [09:18<38:24,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.217158555984497, Predicted Probability: 0.0385, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3726327419281006, Predicted Probability: 0.0332, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 982/4000 [09:19<37:44,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4265992641448975, Predicted Probability: 0.0315, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8172190189361572, Predicted Probability: 0.8602, Prediction: 1.0

Epoch 1/3:  25%|██▍       | 983/4000 [09:19<29:37,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.074897289276123, Predicted Probability: 0.0442, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.162524461746216, Predicted Probability: 0.0406, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 984/4000 [09:20<26:32,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.171746015548706, Predicted Probability: 0.0402, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.687757670879364, Predicted Probability: 0.6655, Prediction: 1.0

Epoch 1/3:  25%|██▍       | 985/4000 [09:20<29:25,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2312629222869873, Predicted Probability: 0.0380, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8716310262680054, Predicted Probability: 0.8666, Prediction: 1.0

Epoch 1/3:  25%|██▍       | 986/4000 [09:21<32:05,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.23159974813461304, Predicted Probability: 0.5576, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4334893226623535, Predicted Probability: 0.0313, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 987/4000 [09:22<34:58,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8552850484848022, Predicted Probability: 0.1353, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2976856231689453, Predicted Probability: 0.0357, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 988/4000 [09:22<30:09,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1324775218963623, Predicted Probability: 0.9582, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.353266716003418, Predicted Probability: 0.9132, Prediction: 1.0

Epoch 1/3:  25%|██▍       | 989/4000 [09:23<32:41,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2525265216827393, Predicted Probability: 0.7777, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4161481857299805, Predicted Probability: 0.0318, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 990/4000 [09:24<34:06,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.733181118965149, Predicted Probability: 0.8498, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4911537170410156, Predicted Probability: 0.0296, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 991/4000 [09:25<34:38,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5667072534561157, Predicted Probability: 0.8273, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2009286880493164, Predicted Probability: 0.0391, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 992/4000 [09:25<36:26,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.447352409362793, Predicted Probability: 0.0308, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.475964307785034, Predicted Probability: 0.0300, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 993/4000 [09:26<37:14,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.035266160964966, Predicted Probability: 0.1155, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2434749603271484, Predicted Probability: 0.0959, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 994/4000 [09:27<36:56,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2702794373035431, Predicted Probability: 0.5672, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9440371990203857, Predicted Probability: 0.0500, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 995/4000 [09:28<37:44,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31760233640670776, Predicted Probability: 0.4213, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4094114303588867, Predicted Probability: 0.0320, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 997/4000 [09:28<23:42,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8302462100982666, Predicted Probability: 0.0557, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8026440143585205, Predicted Probability: 0.0572, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -1.8571064472198486, Predicted Probability: 0.1350, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.220810890197754, Predicted Probability: 0.9616, Prediction: 1.0

Epoch 1/3:  25%|██▍       | 998/4000 [09:29<24:31,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9686429500579834, Predicted Probability: 0.8775, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4093417823314667, Predicted Probability: 0.3991, Prediction: 0.0

Epoch 1/3:  25%|██▍       | 999/4000 [09:29<28:23,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0914247035980225, Predicted Probability: 0.7486, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3244242668151855, Predicted Probability: 0.0347, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1000/4000 [09:30<31:14,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.223419189453125, Predicted Probability: 0.0383, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.543485403060913, Predicted Probability: 0.8240, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1001/4000 [09:31<27:29,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3156681060791016, Predicted Probability: 0.0350, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3764824867248535, Predicted Probability: 0.9150, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1002/4000 [09:31<22:23,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.466590642929077, Predicted Probability: 0.9697, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.027339458465576, Predicted Probability: 0.9538, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1003/4000 [09:32<27:33,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2223246097564697, Predicted Probability: 0.0383, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4225206971168518, Predicted Probability: 0.6041, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1004/4000 [09:32<24:51,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5390733480453491, Predicted Probability: 0.1767, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9159281253814697, Predicted Probability: 0.0514, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1006/4000 [09:33<19:42,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.0234824419021606, Predicted Probability: 0.2643, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1661672592163086, Predicted Probability: 0.8972, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 2.422748327255249, Predicted Probability: 0.9185, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.24796351790428162, Predicted Probability: 0.5617, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1007/4000 [09:33<25:04,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3637943267822266, Predicted Probability: 0.0334, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.09764516353607178, Predicted Probability: 0.5244, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1008/4000 [09:34<28:30,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3762316703796387, Predicted Probability: 0.0330, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.657869577407837, Predicted Probability: 0.8400, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1009/4000 [09:35<26:43,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7883856296539307, Predicted Probability: 0.9420, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0955424308776855, Predicted Probability: 0.7494, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1010/4000 [09:35<24:31,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1142666339874268, Predicted Probability: 0.8923, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.367847204208374, Predicted Probability: 0.2030, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1011/4000 [09:35<22:48,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6525455713272095, Predicted Probability: 0.1608, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.059828042984009, Predicted Probability: 0.9552, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1012/4000 [09:36<29:33,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.472221851348877, Predicted Probability: 0.0301, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.241827964782715, Predicted Probability: 0.0376, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1013/4000 [09:37<26:21,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.878552198410034, Predicted Probability: 0.9468, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3403645753860474, Predicted Probability: 0.2075, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1014/4000 [09:37<29:40,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0075273513793945, Predicted Probability: 0.8816, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4551095962524414, Predicted Probability: 0.0306, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1015/4000 [09:38<32:35,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.364987850189209, Predicted Probability: 0.0334, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.5933040380477905, Predicted Probability: 0.8311, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1016/4000 [09:39<28:05,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5081841945648193, Predicted Probability: 0.0291, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4401915073394775, Predicted Probability: 0.9198, Prediction: 1.0

Epoch 1/3:  25%|██▌       | 1017/4000 [09:39<25:20,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5851519107818604, Predicted Probability: 0.9299, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.492600440979004, Predicted Probability: 0.0764, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1018/4000 [09:40<29:29,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.54890513420105, Predicted Probability: 0.0280, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8663041591644287, Predicted Probability: 0.0538, Prediction: 0.0

Epoch 1/3:  25%|██▌       | 1019/4000 [09:40<28:40,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.31558895111084, Predicted Probability: 0.9102, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.075061082839966, Predicted Probability: 0.0441, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1020/4000 [09:41<37:02,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4538211822509766, Predicted Probability: 0.0307, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9284383654594421, Predicted Probability: 0.7168, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1021/4000 [09:42<37:13,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.104405403137207, Predicted Probability: 0.8913, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8609638214111328, Predicted Probability: 0.1346, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1022/4000 [09:42<31:40,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.945128917694092, Predicted Probability: 0.0500, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0639803409576416, Predicted Probability: 0.9554, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1023/4000 [09:43<28:59,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7339892387390137, Predicted Probability: 0.9390, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.674750328063965, Predicted Probability: 0.9355, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1024/4000 [09:43<26:58,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.739926815032959, Predicted Probability: 0.8507, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2817156314849854, Predicted Probability: 0.9638, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1025/4000 [09:44<29:37,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.982725739479065, Predicted Probability: 0.8790, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9153112173080444, Predicted Probability: 0.1284, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1026/4000 [09:44<26:18,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.937256097793579, Predicted Probability: 0.9497, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9624922275543213, Predicted Probability: 0.9509, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1027/4000 [09:45<26:29,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1896897554397583, Predicted Probability: 0.2333, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9695050716400146, Predicted Probability: 0.9512, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1028/4000 [09:46<29:26,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.393817663192749, Predicted Probability: 0.5972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0735414028167725, Predicted Probability: 0.1117, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1029/4000 [09:46<31:17,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.208857536315918, Predicted Probability: 0.0990, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8717845678329468, Predicted Probability: 0.8667, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1030/4000 [09:47<32:52,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.968146324157715, Predicted Probability: 0.0489, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8545384407043457, Predicted Probability: 0.8647, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1031/4000 [09:48<34:06,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.358018398284912, Predicted Probability: 0.0336, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8838579654693604, Predicted Probability: 0.8681, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1032/4000 [09:48<29:22,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.463519334793091, Predicted Probability: 0.0785, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1169052124023438, Predicted Probability: 0.9576, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1033/4000 [09:49<33:19,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9943715333938599, Predicted Probability: 0.1198, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3791351318359375, Predicted Probability: 0.0330, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1034/4000 [09:50<29:03,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2557575702667236, Predicted Probability: 0.9629, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.838399887084961, Predicted Probability: 0.9447, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1035/4000 [09:50<31:36,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7185578942298889, Predicted Probability: 0.3277, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9139316082000732, Predicted Probability: 0.7138, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1036/4000 [09:51<27:39,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.372657299041748, Predicted Probability: 0.9668, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.836129069328308, Predicted Probability: 0.1375, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1037/4000 [09:52<31:10,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9430646896362305, Predicted Probability: 0.8747, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.014195799827575684, Predicted Probability: 0.4965, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1038/4000 [09:53<46:06,  1.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8374031186103821, Predicted Probability: 0.6979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.302102565765381, Predicted Probability: 0.0355, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1039/4000 [09:54<37:59,  1.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3136324882507324, Predicted Probability: 0.9100, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.933307409286499, Predicted Probability: 0.0505, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1040/4000 [09:54<37:14,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7591876983642578, Predicted Probability: 0.8531, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6020188331604004, Predicted Probability: 0.0265, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1041/4000 [09:54<29:06,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.992603302001953, Predicted Probability: 0.9522, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.375389337539673, Predicted Probability: 0.9669, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1042/4000 [09:55<31:57,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7985026836395264, Predicted Probability: 0.8580, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.281548023223877, Predicted Probability: 0.0927, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1043/4000 [09:56<27:48,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8371708393096924, Predicted Probability: 0.9447, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2158384323120117, Predicted Probability: 0.0386, Prediction: 0.0

Epoch 1/3:  26%|██▌       | 1044/4000 [09:56<24:53,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.825206995010376, Predicted Probability: 0.9440, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4821178913116455, Predicted Probability: 0.9229, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1045/4000 [09:56<20:31,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.282411813735962, Predicted Probability: 0.9638, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.555001974105835, Predicted Probability: 0.9722, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1047/4000 [09:57<18:41,  2.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7580175399780273, Predicted Probability: 0.9404, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8231397867202759, Predicted Probability: 0.1391, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 2.706648111343384, Predicted Probability: 0.9374, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2371630668640137, Predicted Probability: 0.9622, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1048/4000 [09:58<24:32,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6944873332977295, Predicted Probability: 0.0243, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.414463758468628, Predicted Probability: 0.9179, Prediction: 1.0

Epoch 1/3:  26%|██▌       | 1049/4000 [09:58<22:34,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9543994665145874, Predicted Probability: 0.8759, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.732553243637085, Predicted Probability: 0.9389, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1050/4000 [09:59<26:42,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3802163004875183, Predicted Probability: 0.5939, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2906434535980225, Predicted Probability: 0.0359, Prediction: 0.0

Epoch 1/3:  26%|██▋       | 1051/4000 [09:59<24:14,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.146812677383423, Predicted Probability: 0.0412, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.131522536277771, Predicted Probability: 0.2439, Prediction: 0.0

Epoch 1/3:  26%|██▋       | 1052/4000 [10:00<27:51,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.912651777267456, Predicted Probability: 0.2865, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4729130268096924, Predicted Probability: 0.0301, Prediction: 0.0

Epoch 1/3:  26%|██▋       | 1053/4000 [10:01<30:06,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.621994972229004, Predicted Probability: 0.0260, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9767208099365234, Predicted Probability: 0.8783, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1054/4000 [10:01<29:00,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2029261589050293, Predicted Probability: 0.4494, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0732834339141846, Predicted Probability: 0.8883, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1055/4000 [10:02<26:41,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.622699022293091, Predicted Probability: 0.9323, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4206135272979736, Predicted Probability: 0.9184, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1056/4000 [10:03<31:28,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5441064834594727, Predicted Probability: 0.0281, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6779894828796387, Predicted Probability: 0.0247, Prediction: 0.0

Epoch 1/3:  26%|██▋       | 1057/4000 [10:03<33:40,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.421287775039673, Predicted Probability: 0.0816, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7655737400054932, Predicted Probability: 0.8539, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1058/4000 [10:04<34:24,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8144869804382324, Predicted Probability: 0.0216, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9974859952926636, Predicted Probability: 0.8805, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1059/4000 [10:05<34:37,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1335904598236084, Predicted Probability: 0.1059, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.13449132442474365, Predicted Probability: 0.5336, Prediction: 1.0

Epoch 1/3:  26%|██▋       | 1060/4000 [10:05<29:43,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.865792751312256, Predicted Probability: 0.9461, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4865692853927612, Predicted Probability: 0.1844, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1061/4000 [10:05<23:58,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.58447265625, Predicted Probability: 0.9730, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5256288051605225, Predicted Probability: 0.9714, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1062/4000 [10:06<24:46,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.312102794647217, Predicted Probability: 0.9099, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.740640163421631, Predicted Probability: 0.0606, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1063/4000 [10:07<27:59,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5773673057556152, Predicted Probability: 0.0272, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8079239130020142, Predicted Probability: 0.8591, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1064/4000 [10:07<30:29,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.1756148338317871, Predicted Probability: 0.5438, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5182013511657715, Predicted Probability: 0.0746, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1065/4000 [10:08<27:04,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.167715072631836, Predicted Probability: 0.2373, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2467474937438965, Predicted Probability: 0.9626, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1066/4000 [10:08<24:24,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.658402919769287, Predicted Probability: 0.0655, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.255624294281006, Predicted Probability: 0.9629, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1068/4000 [10:09<20:19,  2.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.302143096923828, Predicted Probability: 0.0909, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.665783405303955, Predicted Probability: 0.0249, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 2.738889455795288, Predicted Probability: 0.9393, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.16742029786109924, Predicted Probability: 0.5418, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1069/4000 [10:10<24:54,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7320184707641602, Predicted Probability: 0.8497, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6451542377471924, Predicted Probability: 0.0255, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1070/4000 [10:10<22:56,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4198455810546875, Predicted Probability: 0.1947, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.557795524597168, Predicted Probability: 0.8260, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1071/4000 [10:10<22:21,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0574452877044678, Predicted Probability: 0.8867, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.1095600500702858, Predicted Probability: 0.4726, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1072/4000 [10:11<26:40,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0871615409851074, Predicted Probability: 0.0436, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.22749659419059753, Predicted Probability: 0.5566, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1073/4000 [10:12<26:31,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.663050889968872, Predicted Probability: 0.0250, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2207314521074295, Predicted Probability: 0.4450, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1074/4000 [10:12<29:25,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6938567161560059, Predicted Probability: 0.8447, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9723283052444458, Predicted Probability: 0.1221, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1075/4000 [10:13<23:35,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5634350776672363, Predicted Probability: 0.9724, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5707550048828125, Predicted Probability: 0.0710, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1076/4000 [10:13<20:25,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4944632053375244, Predicted Probability: 0.9705, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.3896281719207764, Predicted Probability: 0.0840, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1077/4000 [10:14<26:47,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.593698024749756, Predicted Probability: 0.0268, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4163622856140137, Predicted Probability: 0.0819, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1078/4000 [10:14<24:30,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.894302248954773, Predicted Probability: 0.2902, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2441532611846924, Predicted Probability: 0.9625, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1079/4000 [10:15<22:37,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.218456983566284, Predicted Probability: 0.9615, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.230424642562866, Predicted Probability: 0.9620, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1080/4000 [10:15<26:29,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6012804508209229, Predicted Probability: 0.8322, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7147021293640137, Predicted Probability: 0.0238, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1081/4000 [10:15<21:34,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.14974308013916, Predicted Probability: 0.9589, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.099717617034912, Predicted Probability: 0.1091, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1082/4000 [10:16<20:25,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8033313751220703, Predicted Probability: 0.0571, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.156860113143921, Predicted Probability: 0.9592, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1083/4000 [10:17<25:00,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2698907852172852, Predicted Probability: 0.7807, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.873091697692871, Predicted Probability: 0.0204, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1084/4000 [10:17<29:03,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5830848217010498, Predicted Probability: 0.8296, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3936312198638916, Predicted Probability: 0.0837, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1085/4000 [10:18<25:44,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.551007032394409, Predicted Probability: 0.9721, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6704888939857483, Predicted Probability: 0.3384, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1086/4000 [10:18<28:28,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.28067734837532043, Predicted Probability: 0.4303, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.599266767501831, Predicted Probability: 0.3545, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1087/4000 [10:19<25:11,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.012660503387451, Predicted Probability: 0.9531, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6201934814453125, Predicted Probability: 0.0679, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1088/4000 [10:19<24:10,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.987842559814453, Predicted Probability: 0.9520, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.99397873878479, Predicted Probability: 0.9523, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1089/4000 [10:20<27:51,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.399019479751587, Predicted Probability: 0.0323, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.7139477729797363, Predicted Probability: 0.8473, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1090/4000 [10:21<27:36,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8760247230529785, Predicted Probability: 0.0534, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.48038309812545776, Predicted Probability: 0.3822, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1091/4000 [10:21<31:00,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7966160178184509, Predicted Probability: 0.6893, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5116580128669739, Predicted Probability: 0.6252, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1092/4000 [10:22<32:17,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8770127296447754, Predicted Probability: 0.0533, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6250154972076416, Predicted Probability: 0.8355, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1093/4000 [10:22<27:59,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.388085126876831, Predicted Probability: 0.9673, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0659682750701904, Predicted Probability: 0.1124, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1094/4000 [10:23<30:58,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.879340410232544, Predicted Probability: 0.1325, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.706000328063965, Predicted Probability: 0.0240, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1095/4000 [10:24<32:14,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.81221604347229, Predicted Probability: 0.0216, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5652185678482056, Predicted Probability: 0.8271, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1096/4000 [10:25<33:07,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4677568674087524, Predicted Probability: 0.8127, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3295328617095947, Predicted Probability: 0.0346, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1097/4000 [10:25<29:35,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0611402988433838, Predicted Probability: 0.2571, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2756497859954834, Predicted Probability: 0.9636, Prediction: 1.0

Epoch 1/3:  27%|██▋       | 1098/4000 [10:26<31:35,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.460737705230713, Predicted Probability: 0.8116, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9965579509735107, Predicted Probability: 0.1196, Prediction: 0.0

Epoch 1/3:  27%|██▋       | 1099/4000 [10:27<33:53,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.649662733078003, Predicted Probability: 0.0253, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9225032329559326, Predicted Probability: 0.9489, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1100/4000 [10:27<32:37,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0658974647521973, Predicted Probability: 0.8875, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8516355752944946, Predicted Probability: 0.8643, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1101/4000 [10:28<34:26,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5559067726135254, Predicted Probability: 0.0278, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4596836566925049, Predicted Probability: 0.8115, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1102/4000 [10:29<29:33,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9465651512145996, Predicted Probability: 0.9501, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.306452989578247, Predicted Probability: 0.2131, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1103/4000 [10:29<26:08,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1843531131744385, Predicted Probability: 0.9602, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.373051643371582, Predicted Probability: 0.9147, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1104/4000 [10:30<29:12,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6398420333862305, Predicted Probability: 0.0256, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.521958827972412, Predicted Probability: 0.9257, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1105/4000 [10:30<23:24,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.731820583343506, Predicted Probability: 0.9766, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2191579341888428, Predicted Probability: 0.9615, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1106/4000 [10:31<27:36,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.593590497970581, Predicted Probability: 0.8311, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.579561233520508, Predicted Probability: 0.0271, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1107/4000 [10:31<25:38,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.172276496887207, Predicted Probability: 0.9598, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.788440227508545, Predicted Probability: 0.8567, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1108/4000 [10:32<28:21,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6502997875213623, Predicted Probability: 0.0253, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4819508790969849, Predicted Probability: 0.8149, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1109/4000 [10:32<22:45,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5589194297790527, Predicted Probability: 0.9723, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6536076068878174, Predicted Probability: 0.9342, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1110/4000 [10:32<21:19,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.555617332458496, Predicted Probability: 0.9722, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.193650484085083, Predicted Probability: 0.1003, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1111/4000 [10:33<22:54,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.17125587165355682, Predicted Probability: 0.5427, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6727471351623535, Predicted Probability: 0.9354, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1112/4000 [10:34<26:16,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6098835468292236, Predicted Probability: 0.0263, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.652290940284729, Predicted Probability: 0.8392, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1113/4000 [10:34<23:52,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.33070969581604, Predicted Probability: 0.7910, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.059629201889038, Predicted Probability: 0.9552, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1114/4000 [10:34<21:59,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.6492385864257812, Predicted Probability: 0.1612, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.734114170074463, Predicted Probability: 0.8499, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1115/4000 [10:35<26:07,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.782569408416748, Predicted Probability: 0.0223, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9762182235717773, Predicted Probability: 0.8783, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1116/4000 [10:35<23:45,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7998137474060059, Predicted Probability: 0.1419, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4529356956481934, Predicted Probability: 0.9208, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1117/4000 [10:36<27:20,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6008572578430176, Predicted Probability: 0.0266, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.698959231376648, Predicted Probability: 0.1546, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1118/4000 [10:36<22:06,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.436084270477295, Predicted Probability: 0.9688, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5446677207946777, Predicted Probability: 0.9272, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1119/4000 [10:37<26:23,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8430847525596619, Predicted Probability: 0.3009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6560540199279785, Predicted Probability: 0.0252, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1120/4000 [10:38<28:57,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.074643075466156, Predicted Probability: 0.4813, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6044421195983887, Predicted Probability: 0.0265, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1121/4000 [10:38<27:59,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5825679302215576, Predicted Probability: 0.0271, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.000434160232544, Predicted Probability: 0.8808, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1122/4000 [10:39<27:32,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0384091138839722, Predicted Probability: 0.7385, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.661187171936035, Predicted Probability: 0.9347, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1123/4000 [10:40<30:00,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.71626353263855, Predicted Probability: 0.0237, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1321749687194824, Predicted Probability: 0.8940, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1124/4000 [10:40<26:22,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4279751777648926, Predicted Probability: 0.9189, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.330842971801758, Predicted Probability: 0.9655, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1125/4000 [10:41<29:21,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8191678524017334, Predicted Probability: 0.8605, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8452513217926025, Predicted Probability: 0.0209, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1126/4000 [10:42<31:18,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9584518671035767, Predicted Probability: 0.7228, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.469259262084961, Predicted Probability: 0.0780, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1127/4000 [10:42<33:25,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.462258815765381, Predicted Probability: 0.0304, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.708134889602661, Predicted Probability: 0.0239, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1128/4000 [10:43<35:05,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.795114517211914, Predicted Probability: 0.0220, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8461315631866455, Predicted Probability: 0.0209, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1129/4000 [10:44<35:31,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.792325019836426, Predicted Probability: 0.0577, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7805488109588623, Predicted Probability: 0.0223, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1130/4000 [10:45<35:17,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.0803079605102539, Predicted Probability: 0.5201, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.118434429168701, Predicted Probability: 0.0424, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1131/4000 [10:45<35:09,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.732809066772461, Predicted Probability: 0.0234, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4798922538757324, Predicted Probability: 0.8146, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1132/4000 [10:46<35:53,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8077356815338135, Predicted Probability: 0.3084, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7900152206420898, Predicted Probability: 0.1431, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1133/4000 [10:47<36:43,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3086568117141724, Predicted Probability: 0.2127, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2782249450683594, Predicted Probability: 0.0363, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1134/4000 [10:48<36:10,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.393235683441162, Predicted Probability: 0.0325, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8877356052398682, Predicted Probability: 0.8685, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1135/4000 [10:48<30:38,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.37487530708313, Predicted Probability: 0.9149, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6294467449188232, Predicted Probability: 0.9327, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1136/4000 [10:49<26:41,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.126279592514038, Predicted Probability: 0.9580, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5970160961151123, Predicted Probability: 0.9307, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1137/4000 [10:49<29:30,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6274497509002686, Predicted Probability: 0.0674, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7402377128601074, Predicted Probability: 0.0232, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1138/4000 [10:50<28:18,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.769477128982544, Predicted Probability: 0.6834, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6174399256706238, Predicted Probability: 0.3504, Prediction: 0.0

Epoch 1/3:  28%|██▊       | 1139/4000 [10:51<30:54,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.791733741760254, Predicted Probability: 0.0221, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9773881435394287, Predicted Probability: 0.7266, Prediction: 1.0

Epoch 1/3:  28%|██▊       | 1140/4000 [10:51<32:02,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.25906676054000854, Predicted Probability: 0.4356, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.886566162109375, Predicted Probability: 0.0201, Prediction: 0.0

Epoch 1/3:  29%|██▊       | 1141/4000 [10:52<33:06,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4665579795837402, Predicted Probability: 0.8125, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8171472549438477, Predicted Probability: 0.0215, Prediction: 0.0

Epoch 1/3:  29%|██▊       | 1142/4000 [10:53<30:45,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.869741201400757, Predicted Probability: 0.9463, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7350289821624756, Predicted Probability: 0.3241, Prediction: 0.0

Epoch 1/3:  29%|██▊       | 1143/4000 [10:53<27:00,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7445383071899414, Predicted Probability: 0.8513, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.688271701335907, Predicted Probability: 0.6656, Prediction: 1.0

Epoch 1/3:  29%|██▊       | 1144/4000 [10:53<25:16,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.021524578332901, Predicted Probability: 0.5054, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1577318161725998, Predicted Probability: 0.5394, Prediction: 1.0

Epoch 1/3:  29%|██▊       | 1145/4000 [10:54<28:58,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5620830059051514, Predicted Probability: 0.8267, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.723924160003662, Predicted Probability: 0.0236, Prediction: 0.0

Epoch 1/3:  29%|██▊       | 1146/4000 [10:55<25:48,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8128597736358643, Predicted Probability: 0.9434, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.329130172729492, Predicted Probability: 0.0346, Prediction: 0.0

Epoch 1/3:  29%|██▊       | 1147/4000 [10:55<28:49,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.251589059829712, Predicted Probability: 0.7776, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.800654649734497, Predicted Probability: 0.0219, Prediction: 0.0

Epoch 1/3:  29%|██▊       | 1148/4000 [10:56<25:20,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7284200191497803, Predicted Probability: 0.0235, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.474438428878784, Predicted Probability: 0.9223, Prediction: 1.0

Epoch 1/3:  29%|██▊       | 1149/4000 [10:57<28:55,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.3699455261230469, Predicted Probability: 0.2026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.780015468597412, Predicted Probability: 0.0584, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1150/4000 [10:57<28:09,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4579660892486572, Predicted Probability: 0.0789, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.958696126937866, Predicted Probability: 0.0493, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1151/4000 [10:57<25:06,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7919187545776367, Predicted Probability: 0.8572, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3923592567443848, Predicted Probability: 0.0325, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1152/4000 [10:58<28:14,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6629869937896729, Predicted Probability: 0.8406, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.623770236968994, Predicted Probability: 0.0260, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1153/4000 [10:59<27:17,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8114922046661377, Predicted Probability: 0.8595, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2547876834869385, Predicted Probability: 0.9628, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1154/4000 [10:59<22:08,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2789485454559326, Predicted Probability: 0.9637, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.37711501121521, Predicted Probability: 0.9670, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1155/4000 [11:00<26:28,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1393332481384277, Predicted Probability: 0.7576, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.712193489074707, Predicted Probability: 0.0238, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1156/4000 [11:01<29:28,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3002951145172119, Predicted Probability: 0.4255, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.00496244430542, Predicted Probability: 0.8813, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1157/4000 [11:01<28:19,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7602839469909668, Predicted Probability: 0.8532, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.569596767425537, Predicted Probability: 0.0274, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1158/4000 [11:01<25:06,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.796931743621826, Predicted Probability: 0.9425, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2324475049972534, Predicted Probability: 0.7742, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1159/4000 [11:02<28:12,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4687235355377197, Predicted Probability: 0.8129, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.775946617126465, Predicted Probability: 0.0224, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1160/4000 [11:03<30:37,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6910929679870605, Predicted Probability: 0.6662, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.837606430053711, Predicted Probability: 0.0211, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1161/4000 [11:03<29:16,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.097877025604248, Predicted Probability: 0.9568, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.469322681427002, Predicted Probability: 0.9698, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1162/4000 [11:04<32:31,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.803661823272705, Predicted Probability: 0.0218, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6930971145629883, Predicted Probability: 0.0243, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1163/4000 [11:05<36:58,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4152026176452637, Predicted Probability: 0.0318, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.355579376220703, Predicted Probability: 0.0337, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1164/4000 [11:06<36:37,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5080909729003906, Predicted Probability: 0.0291, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2797470092773438, Predicted Probability: 0.7824, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1165/4000 [11:07<36:08,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4064083099365234, Predicted Probability: 0.0321, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7930924892425537, Predicted Probability: 0.8573, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1166/4000 [11:08<35:49,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.424299716949463, Predicted Probability: 0.8060, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.915478229522705, Predicted Probability: 0.8716, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1167/4000 [11:08<36:54,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.51290225982666, Predicted Probability: 0.0289, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.80489444732666, Predicted Probability: 0.0218, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1168/4000 [11:09<36:22,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.688171148300171, Predicted Probability: 0.0637, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.860978603363037, Predicted Probability: 0.0206, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1169/4000 [11:10<35:51,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.530790328979492, Predicted Probability: 0.0284, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.00903281569480896, Predicted Probability: 0.4977, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1170/4000 [11:10<30:19,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.145139217376709, Predicted Probability: 0.0413, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6550962924957275, Predicted Probability: 0.0252, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1171/4000 [11:11<26:38,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.550412178039551, Predicted Probability: 0.9721, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.359278440475464, Predicted Probability: 0.9137, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1172/4000 [11:11<25:01,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1512982845306396, Predicted Probability: 0.9590, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.065056085586548, Predicted Probability: 0.9554, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1173/4000 [11:12<28:35,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.558751106262207, Predicted Probability: 0.8262, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.624660015106201, Predicted Probability: 0.0260, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1174/4000 [11:12<22:53,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2346110343933105, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2971603870391846, Predicted Probability: 0.0357, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1175/4000 [11:13<26:50,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.850731611251831, Predicted Probability: 0.0208, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2580393552780151, Predicted Probability: 0.7787, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1176/4000 [11:14<28:51,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7908194065093994, Predicted Probability: 0.0221, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4435371160507202, Predicted Probability: 0.8090, Prediction: 1.0

Epoch 1/3:  29%|██▉       | 1177/4000 [11:14<25:24,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4797894954681396, Predicted Probability: 0.9701, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9099317789077759, Predicted Probability: 0.1290, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1178/4000 [11:15<28:53,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3159265518188477, Predicted Probability: 0.9102, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.879303455352783, Predicted Probability: 0.0202, Prediction: 0.0

Epoch 1/3:  29%|██▉       | 1179/4000 [11:16<31:04,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.328514575958252, Predicted Probability: 0.0346, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0151457786560059, Predicted Probability: 0.7340, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1180/4000 [11:16<32:10,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9886311292648315, Predicted Probability: 0.8796, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.026767730712891, Predicted Probability: 0.0175, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1181/4000 [11:17<33:20,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1064839363098145, Predicted Probability: 0.0428, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9481812715530396, Predicted Probability: 0.8752, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1182/4000 [11:18<35:17,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9722015857696533, Predicted Probability: 0.8778, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0973362922668457, Predicted Probability: 0.0432, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1183/4000 [11:18<33:18,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0154882669448853, Predicted Probability: 0.7341, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8119868040084839, Predicted Probability: 0.8596, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1184/4000 [11:19<34:49,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9912021160125732, Predicted Probability: 0.1201, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3144102096557617, Predicted Probability: 0.0351, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1185/4000 [11:20<34:42,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8393945693969727, Predicted Probability: 0.0211, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.21063363552093506, Predicted Probability: 0.4475, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1186/4000 [11:21<34:50,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3282275199890137, Predicted Probability: 0.0346, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6373894214630127, Predicted Probability: 0.0668, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1187/4000 [11:22<35:33,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.05034419894218445, Predicted Probability: 0.5126, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.854541063308716, Predicted Probability: 0.0207, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1188/4000 [11:22<29:58,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3263678550720215, Predicted Probability: 0.0347, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9059996604919434, Predicted Probability: 0.9803, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1189/4000 [11:22<26:05,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8666224479675293, Predicted Probability: 0.0205, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.262885332107544, Predicted Probability: 0.9058, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1190/4000 [11:23<28:39,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.23009026050567627, Predicted Probability: 0.5573, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.827256202697754, Predicted Probability: 0.0213, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1191/4000 [11:24<30:01,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.41259342432022095, Predicted Probability: 0.6017, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7469515800476074, Predicted Probability: 0.0230, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1192/4000 [11:25<32:06,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4818708896636963, Predicted Probability: 0.0771, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7452661991119385, Predicted Probability: 0.0231, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1193/4000 [11:25<30:20,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9151206016540527, Predicted Probability: 0.9486, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.702319383621216, Predicted Probability: 0.9372, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1194/4000 [11:26<33:27,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8433475494384766, Predicted Probability: 0.0210, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.398512601852417, Predicted Probability: 0.0323, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1195/4000 [11:27<35:09,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.666078567504883, Predicted Probability: 0.0249, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6866421699523926, Predicted Probability: 0.0638, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1196/4000 [11:28<36:22,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.941534996032715, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2469613552093506, Predicted Probability: 0.0374, Prediction: 0.0

Epoch 1/3:  30%|██▉       | 1197/4000 [11:28<30:43,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.508371591567993, Predicted Probability: 0.9247, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1338398456573486, Predicted Probability: 0.9583, Prediction: 1.0

Epoch 1/3:  30%|██▉       | 1198/4000 [11:29<30:17,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2864866256713867, Predicted Probability: 0.0360, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.478163480758667, Predicted Probability: 0.9226, Prediction: 1.0

Epoch 1/3:  30%|███       | 1200/4000 [11:29<23:03,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.970832347869873, Predicted Probability: 0.8777, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.706552267074585, Predicted Probability: 0.8464, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 3.5244626998901367, Predicted Probability: 0.9714, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9587924480438232, Predicted Probability: 0.8764, Prediction: 1.0

Epoch 1/3:  30%|███       | 1201/4000 [11:30<21:35,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.415560007095337, Predicted Probability: 0.9180, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.394770622253418, Predicted Probability: 0.9675, Prediction: 1.0

Epoch 1/3:  30%|███       | 1202/4000 [11:30<21:16,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.941476821899414, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1851634979248047, Predicted Probability: 0.8989, Prediction: 1.0

Epoch 1/3:  30%|███       | 1203/4000 [11:31<20:13,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0673515796661377, Predicted Probability: 0.9555, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.227870464324951, Predicted Probability: 0.0381, Prediction: 0.0

Epoch 1/3:  30%|███       | 1204/4000 [11:31<17:50,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7655303478240967, Predicted Probability: 0.9774, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.025105953216553, Predicted Probability: 0.9825, Prediction: 1.0

Epoch 1/3:  30%|███       | 1205/4000 [11:32<22:40,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.030139446258545, Predicted Probability: 0.0175, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7820181846618652, Predicted Probability: 0.6861, Prediction: 1.0

Epoch 1/3:  30%|███       | 1206/4000 [11:32<20:56,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9853270053863525, Predicted Probability: 0.0182, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.609794855117798, Predicted Probability: 0.9737, Prediction: 1.0

Epoch 1/3:  30%|███       | 1207/4000 [11:32<20:52,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.703371286392212, Predicted Probability: 0.0628, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.105912923812866, Predicted Probability: 0.8915, Prediction: 1.0

Epoch 1/3:  30%|███       | 1208/4000 [11:33<17:37,  2.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3489391803741455, Predicted Probability: 0.9661, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.775615930557251, Predicted Probability: 0.9776, Prediction: 1.0

Epoch 1/3:  30%|███       | 1209/4000 [11:33<22:32,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8006322383880615, Predicted Probability: 0.8582, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9276654720306396, Predicted Probability: 0.0193, Prediction: 0.0

Epoch 1/3:  30%|███       | 1210/4000 [11:34<26:29,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.034149169921875, Predicted Probability: 0.0174, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.371579647064209, Predicted Probability: 0.0854, Prediction: 0.0

Epoch 1/3:  30%|███       | 1211/4000 [11:35<23:38,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.881878137588501, Predicted Probability: 0.9469, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.0013678526738658547, Predicted Probability: 0.4997, Prediction: 0.0

Epoch 1/3:  30%|███       | 1212/4000 [11:35<22:43,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.16959352791309357, Predicted Probability: 0.4577, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.571404457092285, Predicted Probability: 0.9727, Prediction: 1.0

Epoch 1/3:  30%|███       | 1213/4000 [11:35<18:47,  2.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.911717176437378, Predicted Probability: 0.0196, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.569389581680298, Predicted Probability: 0.9726, Prediction: 1.0

Epoch 1/3:  30%|███       | 1214/4000 [11:36<18:15,  2.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7676823139190674, Predicted Probability: 0.0226, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.136950731277466, Predicted Probability: 0.9584, Prediction: 1.0

Epoch 1/3:  30%|███       | 1215/4000 [11:36<22:41,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.650939464569092, Predicted Probability: 0.0253, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.11112605035305023, Predicted Probability: 0.5278, Prediction: 1.0

Epoch 1/3:  30%|███       | 1216/4000 [11:37<24:37,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8302690982818604, Predicted Probability: 0.9443, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2097880840301514, Predicted Probability: 0.0989, Prediction: 0.0

Epoch 1/3:  30%|███       | 1217/4000 [11:38<27:37,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6144793033599854, Predicted Probability: 0.8340, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1539071798324585, Predicted Probability: 0.5384, Prediction: 1.0

Epoch 1/3:  30%|███       | 1218/4000 [11:38<29:23,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.983381748199463, Predicted Probability: 0.0183, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4338934421539307, Predicted Probability: 0.8075, Prediction: 1.0

Epoch 1/3:  30%|███       | 1219/4000 [11:39<30:31,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2990455627441406, Predicted Probability: 0.0356, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4919500350952148, Predicted Probability: 0.8164, Prediction: 1.0

Epoch 1/3:  30%|███       | 1220/4000 [11:40<31:06,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0774171352386475, Predicted Probability: 0.0440, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.561961054801941, Predicted Probability: 0.8266, Prediction: 1.0

Epoch 1/3:  31%|███       | 1221/4000 [11:40<31:59,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.138123512268066, Predicted Probability: 0.0157, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.616898775100708, Predicted Probability: 0.8344, Prediction: 1.0

Epoch 1/3:  31%|███       | 1222/4000 [11:41<27:44,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8502941131591797, Predicted Probability: 0.0547, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8668735027313232, Predicted Probability: 0.9462, Prediction: 1.0

Epoch 1/3:  31%|███       | 1223/4000 [11:42<30:26,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.199885845184326, Predicted Probability: 0.0148, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2238171100616455, Predicted Probability: 0.0383, Prediction: 0.0

Epoch 1/3:  31%|███       | 1224/4000 [11:42<29:47,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.577723741531372, Predicted Probability: 0.9294, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.273965358734131, Predicted Probability: 0.0137, Prediction: 0.0

Epoch 1/3:  31%|███       | 1226/4000 [11:43<25:35,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.164334297180176, Predicted Probability: 0.0153, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.074583053588867, Predicted Probability: 0.0167, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 3.1378173828125, Predicted Probability: 0.9584, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4991066455841064, Predicted Probability: 0.9707, Prediction: 1.0

Epoch 1/3:  31%|███       | 1227/4000 [11:44<22:52,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2453699111938477, Predicted Probability: 0.9625, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6174395084381104, Predicted Probability: 0.9739, Prediction: 1.0

Epoch 1/3:  31%|███       | 1228/4000 [11:44<21:15,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.482684850692749, Predicted Probability: 0.9702, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.3993620872497559, Predicted Probability: 0.8021, Prediction: 1.0

Epoch 1/3:  31%|███       | 1229/4000 [11:45<24:57,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.0083088874816895, Predicted Probability: 0.0178, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.031534194946289, Predicted Probability: 0.8841, Prediction: 1.0

Epoch 1/3:  31%|███       | 1230/4000 [11:45<22:37,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.410785436630249, Predicted Probability: 0.9176, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.138491153717041, Predicted Probability: 0.9843, Prediction: 1.0

Epoch 1/3:  31%|███       | 1231/4000 [11:46<21:19,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.303925037384033, Predicted Probability: 0.9646, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4195542335510254, Predicted Probability: 0.9183, Prediction: 1.0

Epoch 1/3:  31%|███       | 1232/4000 [11:46<25:27,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7665027976036072, Predicted Probability: 0.3172, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.19921648502349854, Predicted Probability: 0.4504, Prediction: 0.0

Epoch 1/3:  31%|███       | 1233/4000 [11:47<28:37,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.603462815284729, Predicted Probability: 0.3536, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.00039529800415, Predicted Probability: 0.0180, Prediction: 0.0

Epoch 1/3:  31%|███       | 1234/4000 [11:48<30:13,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8732526302337646, Predicted Probability: 0.2946, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.149322509765625, Predicted Probability: 0.0155, Prediction: 0.0

Epoch 1/3:  31%|███       | 1235/4000 [11:49<31:31,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1338751316070557, Predicted Probability: 0.0417, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5875587463378906, Predicted Probability: 0.8303, Prediction: 1.0

Epoch 1/3:  31%|███       | 1236/4000 [11:49<27:10,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4767889976501465, Predicted Probability: 0.0300, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.800832748413086, Predicted Probability: 0.9781, Prediction: 1.0

Epoch 1/3:  31%|███       | 1237/4000 [11:50<26:42,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5233185291290283, Predicted Probability: 0.9258, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.01924467086792, Predicted Probability: 0.8828, Prediction: 1.0

Epoch 1/3:  31%|███       | 1238/4000 [11:50<29:15,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1662397384643555, Predicted Probability: 0.0153, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4045560359954834, Predicted Probability: 0.8029, Prediction: 1.0

Epoch 1/3:  31%|███       | 1239/4000 [11:51<31:09,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.027192115783691, Predicted Probability: 0.0175, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7435007095336914, Predicted Probability: 0.8511, Prediction: 1.0

Epoch 1/3:  31%|███       | 1240/4000 [11:51<27:03,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6850361824035645, Predicted Probability: 0.1564, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0031148195266724, Predicted Probability: 0.2683, Prediction: 0.0

Epoch 1/3:  31%|███       | 1241/4000 [11:52<28:57,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7952625751495361, Predicted Probability: 0.8576, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.075469017028809, Predicted Probability: 0.0167, Prediction: 0.0

Epoch 1/3:  31%|███       | 1242/4000 [11:53<25:26,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8009495735168457, Predicted Probability: 0.9427, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.147826910018921, Predicted Probability: 0.8955, Prediction: 1.0

Epoch 1/3:  31%|███       | 1243/4000 [11:53<28:03,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.175350189208984, Predicted Probability: 0.0151, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3290715217590332, Predicted Probability: 0.7907, Prediction: 1.0

Epoch 1/3:  31%|███       | 1244/4000 [11:54<29:34,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.626119613647461, Predicted Probability: 0.8356, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.1703643798828125, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 1/3:  31%|███       | 1245/4000 [11:54<26:06,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.43661877512931824, Predicted Probability: 0.6075, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.167959690093994, Predicted Probability: 0.8973, Prediction: 1.0

Epoch 1/3:  31%|███       | 1246/4000 [11:55<23:20,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8163927793502808, Predicted Probability: 0.3065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.631573438644409, Predicted Probability: 0.0671, Prediction: 0.0

Epoch 1/3:  31%|███       | 1247/4000 [11:56<27:22,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.140352725982666, Predicted Probability: 0.0157, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.076000213623047, Predicted Probability: 0.0167, Prediction: 0.0

Epoch 1/3:  31%|███       | 1248/4000 [11:56<29:06,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.679011583328247, Predicted Probability: 0.0246, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.20212695002555847, Predicted Probability: 0.5504, Prediction: 1.0

Epoch 1/3:  31%|███       | 1249/4000 [11:56<23:09,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2547789514064789, Predicted Probability: 0.4366, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5487992763519287, Predicted Probability: 0.9720, Prediction: 1.0

Epoch 1/3:  31%|███▏      | 1250/4000 [11:57<24:02,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.781071424484253, Predicted Probability: 0.0223, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5054399967193604, Predicted Probability: 0.9708, Prediction: 1.0

Epoch 1/3:  31%|███▏      | 1251/4000 [11:58<26:47,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.758942186832428, Predicted Probability: 0.6811, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.221343040466309, Predicted Probability: 0.0145, Prediction: 0.0

Epoch 1/3:  31%|███▏      | 1252/4000 [11:59<29:03,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4745712280273438, Predicted Probability: 0.9223, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.1557416915893555, Predicted Probability: 0.0154, Prediction: 0.0

Epoch 1/3:  31%|███▏      | 1253/4000 [11:59<30:51,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6605920791625977, Predicted Probability: 0.0653, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0497655868530273, Predicted Probability: 0.0452, Prediction: 0.0

Epoch 1/3:  31%|███▏      | 1254/4000 [12:00<33:18,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.161834716796875, Predicted Probability: 0.0153, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5800931453704834, Predicted Probability: 0.0271, Prediction: 0.0

Epoch 1/3:  31%|███▏      | 1255/4000 [12:01<28:30,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3634722232818604, Predicted Probability: 0.2037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1489291191101074, Predicted Probability: 0.9589, Prediction: 1.0

Epoch 1/3:  31%|███▏      | 1256/4000 [12:01<29:56,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5259761810302734, Predicted Probability: 0.0286, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1314212679862976, Predicted Probability: 0.4672, Prediction: 0.0

Epoch 1/3:  31%|███▏      | 1257/4000 [12:02<26:12,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9093154668807983, Predicted Probability: 0.8709, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8977444171905518, Predicted Probability: 0.9801, Prediction: 1.0

Epoch 1/3:  31%|███▏      | 1258/4000 [12:02<23:21,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.510012149810791, Predicted Probability: 0.9248, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6586456298828125, Predicted Probability: 0.9345, Prediction: 1.0

Epoch 1/3:  31%|███▏      | 1259/4000 [12:02<21:42,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.894843578338623, Predicted Probability: 0.9476, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.92192006111145, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1260/4000 [12:03<25:33,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7079753875732422, Predicted Probability: 0.8466, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6080145835876465, Predicted Probability: 0.0264, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1261/4000 [12:04<28:11,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9576668739318848, Predicted Probability: 0.0187, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.11720609664917, Predicted Probability: 0.8926, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1262/4000 [12:04<24:54,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.744666576385498, Predicted Probability: 0.9769, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4314026832580566, Predicted Probability: 0.1929, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1263/4000 [12:05<27:28,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.1251743733882904, Predicted Probability: 0.4687, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8500821590423584, Predicted Probability: 0.0208, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1264/4000 [12:06<32:12,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.937419891357422, Predicted Probability: 0.0503, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.314932107925415, Predicted Probability: 0.0351, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1265/4000 [12:07<32:46,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3538997173309326, Predicted Probability: 0.0338, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.3188855648040771, Predicted Probability: 0.7890, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1266/4000 [12:07<28:13,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7203667163848877, Predicted Probability: 0.9382, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9239389896392822, Predicted Probability: 0.9806, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1267/4000 [12:08<29:51,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.16281795501709, Predicted Probability: 0.0153, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.273647427558899, Predicted Probability: 0.2186, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1268/4000 [12:09<31:06,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.642002820968628, Predicted Probability: 0.8378, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2058558464050293, Predicted Probability: 0.0389, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1269/4000 [12:09<26:44,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.6456815004348755, Predicted Probability: 0.8383, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.167475938796997, Predicted Probability: 0.7627, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1270/4000 [12:09<23:48,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5262649059295654, Predicted Probability: 0.9260, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.157984972000122, Predicted Probability: 0.9592, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1271/4000 [12:10<21:40,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9046990871429443, Predicted Probability: 0.9803, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7813570499420166, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1272/4000 [12:10<25:10,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.207071542739868, Predicted Probability: 0.9009, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9198063611984253, Predicted Probability: 0.2850, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1273/4000 [12:11<22:40,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.79374098777771, Predicted Probability: 0.9423, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1563045978546143, Predicted Probability: 0.9592, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1274/4000 [12:12<26:55,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5039610862731934, Predicted Probability: 0.0292, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -3.354804039001465, Predicted Probability: 0.0337, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1275/4000 [12:12<23:47,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.781770944595337, Predicted Probability: 0.9417, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.25765570998191833, Predicted Probability: 0.5641, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1276/4000 [12:12<21:35,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0301027297973633, Predicted Probability: 0.1161, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7505688667297363, Predicted Probability: 0.0230, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1277/4000 [12:13<24:42,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5230438709259033, Predicted Probability: 0.8210, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.08568083494901657, Predicted Probability: 0.5214, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1278/4000 [12:13<22:14,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1917431354522705, Predicted Probability: 0.0395, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2611477375030518, Predicted Probability: 0.9056, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1279/4000 [12:14<25:24,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4856584072113037, Predicted Probability: 0.8154, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0589847564697266, Predicted Probability: 0.0448, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1280/4000 [12:15<27:56,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1836023330688477, Predicted Probability: 0.8988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6426329612731934, Predicted Probability: 0.0255, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1281/4000 [12:15<25:36,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3339185118675232, Predicted Probability: 0.5827, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1197376251220703, Predicted Probability: 0.8928, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1282/4000 [12:16<27:55,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1481819152832031, Predicted Probability: 0.7592, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.030063629150391, Predicted Probability: 0.0175, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1283/4000 [12:17<30:07,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5408360958099365, Predicted Probability: 0.8236, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.072272300720215, Predicted Probability: 0.0168, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1284/4000 [12:17<26:23,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5484025478363037, Predicted Probability: 0.9720, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.860053300857544, Predicted Probability: 0.9794, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1285/4000 [12:18<28:46,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3604888916015625, Predicted Probability: 0.7958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6963582038879395, Predicted Probability: 0.0242, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1286/4000 [12:18<25:05,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7225215435028076, Predicted Probability: 0.0617, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.129566192626953, Predicted Probability: 0.1063, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1287/4000 [12:19<25:41,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7946794033050537, Predicted Probability: 0.9424, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6382296085357666, Predicted Probability: 0.8373, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1288/4000 [12:20<28:29,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.968378782272339, Predicted Probability: 0.0186, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.094630718231201, Predicted Probability: 0.8904, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1289/4000 [12:20<25:08,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.866382360458374, Predicted Probability: 0.9795, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.765275001525879, Predicted Probability: 0.9774, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1290/4000 [12:21<23:33,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5679110288619995, Predicted Probability: 0.3617, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6710174083709717, Predicted Probability: 0.9752, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1291/4000 [12:21<26:27,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.180200099945068, Predicted Probability: 0.0151, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5320343971252441, Predicted Probability: 0.8223, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1292/4000 [12:22<23:44,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.437574625015259, Predicted Probability: 0.9196, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9837193489074707, Predicted Probability: 0.9817, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1293/4000 [12:22<26:47,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9421873092651367, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0723474025726318, Predicted Probability: 0.7450, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1294/4000 [12:23<28:45,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4820301532745361, Predicted Probability: 0.8149, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1827268600463867, Predicted Probability: 0.1013, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1295/4000 [12:24<30:48,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.584862232208252, Predicted Probability: 0.0270, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9925601482391357, Predicted Probability: 0.0181, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1296/4000 [12:24<26:40,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9013698101043701, Predicted Probability: 0.8700, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.870274782180786, Predicted Probability: 0.9464, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1297/4000 [12:25<26:04,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3768367767333984, Predicted Probability: 0.0850, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5156819820404053, Predicted Probability: 0.9711, Prediction: 1.0

Epoch 1/3:  32%|███▏      | 1298/4000 [12:26<28:22,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5435919761657715, Predicted Probability: 0.0281, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.711261510848999, Predicted Probability: 0.1530, Prediction: 0.0

Epoch 1/3:  32%|███▏      | 1299/4000 [12:26<29:47,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5093324184417725, Predicted Probability: 0.9248, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3215974569320679, Predicted Probability: 0.2106, Prediction: 0.0

Epoch 1/3:  32%|███▎      | 1300/4000 [12:27<28:19,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.395284414291382, Predicted Probability: 0.9676, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2909841537475586, Predicted Probability: 0.0359, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1301/4000 [12:28<31:03,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.821554183959961, Predicted Probability: 0.0214, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.29849910736083984, Predicted Probability: 0.4259, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1302/4000 [12:28<25:24,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.211700439453125, Predicted Probability: 0.9854, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8926658630371094, Predicted Probability: 0.0200, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1303/4000 [12:28<22:53,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.758777618408203, Predicted Probability: 0.9404, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.976924180984497, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1304/4000 [12:29<21:07,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.68701434135437, Predicted Probability: 0.9363, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4687106609344482, Predicted Probability: 0.0302, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1305/4000 [12:29<21:50,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9961068630218506, Predicted Probability: 0.9524, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1914658546447754, Predicted Probability: 0.8995, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1306/4000 [12:30<25:11,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.730433702468872, Predicted Probability: 0.0612, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.686632752418518, Predicted Probability: 0.8438, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1307/4000 [12:31<27:31,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7592318058013916, Predicted Probability: 0.0228, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9971749782562256, Predicted Probability: 0.7305, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1308/4000 [12:32<29:02,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.852717876434326, Predicted Probability: 0.0208, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6728193759918213, Predicted Probability: 0.8420, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1309/4000 [12:32<31:35,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.122641086578369, Predicted Probability: 0.0159, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7980575561523438, Predicted Probability: 0.0219, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1310/4000 [12:33<31:53,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.000123023986816, Predicted Probability: 0.0180, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5156590938568115, Predicted Probability: 0.8199, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1311/4000 [12:33<26:02,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.052876949310303, Predicted Probability: 0.9829, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6693472862243652, Predicted Probability: 0.0249, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1312/4000 [12:34<28:39,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3188252449035645, Predicted Probability: 0.9104, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5727977752685547, Predicted Probability: 0.0273, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1313/4000 [12:35<30:42,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7705581188201904, Predicted Probability: 0.0225, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.364593029022217, Predicted Probability: 0.9141, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1314/4000 [12:35<26:31,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.658722162246704, Predicted Probability: 0.1599, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.146433353424072, Predicted Probability: 0.9844, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1315/4000 [12:36<21:19,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.6890405416488647, Predicted Probability: 0.8441, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5959858894348145, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1316/4000 [12:36<25:35,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7866554260253906, Predicted Probability: 0.0222, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.291989803314209, Predicted Probability: 0.0358, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1317/4000 [12:37<28:17,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5386137962341309, Predicted Probability: 0.1767, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4380109310150146, Predicted Probability: 0.9197, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1318/4000 [12:37<24:57,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5243418216705322, Predicted Probability: 0.9714, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6410534381866455, Predicted Probability: 0.9744, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1319/4000 [12:38<24:42,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.581281304359436, Predicted Probability: 0.8294, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1194441318511963, Predicted Probability: 0.8928, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1320/4000 [12:39<27:01,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9924440383911133, Predicted Probability: 0.0181, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5679608583450317, Predicted Probability: 0.8275, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1321/4000 [12:39<28:45,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4105842113494873, Predicted Probability: 0.9680, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7114224433898926, Predicted Probability: 0.1530, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1322/4000 [12:40<25:06,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4686145782470703, Predicted Probability: 0.0302, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0468909740448, Predicted Probability: 0.9546, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1323/4000 [12:41<27:44,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3380231857299805, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.2518939673900604, Predicted Probability: 0.5626, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1324/4000 [12:41<30:06,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.877523422241211, Predicted Probability: 0.0203, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.460160970687866, Predicted Probability: 0.0305, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1325/4000 [12:42<31:09,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.225114822387695, Predicted Probability: 0.0144, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0801925659179688, Predicted Probability: 0.8890, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1326/4000 [12:43<26:44,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.07797987759113312, Predicted Probability: 0.4805, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3143343925476074, Predicted Probability: 0.9101, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1327/4000 [12:43<29:11,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.053338050842285, Predicted Probability: 0.0171, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6851871013641357, Predicted Probability: 0.8436, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1328/4000 [12:44<30:07,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5913207530975342, Predicted Probability: 0.8308, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.279705047607422, Predicted Probability: 0.0137, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1329/4000 [12:45<30:31,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.031193971633911133, Predicted Probability: 0.5078, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2341325283050537, Predicted Probability: 0.9621, Prediction: 1.0

Epoch 1/3:  33%|███▎      | 1330/4000 [12:45<31:09,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4000940322875977, Predicted Probability: 0.0323, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.18706071376800537, Predicted Probability: 0.4534, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1331/4000 [12:46<27:48,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.495955228805542, Predicted Probability: 0.8170, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.985896587371826, Predicted Probability: 0.0182, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1332/4000 [12:47<29:23,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3198368549346924, Predicted Probability: 0.5793, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.129096031188965, Predicted Probability: 0.0158, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1333/4000 [12:47<31:16,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0978455543518066, Predicted Probability: 0.0432, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.19699764251709, Predicted Probability: 0.0148, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1334/4000 [12:48<26:42,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5340182781219482, Predicted Probability: 0.9716, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.942075252532959, Predicted Probability: 0.0190, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1335/4000 [12:49<28:12,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3541035056114197, Predicted Probability: 0.5876, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.0322065353393555, Predicted Probability: 0.0174, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1336/4000 [12:49<24:43,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7313365936279297, Predicted Probability: 0.0611, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9931130409240723, Predicted Probability: 0.0181, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1337/4000 [12:50<27:18,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2334823608398438, Predicted Probability: 0.2256, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5422511100769043, Predicted Probability: 0.1762, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1338/4000 [12:50<29:41,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.140471935272217, Predicted Probability: 0.0157, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.211862564086914, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 1/3:  33%|███▎      | 1339/4000 [12:51<30:55,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.938229560852051, Predicted Probability: 0.0191, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7773815393447876, Predicted Probability: 0.3149, Prediction: 0.0

Epoch 1/3:  34%|███▎      | 1340/4000 [12:52<31:19,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.073176383972168, Predicted Probability: 0.7452, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.209744930267334, Predicted Probability: 0.0388, Prediction: 0.0

Epoch 1/3:  34%|███▎      | 1341/4000 [12:53<32:24,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.182465076446533, Predicted Probability: 0.0150, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.629654884338379, Predicted Probability: 0.8361, Prediction: 1.0

Epoch 1/3:  34%|███▎      | 1342/4000 [12:53<26:21,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.07059043645858765, Predicted Probability: 0.4824, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.0195280313491821, Predicted Probability: 0.2651, Prediction: 0.0

Epoch 1/3:  34%|███▎      | 1343/4000 [12:54<28:15,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.153763294219971, Predicted Probability: 0.0155, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2940008640289307, Predicted Probability: 0.7848, Prediction: 1.0

Epoch 1/3:  34%|███▎      | 1344/4000 [12:54<23:21,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.673910617828369, Predicted Probability: 0.9355, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7748494148254395, Predicted Probability: 0.9413, Prediction: 1.0

Epoch 1/3:  34%|███▎      | 1345/4000 [12:54<21:20,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.559817314147949, Predicted Probability: 0.0277, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.60310697555542, Predicted Probability: 0.0265, Prediction: 0.0

Epoch 1/3:  34%|███▎      | 1346/4000 [12:55<25:21,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1781229972839355, Predicted Probability: 0.0151, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9180358052253723, Predicted Probability: 0.7146, Prediction: 1.0

Epoch 1/3:  34%|███▎      | 1347/4000 [12:56<22:50,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6905725002288818, Predicted Probability: 0.1557, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5061073303222656, Predicted Probability: 0.9709, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -3.1562886238098145, Predicted Probability: 0.0408, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7772009372711182, Predicted Probability: 0.8554, Prediction: 1.0

Epoch 1/3:  34%|███▎      | 1349/4000 [12:56<22:30,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9270823001861572, Predicted Probability: 0.8729, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.239907741546631, Predicted Probability: 0.0377, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1350/4000 [12:57<20:47,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.841142416000366, Predicted Probability: 0.9449, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.205052137374878, Predicted Probability: 0.9007, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1351/4000 [12:58<24:47,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.929548740386963, Predicted Probability: 0.0193, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.737400531768799, Predicted Probability: 0.0233, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1352/4000 [12:58<27:40,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2100971937179565, Predicted Probability: 0.2297, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.501786231994629, Predicted Probability: 0.0293, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1353/4000 [12:59<29:28,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.332794189453125, Predicted Probability: 0.0130, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.725304365158081, Predicted Probability: 0.8488, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1354/4000 [13:00<25:28,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1801083087921143, Predicted Probability: 0.1016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.07846556603908539, Predicted Probability: 0.5196, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1355/4000 [13:00<27:42,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.268173694610596, Predicted Probability: 0.0138, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6305441856384277, Predicted Probability: 0.6526, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1356/4000 [13:01<29:24,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.08847188949585, Predicted Probability: 0.0165, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.758967638015747, Predicted Probability: 0.8531, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1357/4000 [13:01<25:41,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1938493251800537, Predicted Probability: 0.9606, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.424391984939575, Predicted Probability: 0.9187, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1358/4000 [13:02<23:43,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.785320997238159, Predicted Probability: 0.9419, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9184393882751465, Predicted Probability: 0.9488, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 3.918672561645508, Predicted Probability: 0.9805, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.141444206237793, Predicted Probability: 0.9843, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1360/4000 [13:02<18:18,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.909409999847412, Predicted Probability: 0.9483, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8388168811798096, Predicted Probability: 0.9789, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1361/4000 [13:03<22:57,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.279285430908203, Predicted Probability: 0.0929, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.936967134475708, Predicted Probability: 0.8740, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1362/4000 [13:04<26:00,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.01619771122932434, Predicted Probability: 0.4960, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0578174591064453, Predicted Probability: 0.0449, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1363/4000 [13:05<25:38,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.330340623855591, Predicted Probability: 0.9655, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.594967842102051, Predicted Probability: 0.9305, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1364/4000 [13:05<28:24,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.355724334716797, Predicted Probability: 0.0127, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.381174087524414, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1365/4000 [13:06<24:47,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6005923748016357, Predicted Probability: 0.8321, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.0558977127075195, Predicted Probability: 0.9830, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1366/4000 [13:06<24:35,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.940408945083618, Predicted Probability: 0.0191, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0513999462127686, Predicted Probability: 0.8861, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1367/4000 [13:07<24:09,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.2506023645401, Predicted Probability: 0.7774, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5826627016067505, Predicted Probability: 0.6417, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1369/4000 [13:07<16:55,  2.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9714739322662354, Predicted Probability: 0.9815, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.998445510864258, Predicted Probability: 0.0180, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.2692790031433105, Predicted Probability: 0.9862, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3823041915893555, Predicted Probability: 0.9877, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1370/4000 [13:08<17:51,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0452799797058105, Predicted Probability: 0.8855, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9746408462524414, Predicted Probability: 0.9514, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1371/4000 [13:08<16:02,  2.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.607656717300415, Predicted Probability: 0.9736, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2700228691101074, Predicted Probability: 0.9634, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1372/4000 [13:09<20:43,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.597032070159912, Predicted Probability: 0.0267, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.08500438928604126, Predicted Probability: 0.4788, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1373/4000 [13:09<19:19,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1895887851715088, Predicted Probability: 0.7667, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.949597120285034, Predicted Probability: 0.9811, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1374/4000 [13:09<16:16,  2.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8221662044525146, Predicted Probability: 0.0561, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7512001991271973, Predicted Probability: 0.9400, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1375/4000 [13:10<21:18,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1333959102630615, Predicted Probability: 0.9582, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.738980770111084, Predicted Probability: 0.0232, Prediction: 0.0

Epoch 1/3:  34%|███▍      | 1376/4000 [13:10<19:51,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9009523391723633, Predicted Probability: 0.1300, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0835623741149902, Predicted Probability: 0.9562, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1377/4000 [13:11<24:45,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.815436363220215, Predicted Probability: 0.0216, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.67556095123291, Predicted Probability: 0.9356, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1378/4000 [13:12<22:11,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7083866596221924, Predicted Probability: 0.0625, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.264475107192993, Predicted Probability: 0.9632, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1379/4000 [13:12<18:16,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.404049873352051, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.054263114929199, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 1/3:  34%|███▍      | 1380/4000 [13:13<23:26,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.396271228790283, Predicted Probability: 0.0324, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9205968379974365, Predicted Probability: 0.0511, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1381/4000 [13:13<22:21,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5405170917510986, Predicted Probability: 0.0282, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3126165568828583, Predicted Probability: 0.4225, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1382/4000 [13:14<25:07,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.965205192565918, Predicted Probability: 0.8771, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.318180084228516, Predicted Probability: 0.0131, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1383/4000 [13:14<20:14,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8706917762756348, Predicted Probability: 0.7049, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9396748542785645, Predicted Probability: 0.9809, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1384/4000 [13:15<23:55,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3217132091522217, Predicted Probability: 0.9107, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.299225807189941, Predicted Probability: 0.0134, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1385/4000 [13:16<26:27,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1346969604492188, Predicted Probability: 0.8942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.1691412925720215, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1386/4000 [13:16<27:46,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.319171905517578, Predicted Probability: 0.0131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4587417840957642, Predicted Probability: 0.8113, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1387/4000 [13:16<22:05,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.258749485015869, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.679980993270874, Predicted Probability: 0.9754, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1388/4000 [13:17<20:15,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9911012649536133, Predicted Probability: 0.9522, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7819011211395264, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1389/4000 [13:17<18:56,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7949007749557495, Predicted Probability: 0.8575, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7266106605529785, Predicted Probability: 0.9765, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1390/4000 [13:18<23:22,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.08489066362380981, Predicted Probability: 0.4788, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.551081657409668, Predicted Probability: 0.0104, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1391/4000 [13:19<27:19,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7991456985473633, Predicted Probability: 0.0219, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7786662578582764, Predicted Probability: 0.8555, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1392/4000 [13:19<26:08,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4664084911346436, Predicted Probability: 0.9697, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7312052249908447, Predicted Probability: 0.9766, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1393/4000 [13:20<23:13,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7115460634231567, Predicted Probability: 0.6707, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.421328544616699, Predicted Probability: 0.0316, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1394/4000 [13:20<20:56,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5165945887565613, Predicted Probability: 0.3736, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.10976909101009369, Predicted Probability: 0.5274, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1395/4000 [13:20<19:25,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7073384523391724, Predicted Probability: 0.1535, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3340723514556885, Predicted Probability: 0.2085, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1396/4000 [13:21<19:17,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5387392044067383, Predicted Probability: 0.9718, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6155900955200195, Predicted Probability: 0.3508, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1397/4000 [13:22<23:01,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6635158061981201, Predicted Probability: 0.8407, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.63273024559021, Predicted Probability: 0.9742, Prediction: 1.0

Epoch 1/3:  35%|███▍      | 1398/4000 [13:22<25:57,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.118960380554199, Predicted Probability: 0.0160, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5445010662078857, Predicted Probability: 0.1759, Prediction: 0.0

Epoch 1/3:  35%|███▍      | 1399/4000 [13:23<20:52,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8170390129089355, Predicted Probability: 0.9785, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.159818649291992, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1400/4000 [13:23<19:35,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.992748737335205, Predicted Probability: 0.9522, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6197962760925293, Predicted Probability: 0.6502, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1401/4000 [13:23<18:38,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7546515464782715, Predicted Probability: 0.0229, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.049307823181152, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1402/4000 [13:24<20:56,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7804415225982666, Predicted Probability: 0.0223, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3351356983184814, Predicted Probability: 0.9117, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1403/4000 [13:24<20:31,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.928554058074951, Predicted Probability: 0.9492, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1036787033081055, Predicted Probability: 0.9570, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1404/4000 [13:25<21:35,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7779335975646973, Predicted Probability: 0.9415, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.536407709121704, Predicted Probability: 0.9717, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1405/4000 [13:26<24:33,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5512632131576538, Predicted Probability: 0.3656, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2526071071624756, Predicted Probability: 0.0372, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1406/4000 [13:26<25:31,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.192009925842285, Predicted Probability: 0.0149, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.305478096008301, Predicted Probability: 0.0133, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1407/4000 [13:27<22:47,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9391170740127563, Predicted Probability: 0.1257, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.663109540939331, Predicted Probability: 0.9750, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1408/4000 [13:27<18:35,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.192204475402832, Predicted Probability: 0.9851, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.0693206787109375, Predicted Probability: 0.9832, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1409/4000 [13:28<23:13,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6697274446487427, Predicted Probability: 0.1585, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.14476203918457, Predicted Probability: 0.0156, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1410/4000 [13:28<21:06,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0310144424438477, Predicted Probability: 0.9540, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5841765403747559, Predicted Probability: 0.3580, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1411/4000 [13:29<24:20,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2272017002105713, Predicted Probability: 0.0382, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6743032932281494, Predicted Probability: 0.1579, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1412/4000 [13:30<26:23,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7279881238937378, Predicted Probability: 0.8492, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.073635578155518, Predicted Probability: 0.0167, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1413/4000 [13:30<23:16,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7325925827026367, Predicted Probability: 0.0234, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.113105297088623, Predicted Probability: 0.9574, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1414/4000 [13:31<26:09,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.546558141708374, Predicted Probability: 0.8244, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.492572784423828, Predicted Probability: 0.0111, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1415/4000 [13:31<21:00,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6296463012695312, Predicted Probability: 0.9742, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.171900272369385, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1416/4000 [13:31<21:55,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1177008152008057, Predicted Probability: 0.8926, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.204779624938965, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1417/4000 [13:32<24:59,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3906707763671875, Predicted Probability: 0.0122, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.37457275390625, Predicted Probability: 0.4074, Prediction: 0.0

Epoch 1/3:  35%|███▌      | 1418/4000 [13:33<30:14,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.769827127456665, Predicted Probability: 0.0225, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.29604998230934143, Predicted Probability: 0.5735, Prediction: 1.0

Epoch 1/3:  35%|███▌      | 1419/4000 [13:33<23:49,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.712407350540161, Predicted Probability: 0.9762, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7784790992736816, Predicted Probability: 0.9415, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1420/4000 [13:34<26:03,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.421566009521484, Predicted Probability: 0.0119, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4261664152145386, Predicted Probability: 0.8063, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1421/4000 [13:34<23:05,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.754102110862732, Predicted Probability: 0.1475, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3376728296279907, Predicted Probability: 0.7921, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1422/4000 [13:35<23:07,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5347959995269775, Predicted Probability: 0.9717, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4595993757247925, Predicted Probability: 0.3871, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1423/4000 [13:36<27:40,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.385432243347168, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.262905120849609, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1424/4000 [13:37<30:13,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.428673267364502, Predicted Probability: 0.0314, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.1705474853515625, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1425/4000 [13:38<31:02,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.30026388168335, Predicted Probability: 0.0134, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5553282499313354, Predicted Probability: 0.3646, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1426/4000 [13:38<32:02,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.223926544189453, Predicted Probability: 0.0144, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1927571296691895, Predicted Probability: 0.8996, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1427/4000 [13:39<31:49,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.175184488296509, Predicted Probability: 0.9599, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.149548053741455, Predicted Probability: 0.0411, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1428/4000 [13:40<32:16,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5092520713806152, Predicted Probability: 0.9248, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.461894989013672, Predicted Probability: 0.0114, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1429/4000 [13:40<25:10,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.323589324951172, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8762412071228027, Predicted Probability: 0.9797, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1430/4000 [13:40<23:16,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4251346588134766, Predicted Probability: 0.9187, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6880669593811035, Predicted Probability: 0.0244, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1432/4000 [13:41<17:08,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7345259189605713, Predicted Probability: 0.9767, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.104803085327148, Predicted Probability: 0.9838, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 3.8096349239349365, Predicted Probability: 0.9783, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.186384201049805, Predicted Probability: 0.9850, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1433/4000 [13:42<21:38,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.417498588562012, Predicted Probability: 0.0119, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8050239086151123, Predicted Probability: 0.8588, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1434/4000 [13:43<25:52,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2188754081726074, Predicted Probability: 0.0385, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6084954738616943, Predicted Probability: 0.1668, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1435/4000 [13:43<27:34,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3148720264434814, Predicted Probability: 0.0351, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3553253412246704, Predicted Probability: 0.7950, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1436/4000 [13:44<29:21,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5254015326499939, Predicted Probability: 0.3716, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8886160850524902, Predicted Probability: 0.0201, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1437/4000 [13:45<30:36,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.681010127067566, Predicted Probability: 0.8430, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.20806884765625, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1438/4000 [13:46<29:07,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0533435344696045, Predicted Probability: 0.8863, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.203375339508057, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1439/4000 [13:46<30:09,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.02286696434021, Predicted Probability: 0.9536, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.131568908691406, Predicted Probability: 0.0158, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1440/4000 [13:47<30:37,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8837900161743164, Predicted Probability: 0.8680, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.752579689025879, Predicted Probability: 0.0229, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1441/4000 [13:48<31:18,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.298153400421143, Predicted Probability: 0.0134, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.980476140975952, Predicted Probability: 0.9517, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1442/4000 [13:48<27:38,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.082207679748535, Predicted Probability: 0.9834, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.482342004776001, Predicted Probability: 0.9229, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1443/4000 [13:49<24:55,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.898944616317749, Predicted Probability: 0.0199, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9877576231956482, Predicted Probability: 0.7286, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1444/4000 [13:49<27:35,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3236260414123535, Predicted Probability: 0.9108, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.82124400138855, Predicted Probability: 0.0214, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1445/4000 [13:50<29:39,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.79300594329834, Predicted Probability: 0.0577, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3748745918273926, Predicted Probability: 0.9149, Prediction: 1.0

Epoch 1/3:  36%|███▌      | 1446/4000 [13:51<30:49,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7806817889213562, Predicted Probability: 0.6858, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.592729568481445, Predicted Probability: 0.0100, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1447/4000 [13:52<28:37,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7699881792068481, Predicted Probability: 0.1455, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.096384048461914, Predicted Probability: 0.0164, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1448/4000 [13:52<22:45,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.388746976852417, Predicted Probability: 0.9674, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.141092777252197, Predicted Probability: 0.0157, Prediction: 0.0

Epoch 1/3:  36%|███▌      | 1449/4000 [13:52<22:46,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.650413990020752, Predicted Probability: 0.9340, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6807138919830322, Predicted Probability: 0.9359, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1450/4000 [13:53<20:35,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.024125099182129, Predicted Probability: 0.9824, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.66328501701355, Predicted Probability: 0.9750, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1451/4000 [13:53<17:07,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.473768711090088, Predicted Probability: 0.9887, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.410781383514404, Predicted Probability: 0.9880, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1452/4000 [13:54<21:01,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.548863887786865, Predicted Probability: 0.0105, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.837916374206543, Predicted Probability: 0.8627, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1453/4000 [13:54<19:29,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.25307035446167, Predicted Probability: 0.0140, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.211986064910889, Predicted Probability: 0.9854, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1454/4000 [13:55<23:41,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3701426982879639, Predicted Probability: 0.2026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.586747169494629, Predicted Probability: 0.0269, Prediction: 0.0

Epoch 1/3:  36%|███▋      | 1455/4000 [13:55<21:21,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.936093330383301, Predicted Probability: 0.9496, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2354743480682373, Predicted Probability: 0.9621, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1456/4000 [13:56<24:25,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.145440697669983, Predicted Probability: 0.7587, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.714452266693115, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  36%|███▋      | 1457/4000 [13:57<28:01,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.442625522613525, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.449086666107178, Predicted Probability: 0.0116, Prediction: 0.0

Epoch 1/3:  36%|███▋      | 1459/4000 [13:57<19:32,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.34442779421806335, Predicted Probability: 0.5853, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.618211269378662, Predicted Probability: 0.9739, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 4.554968357086182, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.368697643280029, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 1/3:  36%|███▋      | 1460/4000 [13:58<18:14,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6720643043518066, Predicted Probability: 0.9752, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.046990394592285, Predicted Probability: 0.9828, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1461/4000 [13:58<22:23,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.462250232696533, Predicted Probability: 0.0114, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0577611923217773, Predicted Probability: 0.8867, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1462/4000 [13:59<20:19,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.5207512378692627, Predicted Probability: 0.0744, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9736273288726807, Predicted Probability: 0.9514, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1463/4000 [13:59<17:31,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.744879722595215, Predicted Probability: 0.0231, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7293753623962402, Predicted Probability: 0.9766, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1465/4000 [14:00<16:05,  2.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.025115966796875, Predicted Probability: 0.0175, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.20959734916687, Predicted Probability: 0.9612, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -3.8195841312408447, Predicted Probability: 0.0215, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.163859844207764, Predicted Probability: 0.9847, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1466/4000 [14:01<21:01,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0173206329345703, Predicted Probability: 0.0466, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.264460325241089, Predicted Probability: 0.0941, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1467/4000 [14:01<20:19,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7706363201141357, Predicted Probability: 0.9411, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.320133686065674, Predicted Probability: 0.9869, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1468/4000 [14:01<18:48,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.587167501449585, Predicted Probability: 0.0269, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5212032794952393, Predicted Probability: 0.9713, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1469/4000 [14:02<23:28,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.415003776550293, Predicted Probability: 0.0119, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.315800666809082, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1470/4000 [14:03<23:31,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9413090944290161, Predicted Probability: 0.8745, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2862846851348877, Predicted Probability: 0.0360, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1471/4000 [14:04<25:55,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.072197914123535, Predicted Probability: 0.0168, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0623364448547363, Predicted Probability: 0.8872, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1472/4000 [14:04<20:50,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.427710056304932, Predicted Probability: 0.0118, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.315251588821411, Predicted Probability: 0.0351, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1473/4000 [14:05<24:09,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.366244077682495, Predicted Probability: 0.9142, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.305135250091553, Predicted Probability: 0.0133, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1474/4000 [14:05<26:12,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.33732795715332, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6296303272247314, Predicted Probability: 0.9327, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1475/4000 [14:06<27:58,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7182934284210205, Predicted Probability: 0.9381, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.457583904266357, Predicted Probability: 0.0115, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1476/4000 [14:07<29:30,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.308099746704102, Predicted Probability: 0.0133, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.382086277008057, Predicted Probability: 0.0123, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1477/4000 [14:08<31:23,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7685976028442383, Predicted Probability: 0.1457, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.566425323486328, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1478/4000 [14:08<24:35,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.35904598236084, Predicted Probability: 0.9874, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7967965602874756, Predicted Probability: 0.1422, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1479/4000 [14:09<26:41,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0732078552246094, Predicted Probability: 0.9558, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.634265899658203, Predicted Probability: 0.9330, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1480/4000 [14:09<25:36,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.238199472427368, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4522786140441895, Predicted Probability: 0.9693, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1481/4000 [14:10<27:11,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6189745664596558, Predicted Probability: 0.3500, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7287354469299316, Predicted Probability: 0.0235, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1482/4000 [14:10<23:40,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8490979671478271, Predicted Probability: 0.8640, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.000523090362549, Predicted Probability: 0.9820, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1483/4000 [14:11<25:49,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6448187828063965, Predicted Probability: 0.3442, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.084580421447754, Predicted Probability: 0.0166, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1484/4000 [14:12<24:59,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4239912033081055, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5902822017669678, Predicted Probability: 0.9732, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1485/4000 [14:12<26:50,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0680603981018066, Predicted Probability: 0.8878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.373353958129883, Predicted Probability: 0.0125, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1486/4000 [14:13<23:44,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.422215938568115, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9680700302124023, Predicted Probability: 0.0186, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1487/4000 [14:13<25:53,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8383431434631348, Predicted Probability: 0.8628, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.107553005218506, Predicted Probability: 0.0428, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1488/4000 [14:14<20:40,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.582024097442627, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.067403793334961, Predicted Probability: 0.9832, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1489/4000 [14:14<23:34,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9862074851989746, Predicted Probability: 0.0182, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.526085615158081, Predicted Probability: 0.8214, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1490/4000 [14:15<26:23,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.247734069824219, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0988268852233887, Predicted Probability: 0.8908, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1491/4000 [14:16<23:24,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.969609022140503, Predicted Probability: 0.0488, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6405792236328125, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1492/4000 [14:16<25:38,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.342156887054443, Predicted Probability: 0.0128, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1480159759521484, Predicted Probability: 0.8955, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1493/4000 [14:17<24:39,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.11049704253673553, Predicted Probability: 0.4724, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6674593091011047, Predicted Probability: 0.6609, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1494/4000 [14:17<22:45,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8893797397613525, Predicted Probability: 0.9800, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6262163519859314, Predicted Probability: 0.3484, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1495/4000 [14:18<18:36,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.238333225250244, Predicted Probability: 0.9858, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.797986030578613, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1496/4000 [14:18<18:31,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.174525260925293, Predicted Probability: 0.2360, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4534934163093567, Predicted Probability: 0.3885, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1497/4000 [14:18<17:40,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.357349872589111, Predicted Probability: 0.0127, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.24978494644165, Predicted Probability: 0.9859, Prediction: 1.0

Epoch 1/3:  37%|███▋      | 1498/4000 [14:19<16:51,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4248194694519043, Predicted Probability: 0.9685, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.9027156829833984, Predicted Probability: 0.1298, Prediction: 0.0

Epoch 1/3:  37%|███▋      | 1499/4000 [14:19<16:23,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8454408645629883, Predicted Probability: 0.9791, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.496323823928833, Predicted Probability: 0.9706, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1500/4000 [14:20<20:23,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0321295261383057, Predicted Probability: 0.8841, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6111223101615906, Predicted Probability: 0.3518, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1501/4000 [14:20<18:53,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.393953412771225, Predicted Probability: 0.4028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.03570556640625, Predicted Probability: 0.9826, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1502/4000 [14:20<16:35,  2.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.735222816467285, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.857693672180176, Predicted Probability: 0.9793, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1503/4000 [14:21<16:07,  2.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6513185501098633, Predicted Probability: 0.9341, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.068864583969116, Predicted Probability: 0.9556, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1504/4000 [14:21<16:54,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.136926651000977, Predicted Probability: 0.9843, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6163249611854553, Predicted Probability: 0.3506, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1505/4000 [14:22<18:55,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.003129482269287, Predicted Probability: 0.0179, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.8614979982376099, Predicted Probability: 0.8655, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1506/4000 [14:22<15:45,  2.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8676772117614746, Predicted Probability: 0.0205, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.710503101348877, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1507/4000 [14:22<15:36,  2.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8657928109169006, Predicted Probability: 0.7039, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0197277069091797, Predicted Probability: 0.9535, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1508/4000 [14:23<19:41,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.956671953201294, Predicted Probability: 0.8762, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7601176500320435, Predicted Probability: 0.1468, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1509/4000 [14:24<23:40,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.532251358032227, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.007730484008789, Predicted Probability: 0.0179, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1511/4000 [14:24<15:50,  2.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.3039182424545288, Predicted Probability: 0.7865, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.194664478302002, Predicted Probability: 0.9606, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 4.1603264808654785, Predicted Probability: 0.9846, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8906100988388062, Predicted Probability: 0.1312, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1512/4000 [14:25<20:17,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8998082876205444, Predicted Probability: 0.8699, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.022375106811523, Predicted Probability: 0.0176, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1513/4000 [14:25<19:01,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8195464611053467, Predicted Probability: 0.9437, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.4757323265075684, Predicted Probability: 0.0776, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1514/4000 [14:26<15:54,  2.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.629268169403076, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.432925224304199, Predicted Probability: 0.9193, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1515/4000 [14:26<21:17,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.506906509399414, Predicted Probability: 0.0291, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.193950653076172, Predicted Probability: 0.0149, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1516/4000 [14:27<19:34,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.105412721633911, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.217965126037598, Predicted Probability: 0.9855, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1517/4000 [14:27<18:27,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.43519991636276245, Predicted Probability: 0.6071, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.102963924407959, Predicted Probability: 0.9837, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1518/4000 [14:28<21:47,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7317874431610107, Predicted Probability: 0.8496, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.759840965270996, Predicted Probability: 0.0228, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1519/4000 [14:28<17:51,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.535481929779053, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.338985919952393, Predicted Probability: 0.0129, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1520/4000 [14:29<17:54,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9891587495803833, Predicted Probability: 0.8797, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3935039043426514, Predicted Probability: 0.9163, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1521/4000 [14:29<17:08,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.408853769302368, Predicted Probability: 0.0320, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7311919927597046, Predicted Probability: 0.1504, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1522/4000 [14:30<20:57,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.2627301812171936, Predicted Probability: 0.4347, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8756017684936523, Predicted Probability: 0.0203, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1523/4000 [14:30<24:24,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.454678058624268, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.998185396194458, Predicted Probability: 0.0475, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1524/4000 [14:31<23:58,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3984241485595703, Predicted Probability: 0.0833, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5001842975616455, Predicted Probability: 0.9707, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1525/4000 [14:32<23:21,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7587066292762756, Predicted Probability: 0.3189, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.0005669593811035, Predicted Probability: 0.0180, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1526/4000 [14:32<23:00,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.15942645072937, Predicted Probability: 0.8965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.20091435313224792, Predicted Probability: 0.4499, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1527/4000 [14:33<25:39,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5846501588821411, Predicted Probability: 0.8299, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.207160472869873, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1528/4000 [14:34<27:58,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.440951347351074, Predicted Probability: 0.0310, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.899200677871704, Predicted Probability: 0.0522, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1529/4000 [14:34<29:36,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.252429962158203, Predicted Probability: 0.0140, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9689206480979919, Predicted Probability: 0.7249, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1530/4000 [14:35<30:53,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3680033683776855, Predicted Probability: 0.0125, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8005361557006836, Predicted Probability: 0.0573, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1531/4000 [14:36<26:19,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6134698390960693, Predicted Probability: 0.9737, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8069732189178467, Predicted Probability: 0.9783, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1532/4000 [14:36<25:11,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4051456451416016, Predicted Probability: 0.0828, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3134310245513916, Predicted Probability: 0.4223, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1533/4000 [14:37<26:28,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.19099709391593933, Predicted Probability: 0.5476, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9787039756774902, Predicted Probability: 0.0184, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1534/4000 [14:38<26:23,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.9863674640655518, Predicted Probability: 0.2716, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1832921504974365, Predicted Probability: 0.1013, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1535/4000 [14:38<23:16,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6352155208587646, Predicted Probability: 0.9743, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.149472713470459, Predicted Probability: 0.9845, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1536/4000 [14:38<22:56,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.34050989151001, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2719192504882812, Predicted Probability: 0.0935, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1537/4000 [14:39<25:45,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8375815153121948, Predicted Probability: 0.8627, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.574027061462402, Predicted Probability: 0.0102, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1538/4000 [14:40<28:12,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5960109233856201, Predicted Probability: 0.3553, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2575273513793945, Predicted Probability: 0.0140, Prediction: 0.0

Epoch 1/3:  38%|███▊      | 1539/4000 [14:40<22:19,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.616868019104004, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6647621989250183, Predicted Probability: 0.6603, Prediction: 1.0

Epoch 1/3:  38%|███▊      | 1540/4000 [14:41<26:37,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.081035614013672, Predicted Probability: 0.0166, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.516579627990723, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 1/3:  39%|███▊      | 1541/4000 [14:42<23:15,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3100874423980713, Predicted Probability: 0.0352, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.22074510157108307, Predicted Probability: 0.5550, Prediction: 1.0

Epoch 1/3:  39%|███▊      | 1542/4000 [14:42<20:55,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8502707481384277, Predicted Probability: 0.9453, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9246909618377686, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 1/3:  39%|███▊      | 1543/4000 [14:43<24:05,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7643842697143555, Predicted Probability: 0.0227, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5170880556106567, Predicted Probability: 0.1799, Prediction: 0.0

Epoch 1/3:  39%|███▊      | 1544/4000 [14:43<26:03,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.34124755859375, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.458362102508545, Predicted Probability: 0.9212, Prediction: 1.0

Epoch 1/3:  39%|███▊      | 1545/4000 [14:44<26:53,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4751696586608887, Predicted Probability: 0.0300, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.212042808532715, Predicted Probability: 0.9013, Prediction: 1.0

Epoch 1/3:  39%|███▊      | 1546/4000 [14:45<23:14,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7106335163116455, Predicted Probability: 0.0239, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4177761375904083, Predicted Probability: 0.3970, Prediction: 0.0

Epoch 1/3:  39%|███▊      | 1547/4000 [14:45<18:45,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.218306541442871, Predicted Probability: 0.0145, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.317061901092529, Predicted Probability: 0.9868, Prediction: 1.0

Epoch 1/3:  39%|███▊      | 1548/4000 [14:45<15:38,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.825657367706299, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.157196998596191, Predicted Probability: 0.0154, Prediction: 0.0

Epoch 1/3:  39%|███▊      | 1549/4000 [14:46<20:31,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.849569797515869, Predicted Probability: 0.0547, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.195195198059082, Predicted Probability: 0.0148, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1550/4000 [14:46<19:03,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8898744583129883, Predicted Probability: 0.9800, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.743494749069214, Predicted Probability: 0.9769, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1551/4000 [14:46<15:53,  2.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.354717969894409, Predicted Probability: 0.0867, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.514669895172119, Predicted Probability: 0.9892, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1552/4000 [14:47<15:43,  2.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.776734352111816, Predicted Probability: 0.9916, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.327836513519287, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1553/4000 [14:47<20:04,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.129428863525391, Predicted Probability: 0.0158, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1465647220611572, Predicted Probability: 0.7589, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1554/4000 [14:48<23:15,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1448535919189453, Predicted Probability: 0.0413, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.714648723602295, Predicted Probability: 0.8474, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1555/4000 [14:49<23:12,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3815200328826904, Predicted Probability: 0.9671, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.507372856140137, Predicted Probability: 0.0109, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1556/4000 [14:49<24:55,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3115326762199402, Predicted Probability: 0.5773, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.577310085296631, Predicted Probability: 0.0272, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1557/4000 [14:50<19:55,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.103283643722534, Predicted Probability: 0.8912, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1472387313842773, Predicted Probability: 0.9588, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1558/4000 [14:50<19:17,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0783262252807617, Predicted Probability: 0.8888, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.390321731567383, Predicted Probability: 0.9674, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1559/4000 [14:51<23:07,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7619116306304932, Predicted Probability: 0.8534, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.058902263641357, Predicted Probability: 0.0170, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1560/4000 [14:51<22:52,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2139129638671875, Predicted Probability: 0.0146, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2904365062713623, Predicted Probability: 0.0359, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1561/4000 [14:52<25:36,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.571846008300781, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.227527141571045, Predicted Probability: 0.0381, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1562/4000 [14:53<26:46,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.57828426361084, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.15131080150604248, Predicted Probability: 0.4622, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1563/4000 [14:53<23:31,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1117939949035645, Predicted Probability: 0.0161, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.173053741455078, Predicted Probability: 0.9848, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1564/4000 [14:54<23:46,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1684672832489014, Predicted Probability: 0.8974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.41525936126709, Predicted Probability: 0.0119, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1565/4000 [14:55<24:06,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8966388702392578, Predicted Probability: 0.8695, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.489048719406128, Predicted Probability: 0.1841, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1566/4000 [14:55<21:28,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2299275398254395, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.079014778137207, Predicted Probability: 0.9560, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1567/4000 [14:55<17:35,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1630849838256836, Predicted Probability: 0.9594, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.185612678527832, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1568/4000 [14:56<21:39,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.962693452835083, Predicted Probability: 0.0187, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.500765085220337, Predicted Probability: 0.8177, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1569/4000 [14:57<24:10,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0783092975616455, Predicted Probability: 0.1112, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4078792929649353, Predicted Probability: 0.3994, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1570/4000 [14:57<26:16,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6830439567565918, Predicted Probability: 0.8433, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.358970642089844, Predicted Probability: 0.0126, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1571/4000 [14:58<27:07,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5381556749343872, Predicted Probability: 0.1768, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9471701383590698, Predicted Probability: 0.8751, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1572/4000 [14:59<25:46,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6769235134124756, Predicted Probability: 0.8425, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.173936367034912, Predicted Probability: 0.9598, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1573/4000 [14:59<22:34,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.702561616897583, Predicted Probability: 0.1541, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.19089412689209, Predicted Probability: 0.8994, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1574/4000 [15:00<25:02,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.781819462776184, Predicted Probability: 0.8559, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.318464279174805, Predicted Probability: 0.0131, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1575/4000 [15:01<27:45,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.554415702819824, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.147324562072754, Predicted Probability: 0.0156, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1576/4000 [15:01<26:01,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0391587018966675, Predicted Probability: 0.7387, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.587737560272217, Predicted Probability: 0.9301, Prediction: 1.0

Epoch 1/3:  39%|███▉      | 1577/4000 [15:02<27:10,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7813459634780884, Predicted Probability: 0.8559, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.9084596633911133, Predicted Probability: 0.0197, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1578/4000 [15:03<29:12,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2402751445770264, Predicted Probability: 0.2244, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.215014457702637, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 1/3:  39%|███▉      | 1579/4000 [15:04<29:27,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5832433700561523, Predicted Probability: 0.0270, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.205164909362793, Predicted Probability: 0.9007, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1580/4000 [15:04<26:09,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.270623683929443, Predicted Probability: 0.9862, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.000982284545898, Predicted Probability: 0.9820, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1581/4000 [15:05<27:01,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.80288028717041, Predicted Probability: 0.0218, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5186468362808228, Predicted Probability: 0.8203, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1582/4000 [15:05<21:23,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6891858577728271, Predicted Probability: 0.3342, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.882098913192749, Predicted Probability: 0.0202, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1583/4000 [15:06<24:01,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6431314945220947, Predicted Probability: 0.0664, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.23295259475708, Predicted Probability: 0.0968, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1584/4000 [15:06<26:10,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0275280475616455, Predicted Probability: 0.7364, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.196782112121582, Predicted Probability: 0.0148, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1585/4000 [15:07<22:51,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.794013500213623, Predicted Probability: 0.1426, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7333450317382812, Predicted Probability: 0.0234, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1586/4000 [15:08<24:59,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3330758810043335, Predicted Probability: 0.4175, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6280517578125, Predicted Probability: 0.0097, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1587/4000 [15:08<27:20,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.90891170501709, Predicted Probability: 0.0517, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.773477077484131, Predicted Probability: 0.0225, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1588/4000 [15:09<27:59,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8883867263793945, Predicted Probability: 0.0201, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.481260061264038, Predicted Probability: 0.9228, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1589/4000 [15:10<26:15,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9156875610351562, Predicted Probability: 0.9805, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5589027404785156, Predicted Probability: 0.0718, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1590/4000 [15:10<26:58,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7369861602783203, Predicted Probability: 0.9392, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8510069847106934, Predicted Probability: 0.8642, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1591/4000 [15:11<23:24,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.442641258239746, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9370397329330444, Predicted Probability: 0.1260, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1592/4000 [15:11<19:34,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.777937889099121, Predicted Probability: 0.9917, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5175139904022217, Predicted Probability: 0.8202, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1593/4000 [15:12<22:18,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.07428473979234695, Predicted Probability: 0.5186, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.538973808288574, Predicted Probability: 0.0106, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1594/4000 [15:12<20:18,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.327282428741455, Predicted Probability: 0.0130, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.291440963745117, Predicted Probability: 0.9082, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1595/4000 [15:12<16:40,  2.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.320993423461914, Predicted Probability: 0.0131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.361810684204102, Predicted Probability: 0.9874, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1596/4000 [15:13<21:31,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.531627655029297, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.117825984954834, Predicted Probability: 0.0160, Prediction: 0.0

Epoch 1/3:  40%|███▉      | 1597/4000 [15:14<24:30,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.032081604003906, Predicted Probability: 0.0174, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3475120067596436, Predicted Probability: 0.9127, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1598/4000 [15:15<26:35,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3683199882507324, Predicted Probability: 0.0333, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9255222082138062, Predicted Probability: 0.8728, Prediction: 1.0

Epoch 1/3:  40%|███▉      | 1599/4000 [15:15<21:07,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.625726222991943, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.0068769454956055, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 1/3:  40%|████      | 1600/4000 [15:15<20:04,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.400672435760498, Predicted Probability: 0.0121, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.042755603790283, Predicted Probability: 0.0172, Prediction: 0.0

Epoch 1/3:  40%|████      | 1601/4000 [15:16<20:38,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8116753101348877, Predicted Probability: 0.9433, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4284074306488037, Predicted Probability: 0.9686, Prediction: 1.0

Epoch 1/3:  40%|████      | 1602/4000 [15:17<23:18,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7050080299377441, Predicted Probability: 0.1538, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8721940517425537, Predicted Probability: 0.0535, Prediction: 0.0

Epoch 1/3:  40%|████      | 1603/4000 [15:17<20:45,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.437525272369385, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8343302011489868, Predicted Probability: 0.8623, Prediction: 1.0

Epoch 1/3:  40%|████      | 1604/4000 [15:17<18:52,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4666786193847656, Predicted Probability: 0.0303, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.462543249130249, Predicted Probability: 0.0785, Prediction: 0.0

Epoch 1/3:  40%|████      | 1605/4000 [15:18<23:19,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.728062629699707, Predicted Probability: 0.0235, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9559028148651123, Predicted Probability: 0.1239, Prediction: 0.0

Epoch 1/3:  40%|████      | 1606/4000 [15:19<20:38,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.447032928466797, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.872342586517334, Predicted Probability: 0.9465, Prediction: 1.0

Epoch 1/3:  40%|████      | 1607/4000 [15:19<23:17,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.520193338394165, Predicted Probability: 0.1794, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.531210899353027, Predicted Probability: 0.0107, Prediction: 0.0

Epoch 1/3:  40%|████      | 1608/4000 [15:20<20:45,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4117023944854736, Predicted Probability: 0.9681, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.541985511779785, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 1/3:  40%|████      | 1609/4000 [15:20<21:07,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9324357509613037, Predicted Probability: 0.0506, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1617655754089355, Predicted Probability: 0.7617, Prediction: 1.0

Epoch 1/3:  40%|████      | 1610/4000 [15:21<19:11,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.061046600341797, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9516372680664062, Predicted Probability: 0.9811, Prediction: 1.0

Epoch 1/3:  40%|████      | 1611/4000 [15:21<22:37,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2577072381973267, Predicted Probability: 0.2214, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5350236892700195, Predicted Probability: 0.0106, Prediction: 0.0

Epoch 1/3:  40%|████      | 1612/4000 [15:22<20:19,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4095427989959717, Predicted Probability: 0.9680, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2302653789520264, Predicted Probability: 0.2261, Prediction: 0.0

Epoch 1/3:  40%|████      | 1613/4000 [15:23<22:53,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.619737386703491, Predicted Probability: 0.0261, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5451780557632446, Predicted Probability: 0.3670, Prediction: 0.0

Epoch 1/3:  40%|████      | 1614/4000 [15:23<22:22,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2226300239562988, Predicted Probability: 0.2275, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3473875522613525, Predicted Probability: 0.9127, Prediction: 1.0

Epoch 1/3:  40%|████      | 1615/4000 [15:24<25:42,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8273489475250244, Predicted Probability: 0.0213, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.642322063446045, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 1/3:  40%|████      | 1616/4000 [15:24<22:27,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.973977565765381, Predicted Probability: 0.9815, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.426494598388672, Predicted Probability: 0.9685, Prediction: 1.0

Epoch 1/3:  40%|████      | 1617/4000 [15:25<24:33,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4796714782714844, Predicted Probability: 0.0299, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.81203293800354, Predicted Probability: 0.8596, Prediction: 1.0

Epoch 1/3:  40%|████      | 1618/4000 [15:26<23:45,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0869044065475464, Predicted Probability: 0.2522, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8587539196014404, Predicted Probability: 0.0207, Prediction: 0.0

Epoch 1/3:  40%|████      | 1619/4000 [15:26<25:57,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.606954574584961, Predicted Probability: 0.0264, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.201887845993042, Predicted Probability: 0.2311, Prediction: 0.0

Epoch 1/3:  40%|████      | 1620/4000 [15:27<27:06,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.713260650634766, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.605722188949585, Predicted Probability: 0.9312, Prediction: 1.0

Epoch 1/3:  41%|████      | 1621/4000 [15:28<28:11,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.559531211853027, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2781403660774231, Predicted Probability: 0.4309, Prediction: 0.0

Epoch 1/3:  41%|████      | 1622/4000 [15:29<28:36,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3855558633804321, Predicted Probability: 0.7999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.848531723022461, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  41%|████      | 1623/4000 [15:29<26:37,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7416329383850098, Predicted Probability: 0.0606, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.635839939117432, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 1/3:  41%|████      | 1624/4000 [15:30<23:00,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8913307189941406, Predicted Probability: 0.0200, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3375954627990723, Predicted Probability: 0.9657, Prediction: 1.0

Epoch 1/3:  41%|████      | 1625/4000 [15:30<25:36,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.447939872741699, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8823291063308716, Predicted Probability: 0.1321, Prediction: 0.0

Epoch 1/3:  41%|████      | 1626/4000 [15:31<22:13,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9966490268707275, Predicted Probability: 0.9820, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5142364501953125, Predicted Probability: 0.9711, Prediction: 1.0

Epoch 1/3:  41%|████      | 1627/4000 [15:31<21:47,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9625337719917297, Predicted Probability: 0.7236, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1089088916778564, Predicted Probability: 0.8918, Prediction: 1.0

Epoch 1/3:  41%|████      | 1628/4000 [15:32<21:44,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.261131525039673, Predicted Probability: 0.9056, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8446879386901855, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  41%|████      | 1629/4000 [15:32<22:19,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.659619688987732, Predicted Probability: 0.8402, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8847156763076782, Predicted Probability: 0.8682, Prediction: 1.0

Epoch 1/3:  41%|████      | 1630/4000 [15:33<21:57,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4608359336853027, Predicted Probability: 0.9214, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.622734069824219, Predicted Probability: 0.9903, Prediction: 1.0

Epoch 1/3:  41%|████      | 1631/4000 [15:33<19:55,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.842989683151245, Predicted Probability: 0.0550, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2477874755859375, Predicted Probability: 0.9626, Prediction: 1.0

Epoch 1/3:  41%|████      | 1632/4000 [15:34<23:11,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7362542152404785, Predicted Probability: 0.8502, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.808058261871338, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  41%|████      | 1633/4000 [15:35<24:57,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5203988552093506, Predicted Probability: 0.9256, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.712728023529053, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  41%|████      | 1634/4000 [15:35<19:52,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8189289569854736, Predicted Probability: 0.0215, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.373883247375488, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 1/3:  41%|████      | 1635/4000 [15:36<22:47,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7589802742004395, Predicted Probability: 0.0228, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8970112800598145, Predicted Probability: 0.9477, Prediction: 1.0

Epoch 1/3:  41%|████      | 1636/4000 [15:37<26:04,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.681612014770508, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.803340435028076, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  41%|████      | 1637/4000 [15:37<22:35,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.173423767089844, Predicted Probability: 0.9848, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4139463901519775, Predicted Probability: 0.0319, Prediction: 0.0

Epoch 1/3:  41%|████      | 1638/4000 [15:38<22:15,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.40610933303833, Predicted Probability: 0.0121, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.510996103286743, Predicted Probability: 0.0290, Prediction: 0.0

Epoch 1/3:  41%|████      | 1639/4000 [15:38<24:36,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.258993148803711, Predicted Probability: 0.0370, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2061595916748047, Predicted Probability: 0.9008, Prediction: 1.0

Epoch 1/3:  41%|████      | 1640/4000 [15:39<26:07,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.10795289278030396, Predicted Probability: 0.4730, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4542574882507324, Predicted Probability: 0.1893, Prediction: 0.0

Epoch 1/3:  41%|████      | 1641/4000 [15:39<20:42,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.229360103607178, Predicted Probability: 0.0144, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.859309196472168, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  41%|████      | 1642/4000 [15:40<18:59,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.613108158111572, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2129902839660645, Predicted Probability: 0.0387, Prediction: 0.0

Epoch 1/3:  41%|████      | 1643/4000 [15:40<22:12,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3716151714324951, Predicted Probability: 0.7976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.870978832244873, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 1/3:  41%|████      | 1644/4000 [15:41<20:03,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.963703155517578, Predicted Probability: 0.9814, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.959435224533081, Predicted Probability: 0.9813, Prediction: 1.0

Epoch 1/3:  41%|████      | 1645/4000 [15:42<22:55,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8267005681991577, Predicted Probability: 0.8614, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5782222747802734, Predicted Probability: 0.0272, Prediction: 0.0

Epoch 1/3:  41%|████      | 1646/4000 [15:42<20:30,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.880242347717285, Predicted Probability: 0.9798, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9347686767578125, Predicted Probability: 0.9495, Prediction: 1.0

Epoch 1/3:  41%|████      | 1647/4000 [15:42<18:37,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.632133960723877, Predicted Probability: 0.0096, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.558255910873413, Predicted Probability: 0.9723, Prediction: 1.0

Epoch 1/3:  41%|████      | 1648/4000 [15:43<21:39,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.81543493270874, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9157071113586426, Predicted Probability: 0.8717, Prediction: 1.0

Epoch 1/3:  41%|████      | 1649/4000 [15:44<24:08,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.784449577331543, Predicted Probability: 0.9418, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.749831199645996, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  41%|████▏     | 1650/4000 [15:44<21:18,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.536282539367676, Predicted Probability: 0.9266, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0527701377868652, Predicted Probability: 0.9549, Prediction: 1.0

Epoch 1/3:  41%|████▏     | 1651/4000 [15:44<17:20,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.382328987121582, Predicted Probability: 0.9877, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.18280553817749, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 1/3:  41%|████▏     | 1652/4000 [15:45<16:23,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.002979278564453, Predicted Probability: 0.1189, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.508986949920654, Predicted Probability: 0.9891, Prediction: 1.0

Epoch 1/3:  41%|████▏     | 1653/4000 [15:46<21:15,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.58919095993042, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.804929733276367, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  41%|████▏     | 1654/4000 [15:46<23:47,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.650805950164795, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.028956890106201, Predicted Probability: 0.9539, Prediction: 1.0

Epoch 1/3:  41%|████▏     | 1655/4000 [15:47<25:31,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.951949119567871, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.332338333129883, Predicted Probability: 0.9115, Prediction: 1.0

Epoch 1/3:  41%|████▏     | 1656/4000 [15:48<22:26,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.628592014312744, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.060572624206543, Predicted Probability: 0.0448, Prediction: 0.0

Epoch 1/3:  41%|████▏     | 1657/4000 [15:48<24:58,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.786773681640625, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9480326175689697, Predicted Probability: 0.7207, Prediction: 1.0

Epoch 1/3:  41%|████▏     | 1658/4000 [15:49<22:15,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.748193740844727, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.531474590301514, Predicted Probability: 0.0107, Prediction: 0.0

Epoch 1/3:  41%|████▏     | 1659/4000 [15:50<25:29,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.891302108764648, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.990152359008789, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1660/4000 [15:50<27:00,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.652560234069824, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6938579082489014, Predicted Probability: 0.9367, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1661/4000 [15:51<28:00,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8895492553710938, Predicted Probability: 0.0527, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.345640182495117, Predicted Probability: 0.0340, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1662/4000 [15:52<28:23,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6741116046905518, Predicted Probability: 0.0645, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.406319618225098, Predicted Probability: 0.0121, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1663/4000 [15:52<24:08,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3558688163757324, Predicted Probability: 0.9663, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.05027802288532257, Predicted Probability: 0.4874, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1664/4000 [15:53<21:09,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.667705059051514, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.886998414993286, Predicted Probability: 0.9799, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1665/4000 [15:53<21:01,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.3545777797698975, Predicted Probability: 0.9133, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.536431789398193, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1666/4000 [15:54<23:12,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.835647106170654, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.661204218864441, Predicted Probability: 0.8404, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1667/4000 [15:55<25:11,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.732605934143066, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.221928119659424, Predicted Probability: 0.9617, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1668/4000 [15:55<22:48,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.355005979537964, Predicted Probability: 0.9133, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9427223205566406, Predicted Probability: 0.9810, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1669/4000 [15:56<21:05,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2777234315872192, Predicted Probability: 0.2179, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.394130706787109, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1670/4000 [15:56<21:11,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.447981357574463, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3997750282287598, Predicted Probability: 0.9677, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1671/4000 [15:57<23:44,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.045589983463287354, Predicted Probability: 0.4886, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.739886283874512, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1672/4000 [15:57<18:59,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.604546070098877, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.140813827514648, Predicted Probability: 0.0157, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1673/4000 [15:58<21:41,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.71445631980896, Predicted Probability: 0.8474, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.863783359527588, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1674/4000 [15:58<19:32,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9903740882873535, Predicted Probability: 0.0479, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.977510929107666, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1675/4000 [15:59<18:02,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7989885807037354, Predicted Probability: 0.0574, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4037833213806152, Predicted Probability: 0.9678, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1676/4000 [15:59<18:49,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.559874057769775, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.043257474899292, Predicted Probability: 0.8853, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1677/4000 [15:59<16:19,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.606717109680176, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9779465198516846, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1678/4000 [16:00<21:50,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.0017080307006836, Predicted Probability: 0.7314, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.235172748565674, Predicted Probability: 0.0143, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1679/4000 [16:01<21:26,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.508756160736084, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.433055877685547, Predicted Probability: 0.9193, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1680/4000 [16:02<24:00,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.462984561920166, Predicted Probability: 0.9215, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.314833641052246, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1681/4000 [16:02<25:20,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0185375213623047, Predicted Probability: 0.1173, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5356962084770203, Predicted Probability: 0.3692, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1682/4000 [16:03<26:18,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5066864490509033, Predicted Probability: 0.8186, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.0739824771881104, Predicted Probability: 0.7454, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1683/4000 [16:04<26:49,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.529861569404602, Predicted Probability: 0.3705, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8042755126953125, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1684/4000 [16:04<21:07,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.417936325073242, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.742705345153809, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1685/4000 [16:04<20:07,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.749938488006592, Predicted Probability: 0.9770, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.174501895904541, Predicted Probability: 0.9849, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1686/4000 [16:05<22:41,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.883851528167725, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6567673683166504, Predicted Probability: 0.8398, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1687/4000 [16:06<20:15,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.233780384063721, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.123534917831421, Predicted Probability: 0.7546, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1688/4000 [16:06<22:58,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.656332969665527, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5826237201690674, Predicted Probability: 0.9297, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1689/4000 [16:07<24:52,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3052568435668945, Predicted Probability: 0.0133, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.2457603216171265, Predicted Probability: 0.7766, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1690/4000 [16:08<26:31,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4887170791625977, Predicted Probability: 0.9233, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3384487628936768, Predicted Probability: 0.0343, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1691/4000 [16:09<27:52,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.176482915878296, Predicted Probability: 0.7643, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.698330879211426, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1692/4000 [16:09<28:10,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6701010465621948, Predicted Probability: 0.1584, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.04599142074585, Predicted Probability: 0.0172, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1693/4000 [16:10<28:21,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2006635665893555, Predicted Probability: 0.9609, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.481986165046692, Predicted Probability: 0.8149, Prediction: 1.0

Epoch 1/3:  42%|████▏     | 1694/4000 [16:10<23:05,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.936336040496826, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.735611915588379, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1695/4000 [16:11<22:29,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3200817108154297, Predicted Probability: 0.9105, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.733057022094727, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1696/4000 [16:12<24:35,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8541209697723389, Predicted Probability: 0.2986, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.562320709228516, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1697/4000 [16:13<26:00,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.244854211807251, Predicted Probability: 0.0375, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.11612606048584, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1698/4000 [16:13<21:15,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.983779191970825, Predicted Probability: 0.9518, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.99201774597168, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 1/3:  42%|████▏     | 1699/4000 [16:14<24:38,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.774284362792969, Predicted Probability: 0.0084, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.950199604034424, Predicted Probability: 0.0070, Prediction: 0.0

Epoch 1/3:  42%|████▎     | 1700/4000 [16:14<25:35,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0389671325683594, Predicted Probability: 0.2613, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.910231590270996, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1701/4000 [16:15<22:10,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.261692762374878, Predicted Probability: 0.0369, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5246901512146, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1702/4000 [16:15<20:44,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.889357089996338, Predicted Probability: 0.1313, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7000346183776855, Predicted Probability: 0.9370, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1704/4000 [16:16<14:14,  2.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.506230354309082, Predicted Probability: 0.9246, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1780292987823486, Predicted Probability: 0.9600, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.025659084320068, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.429786682128906, Predicted Probability: 0.9882, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1705/4000 [16:16<19:22,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5001702308654785, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.052800178527832, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1706/4000 [16:17<17:47,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2131948471069336, Predicted Probability: 0.9613, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6493873596191406, Predicted Probability: 0.9747, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1707/4000 [16:18<21:07,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.7903828620910645, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.6226789951324463, Predicted Probability: 0.3492, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1708/4000 [16:18<19:03,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.878424048423767, Predicted Probability: 0.8674, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9827632904052734, Predicted Probability: 0.9817, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1709/4000 [16:18<19:37,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.6766616702079773, Predicted Probability: 0.3370, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.947163105010986, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1710/4000 [16:19<17:56,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.7425713539123535, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.653953790664673, Predicted Probability: 0.9343, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1711/4000 [16:20<21:10,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.434581756591797, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.459484577178955, Predicted Probability: 0.0787, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1712/4000 [16:20<23:23,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.908866882324219, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2917240858078003, Predicted Probability: 0.7844, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1713/4000 [16:21<25:33,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8980506658554077, Predicted Probability: 0.8697, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.232521057128906, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1714/4000 [16:22<26:21,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.798461437225342, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1607913970947266, Predicted Probability: 0.7615, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 1.4814963340759277, Predicted Probability: 0.8148, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.133385181427002, Predicted Probability: 0.0158, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1716/4000 [16:23<19:39,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8153192400932312, Predicted Probability: 0.3068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4082229137420654, Predicted Probability: 0.9175, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1717/4000 [16:23<21:59,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4577994346618652, Predicted Probability: 0.8112, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.997164249420166, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1718/4000 [16:24<23:49,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9847187995910645, Predicted Probability: 0.0183, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8425579071044922, Predicted Probability: 0.6990, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1719/4000 [16:25<26:22,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.688106536865234, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7513899803161621, Predicted Probability: 0.6795, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1720/4000 [16:26<27:51,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.064189910888672, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.374408483505249, Predicted Probability: 0.0331, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1721/4000 [16:26<25:48,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.054809331893921, Predicted Probability: 0.8864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.4285407066345215, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1722/4000 [16:27<22:16,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.589565753936768, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5277087688446045, Predicted Probability: 0.0285, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1723/4000 [16:27<20:33,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2267017364501953, Predicted Probability: 0.9026, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.909682273864746, Predicted Probability: 0.9803, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1724/4000 [16:28<23:06,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.250111103057861, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5219244956970215, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1725/4000 [16:29<25:09,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9659013748168945, Predicted Probability: 0.1228, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.533475637435913, Predicted Probability: 0.8225, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1726/4000 [16:29<25:41,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.318101406097412, Predicted Probability: 0.0131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2485889047384262, Predicted Probability: 0.4382, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1727/4000 [16:30<22:08,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.962569236755371, Predicted Probability: 0.0187, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.845933437347412, Predicted Probability: 0.9791, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1728/4000 [16:30<22:41,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.315567970275879, Predicted Probability: 0.0132, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9383280277252197, Predicted Probability: 0.0191, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1730/4000 [16:31<16:32,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3823132514953613, Predicted Probability: 0.0329, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.22528076171875, Predicted Probability: 0.9856, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.534990310668945, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.179201126098633, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1731/4000 [16:31<13:59,  2.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.303743600845337, Predicted Probability: 0.0354, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.477947235107422, Predicted Probability: 0.0112, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1732/4000 [16:31<12:06,  3.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.35454511642456055, Predicted Probability: 0.4123, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.298412799835205, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1733/4000 [16:32<17:26,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4946492910385132, Predicted Probability: 0.3788, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.55592942237854, Predicted Probability: 0.0278, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1734/4000 [16:33<20:23,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.760227203369141, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7595993280410767, Predicted Probability: 0.8532, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1735/4000 [16:34<22:23,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.649800717830658, Predicted Probability: 0.3430, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.093225479125977, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1736/4000 [16:34<19:52,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1181411743164062, Predicted Probability: 0.1073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.527234077453613, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1737/4000 [16:34<16:16,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.384068012237549, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.781987190246582, Predicted Probability: 0.9917, Prediction: 1.0

Epoch 1/3:  43%|████▎     | 1738/4000 [16:35<20:35,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.972316741943359, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.742138862609863, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  43%|████▎     | 1739/4000 [16:36<23:43,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.292862892150879, Predicted Probability: 0.0135, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7735769748687744, Predicted Probability: 0.8549, Prediction: 1.0

Epoch 1/3:  44%|████▎     | 1740/4000 [16:36<22:44,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.328859806060791, Predicted Probability: 0.9112, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3636605739593506, Predicted Probability: 0.0335, Prediction: 0.0

Epoch 1/3:  44%|████▎     | 1741/4000 [16:37<20:07,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.584911346435547, Predicted Probability: 0.9730, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2203288078308105, Predicted Probability: 0.9855, Prediction: 1.0

Epoch 1/3:  44%|████▎     | 1742/4000 [16:37<22:36,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.83408522605896, Predicted Probability: 0.8622, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.147833347320557, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  44%|████▎     | 1743/4000 [16:38<23:59,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.624334454536438, Predicted Probability: 0.8354, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.942580699920654, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  44%|████▎     | 1744/4000 [16:39<25:06,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1177592277526855, Predicted Probability: 0.0424, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8968396186828613, Predicted Probability: 0.0523, Prediction: 0.0

Epoch 1/3:  44%|████▎     | 1745/4000 [16:40<26:07,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3917531967163086, Predicted Probability: 0.9162, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.871469020843506, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 1/3:  44%|████▎     | 1746/4000 [16:40<27:03,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.807058334350586, Predicted Probability: 0.0081, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5760519504547119, Predicted Probability: 0.6402, Prediction: 1.0

Epoch 1/3:  44%|████▎     | 1747/4000 [16:41<27:34,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.979943871498108, Predicted Probability: 0.8787, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.027054786682129, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  44%|████▎     | 1748/4000 [16:42<26:07,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6864144206047058, Predicted Probability: 0.6652, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5593795776367188, Predicted Probability: 0.9282, Prediction: 1.0

Epoch 1/3:  44%|████▎     | 1749/4000 [16:43<26:57,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.337553977966309, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.996368169784546, Predicted Probability: 0.1196, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1750/4000 [16:43<23:06,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.910582542419434, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.24718619883060455, Predicted Probability: 0.4385, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1751/4000 [16:44<24:40,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.397310256958008, Predicted Probability: 0.9166, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7916717529296875, Predicted Probability: 0.0221, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1752/4000 [16:44<25:37,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9555559158325195, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.793017625808716, Predicted Probability: 0.9423, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1753/4000 [16:45<22:10,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.307241439819336, Predicted Probability: 0.0905, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.891695022583008, Predicted Probability: 0.9474, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1754/4000 [16:46<24:12,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.559885501861572, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6571598052978516, Predicted Probability: 0.1601, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1755/4000 [16:46<25:23,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8150371313095093, Predicted Probability: 0.8600, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.279632091522217, Predicted Probability: 0.0137, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1756/4000 [16:47<21:53,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.349880695343018, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1179118156433105, Predicted Probability: 0.9840, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1757/4000 [16:47<19:29,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.8590240478515625, Predicted Probability: 0.9923, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.831513524055481, Predicted Probability: 0.1381, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1758/4000 [16:48<19:54,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.601612091064453, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6457600593566895, Predicted Probability: 0.9337, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1759/4000 [16:48<22:13,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.254321575164795, Predicted Probability: 0.7780, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.652301788330078, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1760/4000 [16:49<24:10,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7500383853912354, Predicted Probability: 0.8520, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.77374792098999, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1761/4000 [16:50<21:06,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.635118246078491, Predicted Probability: 0.0669, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3718130588531494, Predicted Probability: 0.9668, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1762/4000 [16:50<18:57,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6360154151916504, Predicted Probability: 0.9331, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.831582546234131, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1763/4000 [16:51<21:16,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.960903644561768, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6993472576141357, Predicted Probability: 0.8454, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1764/4000 [16:51<19:03,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.60795259475708, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8945162296295166, Predicted Probability: 0.9801, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1765/4000 [16:52<21:42,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.52665638923645, Predicted Probability: 0.9260, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.449123859405518, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1766/4000 [16:52<19:21,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.732745170593262, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.001258611679077, Predicted Probability: 0.0474, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1767/4000 [16:53<17:45,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.235437393188477, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6599605083465576, Predicted Probability: 0.0654, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1768/4000 [16:53<20:56,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3731067180633545, Predicted Probability: 0.5922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.799455642700195, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1769/4000 [16:54<18:55,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3444437980651855, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2291324138641357, Predicted Probability: 0.9619, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1770/4000 [16:54<17:22,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4417147636413574, Predicted Probability: 0.9690, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.598945617675781, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1771/4000 [16:55<21:00,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.135656356811523, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.156270980834961, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1772/4000 [16:55<16:58,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.414581298828125, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.30599308013916, Predicted Probability: 0.9867, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1773/4000 [16:56<22:16,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9214673042297363, Predicted Probability: 0.0194, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.245809555053711, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1774/4000 [16:57<24:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.385401964187622, Predicted Probability: 0.0328, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.6017086505889893, Predicted Probability: 0.3540, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1775/4000 [16:57<23:02,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.060836315155029, Predicted Probability: 0.0169, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4318461418151855, Predicted Probability: 0.9882, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1776/4000 [16:58<25:03,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.75924015045166, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9832658767700195, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1777/4000 [16:59<25:37,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.495978355407715, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9099503755569458, Predicted Probability: 0.8710, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1778/4000 [16:59<20:14,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.318795204162598, Predicted Probability: 0.0131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.624083518981934, Predicted Probability: 0.9903, Prediction: 1.0

Epoch 1/3:  44%|████▍     | 1779/4000 [16:59<18:58,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.387483596801758, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4732407331466675, Predicted Probability: 0.1865, Prediction: 0.0

Epoch 1/3:  44%|████▍     | 1780/4000 [17:00<21:22,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.868262529373169, Predicted Probability: 0.8663, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.0822181701660156, Predicted Probability: 0.0438, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1781/4000 [17:01<19:09,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6755993366241455, Predicted Probability: 0.9753, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.287170886993408, Predicted Probability: 0.9864, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1782/4000 [17:01<22:19,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.725706577301025, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8713295459747314, Predicted Probability: 0.9464, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1784/4000 [17:02<15:57,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.695859909057617, Predicted Probability: 0.9909, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3655200004577637, Predicted Probability: 0.9666, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: 2.948485851287842, Predicted Probability: 0.9502, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.091434001922607, Predicted Probability: 0.9939, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1785/4000 [17:03<19:21,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3490350246429443, Predicted Probability: 0.2060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.102530479431152, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1786/4000 [17:04<23:01,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.965241432189941, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.453769683837891, Predicted Probability: 0.0115, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1787/4000 [17:04<22:50,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1777024269104004, Predicted Probability: 0.8982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6279942989349365, Predicted Probability: 0.9326, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1788/4000 [17:05<24:31,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9807438850402832, Predicted Probability: 0.8788, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1996612548828125, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1789/4000 [17:05<21:15,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.2121572494506836, Predicted Probability: 0.0387, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4657163619995117, Predicted Probability: 0.9697, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1790/4000 [17:06<22:59,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3314359784126282, Predicted Probability: 0.4179, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.767335414886475, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1791/4000 [17:07<24:48,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7830486297607422, Predicted Probability: 0.8561, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.267914295196533, Predicted Probability: 0.0138, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1792/4000 [17:07<21:29,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0957329273223877, Predicted Probability: 0.1095, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.540682315826416, Predicted Probability: 0.9269, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1793/4000 [17:08<19:14,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0014398097991943, Predicted Probability: 0.9526, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7618250846862793, Predicted Probability: 0.9406, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1794/4000 [17:08<21:36,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9122684001922607, Predicted Probability: 0.8713, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.197691917419434, Predicted Probability: 0.0148, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1795/4000 [17:09<19:16,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3257906436920166, Predicted Probability: 0.9110, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.75249719619751, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1796/4000 [17:09<22:07,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.687100887298584, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3447492718696594, Predicted Probability: 0.5853, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1797/4000 [17:10<20:23,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.879013776779175, Predicted Probability: 0.9797, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1856205463409424, Predicted Probability: 0.8990, Prediction: 1.0

Epoch 1/3:  45%|████▍     | 1798/4000 [17:11<22:29,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6092095375061035, Predicted Probability: 0.9315, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.758504867553711, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 1/3:  45%|████▍     | 1799/4000 [17:12<25:01,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.62356424331665, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.341482162475586, Predicted Probability: 0.0128, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1800/4000 [17:12<26:06,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.688136100769043, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5393881797790527, Predicted Probability: 0.9269, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1801/4000 [17:13<22:30,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.431797504425049, Predicted Probability: 0.0118, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8950791358947754, Predicted Probability: 0.9801, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1802/4000 [17:13<24:17,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.749605178833008, Predicted Probability: 0.0086, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.717104434967041, Predicted Probability: 0.9380, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1803/4000 [17:14<26:29,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.594254970550537, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.757935047149658, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1804/4000 [17:15<22:36,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.104931354522705, Predicted Probability: 0.0162, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.005111217498779, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1805/4000 [17:15<24:06,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5640442371368408, Predicted Probability: 0.8269, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.900650978088379, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1806/4000 [17:16<21:00,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7186890840530396, Predicted Probability: 0.3277, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.619381427764893, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1808/4000 [17:17<18:04,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.39469391107559204, Predicted Probability: 0.4026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.0569539070129395, Predicted Probability: 0.0063, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -3.444197416305542, Predicted Probability: 0.0309, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3589110374450684, Predicted Probability: 0.0336, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1809/4000 [17:17<20:32,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.82804536819458, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8918538093566895, Predicted Probability: 0.8690, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1810/4000 [17:18<18:32,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7228356599807739, Predicted Probability: 0.6732, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.3126349449157715, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1811/4000 [17:18<17:05,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2056667804718018, Predicted Probability: 0.9610, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.568127155303955, Predicted Probability: 0.9897, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1812/4000 [17:18<14:53,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.152859687805176, Predicted Probability: 0.0155, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.380833148956299, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1813/4000 [17:19<18:52,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.649121284484863, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9856114387512207, Predicted Probability: 0.9519, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1814/4000 [17:20<21:26,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.030387878417969, Predicted Probability: 0.0175, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.869696855545044, Predicted Probability: 0.9463, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1815/4000 [17:21<21:06,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.397575378417969, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.54885196685791, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1816/4000 [17:22<25:42,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3848705291748047, Predicted Probability: 0.0328, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1235102415084839, Predicted Probability: 0.7546, Prediction: 1.0

Epoch 1/3:  45%|████▌     | 1817/4000 [17:22<28:02,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6643757820129395, Predicted Probability: 0.0250, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.747925758361816, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1818/4000 [17:23<21:58,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.209754943847656, Predicted Probability: 0.9946, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.397943496704102, Predicted Probability: 0.0122, Prediction: 0.0

Epoch 1/3:  45%|████▌     | 1819/4000 [17:23<21:14,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.4546427726745605, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2448065280914307, Predicted Probability: 0.2236, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1820/4000 [17:24<22:53,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.11243200302124023, Predicted Probability: 0.4719, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.937568664550781, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1821/4000 [17:25<24:11,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.484501361846924, Predicted Probability: 0.0112, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.49888473749160767, Predicted Probability: 0.3778, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1822/4000 [17:25<24:50,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.816615581512451, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.112130880355835, Predicted Probability: 0.8921, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1823/4000 [17:26<21:36,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7488343715667725, Predicted Probability: 0.8518, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.751509666442871, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1824/4000 [17:27<23:10,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7392239570617676, Predicted Probability: 0.0232, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2963931560516357, Predicted Probability: 0.2148, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1825/4000 [17:27<22:15,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6295530796051025, Predicted Probability: 0.9742, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.660849571228027, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1826/4000 [17:27<17:48,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.503235816955566, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4810709953308105, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1827/4000 [17:28<20:17,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2746169567108154, Predicted Probability: 0.0365, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6162192225456238, Predicted Probability: 0.3506, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1828/4000 [17:29<22:23,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.552740097045898, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7771310806274414, Predicted Probability: 0.8553, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1829/4000 [17:29<19:40,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.627254009246826, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4117441177368164, Predicted Probability: 0.9681, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1830/4000 [17:30<21:44,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.45037510991096497, Predicted Probability: 0.6107, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.566788196563721, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1831/4000 [17:31<22:57,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.626562774181366, Predicted Probability: 0.3483, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0057709217071533, Predicted Probability: 0.0472, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1832/4000 [17:31<20:02,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.558739423751831, Predicted Probability: 0.9723, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.214479446411133, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1833/4000 [17:32<21:56,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5116825103759766, Predicted Probability: 0.9250, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.161881923675537, Predicted Probability: 0.0153, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1834/4000 [17:32<20:16,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.104775428771973, Predicted Probability: 0.0162, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.239110469818115, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1835/4000 [17:33<19:57,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.4041202068328857, Predicted Probability: 0.1972, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.236669063568115, Predicted Probability: 0.0142, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1837/4000 [17:33<13:26,  2.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.875027656555176, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1958699226379395, Predicted Probability: 0.9945, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 0.7821890115737915, Predicted Probability: 0.6862, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7799413204193115, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1839/4000 [17:34<14:19,  2.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.12532639503479, Predicted Probability: 0.0421, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.762955188751221, Predicted Probability: 0.9915, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 3.5767552852630615, Predicted Probability: 0.9728, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.971415996551514, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1840/4000 [17:35<17:42,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3208158016204834, Predicted Probability: 0.9106, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6063451766967773, Predicted Probability: 0.9313, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1841/4000 [17:36<21:18,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6313388347625732, Predicted Probability: 0.3472, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8661341667175293, Predicted Probability: 0.0205, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1842/4000 [17:36<19:12,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.890612602233887, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.969491481781006, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1843/4000 [17:37<21:06,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.88787317276001, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8842574954032898, Predicted Probability: 0.7077, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1844/4000 [17:37<18:54,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.807600021362305, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.580988883972168, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1845/4000 [17:38<21:43,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5737241506576538, Predicted Probability: 0.8283, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.451097011566162, Predicted Probability: 0.0115, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1846/4000 [17:38<19:53,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9462738037109375, Predicted Probability: 0.2796, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.608374118804932, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1847/4000 [17:39<18:03,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.072690486907959, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.124422788619995, Predicted Probability: 0.9579, Prediction: 1.0

Epoch 1/3:  46%|████▌     | 1848/4000 [17:39<20:34,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6421008110046387, Predicted Probability: 0.8378, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3313761949539185, Predicted Probability: 0.2089, Prediction: 0.0

Epoch 1/3:  46%|████▌     | 1849/4000 [17:40<22:30,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.082939624786377, Predicted Probability: 0.8892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.079473495483398, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  46%|████▋     | 1850/4000 [17:41<25:15,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2520906925201416, Predicted Probability: 0.0373, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.426360607147217, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 1/3:  46%|████▋     | 1851/4000 [17:42<23:26,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.195216178894043, Predicted Probability: 0.9852, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.422315239906311, Predicted Probability: 0.1943, Prediction: 0.0

Epoch 1/3:  46%|████▋     | 1852/4000 [17:42<21:07,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.430662155151367, Predicted Probability: 0.9191, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.15683749318122864, Predicted Probability: 0.5391, Prediction: 1.0

Epoch 1/3:  46%|████▋     | 1853/4000 [17:43<20:31,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5422439575195312, Predicted Probability: 0.9271, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.177910327911377, Predicted Probability: 0.9849, Prediction: 1.0

Epoch 1/3:  46%|████▋     | 1854/4000 [17:43<22:25,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6306986808776855, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.853456497192383, Predicted Probability: 0.9455, Prediction: 1.0

Epoch 1/3:  46%|████▋     | 1855/4000 [17:44<23:41,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.512293577194214, Predicted Probability: 0.9250, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.669870853424072, Predicted Probability: 0.0093, Prediction: 0.0

Epoch 1/3:  46%|████▋     | 1856/4000 [17:45<22:18,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.4600368738174438, Predicted Probability: 0.8115, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.084224224090576, Predicted Probability: 0.9834, Prediction: 1.0

Epoch 1/3:  46%|████▋     | 1857/4000 [17:45<23:37,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.539189338684082, Predicted Probability: 0.8233, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.538616180419922, Predicted Probability: 0.0106, Prediction: 0.0

Epoch 1/3:  46%|████▋     | 1858/4000 [17:46<20:26,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.820757865905762, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0661187171936035, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  46%|████▋     | 1859/4000 [17:47<22:58,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7941527366638184, Predicted Probability: 0.0576, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.193591117858887, Predicted Probability: 0.0149, Prediction: 0.0

Epoch 1/3:  46%|████▋     | 1860/4000 [17:47<22:39,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.105498790740967, Predicted Probability: 0.0162, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1110005378723145, Predicted Probability: 0.1080, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1861/4000 [17:48<23:40,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.7289308309555054, Predicted Probability: 0.3254, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7127730846405029, Predicted Probability: 0.3290, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1862/4000 [17:49<24:32,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7408616542816162, Predicted Probability: 0.8508, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.330212593078613, Predicted Probability: 0.0130, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1863/4000 [17:49<21:10,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.518913984298706, Predicted Probability: 0.0288, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.53676700592041, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1864/4000 [17:49<18:53,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.467310428619385, Predicted Probability: 0.0113, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.240078449249268, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1865/4000 [17:50<18:59,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9357988834381104, Predicted Probability: 0.9496, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.530727386474609, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1866/4000 [17:51<21:38,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3241946697235107, Predicted Probability: 0.7899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.105319023132324, Predicted Probability: 0.0162, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1867/4000 [17:51<20:57,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5556617975234985, Predicted Probability: 0.1743, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.05747652053833, Predicted Probability: 0.0170, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1868/4000 [17:51<16:53,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8212995529174805, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.437769412994385, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1869/4000 [17:52<17:30,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.802836298942566, Predicted Probability: 0.8585, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.1904449462890625, Predicted Probability: 0.0149, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1870/4000 [17:52<15:10,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.395811557769775, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.736193656921387, Predicted Probability: 0.9913, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1871/4000 [17:53<14:32,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.954233407974243, Predicted Probability: 0.9812, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9317615032196045, Predicted Probability: 0.0506, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1872/4000 [17:53<17:51,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.107138633728027, Predicted Probability: 0.0162, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7722886204719543, Predicted Probability: 0.3160, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1873/4000 [17:54<18:24,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.361518859863281, Predicted Probability: 0.0126, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.013936309143900871, Predicted Probability: 0.4965, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1874/4000 [17:55<18:53,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5176720023155212, Predicted Probability: 0.6266, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.593676567077637, Predicted Probability: 0.0100, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1875/4000 [17:55<17:13,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.326257228851318, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.479498863220215, Predicted Probability: 0.0112, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1876/4000 [17:56<20:14,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.23958122730255127, Predicted Probability: 0.5596, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.106581687927246, Predicted Probability: 0.0428, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1877/4000 [17:56<18:18,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7168517112731934, Predicted Probability: 0.9763, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.785876750946045, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1878/4000 [17:57<20:52,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.63270902633667, Predicted Probability: 0.0671, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7631797790527344, Predicted Probability: 0.3180, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1879/4000 [17:58<22:26,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.3589472770690918, Predicted Probability: 0.7956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8238301277160645, Predicted Probability: 0.8610, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1880/4000 [17:58<19:54,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.097769021987915, Predicted Probability: 0.1093, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0685982704162598, Predicted Probability: 0.9556, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1881/4000 [17:59<22:12,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7059326171875, Predicted Probability: 0.9374, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.423521995544434, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1882/4000 [17:59<23:14,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.759183883666992, Predicted Probability: 0.9404, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7449254989624023, Predicted Probability: 0.1487, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1883/4000 [18:00<24:00,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.644010543823242, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7429447174072266, Predicted Probability: 0.8511, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1884/4000 [18:01<22:23,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.745182514190674, Predicted Probability: 0.9396, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.41519832611084, Predicted Probability: 0.9881, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1885/4000 [18:01<23:39,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6298460960388184, Predicted Probability: 0.9328, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.130897521972656, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1886/4000 [18:02<24:31,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7891004085540771, Predicted Probability: 0.8568, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.366725444793701, Predicted Probability: 0.0125, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1887/4000 [18:03<21:04,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4370899200439453, Predicted Probability: 0.9688, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5170376300811768, Predicted Probability: 0.9712, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1888/4000 [18:03<23:09,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.207302093505859, Predicted Probability: 0.0147, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.663766622543335, Predicted Probability: 0.0651, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1889/4000 [18:04<23:47,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7544821500778198, Predicted Probability: 0.6802, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.14385461807251, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1890/4000 [18:05<24:39,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.872191905975342, Predicted Probability: 0.0204, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6004233360290527, Predicted Probability: 0.9309, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1891/4000 [18:05<23:05,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6106157302856445, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.425032377243042, Predicted Probability: 0.9685, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1892/4000 [18:06<21:00,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0423970222473145, Predicted Probability: 0.8852, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5797297954559326, Predicted Probability: 0.0705, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1894/4000 [18:06<15:14,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.23599100112915, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.69701623916626, Predicted Probability: 0.9910, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.327645778656006, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.040248394012451, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1895/4000 [18:07<19:11,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.695116996765137, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.450582504272461, Predicted Probability: 0.9206, Prediction: 1.0

Epoch 1/3:  47%|████▋     | 1896/4000 [18:08<22:57,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.736517906188965, Predicted Probability: 0.0233, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.687939643859863, Predicted Probability: 0.0091, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1897/4000 [18:09<19:52,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.571728229522705, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.633101940155029, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1898/4000 [18:09<21:57,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.234148979187012, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6139616966247559, Predicted Probability: 0.1660, Prediction: 0.0

Epoch 1/3:  47%|████▋     | 1899/4000 [18:10<23:07,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.759589672088623, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6560893058776855, Predicted Probability: 0.8397, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1900/4000 [18:11<22:05,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.81485652923584, Predicted Probability: 0.0216, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.171217441558838, Predicted Probability: 0.9848, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1901/4000 [18:11<17:39,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5173702239990234, Predicted Probability: 0.9254, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.53402042388916, Predicted Probability: 0.9265, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1902/4000 [18:12<20:06,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7340495586395264, Predicted Probability: 0.8499, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.82780122756958, Predicted Probability: 0.0558, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1903/4000 [18:12<18:11,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2834296226501465, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8247275352478027, Predicted Probability: 0.9440, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1904/4000 [18:12<16:39,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.711458206176758, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1813747882843018, Predicted Probability: 0.9601, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1905/4000 [18:13<16:19,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9333720207214355, Predicted Probability: 0.9808, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2887444496154785, Predicted Probability: 0.0135, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1906/4000 [18:14<19:30,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1083638668060303, Predicted Probability: 0.9572, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4823052883148193, Predicted Probability: 0.1851, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1907/4000 [18:14<17:32,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.603127956390381, Predicted Probability: 0.0689, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.840618133544922, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1908/4000 [18:14<17:58,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.754161834716797, Predicted Probability: 0.9771, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.010810375213623, Predicted Probability: 0.9822, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1909/4000 [18:15<21:12,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.02449107170105, Predicted Probability: 0.0463, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6512298583984375, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1910/4000 [18:16<17:02,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.961082935333252, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.039344072341919, Predicted Probability: 0.8849, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1911/4000 [18:16<19:51,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0001020431518555, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4749560356140137, Predicted Probability: 0.9224, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1912/4000 [18:16<16:00,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.160613536834717, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0436110496521, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1913/4000 [18:17<18:42,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.193659782409668, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9843451976776123, Predicted Probability: 0.8791, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1914/4000 [18:17<15:12,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.042968273162842, Predicted Probability: 0.0172, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.443150043487549, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1915/4000 [18:18<12:47,  2.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.844597339630127, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2350313663482666, Predicted Probability: 0.0379, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1916/4000 [18:18<12:45,  2.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.871816158294678, Predicted Probability: 0.0076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 3.401012420654297, Predicted Probability: 0.9677, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1917/4000 [18:18<11:01,  3.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.9883627891540527, Predicted Probability: 0.0480, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.260047912597656, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1918/4000 [18:19<16:21,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8687567710876465, Predicted Probability: 0.0076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.708192825317383, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1919/4000 [18:19<15:17,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.060802936553955, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.299675941467285, Predicted Probability: 0.0134, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1920/4000 [18:20<17:12,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2004451751708984, Predicted Probability: 0.9609, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.783402442932129, Predicted Probability: 0.0222, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1921/4000 [18:21<17:36,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9357128143310547, Predicted Probability: 0.0192, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.117302417755127, Predicted Probability: 0.8926, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1922/4000 [18:21<20:02,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5236161947250366, Predicted Probability: 0.8211, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.154636383056641, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1923/4000 [18:22<22:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.178007125854492, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.879211902618408, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1924/4000 [18:23<20:17,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7757177352905273, Predicted Probability: 0.9413, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2682597637176514, Predicted Probability: 0.9633, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1925/4000 [18:23<17:01,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.316310882568359, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.75446081161499, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1926/4000 [18:23<17:24,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9058735370635986, Predicted Probability: 0.9481, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.973066568374634, Predicted Probability: 0.9513, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1927/4000 [18:24<20:02,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.697288990020752, Predicted Probability: 0.9369, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.908926010131836, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1928/4000 [18:24<17:57,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1268913745880127, Predicted Probability: 0.9580, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5765156745910645, Predicted Probability: 0.0102, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1929/4000 [18:25<16:31,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.34194040298461914, Predicted Probability: 0.4153, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.739389419555664, Predicted Probability: 0.0607, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1930/4000 [18:26<19:45,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.682433605194092, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8180814981460571, Predicted Probability: 0.1397, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1931/4000 [18:26<22:22,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.135978698730469, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9732797741889954, Predicted Probability: 0.7258, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1932/4000 [18:27<17:46,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.847454786300659, Predicted Probability: 0.9791, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.4106078147888184, Predicted Probability: 0.0320, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1933/4000 [18:27<18:07,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8171440362930298, Predicted Probability: 0.8602, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5765738487243652, Predicted Probability: 0.1713, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1935/4000 [18:28<13:31,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.462151527404785, Predicted Probability: 0.9696, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.795241355895996, Predicted Probability: 0.9918, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: -2.9455819129943848, Predicted Probability: 0.0499, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.28525972366333, Predicted Probability: 0.9864, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1936/4000 [18:29<16:57,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8386077880859375, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.17931054532527924, Predicted Probability: 0.4553, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1937/4000 [18:29<14:00,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9829189777374268, Predicted Probability: 0.9817, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.067181587219238, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1938/4000 [18:29<17:26,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8619656562805176, Predicted Probability: 0.8655, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.902471542358398, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 1/3:  48%|████▊     | 1939/4000 [18:30<16:05,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.841311931610107, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.804145336151123, Predicted Probability: 0.9429, Prediction: 1.0

Epoch 1/3:  48%|████▊     | 1940/4000 [18:30<16:46,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4354801177978516, Predicted Probability: 0.9195, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.685924768447876, Predicted Probability: 0.9362, Prediction: 1.0

Epoch 1/3:  49%|████▊     | 1941/4000 [18:31<19:52,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9609832763671875, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9506745338439941, Predicted Probability: 0.1245, Prediction: 0.0

Epoch 1/3:  49%|████▊     | 1942/4000 [18:32<18:29,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.947564125061035, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.379990339279175, Predicted Probability: 0.9153, Prediction: 1.0

Epoch 1/3:  49%|████▊     | 1943/4000 [18:32<16:45,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1913197040557861, Predicted Probability: 0.2330, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.130218029022217, Predicted Probability: 0.0158, Prediction: 0.0

Epoch 1/3:  49%|████▊     | 1944/4000 [18:33<19:05,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8903402090072632, Predicted Probability: 0.8688, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1461057662963867, Predicted Probability: 0.8953, Prediction: 1.0

Epoch 1/3:  49%|████▊     | 1945/4000 [18:33<21:13,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.013098955154419, Predicted Probability: 0.8822, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.043190002441406, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  49%|████▊     | 1946/4000 [18:34<23:12,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2998366355896, Predicted Probability: 0.0134, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9453043937683105, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  49%|████▊     | 1947/4000 [18:35<20:11,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.263903617858887, Predicted Probability: 0.0139, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.567249298095703, Predicted Probability: 0.9897, Prediction: 1.0

Epoch 1/3:  49%|████▊     | 1948/4000 [18:35<22:20,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.789424896240234, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9305493831634521, Predicted Probability: 0.8733, Prediction: 1.0

Epoch 1/3:  49%|████▊     | 1949/4000 [18:36<17:46,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7403297424316406, Predicted Probability: 0.9768, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.073780536651611, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1950/4000 [18:36<16:07,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.633206844329834, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.284651756286621, Predicted Probability: 0.0136, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1951/4000 [18:36<15:07,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4849741458892822, Predicted Probability: 0.9703, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.72731351852417, Predicted Probability: 0.9912, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1952/4000 [18:37<18:30,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8171508312225342, Predicted Probability: 0.6936, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.637459754943848, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1953/4000 [18:38<20:55,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.990062713623047, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7376980781555176, Predicted Probability: 0.0608, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1954/4000 [18:39<22:05,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.034097194671631, Predicted Probability: 0.8843, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.005005836486816, Predicted Probability: 0.0179, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1955/4000 [18:39<21:02,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.359365463256836, Predicted Probability: 0.9664, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0806944370269775, Predicted Probability: 0.8890, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1956/4000 [18:40<22:23,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6386511325836182, Predicted Probability: 0.8374, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.786065101623535, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1957/4000 [18:41<21:11,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5194428563117981, Predicted Probability: 0.3730, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.7487119436264038, Predicted Probability: 0.1482, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1958/4000 [18:41<22:13,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9135915040969849, Predicted Probability: 0.8714, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.698284149169922, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1959/4000 [18:42<23:13,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.831316947937012, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9670300483703613, Predicted Probability: 0.0489, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1960/4000 [18:43<24:06,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.075977325439453, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2644433975219727, Predicted Probability: 0.0368, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1961/4000 [18:43<24:05,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6914825439453125, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1019864082336426, Predicted Probability: 0.8911, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1963/4000 [18:44<17:40,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6614084243774414, Predicted Probability: 0.0653, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.636197090148926, Predicted Probability: 0.9904, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 4.570560455322266, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.834295272827148, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1964/4000 [18:45<16:20,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.753473281860352, Predicted Probability: 0.9915, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7341837882995605, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1965/4000 [18:45<18:52,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5970299243927002, Predicted Probability: 0.1684, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.09957394003868103, Predicted Probability: 0.5249, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1966/4000 [18:46<17:08,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.396368980407715, Predicted Probability: 0.0122, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.388110637664795, Predicted Probability: 0.0327, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1967/4000 [18:46<14:06,  2.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3689165115356445, Predicted Probability: 0.0125, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.72831392288208, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1968/4000 [18:47<17:14,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3061123192310333, Predicted Probability: 0.5759, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6735270023345947, Predicted Probability: 0.3377, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1969/4000 [18:47<15:45,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5207958221435547, Predicted Probability: 0.9713, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9787938594818115, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1970/4000 [18:48<18:28,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3801188468933105, Predicted Probability: 0.0124, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1651549339294434, Predicted Probability: 0.8971, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1971/4000 [18:48<19:04,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3473565578460693, Predicted Probability: 0.9127, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.143195390701294, Predicted Probability: 0.8950, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1972/4000 [18:49<20:56,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5911192893981934, Predicted Probability: 0.9303, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4977903366088867, Predicted Probability: 0.1828, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1973/4000 [18:50<18:35,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.017906665802002, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6245830059051514, Predicted Probability: 0.9740, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1974/4000 [18:50<17:43,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.595928192138672, Predicted Probability: 0.9900, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.866184711456299, Predicted Probability: 0.9924, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1975/4000 [18:50<16:19,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.887967586517334, Predicted Probability: 0.0528, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.056764125823975, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1976/4000 [18:51<19:41,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.446455955505371, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.483521461486816, Predicted Probability: 0.0112, Prediction: 0.0

Epoch 1/3:  49%|████▉     | 1977/4000 [18:52<17:42,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5866384506225586, Predicted Probability: 0.1699, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9955661296844482, Predicted Probability: 0.9819, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1978/4000 [18:52<17:59,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6079719066619873, Predicted Probability: 0.9736, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9318971633911133, Predicted Probability: 0.7175, Prediction: 1.0

Epoch 1/3:  49%|████▉     | 1979/4000 [18:52<16:20,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4513068199157715, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.9454450607299805, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1980/4000 [18:53<16:06,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.793003559112549, Predicted Probability: 0.9780, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.010185718536377, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1981/4000 [18:53<14:55,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.291667938232422, Predicted Probability: 0.9865, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.684176445007324, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1982/4000 [18:54<17:48,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.602236747741699, Predicted Probability: 0.9310, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.829168319702148, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1983/4000 [18:55<18:01,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.751745223999023, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5108635425567627, Predicted Probability: 0.0751, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1984/4000 [18:55<20:23,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.7985382080078125, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.258482456207275, Predicted Probability: 0.9861, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1985/4000 [18:56<16:18,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.38566780090332, Predicted Probability: 0.9877, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.240108489990234, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1986/4000 [18:56<17:01,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9071452617645264, Predicted Probability: 0.9803, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.269554615020752, Predicted Probability: 0.9634, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1987/4000 [18:57<19:24,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5293731689453125, Predicted Probability: 0.0107, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1743239164352417, Predicted Probability: 0.2361, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1988/4000 [18:58<20:57,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.43246155977249146, Predicted Probability: 0.3935, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.039463043212891, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1989/4000 [18:58<18:24,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6583023071289062, Predicted Probability: 0.9749, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7999701499938965, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1990/4000 [18:59<21:36,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4417543411254883, Predicted Probability: 0.0800, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.358306884765625, Predicted Probability: 0.0126, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1991/4000 [18:59<20:47,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.558767318725586, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6271519660949707, Predicted Probability: 0.9326, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1992/4000 [19:00<16:37,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.659793853759766, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5745320320129395, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1993/4000 [19:00<19:03,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9627058506011963, Predicted Probability: 0.9509, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.92638635635376, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1994/4000 [19:01<18:48,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6188087463378906, Predicted Probability: 0.9321, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.002741813659668, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1995/4000 [19:02<21:00,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1780145168304443, Predicted Probability: 0.1017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6748875379562378, Predicted Probability: 0.1578, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1996/4000 [19:02<22:27,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.613353729248047, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.008627891540527, Predicted Probability: 0.9822, Prediction: 1.0

Epoch 1/3:  50%|████▉     | 1997/4000 [19:03<22:57,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9583628177642822, Predicted Probability: 0.8764, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.77211856842041, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1998/4000 [19:04<19:55,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.935500621795654, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.973379373550415, Predicted Probability: 0.0185, Prediction: 0.0

Epoch 1/3:  50%|████▉     | 1999/4000 [19:04<21:18,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1944918632507324, Predicted Probability: 0.1002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9517815113067627, Predicted Probability: 0.0189, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2000/4000 [19:05<18:43,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3058550357818604, Predicted Probability: 0.0354, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.124984622001648, Predicted Probability: 0.7549, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2001/4000 [19:05<16:55,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1258039474487305, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.606534004211426, Predicted Probability: 0.0099, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2002/4000 [19:05<15:36,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.297476291656494, Predicted Probability: 0.0134, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.347461223602295, Predicted Probability: 0.0128, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2003/4000 [19:06<19:06,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9410165548324585, Predicted Probability: 0.8745, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.387606620788574, Predicted Probability: 0.0123, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2004/4000 [19:07<17:24,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.996346950531006, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.601353645324707, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2005/4000 [19:07<20:11,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.35475218296051025, Predicted Probability: 0.4122, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.965639591217041, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2006/4000 [19:08<23:12,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.201384544372559, Predicted Probability: 0.0148, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.191728591918945, Predicted Probability: 0.0149, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2007/4000 [19:09<18:20,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.650238037109375, Predicted Probability: 0.9905, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.126171588897705, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2008/4000 [19:09<20:23,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.273270130157471, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9923887252807617, Predicted Probability: 0.8800, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2009/4000 [19:10<21:30,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9403126239776611, Predicted Probability: 0.8744, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.890952110290527, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2010/4000 [19:11<20:31,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7980690002441406, Predicted Probability: 0.9426, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.622922420501709, Predicted Probability: 0.0260, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2011/4000 [19:11<18:14,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.25034359097480774, Predicted Probability: 0.4377, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6678335666656494, Predicted Probability: 0.9751, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2012/4000 [19:11<14:47,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.561548948287964, Predicted Probability: 0.0717, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.505613803863525, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2013/4000 [19:12<17:50,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.427189350128174, Predicted Probability: 0.0315, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.870260238647461, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2014/4000 [19:13<18:44,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.918437957763672, Predicted Probability: 0.9805, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8208768367767334, Predicted Probability: 0.0214, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2015/4000 [19:13<20:18,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.372920036315918, Predicted Probability: 0.0332, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.2461600303649902, Predicted Probability: 0.7766, Prediction: 1.0

Epoch 1/3:  50%|█████     | 2016/4000 [19:14<21:57,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.019399166107178, Predicted Probability: 0.0066, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.160181999206543, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2017/4000 [19:15<23:43,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.016334533691406, Predicted Probability: 0.0066, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.586193561553955, Predicted Probability: 0.0270, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2018/4000 [19:15<20:22,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.924727439880371, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1714189052581787, Predicted Probability: 0.1023, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2019/4000 [19:16<21:49,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8279873132705688, Predicted Probability: 0.3041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.105515956878662, Predicted Probability: 0.0162, Prediction: 0.0

Epoch 1/3:  50%|█████     | 2020/4000 [19:16<17:18,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.141847133636475, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.700963020324707, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2021/4000 [19:17<19:50,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9481287002563477, Predicted Probability: 0.0498, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8308329582214355, Predicted Probability: 0.0212, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2022/4000 [19:17<15:55,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.258666515350342, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.488534450531006, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2023/4000 [19:18<14:52,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.499370098114014, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0496737957000732, Predicted Probability: 0.9548, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2024/4000 [19:18<15:42,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2720866203308105, Predicted Probability: 0.0138, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0310161113739014, Predicted Probability: 0.9540, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2025/4000 [19:19<14:50,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8794662952423096, Predicted Probability: 0.9798, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3969917297363281, Predicted Probability: 0.8017, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2026/4000 [19:19<17:32,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.026793003082275, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5045641660690308, Predicted Probability: 0.8183, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2027/4000 [19:20<20:16,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.072695255279541, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7161813974380493, Predicted Probability: 0.6718, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2028/4000 [19:21<17:48,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.1256121397018433, Predicted Probability: 0.7550, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7645416259765625, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2029/4000 [19:21<20:06,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.234052658081055, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.668529987335205, Predicted Probability: 0.8414, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2030/4000 [19:21<16:03,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.515523910522461, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.293269634246826, Predicted Probability: 0.0135, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2031/4000 [19:22<13:13,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.367114543914795, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6522650718688965, Predicted Probability: 0.9906, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2032/4000 [19:22<13:37,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.505232810974121, Predicted Probability: 0.9891, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.083239793777466, Predicted Probability: 0.9562, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2033/4000 [19:22<12:08,  2.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.893191337585449, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5135838985443115, Predicted Probability: 0.0289, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2034/4000 [19:23<12:07,  2.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4415202140808105, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.237250328063965, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2035/4000 [19:23<12:56,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.658205986022949, Predicted Probability: 0.9906, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.149787902832031, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2037/4000 [19:24<11:01,  2.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5172953605651855, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.544553756713867, Predicted Probability: 0.9895, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.029680252075195, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.54202127456665, Predicted Probability: 0.9895, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2038/4000 [19:25<14:39,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9842604398727417, Predicted Probability: 0.8791, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.051166534423828, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2039/4000 [19:25<15:32,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9073097705841064, Predicted Probability: 0.2876, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5618205070495605, Predicted Probability: 0.9897, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2040/4000 [19:26<18:29,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.579192876815796, Predicted Probability: 0.9295, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.3883056640625, Predicted Probability: 0.0123, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2041/4000 [19:26<16:39,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.843281269073486, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0805537700653076, Predicted Probability: 0.9561, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2042/4000 [19:27<18:42,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0186872482299805, Predicted Probability: 0.0066, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5723782777786255, Predicted Probability: 0.3607, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2043/4000 [19:28<20:59,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.464907646179199, Predicted Probability: 0.0114, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.28999215364456177, Predicted Probability: 0.4280, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2044/4000 [19:28<18:19,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.709796905517578, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8864729404449463, Predicted Probability: 0.9799, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2045/4000 [19:29<18:16,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.776386260986328, Predicted Probability: 0.9414, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.176084518432617, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2046/4000 [19:29<14:46,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4424943923950195, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7956299781799316, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 1/3:  51%|█████     | 2047/4000 [19:30<17:38,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.37524765729904175, Predicted Probability: 0.4073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.268411636352539, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2048/4000 [19:30<20:06,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.859865188598633, Predicted Probability: 0.9923, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.8095626831054688, Predicted Probability: 0.0568, Prediction: 0.0

Epoch 1/3:  51%|█████     | 2049/4000 [19:31<22:03,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.327480316162109, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.043052673339844, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2050/4000 [19:32<20:44,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.092161178588867, Predicted Probability: 0.0164, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5539708137512207, Predicted Probability: 0.1745, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2051/4000 [19:32<16:30,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7342536449432373, Predicted Probability: 0.9390, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.917069911956787, Predicted Probability: 0.0195, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2052/4000 [19:33<19:02,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6176018714904785, Predicted Probability: 0.9320, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.364242076873779, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2053/4000 [19:34<21:26,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.284716606140137, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.788187503814697, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2054/4000 [19:34<22:35,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0606489181518555, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2235097885131836, Predicted Probability: 0.9617, Prediction: 1.0

Epoch 1/3:  51%|█████▏    | 2055/4000 [19:35<22:44,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8177887201309204, Predicted Probability: 0.3062, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7649041414260864, Predicted Probability: 0.3176, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2056/4000 [19:35<17:54,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.618997573852539, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.084403038024902, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2057/4000 [19:36<16:25,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.902647972106934, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6812196969985962, Predicted Probability: 0.6640, Prediction: 1.0

Epoch 1/3:  51%|█████▏    | 2058/4000 [19:36<15:06,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.831678867340088, Predicted Probability: 0.9921, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.260307788848877, Predicted Probability: 0.0945, Prediction: 0.0

Epoch 1/3:  51%|█████▏    | 2059/4000 [19:36<14:09,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3961989879608154, Predicted Probability: 0.9676, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0678253173828125, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2060/4000 [19:37<16:59,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3480291962623596, Predicted Probability: 0.5861, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.733875274658203, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2061/4000 [19:38<15:28,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7608354091644287, Predicted Probability: 0.9773, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.41365355253219604, Predicted Probability: 0.6020, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2062/4000 [19:38<18:13,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.27248477935791, Predicted Probability: 0.0138, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.49571824073791504, Predicted Probability: 0.3785, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2063/4000 [19:39<20:10,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3998371362686157, Predicted Probability: 0.1978, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5449731945991516, Predicted Probability: 0.3670, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2064/4000 [19:40<21:23,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8110337257385254, Predicted Probability: 0.8595, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.126033782958984, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2065/4000 [19:41<21:59,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.109740734100342, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.021472454071045, Predicted Probability: 0.1170, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2066/4000 [19:41<17:22,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5772247314453125, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6042680740356445, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2067/4000 [19:41<19:11,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.63924241065979, Predicted Probability: 0.8374, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.796547889709473, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2068/4000 [19:42<17:01,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.29542654752731323, Predicted Probability: 0.4267, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.367431879043579, Predicted Probability: 0.9667, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2069/4000 [19:42<17:17,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.788765907287598, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7965471744537354, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2070/4000 [19:43<14:05,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.9640860557556152, Predicted Probability: 0.0491, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3061981201171875, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2071/4000 [19:43<15:06,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2382547855377197, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4376108646392822, Predicted Probability: 0.8081, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2072/4000 [19:44<17:40,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7060550451278687, Predicted Probability: 0.8463, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.138157367706299, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2073/4000 [19:44<15:54,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.258721351623535, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.19539475440979, Predicted Probability: 0.9607, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2074/4000 [19:44<13:04,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.205068588256836, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.218034744262695, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2075/4000 [19:45<14:17,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9542131423950195, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5289547443389893, Predicted Probability: 0.9261, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2076/4000 [19:46<17:00,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.593664288520813, Predicted Probability: 0.1689, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.19006529450416565, Predicted Probability: 0.4526, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2077/4000 [19:46<18:51,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.215611457824707, Predicted Probability: 0.0145, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6868324279785156, Predicted Probability: 0.8438, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2078/4000 [19:47<20:25,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.276104688644409, Predicted Probability: 0.0364, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.962937355041504, Predicted Probability: 0.0491, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2079/4000 [19:48<21:31,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6420438289642334, Predicted Probability: 0.3448, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.109707832336426, Predicted Probability: 0.8918, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2080/4000 [19:49<20:23,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.657136917114258, Predicted Probability: 0.9748, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.217597961425781, Predicted Probability: 0.9855, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2081/4000 [19:49<21:27,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.214415550231934, Predicted Probability: 0.0146, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1620569229125977, Predicted Probability: 0.8968, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2082/4000 [19:50<20:15,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1659810543060303, Predicted Probability: 0.8972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.701757431030273, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2083/4000 [19:50<19:21,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.939420223236084, Predicted Probability: 0.9498, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7925059795379639, Predicted Probability: 0.3116, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2084/4000 [19:51<18:52,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.52455997467041, Predicted Probability: 0.0107, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.599463939666748, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2085/4000 [19:51<18:20,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.141977310180664, Predicted Probability: 0.9586, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3322079181671143, Predicted Probability: 0.9115, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2086/4000 [19:52<19:50,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6602015495300293, Predicted Probability: 0.8403, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.886157989501953, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2087/4000 [19:52<15:51,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.6631972789764404, Predicted Probability: 0.1593, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2033467292785645, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2088/4000 [19:53<16:26,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.643076419830322, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5482258796691895, Predicted Probability: 0.9720, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2089/4000 [19:54<18:51,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8098070621490479, Predicted Probability: 0.8593, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.786046028137207, Predicted Probability: 0.0222, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2090/4000 [19:54<20:20,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3483821153640747, Predicted Probability: 0.2061, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.095277309417725, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2091/4000 [19:55<22:06,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.736785888671875, Predicted Probability: 0.9767, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9842021465301514, Predicted Probability: 0.0183, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2092/4000 [19:56<22:45,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.53033447265625, Predicted Probability: 0.0107, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9069128036499023, Predicted Probability: 0.8707, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2093/4000 [19:57<23:30,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.907337665557861, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5901288986206055, Predicted Probability: 0.0100, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2094/4000 [19:58<23:32,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.574295997619629, Predicted Probability: 0.9292, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.47210168838501, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 1/3:  52%|█████▏    | 2095/4000 [19:58<20:12,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.173471689224243, Predicted Probability: 0.9598, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.087401866912842, Predicted Probability: 0.9564, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2096/4000 [19:58<17:40,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.480292320251465, Predicted Probability: 0.9701, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1866397857666016, Predicted Probability: 0.8990, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2097/4000 [19:59<14:57,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.16740608215332, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 3.7355499267578125, Predicted Probability: 0.9767, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2098/4000 [19:59<15:45,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.867714881896973, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.235555648803711, Predicted Probability: 0.9857, Prediction: 1.0

Epoch 1/3:  52%|█████▏    | 2099/4000 [20:00<14:36,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2060065269470215, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.266096353530884, Predicted Probability: 0.9632, Prediction: 1.0

Epoch 1/3:  52%|█████▎    | 2100/4000 [20:00<13:54,  2.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2793073654174805, Predicted Probability: 0.0137, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.278833866119385, Predicted Probability: 0.9863, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2101/4000 [20:01<16:29,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7716224193572998, Predicted Probability: 0.8547, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.580223798751831, Predicted Probability: 0.9729, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2102/4000 [20:01<15:51,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.825024127960205, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0449917316436768, Predicted Probability: 0.0454, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2103/4000 [20:02<16:07,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7657856941223145, Predicted Probability: 0.9408, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.190398693084717, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2104/4000 [20:02<18:03,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6829216480255127, Predicted Probability: 0.0640, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.33580636978149414, Predicted Probability: 0.5832, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2105/4000 [20:03<19:54,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.307352066040039, Predicted Probability: 0.0133, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.188016414642334, Predicted Probability: 0.1008, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2106/4000 [20:04<17:28,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.222142219543457, Predicted Probability: 0.9855, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.188607215881348, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2107/4000 [20:04<15:48,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.814484119415283, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5078206062316895, Predicted Probability: 0.9709, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2108/4000 [20:04<14:41,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6026268005371094, Predicted Probability: 0.0265, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.281791687011719, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2109/4000 [20:05<14:23,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.069334030151367, Predicted Probability: 0.0168, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.037312626838684, Predicted Probability: 0.2617, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2110/4000 [20:05<17:23,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3914830684661865, Predicted Probability: 0.9162, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.100419998168945, Predicted Probability: 0.0163, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2111/4000 [20:06<17:19,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1911345720291138, Predicted Probability: 0.7669, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9555993676185608, Predicted Probability: 0.2778, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2112/4000 [20:07<19:09,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.12019455432891846, Predicted Probability: 0.5300, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.749734401702881, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2113/4000 [20:07<16:56,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2630295753479, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.704174757003784, Predicted Probability: 0.9760, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2114/4000 [20:08<19:30,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.827759742736816, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.747185707092285, Predicted Probability: 0.9398, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2115/4000 [20:08<15:37,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.435882568359375, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.476323127746582, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2116/4000 [20:09<17:43,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3051238059997559, Predicted Probability: 0.7867, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.910182952880859, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2117/4000 [20:09<14:24,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.685114622116089, Predicted Probability: 0.9361, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.4525930881500244, Predicted Probability: 0.0307, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2119/4000 [20:10<13:57,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.190698623657227, Predicted Probability: 0.0149, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7663311958312988, Predicted Probability: 0.8540, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -1.940763235092163, Predicted Probability: 0.1256, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7315788269042969, Predicted Probability: 0.8496, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2120/4000 [20:11<17:04,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.00979471206665, Predicted Probability: 0.0178, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.811070442199707, Predicted Probability: 0.9433, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2121/4000 [20:11<15:25,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5669732093811035, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8700170516967773, Predicted Probability: 0.0204, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2122/4000 [20:12<18:26,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.780820846557617, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.0197296142578125, Predicted Probability: 0.0176, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2123/4000 [20:13<19:48,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9277679920196533, Predicted Probability: 0.8730, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.814428329467773, Predicted Probability: 0.0080, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2124/4000 [20:13<19:07,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.710904836654663, Predicted Probability: 0.9761, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6167116165161133, Predicted Probability: 0.9319, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2125/4000 [20:14<20:15,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0388753414154053, Predicted Probability: 0.0457, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8114452362060547, Predicted Probability: 0.8595, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2126/4000 [20:14<16:09,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7026002407073975, Predicted Probability: 0.9372, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.7627888917922974, Predicted Probability: 0.1464, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2127/4000 [20:15<18:33,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8937506675720215, Predicted Probability: 0.0200, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.792807102203369, Predicted Probability: 0.9423, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2128/4000 [20:16<20:12,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.71028995513916, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4330503940582275, Predicted Probability: 0.0807, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2129/4000 [20:17<20:52,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8652211427688599, Predicted Probability: 0.8659, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2517776489257812, Predicted Probability: 0.0373, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2130/4000 [20:17<21:25,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.565009117126465, Predicted Probability: 0.0275, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.711787462234497, Predicted Probability: 0.8471, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2131/4000 [20:18<22:03,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8782248497009277, Predicted Probability: 0.0203, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.271261990070343, Predicted Probability: 0.5674, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2132/4000 [20:19<20:39,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.104529857635498, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7778141498565674, Predicted Probability: 0.8554, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2133/4000 [20:19<21:24,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7222554683685303, Predicted Probability: 0.8484, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.987519264221191, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2134/4000 [20:20<22:08,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.394826650619507, Predicted Probability: 0.9675, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.811281681060791, Predicted Probability: 0.0216, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2135/4000 [20:20<18:58,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2205092906951904, Predicted Probability: 0.9616, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.083359718322754, Predicted Probability: 0.0166, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2136/4000 [20:21<16:42,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.347009658813477, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.495143413543701, Predicted Probability: 0.0110, Prediction: 0.0

Epoch 1/3:  53%|█████▎    | 2137/4000 [20:21<16:52,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.141402244567871, Predicted Probability: 0.9843, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.105080604553223, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2138/4000 [20:22<15:15,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7094642519950867, Predicted Probability: 0.6703, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.481170654296875, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 1/3:  53%|█████▎    | 2139/4000 [20:22<17:26,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.809031367301941, Predicted Probability: 0.1408, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.213007926940918, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2140/4000 [20:23<15:36,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.210764408111572, Predicted Probability: 0.9854, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.470304012298584, Predicted Probability: 0.0780, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2141/4000 [20:24<17:37,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.754732608795166, Predicted Probability: 0.8525, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.847892761230469, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2142/4000 [20:24<20:00,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.469642162322998, Predicted Probability: 0.0113, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.069681167602539, Predicted Probability: 0.0168, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2143/4000 [20:25<19:12,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.23290491104126, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.792774677276611, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 1/3:  54%|█████▎    | 2144/4000 [20:25<15:21,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3087595999240875, Predicted Probability: 0.4234, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9800803661346436, Predicted Probability: 0.8787, Prediction: 1.0

Epoch 1/3:  54%|█████▎    | 2145/4000 [20:26<18:09,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.481898546218872, Predicted Probability: 0.0771, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.892703056335449, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2146/4000 [20:26<16:10,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.740016460418701, Predicted Probability: 0.9768, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.285956382751465, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 1/3:  54%|█████▎    | 2147/4000 [20:27<18:03,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.1409735083580017, Predicted Probability: 0.4648, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.261836051940918, Predicted Probability: 0.0943, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2148/4000 [20:27<16:04,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.447128772735596, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7053449153900146, Predicted Probability: 0.0627, Prediction: 0.0

Epoch 1/3:  54%|█████▎    | 2149/4000 [20:28<18:10,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.363880157470703, Predicted Probability: 0.0126, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.909733772277832, Predicted Probability: 0.8710, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2150/4000 [20:29<20:09,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8277735710144043, Predicted Probability: 0.0213, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6411356925964355, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2151/4000 [20:30<21:01,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.584929466247559, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9617892503738403, Predicted Probability: 0.8767, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2153/4000 [20:30<14:28,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.596784830093384, Predicted Probability: 0.9733, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.002561569213867, Predicted Probability: 0.0067, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -1.2928203344345093, Predicted Probability: 0.2154, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.560194730758667, Predicted Probability: 0.0717, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2154/4000 [20:31<13:37,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.705319881439209, Predicted Probability: 0.0627, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.785097599029541, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2155/4000 [20:31<11:25,  2.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1798694133758545, Predicted Probability: 0.1016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.528669357299805, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2156/4000 [20:32<15:09,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.039588451385498, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8983027935028076, Predicted Probability: 0.9478, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2157/4000 [20:32<15:41,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.236292839050293, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4774186611175537, Predicted Probability: 0.9225, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2158/4000 [20:33<18:01,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.948338747024536, Predicted Probability: 0.0189, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6001535654067993, Predicted Probability: 0.3543, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2159/4000 [20:33<15:03,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.289287567138672, Predicted Probability: 0.0359, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.582958221435547, Predicted Probability: 0.9730, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2160/4000 [20:34<13:54,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3340322971343994, Predicted Probability: 0.9656, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.811619758605957, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2162/4000 [20:34<10:21,  2.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.557933330535889, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.566349029541016, Predicted Probability: 0.9897, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 3.9443185329437256, Predicted Probability: 0.9810, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.764415740966797, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2163/4000 [20:35<14:01,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.319647789001465, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1151108741760254, Predicted Probability: 0.1076, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2164/4000 [20:36<16:42,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0442123413085938, Predicted Probability: 0.8854, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.655172824859619, Predicted Probability: 0.0252, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2165/4000 [20:36<15:04,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5308070182800293, Predicted Probability: 0.9716, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.924746036529541, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2166/4000 [20:37<17:32,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4647064208984375, Predicted Probability: 0.1877, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.406292200088501, Predicted Probability: 0.0321, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2167/4000 [20:37<18:57,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.036684274673462, Predicted Probability: 0.9542, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.3182487487792969, Predicted Probability: 0.2111, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2168/4000 [20:38<16:36,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0391547679901123, Predicted Probability: 0.0457, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2143449783325195, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2169/4000 [20:39<19:01,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9783499836921692, Predicted Probability: 0.7268, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.987044334411621, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2170/4000 [20:39<16:46,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.718316078186035, Predicted Probability: 0.9763, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.170518636703491, Predicted Probability: 0.9597, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2171/4000 [20:40<19:01,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.785181045532227, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.114454746246338, Predicted Probability: 0.1077, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2173/4000 [20:40<13:35,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.297653675079346, Predicted Probability: 0.9866, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.340000629425049, Predicted Probability: 0.9952, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.192243576049805, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.539003372192383, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2174/4000 [20:41<12:51,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9543673992156982, Predicted Probability: 0.9812, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.693373203277588, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2175/4000 [20:42<16:15,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.567882061004639, Predicted Probability: 0.0103, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.880699157714844, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2176/4000 [20:42<14:51,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4963955879211426, Predicted Probability: 0.9706, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.376614570617676, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2177/4000 [20:43<16:57,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.801393985748291, Predicted Probability: 0.8583, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.917304992675781, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  54%|█████▍    | 2178/4000 [20:43<18:34,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.761713027954102, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.914079189300537, Predicted Probability: 0.9485, Prediction: 1.0

Epoch 1/3:  54%|█████▍    | 2179/4000 [20:44<16:27,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.747056007385254, Predicted Probability: 0.0086, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.1183903217315674, Predicted Probability: 0.8927, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2180/4000 [20:45<18:31,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.184730291366577, Predicted Probability: 0.0397, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9802188873291016, Predicted Probability: 0.9517, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2181/4000 [20:45<14:48,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3125016689300537, Predicted Probability: 0.9099, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.948132038116455, Predicted Probability: 0.0498, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2182/4000 [20:45<15:13,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1636962890625, Predicted Probability: 0.0153, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.007479667663574, Predicted Probability: 0.9529, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2183/4000 [20:46<17:20,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.458555221557617, Predicted Probability: 0.9212, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8257293701171875, Predicted Probability: 0.0080, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2184/4000 [20:47<19:03,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9684264659881592, Predicted Probability: 0.8774, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2198896408081055, Predicted Probability: 0.0145, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2185/4000 [20:47<16:34,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.348428249359131, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.112478256225586, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2186/4000 [20:47<13:29,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.398712635040283, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.4603724479675293, Predicted Probability: 0.8116, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2187/4000 [20:48<16:04,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1592535972595215, Predicted Probability: 0.7612, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.776727557182312, Predicted Probability: 0.3150, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2188/4000 [20:49<18:03,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.695061445236206, Predicted Probability: 0.0242, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.714465379714966, Predicted Probability: 0.0621, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2189/4000 [20:50<19:20,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8800567388534546, Predicted Probability: 0.7068, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.422106742858887, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2190/4000 [20:50<18:28,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.392362117767334, Predicted Probability: 0.9162, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.963724374771118, Predicted Probability: 0.9814, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2191/4000 [20:51<17:01,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3789559602737427, Predicted Probability: 0.7988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.965300559997559, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2192/4000 [20:51<19:15,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.446295738220215, Predicted Probability: 0.9691, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.475170135498047, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2193/4000 [20:52<20:01,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2694288492202759, Predicted Probability: 0.7806, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.699704170227051, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2194/4000 [20:53<18:55,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.433134078979492, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3759310245513916, Predicted Probability: 0.9150, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2195/4000 [20:53<19:58,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0399065017700195, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.18357226252555847, Predicted Probability: 0.5458, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2196/4000 [20:54<21:37,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8752529621124268, Predicted Probability: 0.0203, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.947979211807251, Predicted Probability: 0.1248, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2197/4000 [20:54<16:58,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.457895278930664, Predicted Probability: 0.9885, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.71794056892395, Predicted Probability: 0.9763, Prediction: 1.0

Epoch 1/3:  55%|█████▍    | 2198/4000 [20:55<19:05,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.871690273284912, Predicted Probability: 0.9464, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.581676483154297, Predicted Probability: 0.0101, Prediction: 0.0

Epoch 1/3:  55%|█████▍    | 2199/4000 [20:56<16:49,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4577713012695312, Predicted Probability: 0.9695, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.757375717163086, Predicted Probability: 0.9772, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2200/4000 [20:56<16:37,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.027452047914266586, Predicted Probability: 0.5069, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.4720567464828491, Predicted Probability: 0.1866, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2201/4000 [20:57<18:36,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.841961860656738, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.736220121383667, Predicted Probability: 0.8502, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2202/4000 [20:58<19:35,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.343197822570801, Predicted Probability: 0.9124, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.46791934967041, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2203/4000 [20:58<17:11,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.978438854217529, Predicted Probability: 0.9932, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.53627347946167, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2204/4000 [20:58<15:19,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.016339769586920738, Predicted Probability: 0.4959, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.906422138214111, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2205/4000 [20:59<14:00,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.406094551086426, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.645859718322754, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2206/4000 [21:00<16:34,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.934505462646484, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1714234352111816, Predicted Probability: 0.8977, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2207/4000 [21:00<16:36,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.35763692855835, Predicted Probability: 0.9874, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.58513069152832, Predicted Probability: 0.0101, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2208/4000 [21:01<18:17,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.610834002494812, Predicted Probability: 0.3519, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0402278900146484, Predicted Probability: 0.1150, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2209/4000 [21:02<19:24,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.615997552871704, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7945592403411865, Predicted Probability: 0.1425, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2210/4000 [21:02<16:55,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.073258876800537, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.105100631713867, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2211/4000 [21:02<14:14,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.508337020874023, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.07162618637085, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2212/4000 [21:03<16:37,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.86324405670166, Predicted Probability: 0.0077, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.688781976699829, Predicted Probability: 0.9364, Prediction: 1.0

Epoch 1/3:  55%|█████▌    | 2213/4000 [21:04<18:56,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7905373573303223, Predicted Probability: 0.1430, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.070030212402344, Predicted Probability: 0.0168, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2214/4000 [21:05<20:20,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2452080249786377, Predicted Probability: 0.0375, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6617122292518616, Predicted Probability: 0.3404, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2215/4000 [21:05<20:56,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0430145263671875, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.023932933807373, Predicted Probability: 0.2643, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2216/4000 [21:06<21:48,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4151231050491333, Predicted Probability: 0.8046, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2144384384155273, Predicted Probability: 0.0386, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2217/4000 [21:07<18:34,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.756978988647461, Predicted Probability: 0.9772, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.934397578239441, Predicted Probability: 0.1263, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2218/4000 [21:07<19:42,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5977063179016113, Predicted Probability: 0.1683, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.183231830596924, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 1/3:  55%|█████▌    | 2219/4000 [21:08<21:20,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.970921516418457, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.085854530334473, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2220/4000 [21:09<21:42,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.4613889455795288, Predicted Probability: 0.3867, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.967967510223389, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2221/4000 [21:10<21:46,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0466301441192627, Predicted Probability: 0.1144, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.184592247009277, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2222/4000 [21:10<22:14,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3292462825775146, Predicted Probability: 0.9113, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.054266929626465, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2223/4000 [21:11<20:22,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6476991176605225, Predicted Probability: 0.6565, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7369766235351562, Predicted Probability: 0.9392, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2224/4000 [21:11<17:40,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.640361785888672, Predicted Probability: 0.9334, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.874526500701904, Predicted Probability: 0.9924, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2225/4000 [21:12<14:12,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9862782955169678, Predicted Probability: 0.0182, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.536296367645264, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2226/4000 [21:12<13:14,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.639960289001465, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.029267702251672745, Predicted Probability: 0.5073, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2227/4000 [21:13<15:45,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.501739740371704, Predicted Probability: 0.1822, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.081934928894043, Predicted Probability: 0.0166, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2228/4000 [21:13<14:27,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.271154880523682, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.549273729324341, Predicted Probability: 0.9275, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2229/4000 [21:13<14:06,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.057332992553711, Predicted Probability: 0.0170, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5510454177856445, Predicted Probability: 0.9896, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2230/4000 [21:14<16:12,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8090766668319702, Predicted Probability: 0.3081, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.864333152770996, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2231/4000 [21:15<18:28,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9147326946258545, Predicted Probability: 0.8715, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.147530555725098, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2232/4000 [21:16<20:18,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.94504976272583, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.037989616394043, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2233/4000 [21:17<20:57,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3793718814849854, Predicted Probability: 0.9152, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.862306594848633, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2234/4000 [21:17<16:30,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.12385927885770798, Predicted Probability: 0.4691, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.358053207397461, Predicted Probability: 0.9874, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2235/4000 [21:17<14:53,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2796893119812012, Predicted Probability: 0.2176, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.003237724304199, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2236/4000 [21:18<16:59,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3268165588378906, Predicted Probability: 0.9111, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.570374488830566, Predicted Probability: 0.0102, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2237/4000 [21:19<18:24,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9356032609939575, Predicted Probability: 0.8739, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.895237445831299, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2238/4000 [21:19<14:43,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.248209476470947, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.190573692321777, Predicted Probability: 0.0149, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2239/4000 [21:20<16:53,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4690505266189575, Predicted Probability: 0.8129, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.609285354614258, Predicted Probability: 0.0099, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2240/4000 [21:20<14:59,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4669907093048096, Predicted Probability: 0.9218, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.645202159881592, Predicted Probability: 0.9745, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2241/4000 [21:20<13:45,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6137471199035645, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.123703956604004, Predicted Probability: 0.9841, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2242/4000 [21:21<16:14,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3606719970703125, Predicted Probability: 0.0126, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1442660093307495, Predicted Probability: 0.4640, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2243/4000 [21:22<17:44,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7842702865600586, Predicted Probability: 0.8562, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7520880699157715, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2244/4000 [21:23<19:22,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.4380345344543457, Predicted Probability: 0.0311, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.17577862739563, Predicted Probability: 0.0401, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2245/4000 [21:23<16:57,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9798271656036377, Predicted Probability: 0.0183, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.622580528259277, Predicted Probability: 0.0097, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2246/4000 [21:24<19:14,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2792937755584717, Predicted Probability: 0.0363, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.860606670379639, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2247/4000 [21:24<15:16,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.87708044052124, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.755043983459473, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 1/3:  56%|█████▌    | 2248/4000 [21:25<17:32,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.747345447540283, Predicted Probability: 0.0086, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.343604326248169, Predicted Probability: 0.0341, Prediction: 0.0

Epoch 1/3:  56%|█████▌    | 2249/4000 [21:25<14:04,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5594446659088135, Predicted Probability: 0.1737, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.909665107727051, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  56%|█████▋    | 2250/4000 [21:25<13:12,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.618950843811035, Predicted Probability: 0.9739, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.314743995666504, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 1/3:  56%|█████▋    | 2251/4000 [21:26<15:49,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0665576457977295, Predicted Probability: 0.2561, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.969738483428955, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 1/3:  56%|█████▋    | 2252/4000 [21:27<17:43,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1614843606948853, Predicted Probability: 0.2384, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.580819606781006, Predicted Probability: 0.0271, Prediction: 0.0

Epoch 1/3:  56%|█████▋    | 2253/4000 [21:27<14:14,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.55858850479126, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.247624397277832, Predicted Probability: 0.9859, Prediction: 1.0

Epoch 1/3:  56%|█████▋    | 2254/4000 [21:28<13:13,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.428276538848877, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6928191184997559, Predicted Probability: 0.6666, Prediction: 1.0

Epoch 1/3:  56%|█████▋    | 2255/4000 [21:28<13:59,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6632208824157715, Predicted Probability: 0.0652, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7791452407836914, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 1/3:  56%|█████▋    | 2256/4000 [21:29<16:08,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.578287363052368, Predicted Probability: 0.9295, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.630979537963867, Predicted Probability: 0.9903, Prediction: 1.0

Epoch 1/3:  56%|█████▋    | 2257/4000 [21:29<16:03,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3552236557006836, Predicted Probability: 0.9133, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.2275466918945312, Predicted Probability: 0.2266, Prediction: 0.0

Epoch 1/3:  56%|█████▋    | 2258/4000 [21:30<17:31,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2471064329147339, Predicted Probability: 0.5615, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.2300233840942383, Predicted Probability: 0.7738, Prediction: 1.0

Epoch 1/3:  56%|█████▋    | 2259/4000 [21:31<18:43,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.903745651245117, Predicted Probability: 0.9480, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.591270923614502, Predicted Probability: 0.0268, Prediction: 0.0

Epoch 1/3:  56%|█████▋    | 2260/4000 [21:32<19:21,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5253477096557617, Predicted Probability: 0.8213, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.770172119140625, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2261/4000 [21:32<20:12,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.976513385772705, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6943484544754028, Predicted Probability: 0.8448, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2262/4000 [21:33<17:31,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.717371463775635, Predicted Probability: 0.9911, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.250804901123047, Predicted Probability: 0.0373, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2263/4000 [21:34<19:18,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.387646675109863, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7752366065979, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2264/4000 [21:34<19:54,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.485576152801514, Predicted Probability: 0.9889, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.39569354057312, Predicted Probability: 0.9165, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2265/4000 [21:35<18:41,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1654947996139526, Predicted Probability: 0.7623, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.6669002771377563, Predicted Probability: 0.8412, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2267/4000 [21:36<15:18,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6147171258926392, Predicted Probability: 0.8341, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.582211971282959, Predicted Probability: 0.0101, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.922439098358154, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.673408269882202, Predicted Probability: 0.9752, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2268/4000 [21:36<14:35,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.137263059616089, Predicted Probability: 0.0416, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.286098003387451, Predicted Probability: 0.9864, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2269/4000 [21:37<13:22,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.904042720794678, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.152059078216553, Predicted Probability: 0.9845, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2270/4000 [21:37<15:45,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.303196907043457, Predicted Probability: 0.0133, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.353057861328125, Predicted Probability: 0.9132, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2271/4000 [21:38<17:47,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4977552890777588, Predicted Probability: 0.8172, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.661859512329102, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2272/4000 [21:39<17:12,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2184181660413742, Predicted Probability: 0.5544, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7328906059265137, Predicted Probability: 0.9389, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2273/4000 [21:39<18:17,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.820685386657715, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9512445330619812, Predicted Probability: 0.7214, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2274/4000 [21:40<15:58,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8030753135681152, Predicted Probability: 0.9782, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7099695205688477, Predicted Probability: 0.9761, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2275/4000 [21:40<17:26,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6791588068008423, Predicted Probability: 0.6636, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.973025321960449, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2276/4000 [21:41<19:56,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.069255828857422, Predicted Probability: 0.0168, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.204164981842041, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2277/4000 [21:42<17:44,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7437660694122314, Predicted Probability: 0.9396, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.077326774597168, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2278/4000 [21:43<18:36,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3596105575561523, Predicted Probability: 0.9137, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.545165061950684, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2279/4000 [21:43<16:12,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.3649446964263916, Predicted Probability: 0.2034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2411208152771, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2280/4000 [21:43<16:04,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.63667631149292, Predicted Probability: 0.0096, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9848120808601379, Predicted Probability: 0.2719, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2281/4000 [21:44<14:29,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9245026111602783, Predicted Probability: 0.9806, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4315195083618164, Predicted Probability: 0.9687, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2282/4000 [21:44<13:27,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.040874004364014, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.159261226654053, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2283/4000 [21:45<16:43,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.166393756866455, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9367499351501465, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2284/4000 [21:45<13:28,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.423463821411133, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.179966449737549, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2285/4000 [21:46<15:44,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0366291999816895, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4288270473480225, Predicted Probability: 0.8067, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2286/4000 [21:47<17:16,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7685904502868652, Predicted Probability: 0.8543, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.373622894287109, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2287/4000 [21:47<18:31,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0786139965057373, Predicted Probability: 0.1112, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.610410451889038, Predicted Probability: 0.8335, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2288/4000 [21:48<19:10,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.1797340214252472, Predicted Probability: 0.4552, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.037238121032715, Predicted Probability: 0.0173, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2289/4000 [21:49<20:17,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9307637214660645, Predicted Probability: 0.8733, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.827719211578369, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2290/4000 [21:50<20:49,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.737726211547852, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1369247436523438, Predicted Probability: 0.0416, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2291/4000 [21:51<20:50,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5209025144577026, Predicted Probability: 0.8207, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8404741287231445, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2292/4000 [21:51<19:04,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4184048175811768, Predicted Probability: 0.9182, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1231677532196045, Predicted Probability: 0.8931, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2293/4000 [21:51<16:27,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6123855113983154, Predicted Probability: 0.9737, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.080059051513672, Predicted Probability: 0.0166, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2294/4000 [21:52<14:44,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.52577805519104, Predicted Probability: 0.9714, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.549489974975586, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2295/4000 [21:52<13:58,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4012341499328613, Predicted Probability: 0.8024, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.521844863891602, Predicted Probability: 0.9892, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2296/4000 [21:53<16:14,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9427719116210938, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8883070945739746, Predicted Probability: 0.2915, Prediction: 0.0

Epoch 1/3:  57%|█████▋    | 2298/4000 [21:54<11:55,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.895449161529541, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3974661827087402, Predicted Probability: 0.0324, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.778889179229736, Predicted Probability: 0.9917, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.738545894622803, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 1/3:  57%|█████▋    | 2299/4000 [21:54<10:33,  2.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.51365852355957, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.338700532913208, Predicted Probability: 0.0343, Prediction: 0.0

Epoch 1/3:  57%|█████▊    | 2300/4000 [21:55<14:37,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0917463302612305, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.325359344482422, Predicted Probability: 0.0131, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2301/4000 [21:55<14:54,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.051793575286865, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.62042236328125, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2302/4000 [21:56<13:46,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.593735694885254, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3022212982177734, Predicted Probability: 0.9091, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2303/4000 [21:56<16:34,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.70062780380249, Predicted Probability: 0.0090, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1540632247924805, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2304/4000 [21:57<18:12,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8891295194625854, Predicted Probability: 0.8687, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.204120635986328, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2305/4000 [21:58<15:55,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.414060354232788, Predicted Probability: 0.9179, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2848739624023438, Predicted Probability: 0.9639, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2306/4000 [21:58<16:24,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3266966938972473, Predicted Probability: 0.5810, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6865763664245605, Predicted Probability: 0.0638, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2307/4000 [21:59<17:58,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0938870906829834, Predicted Probability: 0.1097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.159285068511963, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2308/4000 [22:00<19:24,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.177508354187012, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.733936309814453, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2309/4000 [22:01<23:16,  1.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.96531081199646, Predicted Probability: 0.9510, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.600705623626709, Predicted Probability: 0.0266, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2310/4000 [22:02<22:17,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.5679595470428467, Predicted Probability: 0.8275, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7677202224731445, Predicted Probability: 0.0591, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2311/4000 [22:02<22:33,  1.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0928566455841064, Predicted Probability: 0.9566, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.165829658508301, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2312/4000 [22:03<21:48,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.23141884803771973, Predicted Probability: 0.5576, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7079250812530518, Predicted Probability: 0.8466, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2313/4000 [22:04<18:22,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.043253421783447, Predicted Probability: 0.0172, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4848268032073975, Predicted Probability: 0.0297, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2314/4000 [22:04<19:16,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.085256576538086, Predicted Probability: 0.9835, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.461373329162598, Predicted Probability: 0.0114, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2315/4000 [22:05<18:07,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.812665939331055, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.390268325805664, Predicted Probability: 0.9161, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2316/4000 [22:05<17:09,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2403287887573242, Predicted Probability: 0.2244, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2659173011779785, Predicted Probability: 0.9862, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2317/4000 [22:06<15:19,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.912269592285156, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.511019706726074, Predicted Probability: 0.9891, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2318/4000 [22:07<17:59,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.70476770401001, Predicted Probability: 0.0090, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.655896186828613, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2319/4000 [22:07<19:24,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.520432472229004, Predicted Probability: 0.0108, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.166994094848633, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2320/4000 [22:08<15:23,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.625051498413086, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.05670428276062, Predicted Probability: 0.0449, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2321/4000 [22:08<17:33,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4082181453704834, Predicted Probability: 0.0825, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.0755462646484375, Predicted Probability: 0.0167, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2322/4000 [22:09<15:27,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.36556339263916, Predicted Probability: 0.9666, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.574082851409912, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2323/4000 [22:09<13:56,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9164137840270996, Predicted Probability: 0.9805, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.61799430847168, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2324/4000 [22:10<12:56,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3725805282592773, Predicted Probability: 0.9668, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.025338172912598, Predicted Probability: 0.9935, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2325/4000 [22:10<15:20,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.842747688293457, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.649353265762329, Predicted Probability: 0.9340, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2326/4000 [22:11<16:58,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.387899398803711, Predicted Probability: 0.0841, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.57473087310791, Predicted Probability: 0.0102, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2327/4000 [22:11<13:40,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.084784984588623, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.9703497886657715, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2328/4000 [22:12<15:32,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.697001934051514, Predicted Probability: 0.0090, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8504199981689453, Predicted Probability: 0.1358, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2329/4000 [22:12<14:28,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6213314533233643, Predicted Probability: 0.9322, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.702600002288818, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2330/4000 [22:13<16:16,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.728005290031433, Predicted Probability: 0.8492, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.515203475952148, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2331/4000 [22:14<18:06,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.661104917526245, Predicted Probability: 0.0653, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9037988185882568, Predicted Probability: 0.1297, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2332/4000 [22:15<18:55,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9543938636779785, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7274820804595947, Predicted Probability: 0.8491, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2333/4000 [22:15<16:19,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3323068618774414, Predicted Probability: 0.9655, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.336196422576904, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2334/4000 [22:16<18:20,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.367384433746338, Predicted Probability: 0.0125, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.861759662628174, Predicted Probability: 0.0541, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2335/4000 [22:16<15:58,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.752557754516602, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3306891918182373, Predicted Probability: 0.9655, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2336/4000 [22:17<17:25,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5162124633789062, Predicted Probability: 0.9253, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.032927513122559, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2337/4000 [22:18<18:56,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6939051151275635, Predicted Probability: 0.9367, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6809630393981934, Predicted Probability: 0.0641, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2338/4000 [22:18<15:29,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.749179363250732, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3733673095703125, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 1/3:  58%|█████▊    | 2339/4000 [22:19<17:11,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.918874740600586, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.542978525161743, Predicted Probability: 0.0281, Prediction: 0.0

Epoch 1/3:  58%|█████▊    | 2340/4000 [22:20<18:09,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.169630527496338, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.719079613685608, Predicted Probability: 0.1520, Prediction: 0.0

Epoch 1/3:  59%|█████▊    | 2341/4000 [22:20<19:05,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.070305109024048, Predicted Probability: 0.9557, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.892848014831543, Predicted Probability: 0.0525, Prediction: 0.0

Epoch 1/3:  59%|█████▊    | 2342/4000 [22:21<15:03,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.103281497955322, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.592611312866211, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2343/4000 [22:21<12:14,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9913766384124756, Predicted Probability: 0.9819, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.398324966430664, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2344/4000 [22:21<11:36,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9800286293029785, Predicted Probability: 0.9817, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.469766139984131, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2345/4000 [22:22<12:32,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8972325325012207, Predicted Probability: 0.9477, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8283369541168213, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2346/4000 [22:22<13:14,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.462310791015625, Predicted Probability: 0.9215, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7659189701080322, Predicted Probability: 0.9408, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2347/4000 [22:23<15:12,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.242334365844727, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5841437578201294, Predicted Probability: 0.6420, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2348/4000 [22:23<13:42,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4764113426208496, Predicted Probability: 0.9700, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5897960662841797, Predicted Probability: 0.9731, Prediction: 1.0

Epoch 1/3:  59%|█████▊    | 2349/4000 [22:24<15:30,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6540298461914062, Predicted Probability: 0.8394, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3767571449279785, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2350/4000 [22:25<16:59,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4260872602462769, Predicted Probability: 0.8063, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.22330379486084, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2351/4000 [22:25<14:58,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.786205530166626, Predicted Probability: 0.9778, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1750030517578125, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2352/4000 [22:26<13:36,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.318497896194458, Predicted Probability: 0.0896, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.684157371520996, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2353/4000 [22:26<16:39,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.034021377563477, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.118588447570801, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2354/4000 [22:27<18:07,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8344879150390625, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8383572101593018, Predicted Probability: 0.9447, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2355/4000 [22:27<14:23,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.845414161682129, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.003879547119141, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2356/4000 [22:28<16:13,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.1085100173950195, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.19802433252334595, Predicted Probability: 0.4507, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2357/4000 [22:29<18:03,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.960698127746582, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9613144397735596, Predicted Probability: 0.0187, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2358/4000 [22:30<18:33,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3648271560668945, Predicted Probability: 0.0126, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6999378204345703, Predicted Probability: 0.8455, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2359/4000 [22:30<17:29,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.487550735473633, Predicted Probability: 0.0767, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3807878494262695, Predicted Probability: 0.0329, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2360/4000 [22:31<15:15,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.463014602661133, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.002763509750366, Predicted Probability: 0.9527, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2361/4000 [22:31<12:20,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.490906238555908, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 4.467387676239014, Predicted Probability: 0.9887, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2362/4000 [22:32<14:35,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.355109214782715, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7318005561828613, Predicted Probability: 0.8496, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2363/4000 [22:32<16:11,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6215184926986694, Predicted Probability: 0.8350, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.218441009521484, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2364/4000 [22:33<17:25,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.900666236877441, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.918097972869873, Predicted Probability: 0.9487, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2365/4000 [22:33<15:16,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.60523796081543, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2867655754089355, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2366/4000 [22:34<12:21,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.540415287017822, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.729889154434204, Predicted Probability: 0.0234, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2367/4000 [22:34<14:53,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.170365571975708, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.290966987609863, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2368/4000 [22:35<17:16,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.409590721130371, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.356474876403809, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2369/4000 [22:36<18:43,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.248081684112549, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.479460716247559, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2370/4000 [22:36<16:04,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.501809120178223, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4055447578430176, Predicted Probability: 0.0321, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2371/4000 [22:37<17:07,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.880786418914795, Predicted Probability: 0.8677, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.423194885253906, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2372/4000 [22:38<18:24,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.705780029296875, Predicted Probability: 0.0090, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0656098127365112, Predicted Probability: 0.7438, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2373/4000 [22:39<19:22,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.16812866926193237, Predicted Probability: 0.5419, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5307512283325195, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2374/4000 [22:40<19:43,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8588192462921143, Predicted Probability: 0.8652, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.505345344543457, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2375/4000 [22:40<16:49,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5419161319732666, Predicted Probability: 0.9270, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.918871879577637, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2376/4000 [22:41<17:35,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1797196865081787, Predicted Probability: 0.9601, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0423319339752197, Predicted Probability: 0.8852, Prediction: 1.0

Epoch 1/3:  59%|█████▉    | 2377/4000 [22:41<18:44,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0804328918457031, Predicted Probability: 0.2534, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.848631381988525, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2378/4000 [22:42<19:29,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.758232593536377, Predicted Probability: 0.0228, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.137615203857422, Predicted Probability: 0.0416, Prediction: 0.0

Epoch 1/3:  59%|█████▉    | 2379/4000 [22:43<19:46,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.140661239624023, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5634124279022217, Predicted Probability: 0.0276, Prediction: 0.0

Epoch 1/3:  60%|█████▉    | 2380/4000 [22:43<17:00,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7098093032836914, Predicted Probability: 0.9376, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.756513595581055, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2381/4000 [22:44<18:11,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.177788257598877, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8312163352966309, Predicted Probability: 0.8619, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2382/4000 [22:45<18:45,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.009911835193634033, Predicted Probability: 0.5025, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.308955192565918, Predicted Probability: 0.0133, Prediction: 0.0

Epoch 1/3:  60%|█████▉    | 2383/4000 [22:45<17:59,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.383298873901367, Predicted Probability: 0.0328, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9002787470817566, Predicted Probability: 0.2890, Prediction: 0.0

Epoch 1/3:  60%|█████▉    | 2384/4000 [22:46<18:38,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0572705268859863, Predicted Probability: 0.8867, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1204118728637695, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 1/3:  60%|█████▉    | 2385/4000 [22:47<18:46,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.25123611092567444, Predicted Probability: 0.4375, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7847211360931396, Predicted Probability: 0.0222, Prediction: 0.0

Epoch 1/3:  60%|█████▉    | 2386/4000 [22:47<16:12,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2057089805603027, Predicted Probability: 0.9610, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6223018169403076, Predicted Probability: 0.9740, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2387/4000 [22:48<18:03,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4152333736419678, Predicted Probability: 0.1954, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2456560134887695, Predicted Probability: 0.0141, Prediction: 0.0

Epoch 1/3:  60%|█████▉    | 2388/4000 [22:49<15:48,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.029626369476318, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.856459617614746, Predicted Probability: 0.9793, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2390/4000 [22:49<11:29,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.558344841003418, Predicted Probability: 0.9281, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.946777820587158, Predicted Probability: 0.9810, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -4.560067176818848, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 3.931572914123535, Predicted Probability: 0.9808, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2391/4000 [22:50<14:03,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.954381942749023, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9888497591018677, Predicted Probability: 0.8796, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2392/4000 [22:50<11:29,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.419976234436035, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.7476468086242676, Predicted Probability: 0.9398, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2393/4000 [22:51<11:33,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.383979558944702, Predicted Probability: 0.0328, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8778223991394043, Predicted Probability: 0.9467, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2394/4000 [22:51<11:40,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.587252140045166, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8923075199127197, Predicted Probability: 0.9475, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2395/4000 [22:51<09:47,  2.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0118632316589355, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.719152927398682, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2396/4000 [22:52<09:50,  2.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1693670749664307, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.298527717590332, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2398/4000 [22:53<11:00,  2.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0569489002227783, Predicted Probability: 0.0449, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.634459018707275, Predicted Probability: 0.0096, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 3.0528786182403564, Predicted Probability: 0.9549, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.388382434844971, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 1/3:  60%|█████▉    | 2399/4000 [22:53<14:38,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.95169734954834, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.988605499267578, Predicted Probability: 0.0182, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2400/4000 [22:54<16:49,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.745748519897461, Predicted Probability: 0.0231, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.264491081237793, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2401/4000 [22:55<14:43,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.586507797241211, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.991131067276001, Predicted Probability: 0.1201, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2402/4000 [22:55<13:20,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.80523681640625, Predicted Probability: 0.9782, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.062767028808594, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2403/4000 [22:56<15:26,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.006105899810791, Predicted Probability: 0.0179, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.781470537185669, Predicted Probability: 0.9417, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2404/4000 [22:57<17:02,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0342864990234375, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6193587779998779, Predicted Probability: 0.3499, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2405/4000 [22:57<15:30,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1697282791137695, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5981504321098328, Predicted Probability: 0.6452, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2406/4000 [22:57<13:47,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8011507987976074, Predicted Probability: 0.8583, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.439887523651123, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2407/4000 [22:58<12:38,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9481112957000732, Predicted Probability: 0.0498, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.880208969116211, Predicted Probability: 0.9469, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2408/4000 [22:58<10:59,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.663179874420166, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.401580274105072, Predicted Probability: 0.5991, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2409/4000 [22:59<13:26,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.2281394004821777, Predicted Probability: 0.0973, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1503775119781494, Predicted Probability: 0.1043, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2410/4000 [22:59<11:01,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.031463146209717, Predicted Probability: 0.0174, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.576148509979248, Predicted Probability: 0.9293, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2411/4000 [22:59<09:52,  2.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5600725412368774, Predicted Probability: 0.3635, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3314218521118164, Predicted Probability: 0.9655, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2412/4000 [22:59<08:30,  3.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.442599296569824, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.751163959503174, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2413/4000 [23:00<12:03,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.271134376525879, Predicted Probability: 0.0366, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.61683988571167, Predicted Probability: 0.8344, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2414/4000 [23:01<14:19,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.373929977416992, Predicted Probability: 0.0124, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.01406192779541, Predicted Probability: 0.9532, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2415/4000 [23:01<14:29,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5986125469207764, Predicted Probability: 0.9308, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.856926441192627, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2416/4000 [23:02<13:04,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.626671314239502, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.379286766052246, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2417/4000 [23:02<11:17,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.490901231765747, Predicted Probability: 0.9704, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1193926334381104, Predicted Probability: 0.9577, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2418/4000 [23:02<09:34,  2.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7350382804870605, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.164125919342041, Predicted Probability: 0.0153, Prediction: 0.0

Epoch 1/3:  60%|██████    | 2419/4000 [23:03<12:35,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.196637153625488, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6409193277359009, Predicted Probability: 0.8377, Prediction: 1.0

Epoch 1/3:  60%|██████    | 2420/4000 [23:03<11:41,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.922149658203125, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9385690689086914, Predicted Probability: 0.0503, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2421/4000 [23:04<11:06,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.546809434890747, Predicted Probability: 0.0726, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.715341567993164, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2422/4000 [23:04<12:08,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.747143745422363, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.167754173278809, Predicted Probability: 0.9847, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2423/4000 [23:05<14:24,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6365444660186768, Predicted Probability: 0.9332, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.270256042480469, Predicted Probability: 0.0138, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2424/4000 [23:06<16:17,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1938397884368896, Predicted Probability: 0.8997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4810588359832764, Predicted Probability: 0.0299, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2425/4000 [23:07<17:28,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8035902976989746, Predicted Probability: 0.9782, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.90278959274292, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2426/4000 [23:07<18:08,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.171741485595703, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0967905521392822, Predicted Probability: 0.9568, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2427/4000 [23:08<18:46,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.4229888916015625, Predicted Probability: 0.0119, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4947540760040283, Predicted Probability: 0.9238, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2428/4000 [23:09<16:02,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.768308162689209, Predicted Probability: 0.0226, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3396294116973877, Predicted Probability: 0.0342, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2429/4000 [23:09<14:06,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.493453502655029, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.861987590789795, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2430/4000 [23:09<11:28,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3031744956970215, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.010775566101074, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2431/4000 [23:10<12:31,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6380724906921387, Predicted Probability: 0.0256, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6871259212493896, Predicted Probability: 0.9363, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2432/4000 [23:10<12:58,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9151573181152344, Predicted Probability: 0.9486, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.510697364807129, Predicted Probability: 0.9891, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2433/4000 [23:11<14:57,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7285308837890625, Predicted Probability: 0.9387, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1433069705963135, Predicted Probability: 0.1050, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2434/4000 [23:12<16:48,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.453884124755859, Predicted Probability: 0.9885, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.468048095703125, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2435/4000 [23:13<17:47,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.818099498748779, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0091400146484375, Predicted Probability: 0.9530, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2436/4000 [23:13<18:44,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.842167854309082, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.99509334564209, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2437/4000 [23:14<18:58,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.594758987426758, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1320111751556396, Predicted Probability: 0.9582, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2438/4000 [23:14<14:51,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.777902126312256, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.463043212890625, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2439/4000 [23:15<16:12,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4095094203948975, Predicted Probability: 0.0320, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.172924280166626, Predicted Probability: 0.8978, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2440/4000 [23:16<17:56,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8467020988464355, Predicted Probability: 0.9451, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.020999908447266, Predicted Probability: 0.0176, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2441/4000 [23:16<15:29,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.01418924331665, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.105442523956299, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2442/4000 [23:17<16:43,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0778095722198486, Predicted Probability: 0.2539, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9677982330322266, Predicted Probability: 0.9511, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2443/4000 [23:18<17:43,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.151916980743408, Predicted Probability: 0.9845, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.037116050720215, Predicted Probability: 0.0173, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2444/4000 [23:19<18:38,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.282222270965576, Predicted Probability: 0.9638, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.873734474182129, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2445/4000 [23:19<18:40,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1852893829345703, Predicted Probability: 0.8989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.461072564125061, Predicted Probability: 0.1883, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2446/4000 [23:20<18:54,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.406927108764648, Predicted Probability: 0.9880, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1207196712493896, Predicted Probability: 0.0423, Prediction: 0.0

Epoch 1/3:  61%|██████    | 2447/4000 [23:20<16:10,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.706363201141357, Predicted Probability: 0.9910, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5068156719207764, Predicted Probability: 0.9709, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2448/4000 [23:21<14:13,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.81870698928833, Predicted Probability: 0.9785, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.775249481201172, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 1/3:  61%|██████    | 2449/4000 [23:21<13:26,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.277706146240234, Predicted Probability: 0.0137, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7737064361572266, Predicted Probability: 0.9775, Prediction: 1.0

Epoch 1/3:  61%|██████▏   | 2450/4000 [23:22<12:14,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.320953369140625, Predicted Probability: 0.0131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6177632808685303, Predicted Probability: 0.9320, Prediction: 1.0

Epoch 1/3:  61%|██████▏   | 2451/4000 [23:23<14:53,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.682307481765747, Predicted Probability: 0.0640, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5337629318237305, Predicted Probability: 0.0106, Prediction: 0.0

Epoch 1/3:  61%|██████▏   | 2452/4000 [23:23<16:10,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2475297451019287, Predicted Probability: 0.0956, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.240993499755859, Predicted Probability: 0.0142, Prediction: 0.0

Epoch 1/3:  61%|██████▏   | 2453/4000 [23:24<14:48,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.20224666595459, Predicted Probability: 0.9005, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.788519382476807, Predicted Probability: 0.9917, Prediction: 1.0

Epoch 1/3:  61%|██████▏   | 2454/4000 [23:24<13:19,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.917041778564453, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5951339602470398, Predicted Probability: 0.6445, Prediction: 1.0

Epoch 1/3:  61%|██████▏   | 2455/4000 [23:25<14:46,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.082667827606201, Predicted Probability: 0.0166, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6061186790466309, Predicted Probability: 0.8329, Prediction: 1.0

Epoch 1/3:  61%|██████▏   | 2456/4000 [23:25<13:13,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2927093505859375, Predicted Probability: 0.9642, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.301119804382324, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 1/3:  61%|██████▏   | 2457/4000 [23:26<15:03,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.747697353363037, Predicted Probability: 0.9770, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0928702354431152, Predicted Probability: 0.2511, Prediction: 0.0

Epoch 1/3:  61%|██████▏   | 2458/4000 [23:26<13:30,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.546947002410889, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1447196006774902, Predicted Probability: 0.1048, Prediction: 0.0

Epoch 1/3:  61%|██████▏   | 2459/4000 [23:27<12:17,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.692285537719727, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.616154670715332, Predicted Probability: 0.8343, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2460/4000 [23:27<14:16,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3276238441467285, Predicted Probability: 0.0130, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.487213134765625, Predicted Probability: 0.9703, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2461/4000 [23:28<11:35,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8604323863983154, Predicted Probability: 0.1347, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.842548847198486, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2462/4000 [23:28<13:41,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.32284295558929443, Predicted Probability: 0.4200, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.254882335662842, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2463/4000 [23:29<15:40,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3912246227264404, Predicted Probability: 0.9162, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.231503009796143, Predicted Probability: 0.0143, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2464/4000 [23:30<14:26,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.028480529785156, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.080977439880371, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2465/4000 [23:30<15:44,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.865927219390869, Predicted Probability: 0.9461, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1970527172088623, Predicted Probability: 0.9000, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2466/4000 [23:31<16:44,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2285640239715576, Predicted Probability: 0.0972, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.447235584259033, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2467/4000 [23:32<17:19,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2547645568847656, Predicted Probability: 0.0372, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.624006748199463, Predicted Probability: 0.0676, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2468/4000 [23:33<17:58,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.448853015899658, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9341530799865723, Predicted Probability: 0.1263, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2469/4000 [23:33<18:26,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8620266914367676, Predicted Probability: 0.8655, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.215941905975342, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2471/4000 [23:34<12:29,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6325912475585938, Predicted Probability: 0.0671, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.074226379394531, Predicted Probability: 0.0167, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -2.9671220779418945, Predicted Probability: 0.0489, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.520793437957764, Predicted Probability: 0.9892, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2472/4000 [23:35<14:34,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.821913242340088, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.807549476623535, Predicted Probability: 0.9431, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2473/4000 [23:35<15:44,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2206223011016846, Predicted Probability: 0.9021, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.424353122711182, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2474/4000 [23:36<15:18,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.635241508483887, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.427474498748779, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2475/4000 [23:37<16:13,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.523675918579102, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2692298889160156, Predicted Probability: 0.9063, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2476/4000 [23:37<16:56,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6143782138824463, Predicted Probability: 0.9318, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.396050930023193, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2477/4000 [23:38<18:17,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.213111877441406, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.386692047119141, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2478/4000 [23:39<16:11,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7662651538848877, Predicted Probability: 0.9774, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.243450403213501, Predicted Probability: 0.9041, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2479/4000 [23:39<17:03,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8550262451171875, Predicted Probability: 0.8647, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6759696006774902, Predicted Probability: 0.0644, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2480/4000 [23:40<19:49,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.10163688659668, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2053496837615967, Predicted Probability: 0.9007, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2481/4000 [23:41<19:31,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.463491916656494, Predicted Probability: 0.0114, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3369290828704834, Predicted Probability: 0.9119, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2482/4000 [23:42<18:19,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.468799591064453, Predicted Probability: 0.0113, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.546727180480957, Predicted Probability: 0.0726, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2483/4000 [23:43<19:32,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.820979118347168, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6931113004684448, Predicted Probability: 0.1554, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2484/4000 [23:43<19:08,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.55901575088501, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2355475425720215, Predicted Probability: 0.9034, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2485/4000 [23:44<16:19,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6309309005737305, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.48308977484703064, Predicted Probability: 0.3815, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2486/4000 [23:45<17:41,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.242948532104492, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.762813091278076, Predicted Probability: 0.9773, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2487/4000 [23:45<15:21,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.178506374359131, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.783934593200684, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2488/4000 [23:45<12:47,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6158010363578796, Predicted Probability: 0.6493, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.218828201293945, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2489/4000 [23:46<14:57,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9677300453186035, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1462209224700928, Predicted Probability: 0.9588, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2490/4000 [23:47<13:12,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.533813953399658, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1486141681671143, Predicted Probability: 0.1045, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2491/4000 [23:47<15:13,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.236269950866699, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1498076915740967, Predicted Probability: 0.2405, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2492/4000 [23:48<13:33,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.081222057342529, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.703937530517578, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2493/4000 [23:48<12:19,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.173797607421875, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.568315505981445, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2494/4000 [23:49<14:07,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6858344078063965, Predicted Probability: 0.8437, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.698129653930664, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2495/4000 [23:49<14:08,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.341588973999023, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0149827003479004, Predicted Probability: 0.8824, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2496/4000 [23:50<15:41,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.146432876586914, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.977283477783203, Predicted Probability: 0.9515, Prediction: 1.0

Epoch 1/3:  62%|██████▏   | 2497/4000 [23:51<13:53,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.557742118835449, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.80604887008667, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2498/4000 [23:51<15:55,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.479409694671631, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.005419731140137, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 1/3:  62%|██████▏   | 2499/4000 [23:52<17:07,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.85975980758667, Predicted Probability: 0.9794, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.133885383605957, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 1/3:  62%|██████▎   | 2500/4000 [23:53<16:09,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.631542682647705, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.811176300048828, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2501/4000 [23:53<15:48,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3501000702381134, Predicted Probability: 0.4134, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0473220348358154, Predicted Probability: 0.8857, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2502/4000 [23:54<16:47,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6231420040130615, Predicted Probability: 0.9323, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3822691440582275, Predicted Probability: 0.0329, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2504/4000 [23:55<13:53,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.751718282699585, Predicted Probability: 0.1478, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.330474853515625, Predicted Probability: 0.0130, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 5.159898281097412, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.912742853164673, Predicted Probability: 0.0196, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2505/4000 [23:55<12:28,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0820482969284058, Predicted Probability: 0.7469, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.248604774475098, Predicted Probability: 0.0141, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2506/4000 [23:56<11:38,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.583975315093994, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.963170528411865, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2507/4000 [23:57<13:59,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.7470283508300781, Predicted Probability: 0.8516, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.428940773010254, Predicted Probability: 0.0314, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2508/4000 [23:57<15:10,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.212254047393799, Predicted Probability: 0.9013, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.981624603271484, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2509/4000 [23:58<13:20,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3340516090393066, Predicted Probability: 0.0344, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.930002212524414, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2510/4000 [23:58<15:04,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.699307918548584, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9893798828125, Predicted Probability: 0.9818, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2511/4000 [23:59<15:58,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.102323532104492, Predicted Probability: 0.9570, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2418551445007324, Predicted Probability: 0.0961, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2512/4000 [24:00<13:57,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.997386932373047, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.516639232635498, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2513/4000 [24:00<15:43,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3085174560546875, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.383859634399414, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2514/4000 [24:01<13:40,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.540022373199463, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.523258686065674, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2515/4000 [24:01<15:13,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5251994132995605, Predicted Probability: 0.9714, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.491902828216553, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2516/4000 [24:02<14:48,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.609541416168213, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.331803798675537, Predicted Probability: 0.9655, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2517/4000 [24:02<11:51,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.05792226269841194, Predicted Probability: 0.4855, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5175065994262695, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2518/4000 [24:03<11:31,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0945754051208496, Predicted Probability: 0.8904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.40185284614563, Predicted Probability: 0.9678, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2519/4000 [24:03<13:49,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.677878379821777, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.185487270355225, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2521/4000 [24:04<12:05,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.231128692626953, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6268720626831055, Predicted Probability: 0.0259, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 5.426703453063965, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6701192259788513, Predicted Probability: 0.3385, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2522/4000 [24:05<11:19,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.438502788543701, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8794718980789185, Predicted Probability: 0.8676, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2523/4000 [24:05<10:36,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.405287265777588, Predicted Probability: 0.0321, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.174558401107788, Predicted Probability: 0.0401, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2524/4000 [24:06<10:45,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.212917327880859, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6253859996795654, Predicted Probability: 0.1645, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2525/4000 [24:06<11:34,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3199357986450195, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3437106609344482, Predicted Probability: 0.0341, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2526/4000 [24:07<13:41,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6930322647094727, Predicted Probability: 0.0634, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.733240127563477, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2527/4000 [24:08<14:48,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.607776165008545, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.311851441860199, Predicted Probability: 0.4227, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2528/4000 [24:08<13:04,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.192250967025757, Predicted Probability: 0.9605, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.18346551060676575, Predicted Probability: 0.5457, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2529/4000 [24:08<11:54,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6938539743423462, Predicted Probability: 0.3332, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.774265289306641, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2530/4000 [24:09<12:14,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5674936771392822, Predicted Probability: 0.9287, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2879996299743652, Predicted Probability: 0.9079, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2531/4000 [24:10<14:09,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5470499992370605, Predicted Probability: 0.9274, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.152218818664551, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2532/4000 [24:10<15:41,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.7103052139282227, Predicted Probability: 0.1531, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.129955768585205, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2533/4000 [24:11<12:57,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.645920753479004, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.178687572479248, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2534/4000 [24:11<13:10,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.537580966949463, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.950023174285889, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2535/4000 [24:12<12:04,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.040058135986328, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.36387825012207, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2536/4000 [24:12<11:14,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6357054710388184, Predicted Probability: 0.9743, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.972708225250244, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2537/4000 [24:13<13:33,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3802329301834106, Predicted Probability: 0.7990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.41845178604126, Predicted Probability: 0.0119, Prediction: 0.0

Epoch 1/3:  63%|██████▎   | 2538/4000 [24:13<13:24,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.423363208770752, Predicted Probability: 0.0119, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1954433917999268, Predicted Probability: 0.9607, Prediction: 1.0

Epoch 1/3:  63%|██████▎   | 2539/4000 [24:14<12:14,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.074014663696289, Predicted Probability: 0.0167, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.078068256378174, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  64%|██████▎   | 2540/4000 [24:14<11:19,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.755818843841553, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.67525053024292, Predicted Probability: 0.9753, Prediction: 1.0

Epoch 1/3:  64%|██████▎   | 2541/4000 [24:15<12:00,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.572859287261963, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.673943519592285, Predicted Probability: 0.0645, Prediction: 0.0

Epoch 1/3:  64%|██████▎   | 2542/4000 [24:15<12:19,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.861846923828125, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5214829444885254, Predicted Probability: 0.9256, Prediction: 1.0

Epoch 1/3:  64%|██████▎   | 2543/4000 [24:16<11:16,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.121526837348938, Predicted Probability: 0.2457, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5191330909729, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 1/3:  64%|██████▎   | 2544/4000 [24:16<13:32,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.759102821350098, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2981608510017395, Predicted Probability: 0.4260, Prediction: 0.0

Epoch 1/3:  64%|██████▎   | 2545/4000 [24:17<15:02,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.442124366760254, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.356543779373169, Predicted Probability: 0.9135, Prediction: 1.0

Epoch 1/3:  64%|██████▎   | 2546/4000 [24:17<12:00,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1318464279174805, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 3.8645665645599365, Predicted Probability: 0.9795, Prediction: 1.0

Epoch 1/3:  64%|██████▎   | 2547/4000 [24:18<13:39,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.222115993499756, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2032387256622314, Predicted Probability: 0.7691, Prediction: 1.0

Epoch 1/3:  64%|██████▎   | 2548/4000 [24:19<12:50,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.329673767089844, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2972283363342285, Predicted Probability: 0.0134, Prediction: 0.0

Epoch 1/3:  64%|██████▎   | 2549/4000 [24:19<14:09,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0610387325286865, Predicted Probability: 0.9553, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.473766803741455, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2550/4000 [24:20<13:03,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.093778610229492, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9116976261138916, Predicted Probability: 0.9484, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2551/4000 [24:20<12:59,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.935356378555298, Predicted Probability: 0.9808, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1205689907073975, Predicted Probability: 0.9577, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2552/4000 [24:21<12:57,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.984163761138916, Predicted Probability: 0.0183, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.020458221435547, Predicted Probability: 0.9535, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2553/4000 [24:21<11:48,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.560488700866699, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.90185546875, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2554/4000 [24:22<14:03,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.289532661437988, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4666900634765625, Predicted Probability: 0.9697, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2555/4000 [24:22<13:44,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.476099967956543, Predicted Probability: 0.9888, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8214290142059326, Predicted Probability: 0.9438, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2557/4000 [24:23<10:00,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.250882148742676, Predicted Probability: 0.9627, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.108513355255127, Predicted Probability: 0.9940, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.003478527069092, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.011333752423524857, Predicted Probability: 0.4972, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2558/4000 [24:23<09:35,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5174102783203125, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5875797271728516, Predicted Probability: 0.3572, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2559/4000 [24:24<09:54,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.22862990200519562, Predicted Probability: 0.4431, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.107177257537842, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2560/4000 [24:25<12:04,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.947936058044434, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2842419147491455, Predicted Probability: 0.0924, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2561/4000 [24:25<14:37,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.088266611099243, Predicted Probability: 0.8898, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.184556484222412, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2562/4000 [24:26<12:52,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.455359935760498, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.503070116043091, Predicted Probability: 0.9244, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2563/4000 [24:26<10:30,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1918675899505615, Predicted Probability: 0.7671, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.249100685119629, Predicted Probability: 0.2229, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2564/4000 [24:26<10:00,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9418015480041504, Predicted Probability: 0.9499, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.235098838806152, Predicted Probability: 0.9857, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2565/4000 [24:27<12:16,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.282676696777344, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7111566066741943, Predicted Probability: 0.3293, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2566/4000 [24:28<13:54,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.570847988128662, Predicted Probability: 0.1721, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.981218338012695, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2567/4000 [24:29<14:56,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.564974069595337, Predicted Probability: 0.0275, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9436447620391846, Predicted Probability: 0.8748, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2568/4000 [24:29<15:42,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8648608922958374, Predicted Probability: 0.1341, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.391709327697754, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2569/4000 [24:30<16:24,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.122766971588135, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.184251546859741, Predicted Probability: 0.1012, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2570/4000 [24:31<16:48,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.491628646850586, Predicted Probability: 0.9236, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.436212062835693, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2571/4000 [24:31<16:14,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.805575370788574, Predicted Probability: 0.9782, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.229458332061768, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2572/4000 [24:32<13:57,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.480180740356445, Predicted Probability: 0.9888, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.259426116943359, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2573/4000 [24:33<14:52,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4874815940856934, Predicted Probability: 0.0767, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3004071712493896, Predicted Probability: 0.9644, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2574/4000 [24:33<13:05,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.652871131896973, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.793395042419434, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2575/4000 [24:34<14:45,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.951282024383545, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.470724582672119, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2576/4000 [24:34<15:31,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.212900161743164, Predicted Probability: 0.9014, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6471645832061768, Predicted Probability: 0.0662, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2577/4000 [24:35<16:21,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.248496055603027, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5498546957969666, Predicted Probability: 0.6341, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2578/4000 [24:35<13:01,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.029936790466309, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7837233543396, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 1/3:  64%|██████▍   | 2579/4000 [24:36<11:40,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4719371795654297, Predicted Probability: 0.9699, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.82094669342041, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 1/3:  64%|██████▍   | 2580/4000 [24:37<13:31,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.167339324951172, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4061717987060547, Predicted Probability: 0.9173, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2581/4000 [24:37<12:04,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.236237049102783, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.6649930477142334, Predicted Probability: 0.0250, Prediction: 0.0

Epoch 1/3:  65%|██████▍   | 2582/4000 [24:38<13:28,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.988238334655762, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7135673761367798, Predicted Probability: 0.8473, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2583/4000 [24:38<10:51,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.637931823730469, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.41667497158050537, Predicted Probability: 0.6027, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2584/4000 [24:38<12:31,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5488386750221252, Predicted Probability: 0.3661, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.518067359924316, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  65%|██████▍   | 2585/4000 [24:39<14:20,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.063385963439941, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1308226585388184, Predicted Probability: 0.8939, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2586/4000 [24:39<11:28,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.535617828369141, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.985455513000488, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  65%|██████▍   | 2587/4000 [24:40<13:09,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.608395576477051, Predicted Probability: 0.0099, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.114198923110962, Predicted Probability: 0.8923, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2588/4000 [24:41<14:38,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.69974946975708, Predicted Probability: 0.0090, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2973453998565674, Predicted Probability: 0.9643, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2589/4000 [24:41<11:45,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.041688442230225, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.373729228973389, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2590/4000 [24:42<10:48,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.191023826599121, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4954757690429688, Predicted Probability: 0.0294, Prediction: 0.0

Epoch 1/3:  65%|██████▍   | 2591/4000 [24:42<11:28,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.328555107116699, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.259847402572632, Predicted Probability: 0.0945, Prediction: 0.0

Epoch 1/3:  65%|██████▍   | 2592/4000 [24:43<13:01,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.933148145675659, Predicted Probability: 0.0505, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6422643661499023, Predicted Probability: 0.9335, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2593/4000 [24:44<14:19,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1424219608306885, Predicted Probability: 0.8950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.217433452606201, Predicted Probability: 0.0385, Prediction: 0.0

Epoch 1/3:  65%|██████▍   | 2594/4000 [24:44<15:12,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8685941696166992, Predicted Probability: 0.1337, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.875808000564575, Predicted Probability: 0.9797, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2596/4000 [24:45<11:33,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.372121334075928, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.936709880828857, Predicted Probability: 0.0071, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 5.800626277923584, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.650729179382324, Predicted Probability: 0.9905, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2597/4000 [24:46<13:13,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.671131134033203, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.142524719238281, Predicted Probability: 0.9844, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2598/4000 [24:46<11:52,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.271225452423096, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.8934550285339355, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 1/3:  65%|██████▍   | 2599/4000 [24:47<14:30,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.785271167755127, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.833168983459473, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2600/4000 [24:48<16:13,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.826135635375977, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.500591278076172, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2601/4000 [24:48<14:00,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4931910037994385, Predicted Probability: 0.0295, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.258546829223633, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2602/4000 [24:49<14:05,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.844625473022461, Predicted Probability: 0.0550, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.40112566947937, Predicted Probability: 0.9677, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2603/4000 [24:49<12:31,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1887617111206055, Predicted Probability: 0.9604, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.250805854797363, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2604/4000 [24:50<11:22,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.762385368347168, Predicted Probability: 0.1465, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.279527187347412, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2605/4000 [24:50<10:31,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1028265953063965, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.911236047744751, Predicted Probability: 0.9804, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2606/4000 [24:50<08:46,  2.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9314348697662354, Predicted Probability: 0.1266, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.265517234802246, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2607/4000 [24:51<11:33,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.282599925994873, Predicted Probability: 0.0362, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.677910327911377, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2608/4000 [24:52<13:19,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.0352931022644043, Predicted Probability: 0.9541, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2636849880218506, Predicted Probability: 0.9632, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2609/4000 [24:53<14:46,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6853179931640625, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6628267765045166, Predicted Probability: 0.0652, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2610/4000 [24:54<17:16,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.19161957502365112, Predicted Probability: 0.4522, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.245659351348877, Predicted Probability: 0.0141, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2611/4000 [24:54<14:42,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4009904861450195, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8345361351966858, Predicted Probability: 0.3027, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2612/4000 [24:54<12:54,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.559035301208496, Predicted Probability: 0.9282, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.214710235595703, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2613/4000 [24:55<11:33,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.201124668121338, Predicted Probability: 0.0148, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.817781925201416, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2614/4000 [24:55<13:45,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.878028392791748, Predicted Probability: 0.0076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.633852958679199, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2615/4000 [24:56<13:49,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.544391632080078, Predicted Probability: 0.0105, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2482459843158722, Predicted Probability: 0.4383, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2616/4000 [24:57<14:46,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.037148475646973, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8019981384277344, Predicted Probability: 0.3096, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2617/4000 [24:58<15:27,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3081822395324707, Predicted Probability: 0.9647, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6306124329566956, Predicted Probability: 0.3474, Prediction: 0.0

Epoch 1/3:  65%|██████▌   | 2618/4000 [24:58<16:49,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.382559299468994, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4408148527145386, Predicted Probability: 0.6085, Prediction: 1.0

Epoch 1/3:  65%|██████▌   | 2619/4000 [24:59<14:22,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0021824836730957, Predicted Probability: 0.8810, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.677525281906128, Predicted Probability: 0.9357, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2620/4000 [24:59<11:28,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.30618953704834, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.04723013937473297, Predicted Probability: 0.4882, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2621/4000 [25:00<13:10,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.921607494354248, Predicted Probability: 0.0194, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.096891403198242, Predicted Probability: 0.0164, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2622/4000 [25:01<14:14,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6745996475219727, Predicted Probability: 0.8422, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.366352558135986, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2623/4000 [25:01<14:10,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7461798191070557, Predicted Probability: 0.0603, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.644628524780273, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2624/4000 [25:02<13:03,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.201701641082764, Predicted Probability: 0.0147, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -4.701508045196533, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2625/4000 [25:03<15:34,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.130915641784668, Predicted Probability: 0.0158, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.330488204956055, Predicted Probability: 0.0130, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2626/4000 [25:03<15:54,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2604169845581055, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3457214832305908, Predicted Probability: 0.4144, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2627/4000 [25:04<16:57,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.355587005615234, Predicted Probability: 0.0127, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4684200286865234, Predicted Probability: 0.0302, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2628/4000 [25:05<17:07,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0831254720687866, Predicted Probability: 0.7471, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.991874694824219, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2629/4000 [25:06<17:22,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.1564488410949707, Predicted Probability: 0.2393, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.342965602874756, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2630/4000 [25:06<15:54,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.533934235572815, Predicted Probability: 0.8226, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.0490217208862305, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2631/4000 [25:07<16:19,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.865361213684082, Predicted Probability: 0.9461, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.888561248779297, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2632/4000 [25:08<16:40,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0367424488067627, Predicted Probability: 0.9542, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.531763076782227, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2633/4000 [25:08<16:57,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.832212448120117, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.844245433807373, Predicted Probability: 0.9450, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2634/4000 [25:09<17:03,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5658020973205566, Predicted Probability: 0.9286, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.325741767883301, Predicted Probability: 0.0131, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2635/4000 [25:10<14:29,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2106709480285645, Predicted Probability: 0.9946, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7300434112548828, Predicted Probability: 0.8494, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2636/4000 [25:10<15:18,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7274014949798584, Predicted Probability: 0.3258, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.11893892288208, Predicted Probability: 0.0160, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2637/4000 [25:11<15:36,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7789322137832642, Predicted Probability: 0.8556, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.312752723693848, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2638/4000 [25:12<16:16,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.964546203613281, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.2014665603637695, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2639/4000 [25:12<12:48,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.549893856048584, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.842780828475952, Predicted Probability: 0.0551, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2640/4000 [25:13<13:57,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.879063129425049, Predicted Probability: 0.9468, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.69710111618042, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2641/4000 [25:13<12:19,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.467668056488037, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.140740394592285, Predicted Probability: 0.9843, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2642/4000 [25:14<11:05,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1201632022857666, Predicted Probability: 0.8928, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8963229656219482, Predicted Probability: 0.0523, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2643/4000 [25:14<12:53,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.131542682647705, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1815016269683838, Predicted Probability: 0.7652, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2644/4000 [25:15<14:05,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.835842132568359, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0728349685668945, Predicted Probability: 0.8882, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2645/4000 [25:16<16:01,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.830060958862305, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.054262161254883, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 1/3:  66%|██████▌   | 2646/4000 [25:16<13:43,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1890437602996826, Predicted Probability: 0.0396, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.414483547210693, Predicted Probability: 0.9880, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2647/4000 [25:17<14:52,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4301108717918396, Predicted Probability: 0.3941, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.0402917861938477, Predicted Probability: 0.7389, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2648/4000 [25:18<15:24,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.993943214416504, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8581610918045044, Predicted Probability: 0.8651, Prediction: 1.0

Epoch 1/3:  66%|██████▌   | 2649/4000 [25:19<15:43,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4060821533203125, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.197190999984741, Predicted Probability: 0.9000, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2650/4000 [25:19<16:03,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.595677852630615, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8046228289604187, Predicted Probability: 0.6910, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2651/4000 [25:20<16:16,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.902369022369385, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7952195405960083, Predicted Probability: 0.6890, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2652/4000 [25:21<13:59,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.30122184753418, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.889925956726074, Predicted Probability: 0.9473, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2653/4000 [25:21<12:23,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.759800434112549, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.87672758102417, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 1/3:  66%|██████▋   | 2654/4000 [25:22<13:44,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.576522350311279, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.8091158866882324, Predicted Probability: 0.1407, Prediction: 0.0

Epoch 1/3:  66%|██████▋   | 2655/4000 [25:22<14:36,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.660521507263184, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4001554250717163, Predicted Probability: 0.8022, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2656/4000 [25:23<12:39,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7370796203613281, Predicted Probability: 0.8503, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.576761245727539, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2657/4000 [25:23<12:35,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4952967166900635, Predicted Probability: 0.0294, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6245057582855225, Predicted Probability: 0.1646, Prediction: 0.0

Epoch 1/3:  66%|██████▋   | 2658/4000 [25:24<12:24,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8503097295761108, Predicted Probability: 0.8642, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.730825424194336, Predicted Probability: 0.9913, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2659/4000 [25:24<11:10,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2122914791107178, Predicted Probability: 0.9613, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4358584880828857, Predicted Probability: 0.9195, Prediction: 1.0

Epoch 1/3:  66%|██████▋   | 2660/4000 [25:24<09:10,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4818785190582275, Predicted Probability: 0.8149, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.074169158935547, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2661/4000 [25:25<09:57,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8918237686157227, Predicted Probability: 0.9800, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6898789405822754, Predicted Probability: 0.1558, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2662/4000 [25:26<12:15,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.38638535141944885, Predicted Probability: 0.5954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.500014305114746, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2663/4000 [25:27<14:08,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.45235013961792, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6065303087234497, Predicted Probability: 0.1671, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2664/4000 [25:27<14:52,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.149991989135742, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9490394592285156, Predicted Probability: 0.1247, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2665/4000 [25:28<15:16,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2938804626464844, Predicted Probability: 0.9084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.291354656219482, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2666/4000 [25:29<15:54,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.742579936981201, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4043262004852295, Predicted Probability: 0.9678, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2667/4000 [25:29<12:56,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5243306159973145, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.376743316650391, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2668/4000 [25:29<11:37,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.12421178817749, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.303969860076904, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2669/4000 [25:30<10:37,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3060669898986816, Predicted Probability: 0.9646, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.776797771453857, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2670/4000 [25:30<11:26,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0399627685546875, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2683745324611664, Predicted Probability: 0.5667, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2671/4000 [25:31<12:47,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.764257788658142, Predicted Probability: 0.8537, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.2794952392578125, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2672/4000 [25:32<13:46,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.247971057891846, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.30936068296432495, Predicted Probability: 0.4233, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2673/4000 [25:33<14:59,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.70731782913208, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0328519344329834, Predicted Probability: 0.8842, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2674/4000 [25:33<14:00,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.726137638092041, Predicted Probability: 0.9765, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.815588116645813, Predicted Probability: 0.8600, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2675/4000 [25:34<14:41,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.620742917060852, Predicted Probability: 0.8349, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.045843601226807, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2676/4000 [25:34<12:45,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.525571823120117, Predicted Probability: 0.9893, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.158088207244873, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2677/4000 [25:35<10:17,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.269729137420654, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3053277730941772, Predicted Probability: 0.7867, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2678/4000 [25:35<08:32,  2.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2192012071609497, Predicted Probability: 0.2281, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.954370975494385, Predicted Probability: 0.0070, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2679/4000 [25:36<11:03,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9400601387023926, Predicted Probability: 0.0191, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.322954177856445, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2680/4000 [25:36<10:11,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.636168003082275, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3082056045532227, Predicted Probability: 0.0353, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2681/4000 [25:36<09:32,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.979739248752594, Predicted Probability: 0.2729, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.626289367675781, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2682/4000 [25:37<11:41,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.614833354949951, Predicted Probability: 0.9318, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8526535034179688, Predicted Probability: 0.0208, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2683/4000 [25:37<10:41,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.775702476501465, Predicted Probability: 0.9776, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8008531332015991, Predicted Probability: 0.1417, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2684/4000 [25:38<11:01,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0847830772399902, Predicted Probability: 0.9563, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.536044120788574, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2685/4000 [25:39<12:32,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.430809497833252, Predicted Probability: 0.9687, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.204695701599121, Predicted Probability: 0.2306, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2686/4000 [25:39<12:20,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3013254404067993, Predicted Probability: 0.2139, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.693991184234619, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2687/4000 [25:40<13:40,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9747376441955566, Predicted Probability: 0.0184, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.070453405380249, Predicted Probability: 0.8880, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2688/4000 [25:41<13:34,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.664957523345947, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6849368214607239, Predicted Probability: 0.3352, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2689/4000 [25:41<13:09,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.221264839172363, Predicted Probability: 0.0145, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.406397819519043, Predicted Probability: 0.1968, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2690/4000 [25:42<11:40,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7742315530776978, Predicted Probability: 0.6844, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.7406744956970215, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2691/4000 [25:42<11:42,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.612508773803711, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.044787406921387, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2692/4000 [25:43<13:26,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.700572967529297, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.633110046386719, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2693/4000 [25:44<14:25,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5672501921653748, Predicted Probability: 0.6381, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.023917198181152, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2694/4000 [25:45<15:33,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.148419380187988, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.164908409118652, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  67%|██████▋   | 2695/4000 [25:45<13:53,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.524323463439941, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.300240993499756, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2696/4000 [25:45<11:02,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6048665046691895, Predicted Probability: 0.0099, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.125175476074219, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2697/4000 [25:46<12:18,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1723201870918274, Predicted Probability: 0.5430, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2222329378128052, Predicted Probability: 0.7725, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2698/4000 [25:46<10:23,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.753317356109619, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.021195888519287, Predicted Probability: 0.9535, Prediction: 1.0

Epoch 1/3:  67%|██████▋   | 2699/4000 [25:46<08:36,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.342724800109863, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5363330841064453, Predicted Probability: 0.0734, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2700/4000 [25:47<08:59,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.35352620482444763, Predicted Probability: 0.5875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3297969102859497, Predicted Probability: 0.2092, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2701/4000 [25:48<11:31,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8331093788146973, Predicted Probability: 0.8621, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.437435626983643, Predicted Probability: 0.0117, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2702/4000 [25:48<13:00,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.952711582183838, Predicted Probability: 0.0188, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0491700172424316, Predicted Probability: 0.9547, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2703/4000 [25:49<12:38,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0263750553131104, Predicted Probability: 0.9538, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.801146388053894, Predicted Probability: 0.1417, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2705/4000 [25:50<10:52,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.328747749328613, Predicted Probability: 0.0130, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.377044916152954, Predicted Probability: 0.9151, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 2.9081122875213623, Predicted Probability: 0.9482, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.285166263580322, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2706/4000 [25:50<10:08,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.498878479003906, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.723679542541504, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2707/4000 [25:51<11:43,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1340675354003906, Predicted Probability: 0.8942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.159037113189697, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2708/4000 [25:51<10:42,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.769969463348389, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.067567825317383, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2709/4000 [25:52<13:12,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.585312366485596, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1593207120895386, Predicted Probability: 0.2388, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2710/4000 [25:53<11:44,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.050527095794678, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.171451091766357, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2711/4000 [25:53<10:39,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1272172927856445, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.904373645782471, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2712/4000 [25:53<09:48,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.61065673828125, Predicted Probability: 0.0263, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.035518646240234, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2713/4000 [25:54<10:24,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.291041374206543, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.2799904346466064, Predicted Probability: 0.7824, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2714/4000 [25:55<10:52,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.867713451385498, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.457367420196533, Predicted Probability: 0.9885, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2715/4000 [25:55<12:34,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9330096244812012, Predicted Probability: 0.2823, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9011430740356445, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2716/4000 [25:56<12:10,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.125579357147217, Predicted Probability: 0.9579, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9883155822753906, Predicted Probability: 0.0182, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2717/4000 [25:56<12:03,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5464887619018555, Predicted Probability: 0.9895, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.190988063812256, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2718/4000 [25:57<13:26,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7539927959442139, Predicted Probability: 0.3200, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.745209693908691, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2719/4000 [25:57<10:42,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.86946964263916, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.230195045471191, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2720/4000 [25:58<09:47,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9290924072265625, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.245304584503174, Predicted Probability: 0.9859, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2721/4000 [25:58<11:53,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.774906158447266, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3692121505737305, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2722/4000 [25:59<13:14,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.251537799835205, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3163493275642395, Predicted Probability: 0.5784, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2723/4000 [26:00<14:17,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.46014404296875, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2367753982543945, Predicted Probability: 0.0965, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2724/4000 [26:00<12:50,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.200394868850708, Predicted Probability: 0.9608, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.812167167663574, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2725/4000 [26:01<13:35,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9564538598060608, Predicted Probability: 0.7224, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.190308570861816, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2726/4000 [26:02<14:04,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.7801198959350586, Predicted Probability: 0.9777, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1150810718536377, Predicted Probability: 0.8924, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2727/4000 [26:02<11:33,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.408177852630615, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.768520832061768, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2728/4000 [26:03<12:50,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7260096073150635, Predicted Probability: 0.0235, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2844300270080566, Predicted Probability: 0.7832, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2729/4000 [26:04<13:50,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.40147066116333, Predicted Probability: 0.0121, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.43821120262146, Predicted Probability: 0.9689, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2730/4000 [26:04<12:02,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0409536361694336, Predicted Probability: 0.8850, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.104365348815918, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2731/4000 [26:04<10:45,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.195268154144287, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7514351606369019, Predicted Probability: 0.3205, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2732/4000 [26:05<12:42,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.03911018371582, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5496978759765625, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2733/4000 [26:05<10:11,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3120810985565186, Predicted Probability: 0.9648, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.111653804779053, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2734/4000 [26:06<10:36,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.485472202301025, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2748734951019287, Predicted Probability: 0.2184, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2735/4000 [26:07<12:15,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.954787254333496, Predicted Probability: 0.1240, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.728389739990234, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2736/4000 [26:07<10:52,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.596275806427002, Predicted Probability: 0.9733, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.215109348297119, Predicted Probability: 0.0386, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2737/4000 [26:08<10:29,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.7437944412231445, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.065643310546875, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2738/4000 [26:08<09:02,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.929594993591309, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.281237602233887, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 1/3:  68%|██████▊   | 2739/4000 [26:09<11:28,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.885226249694824, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.772649765014648, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 1/3:  68%|██████▊   | 2740/4000 [26:10<13:14,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.927649736404419, Predicted Probability: 0.0193, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.167689323425293, Predicted Probability: 0.1027, Prediction: 0.0

Epoch 1/3:  69%|██████▊   | 2741/4000 [26:10<14:22,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5726728439331055, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.0799560546875, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  69%|██████▊   | 2742/4000 [26:11<14:56,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.617121696472168, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0324783325195312, Predicted Probability: 0.9540, Prediction: 1.0

Epoch 1/3:  69%|██████▊   | 2743/4000 [26:12<13:53,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.07880163192749, Predicted Probability: 0.9834, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6324520111083984, Predicted Probability: 0.9329, Prediction: 1.0

Epoch 1/3:  69%|██████▊   | 2744/4000 [26:12<12:01,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.4544854164123535, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.0561842918396, Predicted Probability: 0.9830, Prediction: 1.0

Epoch 1/3:  69%|██████▊   | 2745/4000 [26:13<13:14,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.496572494506836, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7898755073547363, Predicted Probability: 0.6878, Prediction: 1.0

Epoch 1/3:  69%|██████▊   | 2746/4000 [26:14<13:50,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.492198467254639, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.840404510498047, Predicted Probability: 0.9448, Prediction: 1.0

Epoch 1/3:  69%|██████▊   | 2747/4000 [26:14<14:38,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.939760208129883, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.220249176025391, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  69%|██████▊   | 2748/4000 [26:15<15:11,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.379576683044434, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.504970550537109, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  69%|██████▊   | 2749/4000 [26:16<15:43,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.177206039428711, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.311748504638672, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2750/4000 [26:17<16:24,  1.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.948605537414551, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.460687637329102, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2751/4000 [26:17<12:45,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.640518665313721, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.600638389587402, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2752/4000 [26:18<12:12,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.716125965118408, Predicted Probability: 0.9380, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.7286996841430664, Predicted Probability: 0.8492, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2753/4000 [26:18<10:12,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.784176349639893, Predicted Probability: 0.9917, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.354323387145996, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2754/4000 [26:19<11:49,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.08797550201416, Predicted Probability: 0.0165, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.310325860977173, Predicted Probability: 0.9097, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2755/4000 [26:19<12:41,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7329245805740356, Predicted Probability: 0.3246, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.181128025054932, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2756/4000 [26:20<13:38,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.785327672958374, Predicted Probability: 0.8564, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.675363063812256, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2757/4000 [26:20<11:48,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6898910999298096, Predicted Probability: 0.9756, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7125141620635986, Predicted Probability: 0.9762, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2758/4000 [26:21<10:39,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.529026985168457, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.374138832092285, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2759/4000 [26:22<12:06,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.283694267272949, Predicted Probability: 0.9639, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.369091033935547, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2760/4000 [26:22<11:13,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3658018112182617, Predicted Probability: 0.9142, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.590906620025635, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2761/4000 [26:22<10:06,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.518838405609131, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1982181072235107, Predicted Probability: 0.9608, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2762/4000 [26:23<11:35,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.79897403717041, Predicted Probability: 0.9426, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.0795745849609375, Predicted Probability: 0.4801, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2763/4000 [26:24<12:36,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.259150505065918, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8750865459442139, Predicted Probability: 0.8670, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2764/4000 [26:25<13:25,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.615475654602051, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.297942191362381, Predicted Probability: 0.4261, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2765/4000 [26:25<14:02,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.269794464111328, Predicted Probability: 0.9063, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.301455974578857, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2766/4000 [26:26<14:45,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8017256259918213, Predicted Probability: 0.3097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.459051609039307, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2767/4000 [26:27<13:44,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.271419048309326, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.089577674865723, Predicted Probability: 0.9939, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2768/4000 [26:27<12:01,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.743414878845215, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.018758296966553, Predicted Probability: 0.9823, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2769/4000 [26:28<12:55,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1891512870788574, Predicted Probability: 0.0396, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0955560207366943, Predicted Probability: 0.8905, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2770/4000 [26:28<10:18,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1624040603637695, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.884264945983887, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2771/4000 [26:28<09:31,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.458132266998291, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1611855030059814, Predicted Probability: 0.9593, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2772/4000 [26:29<11:07,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.466327667236328, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1043577194213867, Predicted Probability: 0.1087, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2773/4000 [26:30<13:10,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6827712059021, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.204540252685547, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2774/4000 [26:31<14:15,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.5576276779174805, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8532257080078125, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2775/4000 [26:31<12:14,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.139827728271484, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2743334770202637, Predicted Probability: 0.9635, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2776/4000 [26:32<13:12,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3571231365203857, Predicted Probability: 0.0865, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.436272621154785, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2777/4000 [26:33<13:40,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.916041851043701, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7317280769348145, Predicted Probability: 0.8496, Prediction: 1.0

Epoch 1/3:  69%|██████▉   | 2778/4000 [26:33<12:57,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8673601150512695, Predicted Probability: 0.9795, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.104165554046631, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  69%|██████▉   | 2779/4000 [26:34<11:50,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.945949077606201, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3253424167633057, Predicted Probability: 0.9653, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2780/4000 [26:34<12:46,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7262051105499268, Predicted Probability: 0.9386, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.631060600280762, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2781/4000 [26:35<11:11,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.496857166290283, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1442790031433105, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2782/4000 [26:36<12:30,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9212357997894287, Predicted Probability: 0.2847, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.516387939453125, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2783/4000 [26:36<13:08,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.851022720336914, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8959966897964478, Predicted Probability: 0.8694, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2784/4000 [26:37<11:27,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.880875110626221, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.637128829956055, Predicted Probability: 0.9904, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -1.6309932470321655, Predicted Probability: 0.1637, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.254454612731934, Predicted Probability: 0.9860, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2786/4000 [26:38<10:55,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.260046005249023, Predicted Probability: 0.0139, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.622502326965332, Predicted Probability: 0.0097, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2787/4000 [26:38<08:52,  2.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.0439515113830566, Predicted Probability: 0.9545, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8079423904418945, Predicted Probability: 0.9783, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2788/4000 [26:38<10:39,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.546175956726074, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7785143256187439, Predicted Probability: 0.6854, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2789/4000 [26:39<09:41,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.234551340341568, Predicted Probability: 0.5584, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2890114784240723, Predicted Probability: 0.0920, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2790/4000 [26:40<11:00,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7461172342300415, Predicted Probability: 0.8515, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.177497863769531, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2791/4000 [26:40<12:12,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.008988380432129, Predicted Probability: 0.9530, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.499925136566162, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2792/4000 [26:41<10:45,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8103969693183899, Predicted Probability: 0.3078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.718184947967529, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2793/4000 [26:41<09:45,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.5847707986831665, Predicted Probability: 0.1701, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5834884643554688, Predicted Probability: 0.0270, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2794/4000 [26:41<09:03,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.797568917274475, Predicted Probability: 0.1421, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.40710973739624, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2795/4000 [26:42<10:37,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2056994438171387, Predicted Probability: 0.7695, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.381107330322266, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2796/4000 [26:42<09:36,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.032623052597046, Predicted Probability: 0.2626, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.694382667541504, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2797/4000 [26:43<11:10,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2024993896484375, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9501569271087646, Predicted Probability: 0.8755, Prediction: 1.0

Epoch 1/3:  70%|██████▉   | 2798/4000 [26:43<09:04,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8835880160331726, Predicted Probability: 0.7076, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.025323867797852, Predicted Probability: 0.0175, Prediction: 0.0

Epoch 1/3:  70%|██████▉   | 2799/4000 [26:44<11:00,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.065049886703491, Predicted Probability: 0.1125, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9341912269592285, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2800/4000 [26:45<12:25,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.641776084899902, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9450807571411133, Predicted Probability: 0.0190, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2801/4000 [26:45<11:19,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.246632099151611, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.659310817718506, Predicted Probability: 0.9346, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2803/4000 [26:46<08:59,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.334340572357178, Predicted Probability: 0.9871, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.01340913772583, Predicted Probability: 0.0178, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 5.023504257202148, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.623386383056641, Predicted Probability: 0.0097, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2804/4000 [26:47<09:53,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0442222356796265, Predicted Probability: 0.2603, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -3.7019529342651367, Predicted Probability: 0.0241, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2806/4000 [26:48<09:11,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.392695903778076, Predicted Probability: 0.0122, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7311842441558838, Predicted Probability: 0.1504, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 5.758155345916748, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.331193447113037, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2807/4000 [26:48<10:53,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.709508895874023, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.131824493408203, Predicted Probability: 0.8940, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2808/4000 [26:49<09:57,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.6357951164245605, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3293137848377228, Predicted Probability: 0.5816, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2809/4000 [26:49<10:08,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.967472791671753, Predicted Probability: 0.1227, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7110939025878906, Predicted Probability: 0.9377, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2810/4000 [26:50<12:03,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.675539493560791, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.669569969177246, Predicted Probability: 0.0093, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2811/4000 [26:51<13:00,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.798340320587158, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.685922622680664, Predicted Probability: 0.9362, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2812/4000 [26:52<13:29,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7080302238464355, Predicted Probability: 0.0239, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9707890748977661, Predicted Probability: 0.8777, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2813/4000 [26:52<11:39,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.312978744506836, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.747592449188232, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2814/4000 [26:53<12:59,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.673912525177002, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.217226028442383, Predicted Probability: 0.0145, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2815/4000 [26:53<11:18,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6583688259124756, Predicted Probability: 0.0251, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.254171848297119, Predicted Probability: 0.0140, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2816/4000 [26:54<13:05,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.537614822387695, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.988054037094116, Predicted Probability: 0.0182, Prediction: 0.0

Epoch 1/3:  70%|███████   | 2817/4000 [26:55<13:29,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.777008056640625, Predicted Probability: 0.0084, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.242896795272827, Predicted Probability: 0.9040, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2818/4000 [26:55<11:37,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5107741355895996, Predicted Probability: 0.9249, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.8677263259887695, Predicted Probability: 0.9924, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2819/4000 [26:56<11:48,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.679002285003662, Predicted Probability: 0.9358, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3485115766525269, Predicted Probability: 0.7939, Prediction: 1.0

Epoch 1/3:  70%|███████   | 2820/4000 [26:57<12:44,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.466734409332275, Predicted Probability: 0.0114, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9985852241516113, Predicted Probability: 0.8806, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2821/4000 [26:57<11:10,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.315816879272461, Predicted Probability: 0.0898, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.13647723197937, Predicted Probability: 0.9584, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2822/4000 [26:58<12:09,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3105077743530273, Predicted Probability: 0.9648, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8462852239608765, Predicted Probability: 0.1363, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2823/4000 [26:59<12:45,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1155343055725098, Predicted Probability: 0.8924, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.389164447784424, Predicted Probability: 0.0326, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2824/4000 [26:59<13:20,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.656714916229248, Predicted Probability: 0.0656, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.27836012840271, Predicted Probability: 0.9071, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2825/4000 [27:00<13:53,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.909191131591797, Predicted Probability: 0.0197, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.474764347076416, Predicted Probability: 0.1862, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2826/4000 [27:01<14:01,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3444719314575195, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2198803424835205, Predicted Probability: 0.9020, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2827/4000 [27:01<11:01,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.056036949157715, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.498408317565918, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2828/4000 [27:02<10:51,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.717186450958252, Predicted Probability: 0.9380, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.709536552429199, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2829/4000 [27:02<11:46,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.221111297607422, Predicted Probability: 0.9616, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.263846397399902, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2830/4000 [27:03<11:20,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4199891090393066, Predicted Probability: 0.0317, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9373509883880615, Predicted Probability: 0.9497, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2831/4000 [27:04<12:32,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3605735301971436, Predicted Probability: 0.0336, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7297728061676025, Predicted Probability: 0.0234, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2832/4000 [27:04<10:56,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4972493648529053, Predicted Probability: 0.9706, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.871192932128906, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2833/4000 [27:04<10:48,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.577799081802368, Predicted Probability: 0.9294, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.994621753692627, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2834/4000 [27:05<11:43,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.293127536773682, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4104485511779785, Predicted Probability: 0.9176, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2835/4000 [27:06<12:58,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.36385321617126465, Predicted Probability: 0.5900, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.716935157775879, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2836/4000 [27:07<13:37,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.944425582885742, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2847938537597656, Predicted Probability: 0.9639, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2837/4000 [27:08<14:06,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4862895011901855, Predicted Probability: 0.9232, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.732429027557373, Predicted Probability: 0.0234, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2838/4000 [27:08<11:06,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.629393100738525, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.870053291320801, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2839/4000 [27:09<11:58,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.550743579864502, Predicted Probability: 0.9276, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.08061146736145, Predicted Probability: 0.0439, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2840/4000 [27:09<12:34,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6358702182769775, Predicted Probability: 0.9743, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3460211753845215, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2841/4000 [27:10<10:56,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.450711250305176, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9790242910385132, Predicted Probability: 0.2731, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2842/4000 [27:10<11:55,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5616743564605713, Predicted Probability: 0.3632, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.490599632263184, Predicted Probability: 0.0111, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2843/4000 [27:11<10:36,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.096683025360107, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3294196128845215, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2844/4000 [27:11<09:30,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.627556800842285, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9121649265289307, Predicted Probability: 0.8713, Prediction: 1.0

Epoch 1/3:  71%|███████   | 2845/4000 [27:12<11:36,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.919079780578613, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.192935943603516, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2846/4000 [27:13<12:58,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.364327907562256, Predicted Probability: 0.0334, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.587852478027344, Predicted Probability: 0.0101, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2847/4000 [27:14<13:50,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.34068489074707, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.896000862121582, Predicted Probability: 0.0199, Prediction: 0.0

Epoch 1/3:  71%|███████   | 2849/4000 [27:15<11:04,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.630474328994751, Predicted Probability: 0.0258, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6435484886169434, Predicted Probability: 0.8380, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.339141368865967, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6624298095703125, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2850/4000 [27:15<09:50,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8002161979675293, Predicted Probability: 0.6900, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.10118293762207, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 1/3:  71%|███████▏  | 2851/4000 [27:15<08:07,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.082841396331787, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.758084297180176, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2852/4000 [27:15<06:54,  2.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.593425273895264, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.093514442443848, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2853/4000 [27:16<06:55,  2.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.305399626493454, Predicted Probability: 0.5758, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6243057250976562, Predicted Probability: 0.0676, Prediction: 0.0

Epoch 1/3:  71%|███████▏  | 2854/4000 [27:16<07:56,  2.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3393235206604, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3725638389587402, Predicted Probability: 0.9147, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2855/4000 [27:17<09:59,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5735340118408203, Predicted Probability: 0.0273, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.207675933837891, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2856/4000 [27:18<10:07,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.658689498901367, Predicted Probability: 0.0655, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.716143608093262, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2857/4000 [27:18<09:11,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.162742614746094, Predicted Probability: 0.9847, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.60261344909668, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2858/4000 [27:18<08:56,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8753520846366882, Predicted Probability: 0.2941, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.992356300354004, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 1/3:  71%|███████▏  | 2859/4000 [27:19<08:25,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.145689964294434, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.32555437088012695, Predicted Probability: 0.4193, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2860/4000 [27:20<10:15,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.140374183654785, Predicted Probability: 0.9585, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.040968894958496, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2861/4000 [27:20<09:23,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.657116413116455, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.246711254119873, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2862/4000 [27:21<10:56,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6218924522399902, Predicted Probability: 0.9323, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.070974349975586, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2863/4000 [27:22<12:01,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.479174613952637, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5744481086730957, Predicted Probability: 0.0708, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2864/4000 [27:22<12:54,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9829678535461426, Predicted Probability: 0.0183, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1081230640411377, Predicted Probability: 0.1083, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2865/4000 [27:23<11:07,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.945244312286377, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.954463481903076, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2866/4000 [27:23<09:58,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.230003356933594, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1670284271240234, Predicted Probability: 0.1028, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2867/4000 [27:24<11:42,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7695980072021484, Predicted Probability: 0.0225, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.38315486907959, Predicted Probability: 0.0123, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2868/4000 [27:25<12:35,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.252439498901367, Predicted Probability: 0.0140, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.885021924972534, Predicted Probability: 0.0529, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2869/4000 [27:25<12:47,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7677090764045715, Predicted Probability: 0.3170, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0986077785491943, Predicted Probability: 0.8908, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2870/4000 [27:26<11:34,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1775758266448975, Predicted Probability: 0.9600, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.84805965423584, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2871/4000 [27:26<11:09,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0567349195480347, Predicted Probability: 0.2579, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.977972507476807, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2872/4000 [27:27<12:10,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1672418117523193, Predicted Probability: 0.9596, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.552637577056885, Predicted Probability: 0.0104, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2873/4000 [27:28<12:43,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.385653495788574, Predicted Probability: 0.9673, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.523555755615234, Predicted Probability: 0.0107, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2874/4000 [27:28<10:05,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.803549766540527, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.590529918670654, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2875/4000 [27:29<11:10,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0336755514144897, Predicted Probability: 0.7376, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.19476318359375, Predicted Probability: 0.0394, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2876/4000 [27:29<09:23,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3444511890411377, Predicted Probability: 0.0875, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.07237014919519424, Predicted Probability: 0.5181, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2877/4000 [27:30<11:25,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.0153987407684326, Predicted Probability: 0.7341, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.756687641143799, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2878/4000 [27:31<12:27,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0956923961639404, Predicted Probability: 0.2505, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3805389404296875, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2879/4000 [27:32<13:02,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9276691675186157, Predicted Probability: 0.8730, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.468176364898682, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2880/4000 [27:32<13:11,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.627823829650879, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1741318702697754, Predicted Probability: 0.9598, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2881/4000 [27:33<12:16,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9306254982948303, Predicted Probability: 0.2828, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.274045944213867, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2882/4000 [27:34<12:31,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.9005552530288696, Predicted Probability: 0.1300, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2579567432403564, Predicted Probability: 0.7787, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2883/4000 [27:34<09:54,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.506584644317627, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5011887550354, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2884/4000 [27:34<09:20,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.198819637298584, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4051072597503662, Predicted Probability: 0.1970, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2885/4000 [27:35<08:34,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.651240348815918, Predicted Probability: 0.9341, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.847199440002441, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2886/4000 [27:35<09:59,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7653555870056152, Predicted Probability: 0.8539, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.720029830932617, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2887/4000 [27:36<11:04,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2507708072662354, Predicted Probability: 0.9627, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.862328052520752, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2888/4000 [27:37<12:14,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0820322036743164, Predicted Probability: 0.8891, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.093096733093262, Predicted Probability: 0.0164, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2889/4000 [27:38<12:55,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.085990905761719, Predicted Probability: 0.0165, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.565112590789795, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2890/4000 [27:38<13:23,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.551244735717773, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3498027324676514, Predicted Probability: 0.9661, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2891/4000 [27:39<12:23,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4788339138031006, Predicted Probability: 0.9226, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.707878589630127, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2892/4000 [27:39<09:47,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.273327350616455, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.015944480895996, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2893/4000 [27:40<11:11,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.13465675711631775, Predicted Probability: 0.4664, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.708671569824219, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2894/4000 [27:40<09:49,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.335907459259033, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.291173458099365, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2895/4000 [27:41<10:12,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4079524874687195, Predicted Probability: 0.3994, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.633218765258789, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 1/3:  72%|███████▏  | 2896/4000 [27:42<12:12,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.252225875854492, Predicted Probability: 0.0140, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8641533851623535, Predicted Probability: 0.0205, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2897/4000 [27:43<12:51,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6196773052215576, Predicted Probability: 0.0261, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.021951675415039, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2898/4000 [27:43<12:55,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0910401344299316, Predicted Probability: 0.9565, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.617069721221924, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 1/3:  72%|███████▏  | 2899/4000 [27:44<11:07,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3366531133651733, Predicted Probability: 0.2081, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.879330635070801, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  72%|███████▎  | 2900/4000 [27:44<10:17,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.661532402038574, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.414755821228027, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2901/4000 [27:45<11:34,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0640792846679688, Predicted Probability: 0.8874, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.222106695175171, Predicted Probability: 0.0978, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2902/4000 [27:45<10:09,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.131961345672607, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.436647415161133, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2903/4000 [27:46<11:27,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1483509540557861, Predicted Probability: 0.7592, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.574723243713379, Predicted Probability: 0.0273, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2904/4000 [27:47<10:23,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9369356632232666, Predicted Probability: 0.9809, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.263434648513794, Predicted Probability: 0.9632, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2905/4000 [27:47<09:16,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.818636417388916, Predicted Probability: 0.9785, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.50429630279541, Predicted Probability: 0.0109, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2906/4000 [27:48<10:56,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.700949192047119, Predicted Probability: 0.0241, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.322317123413086, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2907/4000 [27:48<11:39,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4457855224609375, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8654706478118896, Predicted Probability: 0.8659, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2908/4000 [27:49<10:06,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8281807899475098, Predicted Probability: 0.0213, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.270050048828125, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2909/4000 [27:49<10:28,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4797985553741455, Predicted Probability: 0.0773, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.667748928070068, Predicted Probability: 0.0093, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2910/4000 [27:50<11:35,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.564823150634766, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1379547119140625, Predicted Probability: 0.9843, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2911/4000 [27:51<12:19,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.50738525390625, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9692100286483765, Predicted Probability: 0.8775, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2912/4000 [27:52<12:48,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9722650051116943, Predicted Probability: 0.9513, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3822741508483887, Predicted Probability: 0.0329, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2914/4000 [27:52<09:04,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.042808532714844, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.819378852844238, Predicted Probability: 0.9920, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.953325271606445, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3961052894592285, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2915/4000 [27:53<08:16,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.63258695602417, Predicted Probability: 0.0258, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.732549667358398, Predicted Probability: 0.9913, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2916/4000 [27:53<07:59,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9418184757232666, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8701202869415283, Predicted Probability: 0.0537, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2917/4000 [27:53<06:42,  2.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7295942306518555, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.602604866027832, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2918/4000 [27:54<06:40,  2.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.264828681945801, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5429368019104, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2919/4000 [27:55<08:48,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.829520225524902, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7757925987243652, Predicted Probability: 0.9776, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2920/4000 [27:55<08:11,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.731928825378418, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.163650035858154, Predicted Probability: 0.9847, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2921/4000 [27:55<08:10,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.017390489578247, Predicted Probability: 0.0466, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.783219575881958, Predicted Probability: 0.8561, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2922/4000 [27:56<06:50,  2.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.140816688537598, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.025820255279541, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2923/4000 [27:56<06:43,  2.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.34963321685791, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.043562889099121, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2924/4000 [27:56<06:43,  2.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.353306293487549, Predicted Probability: 0.9132, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.868223190307617, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2925/4000 [27:57<07:02,  2.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2762627601623535, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7719771265983582, Predicted Probability: 0.6839, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2926/4000 [27:57<09:02,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8224367499351501, Predicted Probability: 0.3052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.040614604949951, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2927/4000 [27:58<10:42,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.681963920593262, Predicted Probability: 0.9908, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.376420021057129, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2928/4000 [27:59<11:47,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.270796775817871, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9111328125, Predicted Probability: 0.9484, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2930/4000 [28:00<09:36,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7064647674560547, Predicted Probability: 0.0240, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.233229637145996, Predicted Probability: 0.9032, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -4.5744524002075195, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.020929336547852, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2931/4000 [28:01<10:38,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.83383846282959, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.988163471221924, Predicted Probability: 0.9818, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2932/4000 [28:02<11:18,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.246488571166992, Predicted Probability: 0.9043, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.705784797668457, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2933/4000 [28:02<09:01,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.721805572509766, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.740743637084961, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2934/4000 [28:02<08:21,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.768306255340576, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.547257900238037, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2935/4000 [28:02<07:50,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.628610372543335, Predicted Probability: 0.9741, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.191567897796631, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2936/4000 [28:03<07:27,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.725329399108887, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.738400936126709, Predicted Probability: 0.0232, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2937/4000 [28:04<09:25,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.106321811676025, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.103562355041504, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  73%|███████▎  | 2938/4000 [28:04<09:25,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.860849142074585, Predicted Probability: 0.9794, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6349565982818604, Predicted Probability: 0.9331, Prediction: 1.0

Epoch 1/3:  73%|███████▎  | 2939/4000 [28:05<08:38,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.3147077560424805, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5432569980621338, Predicted Probability: 0.3674, Prediction: 0.0

Epoch 1/3:  74%|███████▎  | 2940/4000 [28:05<10:03,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.324619770050049, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.204456329345703, Predicted Probability: 0.9610, Prediction: 1.0

Epoch 1/3:  74%|███████▎  | 2942/4000 [28:06<07:20,  2.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7561032176017761, Predicted Probability: 0.6805, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.615055084228516, Predicted Probability: 0.0036, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.484614849090576, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.236776828765869, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  74%|███████▎  | 2943/4000 [28:07<09:03,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8200759887695312, Predicted Probability: 0.0215, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7288997173309326, Predicted Probability: 0.0235, Prediction: 0.0

Epoch 1/3:  74%|███████▎  | 2944/4000 [28:07<08:23,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.736616134643555, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.319044589996338, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  74%|███████▎  | 2945/4000 [28:08<09:53,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0688583850860596, Predicted Probability: 0.8878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7404162883758545, Predicted Probability: 0.0232, Prediction: 0.0

Epoch 1/3:  74%|███████▎  | 2946/4000 [28:08<09:18,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0279541015625, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.013893127441406, Predicted Probability: 0.0066, Prediction: 0.0

Epoch 1/3:  74%|███████▎  | 2947/4000 [28:09<08:26,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.490889072418213, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.816802978515625, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 1/3:  74%|███████▎  | 2948/4000 [28:09<09:42,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.289839744567871, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8807356357574463, Predicted Probability: 0.8677, Prediction: 1.0

Epoch 1/3:  74%|███████▎  | 2949/4000 [28:10<08:50,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.57504940032959, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.542306423187256, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2950/4000 [28:10<08:08,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.3864336013793945, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.223262786865234, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2951/4000 [28:11<09:48,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.219576358795166, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.049838066101074, Predicted Probability: 0.0171, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2952/4000 [28:11<08:49,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.140733003616333, Predicted Probability: 0.0415, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.4469313621521, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2953/4000 [28:12<09:20,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4465339183807373, Predicted Probability: 0.0797, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7420146465301514, Predicted Probability: 0.9395, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2954/4000 [28:12<07:36,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.024153709411621, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.985968589782715, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2955/4000 [28:12<07:15,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.393939733505249, Predicted Probability: 0.9675, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.628530740737915, Predicted Probability: 0.9327, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2956/4000 [28:13<07:02,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.406452655792236, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6447954177856445, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2957/4000 [28:14<09:00,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.326865196228027, Predicted Probability: 0.0130, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.261202812194824, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2958/4000 [28:14<08:15,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.711827754974365, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5169851779937744, Predicted Probability: 0.9712, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2959/4000 [28:14<07:43,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.237824440002441, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.880861282348633, Predicted Probability: 0.0531, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2960/4000 [28:15<09:30,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.665107011795044, Predicted Probability: 0.0651, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.226847171783447, Predicted Probability: 0.0144, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2961/4000 [28:16<10:37,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.671759009361267, Predicted Probability: 0.8418, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.720775604248047, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2962/4000 [28:16<09:22,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.180649280548096, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7445154190063477, Predicted Probability: 0.9769, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2963/4000 [28:17<09:18,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.897860050201416, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3411706686019897, Predicted Probability: 0.2073, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2964/4000 [28:18<10:24,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.845771551132202, Predicted Probability: 0.9791, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.431769371032715, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2965/4000 [28:18<09:12,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.94424295425415, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2960305213928223, Predicted Probability: 0.0915, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2966/4000 [28:19<10:29,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.681393623352051, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.428158283233643, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2967/4000 [28:20<11:29,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.342240333557129, Predicted Probability: 0.0342, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.707228183746338, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2968/4000 [28:21<13:15,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.292664527893066, Predicted Probability: 0.0135, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.623381614685059, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2969/4000 [28:21<13:06,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.130016803741455, Predicted Probability: 0.9581, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.048410892486572, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2970/4000 [28:22<12:57,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.748300552368164, Predicted Probability: 0.0230, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.446835517883301, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2971/4000 [28:22<11:20,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.006106376647949, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7752206325531006, Predicted Probability: 0.8551, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2972/4000 [28:23<09:19,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5124359130859375, Predicted Probability: 0.9891, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.121167182922363, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2973/4000 [28:23<09:22,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5627386569976807, Predicted Probability: 0.0716, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.807281017303467, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2974/4000 [28:24<09:18,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8735575675964355, Predicted Probability: 0.0076, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9146389961242676, Predicted Probability: 0.9486, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2975/4000 [28:25<10:39,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7715225219726562, Predicted Probability: 0.9411, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6060261726379395, Predicted Probability: 0.0264, Prediction: 0.0

Epoch 1/3:  74%|███████▍  | 2976/4000 [28:25<08:51,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.15997314453125, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0779730081558228, Predicted Probability: 0.7461, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2977/4000 [28:26<10:08,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.144984245300293, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.156002044677734, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2978/4000 [28:26<09:01,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.754956245422363, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1752333641052246, Predicted Probability: 0.8980, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2979/4000 [28:27<09:25,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7537739276885986, Predicted Probability: 0.9771, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2733209133148193, Predicted Probability: 0.9635, Prediction: 1.0

Epoch 1/3:  74%|███████▍  | 2980/4000 [28:27<07:39,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.437501907348633, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.275819778442383, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2981/4000 [28:27<07:17,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.414233684539795, Predicted Probability: 0.9880, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8308260440826416, Predicted Probability: 0.9788, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2983/4000 [28:28<05:54,  2.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9523520469665527, Predicted Probability: 0.1243, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9663078784942627, Predicted Probability: 0.9814, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.603471279144287, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.211647987365723, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2984/4000 [28:28<05:57,  2.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.272545099258423, Predicted Probability: 0.9635, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.783348083496094, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2985/4000 [28:29<06:00,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.455615520477295, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2066314220428467, Predicted Probability: 0.0389, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2986/4000 [28:29<06:04,  2.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.576179027557373, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.671278953552246, Predicted Probability: 0.9907, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2987/4000 [28:30<08:02,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.79160213470459, Predicted Probability: 0.0221, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.064998626708984, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2988/4000 [28:30<09:17,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.067128896713257, Predicted Probability: 0.8877, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.395519733428955, Predicted Probability: 0.8015, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2989/4000 [28:31<10:25,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.370574951171875, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.41994786262512207, Predicted Probability: 0.3965, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2990/4000 [28:32<09:12,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.357186794281006, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5273101329803467, Predicted Probability: 0.9715, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2991/4000 [28:32<10:43,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5577831268310547, Predicted Probability: 0.0277, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9191251993179321, Predicted Probability: 0.2851, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2992/4000 [28:33<11:15,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9451934099197388, Predicted Probability: 0.8749, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.748871803283691, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2993/4000 [28:34<11:46,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.361480474472046, Predicted Probability: 0.9138, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.931121826171875, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2994/4000 [28:35<11:50,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7955243587493896, Predicted Probability: 0.0220, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0590298175811768, Predicted Probability: 0.8869, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2995/4000 [28:35<12:00,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.453227996826172, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.09536319971084595, Predicted Probability: 0.5238, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2996/4000 [28:36<09:28,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.610686302185059, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.93422794342041, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2997/4000 [28:36<08:31,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.335304260253906, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.241010904312134, Predicted Probability: 0.9623, Prediction: 1.0

Epoch 1/3:  75%|███████▍  | 2998/4000 [28:37<09:33,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.329993486404419, Predicted Probability: 0.9113, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.610391616821289, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  75%|███████▍  | 2999/4000 [28:37<09:49,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2321105003356934, Predicted Probability: 0.9620, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.715676307678223, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3000/4000 [28:38<08:45,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.773072242736816, Predicted Probability: 0.9916, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.963613033294678, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3001/4000 [28:39<10:17,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.253715515136719, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.765805244445801, Predicted Probability: 0.0226, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3002/4000 [28:39<11:18,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5128984451293945, Predicted Probability: 0.0108, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.351765155792236, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3003/4000 [28:40<11:44,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8125630617141724, Predicted Probability: 0.3073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.789610862731934, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3004/4000 [28:41<12:03,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.03812575340271, Predicted Probability: 0.9543, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.027591228485107, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3005/4000 [28:42<12:05,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.945611953735352, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3692352771759033, Predicted Probability: 0.4087, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3006/4000 [28:42<12:18,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6321274042129517, Predicted Probability: 0.3470, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.744599342346191, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3007/4000 [28:43<12:26,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6111936569213867, Predicted Probability: 0.0263, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9344375133514404, Predicted Probability: 0.9808, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3009/4000 [28:44<08:19,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5288310050964355, Predicted Probability: 0.9893, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.322141170501709, Predicted Probability: 0.9982, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -6.103331565856934, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.987967491149902, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3010/4000 [28:44<08:31,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9801578521728516, Predicted Probability: 0.9817, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.29532578587532043, Predicted Probability: 0.5733, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3011/4000 [28:45<09:31,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0198593139648438, Predicted Probability: 0.8829, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.30430793762207, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3012/4000 [28:46<10:13,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.020078182220459, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.400979518890381, Predicted Probability: 0.9169, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3013/4000 [28:46<08:59,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.784271240234375, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.037621021270752, Predicted Probability: 0.9827, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3014/4000 [28:47<10:00,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.687034606933594, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3830924034118652, Predicted Probability: 0.9155, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3015/4000 [28:48<10:28,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.352979898452759, Predicted Probability: 0.9132, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.19627046585083, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3016/4000 [28:48<10:01,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.212120532989502, Predicted Probability: 0.2293, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.94968843460083, Predicted Probability: 0.0189, Prediction: 0.0

Epoch 1/3:  75%|███████▌  | 3017/4000 [28:49<10:52,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.247008800506592, Predicted Probability: 0.0374, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6304179430007935, Predicted Probability: 0.6526, Prediction: 1.0

Epoch 1/3:  75%|███████▌  | 3018/4000 [28:50<11:17,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.599234104156494, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0724992752075195, Predicted Probability: 0.8882, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3020/4000 [28:50<07:11,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.021267890930176, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.798346042633057, Predicted Probability: 0.0030, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.105257987976074, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.092574119567871, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3021/4000 [28:50<06:01,  2.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.0377020835876465, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5732741355896, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3022/4000 [28:51<06:03,  2.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.357754230499268, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6961060762405396, Predicted Probability: 0.6673, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3023/4000 [28:51<08:03,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.410763263702393, Predicted Probability: 0.0120, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.0012708306312561035, Predicted Probability: 0.5003, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3024/4000 [28:52<07:26,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.533360004425049, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.419674396514893, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3025/4000 [28:52<06:59,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9438605308532715, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1460671424865723, Predicted Probability: 0.9588, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3026/4000 [28:53<08:26,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8898402452468872, Predicted Probability: 0.2911, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3440608978271484, Predicted Probability: 0.0875, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3027/4000 [28:54<09:26,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1648969650268555, Predicted Probability: 0.8971, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.116244316101074, Predicted Probability: 0.0160, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3028/4000 [28:54<08:27,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.143038749694824, Predicted Probability: 0.9844, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.221189498901367, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3029/4000 [28:54<07:43,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.527371883392334, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.045278310775757, Predicted Probability: 0.1145, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3030/4000 [28:55<08:45,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.981443166732788, Predicted Probability: 0.8788, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.197731018066406, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3031/4000 [28:56<10:29,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.643299102783203, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.078588485717773, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3032/4000 [28:57<11:02,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.295180797576904, Predicted Probability: 0.0135, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.931936025619507, Predicted Probability: 0.9494, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3033/4000 [28:57<09:53,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1553876399993896, Predicted Probability: 0.1038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.782262325286865, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3034/4000 [28:58<09:02,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.683309078216553, Predicted Probability: 0.9908, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1929306983947754, Predicted Probability: 0.9606, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3035/4000 [28:58<08:05,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.303370952606201, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.00791597366333, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3036/4000 [28:58<07:29,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.304102420806885, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.316093921661377, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3037/4000 [28:59<07:02,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.125241756439209, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.703891277313232, Predicted Probability: 0.9910, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3038/4000 [29:00<08:44,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.429769515991211, Predicted Probability: 0.0809, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.323687553405762, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3039/4000 [29:00<08:18,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.890668869018555, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.874464988708496, Predicted Probability: 0.0534, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3040/4000 [29:01<09:41,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.657581329345703, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.02336311340332, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3042/4000 [29:01<06:56,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.10387921333313, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.373199462890625, Predicted Probability: 0.9875, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -5.244262218475342, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0611988306045532, Predicted Probability: 0.7429, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3043/4000 [29:02<07:26,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.965665817260742, Predicted Probability: 0.9510, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.152034282684326, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3044/4000 [29:03<08:45,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.28001070022583, Predicted Probability: 0.9072, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1518235206604, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3045/4000 [29:03<07:09,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.00161075592041, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1326095163822174, Predicted Probability: 0.5331, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3046/4000 [29:04<08:44,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4814295768737793, Predicted Probability: 0.9702, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.533638000488281, Predicted Probability: 0.0106, Prediction: 0.0

Epoch 1/3:  76%|███████▌  | 3047/4000 [29:04<08:11,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.637784481048584, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.836637020111084, Predicted Probability: 0.9446, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3048/4000 [29:05<09:16,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.255929946899414, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2804064750671387, Predicted Probability: 0.9072, Prediction: 1.0

Epoch 1/3:  76%|███████▌  | 3049/4000 [29:05<08:13,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.200654983520508, Predicted Probability: 0.9852, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.212433815002441, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3050/4000 [29:05<06:42,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.211802959442139, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.565017223358154, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3051/4000 [29:06<06:47,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4582550525665283, Predicted Probability: 0.1887, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6259236335754395, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  76%|███████▋  | 3052/4000 [29:07<08:25,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.25728702545166, Predicted Probability: 0.0947, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4368820190429688, Predicted Probability: 0.9688, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3053/4000 [29:07<09:27,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4595866203308105, Predicted Probability: 0.0305, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.694384574890137, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  76%|███████▋  | 3054/4000 [29:08<10:13,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4749908447265625, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9385173320770264, Predicted Probability: 0.9809, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3055/4000 [29:08<08:55,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.225391149520874, Predicted Probability: 0.9025, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1791181564331055, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3056/4000 [29:09<08:44,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8415040969848633, Predicted Probability: 0.9449, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.968420147895813, Predicted Probability: 0.8774, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3057/4000 [29:10<08:38,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3545544147491455, Predicted Probability: 0.9133, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.331029891967773, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3058/4000 [29:10<07:47,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.393779754638672, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.088119983673096, Predicted Probability: 0.9835, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3059/4000 [29:11<08:51,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.727409362792969, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3036060333251953, Predicted Probability: 0.9092, Prediction: 1.0

Epoch 1/3:  76%|███████▋  | 3060/4000 [29:11<09:39,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.278127908706665, Predicted Probability: 0.9070, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.984760761260986, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3061/4000 [29:12<10:34,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.358315467834473, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.790032386779785, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3062/4000 [29:13<11:08,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1781179904937744, Predicted Probability: 0.1017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.189192771911621, Predicted Probability: 0.0396, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3063/4000 [29:13<09:31,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.876564979553223, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.187597274780273, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3064/4000 [29:14<09:31,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.823781728744507, Predicted Probability: 0.9439, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3610968589782715, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3065/4000 [29:15<10:19,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4841957092285156, Predicted Probability: 0.9230, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.670344352722168, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3066/4000 [29:16<10:42,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.295210123062134, Predicted Probability: 0.9643, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.288945198059082, Predicted Probability: 0.0135, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3067/4000 [29:16<11:17,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.290413856506348, Predicted Probability: 0.9865, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.177901268005371, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3068/4000 [29:17<09:36,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.944766044616699, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.763049125671387, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3069/4000 [29:17<10:07,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.441505432128906, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2415597438812256, Predicted Probability: 0.2242, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3070/4000 [29:18<08:51,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5462658405303955, Predicted Probability: 0.9720, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.504619836807251, Predicted Probability: 0.9708, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3071/4000 [29:18<09:10,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.337904453277588, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6643701791763306, Predicted Probability: 0.6602, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3072/4000 [29:19<10:06,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0435643196105957, Predicted Probability: 0.8853, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.512415409088135, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3073/4000 [29:20<08:47,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.376079082489014, Predicted Probability: 0.9876, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8412957191467285, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3074/4000 [29:20<09:57,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.596706867218018, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.008430480957031, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3075/4000 [29:21<10:28,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3649749755859375, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5008358359336853, Predicted Probability: 0.3773, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3076/4000 [29:22<10:57,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.504604160785675, Predicted Probability: 0.3765, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4774703979492188, Predicted Probability: 0.0300, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3077/4000 [29:22<09:21,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.77085280418396, Predicted Probability: 0.0225, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.807210922241211, Predicted Probability: 0.9919, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3078/4000 [29:23<08:15,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.294633388519287, Predicted Probability: 0.9865, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8409019112586975, Predicted Probability: 0.3013, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3079/4000 [29:23<09:10,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.799973487854004, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6549351215362549, Predicted Probability: 0.1604, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3080/4000 [29:24<09:01,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.730871200561523, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.328841686248779, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3081/4000 [29:25<10:13,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.41316032409668, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.100245475769043, Predicted Probability: 0.0163, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3082/4000 [29:25<09:37,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2289063930511475, Predicted Probability: 0.9028, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.656491279602051, Predicted Probability: 0.9906, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3083/4000 [29:26<09:58,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2376518249511719, Predicted Probability: 0.2248, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4231890439987183, Predicted Probability: 0.8058, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3084/4000 [29:27<08:38,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.694504261016846, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.25263786315918, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3085/4000 [29:27<07:48,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.171561241149902, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.836334228515625, Predicted Probability: 0.9789, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3086/4000 [29:27<07:07,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.581960201263428, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.38578987121582, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3087/4000 [29:28<08:18,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.139652252197266, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8332993984222412, Predicted Probability: 0.3029, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3088/4000 [29:28<06:48,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8533788919448853, Predicted Probability: 0.7013, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.314871311187744, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3089/4000 [29:29<06:32,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8749191761016846, Predicted Probability: 0.0203, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.8203444480896, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3090/4000 [29:29<06:13,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8594601154327393, Predicted Probability: 0.9794, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.560884952545166, Predicted Probability: 0.9724, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3091/4000 [29:29<06:02,  2.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.695712566375732, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.667787790298462, Predicted Probability: 0.0649, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3092/4000 [29:30<07:42,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.513453960418701, Predicted Probability: 0.9711, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.084712028503418, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3093/4000 [29:30<07:06,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5887186527252197, Predicted Probability: 0.0269, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.469759941101074, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  77%|███████▋  | 3094/4000 [29:31<06:43,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.323280334472656, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.07011155784130096, Predicted Probability: 0.4825, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3095/4000 [29:32<08:26,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.369599342346191, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.099213600158691, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3096/4000 [29:33<09:43,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.907544136047363, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.346989631652832, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3097/4000 [29:33<08:28,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.919529914855957, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.414870023727417, Predicted Probability: 0.0318, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3098/4000 [29:34<09:12,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0208663940429688, Predicted Probability: 0.9535, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.366410732269287, Predicted Probability: 0.0125, Prediction: 0.0

Epoch 1/3:  77%|███████▋  | 3099/4000 [29:34<08:07,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.827704429626465, Predicted Probability: 0.9921, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.099737644195557, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3100/4000 [29:35<09:02,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.773704528808594, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.351298809051514, Predicted Probability: 0.9873, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3101/4000 [29:36<09:46,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.987669944763184, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.633462905883789, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3102/4000 [29:36<10:16,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2328057289123535, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9165854454040527, Predicted Probability: 0.8718, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3103/4000 [29:37<10:31,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9394731521606445, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6051939725875854, Predicted Probability: 0.8327, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3104/4000 [29:38<10:49,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.50806999206543, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.142625093460083, Predicted Probability: 0.9586, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3105/4000 [29:38<09:23,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.361076831817627, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.050510406494141, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3106/4000 [29:39<08:30,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.81281042098999, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3131492137908936, Predicted Probability: 0.9649, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3107/4000 [29:39<09:15,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9722806215286255, Predicted Probability: 0.2744, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.165839195251465, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3108/4000 [29:40<07:40,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.158607006072998, Predicted Probability: 0.0408, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.2108025550842285, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3109/4000 [29:40<08:43,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.261237621307373, Predicted Probability: 0.9631, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.91845178604126, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3111/4000 [29:41<07:36,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.967611312866211, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5932376384735107, Predicted Probability: 0.0696, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.589566707611084, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.636446475982666, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3112/4000 [29:42<09:02,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.153092861175537, Predicted Probability: 0.0155, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.380865097045898, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3113/4000 [29:42<07:13,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.849937915802002, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.556430816650391, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3114/4000 [29:43<08:29,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.006133556365967, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8683502674102783, Predicted Probability: 0.1337, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3115/4000 [29:44<07:35,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.667682647705078, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0790226459503174, Predicted Probability: 0.9560, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3116/4000 [29:44<06:14,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.669881820678711, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.093525409698486, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3117/4000 [29:44<06:01,  2.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6861088275909424, Predicted Probability: 0.0245, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.3168463706970215, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3118/4000 [29:45<05:55,  2.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.050634384155273, Predicted Probability: 0.0171, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9018514156341553, Predicted Probability: 0.9802, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3119/4000 [29:48<17:38,  1.20s/it]

Data point 1: Actual Class: 1.0, Final Logit: -0.0555424690246582, Predicted Probability: 0.4861, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.957394599914551, Predicted Probability: 0.0188, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3120/4000 [29:48<13:59,  1.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4722161293029785, Predicted Probability: 0.9699, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.711139678955078, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3121/4000 [29:49<12:58,  1.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8984251022338867, Predicted Probability: 0.2894, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.987825870513916, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3122/4000 [29:49<10:47,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.462747097015381, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.052011489868164, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3124/4000 [29:50<08:26,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.3741018772125244, Predicted Probability: 0.4076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.815610408782959, Predicted Probability: 0.0030, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.023227691650391, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.195731163024902, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3125/4000 [29:50<07:31,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.731072902679443, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.712865352630615, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3126/4000 [29:51<08:28,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.982415199279785, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.026256561279297, Predicted Probability: 0.8835, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3127/4000 [29:52<09:08,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.376150131225586, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.155029058456421, Predicted Probability: 0.8961, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3128/4000 [29:53<09:44,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9571399688720703, Predicted Probability: 0.8762, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7220327854156494, Predicted Probability: 0.0236, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3130/4000 [29:53<06:15,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.51911735534668, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.413852691650391, Predicted Probability: 0.9984, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 4.352591037750244, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.860558271408081, Predicted Probability: 0.9794, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3131/4000 [29:54<07:29,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9984893798828125, Predicted Probability: 0.2692, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.528059005737305, Predicted Probability: 0.0107, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3132/4000 [29:55<08:54,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.638521194458008, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.495938301086426, Predicted Probability: 0.9239, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3133/4000 [29:55<07:53,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.826566696166992, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.429389476776123, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3134/4000 [29:56<09:00,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.359043121337891, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1504292488098145, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3135/4000 [29:57<09:24,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.852966785430908, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.164682626724243, Predicted Probability: 0.1030, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3136/4000 [29:57<08:27,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.137198448181152, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.579813003540039, Predicted Probability: 0.9729, Prediction: 1.0

Epoch 1/3:  78%|███████▊  | 3137/4000 [29:58<09:05,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.153611898422241, Predicted Probability: 0.8960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.106266021728516, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3138/4000 [29:59<09:47,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.96528434753418, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.38533616065979, Predicted Probability: 0.0328, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3139/4000 [29:59<10:03,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5516703128814697, Predicted Probability: 0.0723, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6687517166137695, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  78%|███████▊  | 3140/4000 [30:00<10:19,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.742024898529053, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5765652656555176, Predicted Probability: 0.8287, Prediction: 1.0

Epoch 1/3:  79%|███████▊  | 3141/4000 [30:01<10:15,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.336522579193115, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2522549629211426, Predicted Probability: 0.9048, Prediction: 1.0

Epoch 1/3:  79%|███████▊  | 3142/4000 [30:02<10:33,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.490182399749756, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.415118217468262, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  79%|███████▊  | 3143/4000 [30:02<10:37,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.083859920501709, Predicted Probability: 0.9562, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.710920333862305, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  79%|███████▊  | 3144/4000 [30:03<10:44,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.952550411224365, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.024031162261963, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  79%|███████▊  | 3145/4000 [30:04<10:06,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.114176273345947, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.491316795349121, Predicted Probability: 0.9235, Prediction: 1.0

Epoch 1/3:  79%|███████▊  | 3146/4000 [30:04<08:43,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.433983325958252, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.724404335021973, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  79%|███████▊  | 3147/4000 [30:05<09:20,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2615137100219727, Predicted Probability: 0.9056, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.322660446166992, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  79%|███████▊  | 3148/4000 [30:06<09:43,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9037516713142395, Predicted Probability: 0.2883, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.833424091339111, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 1/3:  79%|███████▊  | 3149/4000 [30:06<08:28,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.380862712860107, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.060640811920166, Predicted Probability: 0.0448, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3150/4000 [30:06<07:30,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8156323432922363, Predicted Probability: 0.9785, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.921366214752197, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3151/4000 [30:07<08:32,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6680517196655273, Predicted Probability: 0.3389, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.72247314453125, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3152/4000 [30:08<09:08,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.294665813446045, Predicted Probability: 0.9084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.378033638000488, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3153/4000 [30:09<09:48,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.778997421264648, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.422277927398682, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3154/4000 [30:09<07:42,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.278774261474609, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.081299781799316, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3155/4000 [30:09<07:42,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.900743007659912, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2690510749816895, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3156/4000 [30:10<08:32,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1729276180267334, Predicted Probability: 0.9598, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.403382301330566, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3157/4000 [30:11<07:34,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.552391529083252, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.6561287641525269, Predicted Probability: 0.8397, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3158/4000 [30:11<08:31,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.935502052307129, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.151625156402588, Predicted Probability: 0.8958, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3159/4000 [30:12<09:06,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1402184963226318, Predicted Probability: 0.2423, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6005008220672607, Predicted Probability: 0.9734, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3160/4000 [30:12<07:56,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2506608963012695, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.917309284210205, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3161/4000 [30:13<08:55,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7373902797698975, Predicted Probability: 0.0233, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.2129011154174805, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3162/4000 [30:14<08:31,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.870997428894043, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.718754768371582, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3163/4000 [30:14<07:30,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.510067462921143, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.466104030609131, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3164/4000 [30:15<06:47,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.176222324371338, Predicted Probability: 0.9849, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.067441463470459, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3165/4000 [30:15<05:51,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.385274887084961, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.719491481781006, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3166/4000 [30:15<06:22,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2126200199127197, Predicted Probability: 0.9613, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.570465087890625, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3168/4000 [30:16<06:11,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.278559684753418, Predicted Probability: 0.0137, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.396505832672119, Predicted Probability: 0.9676, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 4.852520942687988, Predicted Probability: 0.9923, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.530157089233398, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3169/4000 [30:17<07:17,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3838016986846924, Predicted Probability: 0.9156, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.909882068634033, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3170/4000 [30:18<08:14,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.790116310119629, Predicted Probability: 0.0221, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.016664981842041, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3171/4000 [30:18<07:59,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.204390525817871, Predicted Probability: 0.9610, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.04149055480957, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3172/4000 [30:19<07:51,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4289443492889404, Predicted Probability: 0.9686, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.066899299621582, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3173/4000 [30:20<08:50,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.173760414123535, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3114943504333496, Predicted Probability: 0.0902, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3174/4000 [30:20<09:12,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.41505241394043, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.026906967163086, Predicted Probability: 0.9538, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3175/4000 [30:21<09:24,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.751825332641602, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0144665241241455, Predicted Probability: 0.7339, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3176/4000 [30:22<09:54,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.9841108322143555, Predicted Probability: 0.9932, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.429365634918213, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3177/4000 [30:22<08:47,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.040945053100586, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0644850730896, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  79%|███████▉  | 3178/4000 [30:23<09:12,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1724724769592285, Predicted Probability: 0.9598, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.854650497436523, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  79%|███████▉  | 3179/4000 [30:24<10:17,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8748114109039307, Predicted Probability: 0.1330, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.774034023284912, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  80%|███████▉  | 3180/4000 [30:24<08:44,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.236328125, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.123240947723389, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3181/4000 [30:25<07:34,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.561727523803711, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.855515003204346, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  80%|███████▉  | 3182/4000 [30:26<08:18,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.984982490539551, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.261385202407837, Predicted Probability: 0.9056, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3183/4000 [30:26<07:19,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.403449058532715, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3656091690063477, Predicted Probability: 0.9666, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3184/4000 [30:26<06:41,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3422393798828125, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.825608253479004, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3185/4000 [30:27<07:52,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.272087097167969, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.075542449951172, Predicted Probability: 0.8885, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3186/4000 [30:28<08:25,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.581300735473633, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7938243746757507, Predicted Probability: 0.3113, Prediction: 0.0

Epoch 1/3:  80%|███████▉  | 3187/4000 [30:29<08:55,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.541236877441406, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0350358486175537, Predicted Probability: 0.8844, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3189/4000 [30:29<05:44,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.612606525421143, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0204267501831055, Predicted Probability: 0.9535, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.6551194190979, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.515580654144287, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3190/4000 [30:30<06:51,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.591075897216797, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.56173038482666, Predicted Probability: 0.9284, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3192/4000 [30:30<05:12,  2.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.087167739868164, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.150021553039551, Predicted Probability: 0.9979, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.011899948120117, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.753869533538818, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3193/4000 [30:31<06:40,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.103732585906982, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.971648216247559, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  80%|███████▉  | 3194/4000 [30:32<07:51,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.246242523193359, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.723779678344727, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3195/4000 [30:32<06:57,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.409034729003906, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.304311275482178, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3196/4000 [30:33<06:22,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.424059867858887, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.977240562438965, Predicted Probability: 0.9515, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3197/4000 [30:33<05:32,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.532106876373291, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.119838237762451, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3198/4000 [30:33<06:40,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.870301365852356, Predicted Probability: 0.1335, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.633859634399414, Predicted Probability: 0.9330, Prediction: 1.0

Epoch 1/3:  80%|███████▉  | 3199/4000 [30:34<07:42,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2454075813293457, Predicted Probability: 0.9043, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.65257453918457, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3200/4000 [30:35<08:22,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.91375470161438, Predicted Probability: 0.0196, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3413772583007812, Predicted Probability: 0.0878, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3201/4000 [30:36<08:10,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.841303825378418, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.239827632904053, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3202/4000 [30:36<08:52,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.091752290725708, Predicted Probability: 0.9566, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.903097629547119, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3203/4000 [30:37<07:37,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.088115692138672, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.4852800369262695, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3204/4000 [30:37<08:16,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6829921007156372, Predicted Probability: 0.6644, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.135869979858398, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3205/4000 [30:38<08:41,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.615485191345215, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.33980655670166, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3206/4000 [30:39<08:14,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.603946685791016, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.565187931060791, Predicted Probability: 0.9725, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3207/4000 [30:40<08:53,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1254281997680664, Predicted Probability: 0.1066, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.493115425109863, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3208/4000 [30:40<09:24,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.952498197555542, Predicted Probability: 0.9812, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.212048053741455, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3209/4000 [30:41<08:47,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5028091669082642, Predicted Probability: 0.1820, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6364569664001465, Predicted Probability: 0.6540, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3210/4000 [30:41<08:16,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8939924240112305, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.4016499519348145, Predicted Probability: 0.0121, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3211/4000 [30:42<08:46,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.139895439147949, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.920650601387024, Predicted Probability: 0.8722, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3212/4000 [30:43<09:12,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.745353698730469, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.645981788635254, Predicted Probability: 0.9746, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3213/4000 [30:43<07:14,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.187642574310303, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.276329040527344, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3214/4000 [30:44<08:10,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.229600429534912, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.158007621765137, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3215/4000 [30:44<07:10,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.064436912536621, Predicted Probability: 0.9831, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.799526691436768, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3216/4000 [30:45<07:09,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.855885982513428, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5623321533203125, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 1/3:  80%|████████  | 3217/4000 [30:45<07:10,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.440732479095459, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.231504917144775, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3218/4000 [30:46<06:30,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5810179710388184, Predicted Probability: 0.0704, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.557882308959961, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3219/4000 [30:46<06:00,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.432978868484497, Predicted Probability: 0.0807, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.227616310119629, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  80%|████████  | 3220/4000 [30:47<05:59,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5789923667907715, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.064537525177002, Predicted Probability: 0.9937, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -4.691583156585693, Predicted Probability: 0.0091, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3221/4000 [30:47<04:58,  2.61it/s]

Data point 2: Actual Class: 1.0, Final Logit: -1.6814188957214355, Predicted Probability: 0.1569, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3222/4000 [30:48<06:19,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.829781532287598, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1424827575683594, Predicted Probability: 0.2419, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3223/4000 [30:48<06:32,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.600673198699951, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.942985534667969, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3224/4000 [30:49<06:23,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5004706382751465, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.56927490234375, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3225/4000 [30:49<07:26,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.57352352142334, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.098787546157837, Predicted Probability: 0.8908, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3226/4000 [30:50<07:31,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9902262687683105, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.273707151412964, Predicted Probability: 0.9067, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3227/4000 [30:50<06:41,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.504194736480713, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.746152400970459, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3228/4000 [30:51<07:37,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.496830940246582, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5097107887268066, Predicted Probability: 0.0752, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3229/4000 [30:52<08:08,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0518525838851929, Predicted Probability: 0.2589, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7995991706848145, Predicted Probability: 0.0573, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3230/4000 [30:52<07:50,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4817121028900146, Predicted Probability: 0.9702, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.89571475982666, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3231/4000 [30:53<06:16,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.175334930419922, Predicted Probability: 0.0401, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.044681549072266, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3232/4000 [30:53<07:24,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.038010120391846, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9144043922424316, Predicted Probability: 0.8715, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3233/4000 [30:54<07:55,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0155773162841797, Predicted Probability: 0.8824, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.655052185058594, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3234/4000 [30:55<07:15,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.086759567260742, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5797922611236572, Predicted Probability: 0.9729, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3235/4000 [30:55<07:09,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5294389724731445, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.550518751144409, Predicted Probability: 0.9276, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3236/4000 [30:56<07:04,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2803633213043213, Predicted Probability: 0.9637, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.340885162353516, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3238/4000 [30:56<05:12,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9903626441955566, Predicted Probability: 0.9818, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.159539699554443, Predicted Probability: 0.9979, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.713975429534912, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4814398288726807, Predicted Probability: 0.0298, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3239/4000 [30:57<05:09,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.856211185455322, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.647376537322998, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3240/4000 [30:57<06:22,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5737576484680176, Predicted Probability: 0.9292, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7332568168640137, Predicted Probability: 0.1502, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3241/4000 [30:58<07:09,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8781614303588867, Predicted Probability: 0.9797, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.10364817082881927, Predicted Probability: 0.4741, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3242/4000 [30:58<06:32,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.938124179840088, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.231632709503174, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3243/4000 [30:59<07:26,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.266021966934204, Predicted Probability: 0.9632, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.320734739303589, Predicted Probability: 0.0894, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3244/4000 [30:59<05:58,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.630585670471191, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.120538711547852, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3245/4000 [31:00<07:24,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.106081008911133, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.171281814575195, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3246/4000 [31:01<06:35,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.582715630531311, Predicted Probability: 0.1704, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5389909744262695, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3247/4000 [31:01<07:31,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.520939826965332, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.10993766784668, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  81%|████████  | 3248/4000 [31:02<08:13,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.50507652759552, Predicted Probability: 0.6237, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.141291856765747, Predicted Probability: 0.8949, Prediction: 1.0

Epoch 1/3:  81%|████████  | 3249/4000 [31:03<07:09,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0194878578186035, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7361979484558105, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  81%|████████▏ | 3250/4000 [31:03<07:53,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.893176794052124, Predicted Probability: 0.7095, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.408993244171143, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 1/3:  81%|████████▏ | 3251/4000 [31:04<07:10,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.391617774963379, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0119564533233643, Predicted Probability: 0.1180, Prediction: 0.0

Epoch 1/3:  81%|████████▏ | 3252/4000 [31:04<07:05,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7647109031677246, Predicted Probability: 0.0226, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.625794410705566, Predicted Probability: 0.9903, Prediction: 1.0

Epoch 1/3:  81%|████████▏ | 3253/4000 [31:05<06:36,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.737330436706543, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5732338428497314, Predicted Probability: 0.9727, Prediction: 1.0

Epoch 1/3:  81%|████████▏ | 3254/4000 [31:06<07:18,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.343468189239502, Predicted Probability: 0.0128, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1386029720306396, Predicted Probability: 0.8946, Prediction: 1.0

Epoch 1/3:  81%|████████▏ | 3255/4000 [31:06<07:45,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.029309272766113, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9876234531402588, Predicted Probability: 0.8795, Prediction: 1.0

Epoch 1/3:  81%|████████▏ | 3256/4000 [31:07<07:05,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.595608234405518, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9232606887817383, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 1/3:  81%|████████▏ | 3257/4000 [31:07<06:25,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.663525104522705, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.789858341217041, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 1/3:  81%|████████▏ | 3259/4000 [31:08<04:50,  2.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8686959147453308, Predicted Probability: 0.2955, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.859404563903809, Predicted Probability: 0.9990, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.669559001922607, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.627580642700195, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3260/4000 [31:08<06:14,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.932635307312012, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.102352142333984, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3261/4000 [31:09<07:07,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7054758071899414, Predicted Probability: 0.3306, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.563551902770996, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3262/4000 [31:10<07:01,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3531827926635742, Predicted Probability: 0.7946, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8796334266662598, Predicted Probability: 0.9468, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3263/4000 [31:10<05:41,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.127936363220215, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.713399410247803, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3264/4000 [31:11<06:48,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0737507343292236, Predicted Probability: 0.8883, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.945302486419678, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3265/4000 [31:12<07:56,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0466156005859375, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.629991054534912, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3266/4000 [31:12<08:13,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.089716911315918, Predicted Probability: 0.8899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.257620811462402, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3267/4000 [31:13<07:44,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2357773780822754, Predicted Probability: 0.0378, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.52023983001709, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3268/4000 [31:14<08:10,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.7703447341918945, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.916717767715454, Predicted Probability: 0.0513, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3269/4000 [31:14<08:21,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.165801525115967, Predicted Probability: 0.0153, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.027932643890381, Predicted Probability: 0.8837, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3270/4000 [31:15<08:35,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0734214782714844, Predicted Probability: 0.1117, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1781805157661438, Predicted Probability: 0.5444, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3271/4000 [31:16<08:48,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1581876277923584, Predicted Probability: 0.8964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.946372032165527, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3272/4000 [31:16<07:36,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1067891120910645, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.165046215057373, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3273/4000 [31:17<06:40,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.78228759765625, Predicted Probability: 0.9777, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.804413795471191, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3274/4000 [31:17<07:35,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.103816032409668, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.2852606773376465, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3275/4000 [31:18<06:58,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1407575607299805, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0228116512298584, Predicted Probability: 0.9536, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3276/4000 [31:18<06:53,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2641066312789917, Predicted Probability: 0.7797, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.40575647354126, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3277/4000 [31:19<07:33,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.949794769287109, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.19087028503418, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3278/4000 [31:20<08:02,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4776861667633057, Predicted Probability: 0.9700, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.797194004058838, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3279/4000 [31:20<06:23,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.563859462738037, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.000391960144043, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3280/4000 [31:21<06:03,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.026805400848389, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4461703300476074, Predicted Probability: 0.9691, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3281/4000 [31:21<05:34,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.682476282119751, Predicted Probability: 0.0640, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.165285110473633, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3282/4000 [31:21<04:38,  2.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6321649551391602, Predicted Probability: 0.1635, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.712057113647461, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3284/4000 [31:22<03:53,  3.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.136709213256836, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1137542724609375, Predicted Probability: 0.9839, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.801765441894531, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.442544460296631, Predicted Probability: 0.0310, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3285/4000 [31:22<04:01,  2.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.588317394256592, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7883858680725098, Predicted Probability: 0.0221, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3286/4000 [31:23<05:38,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.34939873218536377, Predicted Probability: 0.4135, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6254682540893555, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3287/4000 [31:23<05:32,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.548722505569458, Predicted Probability: 0.9720, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.51194953918457, Predicted Probability: 0.0109, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3288/4000 [31:24<05:45,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6170543432235718, Predicted Probability: 0.8344, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.002749443054199, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3289/4000 [31:24<05:23,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.156660556793213, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.212486267089844, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3290/4000 [31:25<06:19,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.069009780883789, Predicted Probability: 0.8879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.158510684967041, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3291/4000 [31:25<05:48,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0967533588409424, Predicted Probability: 0.9568, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.510222911834717, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3292/4000 [31:26<06:36,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2149964570999146, Predicted Probability: 0.2288, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.197990417480469, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3293/4000 [31:26<05:20,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.581604957580566, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.919699668884277, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3294/4000 [31:27<05:02,  2.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.945382118225098, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.009868621826172, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3295/4000 [31:27<04:51,  2.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.16678524017334, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.074347496032715, Predicted Probability: 0.9833, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3296/4000 [31:28<06:01,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.131772041320801, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2129898071289062, Predicted Probability: 0.9014, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3297/4000 [31:28<06:26,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3445773124694824, Predicted Probability: 0.9659, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.983745098114014, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  82%|████████▏ | 3298/4000 [31:29<05:48,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.2227681875228882, Predicted Probability: 0.2274, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.259521961212158, Predicted Probability: 0.9861, Prediction: 1.0

Epoch 1/3:  82%|████████▏ | 3299/4000 [31:29<05:22,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.654339790344238, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.291216850280762, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 1/3:  82%|████████▎ | 3300/4000 [31:30<06:17,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.164173603057861, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0848605632781982, Predicted Probability: 0.8894, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3301/4000 [31:30<05:43,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.032902717590332, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9311935901641846, Predicted Probability: 0.9808, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3302/4000 [31:31<06:52,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6256561279296875, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.910106897354126, Predicted Probability: 0.9483, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3303/4000 [31:31<06:08,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.022383213043213, Predicted Probability: 0.9824, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9918198585510254, Predicted Probability: 0.1201, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3304/4000 [31:32<06:48,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.568643569946289, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0563193559646606, Predicted Probability: 0.7420, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3305/4000 [31:33<07:16,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5999844074249268, Predicted Probability: 0.3543, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.746335029602051, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3306/4000 [31:33<06:59,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.193484783172607, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.126049518585205, Predicted Probability: 0.9580, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3307/4000 [31:34<06:46,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.605937957763672, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2987585067749023, Predicted Probability: 0.0356, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3308/4000 [31:35<07:24,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6444103717803955, Predicted Probability: 0.1619, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.395322799682617, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3309/4000 [31:35<07:08,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.810393810272217, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.713732898235321, Predicted Probability: 0.3288, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3310/4000 [31:36<07:55,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.662740707397461, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.418540954589844, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3311/4000 [31:37<08:05,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2957968711853027, Predicted Probability: 0.9085, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.321122169494629, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3312/4000 [31:38<08:22,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.406353950500488, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.912256956100464, Predicted Probability: 0.9484, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3313/4000 [31:39<08:32,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.129194736480713, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9077526330947876, Predicted Probability: 0.8708, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3314/4000 [31:39<07:34,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.098715782165527, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.7189860343933105, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3315/4000 [31:40<07:48,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1606369018554688, Predicted Probability: 0.7614, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.664966583251953, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3316/4000 [31:41<08:07,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.5659356117248535, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4167747497558594, Predicted Probability: 0.9181, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3317/4000 [31:41<08:07,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2123167514801025, Predicted Probability: 0.9014, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.261768341064453, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3318/4000 [31:41<06:24,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: 6.652481555938721, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.753077507019043, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3319/4000 [31:42<07:11,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.108007431030273, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.889430522918701, Predicted Probability: 0.9925, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3320/4000 [31:43<07:32,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.271651268005371, Predicted Probability: 0.9065, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.923027038574219, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3321/4000 [31:44<07:09,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.299952983856201, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.37585899233818054, Predicted Probability: 0.4071, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3322/4000 [31:44<07:46,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.178943634033203, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.261852741241455, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3323/4000 [31:45<06:20,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.679683208465576, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.688319206237793, Predicted Probability: 0.8440, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3324/4000 [31:45<07:06,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6487915515899658, Predicted Probability: 0.6567, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.674890995025635, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3325/4000 [31:46<06:16,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.685671806335449, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.690924644470215, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3326/4000 [31:46<05:40,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.380552291870117, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.417113780975342, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3327/4000 [31:47<06:22,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.160741806030273, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9507948756217957, Predicted Probability: 0.7213, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3328/4000 [31:48<06:55,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.178034782409668, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7760159969329834, Predicted Probability: 0.3152, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3329/4000 [31:48<07:16,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.907605171203613, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.211658000946045, Predicted Probability: 0.9013, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3330/4000 [31:49<07:36,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.15376615524292, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.053367853164673, Predicted Probability: 0.8863, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3331/4000 [31:50<07:51,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2640817165374756, Predicted Probability: 0.9632, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.295663356781006, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3332/4000 [31:51<08:18,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.378190040588379, Predicted Probability: 0.9876, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.527857780456543, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3333/4000 [31:51<08:16,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.574292182922363, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.270937442779541, Predicted Probability: 0.9064, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3334/4000 [31:52<07:45,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.863056182861328, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.8341426849365234, Predicted Probability: 0.1377, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3335/4000 [31:53<07:16,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.662649154663086, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.889364242553711, Predicted Probability: 0.9800, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3336/4000 [31:53<07:31,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.1639862060546875, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2898287773132324, Predicted Probability: 0.9080, Prediction: 1.0

Epoch 1/3:  83%|████████▎ | 3337/4000 [31:54<07:40,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.564300775527954, Predicted Probability: 0.8270, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.364416122436523, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3338/4000 [31:55<07:57,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6992483139038086, Predicted Probability: 0.0630, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.482454299926758, Predicted Probability: 0.0298, Prediction: 0.0

Epoch 1/3:  83%|████████▎ | 3339/4000 [31:55<06:16,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.784646511077881, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.346846103668213, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  84%|████████▎ | 3340/4000 [31:56<06:59,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6997780799865723, Predicted Probability: 0.9759, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.099252700805664, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 1/3:  84%|████████▎ | 3341/4000 [31:57<07:26,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.13018274307251, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.684732437133789, Predicted Probability: 0.0639, Prediction: 0.0

Epoch 1/3:  84%|████████▎ | 3342/4000 [31:57<07:39,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.505950927734375, Predicted Probability: 0.9709, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.69827938079834, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  84%|████████▎ | 3343/4000 [31:58<06:36,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.766410827636719, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3309972286224365, Predicted Probability: 0.9114, Prediction: 1.0

Epoch 1/3:  84%|████████▎ | 3344/4000 [31:59<07:04,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.26565408706665, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.617443084716797, Predicted Probability: 0.9739, Prediction: 1.0

Epoch 1/3:  84%|████████▎ | 3345/4000 [31:59<06:08,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.147564888000488, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.448634624481201, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  84%|████████▎ | 3346/4000 [32:00<06:53,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5982513427734375, Predicted Probability: 0.0693, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.166830062866211, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  84%|████████▎ | 3347/4000 [32:00<07:24,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3347227573394775, Predicted Probability: 0.0344, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.847830295562744, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  84%|████████▎ | 3348/4000 [32:01<07:34,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.042417526245117, Predicted Probability: 0.1148, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.596559524536133, Predicted Probability: 0.9733, Prediction: 1.0

Epoch 1/3:  84%|████████▎ | 3349/4000 [32:01<05:58,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.183212757110596, Predicted Probability: 0.0150, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7007105350494385, Predicted Probability: 0.1544, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3350/4000 [32:02<06:46,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.345770359039307, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.891756534576416, Predicted Probability: 0.0526, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3351/4000 [32:03<07:05,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.026384353637695, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.046663999557495, Predicted Probability: 0.8856, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3352/4000 [32:04<06:55,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4488985538482666, Predicted Probability: 0.9205, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.581917762756348, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3353/4000 [32:04<07:20,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.131778240203857, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.428744316101074, Predicted Probability: 0.9686, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3354/4000 [32:05<06:38,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.070339202880859, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3614132404327393, Predicted Probability: 0.9665, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3355/4000 [32:05<05:49,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.876877307891846, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.978074789047241, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3356/4000 [32:06<05:34,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.805437088012695, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.622418403625488, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3357/4000 [32:06<04:33,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.517341375350952, Predicted Probability: 0.9253, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.961734771728516, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3358/4000 [32:07<05:35,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5962085723876953, Predicted Probability: 0.9306, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.697585582733154, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3359/4000 [32:07<06:27,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2319610118865967, Predicted Probability: 0.9031, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.105996131896973, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3360/4000 [32:08<06:17,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.534247875213623, Predicted Probability: 0.0284, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.205214500427246, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3361/4000 [32:08<05:34,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.340031862258911, Predicted Probability: 0.9121, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.179935932159424, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3362/4000 [32:09<06:21,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.761030435562134, Predicted Probability: 0.0595, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.8188276290893555, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3363/4000 [32:10<06:53,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6887664794921875, Predicted Probability: 0.0244, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.812122344970703, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3364/4000 [32:11<07:18,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.542169094085693, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2400057315826416, Predicted Probability: 0.9038, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3365/4000 [32:11<07:26,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.215827941894531, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2757720947265625, Predicted Probability: 0.9069, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3366/4000 [32:12<07:38,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.621883392333984, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.750589609146118, Predicted Probability: 0.0601, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3367/4000 [32:13<07:07,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4875118732452393, Predicted Probability: 0.9703, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.72132682800293, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3368/4000 [32:14<07:39,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.073949813842773, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.438910484313965, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3369/4000 [32:14<07:37,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.110518455505371, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.472445487976074, Predicted Probability: 0.9222, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3370/4000 [32:15<07:35,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.016726374626159668, Predicted Probability: 0.5042, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.025239944458008, Predicted Probability: 0.8834, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3371/4000 [32:16<07:42,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.25739860534668, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.06695270538330078, Predicted Probability: 0.4833, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3372/4000 [32:16<07:44,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.615715980529785, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.370267868041992, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3373/4000 [32:17<07:41,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.404738664627075, Predicted Probability: 0.0828, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7918984889984131, Predicted Probability: 0.3118, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3374/4000 [32:18<07:39,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.571371078491211, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5108602046966553, Predicted Probability: 0.9249, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3375/4000 [32:19<07:37,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4696297645568848, Predicted Probability: 0.9220, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.402890205383301, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3376/4000 [32:19<06:43,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.148740291595459, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.317312240600586, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3377/4000 [32:20<05:57,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7367897033691406, Predicted Probability: 0.0233, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.866666316986084, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3378/4000 [32:20<06:35,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.776345729827881, Predicted Probability: 0.0224, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.179105758666992, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  84%|████████▍ | 3379/4000 [32:21<05:46,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.1508378982543945, Predicted Probability: 0.9845, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.327692031860352, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  84%|████████▍ | 3380/4000 [32:21<06:24,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.558321952819824, Predicted Probability: 0.0719, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.876969337463379, Predicted Probability: 0.9924, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3381/4000 [32:22<06:08,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.319160223007202, Predicted Probability: 0.9105, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.2897731065750122, Predicted Probability: 0.2159, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3382/4000 [32:23<06:43,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.7692975997924805, Predicted Probability: 0.0084, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1566569209098816, Predicted Probability: 0.4609, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3383/4000 [32:24<07:34,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.145774841308594, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.569799423217773, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3384/4000 [32:24<06:28,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.56223201751709, Predicted Probability: 0.9724, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.226918697357178, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3385/4000 [32:25<05:54,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.301039695739746, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.910339832305908, Predicted Probability: 0.9804, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3386/4000 [32:25<06:22,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5878689289093018, Predicted Probability: 0.9301, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.275953769683838, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3387/4000 [32:26<06:53,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.4958672523498535, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.3567094802856445, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3388/4000 [32:26<05:59,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4152116775512695, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.863002300262451, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3389/4000 [32:27<06:28,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.026581764221191, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5900859832763672, Predicted Probability: 0.8306, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3390/4000 [32:28<06:50,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9911394119262695, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5130081176757812, Predicted Probability: 0.9250, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3391/4000 [32:28<05:55,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.895657539367676, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.200658082962036, Predicted Probability: 0.0997, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3392/4000 [32:29<06:48,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.634310722351074, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9251456260681152, Predicted Probability: 0.0509, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3393/4000 [32:30<07:09,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9071741104125977, Predicted Probability: 0.1293, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.20941162109375, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  85%|████████▍ | 3394/4000 [32:30<05:38,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.960229873657227, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5541709661483765, Predicted Probability: 0.8255, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3396/4000 [32:31<04:07,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.002965211868286, Predicted Probability: 0.8811, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.087165355682373, Predicted Probability: 0.0061, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -5.105056285858154, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5161824226379395, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3397/4000 [32:31<03:41,  2.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.383642673492432, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.96152925491333, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3398/4000 [32:31<03:41,  2.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.32476282119751, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.572172164916992, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  85%|████████▍ | 3399/4000 [32:32<03:11,  3.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.924598217010498, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.848308086395264, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3400/4000 [32:32<04:32,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.102501392364502, Predicted Probability: 0.8911, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.964297294616699, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3401/4000 [32:33<05:28,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.63435173034668, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.54508113861084, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3402/4000 [32:34<06:02,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6745972633361816, Predicted Probability: 0.9355, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.918360233306885, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3403/4000 [32:35<06:23,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7386717796325684, Predicted Probability: 0.9393, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.615065097808838, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3404/4000 [32:35<06:17,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.786188125610352, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9226023554801941, Predicted Probability: 0.2844, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3405/4000 [32:36<06:36,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.017352104187012, Predicted Probability: 0.9823, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.118524074554443, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3406/4000 [32:37<06:51,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.538344621658325, Predicted Probability: 0.9718, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.516286849975586, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3407/4000 [32:37<06:53,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8299988508224487, Predicted Probability: 0.1382, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.694439649581909, Predicted Probability: 0.9367, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3408/4000 [32:38<05:55,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.332509756088257, Predicted Probability: 0.0885, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.900081157684326, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3409/4000 [32:38<04:46,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.821168899536133, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.146225929260254, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3410/4000 [32:39<05:31,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9417171478271484, Predicted Probability: 0.9810, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.506900787353516, Predicted Probability: 0.0109, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3411/4000 [32:39<04:58,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6808059215545654, Predicted Probability: 0.0641, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.9865522384643555, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3412/4000 [32:40<04:32,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.371848106384277, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.746192932128906, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3413/4000 [32:40<04:15,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.904980182647705, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.561279535293579, Predicted Probability: 0.9283, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3414/4000 [32:41<05:13,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.677050828933716, Predicted Probability: 0.9357, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.882670879364014, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3415/4000 [32:41<05:50,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.886003017425537, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.554877281188965, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3416/4000 [32:42<06:33,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2607884407043457, Predicted Probability: 0.9056, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.139111042022705, Predicted Probability: 0.0157, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3417/4000 [32:42<05:10,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.67692756652832, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.242279529571533, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  85%|████████▌ | 3418/4000 [32:43<05:12,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.658172130584717, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.595712184906006, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 1/3:  85%|████████▌ | 3419/4000 [32:43<04:13,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.716997146606445, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7968244552612305, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3420/4000 [32:44<05:03,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.788689613342285, Predicted Probability: 0.9779, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.55711555480957, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3421/4000 [32:45<05:52,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.332341194152832, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0476322174072266, Predicted Probability: 0.1143, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3422/4000 [32:46<06:25,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.099205493927002, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.521468639373779, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3423/4000 [32:46<06:36,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5306997299194336, Predicted Probability: 0.0737, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.205105304718018, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3424/4000 [32:47<06:42,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.974360466003418, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7181591987609863, Predicted Probability: 0.9381, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3425/4000 [32:48<06:50,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.208530426025391, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3327736854553223, Predicted Probability: 0.9116, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3426/4000 [32:48<05:51,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.233731746673584, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.756824493408203, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3427/4000 [32:49<05:14,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.596212387084961, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.6005988121032715, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3429/4000 [32:49<04:13,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.036062479019165, Predicted Probability: 0.8845, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7413787841796875, Predicted Probability: 0.9768, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.328652381896973, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4598143100738525, Predicted Probability: 0.0305, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3430/4000 [32:50<05:28,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.140277862548828, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.093709468841553, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3431/4000 [32:51<06:07,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5662262439727783, Predicted Probability: 0.9725, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.994295597076416, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3432/4000 [32:52<06:16,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.958157539367676, Predicted Probability: 0.9506, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.141920566558838, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3433/4000 [32:52<05:57,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.879095554351807, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.557737350463867, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3434/4000 [32:53<05:14,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5821340084075928, Predicted Probability: 0.0703, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0670976638793945, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3435/4000 [32:53<05:41,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.124670028686523, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5431542992591858, Predicted Probability: 0.3675, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3436/4000 [32:54<05:01,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.261961936950684, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.567385673522949, Predicted Probability: 0.9897, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3437/4000 [32:54<04:34,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0592548847198486, Predicted Probability: 0.9552, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7992610335350037, Predicted Probability: 0.3102, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3438/4000 [32:55<05:22,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.874650239944458, Predicted Probability: 0.1330, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.262053966522217, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3439/4000 [32:56<05:51,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.675205230712891, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5293828248977661, Predicted Probability: 0.3707, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3440/4000 [32:56<05:08,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.427743434906006, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.844570636749268, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3441/4000 [32:57<05:40,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.445422410964966, Predicted Probability: 0.9202, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.565959930419922, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3442/4000 [32:57<05:00,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6731743812561035, Predicted Probability: 0.0248, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.036815643310547, Predicted Probability: 0.0458, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3443/4000 [32:58<05:36,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.556626319885254, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4725537300109863, Predicted Probability: 0.9222, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3444/4000 [32:59<06:21,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.869065284729004, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9272565841674805, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3445/4000 [32:59<06:32,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.757414817810059, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.257439374923706, Predicted Probability: 0.9629, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3446/4000 [33:00<06:37,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5761985778808594, Predicted Probability: 0.0707, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.320401668548584, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3447/4000 [33:01<05:39,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.029189586639404, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.834007740020752, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  86%|████████▌ | 3448/4000 [33:01<06:06,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.688753128051758, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9648284912109375, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  86%|████████▌ | 3449/4000 [33:02<05:30,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.34232234954834, Predicted Probability: 0.9123, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.187687873840332, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 1/3:  86%|████████▋ | 3450/4000 [33:03<05:57,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6682925224304199, Predicted Probability: 0.3389, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.99556827545166, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  86%|████████▋ | 3451/4000 [33:03<06:15,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.582945823669434, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2729249000549316, Predicted Probability: 0.0934, Prediction: 0.0

Epoch 1/3:  86%|████████▋ | 3452/4000 [33:04<05:34,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.445580959320068, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.488760232925415, Predicted Probability: 0.1841, Prediction: 0.0

Epoch 1/3:  86%|████████▋ | 3453/4000 [33:04<04:28,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.36937141418457, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.016068935394287, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  86%|████████▋ | 3454/4000 [33:04<04:10,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.74752950668335, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.04777270555496216, Predicted Probability: 0.5119, Prediction: 1.0

Epoch 1/3:  86%|████████▋ | 3455/4000 [33:05<03:55,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.520052433013916, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2681219577789307, Predicted Probability: 0.9633, Prediction: 1.0

Epoch 1/3:  86%|████████▋ | 3457/4000 [33:05<02:50,  3.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.416811227798462, Predicted Probability: 0.0819, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.683994293212891, Predicted Probability: 0.9988, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -6.021815776824951, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.302089214324951, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 1/3:  86%|████████▋ | 3458/4000 [33:06<04:26,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3800835609436035, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.445439338684082, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 1/3:  86%|████████▋ | 3459/4000 [33:07<04:40,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.668657302856445, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.944737434387207, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 1/3:  86%|████████▋ | 3460/4000 [33:07<04:55,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1572186946868896, Predicted Probability: 0.7608, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8998297452926636, Predicted Probability: 0.8699, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3461/4000 [33:08<05:47,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.388017177581787, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.16065788269043, Predicted Probability: 0.0154, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3462/4000 [33:09<05:44,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.459487438201904, Predicted Probability: 0.0114, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.3348456621170044, Predicted Probability: 0.7916, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3463/4000 [33:09<05:00,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.755722999572754, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.019449710845947, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3464/4000 [33:10<04:31,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.45767879486084, Predicted Probability: 0.9885, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.631612300872803, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3465/4000 [33:10<04:12,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.298792362213135, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.51908540725708, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3466/4000 [33:11<04:54,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.426174163818359, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4572911262512207, Predicted Probability: 0.9211, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3467/4000 [33:11<05:23,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6970260739326477, Predicted Probability: 0.3325, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.424413681030273, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3468/4000 [33:12<05:55,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.107956886291504, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.03520393371582, Predicted Probability: 0.9826, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3469/4000 [33:13<05:08,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.483787536621094, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.106277942657471, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3470/4000 [33:13<05:04,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5303661823272705, Predicted Probability: 0.0738, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2248053550720215, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3471/4000 [33:14<05:26,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.250002145767212, Predicted Probability: 0.9047, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.965873718261719, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3472/4000 [33:15<05:51,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1788992881774902, Predicted Probability: 0.1017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0600078105926514, Predicted Probability: 0.0448, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3473/4000 [33:15<05:13,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6601264476776123, Predicted Probability: 0.9749, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.437632083892822, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3474/4000 [33:15<04:39,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.650829315185547, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.846733570098877, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3475/4000 [33:16<04:14,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.509287357330322, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.230554580688477, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3476/4000 [33:17<05:00,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.546835899353027, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.297614574432373, Predicted Probability: 0.9866, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3477/4000 [33:17<05:28,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.774651050567627, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.317202568054199, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3478/4000 [33:18<04:23,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.687299728393555, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3277668952941895, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3479/4000 [33:18<05:01,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.335190773010254, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.346630334854126, Predicted Probability: 0.9660, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3480/4000 [33:19<04:30,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2131187915802, Predicted Probability: 0.0986, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.154360771179199, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3481/4000 [33:19<04:06,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.745651721954346, Predicted Probability: 0.0086, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.711027145385742, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3482/4000 [33:19<03:48,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.681131362915039, Predicted Probability: 0.8431, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.173146724700928, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3483/4000 [33:20<04:38,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.218104600906372, Predicted Probability: 0.2283, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.419142723083496, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3484/4000 [33:20<03:47,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.300142288208008, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.660422325134277, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3485/4000 [33:21<04:32,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.130409240722656, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.091473579406738, Predicted Probability: 0.9836, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3486/4000 [33:22<05:04,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8871588706970215, Predicted Probability: 0.9799, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.130244731903076, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3487/4000 [33:23<05:29,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6132073402404785, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.205779552459717, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3488/4000 [33:23<05:54,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.67534065246582, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9009275436401367, Predicted Probability: 0.9802, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3489/4000 [33:24<05:55,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6196969747543335, Predicted Probability: 0.1652, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.808446407318115, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3490/4000 [33:25<05:45,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9108757972717285, Predicted Probability: 0.9804, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.66278076171875, Predicted Probability: 0.9750, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3491/4000 [33:25<04:59,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.740599632263184, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.433934211730957, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3492/4000 [33:26<04:55,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8042709827423096, Predicted Probability: 0.9429, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.594017505645752, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3493/4000 [33:27<05:25,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5404391288757324, Predicted Probability: 0.1765, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.400578498840332, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3494/4000 [33:27<04:19,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9191131591796875, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.461141109466553, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  87%|████████▋ | 3495/4000 [33:27<04:53,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.280747175216675, Predicted Probability: 0.9073, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.715571880340576, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3496/4000 [33:28<05:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.177738189697266, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.720408916473389, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3497/4000 [33:29<05:41,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9865561723709106, Predicted Probability: 0.7284, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.245009422302246, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3498/4000 [33:31<08:14,  1.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2602601051330566, Predicted Probability: 0.9055, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.600857257843018, Predicted Probability: 0.0099, Prediction: 0.0

Epoch 1/3:  87%|████████▋ | 3499/4000 [33:31<06:42,  1.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.704371452331543, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.297852993011475, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3500/4000 [33:32<06:30,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9035818576812744, Predicted Probability: 0.0520, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3557920455932617, Predicted Probability: 0.9134, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3501/4000 [33:32<05:02,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.422016143798828, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.1619038581848145, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3502/4000 [33:33<05:22,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3892717361450195, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8995299339294434, Predicted Probability: 0.2891, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3503/4000 [33:33<05:32,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.253916263580322, Predicted Probability: 0.9860, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.987820148468018, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3504/4000 [33:34<05:49,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5008658170700073, Predicted Probability: 0.1823, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.773988723754883, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3505/4000 [33:35<06:29,  1.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.364983320236206, Predicted Probability: 0.9141, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.885634899139404, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3506/4000 [33:36<05:30,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.685732841491699, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.576477527618408, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3507/4000 [33:36<05:10,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0579917430877686, Predicted Probability: 0.9551, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.444806098937988, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3508/4000 [33:37<05:25,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1969261169433594, Predicted Probability: 0.9000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.630952835083008, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3509/4000 [33:37<04:17,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.507943153381348, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3466296195983887, Predicted Probability: 0.9127, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3510/4000 [33:38<03:55,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.548091888427734, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.119686126708984, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3511/4000 [33:38<03:39,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.095363616943359, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.265232086181641, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3512/4000 [33:39<04:02,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9321984052658081, Predicted Probability: 0.7175, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.443741798400879, Predicted Probability: 0.0310, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3513/4000 [33:39<03:20,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.268474578857422, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.48795747756958, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3514/4000 [33:39<02:50,  2.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.801056385040283, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.31119441986084, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3515/4000 [33:40<03:45,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6116814613342285, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0379981994628906, Predicted Probability: 0.0457, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3516/4000 [33:40<04:25,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8531346321105957, Predicted Probability: 0.9792, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.218990802764893, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3517/4000 [33:41<04:59,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1938929557800293, Predicted Probability: 0.8997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.054973602294922, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3518/4000 [33:42<04:24,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.45372000336647034, Predicted Probability: 0.3885, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6181559562683105, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3519/4000 [33:42<04:53,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2813094854354858, Predicted Probability: 0.2173, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.776928901672363, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3520/4000 [33:43<05:17,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9117023944854736, Predicted Probability: 0.0516, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.789305686950684, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3521/4000 [33:44<05:36,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.997838973999023, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.686082363128662, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3522/4000 [33:44<04:49,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2376179695129395, Predicted Probability: 0.9858, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5324676632881165, Predicted Probability: 0.6301, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3523/4000 [33:45<04:40,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.125910997390747, Predicted Probability: 0.9579, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.776113986968994, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3524/4000 [33:45<04:09,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.495565414428711, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.36307954788208, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3525/4000 [33:46<04:42,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.285228252410889, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.436674118041992, Predicted Probability: 0.9688, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3526/4000 [33:46<03:46,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.554600238800049, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.6685357093811035, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3527/4000 [33:47<04:05,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.67718505859375, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6515121459960938, Predicted Probability: 0.1609, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3528/4000 [33:48<04:41,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.256959438323975, Predicted Probability: 0.0140, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4111223220825195, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3529/4000 [33:48<05:04,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.746394634246826, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.797732353210449, Predicted Probability: 0.9426, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3531/4000 [33:49<04:08,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.85960853099823, Predicted Probability: 0.8653, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.434543132781982, Predicted Probability: 0.0016, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -2.6789543628692627, Predicted Probability: 0.0642, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.053016185760498, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3532/4000 [33:50<03:45,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.065463542938232, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.302518844604492, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3533/4000 [33:50<03:30,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.21399180591106415, Predicted Probability: 0.4467, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.918683052062988, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3534/4000 [33:50<03:29,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.541965007781982, Predicted Probability: 0.0105, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.529273986816406, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3535/4000 [33:51<04:13,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.10371994972229, Predicted Probability: 0.1087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.156313896179199, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3536/4000 [33:52<04:12,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.1161317527294159, Predicted Probability: 0.5290, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.273440361022949, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3537/4000 [33:52<04:38,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9255895614624023, Predicted Probability: 0.0509, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.76859188079834, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3538/4000 [33:53<04:16,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.737735748291016, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.663957357406616, Predicted Probability: 0.0651, Prediction: 0.0

Epoch 1/3:  88%|████████▊ | 3539/4000 [33:53<04:13,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.744776964187622, Predicted Probability: 0.9769, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8079217672348022, Predicted Probability: 0.6917, Prediction: 1.0

Epoch 1/3:  88%|████████▊ | 3540/4000 [33:54<04:45,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.844776153564453, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.138512134552002, Predicted Probability: 0.0157, Prediction: 0.0

Epoch 1/3:  89%|████████▊ | 3541/4000 [33:55<05:02,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.609524965286255, Predicted Probability: 0.9736, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.695244312286377, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 1/3:  89%|████████▊ | 3542/4000 [33:56<05:26,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.298825263977051, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.639334678649902, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 1/3:  89%|████████▊ | 3543/4000 [33:57<05:32,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.153379440307617, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1930636167526245, Predicted Probability: 0.2327, Prediction: 0.0

Epoch 1/3:  89%|████████▊ | 3544/4000 [33:57<05:43,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.390580177307129, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.489063739776611, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  89%|████████▊ | 3545/4000 [33:58<05:40,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.61796760559082, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3206610679626465, Predicted Probability: 0.9106, Prediction: 1.0

Epoch 1/3:  89%|████████▊ | 3546/4000 [33:59<05:53,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.503711700439453, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.053067207336426, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 1/3:  89%|████████▊ | 3547/4000 [34:00<05:50,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.517327308654785, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -3.1781628131866455, Predicted Probability: 0.0400, Prediction: 0.0

Epoch 1/3:  89%|████████▊ | 3548/4000 [34:00<04:32,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.408238410949707, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.005763053894043, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  89%|████████▊ | 3549/4000 [34:01<05:00,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.763312339782715, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.007688522338867, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3550/4000 [34:01<04:52,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.804178714752197, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6120048761367798, Predicted Probability: 0.6484, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3551/4000 [34:02<03:52,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.122896194458008, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8021126985549927, Predicted Probability: 0.3096, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3552/4000 [34:02<03:09,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.128416061401367, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.474577903747559, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3553/4000 [34:03<03:56,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.402294874191284, Predicted Probability: 0.9170, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.110177993774414, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3554/4000 [34:03<04:28,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4781291484832764, Predicted Probability: 0.9226, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.909452438354492, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3555/4000 [34:04<03:57,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.31827974319458, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.730166912078857, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3556/4000 [34:04<03:34,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.939455986022949, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4742279052734375, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3557/4000 [34:05<04:18,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.932169437408447, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6550180912017822, Predicted Probability: 0.9748, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3558/4000 [34:06<04:35,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3706603050231934, Predicted Probability: 0.9146, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.928521633148193, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3559/4000 [34:06<03:41,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.375629425048828, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.519962310791016, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3560/4000 [34:06<03:25,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.12373685836792, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.655712127685547, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3561/4000 [34:07<03:33,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4532134532928467, Predicted Probability: 0.9693, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.650712966918945, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3562/4000 [34:08<04:11,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.806020736694336, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9741058349609375, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3563/4000 [34:08<03:44,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.4328775703907013, Predicted Probability: 0.6066, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2039008140563965, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3564/4000 [34:08<03:49,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.712005615234375, Predicted Probability: 0.9377, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.125912666320801, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3565/4000 [34:09<04:15,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.824342250823975, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8191787004470825, Predicted Probability: 0.3059, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3566/4000 [34:10<03:48,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9745877981185913, Predicted Probability: 0.2740, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.972851276397705, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3567/4000 [34:10<04:14,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.541931629180908, Predicted Probability: 0.9270, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.844815254211426, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3568/4000 [34:11<04:37,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.499874114990234, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6578385829925537, Predicted Probability: 0.9749, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3569/4000 [34:12<04:57,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.756602764129639, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.938357353210449, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3570/4000 [34:13<05:12,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.097823143005371, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.255563735961914, Predicted Probability: 0.0140, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3571/4000 [34:13<04:13,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.487441539764404, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.7820658683776855, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3572/4000 [34:14<04:34,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.538973093032837, Predicted Probability: 0.9268, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.62698221206665, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3573/4000 [34:14<04:44,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6875767707824707, Predicted Probability: 0.9363, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.553223609924316, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3574/4000 [34:15<04:52,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5987932682037354, Predicted Probability: 0.9734, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.895301818847656, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3575/4000 [34:16<05:02,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9012293815612793, Predicted Probability: 0.2888, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6567912101745605, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3576/4000 [34:16<03:56,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.247843861579895, Predicted Probability: 0.7769, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.173945903778076, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3577/4000 [34:17<04:34,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.574359893798828, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.877717971801758, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 1/3:  89%|████████▉ | 3578/4000 [34:18<04:28,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1046066284179688, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.444321155548096, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  89%|████████▉ | 3579/4000 [34:18<04:41,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2595319747924805, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.395122766494751, Predicted Probability: 0.4025, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3580/4000 [34:19<04:04,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.028932571411133, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.709414482116699, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3581/4000 [34:20<04:24,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.77305269241333, Predicted Probability: 0.0588, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.508759498596191, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3582/4000 [34:20<04:14,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.823843002319336, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.246456623077393, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3583/4000 [34:21<04:31,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.599217414855957, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8781014680862427, Predicted Probability: 0.8674, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3584/4000 [34:21<04:04,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7550251483917236, Predicted Probability: 0.9771, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.531949043273926, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3585/4000 [34:22<03:37,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.572672367095947, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.636032581329346, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3586/4000 [34:22<04:15,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3866822719573975, Predicted Probability: 0.9158, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.666652679443359, Predicted Probability: 0.0093, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3587/4000 [34:23<04:33,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.261694431304932, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8774442672729492, Predicted Probability: 0.8673, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3588/4000 [34:24<03:57,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.535633087158203, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7940473556518555, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3589/4000 [34:24<04:13,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.95942497253418, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.546755790710449, Predicted Probability: 0.9274, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3590/4000 [34:25<04:06,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.545678615570068, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8491833209991455, Predicted Probability: 0.8640, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3591/4000 [34:26<04:28,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.805558681488037, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2474720478057861, Predicted Probability: 0.7769, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3592/4000 [34:26<03:53,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.241156578063965, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.689113616943359, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3593/4000 [34:27<03:48,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.387240886688232, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2234468460083008, Predicted Probability: 0.7727, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3594/4000 [34:27<04:09,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.02750301361084, Predicted Probability: 0.8837, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.939263820648193, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3595/4000 [34:28<03:19,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.791165828704834, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.802474021911621, Predicted Probability: 0.9919, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3596/4000 [34:28<03:27,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.45742547512054443, Predicted Probability: 0.3876, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.066464900970459, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3597/4000 [34:28<03:10,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4148430824279785, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4427971839904785, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  90%|████████▉ | 3598/4000 [34:29<02:59,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.154256343841553, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9160702228546143, Predicted Probability: 0.9805, Prediction: 1.0

Epoch 1/3:  90%|████████▉ | 3599/4000 [34:30<03:31,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.274761915206909, Predicted Probability: 0.9068, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7425432205200195, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3600/4000 [34:30<03:57,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.0571088790893555, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2339155673980713, Predicted Probability: 0.9033, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3601/4000 [34:31<04:22,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.17438268661499, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.663724422454834, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3602/4000 [34:32<04:36,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7047079801559448, Predicted Probability: 0.6692, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.247794151306152, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3603/4000 [34:33<04:42,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.95712947845459, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.340031147003174, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3604/4000 [34:33<04:01,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.001986026763916, Predicted Probability: 0.9820, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.54463005065918, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3605/4000 [34:34<04:25,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.284336090087891, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.497740268707275, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3606/4000 [34:34<03:49,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.201969623565674, Predicted Probability: 0.9609, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.062192916870117, Predicted Probability: 0.1128, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3607/4000 [34:35<04:08,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.696649551391602, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.11715030670166, Predicted Probability: 0.9576, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3608/4000 [34:36<04:20,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.175612926483154, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5080034732818604, Predicted Probability: 0.0753, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3609/4000 [34:36<03:45,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.959372043609619, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.584886074066162, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3610/4000 [34:37<04:05,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.502817153930664, Predicted Probability: 0.9243, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.741929054260254, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3611/4000 [34:37<03:16,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.466328144073486, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.121716260910034, Predicted Probability: 0.0422, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3612/4000 [34:37<03:00,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0708043575286865, Predicted Probability: 0.7447, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.841846466064453, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3613/4000 [34:38<03:31,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.901813507080078, Predicted Probability: 0.9802, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.301097869873047, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3614/4000 [34:39<03:56,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.2381062507629395, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4273338317871094, Predicted Probability: 0.9189, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3615/4000 [34:40<04:20,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.397611618041992, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.821826934814453, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3616/4000 [34:41<04:51,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6441053152084351, Predicted Probability: 0.3443, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.902825355529785, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  90%|█████████ | 3617/4000 [34:41<04:07,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7622504234313965, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.657909393310547, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3618/4000 [34:41<03:34,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.767085075378418, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.14010763168335, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3619/4000 [34:42<03:11,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.267019748687744, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.083270072937012, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  90%|█████████ | 3620/4000 [34:43<03:49,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.276670455932617, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5288567543029785, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3621/4000 [34:43<03:26,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.535177707672119, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.134562015533447, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3622/4000 [34:43<03:06,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7301554679870605, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.26780882477760315, Predicted Probability: 0.4334, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3623/4000 [34:44<03:32,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.694928169250488, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.154442310333252, Predicted Probability: 0.8961, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3624/4000 [34:45<03:13,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.891200065612793, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.800375461578369, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3625/4000 [34:45<02:57,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.320180416107178, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.394532203674316, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3626/4000 [34:45<02:48,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.96141242980957, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.133140563964844, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3627/4000 [34:46<02:40,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.903470993041992, Predicted Probability: 0.0198, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3818912506103516, Predicted Probability: 0.0846, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3628/4000 [34:46<02:22,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.239668846130371, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.807358741760254, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3629/4000 [34:47<03:05,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.769723415374756, Predicted Probability: 0.9410, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.686593055725098, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3630/4000 [34:47<02:50,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.230170249938965, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7178423404693604, Predicted Probability: 0.0619, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3631/4000 [34:48<02:40,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1308746337890625, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.971494674682617, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3632/4000 [34:48<03:18,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.480277061462402, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6443500518798828, Predicted Probability: 0.3443, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3633/4000 [34:49<03:21,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.0798420906066895, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1310272216796875, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3634/4000 [34:50<03:42,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.245481491088867, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.667485237121582, Predicted Probability: 0.9751, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3635/4000 [34:50<03:16,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6967897415161133, Predicted Probability: 0.0242, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.097836017608643, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3636/4000 [34:50<02:58,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.084408760070801, Predicted Probability: 0.0438, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.064305305480957, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3637/4000 [34:51<02:27,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.403888702392578, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.341675281524658, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3638/4000 [34:51<03:00,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.878296136856079, Predicted Probability: 0.9797, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3067784309387207, Predicted Probability: 0.0353, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3639/4000 [34:52<03:03,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.768993854522705, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6950347423553467, Predicted Probability: 0.9758, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3640/4000 [34:53<03:30,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.76949405670166, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6795544624328613, Predicted Probability: 0.9358, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3641/4000 [34:53<02:49,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.1765997409820557, Predicted Probability: 0.0401, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.971465587615967, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3642/4000 [34:54<03:20,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.767989158630371, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.673348903656006, Predicted Probability: 0.0093, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3643/4000 [34:54<02:48,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.967365264892578, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.8610615730285645, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3644/4000 [34:55<03:16,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.690670967102051, Predicted Probability: 0.9365, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.503829002380371, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3645/4000 [34:55<03:40,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.534974098205566, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6200928688049316, Predicted Probability: 0.0679, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3646/4000 [34:56<03:14,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.362377166748047, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.82014274597168, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3647/4000 [34:56<03:19,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7367641925811768, Predicted Probability: 0.9392, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.726091384887695, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 1/3:  91%|█████████ | 3648/4000 [34:57<02:40,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.672966957092285, Predicted Probability: 0.0646, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3424482345581055, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  91%|█████████ | 3649/4000 [34:57<02:13,  2.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.126640796661377, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.213913440704346, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  91%|█████████▏| 3650/4000 [34:57<02:13,  2.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.83066987991333, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5332980751991272, Predicted Probability: 0.6303, Prediction: 1.0

Epoch 1/3:  91%|█████████▏| 3651/4000 [34:58<02:52,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2620978355407715, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.475520610809326, Predicted Probability: 0.9700, Prediction: 1.0

Epoch 1/3:  91%|█████████▏| 3652/4000 [34:59<03:17,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3228673934936523, Predicted Probability: 0.9652, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3507814407348633, Predicted Probability: 0.0339, Prediction: 0.0

Epoch 1/3:  91%|█████████▏| 3653/4000 [34:59<03:06,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.222039699554443, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.402725696563721, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  91%|█████████▏| 3654/4000 [35:00<03:27,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2931857109069824, Predicted Probability: 0.9642, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.583369255065918, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 1/3:  91%|█████████▏| 3655/4000 [35:00<03:12,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.869606018066406, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.113065719604492, Predicted Probability: 0.1078, Prediction: 0.0

Epoch 1/3:  91%|█████████▏| 3656/4000 [35:01<03:31,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5268683433532715, Predicted Probability: 0.9260, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.734567642211914, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  91%|█████████▏| 3657/4000 [35:02<03:44,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.738104343414307, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.16615179181098938, Predicted Probability: 0.5414, Prediction: 1.0

Epoch 1/3:  91%|█████████▏| 3659/4000 [35:02<02:36,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9038591384887695, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.161258220672607, Predicted Probability: 0.9943, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.434340953826904, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.466233730316162, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3660/4000 [35:03<02:09,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.645665168762207, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.076131343841553, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3661/4000 [35:03<02:45,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5476784706115723, Predicted Probability: 0.9274, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.761336326599121, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3662/4000 [35:04<02:40,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.905436038970947, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.981410503387451, Predicted Probability: 0.9817, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3663/4000 [35:04<03:05,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.755839824676514, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.030062198638916, Predicted Probability: 0.9825, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3664/4000 [35:05<02:47,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.174318790435791, Predicted Probability: 0.9848, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2790340185165405, Predicted Probability: 0.4307, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3665/4000 [35:06<03:19,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.153985023498535, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.386256217956543, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3666/4000 [35:06<02:56,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.1756446361541748, Predicted Probability: 0.7642, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9272871017456055, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3667/4000 [35:07<03:16,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.931354522705078, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5835421085357666, Predicted Probability: 0.9298, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3668/4000 [35:08<03:32,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0659189224243164, Predicted Probability: 0.9555, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.388236999511719, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3669/4000 [35:08<03:12,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.257826089859009, Predicted Probability: 0.0947, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.995490074157715, Predicted Probability: 0.9819, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3670/4000 [35:09<03:39,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.867794990539551, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.526535511016846, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3671/4000 [35:10<03:45,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.237769603729248, Predicted Probability: 0.0964, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.906050682067871, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3672/4000 [35:10<03:54,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.621424674987793, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.650003433227539, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3673/4000 [35:12<04:50,  1.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.643759250640869, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.404448986053467, Predicted Probability: 0.0828, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3674/4000 [35:12<04:37,  1.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.851282119750977, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.901064395904541, Predicted Probability: 0.8700, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3675/4000 [35:13<04:27,  1.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9872636795043945, Predicted Probability: 0.0182, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.838960647583008, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3676/4000 [35:14<04:08,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2289552688598633, Predicted Probability: 0.9619, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3718866109848022, Predicted Probability: 0.7977, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3677/4000 [35:15<04:05,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.081324577331543, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6312682032585144, Predicted Probability: 0.3472, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3678/4000 [35:15<04:01,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.11430549621582, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3175368309020996, Predicted Probability: 0.9103, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3679/4000 [35:16<03:33,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.387449264526367, Predicted Probability: 0.9877, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.33560848236084, Predicted Probability: 0.9871, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3680/4000 [35:17<03:43,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7168128490448, Predicted Probability: 0.0620, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.470348834991455, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3681/4000 [35:17<03:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.676618576049805, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.961757183074951, Predicted Probability: 0.9508, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3682/4000 [35:18<03:17,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4187798500061035, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.998085021972656, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3683/4000 [35:18<02:53,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2017340660095215, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.497220993041992, Predicted Probability: 0.9890, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3684/4000 [35:18<02:20,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.962914943695068, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.017714977264404, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3685/4000 [35:19<02:53,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.641562461853027, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.082724094390869, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3686/4000 [35:20<03:09,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6549620628356934, Predicted Probability: 0.0657, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.954681396484375, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3687/4000 [35:20<03:20,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.393627166748047, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1790356636047363, Predicted Probability: 0.8984, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3688/4000 [35:21<03:30,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6112308502197266, Predicted Probability: 0.6482, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.84663200378418, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3689/4000 [35:22<03:34,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.695591926574707, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7852587699890137, Predicted Probability: 0.3132, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3690/4000 [35:22<03:03,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: -6.052060127258301, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.6920905113220215, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3691/4000 [35:23<02:42,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.492119789123535, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.257084369659424, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3692/4000 [35:23<03:01,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.909255027770996, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4037609100341797, Predicted Probability: 0.9171, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3693/4000 [35:24<02:48,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9885430335998535, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6543469429016113, Predicted Probability: 0.0657, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3694/4000 [35:24<02:31,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.651994228363037, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3190646171569824, Predicted Probability: 0.0349, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3695/4000 [35:25<02:19,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.103817462921143, Predicted Probability: 0.9838, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0194315910339355, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3696/4000 [35:25<02:11,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.229915618896484, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.206705093383789, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3697/4000 [35:25<02:20,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.848944664001465, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.310110330581665, Predicted Probability: 0.9648, Prediction: 1.0

Epoch 1/3:  92%|█████████▏| 3698/4000 [35:26<02:49,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.424102783203125, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.019287586212158, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  92%|█████████▏| 3699/4000 [35:27<03:04,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9094107151031494, Predicted Probability: 0.2871, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.747272491455078, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 1/3:  92%|█████████▎| 3700/4000 [35:28<03:16,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.42471981048584, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.307128429412842, Predicted Probability: 0.9095, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3701/4000 [35:28<02:56,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7483630180358887, Predicted Probability: 0.9770, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.814627647399902, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3702/4000 [35:29<03:18,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.576948165893555, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.501269817352295, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3703/4000 [35:29<02:51,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.461102485656738, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.988379001617432, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3704/4000 [35:30<02:40,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1992404460906982, Predicted Probability: 0.0998, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.981310844421387, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3705/4000 [35:30<02:24,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.460183620452881, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.505824565887451, Predicted Probability: 0.9891, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3706/4000 [35:31<02:55,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.468406677246094, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.910801887512207, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3707/4000 [35:31<02:20,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2512664794921875, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0510950088500977, Predicted Probability: 0.8861, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3708/4000 [35:32<02:40,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.374992370605469, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4744606614112854, Predicted Probability: 0.3836, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3709/4000 [35:32<02:10,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.5488176345825195, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.897475242614746, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3710/4000 [35:33<02:22,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.737182140350342, Predicted Probability: 0.9392, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1062092781066895, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3711/4000 [35:34<02:45,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.540329933166504, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.391998291015625, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3712/4000 [35:34<02:55,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.410020351409912, Predicted Probability: 0.9176, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8890694975852966, Predicted Probability: 0.2913, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3713/4000 [35:35<03:07,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.440112352371216, Predicted Probability: 0.0311, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.1169586181640625, Predicted Probability: 0.0160, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3714/4000 [35:35<02:42,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.059865951538086, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.240747451782227, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3715/4000 [35:36<02:56,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.35674524307251, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.213671922683716, Predicted Probability: 0.9015, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3716/4000 [35:37<02:37,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.212343692779541, Predicted Probability: 0.0146, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5300750732421875, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3717/4000 [35:37<02:36,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.482066631317139, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.445300102233887, Predicted Probability: 0.0116, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3718/4000 [35:38<02:52,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3144702911376953, Predicted Probability: 0.9101, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5266618728637695, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3719/4000 [35:38<02:17,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.126578330993652, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.27696418762207, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3720/4000 [35:38<02:07,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.068878173828125, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.788400173187256, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3721/4000 [35:39<02:01,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.348148822784424, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.081743240356445, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3722/4000 [35:40<02:25,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.054816722869873, Predicted Probability: 0.8864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.160769462585449, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3723/4000 [35:40<02:43,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9026472568511963, Predicted Probability: 0.0520, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.054131984710693, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3724/4000 [35:41<02:59,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.44171142578125, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.418388843536377, Predicted Probability: 0.9182, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3725/4000 [35:42<03:07,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.823694229125977, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3433520793914795, Predicted Probability: 0.9124, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3726/4000 [35:43<03:15,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.334527492523193, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.368513822555542, Predicted Probability: 0.9667, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3727/4000 [35:43<03:18,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.40120005607605, Predicted Probability: 0.9169, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.0803117752075195, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3728/4000 [35:44<03:09,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.001928806304932, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.731041431427002, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3729/4000 [35:44<02:29,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.319437026977539, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.03418493270874, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3730/4000 [35:45<02:29,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.595199108123779, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5260387659072876, Predicted Probability: 0.8214, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3731/4000 [35:45<02:21,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.241927146911621, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.563621520996094, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3732/4000 [35:46<02:43,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.086162567138672, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.896440505981445, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3733/4000 [35:47<02:54,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.28929328918457, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.82417106628418, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3734/4000 [35:47<02:33,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.6982245445251465, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.589419364929199, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 1/3:  93%|█████████▎| 3735/4000 [35:48<02:30,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.944395542144775, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.816659450531006, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3736/4000 [35:48<02:14,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.600636959075928, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.440800666809082, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3737/4000 [35:49<02:31,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.621997833251953, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4248456954956055, Predicted Probability: 0.9187, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3738/4000 [35:50<02:43,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.426234483718872, Predicted Probability: 0.0812, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.846035361289978, Predicted Probability: 0.8637, Prediction: 1.0

Epoch 1/3:  93%|█████████▎| 3739/4000 [35:50<02:22,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.8996901512146, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.893146991729736, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3740/4000 [35:51<02:37,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.418918132781982, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5834131240844727, Predicted Probability: 0.9298, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3741/4000 [35:51<02:18,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7014124393463135, Predicted Probability: 0.0629, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.088956356048584, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3742/4000 [35:52<02:39,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.471973419189453, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.128542900085449, Predicted Probability: 0.1064, Prediction: 0.0

Epoch 1/3:  94%|█████████▎| 3743/4000 [35:53<02:46,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7262330651283264, Predicted Probability: 0.3260, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6919755935668945, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  94%|█████████▎| 3744/4000 [35:53<02:57,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.047430038452148, Predicted Probability: 0.0172, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.050777912139893, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3745/4000 [35:54<03:01,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.518793106079102, Predicted Probability: 0.0108, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.1330167055130005, Predicted Probability: 0.7564, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3746/4000 [35:55<02:35,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: -5.194285869598389, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.559571266174316, Predicted Probability: 0.9896, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3747/4000 [35:55<02:18,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.871298789978027, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3674516677856445, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3748/4000 [35:55<02:04,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.420969486236572, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.439517498016357, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  94%|█████████▎| 3749/4000 [35:56<02:08,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9034250974655151, Predicted Probability: 0.1297, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0796825885772705, Predicted Probability: 0.9560, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3750/4000 [35:56<01:56,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.728089809417725, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.74498987197876, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3751/4000 [35:57<02:16,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6252264976501465, Predicted Probability: 0.0675, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.430724143981934, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3752/4000 [35:57<02:02,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.499063491821289, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.120669841766357, Predicted Probability: 0.0160, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3753/4000 [35:58<01:53,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.960896968841553, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.038715839385986, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3755/4000 [35:59<01:48,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8451411724090576, Predicted Probability: 0.9791, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.270326137542725, Predicted Probability: 0.0138, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.215049743652344, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.088190078735352, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3756/4000 [35:59<02:14,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.352287292480469, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.989745616912842, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3757/4000 [36:00<02:28,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6004728078842163, Predicted Probability: 0.6458, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.321464538574219, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3758/4000 [36:01<02:10,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.987274646759033, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.416578769683838, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3759/4000 [36:01<02:23,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.742128849029541, Predicted Probability: 0.0232, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4852590560913086, Predicted Probability: 0.9231, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3760/4000 [36:02<02:35,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5765130519866943, Predicted Probability: 0.0707, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.770880699157715, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3761/4000 [36:03<02:42,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.420499801635742, Predicted Probability: 0.9184, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.690617561340332, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3762/4000 [36:04<02:45,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.258454322814941, Predicted Probability: 0.0139, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1619873046875, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3763/4000 [36:04<02:27,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.204089641571045, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4583671987056732, Predicted Probability: 0.3874, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3764/4000 [36:05<02:34,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.882070541381836, Predicted Probability: 0.9470, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.240717887878418, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3765/4000 [36:05<02:30,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7829620838165283, Predicted Probability: 0.9417, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.164464473724365, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3766/4000 [36:06<02:34,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.570768356323242, Predicted Probability: 0.9290, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.658111572265625, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3767/4000 [36:07<02:26,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.898388862609863, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8360259532928467, Predicted Probability: 0.0554, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3768/4000 [36:07<02:08,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.529133319854736, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2897346019744873, Predicted Probability: 0.0920, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3769/4000 [36:08<02:26,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.651035308837891, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.263114929199219, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3770/4000 [36:08<02:08,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.590702533721924, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.395633697509766, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3771/4000 [36:09<02:26,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.816951751708984, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.9962661266326904, Predicted Probability: 0.8804, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3772/4000 [36:10<02:33,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.1613664627075195, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5066317319869995, Predicted Probability: 0.1814, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3773/4000 [36:11<02:40,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2110209465026855, Predicted Probability: 0.9012, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.699812412261963, Predicted Probability: 0.0241, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3774/4000 [36:11<02:42,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.23819899559021, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.153094291687012, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3775/4000 [36:12<02:18,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.14357852935791, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.291752338409424, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3776/4000 [36:12<02:02,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.714919090270996, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.756388187408447, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3777/4000 [36:12<01:44,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.895026206970215, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.2263729572296143, Predicted Probability: 0.0974, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3778/4000 [36:13<02:08,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.006159782409668, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.470869064331055, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  94%|█████████▍| 3779/4000 [36:13<01:43,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.691646575927734, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.964879035949707, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  94%|█████████▍| 3780/4000 [36:14<02:02,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4368371963500977, Predicted Probability: 0.9688, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.883171081542969, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3781/4000 [36:15<02:24,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.79038143157959, Predicted Probability: 0.9779, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.860140800476074, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3782/4000 [36:16<02:32,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.674150466918945, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.473822593688965, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3783/4000 [36:16<02:09,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.355956554412842, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.16478557884693146, Predicted Probability: 0.4589, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3784/4000 [36:16<01:43,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.039929389953613, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.273031711578369, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3785/4000 [36:17<01:35,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.613653659820557, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0018067359924316, Predicted Probability: 0.0473, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3786/4000 [36:17<01:30,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.483679294586182, Predicted Probability: 0.9888, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.891942977905273, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3787/4000 [36:18<01:56,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.43998908996582, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.803373336791992, Predicted Probability: 0.9429, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3788/4000 [36:19<02:09,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.822016716003418, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.329378843307495, Predicted Probability: 0.9113, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3789/4000 [36:19<01:54,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.69697904586792, Predicted Probability: 0.9910, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7963759899139404, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3790/4000 [36:20<02:06,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.574376106262207, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.370047092437744, Predicted Probability: 0.9145, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3791/4000 [36:20<01:52,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.891330718994141, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.155308723449707, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3792/4000 [36:21<02:09,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.802465915679932, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.851294994354248, Predicted Probability: 0.0546, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3793/4000 [36:22<02:17,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.212275505065918, Predicted Probability: 0.9854, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.532115936279297, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3794/4000 [36:23<02:20,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9215337634086609, Predicted Probability: 0.7154, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.079291820526123, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3795/4000 [36:23<02:06,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.949085712432861, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.616641998291016, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3796/4000 [36:24<02:11,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.039498805999756, Predicted Probability: 0.8849, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.474805235862732, Predicted Probability: 0.1862, Prediction: 0.0

Epoch 1/3:  95%|█████████▍| 3797/4000 [36:24<01:45,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2866106033325195, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.480302572250366, Predicted Probability: 0.9227, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3798/4000 [36:24<01:37,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.290162086486816, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.877241611480713, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  95%|█████████▍| 3799/4000 [36:25<01:30,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.228003978729248, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8657069206237793, Predicted Probability: 0.9461, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3800/4000 [36:26<01:56,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.11927604675293, Predicted Probability: 0.0160, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.072109699249268, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3801/4000 [36:26<01:43,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3007049560546875, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.584331214427948, Predicted Probability: 0.3579, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3802/4000 [36:27<01:43,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8417184352874756, Predicted Probability: 0.9790, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.463163375854492, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3803/4000 [36:27<01:59,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.482622146606445, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.649716377258301, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3804/4000 [36:28<01:54,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.418428421020508, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.794583797454834, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3805/4000 [36:28<01:42,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.25990629196167, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.168951511383057, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3806/4000 [36:29<01:54,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.314944744110107, Predicted Probability: 0.0132, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.252644062042236, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3807/4000 [36:30<01:50,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7666081190109253, Predicted Probability: 0.1460, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.004704475402832, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3808/4000 [36:30<01:52,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.503271579742432, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 4.051157474517822, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3809/4000 [36:31<02:00,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6657609939575195, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4245147705078125, Predicted Probability: 0.9187, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3810/4000 [36:32<02:04,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.929323196411133, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6038851737976074, Predicted Probability: 0.9735, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3811/4000 [36:32<01:48,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.092102527618408, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.576223850250244, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3812/4000 [36:33<01:46,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9066057205200195, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.343334197998047, Predicted Probability: 0.9659, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3813/4000 [36:33<01:55,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9965020418167114, Predicted Probability: 0.1196, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.336797714233398, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3814/4000 [36:34<01:59,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.553966999053955, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.78134822845459, Predicted Probability: 0.9417, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3815/4000 [36:35<02:05,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.355388879776001, Predicted Probability: 0.2050, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0431108474731445, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3816/4000 [36:35<02:08,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9845709800720215, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7901825904846191, Predicted Probability: 0.8569, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3817/4000 [36:36<02:11,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2143162488937378, Predicted Probability: 0.2289, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -4.015844345092773, Predicted Probability: 0.0177, Prediction: 0.0

Epoch 1/3:  95%|█████████▌| 3818/4000 [36:37<02:12,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.885540962219238, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5605602264404297, Predicted Probability: 0.9724, Prediction: 1.0

Epoch 1/3:  95%|█████████▌| 3819/4000 [36:38<02:12,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.891739845275879, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.777885913848877, Predicted Probability: 0.8554, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3820/4000 [36:38<02:13,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.69218111038208, Predicted Probability: 0.9366, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.197651386260986, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3821/4000 [36:39<01:53,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.016331195831299, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.793185234069824, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3822/4000 [36:40<01:57,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.1929420232772827, Predicted Probability: 0.2327, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.729347229003906, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3823/4000 [36:40<01:42,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6624603271484375, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.236898422241211, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3824/4000 [36:41<01:40,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.633519649505615, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.346493721008301, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3825/4000 [36:41<01:29,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.811119556427002, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.205159664154053, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3826/4000 [36:42<01:42,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.76467227935791, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2809581756591797, Predicted Probability: 0.9638, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3827/4000 [36:42<01:52,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.49080753326416, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -4.263779640197754, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3828/4000 [36:43<01:58,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0476229190826416, Predicted Probability: 0.1143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1440742015838623, Predicted Probability: 0.8951, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3829/4000 [36:44<02:03,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.794109344482422, Predicted Probability: 0.9780, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.672260284423828, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3830/4000 [36:44<01:36,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.784923553466797, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.955320835113525, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3831/4000 [36:45<01:44,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2403738498687744, Predicted Probability: 0.9038, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3849964141845703, Predicted Probability: 0.2002, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3832/4000 [36:46<01:51,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6563146114349365, Predicted Probability: 0.0656, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.106172561645508, Predicted Probability: 0.8915, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3833/4000 [36:46<01:45,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.437865972518921, Predicted Probability: 0.0803, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2270660400390625, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3834/4000 [36:47<01:53,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.126138687133789, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7993874549865723, Predicted Probability: 0.0574, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3835/4000 [36:48<01:56,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5690488815307617, Predicted Probability: 0.0274, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.681870222091675, Predicted Probability: 0.9754, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3836/4000 [36:48<01:39,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.311227321624756, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.51453161239624, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3837/4000 [36:49<01:26,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.665018558502197, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.680491924285889, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3838/4000 [36:49<01:19,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.241168022155762, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.074868202209473, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3839/4000 [36:50<01:33,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5594499111175537, Predicted Probability: 0.1737, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.873125076293945, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3841/4000 [36:51<01:21,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.54116678237915, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7325310707092285, Predicted Probability: 0.9766, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.7185959815979, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.005336284637451, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3842/4000 [36:51<01:22,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7933549880981445, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.550281047821045, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3843/4000 [36:52<01:32,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.334681272506714, Predicted Probability: 0.9117, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.224122047424316, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3844/4000 [36:52<01:21,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.788078784942627, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.795605659484863, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3845/4000 [36:53<01:32,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.98334002494812, Predicted Probability: 0.9518, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.416133880615234, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3846/4000 [36:54<01:21,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.352869987487793, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0417399406433105, Predicted Probability: 0.0456, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3847/4000 [36:54<01:31,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.305992126464844, Predicted Probability: 0.0133, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6515778303146362, Predicted Probability: 0.8391, Prediction: 1.0

Epoch 1/3:  96%|█████████▌| 3848/4000 [36:55<01:15,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9680769443511963, Predicted Probability: 0.0489, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.207719087600708, Predicted Probability: 0.0389, Prediction: 0.0

Epoch 1/3:  96%|█████████▌| 3849/4000 [36:55<01:28,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8899993896484375, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.33359694480896, Predicted Probability: 0.9656, Prediction: 1.0

Epoch 1/3:  96%|█████████▋| 3850/4000 [36:56<01:34,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.267880916595459, Predicted Probability: 0.9062, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.206543922424316, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  96%|█████████▋| 3851/4000 [36:57<01:29,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.083783149719238, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7210581302642822, Predicted Probability: 0.9383, Prediction: 1.0

Epoch 1/3:  96%|█████████▋| 3852/4000 [36:57<01:25,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.326845169067383, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1742565631866455, Predicted Probability: 0.9599, Prediction: 1.0

Epoch 1/3:  96%|█████████▋| 3853/4000 [36:58<01:36,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.304419994354248, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.534273147583008, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 1/3:  96%|█████████▋| 3854/4000 [36:58<01:23,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5047786831855774, Predicted Probability: 0.6236, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3513123989105225, Predicted Probability: 0.9130, Prediction: 1.0

Epoch 1/3:  96%|█████████▋| 3855/4000 [36:59<01:21,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.215396404266357, Predicted Probability: 0.0146, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5565910339355469, Predicted Probability: 0.3643, Prediction: 0.0

Epoch 1/3:  96%|█████████▋| 3856/4000 [37:00<01:30,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5604324340820312, Predicted Probability: 0.9283, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.416388034820557, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 1/3:  96%|█████████▋| 3857/4000 [37:00<01:33,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.0038299560546875, Predicted Probability: 0.0473, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9338369369506836, Predicted Probability: 0.0192, Prediction: 0.0

Epoch 1/3:  96%|█████████▋| 3859/4000 [37:01<00:59,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.930233001708984, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.557743549346924, Predicted Probability: 0.0014, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: 0.030994433909654617, Predicted Probability: 0.5077, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.741143226623535, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 1/3:  96%|█████████▋| 3860/4000 [37:01<01:04,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.971593856811523, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.115607261657715, Predicted Probability: 0.9839, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3861/4000 [37:02<01:17,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.279298782348633, Predicted Probability: 0.9637, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.656183958053589, Predicted Probability: 0.0252, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3862/4000 [37:03<01:24,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.317317485809326, Predicted Probability: 0.9650, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.3719892501831055, Predicted Probability: 0.0125, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3863/4000 [37:04<01:33,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.764326095581055, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.993461608886719, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3864/4000 [37:05<01:37,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.049721717834473, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9327497482299805, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3865/4000 [37:05<01:38,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5342557430267334, Predicted Probability: 0.0284, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.085712194442749, Predicted Probability: 0.0437, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3866/4000 [37:06<01:17,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.257548809051514, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7402026653289795, Predicted Probability: 0.9768, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3867/4000 [37:06<01:15,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.766408920288086, Predicted Probability: 0.9408, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.398379325866699, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3868/4000 [37:06<01:06,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.626119613647461, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4104835987091064, Predicted Probability: 0.0320, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3869/4000 [37:07<01:03,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7624133825302124, Predicted Probability: 0.1465, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.542570114135742, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3870/4000 [37:08<01:12,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5892263650894165, Predicted Probability: 0.3568, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.431248664855957, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3871/4000 [37:08<01:18,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.625016212463379, Predicted Probability: 0.0675, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.307208061218262, Predicted Probability: 0.0133, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3872/4000 [37:09<01:24,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4169158935546875, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5969901084899902, Predicted Probability: 0.9307, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3873/4000 [37:10<01:31,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.0258307456970215, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.758927345275879, Predicted Probability: 0.0228, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3874/4000 [37:11<01:35,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.451275825500488, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.600369930267334, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3875/4000 [37:11<01:20,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.564013957977295, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.443669080734253, Predicted Probability: 0.9690, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3876/4000 [37:12<01:24,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.534989356994629, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.698697566986084, Predicted Probability: 0.9758, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3877/4000 [37:13<01:24,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.609658241271973, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3791441917419434, Predicted Probability: 0.9152, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3878/4000 [37:13<01:13,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3821637630462646, Predicted Probability: 0.0845, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.550065040588379, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3879/4000 [37:13<01:04,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.6993029117584229, Predicted Probability: 0.8454, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.179341793060303, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3880/4000 [37:14<01:04,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.400361061096191, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.21191668510437, Predicted Probability: 0.9613, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3881/4000 [37:15<01:10,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1132712364196777, Predicted Probability: 0.8922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.452468395233154, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3882/4000 [37:15<01:03,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.135204315185547, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.211299419403076, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3883/4000 [37:16<01:09,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.239248752593994, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3100264072418213, Predicted Probability: 0.7875, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3884/4000 [37:17<01:15,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.811165809631348, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8291361331939697, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3885/4000 [37:17<01:10,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.818211555480957, Predicted Probability: 0.9785, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.413424253463745, Predicted Probability: 0.9681, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3886/4000 [37:18<01:14,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.497406959533691, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.056824207305908, Predicted Probability: 0.0449, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3887/4000 [37:18<01:05,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.602086067199707, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.11637020111084, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3888/4000 [37:19<01:12,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.699608564376831, Predicted Probability: 0.0241, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1400156021118164, Predicted Probability: 0.8947, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3889/4000 [37:20<01:13,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9006327390670776, Predicted Probability: 0.7111, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.044316530227661, Predicted Probability: 0.8854, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3891/4000 [37:20<00:50,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5369391441345215, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.843506336212158, Predicted Probability: 0.9989, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -2.974297046661377, Predicted Probability: 0.0486, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.226630687713623, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3892/4000 [37:21<00:59,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9936776757240295, Predicted Probability: 0.7298, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.925244331359863, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3893/4000 [37:22<00:53,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.102818965911865, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.7224318981170654, Predicted Probability: 0.0617, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3894/4000 [37:22<00:48,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.023495674133301, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.267539978027344, Predicted Probability: 0.9862, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3895/4000 [37:23<00:56,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.196361064910889, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0221598148345947, Predicted Probability: 0.8831, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3896/4000 [37:23<00:56,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.273563861846924, Predicted Probability: 0.9635, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5957809686660767, Predicted Probability: 0.6447, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3897/4000 [37:24<01:01,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0900533199310303, Predicted Probability: 0.0435, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.609808921813965, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 1/3:  97%|█████████▋| 3898/4000 [37:25<01:05,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1874704360961914, Predicted Probability: 0.0396, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.046597957611084, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  97%|█████████▋| 3899/4000 [37:25<00:51,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9763898849487305, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.851648330688477, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3900/4000 [37:25<00:46,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.557867527008057, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.98937726020813, Predicted Probability: 0.9818, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3901/4000 [37:26<00:56,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1472976207733154, Predicted Probability: 0.7590, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.379748344421387, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3902/4000 [37:26<00:49,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.431028366088867, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.8536906242370605, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3904/4000 [37:27<00:38,  2.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.1068220138549805, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.287132263183594, Predicted Probability: 0.9950, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.077225208282471, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.489985942840576, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3905/4000 [37:28<00:49,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.169878005981445, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.570230007171631, Predicted Probability: 0.9726, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3906/4000 [37:28<00:44,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.68367338180542, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.996135711669922, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3907/4000 [37:29<00:50,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2503559589385986, Predicted Probability: 0.9047, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.330494403839111, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3908/4000 [37:30<00:56,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.549376964569092, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4551279544830322, Predicted Probability: 0.0306, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3909/4000 [37:30<00:49,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8003098964691162, Predicted Probability: 0.8582, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.478601455688477, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3910/4000 [37:30<00:39,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.035953998565674, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 4.299273490905762, Predicted Probability: 0.9866, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3911/4000 [37:31<00:49,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8603097796440125, Predicted Probability: 0.2973, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.993776798248291, Predicted Probability: 0.0181, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3912/4000 [37:32<00:51,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.968770742416382, Predicted Probability: 0.0489, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.862377882003784, Predicted Probability: 0.9460, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3913/4000 [37:32<00:44,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.227491855621338, Predicted Probability: 0.0381, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.114544868469238, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3914/4000 [37:33<00:50,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7096872329711914, Predicted Probability: 0.0239, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.999610185623169, Predicted Probability: 0.9526, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3915/4000 [37:33<00:44,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.295740127563477, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.550019264221191, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3916/4000 [37:34<00:40,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.00084924697876, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.019805908203125, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3917/4000 [37:34<00:46,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.218092679977417, Predicted Probability: 0.0981, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1103515625, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3918/4000 [37:35<00:50,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5104660987854, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5260627269744873, Predicted Probability: 0.9259, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3919/4000 [37:36<00:52,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.047860860824585, Predicted Probability: 0.8857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.51051139831543, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3920/4000 [37:37<00:57,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.38641357421875, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.641952037811279, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3921/4000 [37:38<01:00,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.977274179458618, Predicted Probability: 0.9515, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.197464466094971, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3922/4000 [37:38<00:58,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.246180057525635, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2048540115356445, Predicted Probability: 0.9007, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3923/4000 [37:39<00:49,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.615663528442383, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.926954746246338, Predicted Probability: 0.0508, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3924/4000 [37:39<00:42,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.621331691741943, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.604309558868408, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3925/4000 [37:39<00:38,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.804195880889893, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.556598663330078, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3926/4000 [37:40<00:42,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.610506772994995, Predicted Probability: 0.0685, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7092487812042236, Predicted Probability: 0.9376, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3927/4000 [37:41<00:46,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.777608633041382, Predicted Probability: 0.9776, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.542823791503906, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3928/4000 [37:42<00:48,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2735276222229004, Predicted Probability: 0.9635, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.140873908996582, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3929/4000 [37:42<00:49,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.628856182098389, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5279525518417358, Predicted Probability: 0.8217, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3930/4000 [37:43<00:49,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.840821385383606, Predicted Probability: 0.6986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.731492519378662, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3931/4000 [37:44<00:43,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.373411655426025, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2072479724884033, Predicted Probability: 0.9611, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3932/4000 [37:44<00:34,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5185455083847046, Predicted Probability: 0.1797, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.847994804382324, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3933/4000 [37:44<00:34,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.474489212036133, Predicted Probability: 0.9700, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.334144592285156, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3934/4000 [37:45<00:31,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.886116981506348, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.864408254623413, Predicted Probability: 0.9795, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3935/4000 [37:45<00:32,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7590386867523193, Predicted Probability: 0.1469, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0832338333129883, Predicted Probability: 0.0438, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3936/4000 [37:45<00:26,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.639668941497803, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.028614044189453, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3937/4000 [37:46<00:31,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1037933826446533, Predicted Probability: 0.8913, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.51704740524292, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 1/3:  98%|█████████▊| 3938/4000 [37:47<00:28,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.416917085647583, Predicted Probability: 0.8049, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.378663539886475, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3939/4000 [37:47<00:34,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.383665561676025, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.882053554058075, Predicted Probability: 0.7072, Prediction: 1.0

Epoch 1/3:  98%|█████████▊| 3940/4000 [37:48<00:37,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.318289756774902, Predicted Probability: 0.0131, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.428706407546997, Predicted Probability: 0.9190, Prediction: 1.0

Epoch 1/3:  99%|█████████▊| 3941/4000 [37:49<00:39,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.219148635864258, Predicted Probability: 0.0385, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4043469429016113, Predicted Probability: 0.9172, Prediction: 1.0

Epoch 1/3:  99%|█████████▊| 3942/4000 [37:49<00:33,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.339344024658203, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.670746803283691, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 1/3:  99%|█████████▊| 3943/4000 [37:50<00:29,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.544610977172852, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.551424980163574, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 1/3:  99%|█████████▊| 3944/4000 [37:50<00:32,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.599970817565918, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.217395544052124, Predicted Probability: 0.9018, Prediction: 1.0

Epoch 1/3:  99%|█████████▊| 3945/4000 [37:51<00:29,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7286272048950195, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4837563037872314, Predicted Probability: 0.0298, Prediction: 0.0

Epoch 1/3:  99%|█████████▊| 3946/4000 [37:52<00:32,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6407573223114014, Predicted Probability: 0.9334, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8142588138580322, Predicted Probability: 0.0216, Prediction: 0.0

Epoch 1/3:  99%|█████████▊| 3947/4000 [37:52<00:34,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.75122594833374, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4051713943481445, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 1/3:  99%|█████████▊| 3948/4000 [37:53<00:36,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.390596389770508, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.078514099121094, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 1/3:  99%|█████████▊| 3949/4000 [37:54<00:37,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.392345428466797, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.520880699157715, Predicted Probability: 0.9256, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3950/4000 [37:55<00:36,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.400440692901611, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.714714527130127, Predicted Probability: 0.9379, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3951/4000 [37:55<00:33,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.445311546325684, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.949263334274292, Predicted Probability: 0.8754, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3952/4000 [37:56<00:29,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.263435125350952, Predicted Probability: 0.9632, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.608520984649658, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3953/4000 [37:56<00:30,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.317745685577393, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3660988807678223, Predicted Probability: 0.9142, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3954/4000 [37:57<00:31,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.153923273086548, Predicted Probability: 0.8960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.297591209411621, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3955/4000 [37:58<00:31,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.860159397125244, Predicted Probability: 0.0077, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.654151439666748, Predicted Probability: 0.9343, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3956/4000 [37:58<00:28,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.082671880722046, Predicted Probability: 0.1108, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.591482400894165, Predicted Probability: 0.1692, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3957/4000 [37:59<00:28,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3856589794158936, Predicted Probability: 0.0327, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.683661460876465, Predicted Probability: 0.9361, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3958/4000 [38:00<00:26,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7301158905029297, Predicted Probability: 0.9766, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.151673316955566, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3959/4000 [38:00<00:20,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.365609169006348, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.581510543823242, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3960/4000 [38:00<00:18,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.4231843650341034, Predicted Probability: 0.3958, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.410025119781494, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3961/4000 [38:01<00:18,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.8363823890686035, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7476842403411865, Predicted Probability: 0.9770, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3962/4000 [38:01<00:17,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.441967964172363, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1730093955993652, Predicted Probability: 0.1022, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3963/4000 [38:02<00:18,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.049864768981934, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2721081972122192, Predicted Probability: 0.2189, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3964/4000 [38:02<00:18,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.182428359985352, Predicted Probability: 0.9850, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.76758337020874, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3965/4000 [38:03<00:17,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.365292072296143, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.618404388427734, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3966/4000 [38:04<00:19,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6650235652923584, Predicted Probability: 0.1591, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.975247621536255, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3967/4000 [38:04<00:16,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.392953395843506, Predicted Probability: 0.0122, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.05627965927124, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3968/4000 [38:04<00:15,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.039056301116943, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.222450256347656, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3969/4000 [38:05<00:13,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7163610458374023, Predicted Probability: 0.0237, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.061776161193848, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3970/4000 [38:05<00:16,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.587967872619629, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5967626571655273, Predicted Probability: 0.9307, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3971/4000 [38:06<00:17,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.31456184387207, Predicted Probability: 0.9868, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2170488834381104, Predicted Probability: 0.0385, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3972/4000 [38:07<00:15,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.002739429473877, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9417388439178467, Predicted Probability: 0.2805, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3973/4000 [38:07<00:16,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.158563613891602, Predicted Probability: 0.9846, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.208184719085693, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3974/4000 [38:08<00:13,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.596836090087891, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.63876485824585, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3975/4000 [38:08<00:11,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.190369606018066, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.395323753356934, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3976/4000 [38:09<00:11,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.643646001815796, Predicted Probability: 0.0664, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.142446994781494, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 1/3:  99%|█████████▉| 3977/4000 [38:09<00:10,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.217365264892578, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8779561519622803, Predicted Probability: 0.1326, Prediction: 0.0

Epoch 1/3:  99%|█████████▉| 3979/4000 [38:10<00:07,  2.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.377151012420654, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.62168025970459, Predicted Probability: 0.9903, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.831627368927002, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.977798938751221, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3980/4000 [38:10<00:07,  2.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.4913089275360107, Predicted Probability: 0.9704, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.654805660247803, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3981/4000 [38:11<00:08,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.836925983428955, Predicted Probability: 0.9789, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.35569167137145996, Predicted Probability: 0.4120, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3982/4000 [38:11<00:10,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3079605102539062, Predicted Probability: 0.0353, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2302141189575195, Predicted Probability: 0.0143, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3983/4000 [38:12<00:10,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.140152931213379, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.081851005554199, Predicted Probability: 0.0166, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3984/4000 [38:13<00:08,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3796112537384033, Predicted Probability: 0.4062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.359735488891602, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3985/4000 [38:13<00:07,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4175775051116943, Predicted Probability: 0.0818, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0004658699035645, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3986/4000 [38:13<00:06,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.241402626037598, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.568634510040283, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3987/4000 [38:14<00:07,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.541724681854248, Predicted Probability: 0.8237, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.75449800491333, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3989/4000 [38:15<00:05,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8098280429840088, Predicted Probability: 0.3079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.518310070037842, Predicted Probability: 0.0040, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -6.081582069396973, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.218153953552246, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3990/4000 [38:16<00:05,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.33294677734375, Predicted Probability: 0.5825, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.559187412261963, Predicted Probability: 0.0104, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3992/4000 [38:17<00:03,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6000494956970215, Predicted Probability: 0.9309, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7491455078125, Predicted Probability: 0.0086, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.342060565948486, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.116459369659424, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3993/4000 [38:17<00:03,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.343936443328857, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6553473472595215, Predicted Probability: 0.9906, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3994/4000 [38:18<00:03,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.966506004333496, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5856382846832275, Predicted Probability: 0.9299, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3995/4000 [38:19<00:03,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.416682720184326, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.978315353393555, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3996/4000 [38:19<00:02,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.286700248718262, Predicted Probability: 0.9864, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.025154113769531, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3997/4000 [38:20<00:01,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.000997543334961, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.379005491733551, Predicted Probability: 0.5936, Prediction: 1.0

Epoch 1/3: 100%|█████████▉| 3998/4000 [38:20<00:01,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.629737854003906, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4653881788253784, Predicted Probability: 0.3857, Prediction: 0.0

Epoch 1/3: 100%|█████████▉| 3999/4000 [38:21<00:00,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.790110111236572, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9140748977661133, Predicted Probability: 0.8715, Prediction: 1.0

Epoch 1/3: 100%|██████████| 4000/4000 [38:21<00:00,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.95973539352417, Predicted Probability: 0.9813, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.89162015914917, Predicted Probability: 0.0010, Prediction: 0.0
Epoch 1, Loss: 0.2196, Accuracy: 0.9124

Epoch 2/3:   0%|          | 1/4000 [00:00<52:48,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.788512229919434, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7882089614868164, Predicted Probability: 0.9779, Prediction: 1.0

Epoch 2/3:   0%|          | 2/4000 [00:01<36:42,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.688138008117676, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.564060211181641, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:   0%|          | 3/4000 [00:01<43:30,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.800645112991333, Predicted Probability: 0.0573, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0170464515686035, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:   0%|          | 4/4000 [00:02<41:27,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.18073034286499, Predicted Probability: 0.0151, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.236486434936523, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:   0%|          | 5/4000 [00:03<39:55,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6002016067504883, Predicted Probability: 0.9734, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.01826810836792, Predicted Probability: 0.0066, Prediction: 0.0

Epoch 2/3:   0%|          | 6/4000 [00:03<35:07,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.447198867797852, Predicted Probability: 0.0116, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.8183207511901855, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:   0%|          | 7/4000 [00:03<32:06,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.79567289352417, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.190730094909668, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:   0%|          | 8/4000 [00:04<34:33,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9674530029296875, Predicted Probability: 0.9511, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3526833057403564, Predicted Probability: 0.7946, Prediction: 1.0

Epoch 2/3:   0%|          | 9/4000 [00:04<31:33,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.663550853729248, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0119810104370117, Predicted Probability: 0.8820, Prediction: 1.0

Epoch 2/3:   0%|          | 10/4000 [00:05<29:55,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.338592052459717, Predicted Probability: 0.9871, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.384045124053955, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:   0%|          | 11/4000 [00:06<37:30,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.501871109008789, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.400029182434082, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:   0%|          | 12/4000 [00:06<41:27,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.769684314727783, Predicted Probability: 0.9775, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.60823917388916, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   0%|          | 13/4000 [00:07<39:54,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.754968166351318, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.975115776062012, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 2/3:   0%|          | 14/4000 [00:07<35:23,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.013268007896840572, Predicted Probability: 0.4967, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.929651737213135, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:   0%|          | 15/4000 [00:08<32:01,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.944387435913086, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.28465461730957, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:   0%|          | 16/4000 [00:08<33:44,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.987675428390503, Predicted Probability: 0.9818, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.695812225341797, Predicted Probability: 0.9758, Prediction: 1.0

Epoch 2/3:   0%|          | 17/4000 [00:09<34:20,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0047736167907715, Predicted Probability: 0.9528, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.936029314994812, Predicted Probability: 0.2817, Prediction: 0.0

Epoch 2/3:   0%|          | 18/4000 [00:09<39:41,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.591306686401367, Predicted Probability: 0.9303, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.415094375610352, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   0%|          | 19/4000 [00:10<34:54,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.990016937255859, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.445213794708252, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:   0%|          | 20/4000 [00:11<39:28,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8794384002685547, Predicted Probability: 0.9798, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.448895454406738, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:   1%|          | 21/4000 [00:11<34:59,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.49957275390625, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.493428707122803, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:   1%|          | 22/4000 [00:12<39:24,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5848968029022217, Predicted Probability: 0.9730, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.756186008453369, Predicted Probability: 0.0228, Prediction: 0.0

Epoch 2/3:   1%|          | 23/4000 [00:12<42:10,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.400202751159668, Predicted Probability: 0.0121, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3791213035583496, Predicted Probability: 0.9670, Prediction: 1.0

Epoch 2/3:   1%|          | 24/4000 [00:13<40:42,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.550107002258301, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.550405979156494, Predicted Probability: 0.0724, Prediction: 0.0

Epoch 2/3:   1%|          | 25/4000 [00:14<44:28,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.477463722229004, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1022629737854004, Predicted Probability: 0.1089, Prediction: 0.0

Epoch 2/3:   1%|          | 26/4000 [00:14<35:09,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.831611633300781, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.053256988525391, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   1%|          | 27/4000 [00:15<40:39,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.639267921447754, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.537392616271973, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:   1%|          | 28/4000 [00:16<43:24,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4364399909973145, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.293671607971191, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:   1%|          | 29/4000 [00:16<44:44,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.804876327514648, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6240092515945435, Predicted Probability: 0.3489, Prediction: 0.0

Epoch 2/3:   1%|          | 30/4000 [00:17<38:38,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7739149332046509, Predicted Probability: 0.8549, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.777461051940918, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:   1%|          | 31/4000 [00:17<41:27,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9976630210876465, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.971327781677246, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 2/3:   1%|          | 32/4000 [00:18<36:19,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1563286781311035, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.885685443878174, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:   1%|          | 33/4000 [00:18<32:42,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5194108486175537, Predicted Probability: 0.9255, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0651021003723145, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   1%|          | 34/4000 [00:19<33:53,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.963229656219482, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.584078788757324, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 2/3:   1%|          | 35/4000 [00:20<40:53,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.948805809020996, Predicted Probability: 0.0189, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.965914726257324, Predicted Probability: 0.0186, Prediction: 0.0

Epoch 2/3:   1%|          | 36/4000 [00:20<43:33,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.069429397583008, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.015115261077881, Predicted Probability: 0.9533, Prediction: 1.0

Epoch 2/3:   1%|          | 37/4000 [00:21<44:58,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.13992977142334, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9838664531707764, Predicted Probability: 0.9518, Prediction: 1.0

Epoch 2/3:   1%|          | 38/4000 [00:21<38:49,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.08439826965332, Predicted Probability: 0.0166, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5896711349487305, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:   1%|          | 39/4000 [00:22<42:07,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.636737823486328, Predicted Probability: 0.0096, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.392025351524353, Predicted Probability: 0.4032, Prediction: 0.0

Epoch 2/3:   1%|          | 40/4000 [00:23<36:53,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.390121936798096, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.445944786071777, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:   1%|          | 41/4000 [00:23<33:25,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.467647552490234, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.378508567810059, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:   1%|          | 42/4000 [00:24<37:38,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.09665876626968384, Predicted Probability: 0.4759, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.811077117919922, Predicted Probability: 0.0216, Prediction: 0.0

Epoch 2/3:   1%|          | 43/4000 [00:24<40:45,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.842314720153809, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9805855751037598, Predicted Probability: 0.9817, Prediction: 1.0

Epoch 2/3:   1%|          | 44/4000 [00:25<42:36,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.432206153869629, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5129024982452393, Predicted Probability: 0.9250, Prediction: 1.0

Epoch 2/3:   1%|          | 45/4000 [00:25<37:17,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.272204875946045, Predicted Probability: 0.0365, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.408298492431641, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:   1%|          | 46/4000 [00:26<33:17,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.26790189743042, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.78307580947876, Predicted Probability: 0.9917, Prediction: 1.0

Epoch 2/3:   1%|          | 47/4000 [00:27<37:53,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.755967140197754, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2288166880607605, Predicted Probability: 0.4430, Prediction: 0.0

Epoch 2/3:   1%|          | 48/4000 [00:27<40:43,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.805271625518799, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7961358428001404, Predicted Probability: 0.3109, Prediction: 0.0

Epoch 2/3:   1%|          | 49/4000 [00:28<37:35,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.769471168518066, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.694162845611572, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:   1%|▏         | 50/4000 [00:29<42:00,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.628620147705078, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6550281047821045, Predicted Probability: 0.9343, Prediction: 1.0

Epoch 2/3:   1%|▏         | 51/4000 [00:29<38:16,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.258718967437744, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.599882125854492, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:   1%|▏         | 52/4000 [00:30<50:35,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.730348587036133, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.078080177307129, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:   1%|▏         | 53/4000 [00:31<50:14,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.487638235092163, Predicted Probability: 0.0297, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.540111064910889, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:   1%|▏         | 54/4000 [00:32<49:08,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6574720740318298, Predicted Probability: 0.3413, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.079345226287842, Predicted Probability: 0.8889, Prediction: 1.0

Epoch 2/3:   1%|▏         | 55/4000 [00:32<50:28,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0140461921691895, Predicted Probability: 0.0468, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.547307014465332, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:   1%|▏         | 56/4000 [00:33<50:10,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4971981048583984, Predicted Probability: 0.9239, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.862196445465088, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 2/3:   1%|▏         | 57/4000 [00:34<42:28,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.505614280700684, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.197253704071045, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:   1%|▏         | 58/4000 [00:34<45:09,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.054781436920166, Predicted Probability: 0.9830, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.555041313171387, Predicted Probability: 0.0104, Prediction: 0.0

Epoch 2/3:   1%|▏         | 59/4000 [00:35<49:09,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.823740482330322, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9551825523376465, Predicted Probability: 0.1240, Prediction: 0.0

Epoch 2/3:   2%|▏         | 60/4000 [00:36<45:11,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.2700629234313965, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.488970756530762, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 2/3:   2%|▏         | 61/4000 [00:37<46:10,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6050541400909424, Predicted Probability: 0.0688, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.363539934158325, Predicted Probability: 0.9140, Prediction: 1.0

Epoch 2/3:   2%|▏         | 62/4000 [00:37<47:22,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8098089694976807, Predicted Probability: 0.1407, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0274981260299683, Predicted Probability: 0.2636, Prediction: 0.0

Epoch 2/3:   2%|▏         | 63/4000 [00:38<47:58,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.236908435821533, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.659688949584961, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:   2%|▏         | 64/4000 [00:38<40:52,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.930246353149414, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.372883319854736, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:   2%|▏         | 65/4000 [00:39<39:24,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.428891181945801, Predicted Probability: 0.0118, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.455236911773682, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   2%|▏         | 66/4000 [00:39<31:38,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.675674915313721, Predicted Probability: 0.9908, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.028510093688965, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   2%|▏         | 67/4000 [00:40<37:48,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.233370780944824, Predicted Probability: 0.0379, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.699320316314697, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:   2%|▏         | 68/4000 [00:41<41:11,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.676650047302246, Predicted Probability: 0.9753, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2659878730773926, Predicted Probability: 0.0368, Prediction: 0.0

Epoch 2/3:   2%|▏         | 69/4000 [00:42<45:39,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.585229873657227, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.336585998535156, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 2/3:   2%|▏         | 70/4000 [00:42<48:53,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.135780334472656, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.000070571899414, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:   2%|▏         | 71/4000 [00:43<49:09,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8569578528404236, Predicted Probability: 0.2980, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.483569145202637, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:   2%|▏         | 72/4000 [00:44<49:02,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.811244249343872, Predicted Probability: 0.1405, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9803444147109985, Predicted Probability: 0.2728, Prediction: 0.0

Epoch 2/3:   2%|▏         | 73/4000 [00:45<49:00,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.141977310180664, Predicted Probability: 0.9844, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.129241943359375, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 2/3:   2%|▏         | 75/4000 [00:46<38:46,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.929062843322754, Predicted Probability: 0.0507, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2140092849731445, Predicted Probability: 0.9946, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.082300186157227, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.4480438232421875, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   2%|▏         | 76/4000 [00:46<34:42,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.787802696228027, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.566367149353027, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:   2%|▏         | 77/4000 [00:47<39:30,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.952282428741455, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.408153533935547, Predicted Probability: 0.0120, Prediction: 0.0

Epoch 2/3:   2%|▏         | 78/4000 [00:47<38:01,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.872956275939941, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.234952449798584, Predicted Probability: 0.0967, Prediction: 0.0

Epoch 2/3:   2%|▏         | 79/4000 [00:48<33:52,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.810306549072266, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9828975200653076, Predicted Probability: 0.9817, Prediction: 1.0

Epoch 2/3:   2%|▏         | 80/4000 [00:49<39:26,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.916440963745117, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3458614349365234, Predicted Probability: 0.0340, Prediction: 0.0

Epoch 2/3:   2%|▏         | 81/4000 [00:49<42:05,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.062148571014404, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8844205141067505, Predicted Probability: 0.8681, Prediction: 1.0

Epoch 2/3:   2%|▏         | 82/4000 [00:50<50:01,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.290318489074707, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.295927047729492, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 2/3:   2%|▏         | 83/4000 [00:51<45:23,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9394547939300537, Predicted Probability: 0.0191, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1472017765045166, Predicted Probability: 0.8954, Prediction: 1.0

Epoch 2/3:   2%|▏         | 84/4000 [00:52<45:52,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.155086994171143, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7709366083145142, Predicted Probability: 0.3163, Prediction: 0.0

Epoch 2/3:   2%|▏         | 86/4000 [00:52<32:40,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1474289894104, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.562388896942139, Predicted Probability: 0.9986, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -6.238956928253174, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8200364112854, Predicted Probability: 0.0080, Prediction: 0.0

Epoch 2/3:   2%|▏         | 87/4000 [00:53<37:24,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.032895565032959, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0129830837249756, Predicted Probability: 0.8822, Prediction: 1.0

Epoch 2/3:   2%|▏         | 88/4000 [00:54<40:42,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1935715675354004, Predicted Probability: 0.0394, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.346611738204956, Predicted Probability: 0.9127, Prediction: 1.0

Epoch 2/3:   2%|▏         | 89/4000 [00:55<44:44,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.576663970947266, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.910257816314697, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:   2%|▏         | 90/4000 [00:55<45:14,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2282931804656982, Predicted Probability: 0.9028, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.848333835601807, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   2%|▏         | 91/4000 [00:56<42:13,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.792973041534424, Predicted Probability: 0.9423, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.445804119110107, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   2%|▏         | 92/4000 [00:56<36:49,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.538824081420898, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7569966316223145, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:   2%|▏         | 93/4000 [00:57<32:59,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.268403053283691, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.12773734331130981, Predicted Probability: 0.5319, Prediction: 1.0

Epoch 2/3:   2%|▏         | 94/4000 [00:57<38:33,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.793820381164551, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.944234848022461, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:   2%|▏         | 95/4000 [00:58<41:12,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.122596502304077, Predicted Probability: 0.0422, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1190571784973145, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 2/3:   2%|▏         | 96/4000 [00:59<43:03,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.094982624053955, Predicted Probability: 0.8904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.52580451965332, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 2/3:   2%|▏         | 97/4000 [00:59<35:34,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.601746082305908, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.372867584228516, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:   2%|▏         | 98/4000 [01:00<40:42,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.714296340942383, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.766984939575195, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:   2%|▏         | 99/4000 [01:00<32:25,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.637212753295898, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1533448696136475, Predicted Probability: 0.1040, Prediction: 0.0

Epoch 2/3:   2%|▎         | 100/4000 [01:00<26:50,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.489532470703125, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.779501914978027, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   3%|▎         | 101/4000 [01:01<29:48,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.284732818603516, Predicted Probability: 0.0136, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.45176362991333, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   3%|▎         | 102/4000 [01:01<28:06,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7201032638549805, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.126333236694336, Predicted Probability: 0.0159, Prediction: 0.0

Epoch 2/3:   3%|▎         | 103/4000 [01:02<35:13,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4296464920043945, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.13292121887207, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 2/3:   3%|▎         | 104/4000 [01:03<35:08,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.141232490539551, Predicted Probability: 0.9586, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.4284234046936035, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   3%|▎         | 105/4000 [01:03<31:50,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.46191930770874, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.372859954833984, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:   3%|▎         | 106/4000 [01:04<34:56,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.376288890838623, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.367428779602051, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:   3%|▎         | 107/4000 [01:04<32:05,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.136956214904785, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.089360237121582, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:   3%|▎         | 108/4000 [01:04<26:29,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4445929527282715, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.458787441253662, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   3%|▎         | 109/4000 [01:05<33:34,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.030059814453125, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.20874309539794922, Predicted Probability: 0.4480, Prediction: 0.0

Epoch 2/3:   3%|▎         | 110/4000 [01:06<37:10,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.416374444961548, Predicted Probability: 0.9181, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.0235252380371094, Predicted Probability: 0.1168, Prediction: 0.0

Epoch 2/3:   3%|▎         | 111/4000 [01:06<40:03,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.7955478429794312, Predicted Probability: 0.1424, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0913736820220947, Predicted Probability: 0.9565, Prediction: 1.0

Epoch 2/3:   3%|▎         | 112/4000 [01:07<36:42,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6922889947891235, Predicted Probability: 0.1555, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.0966033935546875, Predicted Probability: 0.9836, Prediction: 1.0

Epoch 2/3:   3%|▎         | 113/4000 [01:08<39:19,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9984631538391113, Predicted Probability: 0.2692, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.792458534240723, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:   3%|▎         | 114/4000 [01:08<42:41,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3577301502227783, Predicted Probability: 0.2046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.407956600189209, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   3%|▎         | 115/4000 [01:09<40:35,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.07293176651001, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3217240571975708, Predicted Probability: 0.5797, Prediction: 1.0

Epoch 2/3:   3%|▎         | 116/4000 [01:10<42:20,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3311820030212402, Predicted Probability: 0.9114, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3104047775268555, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 2/3:   3%|▎         | 117/4000 [01:10<37:02,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.202533721923828, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0332143306732178, Predicted Probability: 0.9541, Prediction: 1.0

Epoch 2/3:   3%|▎         | 118/4000 [01:11<37:01,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.226424694061279, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.956179141998291, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:   3%|▎         | 119/4000 [01:11<40:09,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.118234634399414, Predicted Probability: 0.8927, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.97815203666687, Predicted Probability: 0.0184, Prediction: 0.0

Epoch 2/3:   3%|▎         | 120/4000 [01:12<39:02,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8083081245422363, Predicted Probability: 0.0217, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.430772304534912, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   3%|▎         | 121/4000 [01:13<42:53,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.508131980895996, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5869293212890625, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:   3%|▎         | 122/4000 [01:13<37:15,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.951014995574951, Predicted Probability: 0.9811, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.366069793701172, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:   3%|▎         | 123/4000 [01:14<41:16,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8711907863616943, Predicted Probability: 0.9796, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.265434265136719, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:   3%|▎         | 124/4000 [01:15<43:49,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.061023712158203, Predicted Probability: 0.9831, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.261700630187988, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:   3%|▎         | 125/4000 [01:15<47:04,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.278682231903076, Predicted Probability: 0.0137, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.396002769470215, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 2/3:   3%|▎         | 126/4000 [01:16<37:02,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.807216644287109, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9304969906806946, Predicted Probability: 0.2828, Prediction: 0.0

Epoch 2/3:   3%|▎         | 127/4000 [01:16<32:58,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.048750400543213, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.12044093757867813, Predicted Probability: 0.5301, Prediction: 1.0

Epoch 2/3:   3%|▎         | 128/4000 [01:17<38:16,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.770618438720703, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.991597056388855, Predicted Probability: 0.1201, Prediction: 0.0

Epoch 2/3:   3%|▎         | 129/4000 [01:17<37:44,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.503632068634033, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.455443382263184, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 2/3:   3%|▎         | 130/4000 [01:18<39:52,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1407408714294434, Predicted Probability: 0.2422, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.52095365524292, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 2/3:   3%|▎         | 131/4000 [01:19<36:32,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.104813575744629, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.799063682556152, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:   3%|▎         | 132/4000 [01:19<39:48,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1626396179199219, Predicted Probability: 0.2382, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.21209192276001, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:   3%|▎         | 133/4000 [01:20<38:02,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0653586387634277, Predicted Probability: 0.1125, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.227476119995117, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 2/3:   3%|▎         | 134/4000 [01:21<41:06,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2348251342773438, Predicted Probability: 0.0379, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.204440593719482, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 2/3:   3%|▎         | 135/4000 [01:21<43:50,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.523761034011841, Predicted Probability: 0.0742, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5285883545875549, Predicted Probability: 0.3708, Prediction: 0.0

Epoch 2/3:   3%|▎         | 136/4000 [01:22<34:37,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.623493194580078, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0543975830078125, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   3%|▎         | 137/4000 [01:22<41:02,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.32843542098999, Predicted Probability: 0.0130, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6837087869644165, Predicted Probability: 0.8434, Prediction: 1.0

Epoch 2/3:   3%|▎         | 138/4000 [01:23<36:14,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.821981430053711, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.31614351272583, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:   3%|▎         | 139/4000 [01:23<29:19,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.177480220794678, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.252472400665283, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:   4%|▎         | 140/4000 [01:23<24:26,  2.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.506722450256348, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.60627555847168, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:   4%|▎         | 141/4000 [01:24<24:31,  2.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.561725616455078, Predicted Probability: 0.0276, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.931055068969727, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:   4%|▎         | 142/4000 [01:24<32:07,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.911059379577637, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.109045028686523, Predicted Probability: 0.0162, Prediction: 0.0

Epoch 2/3:   4%|▎         | 143/4000 [01:25<37:49,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.546853542327881, Predicted Probability: 0.9274, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.168318510055542, Predicted Probability: 0.0404, Prediction: 0.0

Epoch 2/3:   4%|▎         | 144/4000 [01:26<33:30,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.805047988891602, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.207949638366699, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 2/3:   4%|▎         | 145/4000 [01:26<39:03,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.821080446243286, Predicted Probability: 0.9438, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.831915855407715, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:   4%|▎         | 146/4000 [01:27<34:28,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.474790573120117, Predicted Probability: 0.9887, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.85458517074585, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:   4%|▎         | 147/4000 [01:27<31:29,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.661576747894287, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.949769496917725, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:   4%|▎         | 148/4000 [01:28<36:00,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.437516212463379, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.271726608276367, Predicted Probability: 0.9065, Prediction: 1.0

Epoch 2/3:   4%|▎         | 149/4000 [01:29<40:18,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.617260456085205, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.3009922504425049, Predicted Probability: 0.7860, Prediction: 1.0

Epoch 2/3:   4%|▍         | 150/4000 [01:29<32:10,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.43992805480957, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.707906246185303, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:   4%|▍         | 151/4000 [01:30<36:53,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.414166450500488, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9393739700317383, Predicted Probability: 0.9809, Prediction: 1.0

Epoch 2/3:   4%|▍         | 152/4000 [01:30<33:05,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.650262832641602, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.064689874649048, Predicted Probability: 0.1126, Prediction: 0.0

Epoch 2/3:   4%|▍         | 153/4000 [01:30<30:00,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.087612628936768, Predicted Probability: 0.0165, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.222325325012207, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:   4%|▍         | 154/4000 [01:31<35:25,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.247529983520508, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6664199829101562, Predicted Probability: 0.9751, Prediction: 1.0

Epoch 2/3:   4%|▍         | 155/4000 [01:32<39:27,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.561572074890137, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3184428215026855, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 2/3:   4%|▍         | 156/4000 [01:32<34:48,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.549076557159424, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.203737497329712, Predicted Probability: 0.0994, Prediction: 0.0

Epoch 2/3:   4%|▍         | 157/4000 [01:33<34:36,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.459469318389893, Predicted Probability: 0.9886, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9586212635040283, Predicted Probability: 0.9507, Prediction: 1.0

Epoch 2/3:   4%|▍         | 158/4000 [01:33<32:35,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.071435451507568, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.678558111190796, Predicted Probability: 0.9754, Prediction: 1.0

Epoch 2/3:   4%|▍         | 159/4000 [01:34<37:29,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.248510360717773, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.036814212799072, Predicted Probability: 0.9935, Prediction: 1.0

Epoch 2/3:   4%|▍         | 160/4000 [01:35<40:13,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.970461845397949, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5248236656188965, Predicted Probability: 0.9714, Prediction: 1.0

Epoch 2/3:   4%|▍         | 161/4000 [01:35<38:49,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.45095682144165, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.818004131317139, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   4%|▍         | 162/4000 [01:36<37:41,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.098225116729736, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.463958740234375, Predicted Probability: 0.9696, Prediction: 1.0

Epoch 2/3:   4%|▍         | 163/4000 [01:37<46:12,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.983955383300781, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.061049699783325, Predicted Probability: 0.9553, Prediction: 1.0

Epoch 2/3:   4%|▍         | 164/4000 [01:38<46:44,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.922820568084717, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.024378538131714, Predicted Probability: 0.9537, Prediction: 1.0

Epoch 2/3:   4%|▍         | 165/4000 [01:38<43:33,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.022120475769043, Predicted Probability: 0.9824, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2782182693481445, Predicted Probability: 0.2179, Prediction: 0.0

Epoch 2/3:   4%|▍         | 166/4000 [01:39<44:15,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.14003849029541, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2196760177612305, Predicted Probability: 0.0384, Prediction: 0.0

Epoch 2/3:   4%|▍         | 167/4000 [01:40<45:47,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.904558181762695, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.414894104003906, Predicted Probability: 0.0120, Prediction: 0.0

Epoch 2/3:   4%|▍         | 168/4000 [01:40<47:32,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.676046371459961, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.805036544799805, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:   4%|▍         | 169/4000 [01:41<43:36,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.7199320793151855, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9113264083862305, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:   4%|▍         | 170/4000 [01:42<44:34,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4748568534851074, Predicted Probability: 0.9700, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.701438903808594, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:   4%|▍         | 171/4000 [01:42<41:35,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.618284225463867, Predicted Probability: 0.0680, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.175986289978027, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:   4%|▍         | 172/4000 [01:43<36:28,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.764909267425537, Predicted Probability: 0.9774, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3786444664001465, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:   4%|▍         | 173/4000 [01:43<40:18,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.629032611846924, Predicted Probability: 0.9327, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.836773872375488, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   4%|▍         | 174/4000 [01:44<35:24,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3257832527160645, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.361499309539795, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:   4%|▍         | 175/4000 [01:45<40:43,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3667707443237305, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.431492805480957, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 2/3:   4%|▍         | 176/4000 [01:45<35:57,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.392970085144043, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.828786849975586, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:   4%|▍         | 177/4000 [01:45<32:07,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.209895610809326, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.65159273147583, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   4%|▍         | 178/4000 [01:46<26:27,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4625678062438965, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.818000316619873, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   4%|▍         | 179/4000 [01:46<32:29,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.572542190551758, Predicted Probability: 0.9727, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.5515336990356445, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:   4%|▍         | 180/4000 [01:47<29:59,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.673336029052734, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.418265342712402, Predicted Probability: 0.9881, Prediction: 1.0

Epoch 2/3:   5%|▍         | 181/4000 [01:47<35:15,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.916888236999512, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1976559162139893, Predicted Probability: 0.9000, Prediction: 1.0

Epoch 2/3:   5%|▍         | 182/4000 [01:48<40:22,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.006058216094971, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.764746189117432, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:   5%|▍         | 183/4000 [01:49<43:04,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5658084750175476, Predicted Probability: 0.6378, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.776561737060547, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   5%|▍         | 184/4000 [01:49<37:20,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.3654428720474243, Predicted Probability: 0.2034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.90388822555542, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:   5%|▍         | 185/4000 [01:50<40:59,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.059711456298828, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.281125068664551, Predicted Probability: 0.9864, Prediction: 1.0

Epoch 2/3:   5%|▍         | 186/4000 [01:51<43:05,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.176033973693848, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6683390140533447, Predicted Probability: 0.9351, Prediction: 1.0

Epoch 2/3:   5%|▍         | 187/4000 [01:51<34:08,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.497673511505127, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.867034435272217, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:   5%|▍         | 188/4000 [01:51<30:45,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.480788707733154, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.43177604675293, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   5%|▍         | 189/4000 [01:52<30:19,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.06370735168457, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.52805233001709, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 2/3:   5%|▍         | 190/4000 [01:53<35:18,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9593157768249512, Predicted Probability: 0.8765, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.265754222869873, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 2/3:   5%|▍         | 191/4000 [01:53<38:31,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.010358810424805, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5677406787872314, Predicted Probability: 0.9288, Prediction: 1.0

Epoch 2/3:   5%|▍         | 192/4000 [01:54<37:11,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2917590141296387, Predicted Probability: 0.9641, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.731945514678955, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 2/3:   5%|▍         | 193/4000 [01:54<36:15,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.18464994430542, Predicted Probability: 0.9603, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8995187282562256, Predicted Probability: 0.1302, Prediction: 0.0

Epoch 2/3:   5%|▍         | 194/4000 [01:55<39:46,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.501067161560059, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.368022918701172, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:   5%|▍         | 195/4000 [01:56<34:51,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.919544219970703, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.863554954528809, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:   5%|▍         | 196/4000 [01:56<38:08,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5673813819885254, Predicted Probability: 0.9287, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.559328556060791, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:   5%|▍         | 197/4000 [01:57<37:18,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.186026096343994, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.665844440460205, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   5%|▍         | 198/4000 [01:57<36:27,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5757927894592285, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1600964069366455, Predicted Probability: 0.9593, Prediction: 1.0

Epoch 2/3:   5%|▍         | 199/4000 [01:58<39:03,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.9642901420593262, Predicted Probability: 0.8770, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.231025695800781, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:   5%|▌         | 200/4000 [01:58<31:10,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.120937347412109, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.990301132202148, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   5%|▌         | 201/4000 [01:59<37:17,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.434321403503418, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7412071228027344, Predicted Probability: 0.9394, Prediction: 1.0

Epoch 2/3:   5%|▌         | 202/4000 [02:00<33:02,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5681204199790955, Predicted Probability: 0.3617, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.287625789642334, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:   5%|▌         | 203/4000 [02:00<29:59,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.085440158843994, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.143520832061768, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:   5%|▌         | 204/4000 [02:01<36:37,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.220450401306152, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.056065559387207, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 2/3:   5%|▌         | 205/4000 [02:01<39:55,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.676963806152344, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4286246299743652, Predicted Probability: 0.0810, Prediction: 0.0

Epoch 2/3:   5%|▌         | 206/4000 [02:02<41:52,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.632079124450684, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.846219539642334, Predicted Probability: 0.9791, Prediction: 1.0

Epoch 2/3:   5%|▌         | 207/4000 [02:03<37:51,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.889500617980957, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.892268180847168, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:   5%|▌         | 208/4000 [02:03<40:40,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.312970161437988, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8302621841430664, Predicted Probability: 0.9788, Prediction: 1.0

Epoch 2/3:   5%|▌         | 209/4000 [02:04<43:03,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1245229244232178, Predicted Probability: 0.1067, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5064470767974854, Predicted Probability: 0.9246, Prediction: 1.0

Epoch 2/3:   5%|▌         | 210/4000 [02:05<45:08,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6197855472564697, Predicted Probability: 0.0679, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.987851619720459, Predicted Probability: 0.0480, Prediction: 0.0

Epoch 2/3:   5%|▌         | 211/4000 [02:05<35:36,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.283813953399658, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2376468181610107, Predicted Probability: 0.9036, Prediction: 1.0

Epoch 2/3:   5%|▌         | 212/4000 [02:06<35:11,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.507741451263428, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.494678020477295, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:   5%|▌         | 213/4000 [02:06<34:50,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4510092735290527, Predicted Probability: 0.9693, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.09586763381958, Predicted Probability: 0.9836, Prediction: 1.0

Epoch 2/3:   5%|▌         | 214/4000 [02:07<31:32,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9282708168029785, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.365188121795654, Predicted Probability: 0.0126, Prediction: 0.0

Epoch 2/3:   5%|▌         | 215/4000 [02:07<25:54,  2.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.265195846557617, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5644354820251465, Predicted Probability: 0.0715, Prediction: 0.0

Epoch 2/3:   5%|▌         | 216/4000 [02:08<32:13,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.99949312210083, Predicted Probability: 0.0474, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.350290775299072, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 2/3:   5%|▌         | 217/4000 [02:08<36:25,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2774949073791504, Predicted Probability: 0.9070, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.4695210456848145, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:   5%|▌         | 218/4000 [02:09<34:01,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.966870307922363, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.009838104248047, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:   5%|▌         | 219/4000 [02:09<35:15,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.822139024734497, Predicted Probability: 0.9439, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.411748886108398, Predicted Probability: 0.0120, Prediction: 0.0

Epoch 2/3:   6%|▌         | 220/4000 [02:10<29:43,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.449686527252197, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5109612941741943, Predicted Probability: 0.0751, Prediction: 0.0

Epoch 2/3:   6%|▌         | 221/4000 [02:11<37:05,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.899267196655273, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.639863967895508, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:   6%|▌         | 222/4000 [02:11<42:09,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.989374160766602, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.8404483795166016, Predicted Probability: 0.0552, Prediction: 0.0

Epoch 2/3:   6%|▌         | 224/4000 [02:12<27:10,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.318412780761719, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.320380210876465, Predicted Probability: 0.0018, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.555683612823486, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.067578315734863, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:   6%|▌         | 225/4000 [02:12<26:11,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.090141296386719, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.304595470428467, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:   6%|▌         | 226/4000 [02:13<25:13,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.307485580444336, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.30013594031333923, Predicted Probability: 0.4255, Prediction: 0.0

Epoch 2/3:   6%|▌         | 227/4000 [02:13<32:17,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.342418670654297, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.483310699462891, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:   6%|▌         | 228/4000 [02:14<26:39,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.243597030639648, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1376338005065918, Predicted Probability: 0.2428, Prediction: 0.0

Epoch 2/3:   6%|▌         | 229/4000 [02:14<25:47,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.242194652557373, Predicted Probability: 0.9624, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3767781257629395, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 2/3:   6%|▌         | 230/4000 [02:14<26:23,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.515181541442871, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8162829875946045, Predicted Probability: 0.1399, Prediction: 0.0

Epoch 2/3:   6%|▌         | 231/4000 [02:15<33:47,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.483911514282227, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.129434585571289, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:   6%|▌         | 232/4000 [02:15<27:33,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.972722053527832, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9826741218566895, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:   6%|▌         | 233/4000 [02:16<26:22,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.861682415008545, Predicted Probability: 0.0077, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.705942153930664, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 2/3:   6%|▌         | 234/4000 [02:16<25:16,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.288569927215576, Predicted Probability: 0.9865, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.406897068023682, Predicted Probability: 0.9880, Prediction: 1.0

Epoch 2/3:   6%|▌         | 235/4000 [02:17<31:33,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.643037796020508, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9945361614227295, Predicted Probability: 0.9819, Prediction: 1.0

Epoch 2/3:   6%|▌         | 236/4000 [02:18<38:14,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.115787982940674, Predicted Probability: 0.9575, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7306623458862305, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 2/3:   6%|▌         | 237/4000 [02:18<40:21,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.949462413787842, Predicted Probability: 0.0498, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.15487003326416, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 2/3:   6%|▌         | 238/4000 [02:19<43:09,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7356841564178467, Predicted Probability: 0.3239, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.654036998748779, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   6%|▌         | 239/4000 [02:20<43:57,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.458728075027466, Predicted Probability: 0.9212, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3840384781360626, Predicted Probability: 0.5948, Prediction: 1.0

Epoch 2/3:   6%|▌         | 240/4000 [02:21<44:23,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.30609393119812, Predicted Probability: 0.9094, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.193393707275391, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:   6%|▌         | 241/4000 [02:21<44:47,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.545699596405029, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7804887294769287, Predicted Probability: 0.1442, Prediction: 0.0

Epoch 2/3:   6%|▌         | 242/4000 [02:22<45:00,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.843189239501953, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.129521369934082, Predicted Probability: 0.2442, Prediction: 0.0

Epoch 2/3:   6%|▌         | 243/4000 [02:23<45:36,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.014026165008545, Predicted Probability: 0.0177, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.45945405960083, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   6%|▌         | 244/4000 [02:24<46:37,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.016910552978516, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.617763042449951, Predicted Probability: 0.9739, Prediction: 1.0

Epoch 2/3:   6%|▌         | 245/4000 [02:24<46:26,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1819119453430176, Predicted Probability: 0.2347, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.25985050201416, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:   6%|▌         | 246/4000 [02:25<39:36,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.548738956451416, Predicted Probability: 0.9720, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6304574012756348, Predicted Probability: 0.9328, Prediction: 1.0

Epoch 2/3:   6%|▌         | 247/4000 [02:26<43:04,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.155229568481445, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.911849021911621, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:   6%|▌         | 248/4000 [02:26<44:30,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3927063941955566, Predicted Probability: 0.9675, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.714549541473389, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:   6%|▌         | 249/4000 [02:27<44:42,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.175670623779297, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.164838433265686, Predicted Probability: 0.2378, Prediction: 0.0

Epoch 2/3:   6%|▋         | 250/4000 [02:27<38:19,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0333218574523926, Predicted Probability: 0.8843, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.038081645965576, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:   6%|▋         | 251/4000 [02:28<33:50,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.129798412322998, Predicted Probability: 0.9581, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.067989349365234, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 2/3:   6%|▋         | 252/4000 [02:29<37:38,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4429364204406738, Predicted Probability: 0.8089, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.286430835723877, Predicted Probability: 0.9077, Prediction: 1.0

Epoch 2/3:   6%|▋         | 253/4000 [02:29<37:41,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.407176971435547, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.747453451156616, Predicted Probability: 0.9398, Prediction: 1.0

Epoch 2/3:   6%|▋         | 254/4000 [02:30<40:07,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.459339141845703, Predicted Probability: 0.9212, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.315834045410156, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 2/3:   6%|▋         | 255/4000 [02:31<43:27,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.483819961547852, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.983181953430176, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:   6%|▋         | 256/4000 [02:31<37:28,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.146058082580566, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.655700206756592, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   6%|▋         | 257/4000 [02:31<32:57,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.156512260437012, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.669551849365234, Predicted Probability: 0.9907, Prediction: 1.0

Epoch 2/3:   6%|▋         | 258/4000 [02:32<30:00,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.854918956756592, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.597412586212158, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 2/3:   6%|▋         | 259/4000 [02:33<34:55,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6524782180786133, Predicted Probability: 0.8392, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.030486106872559, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:   6%|▋         | 260/4000 [02:33<31:39,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9268364906311035, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.128927707672119, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:   7%|▋         | 261/4000 [02:33<29:27,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6323533654212952, Predicted Probability: 0.6530, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.171016216278076, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:   7%|▋         | 262/4000 [02:34<35:38,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.889863014221191, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.144372940063477, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:   7%|▋         | 263/4000 [02:35<32:12,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.89778470993042, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.329219341278076, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:   7%|▋         | 264/4000 [02:35<36:28,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.890398979187012, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2619144916534424, Predicted Probability: 0.9057, Prediction: 1.0

Epoch 2/3:   7%|▋         | 265/4000 [02:36<38:55,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.212558746337891, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.04035714268684387, Predicted Probability: 0.5101, Prediction: 1.0

Epoch 2/3:   7%|▋         | 266/4000 [02:37<41:40,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.889499664306641, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3134400844573975, Predicted Probability: 0.7881, Prediction: 1.0

Epoch 2/3:   7%|▋         | 268/4000 [02:38<33:47,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1832704544067383, Predicted Probability: 0.0398, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3417153358459473, Predicted Probability: 0.0342, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.097855091094971, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.991739273071289, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:   7%|▋         | 269/4000 [02:38<30:28,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.390941619873047, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.315698146820068, Predicted Probability: 0.0132, Prediction: 0.0

Epoch 2/3:   7%|▋         | 270/4000 [02:39<37:19,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.324334144592285, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.425957679748535, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   7%|▋         | 271/4000 [02:40<36:57,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1644468307495117, Predicted Probability: 0.8970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.273808240890503, Predicted Probability: 0.9067, Prediction: 1.0

Epoch 2/3:   7%|▋         | 272/4000 [02:40<39:59,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.103670120239258, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.945845127105713, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 2/3:   7%|▋         | 273/4000 [02:41<39:18,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8438513278961182, Predicted Probability: 0.1366, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.636474609375, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   7%|▋         | 274/4000 [02:42<43:17,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.815768241882324, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.899702072143555, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 2/3:   7%|▋         | 276/4000 [02:43<34:08,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.430928945541382, Predicted Probability: 0.0808, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.038370370864868, Predicted Probability: 0.8848, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 3.9877419471740723, Predicted Probability: 0.9818, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6453747749328613, Predicted Probability: 0.9337, Prediction: 1.0

Epoch 2/3:   7%|▋         | 277/4000 [02:43<38:15,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2095556259155273, Predicted Probability: 0.0388, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.539557456970215, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:   7%|▋         | 278/4000 [02:44<37:04,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9250621795654297, Predicted Probability: 0.0509, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.685311794281006, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:   7%|▋         | 279/4000 [02:45<39:15,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.413591742515564, Predicted Probability: 0.8043, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7709197998046875, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   7%|▋         | 280/4000 [02:45<35:42,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.579156398773193, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.079179286956787, Predicted Probability: 0.1111, Prediction: 0.0

Epoch 2/3:   7%|▋         | 281/4000 [02:46<40:14,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.435632705688477, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.591678142547607, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:   7%|▋         | 282/4000 [02:46<35:13,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.441743850708008, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.413496017456055, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:   7%|▋         | 283/4000 [02:47<31:19,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.259215354919434, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7048749923706055, Predicted Probability: 0.9760, Prediction: 1.0

Epoch 2/3:   7%|▋         | 284/4000 [02:47<35:22,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.220990180969238, Predicted Probability: 0.9855, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.668511390686035, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 2/3:   7%|▋         | 285/4000 [02:48<40:21,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.241588592529297, Predicted Probability: 0.0142, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.801227569580078, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 2/3:   7%|▋         | 286/4000 [02:49<38:35,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.808984279632568, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.716922760009766, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:   7%|▋         | 287/4000 [02:50<40:40,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.871237754821777, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7793350219726562, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 2/3:   7%|▋         | 288/4000 [02:50<33:32,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.733966827392578, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4378180503845215, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   7%|▋         | 289/4000 [02:50<27:15,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.440477579832077, Predicted Probability: 0.3916, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.400330066680908, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:   7%|▋         | 290/4000 [02:50<25:46,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.353126049041748, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.488913059234619, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:   7%|▋         | 291/4000 [02:51<25:03,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.14251184463501, Predicted Probability: 0.9844, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.389974117279053, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:   7%|▋         | 292/4000 [02:52<31:19,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.725671768188477, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2951831817626953, Predicted Probability: 0.0357, Prediction: 0.0

Epoch 2/3:   7%|▋         | 293/4000 [02:52<35:47,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.103085517883301, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9661548137664795, Predicted Probability: 0.9814, Prediction: 1.0

Epoch 2/3:   7%|▋         | 294/4000 [02:53<40:20,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0557703971862793, Predicted Probability: 0.0450, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.396812438964844, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 2/3:   7%|▋         | 295/4000 [02:54<43:23,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.499245643615723, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.4676799774169922, Predicted Probability: 0.3852, Prediction: 0.0

Epoch 2/3:   7%|▋         | 296/4000 [02:54<36:59,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.72743558883667, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3754470348358154, Predicted Probability: 0.9669, Prediction: 1.0

Epoch 2/3:   7%|▋         | 297/4000 [02:55<40:50,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.803062915802002, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.234682321548462, Predicted Probability: 0.9033, Prediction: 1.0

Epoch 2/3:   7%|▋         | 298/4000 [02:56<42:45,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.832395553588867, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.178072452545166, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:   7%|▋         | 299/4000 [02:57<43:53,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.185079336166382, Predicted Probability: 0.0397, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.698915481567383, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:   8%|▊         | 300/4000 [02:57<44:02,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.687252521514893, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.444995641708374, Predicted Probability: 0.9691, Prediction: 1.0

Epoch 2/3:   8%|▊         | 301/4000 [02:58<35:50,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.474009037017822, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.729197025299072, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:   8%|▊         | 302/4000 [02:58<31:50,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.738264560699463, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.492407321929932, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:   8%|▊         | 303/4000 [02:59<37:26,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.422025680541992, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.445351600646973, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   8%|▊         | 304/4000 [02:59<33:02,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.073647499084473, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.863229274749756, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 2/3:   8%|▊         | 305/4000 [03:00<36:53,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.80166482925415, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1216883659362793, Predicted Probability: 0.8930, Prediction: 1.0

Epoch 2/3:   8%|▊         | 306/4000 [03:01<40:08,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.639394760131836, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.586854934692383, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:   8%|▊         | 307/4000 [03:01<34:52,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.30673885345459, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.015949249267578, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   8%|▊         | 308/4000 [03:02<38:43,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.399503707885742, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.680065155029297, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:   8%|▊         | 309/4000 [03:02<38:39,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.734598636627197, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.399148941040039, Predicted Probability: 0.9879, Prediction: 1.0

Epoch 2/3:   8%|▊         | 310/4000 [03:03<33:54,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.27185583114624, Predicted Probability: 0.9862, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.067811965942383, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:   8%|▊         | 311/4000 [03:03<28:42,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.716625690460205, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.627974510192871, Predicted Probability: 0.9741, Prediction: 1.0

Epoch 2/3:   8%|▊         | 312/4000 [03:03<23:50,  2.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.137129306793213, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.154626846313477, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:   8%|▊         | 313/4000 [03:03<20:34,  2.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.471574783325195, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.648894309997559, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:   8%|▊         | 314/4000 [03:04<21:07,  2.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.998167514801025, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.726712703704834, Predicted Probability: 0.9765, Prediction: 1.0

Epoch 2/3:   8%|▊         | 315/4000 [03:04<24:42,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0292155742645264, Predicted Probability: 0.9539, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7695460319519043, Predicted Probability: 0.9775, Prediction: 1.0

Epoch 2/3:   8%|▊         | 316/4000 [03:05<25:23,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8220996856689453, Predicted Probability: 0.9786, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.403068542480469, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:   8%|▊         | 317/4000 [03:05<24:35,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.507175445556641, Predicted Probability: 0.9891, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.042651176452637, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 2/3:   8%|▊         | 318/4000 [03:06<31:21,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.34664249420166, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.11422646045684814, Predicted Probability: 0.4715, Prediction: 0.0

Epoch 2/3:   8%|▊         | 319/4000 [03:07<35:48,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.612946510314941, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5573068857192993, Predicted Probability: 0.8260, Prediction: 1.0

Epoch 2/3:   8%|▊         | 320/4000 [03:07<32:19,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.95384407043457, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.876935958862305, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:   8%|▊         | 321/4000 [03:08<36:56,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.370551586151123, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4013532400131226, Predicted Probability: 0.1976, Prediction: 0.0

Epoch 2/3:   8%|▊         | 322/4000 [03:08<32:49,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.073970794677734, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8160529136657715, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   8%|▊         | 323/4000 [03:09<36:07,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7764679193496704, Predicted Probability: 0.3151, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0078253746032715, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:   8%|▊         | 324/4000 [03:09<32:06,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.130218982696533, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.215672969818115, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 2/3:   8%|▊         | 325/4000 [03:10<37:58,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6468334197998047, Predicted Probability: 0.0254, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.249850749969482, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:   8%|▊         | 326/4000 [03:11<46:24,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.879083633422852, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.173172950744629, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:   8%|▊         | 327/4000 [03:12<45:57,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1593552827835083, Predicted Probability: 0.2388, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2974367141723633, Predicted Probability: 0.0913, Prediction: 0.0

Epoch 2/3:   8%|▊         | 328/4000 [03:13<47:21,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.976818561553955, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.549814224243164, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:   8%|▊         | 329/4000 [03:14<46:30,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.8822736740112305, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8527655601501465, Predicted Probability: 0.8645, Prediction: 1.0

Epoch 2/3:   8%|▊         | 330/4000 [03:14<46:51,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.17069411277771, Predicted Probability: 0.8976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.778225898742676, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:   8%|▊         | 331/4000 [03:15<36:29,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.23750114440918, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.959895610809326, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 2/3:   8%|▊         | 332/4000 [03:15<39:04,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2112386226654053, Predicted Probability: 0.9013, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.318195819854736, Predicted Probability: 0.0131, Prediction: 0.0

Epoch 2/3:   8%|▊         | 333/4000 [03:16<37:07,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.023463487625122, Predicted Probability: 0.9536, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.207696914672852, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:   8%|▊         | 334/4000 [03:16<34:01,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.289816856384277, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7794528007507324, Predicted Probability: 0.0584, Prediction: 0.0

Epoch 2/3:   8%|▊         | 335/4000 [03:17<39:12,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.759211540222168, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.284120082855225, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 2/3:   8%|▊         | 336/4000 [03:18<37:30,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.351330757141113, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8444180488586426, Predicted Probability: 0.9790, Prediction: 1.0

Epoch 2/3:   8%|▊         | 337/4000 [03:18<34:34,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.979974746704102, Predicted Probability: 0.9932, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1188812255859375, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:   8%|▊         | 338/4000 [03:19<38:02,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1472768783569336, Predicted Probability: 0.9588, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.309263229370117, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:   8%|▊         | 339/4000 [03:19<36:29,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.154099702835083, Predicted Probability: 0.9591, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.964433670043945, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:   8%|▊         | 340/4000 [03:20<32:22,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.777738094329834, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.595320463180542, Predicted Probability: 0.9733, Prediction: 1.0

Epoch 2/3:   9%|▊         | 341/4000 [03:20<32:22,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6066244840621948, Predicted Probability: 0.3528, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7779489755630493, Predicted Probability: 0.1446, Prediction: 0.0

Epoch 2/3:   9%|▊         | 342/4000 [03:21<29:39,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.003969192504883, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8167545795440674, Predicted Probability: 0.9785, Prediction: 1.0

Epoch 2/3:   9%|▊         | 343/4000 [03:21<34:09,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.49777889251709, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9556493759155273, Predicted Probability: 0.9812, Prediction: 1.0

Epoch 2/3:   9%|▊         | 344/4000 [03:22<33:40,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.200705051422119, Predicted Probability: 0.9003, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.655500888824463, Predicted Probability: 0.9343, Prediction: 1.0

Epoch 2/3:   9%|▊         | 345/4000 [03:22<30:21,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.840811729431152, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.266204833984375, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:   9%|▊         | 346/4000 [03:23<36:35,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.11411190032959, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.371150970458984, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:   9%|▊         | 347/4000 [03:23<29:45,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.064237117767334, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.515355587005615, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:   9%|▊         | 348/4000 [03:24<27:43,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.610265731811523, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.543731212615967, Predicted Probability: 0.0728, Prediction: 0.0

Epoch 2/3:   9%|▊         | 349/4000 [03:25<33:33,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.443622589111328, Predicted Probability: 0.9690, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.36657190322876, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:   9%|▉         | 350/4000 [03:25<37:15,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.679020881652832, Predicted Probability: 0.9358, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.821605682373047, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:   9%|▉         | 351/4000 [03:26<29:45,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6018006801605225, Predicted Probability: 0.8323, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.811077117919922, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:   9%|▉         | 352/4000 [03:26<35:03,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.180790424346924, Predicted Probability: 0.0151, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.510492324829102, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:   9%|▉         | 353/4000 [03:27<32:30,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.563141822814941, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8502471446990967, Predicted Probability: 0.9792, Prediction: 1.0

Epoch 2/3:   9%|▉         | 354/4000 [03:27<36:15,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.890634059906006, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.215126037597656, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 2/3:   9%|▉         | 355/4000 [03:28<38:39,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.096910238265991, Predicted Probability: 0.8906, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.800121307373047, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:   9%|▉         | 356/4000 [03:29<40:26,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.705305576324463, Predicted Probability: 0.0240, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.925936460494995, Predicted Probability: 0.9807, Prediction: 1.0

Epoch 2/3:   9%|▉         | 357/4000 [03:29<38:01,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.168576240539551, Predicted Probability: 0.9596, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9746193885803223, Predicted Probability: 0.9514, Prediction: 1.0

Epoch 2/3:   9%|▉         | 358/4000 [03:30<42:32,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.777802467346191, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.499960899353027, Predicted Probability: 0.0110, Prediction: 0.0

Epoch 2/3:   9%|▉         | 359/4000 [03:31<36:37,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.996549606323242, Predicted Probability: 0.9820, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.366036891937256, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:   9%|▉         | 360/4000 [03:31<39:00,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.886294364929199, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9037179946899414, Predicted Probability: 0.8703, Prediction: 1.0

Epoch 2/3:   9%|▉         | 361/4000 [03:32<40:43,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.902617931365967, Predicted Probability: 0.9802, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.993717670440674, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   9%|▉         | 362/4000 [03:33<36:40,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.018105506896973, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7333524227142334, Predicted Probability: 0.0234, Prediction: 0.0

Epoch 2/3:   9%|▉         | 363/4000 [03:33<29:31,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.648312568664551, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.302279949188232, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:   9%|▉         | 364/4000 [03:33<24:23,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.601606369018555, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.786912441253662, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:   9%|▉         | 365/4000 [03:34<30:16,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.677091121673584, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.217750310897827, Predicted Probability: 0.9018, Prediction: 1.0

Epoch 2/3:   9%|▉         | 366/4000 [03:35<37:44,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.202268123626709, Predicted Probability: 0.9853, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.665270805358887, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:   9%|▉         | 367/4000 [03:35<30:17,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9792890548706055, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.003140449523926, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:   9%|▉         | 368/4000 [03:35<28:05,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.134329795837402, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.154636383056641, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 2/3:   9%|▉         | 369/4000 [03:36<32:52,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3061795234680176, Predicted Probability: 0.0354, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1777548789978027, Predicted Probability: 0.8982, Prediction: 1.0

Epoch 2/3:   9%|▉         | 370/4000 [03:37<37:14,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0751290321350098, Predicted Probability: 0.8885, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.42989444732666, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:   9%|▉         | 371/4000 [03:37<32:55,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.329666614532471, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.197579860687256, Predicted Probability: 0.9852, Prediction: 1.0

Epoch 2/3:   9%|▉         | 373/4000 [03:38<24:22,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.558192729949951, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.00093412399292, Predicted Probability: 0.0474, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.034024238586426, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7490394115448, Predicted Probability: 0.0230, Prediction: 0.0

Epoch 2/3:   9%|▉         | 374/4000 [03:38<27:13,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.308114528656006, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.678162097930908, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 2/3:   9%|▉         | 375/4000 [03:39<32:40,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.632399559020996, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8952853679656982, Predicted Probability: 0.9801, Prediction: 1.0

Epoch 2/3:   9%|▉         | 376/4000 [03:40<36:11,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.131757974624634, Predicted Probability: 0.8940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.559454917907715, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 2/3:   9%|▉         | 377/4000 [03:40<32:13,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9423718452453613, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.412580490112305, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:   9%|▉         | 378/4000 [03:41<29:29,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.750116348266602, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.581265926361084, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:   9%|▉         | 379/4000 [03:41<36:27,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9200825691223145, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.948764324188232, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  10%|▉         | 380/4000 [03:42<38:43,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.47493314743042, Predicted Probability: 0.9224, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.4461843967437744, Predicted Probability: 0.8094, Prediction: 1.0

Epoch 2/3:  10%|▉         | 381/4000 [03:43<40:27,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.783992767333984, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.10288405418396, Predicted Probability: 0.8912, Prediction: 1.0

Epoch 2/3:  10%|▉         | 382/4000 [03:44<41:51,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.880288124084473, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6216747164726257, Predicted Probability: 0.3494, Prediction: 0.0

Epoch 2/3:  10%|▉         | 383/4000 [03:44<38:56,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.407223224639893, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.666565418243408, Predicted Probability: 0.9751, Prediction: 1.0

Epoch 2/3:  10%|▉         | 384/4000 [03:45<33:56,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.526308059692383, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.842740058898926, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 2/3:  10%|▉         | 385/4000 [03:45<27:33,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.280200004577637, Predicted Probability: 0.0051, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.22280216217041, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  10%|▉         | 386/4000 [03:45<27:11,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.879965305328369, Predicted Probability: 0.9798, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.003604412078857, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  10%|▉         | 387/4000 [03:46<28:46,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.653547286987305, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.741751790046692, Predicted Probability: 0.1491, Prediction: 0.0

Epoch 2/3:  10%|▉         | 388/4000 [03:47<34:24,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.209839820861816, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.678880214691162, Predicted Probability: 0.9754, Prediction: 1.0

Epoch 2/3:  10%|▉         | 389/4000 [03:47<30:40,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.933363914489746, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5450454354286194, Predicted Probability: 0.3670, Prediction: 0.0

Epoch 2/3:  10%|▉         | 390/4000 [03:47<31:25,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.079832553863525, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.64705753326416, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 2/3:  10%|▉         | 391/4000 [03:48<31:38,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.751067638397217, Predicted Probability: 0.0086, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.996993064880371, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  10%|▉         | 392/4000 [03:49<36:30,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0039896965026855, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.155478477478027, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  10%|▉         | 393/4000 [03:49<32:11,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.902719020843506, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7558670043945312, Predicted Probability: 0.0598, Prediction: 0.0

Epoch 2/3:  10%|▉         | 394/4000 [03:50<36:40,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.398815155029297, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.607966184616089, Predicted Probability: 0.9736, Prediction: 1.0

Epoch 2/3:  10%|▉         | 395/4000 [03:51<36:54,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.31133198738098145, Predicted Probability: 0.4228, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.272891998291016, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 2/3:  10%|▉         | 396/4000 [03:51<39:53,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.998255729675293, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0163841247558594, Predicted Probability: 0.8825, Prediction: 1.0

Epoch 2/3:  10%|▉         | 397/4000 [03:52<34:43,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9936203956604, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.184745788574219, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  10%|▉         | 398/4000 [03:52<38:20,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.716334819793701, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.270994782447815, Predicted Probability: 0.2191, Prediction: 0.0

Epoch 2/3:  10%|▉         | 399/4000 [03:53<40:00,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.123396873474121, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.257720947265625, Predicted Probability: 0.9053, Prediction: 1.0

Epoch 2/3:  10%|█         | 400/4000 [03:54<35:03,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.61334228515625, Predicted Probability: 0.6487, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.844417095184326, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  10%|█         | 401/4000 [03:54<31:12,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.565070152282715, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8973844051361084, Predicted Probability: 0.0199, Prediction: 0.0

Epoch 2/3:  10%|█         | 402/4000 [03:54<28:59,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.717002868652344, Predicted Probability: 0.9911, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.526096343994141, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  10%|█         | 403/4000 [03:55<26:47,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.847275257110596, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.426175117492676, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  10%|█         | 404/4000 [03:55<32:01,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.52333927154541, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.767850160598755, Predicted Probability: 0.9774, Prediction: 1.0

Epoch 2/3:  10%|█         | 405/4000 [03:56<29:22,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.853183746337891, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.766741752624512, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  10%|█         | 406/4000 [03:56<27:22,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.888742923736572, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.78422737121582, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:  10%|█         | 407/4000 [03:57<33:50,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.839787483215332, Predicted Probability: 0.9448, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.408298492431641, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  10%|█         | 408/4000 [03:58<36:24,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.01996374130249, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5588942766189575, Predicted Probability: 0.8262, Prediction: 1.0

Epoch 2/3:  10%|█         | 409/4000 [03:59<38:50,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.000792503356934, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.421517848968506, Predicted Probability: 0.9684, Prediction: 1.0

Epoch 2/3:  10%|█         | 410/4000 [03:59<40:47,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.9345598220825195, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1036176681518555, Predicted Probability: 0.2491, Prediction: 0.0

Epoch 2/3:  10%|█         | 411/4000 [04:00<39:37,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.653378009796143, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.16004753112793, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 2/3:  10%|█         | 412/4000 [04:01<42:01,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.093362808227539, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5233473777770996, Predicted Probability: 0.0742, Prediction: 0.0

Epoch 2/3:  10%|█         | 413/4000 [04:02<45:59,  1.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7152191400527954, Predicted Probability: 0.6716, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.719376087188721, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:  10%|█         | 414/4000 [04:02<43:18,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.010413646697998, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.1845321655273438, Predicted Probability: 0.0398, Prediction: 0.0

Epoch 2/3:  10%|█         | 415/4000 [04:03<37:00,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.069005966186523, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.80387544631958, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  10%|█         | 416/4000 [04:03<40:07,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.103485584259033, Predicted Probability: 0.9838, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.378499507904053, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  10%|█         | 417/4000 [04:04<43:10,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.47853946685791, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.334749221801758, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  10%|█         | 418/4000 [04:05<43:50,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8910329341888428, Predicted Probability: 0.9800, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.666018486022949, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  10%|█         | 419/4000 [04:06<45:53,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.061593055725098, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.38735294342041, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  10%|█         | 420/4000 [04:06<38:41,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.607870101928711, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.475474834442139, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  11%|█         | 421/4000 [04:06<30:49,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.400524616241455, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.046120643615723, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  11%|█         | 422/4000 [04:07<25:18,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.099959850311279, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.346802234649658, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  11%|█         | 423/4000 [04:07<31:07,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.728266716003418, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.831129550933838, Predicted Probability: 0.9788, Prediction: 1.0

Epoch 2/3:  11%|█         | 424/4000 [04:08<28:35,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.402846813201904, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.692405700683594, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 2/3:  11%|█         | 425/4000 [04:08<28:00,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.438015460968018, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.801117420196533, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  11%|█         | 426/4000 [04:09<34:05,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.947121620178223, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.516476631164551, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 2/3:  11%|█         | 427/4000 [04:10<38:05,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.094700813293457, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.705384254455566, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  11%|█         | 428/4000 [04:11<41:30,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.615610122680664, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2221499681472778, Predicted Probability: 0.7724, Prediction: 1.0

Epoch 2/3:  11%|█         | 429/4000 [04:11<42:26,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0742621421813965, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.553999900817871, Predicted Probability: 0.9278, Prediction: 1.0

Epoch 2/3:  11%|█         | 430/4000 [04:12<42:47,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9357435703277588, Predicted Probability: 0.2818, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.880854606628418, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  11%|█         | 431/4000 [04:13<39:37,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.100666522979736, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.55312180519104, Predicted Probability: 0.9722, Prediction: 1.0

Epoch 2/3:  11%|█         | 432/4000 [04:13<41:09,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.10898494720459, Predicted Probability: 0.9838, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8075981736183167, Predicted Probability: 0.6916, Prediction: 1.0

Epoch 2/3:  11%|█         | 433/4000 [04:14<42:50,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5812783241271973, Predicted Probability: 0.9729, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.847900390625, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  11%|█         | 435/4000 [04:15<29:26,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.747328758239746, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.430270195007324, Predicted Probability: 0.9882, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.67364501953125, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.137829780578613, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  11%|█         | 436/4000 [04:16<34:53,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.373517990112305, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2115654945373535, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 2/3:  11%|█         | 437/4000 [04:16<30:50,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.125065803527832, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.622952461242676, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  11%|█         | 438/4000 [04:17<34:22,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.783325672149658, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4248948097229004, Predicted Probability: 0.9187, Prediction: 1.0

Epoch 2/3:  11%|█         | 439/4000 [04:18<39:28,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.821755886077881, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.83750057220459, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  11%|█         | 440/4000 [04:18<31:21,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.658510684967041, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.096139430999756, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  11%|█         | 441/4000 [04:19<34:54,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.37656307220459, Predicted Probability: 0.9670, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.767263650894165, Predicted Probability: 0.1459, Prediction: 0.0

Epoch 2/3:  11%|█         | 442/4000 [04:19<38:06,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.359833240509033, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8311816453933716, Predicted Probability: 0.3034, Prediction: 0.0

Epoch 2/3:  11%|█         | 443/4000 [04:20<36:29,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.633173942565918, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.8878939151763916, Predicted Probability: 0.9472, Prediction: 1.0

Epoch 2/3:  11%|█         | 444/4000 [04:21<38:49,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.612768173217773, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5772151947021484, Predicted Probability: 0.9294, Prediction: 1.0

Epoch 2/3:  11%|█         | 445/4000 [04:21<34:55,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.944364070892334, Predicted Probability: 0.9810, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.96026086807251, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  11%|█         | 446/4000 [04:22<38:17,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4140005111694336, Predicted Probability: 0.0821, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.0768766403198242, Predicted Probability: 0.7459, Prediction: 1.0

Epoch 2/3:  11%|█         | 447/4000 [04:22<39:24,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9631389379501343, Predicted Probability: 0.8769, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.036083221435547, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:  11%|█         | 448/4000 [04:23<40:36,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.322208404541016, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6441495418548584, Predicted Probability: 0.9336, Prediction: 1.0

Epoch 2/3:  11%|█         | 449/4000 [04:24<42:49,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.994931221008301, Predicted Probability: 0.0181, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.5807647705078125, Predicted Probability: 0.0101, Prediction: 0.0

Epoch 2/3:  11%|█▏        | 450/4000 [04:24<36:33,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.54207706451416, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.651346206665039, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  11%|█▏        | 451/4000 [04:25<40:00,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.763972282409668, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.648798942565918, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  11%|█▏        | 452/4000 [04:26<42:43,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7207884788513184, Predicted Probability: 0.9382, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.360470771789551, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 2/3:  11%|█▏        | 453/4000 [04:27<45:14,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.278129577636719, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.967357158660889, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  11%|█▏        | 454/4000 [04:27<38:12,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.103931427001953, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.983809947967529, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 2/3:  11%|█▏        | 456/4000 [04:28<24:44,  2.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.896337509155273, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.62502384185791, Predicted Probability: 0.9995, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.536105155944824, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7695367336273193, Predicted Probability: 0.9775, Prediction: 1.0

Epoch 2/3:  11%|█▏        | 457/4000 [04:28<23:47,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.401556968688965, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.343546390533447, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 2/3:  11%|█▏        | 458/4000 [04:28<23:05,  2.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.540297508239746, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.469862937927246, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 2/3:  11%|█▏        | 459/4000 [04:29<28:44,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.558084726333618, Predicted Probability: 0.9281, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.64463996887207, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 460/4000 [04:30<27:07,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.518397092819214, Predicted Probability: 0.9254, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.444324970245361, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 461/4000 [04:30<33:26,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.435034275054932, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6150593757629395, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 462/4000 [04:31<30:02,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.759520053863525, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9920966625213623, Predicted Probability: 0.9819, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 463/4000 [04:31<27:51,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7240142822265625, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.322696685791016, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 464/4000 [04:32<32:48,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.1449713706970215, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.611043930053711, Predicted Probability: 0.9316, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 465/4000 [04:33<36:21,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.655223846435547, Predicted Probability: 0.0252, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.737732887268066, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 466/4000 [04:33<32:03,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.215710639953613, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.227272033691406, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 467/4000 [04:34<36:00,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0833587646484375, Predicted Probability: 0.8893, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.361484527587891, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 468/4000 [04:34<31:52,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.941987037658691, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2707765102386475, Predicted Probability: 0.0366, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 469/4000 [04:34<25:53,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.584272384643555, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.785231590270996, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 470/4000 [04:35<33:49,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6270856857299805, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.52931022644043, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 471/4000 [04:36<37:27,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.951503276824951, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4626786708831787, Predicted Probability: 0.9215, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 472/4000 [04:36<32:45,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.843038082122803, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.870395183563232, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 473/4000 [04:37<32:23,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.374457836151123, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.752908945083618, Predicted Probability: 0.9771, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 474/4000 [04:37<26:22,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.200804233551025, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.597921848297119, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 475/4000 [04:38<31:29,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.923166275024414, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6327850818634033, Predicted Probability: 0.9742, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 476/4000 [04:39<35:51,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9307475090026855, Predicted Probability: 0.0507, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.038586139678955, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 477/4000 [04:39<31:59,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.230611324310303, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.477461338043213, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 478/4000 [04:40<32:02,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.270202159881592, Predicted Probability: 0.9862, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.497043609619141, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 479/4000 [04:40<35:11,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.476548671722412, Predicted Probability: 0.9700, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.08087158203125, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 480/4000 [04:41<38:05,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.991995811462402, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.138484001159668, Predicted Probability: 0.8946, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 481/4000 [04:41<30:24,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.654819965362549, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7282328605651855, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 482/4000 [04:42<27:44,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.470254898071289, Predicted Probability: 0.0113, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.702369213104248, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 483/4000 [04:42<32:20,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.980672836303711, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6941604614257812, Predicted Probability: 0.9367, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 484/4000 [04:43<35:28,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.522589683532715, Predicted Probability: 0.9257, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.770193099975586, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 485/4000 [04:44<34:25,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1600279808044434, Predicted Probability: 0.9593, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7536308765411377, Predicted Probability: 0.0229, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 486/4000 [04:44<37:12,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4230918884277344, Predicted Probability: 0.9186, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.600900650024414, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 487/4000 [04:45<41:15,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.229450225830078, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.531508445739746, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 488/4000 [04:46<42:02,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2867512702941895, Predicted Probability: 0.9864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.722838401794434, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 489/4000 [04:47<38:51,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.184635162353516, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7614634037017822, Predicted Probability: 0.9773, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 490/4000 [04:47<35:03,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.092581748962402, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.335400104522705, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 491/4000 [04:47<30:59,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.464022159576416, Predicted Probability: 0.9696, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.498297214508057, Predicted Probability: 0.9890, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 492/4000 [04:48<34:12,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3104519844055176, Predicted Probability: 0.9097, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.706160545349121, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 493/4000 [04:49<36:58,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.795904159545898, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.94028377532959, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 494/4000 [04:50<39:03,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.405937910079956, Predicted Probability: 0.9173, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.841238975524902, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 495/4000 [04:50<33:53,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.018913745880127, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.565608024597168, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 496/4000 [04:50<31:48,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.447531700134277, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7175092697143555, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 497/4000 [04:51<28:58,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.213435173034668, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6153106689453125, Predicted Probability: 0.9738, Prediction: 1.0

Epoch 2/3:  12%|█▏        | 498/4000 [04:52<34:18,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.784607887268066, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.755486488342285, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 2/3:  12%|█▏        | 499/4000 [04:52<37:48,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.172915458679199, Predicted Probability: 0.9848, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.245948791503906, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  12%|█▎        | 500/4000 [04:53<39:12,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.1821794509887695, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.738275408744812, Predicted Probability: 0.1495, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 501/4000 [04:54<34:01,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1228439807891846, Predicted Probability: 0.0422, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.452289581298828, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 502/4000 [04:54<36:44,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.851409435272217, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7120676040649414, Predicted Probability: 0.9377, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 503/4000 [04:55<38:07,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.100243091583252, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.017012119293213, Predicted Probability: 0.9533, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 504/4000 [04:56<36:14,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.676727771759033, Predicted Probability: 0.9356, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.478519439697266, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 505/4000 [04:56<39:19,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.849980354309082, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.226555824279785, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 506/4000 [04:57<34:04,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7582907676696777, Predicted Probability: 0.9772, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.989680767059326, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 507/4000 [04:57<28:33,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.09714412689209, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.745690822601318, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 508/4000 [04:57<23:38,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.813132286071777, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.311916351318359, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 509/4000 [04:58<30:21,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.162189960479736, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5466834306716919, Predicted Probability: 0.3666, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 510/4000 [04:58<26:03,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.133248329162598, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.609492778778076, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 511/4000 [04:59<26:16,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.319514751434326, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.649428367614746, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 512/4000 [04:59<31:14,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.087555885314941, Predicted Probability: 0.9835, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.059582233428955, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 513/4000 [05:00<29:45,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.171342849731445, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.46220588684082, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 514/4000 [05:00<31:28,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.613190770149231, Predicted Probability: 0.1661, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.653160095214844, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 515/4000 [05:01<35:37,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.900559425354004, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.271997928619385, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 516/4000 [05:02<37:50,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6928768157958984, Predicted Probability: 0.9366, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.221253871917725, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 517/4000 [05:02<32:59,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.025516033172607, Predicted Probability: 0.9825, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.636341094970703, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 518/4000 [05:03<33:27,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.675912857055664, Predicted Probability: 0.9908, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8504672050476074, Predicted Probability: 0.1358, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 519/4000 [05:04<38:08,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.350199222564697, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.319565773010254, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 520/4000 [05:05<40:50,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.782474517822266, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.189437389373779, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 521/4000 [05:05<37:56,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.88848876953125, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.985412359237671, Predicted Probability: 0.9818, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 522/4000 [05:06<34:12,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.243594169616699, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.70710825920105, Predicted Probability: 0.9760, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 523/4000 [05:06<30:31,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.1302080154418945, Predicted Probability: 0.9842, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.957053184509277, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 524/4000 [05:06<28:09,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.697214126586914, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.127323627471924, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 525/4000 [05:07<33:18,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9503482580184937, Predicted Probability: 0.8755, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.039215087890625, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 526/4000 [05:08<30:08,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.515472888946533, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.322329044342041, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 527/4000 [05:08<28:45,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2493174076080322, Predicted Probability: 0.9626, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.498587131500244, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 528/4000 [05:09<33:37,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.110363006591797, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.95418119430542, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 529/4000 [05:10<36:40,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6942059993743896, Predicted Probability: 0.9757, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.960979461669922, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 530/4000 [05:10<35:21,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.560796737670898, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.932539463043213, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 531/4000 [05:10<31:07,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.314248085021973, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.389021873474121, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 532/4000 [05:11<34:20,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8937177658081055, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.620161294937134, Predicted Probability: 0.9321, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 533/4000 [05:12<30:32,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.182669639587402, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.6883225440979, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 534/4000 [05:12<30:43,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.067712306976318, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.481987476348877, Predicted Probability: 0.9702, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 535/4000 [05:13<35:19,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.214782238006592, Predicted Probability: 0.9016, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.201185703277588, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 536/4000 [05:13<29:23,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.054723739624023, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.348289966583252, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 537/4000 [05:14<28:37,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.462129592895508, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.41132926940918, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  13%|█▎        | 538/4000 [05:14<26:30,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7424862384796143, Predicted Probability: 0.9769, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.066279411315918, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  13%|█▎        | 539/4000 [05:15<33:09,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.33174222707748413, Predicted Probability: 0.5822, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.628636360168457, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  14%|█▎        | 540/4000 [05:16<38:35,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4791100025177, Predicted Probability: 0.0773, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8934197425842285, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  14%|█▎        | 541/4000 [05:17<39:56,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.637816905975342, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7933971881866455, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 2/3:  14%|█▎        | 542/4000 [05:17<41:27,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.939109206199646, Predicted Probability: 0.8743, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.053194046020508, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  14%|█▎        | 543/4000 [05:18<38:11,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.903461456298828, Predicted Probability: 0.9480, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.289674758911133, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  14%|█▎        | 544/4000 [05:18<32:59,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4109907150268555, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.299619674682617, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:  14%|█▎        | 545/4000 [05:19<36:50,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.42568039894104, Predicted Probability: 0.9188, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.160686016082764, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  14%|█▎        | 546/4000 [05:20<39:14,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7898736000061035, Predicted Probability: 0.9779, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.30739688873291, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  14%|█▎        | 547/4000 [05:20<32:11,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.7678608894348145, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.876675605773926, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 2/3:  14%|█▎        | 548/4000 [05:21<37:01,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6994781494140625, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.347031593322754, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  14%|█▎        | 549/4000 [05:22<38:05,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.653054237365723, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8062753677368164, Predicted Probability: 0.9430, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 550/4000 [05:22<39:44,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.17232608795166, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6078901290893555, Predicted Probability: 0.9314, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 551/4000 [05:23<34:40,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9817657470703125, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6716065406799316, Predicted Probability: 0.9752, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 552/4000 [05:23<28:55,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.082668781280518, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.652920722961426, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 553/4000 [05:23<26:34,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.598443031311035, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.851614475250244, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 554/4000 [05:24<22:06,  2.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.806604385375977, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.55298376083374, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 555/4000 [05:24<28:55,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.250680923461914, Predicted Probability: 0.9859, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.802952289581299, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 556/4000 [05:25<32:57,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.944326400756836, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4204742908477783, Predicted Probability: 0.0816, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 557/4000 [05:25<29:38,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2875776290893555, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.124294757843018, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 558/4000 [05:26<25:21,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.772777557373047, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.502070903778076, Predicted Probability: 0.9890, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 559/4000 [05:26<24:21,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.118834495544434, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.536465644836426, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 560/4000 [05:27<23:47,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.689489364624023, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.869710922241211, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 561/4000 [05:27<22:58,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.602843761444092, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.088376522064209, Predicted Probability: 0.0165, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 562/4000 [05:27<23:56,  2.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9745774269104, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7040581703186035, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 563/4000 [05:28<23:03,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.59459114074707, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0636701583862305, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 564/4000 [05:29<29:50,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.011308670043945, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0634918212890625, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 565/4000 [05:29<33:25,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5385122299194336, Predicted Probability: 0.9268, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4659528732299805, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 566/4000 [05:30<36:29,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.614269256591797, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2493362426757812, Predicted Probability: 0.9046, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 567/4000 [05:31<38:09,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.920820236206055, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.706368923187256, Predicted Probability: 0.9374, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 568/4000 [05:32<39:48,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.480513572692871, Predicted Probability: 0.9228, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.406752109527588, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 569/4000 [05:32<42:06,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2819647789001465, Predicted Probability: 0.0136, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.743953227996826, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 570/4000 [05:33<34:10,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.813095569610596, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.758096694946289, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 571/4000 [05:33<30:25,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1159749031066895, Predicted Probability: 0.0160, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8517172336578369, Predicted Probability: 0.7009, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 572/4000 [05:34<34:27,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.325349807739258, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.685713052749634, Predicted Probability: 0.9755, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 573/4000 [05:34<36:28,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9455227851867676, Predicted Probability: 0.9501, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.37949275970459, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 574/4000 [05:35<39:26,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.632178783416748, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2419891357421875, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 575/4000 [05:36<40:38,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6199169158935547, Predicted Probability: 0.0679, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.440975189208984, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 576/4000 [05:37<37:28,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.391484498977661, Predicted Probability: 0.9674, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1839067935943604, Predicted Probability: 0.8988, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 577/4000 [05:37<38:58,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9792917966842651, Predicted Probability: 0.2730, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.265981197357178, Predicted Probability: 0.0051, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 578/4000 [05:38<35:08,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.148174285888672, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.724032878875732, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 2/3:  14%|█▍        | 579/4000 [05:38<34:28,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.213440895080566, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.8286051750183105, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  14%|█▍        | 580/4000 [05:39<30:19,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.553384006023407, Predicted Probability: 0.6349, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.827799320220947, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 581/4000 [05:39<27:56,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.804107666015625, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.47382926940918, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 582/4000 [05:40<31:40,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4407894611358643, Predicted Probability: 0.0801, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7522566318511963, Predicted Probability: 0.9400, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 583/4000 [05:40<28:34,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.710733890533447, Predicted Probability: 0.9911, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.048666954040527, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 584/4000 [05:41<26:19,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.31840705871582, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.176673889160156, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 585/4000 [05:41<30:50,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4417691230773926, Predicted Probability: 0.9690, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9423818588256836, Predicted Probability: 0.9810, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 586/4000 [05:42<26:13,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.970366477966309, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.4959425926208496, Predicted Probability: 0.8170, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 587/4000 [05:42<22:54,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.112115859985352, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.228483200073242, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 589/4000 [05:43<23:13,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.04519510269165, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7261040210723877, Predicted Probability: 0.9385, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -3.6913373470306396, Predicted Probability: 0.0243, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6059083938598633, Predicted Probability: 0.9312, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 590/4000 [05:43<26:37,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9104995727539062, Predicted Probability: 0.9484, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8040379881858826, Predicted Probability: 0.3092, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 591/4000 [05:44<25:09,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.685945749282837, Predicted Probability: 0.9755, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.273397445678711, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 592/4000 [05:44<23:55,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9507856369018555, Predicted Probability: 0.0189, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.981616020202637, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 2/3:  15%|█▍        | 593/4000 [05:45<25:56,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2431483268737793, Predicted Probability: 0.0959, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.059365749359131, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 595/4000 [05:46<25:45,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.237229347229004, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.70142936706543, Predicted Probability: 0.0033, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: -5.513455390930176, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.691679954528809, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 596/4000 [05:46<24:37,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.384727954864502, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.820830821990967, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 597/4000 [05:47<29:40,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.83193302154541, Predicted Probability: 0.9444, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.847890377044678, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 598/4000 [05:48<34:26,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.713528633117676, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.951844215393066, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  15%|█▍        | 599/4000 [05:48<36:51,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.815427780151367, Predicted Probability: 0.9784, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.06321907043457, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 600/4000 [05:49<39:07,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.499283313751221, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.273221015930176, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 601/4000 [05:50<40:15,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.455122947692871, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9621142148971558, Predicted Probability: 0.2765, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 602/4000 [05:51<41:17,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.844057083129883, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.007630109786987305, Predicted Probability: 0.4981, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 603/4000 [05:51<32:22,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.709261417388916, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.977105140686035, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 604/4000 [05:52<35:08,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1218206882476807, Predicted Probability: 0.2457, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.894528388977051, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 605/4000 [05:52<28:11,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.68012809753418, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.174461841583252, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 606/4000 [05:53<32:45,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5489397048950195, Predicted Probability: 0.3661, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.32720422744751, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 608/4000 [05:54<28:07,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4050979614257812, Predicted Probability: 0.9172, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.591275215148926, Predicted Probability: 0.0014, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.600336074829102, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.665435314178467, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 609/4000 [05:54<32:11,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.443307876586914, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9485167264938354, Predicted Probability: 0.7208, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 610/4000 [05:55<35:42,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.627692222595215, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.620810031890869, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 611/4000 [05:56<37:15,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6259469985961914, Predicted Probability: 0.8356, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.810232162475586, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 612/4000 [05:57<53:21,  1.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5565946102142334, Predicted Probability: 0.9723, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9989471435546875, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 613/4000 [05:58<50:02,  1.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.885061264038086, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6473164558410645, Predicted Probability: 0.9338, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 614/4000 [05:59<47:30,  1.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4977142810821533, Predicted Probability: 0.8172, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.8458099365234375, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 615/4000 [05:59<39:36,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.811746597290039, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3798460960388184, Predicted Probability: 0.9153, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 616/4000 [06:00<40:15,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9194085597991943, Predicted Probability: 0.0512, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.466525077819824, Predicted Probability: 0.9218, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 617/4000 [06:01<40:18,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.45481014251709, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.333561420440674, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 2/3:  15%|█▌        | 618/4000 [06:01<31:40,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.069381713867188, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9033514261245728, Predicted Probability: 0.1297, Prediction: 0.0

Epoch 2/3:  15%|█▌        | 619/4000 [06:02<35:09,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.764908790588379, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8754472732543945, Predicted Probability: 0.0203, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 620/4000 [06:02<37:25,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.768402099609375, Predicted Probability: 0.0084, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.33935546875, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 621/4000 [06:03<36:41,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.967824935913086, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4218814373016357, Predicted Probability: 0.9684, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 622/4000 [06:04<38:26,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.667696952819824, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.814882755279541, Predicted Probability: 0.9435, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 623/4000 [06:04<30:24,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.094754695892334, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.158411026000977, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 624/4000 [06:04<27:28,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.33158016204834, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.315821409225464, Predicted Probability: 0.0350, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 625/4000 [06:05<25:37,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.266707420349121, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.495969295501709, Predicted Probability: 0.0110, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 626/4000 [06:05<24:02,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2201478481292725, Predicted Probability: 0.9616, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9899862408638, Predicted Probability: 0.7291, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 627/4000 [06:05<22:58,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.908862829208374, Predicted Probability: 0.7128, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2226154804229736, Predicted Probability: 0.0383, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 628/4000 [06:06<29:16,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.778338432312012, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.897851467132568, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 629/4000 [06:07<27:02,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.410970687866211, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4779927730560303, Predicted Probability: 0.0774, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 630/4000 [06:07<31:42,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.917367935180664, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9937207698822021, Predicted Probability: 0.8801, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 631/4000 [06:08<34:36,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8204498291015625, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7957398891448975, Predicted Probability: 0.9424, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 632/4000 [06:09<37:06,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1929681301116943, Predicted Probability: 0.1004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9240200519561768, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 633/4000 [06:09<35:09,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.871967315673828, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.410062313079834, Predicted Probability: 0.9680, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 634/4000 [06:10<33:32,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.1864013671875, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9604222774505615, Predicted Probability: 0.9813, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 635/4000 [06:11<35:23,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.521490573883057, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0590044260025024, Predicted Probability: 0.2575, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 636/4000 [06:11<37:35,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.694203853607178, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7255512475967407, Predicted Probability: 0.3262, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 638/4000 [06:12<30:48,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3831868171691895, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4553208351135254, Predicted Probability: 0.9209, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 1.7802132368087769, Predicted Probability: 0.8557, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.695016860961914, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 640/4000 [06:13<27:27,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.958067893981934, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.057547569274902, Predicted Probability: 0.0009, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -7.242861270904541, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1064682006835938, Predicted Probability: 0.0428, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 641/4000 [06:14<25:16,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.115036964416504, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.029855728149414, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 642/4000 [06:15<32:02,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.402370929718018, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8732147216796875, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 643/4000 [06:15<25:51,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.621952056884766, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.071651935577393, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 645/4000 [06:15<20:04,  2.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8848443031311035, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1530942916870117, Predicted Probability: 0.8960, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.945575714111328, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.412526607513428, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:  16%|█▌        | 646/4000 [06:16<27:21,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.873898506164551, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.93666934967041, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 647/4000 [06:16<22:41,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.48806095123291, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.30315637588501, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 2/3:  16%|█▌        | 649/4000 [06:17<18:43,  2.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6087727546691895, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7077302932739258, Predicted Probability: 0.8465, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.4721150398254395, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3215131759643555, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 650/4000 [06:18<25:31,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.906615734100342, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.780773639678955, Predicted Probability: 0.8558, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 651/4000 [06:18<25:14,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.834900379180908, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7297914028167725, Predicted Probability: 0.0612, Prediction: 0.0

Epoch 2/3:  16%|█▋        | 652/4000 [06:19<26:39,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5358052253723145, Predicted Probability: 0.9266, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.951353549957275, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  16%|█▋        | 653/4000 [06:19<30:23,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5954056978225708, Predicted Probability: 0.8314, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4143513441085815, Predicted Probability: 0.8045, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 654/4000 [06:20<33:33,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.3324055671691895, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1484527587890625, Predicted Probability: 0.1045, Prediction: 0.0

Epoch 2/3:  16%|█▋        | 655/4000 [06:21<34:09,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.524410247802734, Predicted Probability: 0.0107, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.421845436096191, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 2/3:  16%|█▋        | 656/4000 [06:21<30:04,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.880196571350098, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.548699855804443, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 657/4000 [06:22<32:43,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.019871234893799, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.566391706466675, Predicted Probability: 0.9287, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 658/4000 [06:23<35:20,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.910940647125244, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8260135650634766, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 659/4000 [06:23<30:45,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.714546203613281, Predicted Probability: 0.9911, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9496269226074219, Predicted Probability: 0.8754, Prediction: 1.0

Epoch 2/3:  16%|█▋        | 660/4000 [06:24<34:27,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5290591716766357, Predicted Probability: 0.9262, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.541936874389648, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 661/4000 [06:24<36:13,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8419675827026367, Predicted Probability: 0.9449, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.326016426086426, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 662/4000 [06:25<34:47,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.061164379119873, Predicted Probability: 0.9831, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.062255382537842, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 663/4000 [06:26<36:44,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8718278408050537, Predicted Probability: 0.9464, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.5797014236450195, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 664/4000 [06:26<32:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.075926303863525, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.567009449005127, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 665/4000 [06:26<28:40,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.723923206329346, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1391942501068115, Predicted Probability: 0.9585, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 666/4000 [06:27<26:29,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5854082107543945, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.858415603637695, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 667/4000 [06:28<30:42,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.273403167724609, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.84507417678833, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 668/4000 [06:28<24:55,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9876508712768555, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.807799816131592, Predicted Probability: 0.9783, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 669/4000 [06:29<29:54,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2631030082702637, Predicted Probability: 0.9058, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.039251327514648, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 670/4000 [06:29<30:13,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.304567813873291, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.105881214141846, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 671/4000 [06:29<27:18,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.611781597137451, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.361144542694092, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 673/4000 [06:30<25:22,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.962991714477539, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.3124470710754395, Predicted Probability: 0.0018, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.641051292419434, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.939708232879639, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 674/4000 [06:31<24:00,  2.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.192019462585449, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.374075889587402, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 675/4000 [06:31<23:00,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4653143882751465, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.23889684677124, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 676/4000 [06:32<23:18,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.918786525726318, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.666872262954712, Predicted Probability: 0.0650, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 677/4000 [06:32<19:43,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.495149850845337, Predicted Probability: 0.9238, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.166352272033691, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 678/4000 [06:33<27:42,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.010245323181152, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.435149192810059, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 679/4000 [06:33<32:27,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.418489933013916, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.930713176727295, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 680/4000 [06:34<29:14,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.563348770141602, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.438968658447266, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 681/4000 [06:34<26:34,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.194677352905273, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.289636135101318, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 682/4000 [06:35<30:45,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.38047683238983154, Predicted Probability: 0.5940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.745147705078125, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 683/4000 [06:35<24:53,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.092590808868408, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.673489093780518, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 684/4000 [06:36<30:07,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.106139183044434, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6875391006469727, Predicted Probability: 0.9363, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 685/4000 [06:37<33:09,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6827185153961182, Predicted Probability: 0.6643, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9933366775512695, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 686/4000 [06:37<35:42,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.185276031494141, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.054281711578369, Predicted Probability: 0.0450, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 687/4000 [06:38<32:16,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5727121829986572, Predicted Probability: 0.0709, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.843907356262207, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 688/4000 [06:39<35:38,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.986522674560547, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.264163970947266, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 689/4000 [06:39<38:08,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.867411136627197, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.368899822235107, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 690/4000 [06:40<39:55,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.915350914001465, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.486289978027344, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 691/4000 [06:41<34:15,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1267499923706055, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.86656379699707, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 692/4000 [06:41<31:11,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8163344860076904, Predicted Probability: 0.0564, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.761701583862305, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 693/4000 [06:41<25:13,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.468645095825195, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.579982757568359, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 694/4000 [06:42<29:33,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.879511833190918, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.792879343032837, Predicted Probability: 0.9423, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 695/4000 [06:42<29:37,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6037936210632324, Predicted Probability: 0.9311, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6099703311920166, Predicted Probability: 0.0685, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 696/4000 [06:43<27:16,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.430205821990967, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.757123947143555, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 697/4000 [06:44<32:35,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.933618545532227, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.4742431640625, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:  17%|█▋        | 698/4000 [06:44<31:46,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.181263446807861, Predicted Probability: 0.9850, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.77044677734375, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:  17%|█▋        | 699/4000 [06:44<25:44,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.799901008605957, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.073181629180908, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 700/4000 [06:45<30:43,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.520463705062866, Predicted Probability: 0.0744, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.115057945251465, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 701/4000 [06:46<34:11,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.896170139312744, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.233084678649902, Predicted Probability: 0.9857, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 702/4000 [06:46<27:22,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.739318370819092, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.143661022186279, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 703/4000 [06:47<31:08,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3083417415618896, Predicted Probability: 0.9096, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.783904552459717, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 704/4000 [06:47<28:57,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8529181480407715, Predicted Probability: 0.0545, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.092914581298828, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 705/4000 [06:48<26:36,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.091779947280884, Predicted Probability: 0.0434, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.26910924911499, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 706/4000 [06:48<22:03,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.178437232971191, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7479448318481445, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 707/4000 [06:49<28:08,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2662789821624756, Predicted Probability: 0.9060, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8217878341674805, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 708/4000 [06:50<32:45,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.949995040893555, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1532297134399414, Predicted Probability: 0.9590, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 710/4000 [06:50<23:33,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8195853233337402, Predicted Probability: 0.9785, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1034722328186035, Predicted Probability: 0.9838, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.157042026519775, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8440399169921875, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 711/4000 [06:50<19:42,  2.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.248807907104492, Predicted Probability: 0.9859, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.604213237762451, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 712/4000 [06:51<27:16,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2596462965011597, Predicted Probability: 0.2210, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.696501731872559, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 713/4000 [06:51<25:07,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.615879058837891, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9168291091918945, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 714/4000 [06:52<23:45,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.407144784927368, Predicted Probability: 0.0321, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.250551223754883, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 715/4000 [06:52<25:34,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9806494116783142, Predicted Probability: 0.7272, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.503768444061279, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 716/4000 [06:53<30:03,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4882619380950928, Predicted Probability: 0.9233, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.076288223266602, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 717/4000 [06:54<29:58,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.171375751495361, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.077521800994873, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 718/4000 [06:54<27:18,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.436113357543945, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.725035190582275, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 719/4000 [06:55<27:56,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.556354284286499, Predicted Probability: 0.1742, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.128073692321777, Predicted Probability: 0.9841, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 720/4000 [06:55<32:20,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.371279239654541, Predicted Probability: 0.9146, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.173196792602539, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 721/4000 [06:56<25:59,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.903782367706299, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.75001335144043, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 722/4000 [06:56<24:08,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.135512828826904, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.217676639556885, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 723/4000 [06:56<23:07,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.403168201446533, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.684778213500977, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 724/4000 [06:57<29:25,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9228148460388184, Predicted Probability: 0.0194, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.765263557434082, Predicted Probability: 0.9774, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 725/4000 [06:58<33:21,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.571428298950195, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.856270790100098, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 726/4000 [06:59<35:11,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0788905620574951, Predicted Probability: 0.2537, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.728207588195801, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 727/4000 [06:59<31:04,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.105976104736328, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.227043151855469, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 728/4000 [07:00<30:40,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.51347279548645, Predicted Probability: 0.9251, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4717333316802979, Predicted Probability: 0.1867, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 729/4000 [07:00<30:25,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.555208683013916, Predicted Probability: 0.9722, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1742596626281738, Predicted Probability: 0.2361, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 730/4000 [07:00<24:38,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.083534240722656, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.181448936462402, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 731/4000 [07:01<23:28,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.648623943328857, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.19100284576416, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 732/4000 [07:01<28:25,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.7281084060668945, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.12017244100570679, Predicted Probability: 0.5300, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 733/4000 [07:02<33:21,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.85984992980957, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.413078308105469, Predicted Probability: 0.0120, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 734/4000 [07:03<35:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.871034622192383, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.044072151184082, Predicted Probability: 0.0455, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 735/4000 [07:04<37:56,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.261284112930298, Predicted Probability: 0.9631, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.244646072387695, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 736/4000 [07:05<38:57,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.976802825927734, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.213193893432617, Predicted Probability: 0.9014, Prediction: 1.0

Epoch 2/3:  18%|█▊        | 737/4000 [07:05<39:19,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.33610725402832, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1015063524246216, Predicted Probability: 0.2495, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 738/4000 [07:06<39:22,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.514584541320801, Predicted Probability: 0.0108, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.331111431121826, Predicted Probability: 0.0886, Prediction: 0.0

Epoch 2/3:  18%|█▊        | 739/4000 [07:07<41:05,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.180395126342773, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.194428443908691, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 2/3:  19%|█▊        | 741/4000 [07:08<31:44,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6444835662841797, Predicted Probability: 0.9337, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.615187644958496, Predicted Probability: 0.0013, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -4.755988121032715, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.91524076461792, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  19%|█▊        | 742/4000 [07:08<28:03,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.150398254394531, Predicted Probability: 0.9845, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.205050945281982, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  19%|█▊        | 743/4000 [07:09<25:31,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.648906230926514, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 3.9596734046936035, Predicted Probability: 0.9813, Prediction: 1.0

Epoch 2/3:  19%|█▊        | 744/4000 [07:09<30:25,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.959903717041016, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6085734367370605, Predicted Probability: 0.9314, Prediction: 1.0

Epoch 2/3:  19%|█▊        | 745/4000 [07:10<33:25,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8772659301757812, Predicted Probability: 0.9797, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.044661998748779, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  19%|█▊        | 746/4000 [07:10<26:41,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.623804569244385, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.837639808654785, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  19%|█▊        | 747/4000 [07:10<22:00,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.942070960998535, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3314194679260254, Predicted Probability: 0.0886, Prediction: 0.0

Epoch 2/3:  19%|█▊        | 748/4000 [07:11<28:51,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4389724731445312, Predicted Probability: 0.9198, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.017829895019531, Predicted Probability: 0.0066, Prediction: 0.0

Epoch 2/3:  19%|█▊        | 749/4000 [07:12<26:03,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5309810638427734, Predicted Probability: 0.0284, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.452175140380859, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 750/4000 [07:12<26:59,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.616588592529297, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6497621536254883, Predicted Probability: 0.9747, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 751/4000 [07:13<24:57,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.22733211517334, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8958888053894043, Predicted Probability: 0.1306, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 752/4000 [07:13<24:59,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.997838497161865, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.433818340301514, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 753/4000 [07:14<26:11,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.1453118324279785, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8472001552581787, Predicted Probability: 0.9452, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 754/4000 [07:14<31:02,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.60422420501709, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3234853446483612, Predicted Probability: 0.5802, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 755/4000 [07:15<30:41,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.273595333099365, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.346433162689209, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 756/4000 [07:16<33:33,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.114283084869385, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5369002223014832, Predicted Probability: 0.6311, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 757/4000 [07:16<32:25,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.602771282196045, Predicted Probability: 0.0099, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.9856696128845215, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 758/4000 [07:17<35:57,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.226469039916992, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.110235691070557, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 759/4000 [07:18<37:22,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.074215888977051, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7904574871063232, Predicted Probability: 0.1430, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 760/4000 [07:18<32:09,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.754861354827881, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8226120471954346, Predicted Probability: 0.9786, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 761/4000 [07:19<34:14,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.718631267547607, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4019339084625244, Predicted Probability: 0.9170, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 762/4000 [07:19<27:27,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6337884664535522, Predicted Probability: 0.8367, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.027430534362793, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 763/4000 [07:20<30:52,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.659368515014648, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.112605094909668, Predicted Probability: 0.8921, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 764/4000 [07:20<24:54,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.210331916809082, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.604560613632202, Predicted Probability: 0.9312, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 765/4000 [07:21<29:44,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.168920516967773, Predicted Probability: 0.0152, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4211716651916504, Predicted Probability: 0.0316, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 766/4000 [07:22<33:26,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.06209135055542, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7483469247817993, Predicted Probability: 0.8517, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 767/4000 [07:22<35:51,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9318366050720215, Predicted Probability: 0.0506, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.882249355316162, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 768/4000 [07:23<28:35,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.154078483581543, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.164949893951416, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 769/4000 [07:23<31:48,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.981677055358887, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.121913433074951, Predicted Probability: 0.8930, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 770/4000 [07:24<35:13,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.683903217315674, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4786252975463867, Predicted Probability: 0.9226, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 771/4000 [07:25<37:40,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.8276519775390625, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.803800582885742, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 772/4000 [07:26<39:41,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.781919479370117, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.928348541259766, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 773/4000 [07:26<39:41,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.847604274749756, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.12057527899742126, Predicted Probability: 0.5301, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 774/4000 [07:27<36:26,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1702170372009277, Predicted Probability: 0.7632, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0069940090179443, Predicted Probability: 0.9529, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 775/4000 [07:28<37:22,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.758232116699219, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3559978008270264, Predicted Probability: 0.9134, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 776/4000 [07:28<36:09,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.030667781829834, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3423137664794922, Predicted Probability: 0.2071, Prediction: 0.0

Epoch 2/3:  19%|█▉        | 777/4000 [07:29<38:26,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0687031745910645, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.470294952392578, Predicted Probability: 0.9220, Prediction: 1.0

Epoch 2/3:  19%|█▉        | 779/4000 [07:30<26:19,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6586573123931885, Predicted Probability: 0.6590, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.470292568206787, Predicted Probability: 0.9958, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.066027641296387, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.539843559265137, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 780/4000 [07:30<24:15,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.304742336273193, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.499472141265869, Predicted Probability: 0.0110, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 781/4000 [07:30<22:52,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.590217590332031, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1300857067108154, Predicted Probability: 0.0419, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 782/4000 [07:31<19:17,  2.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.035314559936523, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.113088607788086, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 783/4000 [07:31<19:21,  2.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.204763174057007, Predicted Probability: 0.0390, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.632896423339844, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 784/4000 [07:31<19:32,  2.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.293198585510254, Predicted Probability: 0.0135, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.756747722625732, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 786/4000 [07:32<21:08,  2.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.5081939697265625, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.023213326930999756, Predicted Probability: 0.4942, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.644440174102783, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.696066379547119, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 787/4000 [07:33<20:52,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7289299964904785, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.06015259772539139, Predicted Probability: 0.5150, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 788/4000 [07:33<26:43,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.366339683532715, Predicted Probability: 0.9142, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.564056873321533, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 789/4000 [07:34<30:25,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.424710273742676, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.125555992126465, Predicted Probability: 0.8934, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 790/4000 [07:35<30:09,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.671351909637451, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.442305088043213, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 791/4000 [07:35<24:21,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.147159099578857, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.460114479064941, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 792/4000 [07:36<29:28,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.369580268859863, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.578865051269531, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 793/4000 [07:36<26:43,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.298032522201538, Predicted Probability: 0.0356, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.289583683013916, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 794/4000 [07:36<24:55,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.474298477172852, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.818014621734619, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  20%|█▉        | 795/4000 [07:37<23:18,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.461029052734375, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.141751289367676, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 796/4000 [07:38<27:45,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.458784580230713, Predicted Probability: 0.1887, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.791771411895752, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 797/4000 [07:38<32:58,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.240963935852051, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.739526748657227, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 798/4000 [07:39<37:37,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.48598051071167, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.395541191101074, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  20%|█▉        | 799/4000 [07:40<34:59,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.540377140045166, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3470828533172607, Predicted Probability: 0.9660, Prediction: 1.0

Epoch 2/3:  20%|██        | 800/4000 [07:41<36:33,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1881308555603027, Predicted Probability: 0.8992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.2309160232543945, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  20%|██        | 801/4000 [07:41<37:51,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.15535831451416, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.36021089553833, Predicted Probability: 0.7958, Prediction: 1.0

Epoch 2/3:  20%|██        | 802/4000 [07:42<36:20,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.301682233810425, Predicted Probability: 0.9645, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.905598163604736, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  20%|██        | 803/4000 [07:43<36:50,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.579421520233154, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6701102256774902, Predicted Probability: 0.9352, Prediction: 1.0

Epoch 2/3:  20%|██        | 804/4000 [07:43<37:38,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.313825607299805, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7869627475738525, Predicted Probability: 0.9778, Prediction: 1.0

Epoch 2/3:  20%|██        | 805/4000 [07:44<38:50,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5294697284698486, Predicted Probability: 0.8219, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.00888729095459, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  20%|██        | 806/4000 [07:45<39:07,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.420131683349609, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.237795829772949, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  20%|██        | 807/4000 [07:46<40:07,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.276182174682617, Predicted Probability: 0.0931, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9342641830444336, Predicted Probability: 0.9808, Prediction: 1.0

Epoch 2/3:  20%|██        | 808/4000 [07:47<40:30,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.564098834991455, Predicted Probability: 0.1731, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.657570481300354, Predicted Probability: 0.3413, Prediction: 0.0

Epoch 2/3:  20%|██        | 809/4000 [07:47<40:59,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.699864387512207, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.202418327331543, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 2/3:  20%|██        | 810/4000 [07:48<36:02,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.229699611663818, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.704187870025635, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  20%|██        | 811/4000 [07:48<33:52,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2674193382263184, Predicted Probability: 0.9633, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.285249710083008, Predicted Probability: 0.0924, Prediction: 0.0

Epoch 2/3:  20%|██        | 812/4000 [07:49<27:02,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.232243537902832, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.972777366638184, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  20%|██        | 813/4000 [07:49<27:39,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.172121524810791, Predicted Probability: 0.0152, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.642554521560669, Predicted Probability: 0.9745, Prediction: 1.0

Epoch 2/3:  20%|██        | 814/4000 [07:50<25:34,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.7942047119140625, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5634071826934814, Predicted Probability: 0.0276, Prediction: 0.0

Epoch 2/3:  20%|██        | 815/4000 [07:50<21:11,  2.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.439544200897217, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7192206382751465, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  20%|██        | 816/4000 [07:50<27:01,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3136444091796875, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.195949077606201, Predicted Probability: 0.9852, Prediction: 1.0

Epoch 2/3:  20%|██        | 817/4000 [07:51<25:00,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.661694526672363, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.875189781188965, Predicted Probability: 0.9797, Prediction: 1.0

Epoch 2/3:  20%|██        | 818/4000 [07:52<29:06,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.981768608093262, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2287639379501343, Predicted Probability: 0.2264, Prediction: 0.0

Epoch 2/3:  20%|██        | 819/4000 [07:52<26:23,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.533066272735596, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.197664737701416, Predicted Probability: 0.1000, Prediction: 0.0

Epoch 2/3:  20%|██        | 820/4000 [07:52<24:30,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.388881206512451, Predicted Probability: 0.9877, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.024921417236328, Predicted Probability: 0.0176, Prediction: 0.0

Epoch 2/3:  21%|██        | 821/4000 [07:53<25:49,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.520522594451904, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0455597639083862, Predicted Probability: 0.2601, Prediction: 0.0

Epoch 2/3:  21%|██        | 822/4000 [07:54<29:31,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.167768955230713, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8113596439361572, Predicted Probability: 0.9433, Prediction: 1.0

Epoch 2/3:  21%|██        | 823/4000 [07:54<26:53,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.468069076538086, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4408986568450928, Predicted Probability: 0.0801, Prediction: 0.0

Epoch 2/3:  21%|██        | 824/4000 [07:55<30:51,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8558189868927, Predicted Probability: 0.9456, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9666218757629395, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  21%|██        | 825/4000 [07:56<33:46,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.662130355834961, Predicted Probability: 0.0652, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.339212417602539, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 2/3:  21%|██        | 826/4000 [07:56<35:24,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.244030952453613, Predicted Probability: 0.0141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7078354358673096, Predicted Probability: 0.8466, Prediction: 1.0

Epoch 2/3:  21%|██        | 827/4000 [07:57<37:22,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.603367805480957, Predicted Probability: 0.9311, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.620481491088867, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  21%|██        | 828/4000 [07:58<39:51,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.009215354919434, Predicted Probability: 0.0066, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.807257652282715, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 2/3:  21%|██        | 829/4000 [07:58<33:42,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.941225528717041, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.694590091705322, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  21%|██        | 830/4000 [07:59<36:15,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.035880088806152, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.918641090393066, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  21%|██        | 831/4000 [08:00<37:46,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.903186798095703, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.166827201843262, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  21%|██        | 832/4000 [08:01<37:53,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4430975914001465, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5262491703033447, Predicted Probability: 0.9260, Prediction: 1.0

Epoch 2/3:  21%|██        | 833/4000 [08:01<38:13,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4739291667938232, Predicted Probability: 0.0777, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.330572605133057, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 2/3:  21%|██        | 834/4000 [08:02<31:06,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.6174187660217285, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.901454448699951, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  21%|██        | 835/4000 [08:02<33:07,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5505361557006836, Predicted Probability: 0.9276, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.642361640930176, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  21%|██        | 836/4000 [08:03<31:55,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.327396869659424, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.388752460479736, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 2/3:  21%|██        | 837/4000 [08:04<35:38,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.716635704040527, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.044607639312744, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  21%|██        | 838/4000 [08:04<36:30,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.905479907989502, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.252547264099121, Predicted Probability: 0.9049, Prediction: 1.0

Epoch 2/3:  21%|██        | 839/4000 [08:05<38:00,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0818202495574951, Predicted Probability: 0.7468, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6242170333862305, Predicted Probability: 0.1646, Prediction: 0.0

Epoch 2/3:  21%|██        | 840/4000 [08:06<32:35,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8193602561950684, Predicted Probability: 0.0215, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.208556175231934, Predicted Probability: 0.9854, Prediction: 1.0

Epoch 2/3:  21%|██        | 841/4000 [08:06<35:42,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.494745254516602, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.487765312194824, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  21%|██        | 842/4000 [08:07<30:47,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6343207359313965, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.629103183746338, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  21%|██        | 843/4000 [08:07<27:27,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.978007793426514, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.366308689117432, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:  21%|██        | 844/4000 [08:08<32:47,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.455244541168213, Predicted Probability: 0.9209, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.113527297973633, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  21%|██        | 845/4000 [08:09<34:43,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.327782154083252, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3808469772338867, Predicted Probability: 0.0846, Prediction: 0.0

Epoch 2/3:  21%|██        | 847/4000 [08:10<26:09,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7018914222717285, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.978555202484131, Predicted Probability: 0.9991, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.883616924285889, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 3.185532331466675, Predicted Probability: 0.9603, Prediction: 1.0

Epoch 2/3:  21%|██        | 848/4000 [08:10<24:04,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.941780090332031, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.529211521148682, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  21%|██        | 849/4000 [08:11<30:27,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.788832664489746, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.439032554626465, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 850/4000 [08:12<32:44,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6227824687957764, Predicted Probability: 0.9323, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.2218146324157715, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 851/4000 [08:12<34:59,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.401217460632324, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.631269693374634, Predicted Probability: 0.9742, Prediction: 1.0

Epoch 2/3:  21%|██▏       | 852/4000 [08:13<36:21,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.966432094573975, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0681967735290527, Predicted Probability: 0.2557, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 853/4000 [08:13<31:05,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.941403388977051, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.100160598754883, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  21%|██▏       | 854/4000 [08:14<33:38,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.741816520690918, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.60712194442749, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 855/4000 [08:15<29:41,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.063129901885986, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.26561164855957, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  21%|██▏       | 856/4000 [08:15<24:01,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.141263961791992, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.539765357971191, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 857/4000 [08:15<28:29,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.1328444480896, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.340240001678467, Predicted Probability: 0.0878, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 858/4000 [08:16<32:49,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.281835079193115, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8569055795669556, Predicted Probability: 0.2980, Prediction: 0.0

Epoch 2/3:  21%|██▏       | 859/4000 [08:17<31:31,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.203985214233398, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6283297538757324, Predicted Probability: 0.9327, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 860/4000 [08:17<30:24,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.047436714172363, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9821696281433105, Predicted Probability: 0.9518, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 861/4000 [08:18<24:35,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.17630645632743835, Predicted Probability: 0.5440, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.17397689819336, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 862/4000 [08:18<30:19,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.168190002441406, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.558992385864258, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 863/4000 [08:19<27:07,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6836847066879272, Predicted Probability: 0.3354, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.61929988861084, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 864/4000 [08:19<24:56,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.798964500427246, Predicted Probability: 0.9918, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.418920993804932, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 865/4000 [08:20<29:18,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9039788246154785, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8800702095031738, Predicted Probability: 0.2932, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 866/4000 [08:21<32:18,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.097779273986816, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8366565704345703, Predicted Probability: 0.0554, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 867/4000 [08:21<25:52,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7603020668029785, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.047019958496094, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 868/4000 [08:21<21:18,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.383077144622803, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.217299461364746, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 869/4000 [08:22<26:41,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.252290725708008, Predicted Probability: 0.0372, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6594719886779785, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 870/4000 [08:23<30:05,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8251707553863525, Predicted Probability: 0.0560, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8895583152771, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 871/4000 [08:23<24:14,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.170631408691406, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.720808029174805, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 872/4000 [08:24<28:59,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.230772018432617, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.224552154541016, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 873/4000 [08:24<31:55,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3613178730010986, Predicted Probability: 0.7960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.036681175231934, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 874/4000 [08:25<34:03,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.569597005844116, Predicted Probability: 0.9289, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.100588798522949, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 875/4000 [08:26<36:05,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.855271816253662, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2610747814178467, Predicted Probability: 0.9056, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 876/4000 [08:27<37:04,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.596895217895508, Predicted Probability: 0.0267, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.641974449157715, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 877/4000 [08:27<34:24,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6735845804214478, Predicted Probability: 0.1579, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.783401012420654, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 878/4000 [08:28<29:49,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.54827880859375, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.699041843414307, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 879/4000 [08:28<32:45,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0840827226638794, Predicted Probability: 0.2527, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.692015647888184, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 880/4000 [08:29<34:38,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.524111270904541, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8310760259628296, Predicted Probability: 0.8619, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 881/4000 [08:30<36:14,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.983205795288086, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5790176391601562, Predicted Probability: 0.9295, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 882/4000 [08:31<37:12,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.745081901550293, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6896307468414307, Predicted Probability: 0.3341, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 883/4000 [08:31<31:48,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.635005950927734, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.539194107055664, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 884/4000 [08:32<33:53,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4305243492126465, Predicted Probability: 0.0809, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.997753620147705, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 885/4000 [08:32<36:00,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.044791221618652, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.69170880317688, Predicted Probability: 0.9365, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 886/4000 [08:33<31:05,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0753655433654785, Predicted Probability: 0.0441, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.916976451873779, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 887/4000 [08:34<34:10,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.113283157348633, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.078878402709961, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 888/4000 [08:34<35:44,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.76147723197937, Predicted Probability: 0.9406, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.683691024780273, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 889/4000 [08:35<31:07,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.255712032318115, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.203413963317871, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 890/4000 [08:36<35:12,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.669719696044922, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9988908767700195, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 891/4000 [08:36<30:15,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.437163829803467, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.024643898010254, Predicted Probability: 0.1166, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 892/4000 [08:36<26:59,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.846865177154541, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.785033226013184, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 893/4000 [08:37<24:58,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.07436752319336, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.826803684234619, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 894/4000 [08:37<23:02,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.375055313110352, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.202669143676758, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 895/4000 [08:38<22:02,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.849754810333252, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.119924068450928, Predicted Probability: 0.9840, Prediction: 1.0

Epoch 2/3:  22%|██▏       | 896/4000 [08:38<27:57,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.572676658630371, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.5634074211120605, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 897/4000 [08:39<31:39,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5972845554351807, Predicted Probability: 0.9733, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.697617530822754, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 898/4000 [08:40<33:28,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5949769020080566, Predicted Probability: 0.9305, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.495577335357666, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  22%|██▏       | 899/4000 [08:41<34:19,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.634858131408691, Predicted Probability: 0.0096, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.051830530166626, Predicted Probability: 0.7411, Prediction: 1.0

Epoch 2/3:  22%|██▎       | 900/4000 [08:41<28:12,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.760266304016113, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.403861045837402, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 901/4000 [08:41<25:30,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.564225673675537, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.300175666809082, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 902/4000 [08:41<21:59,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.1695427894592285, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.114419937133789, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 903/4000 [08:42<28:03,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.013554573059082, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.662456035614014, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 904/4000 [08:43<30:57,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4276418685913086, Predicted Probability: 0.0314, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1912641525268555, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 905/4000 [08:44<34:06,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2436399459838867, Predicted Probability: 0.2238, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.278693199157715, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 907/4000 [08:44<23:45,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.10456657409668, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.633554935455322, Predicted Probability: 0.0013, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -5.583054065704346, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.999557018280029, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 908/4000 [08:45<28:06,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4703633785247803, Predicted Probability: 0.0780, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.393572807312012, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 909/4000 [08:45<23:48,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.981739044189453, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.28264045715332, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 910/4000 [08:46<29:41,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.082667827606201, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.966581344604492, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 912/4000 [08:47<19:50,  2.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7258472442626953, Predicted Probability: 0.9765, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.321062088012695, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.785541534423828, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.301822662353516, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 913/4000 [08:47<18:01,  2.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.528438568115234, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.740006446838379, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 914/4000 [08:47<18:41,  2.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.271674633026123, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0401153564453125, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 915/4000 [08:48<18:43,  2.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.341361999511719, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.085093975067139, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 916/4000 [08:48<24:59,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.453315734863281, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.166701793670654, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 917/4000 [08:49<23:04,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.303718566894531, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.6717047691345215, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 918/4000 [08:49<21:52,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.867142677307129, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.346498489379883, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 919/4000 [08:50<26:47,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7627663612365723, Predicted Probability: 0.9406, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.537959098815918, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 920/4000 [08:51<29:46,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7277328372001648, Predicted Probability: 0.3257, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1212568283081055, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 921/4000 [08:51<33:00,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.613870620727539, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.048220634460449, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 922/4000 [08:52<26:15,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7902567982673645, Predicted Probability: 0.3121, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.881164073944092, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 923/4000 [08:52<21:36,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.744353294372559, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.872842788696289, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 924/4000 [08:53<26:20,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.831265926361084, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7983648777008057, Predicted Probability: 0.9781, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 925/4000 [08:53<26:47,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.108202934265137, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.64176082611084, Predicted Probability: 0.9745, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 926/4000 [08:53<22:49,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.044412136077881, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.282589435577393, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 927/4000 [08:54<21:40,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9782395362854, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8605151176452637, Predicted Probability: 0.9794, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 928/4000 [08:54<19:26,  2.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.123117923736572, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.395477294921875, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 929/4000 [08:55<24:56,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.572445392608643, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.122842788696289, Predicted Probability: 0.1069, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 930/4000 [08:55<20:33,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.429924964904785, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.924898147583008, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 931/4000 [08:55<19:56,  2.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.606262683868408, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.4664998054504395, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 932/4000 [08:56<17:16,  2.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.94088077545166, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.275645732879639, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 933/4000 [08:56<23:07,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3600580096244812, Predicted Probability: 0.5891, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.775588035583496, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 934/4000 [08:57<28:15,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.1463470458984375, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.707305908203125, Predicted Probability: 0.9760, Prediction: 1.0

Epoch 2/3:  23%|██▎       | 935/4000 [08:58<31:01,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0859532356262207, Predicted Probability: 0.2524, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.712647914886475, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 936/4000 [08:58<28:49,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.328993320465088, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.886428356170654, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 937/4000 [08:59<32:10,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.321179389953613, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.062999725341797, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 938/4000 [09:00<30:42,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9837849140167236, Predicted Probability: 0.9518, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.209709644317627, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  23%|██▎       | 939/4000 [09:00<32:51,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5187145471572876, Predicted Probability: 0.8203, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.037208557128906, Predicted Probability: 0.9827, Prediction: 1.0

Epoch 2/3:  24%|██▎       | 940/4000 [09:01<35:39,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.030830383300781, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.867981433868408, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  24%|██▎       | 941/4000 [09:02<33:36,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7679338455200195, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.487976551055908, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 2/3:  24%|██▎       | 942/4000 [09:02<34:56,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.639944076538086, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.894232749938965, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 2/3:  24%|██▎       | 943/4000 [09:03<36:48,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4042391777038574, Predicted Probability: 0.0322, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.607275009155273, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  24%|██▎       | 944/4000 [09:04<37:32,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.634474277496338, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.540822982788086, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  24%|██▎       | 945/4000 [09:04<29:22,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.052393913269043, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.845097005367279, Predicted Probability: 0.6995, Prediction: 1.0

Epoch 2/3:  24%|██▎       | 946/4000 [09:05<26:08,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.037120819091797, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.473981857299805, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  24%|██▎       | 947/4000 [09:05<24:10,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.024536609649658, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.705069065093994, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  24%|██▎       | 948/4000 [09:06<27:42,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5761101245880127, Predicted Probability: 0.1713, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.423216819763184, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  24%|██▎       | 949/4000 [09:06<30:58,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.477151393890381, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.647538185119629, Predicted Probability: 0.9339, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 950/4000 [09:07<27:20,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.4916181564331055, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.308051109313965, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 951/4000 [09:08<30:09,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1632468700408936, Predicted Probability: 0.8969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.165436744689941, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 952/4000 [09:08<24:14,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.976200580596924, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.827206611633301, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 953/4000 [09:09<29:38,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.399594306945801, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.771125316619873, Predicted Probability: 0.9775, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 954/4000 [09:09<26:17,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.154281616210938, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.215728282928467, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 955/4000 [09:10<30:06,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.141853332519531, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5306122303009033, Predicted Probability: 0.3704, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 956/4000 [09:10<32:29,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.642397403717041, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.333379745483398, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 957/4000 [09:11<29:35,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.057937145233154, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.030733108520508, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 958/4000 [09:11<26:20,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.003011703491211, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.361493110656738, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 959/4000 [09:12<24:04,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.487592697143555, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.372024059295654, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 960/4000 [09:12<28:09,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0230607986450195, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.822147369384766, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 961/4000 [09:13<25:24,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.882542133331299, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6797637939453125, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 962/4000 [09:14<29:05,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.755539894104004, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.888584852218628, Predicted Probability: 0.9799, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 963/4000 [09:14<31:56,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.60335636138916, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.061740875244141, Predicted Probability: 0.9831, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 964/4000 [09:15<30:31,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.155280828475952, Predicted Probability: 0.8962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.555526256561279, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 965/4000 [09:16<32:17,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0384966135025024, Predicted Probability: 0.2614, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6439738273620605, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 966/4000 [09:16<28:20,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.759256362915039, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4273087978363037, Predicted Probability: 0.0315, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 967/4000 [09:17<30:42,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5955400466918945, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6178388595581055, Predicted Probability: 0.9320, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 968/4000 [09:17<32:44,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.253262996673584, Predicted Probability: 0.0372, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.658173084259033, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 969/4000 [09:18<31:19,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9691972732543945, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.417993068695068, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 970/4000 [09:18<25:01,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.551112651824951, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.32982063293457, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 971/4000 [09:19<28:36,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.466428756713867, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.998736381530762, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 972/4000 [09:20<31:45,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.840460777282715, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.308860778808594, Predicted Probability: 0.9867, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 973/4000 [09:20<33:40,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.200605392456055, Predicted Probability: 0.9852, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.763754844665527, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 974/4000 [09:21<29:08,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5183539390563965, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.781060218811035, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 975/4000 [09:21<23:30,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.448293685913086, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4608889818191528, Predicted Probability: 0.8117, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 976/4000 [09:22<28:57,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.902517318725586, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.824150085449219, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 977/4000 [09:22<23:22,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.376346588134766, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.077371597290039, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  24%|██▍       | 978/4000 [09:22<22:51,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9788944721221924, Predicted Probability: 0.9516, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.058412075042725, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 979/4000 [09:23<21:26,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5954365730285645, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.349584102630615, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  24%|██▍       | 980/4000 [09:23<24:40,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.743085861206055, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.436219215393066, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 981/4000 [09:24<22:54,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.700921058654785, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.991184234619141, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 982/4000 [09:25<27:29,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2790045738220215, Predicted Probability: 0.0363, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.506364107131958, Predicted Probability: 0.0754, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 983/4000 [09:25<24:53,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.798889636993408, Predicted Probability: 0.9918, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1999778747558594, Predicted Probability: 0.9608, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 984/4000 [09:25<20:34,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.687317848205566, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.53834342956543, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 985/4000 [09:25<17:38,  2.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.683956623077393, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.274008750915527, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 986/4000 [09:26<23:46,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8374342918395996, Predicted Probability: 0.9789, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.689281463623047, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 987/4000 [09:27<28:50,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.380582809448242, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5860774517059326, Predicted Probability: 0.0700, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 988/4000 [09:27<28:37,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.627865791320801, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.791528224945068, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 989/4000 [09:28<25:45,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4605512619018555, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.155834197998047, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 990/4000 [09:29<29:51,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.643683433532715, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.656581401824951, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 991/4000 [09:29<32:00,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.907440185546875, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7293176651000977, Predicted Probability: 0.9387, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 992/4000 [09:30<35:13,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.58397912979126, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.067450523376465, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 993/4000 [09:31<32:48,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.093185424804688, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.191631317138672, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 994/4000 [09:31<28:22,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.187526226043701, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.012439727783203, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 995/4000 [09:32<31:26,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6497201919555664, Predicted Probability: 0.9340, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9329516887664795, Predicted Probability: 0.0505, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 996/4000 [09:32<27:29,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4905979633331299, Predicted Probability: 0.1838, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.332736015319824, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 997/4000 [09:33<27:38,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.326226711273193, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.341075897216797, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  25%|██▍       | 998/4000 [09:34<30:14,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.629988431930542, Predicted Probability: 0.9328, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.523087024688721, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 2/3:  25%|██▍       | 999/4000 [09:34<32:12,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.500082969665527, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0848398208618164, Predicted Probability: 0.2526, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1000/4000 [09:35<33:25,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.694921970367432, Predicted Probability: 0.9909, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.937429904937744, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1001/4000 [09:36<35:30,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.344874858856201, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.762020111083984, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1002/4000 [09:36<30:43,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.859893798828125, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.994041442871094, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1003/4000 [09:37<32:53,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.092675685882568, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5663039684295654, Predicted Probability: 0.9287, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1004/4000 [09:38<34:36,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.44745397567749, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.739274978637695, Predicted Probability: 0.9913, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1005/4000 [09:39<35:24,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6700639724731445, Predicted Probability: 0.9352, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.004723072052002, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1006/4000 [09:39<36:38,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9940266609191895, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.536250114440918, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1007/4000 [09:40<37:20,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.371617317199707, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.859920501708984, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1008/4000 [09:41<39:41,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.70833683013916, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.4451093673706055, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1009/4000 [09:41<31:47,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.007086753845215, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.354276657104492, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1010/4000 [09:42<28:01,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.806642532348633, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.848688125610352, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1011/4000 [09:42<25:16,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5637571811676025, Predicted Probability: 0.9724, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.081212520599365, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1012/4000 [09:43<29:22,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1828529834747314, Predicted Probability: 0.8987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.387551307678223, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1013/4000 [09:43<28:44,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.82410192489624, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.22300483286380768, Predicted Probability: 0.5555, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1014/4000 [09:44<31:14,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.289760112762451, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.800161838531494, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 2/3:  25%|██▌       | 1015/4000 [09:45<32:25,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.672374725341797, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1176717281341553, Predicted Probability: 0.9576, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1016/4000 [09:45<25:49,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.646623611450195, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.9872846603393555, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1017/4000 [09:46<29:02,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4803876876831055, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5153021812438965, Predicted Probability: 0.9252, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1018/4000 [09:46<25:53,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.03562068939209, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.972482204437256, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  25%|██▌       | 1019/4000 [09:47<28:34,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.885894298553467, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4099650382995605, Predicted Probability: 0.9176, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1020/4000 [09:48<31:34,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9476391077041626, Predicted Probability: 0.2794, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.632667541503906, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1021/4000 [09:48<25:16,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.593443870544434, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.072294235229492, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1022/4000 [09:48<23:09,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.020862579345703, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8140339851379395, Predicted Probability: 0.0566, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1023/4000 [09:49<21:54,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.532453536987305, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.663369178771973, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1024/4000 [09:49<21:00,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.888876438140869, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4193596839904785, Predicted Probability: 0.9881, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1025/4000 [09:50<22:50,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.600447177886963, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2326765060424805, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1026/4000 [09:50<26:52,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7189459800720215, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0769848823547363, Predicted Probability: 0.7459, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1027/4000 [09:51<29:43,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5533623695373535, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.606942892074585, Predicted Probability: 0.8330, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1028/4000 [09:51<23:51,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.107236862182617, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.767335891723633, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1029/4000 [09:52<27:20,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.550288200378418, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8364610075950623, Predicted Probability: 0.3023, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1030/4000 [09:52<24:44,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.199611186981201, Predicted Probability: 0.0148, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.951938629150391, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1031/4000 [09:53<22:52,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9705193042755127, Predicted Probability: 0.1223, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.027175903320312, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1032/4000 [09:53<19:05,  2.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.421479225158691, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.368419647216797, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1033/4000 [09:53<16:25,  3.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.480041980743408, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.666522026062012, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1034/4000 [09:54<22:59,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.958049774169922, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.673774242401123, Predicted Probability: 0.9355, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1035/4000 [09:57<1:01:16,  1.24s/it]

Data point 1: Actual Class: 0.0, Final Logit: -1.032097339630127, Predicted Probability: 0.2627, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.485553741455078, Predicted Probability: 0.0111, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1036/4000 [09:57<48:35,  1.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.86470365524292, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.638071060180664, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1037/4000 [09:58<45:23,  1.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.798729181289673, Predicted Probability: 0.0574, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.937648057937622, Predicted Probability: 0.1259, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1038/4000 [09:59<43:03,  1.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.646742820739746, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.176144599914551, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1039/4000 [09:59<34:04,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.848746299743652, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.265212059020996, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1040/4000 [10:00<34:39,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7213003635406494, Predicted Probability: 0.9383, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.287123680114746, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1041/4000 [10:00<29:48,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.341951370239258, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.960976600646973, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1042/4000 [10:01<31:48,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.41805797815322876, Predicted Probability: 0.3970, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.401249885559082, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1043/4000 [10:01<27:58,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.69730281829834, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.667954444885254, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1044/4000 [10:02<30:48,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.195533752441406, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4687585830688477, Predicted Probability: 0.9219, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1045/4000 [10:03<33:52,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.868919372558594, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.467538356781006, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1046/4000 [10:04<34:58,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.754017353057861, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9776809215545654, Predicted Probability: 0.0484, Prediction: 0.0

Epoch 2/3:  26%|██▌       | 1047/4000 [10:04<30:08,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.821577310562134, Predicted Probability: 0.0562, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.064190864562988, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1048/4000 [10:05<31:52,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.492060661315918, Predicted Probability: 0.9889, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.396807670593262, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 2/3:  26%|██▌       | 1049/4000 [10:06<33:27,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.731646537780762, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7588998079299927, Predicted Probability: 0.3189, Prediction: 0.0

Epoch 2/3:  26%|██▋       | 1050/4000 [10:06<34:54,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.968328475952148, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.363245964050293, Predicted Probability: 0.9140, Prediction: 1.0

Epoch 2/3:  26%|██▋       | 1051/4000 [10:07<36:46,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.112634658813477, Predicted Probability: 0.0161, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.299099922180176, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  26%|██▋       | 1052/4000 [10:07<28:46,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.755770683288574, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.792223930358887, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  26%|██▋       | 1053/4000 [10:08<29:24,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5364797115325928, Predicted Probability: 0.9267, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9609527587890625, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  26%|██▋       | 1054/4000 [10:09<31:17,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.712759971618652, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0071592330932617, Predicted Probability: 0.8815, Prediction: 1.0

Epoch 2/3:  26%|██▋       | 1055/4000 [10:09<32:42,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.263123035430908, Predicted Probability: 0.0369, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.572782516479492, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  26%|██▋       | 1056/4000 [10:10<33:55,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5955207347869873, Predicted Probability: 0.9306, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.239904403686523, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  26%|██▋       | 1057/4000 [10:11<34:27,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2944493293762207, Predicted Probability: 0.9084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.892672538757324, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  26%|██▋       | 1058/4000 [10:11<29:32,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.054664134979248, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.10456371307373, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  26%|██▋       | 1060/4000 [10:12<25:42,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.70767879486084, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.063624382019043, Predicted Probability: 0.0003, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.50570011138916, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.245660781860352, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1061/4000 [10:13<20:51,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.654553413391113, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.568771362304688, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1062/4000 [10:13<25:20,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4157769680023193, Predicted Probability: 0.9180, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9944844245910645, Predicted Probability: 0.0181, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1063/4000 [10:14<25:59,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.41120341420173645, Predicted Probability: 0.3986, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4295432567596436, Predicted Probability: 0.9686, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1064/4000 [10:15<29:36,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0175371170043945, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4980647563934326, Predicted Probability: 0.9706, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1065/4000 [10:15<23:41,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.005001068115234, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.505963325500488, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1066/4000 [10:16<27:15,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.577449321746826, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.305255889892578, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1067/4000 [10:16<30:28,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.7523980140686035, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3899712562561035, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1068/4000 [10:16<24:28,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.139410972595215, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.233553886413574, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1070/4000 [10:17<18:30,  2.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.59314489364624, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.129993438720703, Predicted Probability: 0.9997, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.457579612731934, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.116374969482422, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1071/4000 [10:18<23:50,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.167979717254639, Predicted Probability: 0.9848, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.794682502746582, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1072/4000 [10:18<20:38,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.7847795486450195, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.084052085876465, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1074/4000 [10:19<21:13,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.690678119659424, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.255037784576416, Predicted Probability: 0.0007, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: -0.12510032951831818, Predicted Probability: 0.4688, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.675846099853516, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1075/4000 [10:20<26:35,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.193498611450195, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8827300667762756, Predicted Probability: 0.2926, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1076/4000 [10:21<29:41,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.521483898162842, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3972028493881226, Predicted Probability: 0.1983, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1077/4000 [10:21<26:15,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.812392234802246, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6770731210708618, Predicted Probability: 0.6631, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1078/4000 [10:21<23:49,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.873776435852051, Predicted Probability: 0.0076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3044776916503906, Predicted Probability: 0.0354, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1079/4000 [10:22<21:57,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.429113388061523, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.607601165771484, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1080/4000 [10:22<25:47,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2348790168762207, Predicted Probability: 0.9033, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7386016845703125, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1081/4000 [10:23<30:26,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.431090354919434, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.321776866912842, Predicted Probability: 0.0348, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1082/4000 [10:24<32:00,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.578174352645874, Predicted Probability: 0.9294, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.619381427764893, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1083/4000 [10:24<25:21,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.0927095413208, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0008301734924316, Predicted Probability: 0.0474, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1084/4000 [10:25<29:07,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.242647171020508, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.44166898727417, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1085/4000 [10:25<23:19,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3736572265625, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9063677787780762, Predicted Probability: 0.1294, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1086/4000 [10:26<24:07,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.660576820373535, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.919114112854004, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1087/4000 [10:26<22:18,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.859104156494141, Predicted Probability: 0.9923, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.217941284179688, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1088/4000 [10:26<20:52,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.447065830230713, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.767264366149902, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1089/4000 [10:27<21:04,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.438569068908691, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.25070473551750183, Predicted Probability: 0.5623, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1090/4000 [10:28<25:47,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.392655849456787, Predicted Probability: 0.9163, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.719623565673828, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1091/4000 [10:28<23:39,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8182458877563477, Predicted Probability: 0.0563, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.872452735900879, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1092/4000 [10:28<22:01,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.704092979431152, Predicted Probability: 0.9910, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.950541019439697, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1093/4000 [10:29<27:27,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6262104511260986, Predicted Probability: 0.0259, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.196193695068359, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 2/3:  27%|██▋       | 1094/4000 [10:30<29:33,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3652191162109375, Predicted Probability: 0.9874, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.002121925354004, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1095/4000 [10:30<23:44,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.10019302368164, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.175325393676758, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1096/4000 [10:31<22:01,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4561843872070312, Predicted Probability: 0.1891, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.434537887573242, Predicted Probability: 0.9883, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1097/4000 [10:31<21:06,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.850605010986328, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.906644821166992, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1098/4000 [10:32<25:40,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.398452281951904, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.614427089691162, Predicted Probability: 0.9318, Prediction: 1.0

Epoch 2/3:  27%|██▋       | 1099/4000 [10:33<29:19,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.937810897827148, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5913772583007812, Predicted Probability: 0.9303, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1100/4000 [10:33<28:24,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.834475040435791, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.174393177032471, Predicted Probability: 0.9848, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1101/4000 [10:34<30:47,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.406336784362793, Predicted Probability: 0.9679, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.920087814331055, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1103/4000 [10:35<25:17,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4403088092803955, Predicted Probability: 0.9198, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6272807121276855, Predicted Probability: 0.0005, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.563276290893555, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.73904275894165, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1104/4000 [10:36<29:05,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.296968460083008, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8176774978637695, Predicted Probability: 0.9785, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1105/4000 [10:36<26:00,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.260559558868408, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.754108428955078, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1106/4000 [10:36<21:12,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.454685688018799, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.2818603515625, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1107/4000 [10:36<20:14,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0336503982543945, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.020739555358887, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1108/4000 [10:37<17:10,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.070728302001953, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.77825927734375, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1109/4000 [10:37<18:42,  2.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.093623638153076, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.651421546936035, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1110/4000 [10:38<22:12,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.144777536392212, Predicted Probability: 0.1048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.135411262512207, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1111/4000 [10:39<27:06,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.675215721130371, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.612355709075928, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1112/4000 [10:39<22:01,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.862020969390869, Predicted Probability: 0.9794, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.502988815307617, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1113/4000 [10:39<18:19,  2.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.454107642173767, Predicted Probability: 0.8106, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.204026222229004, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1114/4000 [10:40<22:00,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.172632694244385, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.70977783203125, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1115/4000 [10:40<26:04,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.293074607849121, Predicted Probability: 0.9865, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.162104606628418, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1116/4000 [10:41<29:22,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31803977489471436, Predicted Probability: 0.4212, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.264404535293579, Predicted Probability: 0.9059, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1117/4000 [10:42<38:06,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.876471519470215, Predicted Probability: 0.0076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.247209548950195, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1118/4000 [10:43<34:25,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.419705629348755, Predicted Probability: 0.9683, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.8659281730651855, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1119/4000 [10:43<32:08,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.043405055999756, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.995514869689941, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1120/4000 [10:44<28:03,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.045614242553711, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.368889808654785, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1122/4000 [10:45<23:54,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.795576572418213, Predicted Probability: 0.9918, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.476476669311523, Predicted Probability: 0.0112, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.699603080749512, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.255624294281006, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1123/4000 [10:45<24:32,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9782345294952393, Predicted Probability: 0.0484, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6386237144470215, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1124/4000 [10:46<27:37,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2043023109436035, Predicted Probability: 0.9006, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.4761128425598145, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1125/4000 [10:47<30:02,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4276670217514038, Predicted Probability: 0.8065, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.407240867614746, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1126/4000 [10:47<23:59,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.746122360229492, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.965622901916504, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1128/4000 [10:48<18:19,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.267061233520508, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.670290946960449, Predicted Probability: 0.9966, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -5.789951801300049, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.764742612838745, Predicted Probability: 0.0593, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1129/4000 [10:48<18:17,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.553704261779785, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5394697189331055, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1130/4000 [10:49<24:38,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7069941759109497, Predicted Probability: 0.3303, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.330392837524414, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1131/4000 [10:50<28:21,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.56425666809082, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5421528816223145, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1132/4000 [10:50<26:16,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5981240272521973, Predicted Probability: 0.9307, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9388136863708496, Predicted Probability: 0.9809, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1133/4000 [10:51<28:48,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.369688987731934, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3792622089385986, Predicted Probability: 0.9152, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1135/4000 [10:51<22:23,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.274017333984375, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.747861385345459, Predicted Probability: 0.9914, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.759044647216797, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.255012035369873, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1136/4000 [10:52<26:24,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.204498767852783, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.145073175430298, Predicted Probability: 0.8952, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1137/4000 [10:53<23:49,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.348604202270508, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.324593544006348, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  28%|██▊       | 1138/4000 [10:53<27:30,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.319626331329346, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.587641716003418, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1139/4000 [10:54<29:59,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2501444816589355, Predicted Probability: 0.9859, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.487008571624756, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  28%|██▊       | 1140/4000 [10:54<26:29,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.320947647094727, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8962721824645996, Predicted Probability: 0.0199, Prediction: 0.0

Epoch 2/3:  29%|██▊       | 1141/4000 [10:55<24:11,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.436702728271484, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.557927131652832, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  29%|██▊       | 1142/4000 [10:55<22:13,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.801358699798584, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.319700717926025, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  29%|██▊       | 1143/4000 [10:56<25:54,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.60537576675415, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.337043762207031, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  29%|██▊       | 1144/4000 [10:56<23:32,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.205781936645508, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.188014030456543, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 2/3:  29%|██▊       | 1145/4000 [10:57<27:54,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.869076728820801, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.066605567932129, Predicted Probability: 0.8876, Prediction: 1.0

Epoch 2/3:  29%|██▊       | 1147/4000 [10:58<20:15,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.409002780914307, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.4815897941589355, Predicted Probability: 0.0006, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.115898609161377, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.844563007354736, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  29%|██▊       | 1148/4000 [10:58<20:25,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.16191291809082, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5054800510406494, Predicted Probability: 0.0292, Prediction: 0.0

Epoch 2/3:  29%|██▊       | 1149/4000 [10:59<19:44,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9967217445373535, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.273050308227539, Predicted Probability: 0.0137, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1150/4000 [10:59<19:01,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.737765789031982, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.873570442199707, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1151/4000 [11:00<23:14,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.349501132965088, Predicted Probability: 0.9129, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.350451946258545, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1152/4000 [11:00<21:38,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8298991918563843, Predicted Probability: 0.8617, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.57790470123291, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1153/4000 [11:00<20:28,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.46522045135498, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.651479959487915, Predicted Probability: 0.9341, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1154/4000 [11:01<19:51,  2.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.559149265289307, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.996763706207275, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1155/4000 [11:02<25:05,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.878493309020996, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7522724866867065, Predicted Probability: 0.1478, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1156/4000 [11:02<23:48,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.700222969055176, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.520384311676025, Predicted Probability: 0.9892, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1157/4000 [11:02<21:43,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.43920373916626, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.256228923797607, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1158/4000 [11:03<25:58,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.5462751388549805, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.171195983886719, Predicted Probability: 0.9848, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1159/4000 [11:03<23:52,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.899557590484619, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.399538993835449, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1160/4000 [11:04<27:25,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.641439437866211, Predicted Probability: 0.1623, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.470074653625488, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1161/4000 [11:05<29:41,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.385687828063965, Predicted Probability: 0.9877, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.656245231628418, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1162/4000 [11:06<28:27,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.3682360649108887, Predicted Probability: 0.9144, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8575313091278076, Predicted Probability: 0.8650, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1163/4000 [11:06<22:55,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.670626163482666, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.336328029632568, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1164/4000 [11:06<22:24,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.3705878257751465, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.510718822479248, Predicted Probability: 0.0290, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1165/4000 [11:07<21:13,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.048449516296387, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.052247524261475, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1166/4000 [11:07<18:36,  2.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.802382946014404, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.779179096221924, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1167/4000 [11:07<19:16,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.109926462173462, Predicted Probability: 0.9573, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6528913974761963, Predicted Probability: 0.9342, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1168/4000 [11:08<19:37,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.652388334274292, Predicted Probability: 0.0253, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.041186332702637, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1169/4000 [11:09<25:14,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.108244895935059, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9502716064453125, Predicted Probability: 0.9811, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1170/4000 [11:09<29:04,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.13492202758789, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.612117767333984, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1171/4000 [11:10<30:39,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.629966735839844, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8573585748672485, Predicted Probability: 0.7021, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1172/4000 [11:10<27:00,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.749300479888916, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7835841178894043, Predicted Probability: 0.9418, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1173/4000 [11:11<29:22,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7595683336257935, Predicted Probability: 0.1468, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.997278690338135, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1174/4000 [11:11<23:30,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1106433868408203, Predicted Probability: 0.7522, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.205011367797852, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1175/4000 [11:12<21:51,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.615036964416504, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.59851336479187, Predicted Probability: 0.9308, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1176/4000 [11:12<18:11,  2.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6339898109436035, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.09611143171787262, Predicted Probability: 0.4760, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1177/4000 [11:12<18:01,  2.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8514485359191895, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.383469581604004, Predicted Probability: 0.7995, Prediction: 1.0

Epoch 2/3:  29%|██▉       | 1178/4000 [11:13<22:45,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.318117618560791, Predicted Probability: 0.0350, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.203819751739502, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  29%|██▉       | 1179/4000 [11:14<24:09,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8372695446014404, Predicted Probability: 0.9789, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8716721534729004, Predicted Probability: 0.9796, Prediction: 1.0

Epoch 2/3:  30%|██▉       | 1180/4000 [11:14<27:09,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5222907066345215, Predicted Probability: 0.8209, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.993020057678223, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1181/4000 [11:15<29:15,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0369994640350342, Predicted Probability: 0.2617, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.006608963012695, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1182/4000 [11:16<25:57,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.02139949798584, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.843689441680908, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1183/4000 [11:16<28:36,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.888916015625, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9503333568573, Predicted Probability: 0.9811, Prediction: 1.0

Epoch 2/3:  30%|██▉       | 1184/4000 [11:17<25:17,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4685916900634766, Predicted Probability: 0.0781, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.587856292724609, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  30%|██▉       | 1185/4000 [11:17<27:50,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1194941997528076, Predicted Probability: 0.8928, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.099749565124512, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1186/4000 [11:18<23:16,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8370388746261597, Predicted Probability: 0.6978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.642265796661377, Predicted Probability: 0.9905, Prediction: 1.0

Epoch 2/3:  30%|██▉       | 1187/4000 [11:18<27:31,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.043004512786865, Predicted Probability: 0.9828, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.522950649261475, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1188/4000 [11:19<22:08,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: -5.7816972732543945, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.174394607543945, Predicted Probability: 0.0008, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.5067853927612305, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 6.151695251464844, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  30%|██▉       | 1190/4000 [11:20<23:31,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.576162815093994, Predicted Probability: 0.9293, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.775636672973633, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1192/4000 [11:20<16:23,  2.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.15895938873291, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.899986505508423, Predicted Probability: 0.9802, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 4.393499374389648, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.64491081237793, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  30%|██▉       | 1193/4000 [11:21<23:23,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.052108764648438, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.293801307678223, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1194/4000 [11:22<26:51,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.539570331573486, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.512606620788574, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1195/4000 [11:22<29:06,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.55537223815918, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0188544988632202, Predicted Probability: 0.2653, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1196/4000 [11:23<25:31,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.397300720214844, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.127995491027832, Predicted Probability: 0.0159, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1197/4000 [11:23<25:42,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.32712984085083, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6258997917175293, Predicted Probability: 0.0675, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1198/4000 [11:24<28:21,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.942591190338135, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.934567928314209, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  30%|██▉       | 1199/4000 [11:25<30:18,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.375833034515381, Predicted Probability: 0.9876, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.429222106933594, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  30%|███       | 1200/4000 [11:25<31:37,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.047811031341553, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.456418752670288, Predicted Probability: 0.9210, Prediction: 1.0

Epoch 2/3:  30%|███       | 1201/4000 [11:26<32:37,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.298508644104004, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.916559100151062, Predicted Probability: 0.8718, Prediction: 1.0

Epoch 2/3:  30%|███       | 1202/4000 [11:26<25:41,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8619006276130676, Predicted Probability: 0.2969, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.5558953285217285, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  30%|███       | 1203/4000 [11:27<28:48,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.575366020202637, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6121339797973633, Predicted Probability: 0.0684, Prediction: 0.0

Epoch 2/3:  30%|███       | 1204/4000 [11:28<30:38,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.693852424621582, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.176820755004883, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  30%|███       | 1205/4000 [11:29<28:53,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.284252166748047, Predicted Probability: 0.0924, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0510945320129395, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  30%|███       | 1206/4000 [11:29<23:07,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.660066604614258, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.716114044189453, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  30%|███       | 1207/4000 [11:29<19:04,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.54188060760498, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.900773525238037, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 2/3:  30%|███       | 1208/4000 [11:30<23:32,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.395484924316406, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.968043804168701, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  30%|███       | 1209/4000 [11:30<24:13,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.702120780944824, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.895232677459717, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 2/3:  30%|███       | 1210/4000 [11:31<27:51,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.573216438293457, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.891726493835449, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  30%|███       | 1211/4000 [11:32<30:25,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.210310935974121, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8294763565063477, Predicted Probability: 0.6962, Prediction: 1.0

Epoch 2/3:  30%|███       | 1212/4000 [11:33<31:31,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.245880603790283, Predicted Probability: 0.9043, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.59107780456543, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  30%|███       | 1213/4000 [11:33<32:44,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7908918857574463, Predicted Probability: 0.0578, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.953894138336182, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  30%|███       | 1214/4000 [11:34<28:19,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.267666339874268, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.2606282234191895, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  30%|███       | 1215/4000 [11:34<25:07,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.464970827102661, Predicted Probability: 0.0303, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.629513263702393, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  30%|███       | 1216/4000 [11:35<28:19,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.689911842346191, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.538439989089966, Predicted Probability: 0.9268, Prediction: 1.0

Epoch 2/3:  30%|███       | 1217/4000 [11:36<30:27,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.627109527587891, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.0406407117843628, Predicted Probability: 0.7390, Prediction: 1.0

Epoch 2/3:  30%|███       | 1218/4000 [11:36<27:31,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.84255313873291, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9006407260894775, Predicted Probability: 0.9802, Prediction: 1.0

Epoch 2/3:  30%|███       | 1219/4000 [11:37<30:09,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.006148815155029, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.418286323547363, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  30%|███       | 1220/4000 [11:37<24:49,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.399203777313232, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.502297401428223, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  31%|███       | 1221/4000 [11:37<21:09,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0148792266845703, Predicted Probability: 0.0468, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1661529541015625, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  31%|███       | 1222/4000 [11:38<25:04,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.836071968078613, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7736005783081055, Predicted Probability: 0.0588, Prediction: 0.0

Epoch 2/3:  31%|███       | 1223/4000 [11:39<28:18,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8775806427001953, Predicted Probability: 0.0533, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7778544425964355, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  31%|███       | 1224/4000 [11:39<25:04,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.01418399810791, Predicted Probability: 0.9823, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.404197931289673, Predicted Probability: 0.9171, Prediction: 1.0

Epoch 2/3:  31%|███       | 1225/4000 [11:40<27:38,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.691972732543945, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.127686023712158, Predicted Probability: 0.8936, Prediction: 1.0

Epoch 2/3:  31%|███       | 1226/4000 [11:41<29:30,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.611015319824219, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.956993818283081, Predicted Probability: 0.9812, Prediction: 1.0

Epoch 2/3:  31%|███       | 1227/4000 [11:41<28:31,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.220961093902588, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.222044944763184, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  31%|███       | 1228/4000 [11:42<35:04,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.498849391937256, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6637039184570312, Predicted Probability: 0.0651, Prediction: 0.0

Epoch 2/3:  31%|███       | 1229/4000 [11:43<29:49,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.18876314163208, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.442215919494629, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:  31%|███       | 1230/4000 [11:43<26:03,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.473536729812622, Predicted Probability: 0.0301, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.246870517730713, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  31%|███       | 1231/4000 [11:43<21:20,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.018060684204102, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.404516220092773, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  31%|███       | 1232/4000 [11:44<22:28,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.315128326416016, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.94740104675293, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  31%|███       | 1234/4000 [11:45<21:35,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.298120975494385, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.051876068115234, Predicted Probability: 0.9829, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.023463726043701, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.525702476501465, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  31%|███       | 1235/4000 [11:45<20:13,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6965861320495605, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.487511157989502, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  31%|███       | 1236/4000 [11:46<25:19,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.815886974334717, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.010928630828857, Predicted Probability: 0.9822, Prediction: 1.0

Epoch 2/3:  31%|███       | 1237/4000 [11:47<28:58,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.094411849975586, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.819812297821045, Predicted Probability: 0.8605, Prediction: 1.0

Epoch 2/3:  31%|███       | 1238/4000 [11:47<28:06,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.3454132080078125, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.34135365486145, Predicted Probability: 0.9122, Prediction: 1.0

Epoch 2/3:  31%|███       | 1239/4000 [11:48<30:27,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.235651969909668, Predicted Probability: 0.2252, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.192782402038574, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  31%|███       | 1240/4000 [11:49<31:48,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.583948612213135, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.730485439300537, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 2/3:  31%|███       | 1241/4000 [11:50<29:44,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.003839492797852, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6343611478805542, Predicted Probability: 0.8368, Prediction: 1.0

Epoch 2/3:  31%|███       | 1242/4000 [11:50<33:09,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.795406341552734, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.67653751373291, Predicted Probability: 0.0005, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.322118282318115, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  31%|███       | 1243/4000 [11:51<25:58,  1.77it/s]

Data point 2: Actual Class: 1.0, Final Logit: 7.6629252433776855, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  31%|███       | 1245/4000 [11:51<17:25,  2.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.307363510131836, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.192061901092529, Predicted Probability: 0.0008, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.605291366577148, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.749163627624512, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  31%|███       | 1246/4000 [11:51<17:27,  2.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.601001262664795, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.614639759063721, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  31%|███       | 1247/4000 [11:52<22:50,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.697874069213867, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.355396747589111, Predicted Probability: 0.9873, Prediction: 1.0

Epoch 2/3:  31%|███       | 1248/4000 [11:53<22:10,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.716279029846191, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.596644878387451, Predicted Probability: 0.0100, Prediction: 0.0

Epoch 2/3:  31%|███       | 1249/4000 [11:53<25:31,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4010725021362305, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6546160578727722, Predicted Probability: 0.3420, Prediction: 0.0

Epoch 2/3:  31%|███▏      | 1250/4000 [11:54<26:17,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4935144186019897, Predicted Probability: 0.1834, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7274649143218994, Predicted Probability: 0.8491, Prediction: 1.0

Epoch 2/3:  31%|███▏      | 1251/4000 [11:55<28:55,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.252093315124512, Predicted Probability: 0.9860, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.142111301422119, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  31%|███▏      | 1252/4000 [11:55<26:18,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.104820728302002, Predicted Probability: 0.9838, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7627108097076416, Predicted Probability: 0.9773, Prediction: 1.0

Epoch 2/3:  31%|███▏      | 1253/4000 [11:56<28:52,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4277420043945312, Predicted Probability: 0.0811, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.655048847198486, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  31%|███▏      | 1254/4000 [11:57<30:20,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.482625961303711, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1386332511901855, Predicted Probability: 0.8946, Prediction: 1.0

Epoch 2/3:  31%|███▏      | 1255/4000 [11:57<31:28,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.814682483673096, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.365818023681641, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:  31%|███▏      | 1256/4000 [11:58<27:16,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.417612075805664, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.063533306121826, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  31%|███▏      | 1257/4000 [11:58<21:54,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5598657727241516, Predicted Probability: 0.3636, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.83595609664917, Predicted Probability: 0.0211, Prediction: 0.0

Epoch 2/3:  31%|███▏      | 1258/4000 [11:58<18:57,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.630435943603516, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.781762599945068, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  31%|███▏      | 1259/4000 [11:59<23:29,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.279417037963867, Predicted Probability: 0.9072, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.953076362609863, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1261/4000 [12:00<17:44,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.651734828948975, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.402022361755371, Predicted Probability: 0.0045, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -6.494012355804443, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.011885643005371, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1262/4000 [12:00<22:51,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.076774597167969, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.737442493438721, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1263/4000 [12:01<26:10,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5305806398391724, Predicted Probability: 0.8221, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.267034530639648, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1264/4000 [12:02<28:36,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.689474105834961, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6098308563232422, Predicted Probability: 0.1666, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1265/4000 [12:03<30:01,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.083532333374023, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.109795093536377, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1266/4000 [12:03<23:53,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.398715972900391, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.725848197937012, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1267/4000 [12:03<22:05,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.781485557556152, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.5428853034973145, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1268/4000 [12:04<20:37,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.32177734375, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.370334148406982, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1269/4000 [12:04<19:36,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9672975540161133, Predicted Probability: 0.0186, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.328413486480713, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1270/4000 [12:04<18:47,  2.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.560191631317139, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7642919421195984, Predicted Probability: 0.6823, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1271/4000 [12:05<20:41,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.214716911315918, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.471212387084961, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1272/4000 [12:06<24:38,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9604291915893555, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9691615104675293, Predicted Probability: 0.9815, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1273/4000 [12:06<28:50,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.183440208435059, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.434637546539307, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1274/4000 [12:07<30:36,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.97826623916626, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2179372310638428, Predicted Probability: 0.9018, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1275/4000 [12:08<27:29,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.878922939300537, Predicted Probability: 0.0532, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.181188583374023, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1276/4000 [12:08<24:23,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.246673107147217, Predicted Probability: 0.9859, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5520524978637695, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1278/4000 [12:08<16:34,  2.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.073780536651611, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.026558876037598, Predicted Probability: 0.9997, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.651941776275635, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.034753322601318, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1279/4000 [12:09<17:01,  2.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.442686080932617, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.194699764251709, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1280/4000 [12:09<14:40,  3.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.244318962097168, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.685030937194824, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1281/4000 [12:10<20:23,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.95706844329834, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.057311534881592, Predicted Probability: 0.8867, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1282/4000 [12:11<24:25,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.618302822113037, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6018120050430298, Predicted Probability: 0.1677, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1283/4000 [12:11<23:14,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9258551597595215, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.792111396789551, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1284/4000 [12:12<26:35,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.978260040283203, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.230713844299316, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1285/4000 [12:12<23:47,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.839894771575928, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.365650653839111, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1286/4000 [12:13<26:31,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2275968790054321, Predicted Probability: 0.7734, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.9548516273498535, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1287/4000 [12:13<23:36,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.754852294921875, Predicted Probability: 0.9771, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.546885013580322, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1288/4000 [12:14<26:30,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2928165793418884, Predicted Probability: 0.5727, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.256992340087891, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1289/4000 [12:14<21:20,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1353840827941895, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.63092041015625, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1290/4000 [12:15<19:48,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.67464017868042, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.750983238220215, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1291/4000 [12:15<25:08,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.950707197189331, Predicted Probability: 0.1245, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.999004364013672, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1292/4000 [12:16<21:12,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.944833278656006, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.545780181884766, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1293/4000 [12:16<25:17,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.131591320037842, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.3239569664001465, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1294/4000 [12:17<27:58,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.740744113922119, Predicted Probability: 0.9768, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.375120162963867, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1295/4000 [12:18<24:26,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.206145763397217, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0365142822265625, Predicted Probability: 0.9935, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1296/4000 [12:18<24:09,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.814692974090576, Predicted Probability: 0.9435, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.382053375244141, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1297/4000 [12:19<26:53,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.946573257446289, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7709691524505615, Predicted Probability: 0.9411, Prediction: 1.0

Epoch 2/3:  32%|███▏      | 1298/4000 [12:20<28:38,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5145761966705322, Predicted Probability: 0.9252, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.354291915893555, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  32%|███▏      | 1299/4000 [12:20<25:57,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.613828659057617, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2261667251586914, Predicted Probability: 0.9618, Prediction: 1.0

Epoch 2/3:  32%|███▎      | 1300/4000 [12:21<28:22,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.519158363342285, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.522940158843994, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1301/4000 [12:21<29:53,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.578679084777832, Predicted Probability: 0.0705, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7851413488388062, Predicted Probability: 0.3132, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1302/4000 [12:22<31:41,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.851383209228516, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.036590576171875, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1303/4000 [12:23<28:14,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.242599010467529, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.421104907989502, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1304/4000 [12:24<30:36,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.262305736541748, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.466080665588379, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1305/4000 [12:24<26:36,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9471782445907593, Predicted Probability: 0.8751, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.576810359954834, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1306/4000 [12:25<32:49,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.112393379211426, Predicted Probability: 0.9574, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.297629356384277, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1307/4000 [12:25<28:06,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.353904724121094, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1337409019470215, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1308/4000 [12:26<29:32,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0774341821670532, Predicted Probability: 0.2540, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.934760570526123, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1309/4000 [12:27<28:08,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.012429237365723, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.97566032409668, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1310/4000 [12:27<28:11,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.359695911407471, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.230183124542236, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1311/4000 [12:28<29:28,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.11059045791626, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2467859983444214, Predicted Probability: 0.2233, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1312/4000 [12:28<23:22,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.198875904083252, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.316285610198975, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1313/4000 [12:29<27:28,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.714026927947998, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.431434154510498, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1314/4000 [12:30<29:00,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.328589916229248, Predicted Probability: 0.9112, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4499642848968506, Predicted Probability: 0.8100, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1315/4000 [12:30<23:03,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4005961418151855, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.564478874206543, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1316/4000 [12:30<21:07,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.8527703285217285, Predicted Probability: 0.9923, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.07070541381836, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1317/4000 [12:31<24:33,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.434893608093262, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.583531379699707, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1318/4000 [12:32<27:06,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.487822532653809, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.260227203369141, Predicted Probability: 0.9861, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1319/4000 [12:33<29:28,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.27811861038208, Predicted Probability: 0.9863, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.915680885314941, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1320/4000 [12:33<23:21,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.886014461517334, Predicted Probability: 0.9472, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.276379585266113, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1321/4000 [12:34<26:03,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.142831325531006, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.526855707168579, Predicted Probability: 0.9260, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1322/4000 [12:34<24:05,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.11146277189254761, Predicted Probability: 0.5278, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.484313011169434, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1323/4000 [12:35<26:15,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5163960456848145, Predicted Probability: 0.9253, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1072680950164795, Predicted Probability: 0.7516, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1324/4000 [12:35<21:04,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.227146148681641, Predicted Probability: 0.9856, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.942699432373047, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1325/4000 [12:36<24:18,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.527632236480713, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6395692825317383, Predicted Probability: 0.8375, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1326/4000 [12:36<21:59,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.340917587280273, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7163729667663574, Predicted Probability: 0.9763, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1327/4000 [12:37<25:51,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.946962356567383, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.322232961654663, Predicted Probability: 0.9107, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1328/4000 [12:37<23:07,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.577841758728027, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.458641529083252, Predicted Probability: 0.9886, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1329/4000 [12:38<26:07,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.001995086669922, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8380283117294312, Predicted Probability: 0.8627, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1330/4000 [12:38<23:06,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.953983306884766, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.809662818908691, Predicted Probability: 0.9919, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1331/4000 [12:39<23:16,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9877077341079712, Predicted Probability: 0.2714, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.365114688873291, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1332/4000 [12:39<21:15,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.416757583618164, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.468164443969727, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1333/4000 [12:39<17:39,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.695228576660156, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.011092662811279, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1334/4000 [12:40<18:04,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.608397364616394, Predicted Probability: 0.8332, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.678438186645508, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1336/4000 [12:41<18:42,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.881824493408203, Predicted Probability: 0.0202, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.461087703704834, Predicted Probability: 0.9984, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -7.922763824462891, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.413403511047363, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  33%|███▎      | 1337/4000 [12:41<23:16,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6134657859802246, Predicted Probability: 0.1661, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.216358661651611, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1338/4000 [12:42<26:35,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.293148994445801, Predicted Probability: 0.9642, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4641642570495605, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  33%|███▎      | 1339/4000 [12:42<21:22,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.283814907073975, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 4.834498882293701, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 2/3:  34%|███▎      | 1340/4000 [12:43<22:07,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.650574207305908, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4095345735549927, Predicted Probability: 0.1963, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1341/4000 [12:43<18:11,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.40578031539917, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1287779808044434, Predicted Probability: 0.9581, Prediction: 1.0

Epoch 2/3:  34%|███▎      | 1342/4000 [12:44<22:55,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8640925884246826, Predicted Probability: 0.9794, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.086276531219482, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1343/4000 [12:45<26:24,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.639301061630249, Predicted Probability: 0.8374, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.816586494445801, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1344/4000 [12:46<29:07,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1993324756622314, Predicted Probability: 0.9002, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.749022960662842, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1345/4000 [12:46<25:28,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.008802890777588, Predicted Probability: 0.9822, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.58244514465332, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  34%|███▎      | 1346/4000 [12:47<27:20,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.42399263381958, Predicted Probability: 0.0118, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.467916965484619, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1347/4000 [12:47<26:35,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.7838398218154907, Predicted Probability: 0.1438, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.848596096038818, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1348/4000 [12:48<28:34,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3949317932128906, Predicted Probability: 0.1986, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5433807373046875, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  34%|███▎      | 1349/4000 [12:49<29:44,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.153570175170898, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6410973072052, Predicted Probability: 0.9335, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1350/4000 [12:49<27:51,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.326392650604248, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.266646862030029, Predicted Probability: 0.9862, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1351/4000 [12:50<30:31,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3276166915893555, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6077880859375, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1352/4000 [12:51<31:16,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.23489665985107422, Predicted Probability: 0.4415, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.019782066345215, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1353/4000 [12:52<32:40,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9625986814498901, Predicted Probability: 0.8768, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.093006134033203, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1354/4000 [12:52<33:02,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.137520790100098, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.279388904571533, Predicted Probability: 0.9072, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1355/4000 [12:53<33:44,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.456084728240967, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.783904552459717, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1356/4000 [12:54<33:28,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.793972969055176, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.635918378829956, Predicted Probability: 0.6538, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1357/4000 [12:55<33:25,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3067779541015625, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.131987571716309, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1358/4000 [12:55<30:29,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4840595722198486, Predicted Probability: 0.8152, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.139059543609619, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1359/4000 [12:56<31:08,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.304309844970703, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.518950939178467, Predicted Probability: 0.9255, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1360/4000 [12:57<29:27,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.794757604598999, Predicted Probability: 0.9780, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.571290969848633, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1361/4000 [12:57<30:12,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.78157114982605, Predicted Probability: 0.9417, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.949988842010498, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1362/4000 [12:58<26:06,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.887187480926514, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.149528503417969, Predicted Probability: 0.9845, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1363/4000 [12:58<27:46,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3711438179016113, Predicted Probability: 0.9146, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.3788228034973145, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1364/4000 [12:59<22:11,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.334700107574463, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.348445415496826, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1365/4000 [12:59<20:34,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.095437049865723, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.818894386291504, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1366/4000 [13:00<24:48,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.419548511505127, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1888880729675293, Predicted Probability: 0.2335, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1367/4000 [13:01<28:09,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.935926914215088, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5864129066467285, Predicted Probability: 0.0270, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1368/4000 [13:01<29:32,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.236880302429199, Predicted Probability: 0.9858, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.9085588455200195, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1369/4000 [13:02<25:29,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5440269708633423, Predicted Probability: 0.8240, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.988700032234192, Predicted Probability: 0.1204, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1370/4000 [13:02<27:22,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.740151882171631, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.721068859100342, Predicted Probability: 0.9383, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1371/4000 [13:03<28:55,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.318144798278809, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.396152973175049, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1372/4000 [13:04<25:17,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9291329383850098, Predicted Probability: 0.8732, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9426872730255127, Predicted Probability: 0.9810, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1373/4000 [13:04<28:13,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.14017105102539, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.437723159790039, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1374/4000 [13:05<29:31,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2777628898620605, Predicted Probability: 0.0363, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.556952476501465, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1375/4000 [13:06<27:59,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.404606342315674, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.168212413787842, Predicted Probability: 0.9848, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1376/4000 [13:06<29:49,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.646498680114746, Predicted Probability: 0.8384, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.187265396118164, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 2/3:  34%|███▍      | 1377/4000 [13:07<25:44,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.868786811828613, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.182994842529297, Predicted Probability: 0.8987, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1378/4000 [13:07<25:02,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.733662128448486, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6883015632629395, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1379/4000 [13:08<26:58,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.997109413146973, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4855226278305054, Predicted Probability: 0.8154, Prediction: 1.0

Epoch 2/3:  34%|███▍      | 1380/4000 [13:08<23:53,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.062884330749512, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.839853286743164, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1381/4000 [13:09<26:39,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2723255157470703, Predicted Probability: 0.9635, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0829901695251465, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1382/4000 [13:10<28:04,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5270795226097107, Predicted Probability: 0.3712, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.585907936096191, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1383/4000 [13:10<24:38,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.948000431060791, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.143670082092285, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1384/4000 [13:11<22:15,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.723267555236816, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.014232635498047, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1385/4000 [13:11<20:28,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.56128454208374, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.405944347381592, Predicted Probability: 0.9879, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1386/4000 [13:12<25:14,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.590428352355957, Predicted Probability: 0.6435, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6950480937957764, Predicted Probability: 0.0242, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1387/4000 [13:13<25:44,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.368180274963379, Predicted Probability: 0.0125, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.364851713180542, Predicted Probability: 0.9666, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1388/4000 [13:13<27:45,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.476773262023926, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9524755477905273, Predicted Probability: 0.9504, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1389/4000 [13:14<29:39,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0834124088287354, Predicted Probability: 0.8893, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.821995258331299, Predicted Probability: 0.0561, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1390/4000 [13:14<23:30,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.351250171661377, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.310131072998047, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1391/4000 [13:15<27:02,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.927822113037109, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.566164016723633, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1392/4000 [13:15<23:41,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5999319553375244, Predicted Probability: 0.9309, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.075495719909668, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1393/4000 [13:16<26:25,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.0652925968170166, Predicted Probability: 0.5163, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.930723190307617, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1394/4000 [13:17<28:40,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.05698299407959, Predicted Probability: 0.0170, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.08240658044815063, Predicted Probability: 0.4794, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1395/4000 [13:18<30:28,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4403096437454224, Predicted Probability: 0.1915, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.627724647521973, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1396/4000 [13:18<24:04,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.865190505981445, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.4811530113220215, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  35%|███▍      | 1397/4000 [13:19<30:23,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5850672721862793, Predicted Probability: 0.0270, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.137538909912109, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1398/4000 [13:20<31:30,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.652027606964111, Predicted Probability: 0.9905, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.309794902801514, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 2/3:  35%|███▍      | 1399/4000 [13:20<27:09,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.846822738647461, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.439276099205017, Predicted Probability: 0.1917, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1400/4000 [13:21<28:10,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.370260238647461, Predicted Probability: 0.9145, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9338175654411316, Predicted Probability: 0.7178, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1401/4000 [13:22<30:41,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.751326560974121, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.845182418823242, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1402/4000 [13:22<25:03,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.752161979675293, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.055293560028076, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1403/4000 [13:23<27:18,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.582626819610596, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.53070068359375, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1404/4000 [13:23<23:49,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.390892505645752, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.35888147354126, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1405/4000 [13:24<27:10,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.816069602966309, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0655083656311035, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1406/4000 [13:24<23:48,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8033640384674072, Predicted Probability: 0.9429, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.84188461303711, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1407/4000 [13:25<26:35,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.038850784301758, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.773556709289551, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1408/4000 [13:26<28:17,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.808684349060059, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4538087844848633, Predicted Probability: 0.9693, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1409/4000 [13:27<29:20,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.272980690002441, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1223931312561035, Predicted Probability: 0.0422, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1410/4000 [13:27<23:15,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.593663215637207, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1043901443481445, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1411/4000 [13:27<21:09,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.624305725097656, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.677066326141357, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1412/4000 [13:28<26:05,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.179079055786133, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.257766246795654, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1413/4000 [13:29<25:21,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8856156468391418, Predicted Probability: 0.2920, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8278520107269287, Predicted Probability: 0.8615, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1414/4000 [13:29<27:40,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.701845169067383, Predicted Probability: 0.9910, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6422648429870605, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1415/4000 [13:30<28:47,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.288816452026367, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0081470012664795, Predicted Probability: 0.2673, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1416/4000 [13:31<28:00,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.0881184339523315, Predicted Probability: 0.2520, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0356028079986572, Predicted Probability: 0.1155, Prediction: 0.0

Epoch 2/3:  35%|███▌      | 1417/4000 [13:31<28:54,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.377630233764648, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9959683418273926, Predicted Probability: 0.9524, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1418/4000 [13:32<29:43,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.48046875, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.971310138702393, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 2/3:  35%|███▌      | 1419/4000 [13:33<30:27,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.141581058502197, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.474032878875732, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1420/4000 [13:34<32:01,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.200913906097412, Predicted Probability: 0.0148, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.23415470123291, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1421/4000 [13:34<27:15,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0091428756713867, Predicted Probability: 0.0470, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.9250874519348145, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1422/4000 [13:35<23:54,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.709303379058838, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2006072998046875, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1423/4000 [13:35<19:31,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.74068546295166, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5940976738929749, Predicted Probability: 0.6443, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1424/4000 [13:35<23:02,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.101547956466675, Predicted Probability: 0.0430, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.162201881408691, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1425/4000 [13:36<25:59,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3165364265441895, Predicted Probability: 0.0350, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.671171188354492, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1426/4000 [13:37<28:11,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.278315544128418, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.246567726135254, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1427/4000 [13:38<29:52,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.12828254699707, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.895210266113281, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1428/4000 [13:38<27:53,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.1241583824157715, Predicted Probability: 0.9841, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5015974044799805, Predicted Probability: 0.9707, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1429/4000 [13:39<22:59,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.211256980895996, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.898956298828125, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1430/4000 [13:39<20:49,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.167950630187988, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.809806823730469, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1431/4000 [13:39<17:10,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.232171058654785, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.492178916931152, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1432/4000 [13:40<21:20,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6913299560546875, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4888274669647217, Predicted Probability: 0.9704, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1433/4000 [13:40<19:56,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.174717903137207, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.940774440765381, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1434/4000 [13:41<23:47,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.404024362564087, Predicted Probability: 0.9171, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1605029106140137, Predicted Probability: 0.1034, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1435/4000 [13:42<25:40,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.22163724899292, Predicted Probability: 0.9616, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.706420421600342, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1436/4000 [13:42<23:37,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.232698440551758, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1177802085876465, Predicted Probability: 0.9840, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1437/4000 [13:43<23:30,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.241746723651886, Predicted Probability: 0.4399, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.922914505004883, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1438/4000 [13:44<27:34,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.984004020690918, Predicted Probability: 0.1209, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.233145713806152, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1439/4000 [13:44<24:15,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.918420791625977, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.898257255554199, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1440/4000 [13:45<24:09,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.650623321533203, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.735354423522949, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1441/4000 [13:45<27:00,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.3550555408000946, Predicted Probability: 0.5878, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.864989757537842, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1442/4000 [13:46<28:18,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8116374015808105, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.617732524871826, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1443/4000 [13:47<30:05,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8990681171417236, Predicted Probability: 0.0522, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.476099967956543, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1444/4000 [13:48<31:20,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.140652656555176, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.627293586730957, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1445/4000 [13:48<24:34,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.115533828735352, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.150012969970703, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1446/4000 [13:49<26:39,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.946444511413574, Predicted Probability: 0.9501, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.249439239501953, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1447/4000 [13:49<25:44,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.337205410003662, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.161690711975098, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  36%|███▌      | 1448/4000 [13:49<21:31,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.658139228820801, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.791035175323486, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  36%|███▌      | 1449/4000 [13:50<24:36,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.383509635925293, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8791401386260986, Predicted Probability: 0.9468, Prediction: 1.0

Epoch 2/3:  36%|███▋      | 1450/4000 [13:51<26:47,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.08750057220459, Predicted Probability: 0.9835, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.324826717376709, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1451/4000 [13:52<28:22,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.082255840301514, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.140685081481934, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1452/4000 [13:53<30:04,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6671414375305176, Predicted Probability: 0.0649, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.673686504364014, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1453/4000 [13:53<30:47,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.754731178283691, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.715622901916504, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 2/3:  36%|███▋      | 1454/4000 [13:54<31:20,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.962860107421875, Predicted Probability: 0.9509, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.80039119720459, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1455/4000 [13:55<31:13,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.438124179840088, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.98797869682312, Predicted Probability: 0.9520, Prediction: 1.0

Epoch 2/3:  36%|███▋      | 1456/4000 [13:56<31:32,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.010784149169922, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.18237066268920898, Predicted Probability: 0.4545, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1457/4000 [13:56<32:10,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.692137718200684, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.9659104347229, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1458/4000 [13:57<32:16,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.387363433837891, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8539462089538574, Predicted Probability: 0.9455, Prediction: 1.0

Epoch 2/3:  36%|███▋      | 1459/4000 [13:57<26:00,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6658453941345215, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7217147946357727, Predicted Probability: 0.3270, Prediction: 0.0

Epoch 2/3:  36%|███▋      | 1460/4000 [13:58<22:51,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.006148338317871, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.781881332397461, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1461/4000 [13:58<20:33,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.7218194007873535, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.228023052215576, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1462/4000 [13:59<24:11,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.546097755432129, Predicted Probability: 0.0105, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9514479637145996, Predicted Probability: 0.9503, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1463/4000 [14:00<26:26,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.877728462219238, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9559454917907715, Predicted Probability: 0.9812, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1464/4000 [14:00<28:44,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.634292125701904, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.828808784484863, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1465/4000 [14:01<29:43,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.716127872467041, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.244151592254639, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1466/4000 [14:01<23:24,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.481235980987549, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.980015754699707, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1467/4000 [14:02<21:16,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.864983558654785, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.779898643493652, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1468/4000 [14:02<19:34,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.798353672027588, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.798503875732422, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1469/4000 [14:03<23:23,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0531249046325684, Predicted Probability: 0.9549, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.359076023101807, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1470/4000 [14:04<25:33,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6730995178222656, Predicted Probability: 0.9354, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.493387222290039, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1471/4000 [14:04<27:01,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7293686866760254, Predicted Probability: 0.9387, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.206643104553223, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1472/4000 [14:05<28:08,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.035581588745117, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3835409879684448, Predicted Probability: 0.4053, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1473/4000 [14:06<29:07,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5390022993087769, Predicted Probability: 0.3684, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.848779678344727, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1474/4000 [14:06<25:14,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.926614284515381, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.942580699920654, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1475/4000 [14:07<27:02,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.663002967834473, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.883772850036621, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1476/4000 [14:07<24:22,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.507655620574951, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2733581066131592, Predicted Probability: 0.2187, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1477/4000 [14:08<26:53,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3985700607299805, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.685856819152832, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1478/4000 [14:09<23:33,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6178746223449707, Predicted Probability: 0.0680, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.902729511260986, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1479/4000 [14:09<21:03,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.023261070251465, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.580077648162842, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1480/4000 [14:10<24:16,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.261013031005859, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8868601322174072, Predicted Probability: 0.0528, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1481/4000 [14:10<21:30,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.670540809631348, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.768594264984131, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1482/4000 [14:10<19:39,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.010756969451904, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.805646896362305, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1483/4000 [14:11<18:26,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.389057159423828, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.254593849182129, Predicted Probability: 0.9860, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1484/4000 [14:12<22:32,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6400550603866577, Predicted Probability: 0.1625, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.931451797485352, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1485/4000 [14:12<25:20,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.094995498657227, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7966738939285278, Predicted Probability: 0.3107, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1486/4000 [14:13<28:30,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2895002365112305, Predicted Probability: 0.9865, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.249812126159668, Predicted Probability: 0.0141, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1487/4000 [14:14<24:40,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.761849880218506, Predicted Probability: 0.9915, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 6.600253582000732, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1488/4000 [14:14<20:38,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.809389114379883, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.654778957366943, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1489/4000 [14:14<21:23,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.526682376861572, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.866941452026367, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1490/4000 [14:15<22:02,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.320367813110352, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.465992450714111, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1491/4000 [14:15<20:11,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.786662101745605, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.569291114807129, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1493/4000 [14:16<18:53,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8073179721832275, Predicted Probability: 0.9783, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6019086837768555, Predicted Probability: 0.0005, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.98156452178955, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.911166191101074, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1494/4000 [14:17<22:23,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.413079261779785, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.127798080444336, Predicted Probability: 0.9841, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1495/4000 [14:17<20:13,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4746038913726807, Predicted Probability: 0.0777, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.3260059356689453, Predicted Probability: 0.7902, Prediction: 1.0

Epoch 2/3:  37%|███▋      | 1496/4000 [14:18<23:31,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.217391490936279, Predicted Probability: 0.9855, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.904513359069824, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1497/4000 [14:19<25:43,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.560039520263672, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.255168914794922, Predicted Probability: 0.0371, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1498/4000 [14:19<22:32,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2821531295776367, Predicted Probability: 0.2172, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.520302772521973, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  37%|███▋      | 1499/4000 [14:20<22:34,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3807597160339355, Predicted Probability: 0.9671, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.843844473361969, Predicted Probability: 0.3007, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1500/4000 [14:21<25:17,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4349849224090576, Predicted Probability: 0.0312, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.388609409332275, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1501/4000 [14:21<22:24,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.153029918670654, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.684401750564575, Predicted Probability: 0.0245, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1502/4000 [14:22<25:25,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.072225093841553, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5436062812805176, Predicted Probability: 0.9719, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1503/4000 [14:22<26:55,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.033648133277893, Predicted Probability: 0.2624, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.970155715942383, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1505/4000 [14:23<22:08,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.531787872314453, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.995060920715332, Predicted Probability: 0.0009, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -7.75140380859375, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.325114250183105, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1506/4000 [14:24<26:36,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.661771774291992, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.681423187255859, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1507/4000 [14:25<23:08,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.403799533843994, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.905568599700928, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1508/4000 [14:25<18:42,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.793776035308838, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.966945171356201, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1509/4000 [14:25<15:38,  2.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.47404688596725464, Predicted Probability: 0.6163, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.920814514160156, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1510/4000 [14:25<15:25,  2.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.393806457519531, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.2899322509765625, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1511/4000 [14:26<15:13,  2.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9593825340271, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0954363346099854, Predicted Probability: 0.8905, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1512/4000 [14:27<21:36,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.593973636627197, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.379214286804199, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1514/4000 [14:27<16:25,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.357545852661133, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7351105213165283, Predicted Probability: 0.9767, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 1.0719184875488281, Predicted Probability: 0.7450, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.998957633972168, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1515/4000 [14:28<21:17,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.954554557800293, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.1765458583831787, Predicted Probability: 0.1019, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1516/4000 [14:29<24:43,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2011489868164062, Predicted Probability: 0.9004, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.136138916015625, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1517/4000 [14:30<26:35,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.768174171447754, Predicted Probability: 0.9409, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.208115100860596, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1518/4000 [14:30<28:34,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.0631181001663208, Predicted Probability: 0.4842, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.297972679138184, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1519/4000 [14:31<29:01,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.6515884399414062, Predicted Probability: 0.6574, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.236112117767334, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1520/4000 [14:31<24:55,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.58245325088501, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.144560694694519, Predicted Probability: 0.7585, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1521/4000 [14:32<26:18,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0626115798950195, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.446169853210449, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1522/4000 [14:33<28:02,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1135973930358887, Predicted Probability: 0.8922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.340322017669678, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1523/4000 [14:34<28:51,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.17461669445037842, Predicted Probability: 0.4565, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.627738952636719, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1524/4000 [14:34<29:24,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.028802871704102, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.09178704023361206, Predicted Probability: 0.4771, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1525/4000 [14:35<25:06,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.616542339324951, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.626137733459473, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1526/4000 [14:36<26:52,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.560584545135498, Predicted Probability: 0.9283, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.074773788452148, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1527/4000 [14:36<28:55,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.74388313293457, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.346551418304443, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1528/4000 [14:37<24:47,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.814111232757568, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.837609052658081, Predicted Probability: 0.9447, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1529/4000 [14:37<21:43,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.632314145565033, Predicted Probability: 0.6530, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.889280319213867, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1530/4000 [14:38<25:49,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.174846649169922, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.122625350952148, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1531/4000 [14:38<22:35,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.12141751497983932, Predicted Probability: 0.5303, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.373878479003906, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1532/4000 [14:39<25:14,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6033220291137695, Predicted Probability: 0.0265, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.866644859313965, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1533/4000 [14:40<26:49,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.511699676513672, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5911312103271484, Predicted Probability: 0.0697, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1534/4000 [14:41<27:36,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.602006912231445, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8780479431152344, Predicted Probability: 0.9468, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1535/4000 [14:41<28:32,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.85556697845459, Predicted Probability: 0.9456, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.872429847717285, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1536/4000 [14:42<24:40,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.525557518005371, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.610325813293457, Predicted Probability: 0.3520, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1537/4000 [14:42<26:22,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.648282766342163, Predicted Probability: 0.8387, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.057563304901123, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1538/4000 [14:43<21:01,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.869483947753906, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.37398624420166, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  38%|███▊      | 1539/4000 [14:43<24:20,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9396133422851562, Predicted Probability: 0.8743, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5257415771484375, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 2/3:  38%|███▊      | 1540/4000 [14:44<22:32,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.29965353012085, Predicted Probability: 0.9866, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6722686290740967, Predicted Probability: 0.8419, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1541/4000 [14:44<18:16,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.867119312286377, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.585168838500977, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1542/4000 [14:45<22:21,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.784090518951416, Predicted Probability: 0.9917, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.33264684677124, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  39%|███▊      | 1543/4000 [14:46<24:54,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.465970993041992, Predicted Probability: 0.0783, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.170382022857666, Predicted Probability: 0.9597, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1544/4000 [14:46<26:40,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.190340042114258, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1078438758850098, Predicted Probability: 0.8917, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1545/4000 [14:47<28:15,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.597681045532227, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1391758918762207, Predicted Probability: 0.9585, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1546/4000 [14:47<22:16,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.923394203186035, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.251979351043701, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1547/4000 [14:48<20:08,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.66600227355957, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.056116580963135, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1548/4000 [14:48<23:28,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.276223659515381, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.51392936706543, Predicted Probability: 0.9892, Prediction: 1.0

Epoch 2/3:  39%|███▊      | 1549/4000 [14:49<26:16,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.075078964233398, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.891374111175537, Predicted Probability: 0.9925, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1550/4000 [14:50<27:47,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5362563133239746, Predicted Probability: 0.0283, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.557353973388672, Predicted Probability: 0.9723, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1551/4000 [14:51<28:16,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.935062408447266, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7706193923950195, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1552/4000 [14:51<29:06,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2510271072387695, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.230384826660156, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1553/4000 [14:52<25:51,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.68585729598999, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.665069103240967, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1554/4000 [14:52<24:48,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.595135688781738, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.690611362457275, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1555/4000 [14:53<27:00,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.434267044067383, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.086119651794434, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1556/4000 [14:54<28:23,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.094257354736328, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.993872880935669, Predicted Probability: 0.9523, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1557/4000 [14:54<25:18,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.580794811248779, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.091983318328857, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1558/4000 [14:55<26:37,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.858771324157715, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.978400468826294, Predicted Probability: 0.0484, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1559/4000 [14:56<27:16,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5517934560775757, Predicted Probability: 0.1748, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2633819580078125, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1560/4000 [14:57<28:03,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.414441108703613, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.236170530319214, Predicted Probability: 0.9622, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1561/4000 [14:57<28:23,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.14108020067214966, Predicted Probability: 0.4648, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.164013862609863, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1562/4000 [14:58<28:44,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.767784118652344, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5349345207214355, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1563/4000 [14:58<24:38,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.049623966217041, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.851468563079834, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1564/4000 [14:59<26:59,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.14231538772583, Predicted Probability: 0.0156, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.969433307647705, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1565/4000 [15:00<23:23,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.590147495269775, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5648417472839355, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1566/4000 [15:00<23:03,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.331338405609131, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.304529190063477, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1567/4000 [15:01<20:30,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.912769794464111, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.259716033935547, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1568/4000 [15:01<21:08,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.808099746704102, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.327564239501953, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1569/4000 [15:02<23:36,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.04230499267578125, Predicted Probability: 0.5106, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.104188919067383, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1570/4000 [15:03<25:38,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.696510314941406, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6404337882995605, Predicted Probability: 0.0666, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 3.2357029914855957, Predicted Probability: 0.9622, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1571/4000 [15:03<20:23,  1.99it/s]

Data point 2: Actual Class: 1.0, Final Logit: 0.16819334030151367, Predicted Probability: 0.5419, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1572/4000 [15:04<23:11,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.25102150440216064, Predicted Probability: 0.5624, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.058961868286133, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1573/4000 [15:04<25:39,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.825766563415527, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.286713600158691, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1574/4000 [15:05<20:28,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.167672157287598, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.246007919311523, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1575/4000 [15:05<23:22,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7190375328063965, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5234336853027344, Predicted Probability: 0.9258, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1576/4000 [15:06<26:23,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.387011528015137, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.025554656982422, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 2/3:  39%|███▉      | 1577/4000 [15:07<27:32,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.685331344604492, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.897292137145996, Predicted Probability: 0.9477, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1578/4000 [15:07<26:37,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.864099502563477, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.754955768585205, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  39%|███▉      | 1579/4000 [15:08<27:36,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.030105113983154, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.720077991485596, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1580/4000 [15:09<24:03,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.331689834594727, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.873622894287109, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1581/4000 [15:09<25:36,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.450647830963135, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4753024578094482, Predicted Probability: 0.8139, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1582/4000 [15:10<27:24,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.039422512054443, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.208662033081055, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1583/4000 [15:10<23:39,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.528043746948242, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.840978622436523, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1584/4000 [15:11<26:46,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.513318061828613, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.490937232971191, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1585/4000 [15:12<27:31,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.041920185089111, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.890128493309021, Predicted Probability: 0.2911, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1586/4000 [15:12<23:45,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.184774398803711, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3991010189056396, Predicted Probability: 0.0323, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1587/4000 [15:13<19:07,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.303585052490234, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.898089408874512, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1588/4000 [15:13<17:54,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.989091873168945, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3881843090057373, Predicted Probability: 0.0327, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1589/4000 [15:14<19:11,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.213873863220215, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.811553955078125, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1590/4000 [15:14<22:17,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.158867359161377, Predicted Probability: 0.7611, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.3356733322143555, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1591/4000 [15:15<22:01,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.757152557373047, Predicted Probability: 0.9772, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.454674243927002, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1592/4000 [15:16<24:22,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.849739074707031, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7482218742370605, Predicted Probability: 0.9398, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1593/4000 [15:16<19:37,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.712682247161865, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.445489406585693, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1594/4000 [15:16<22:21,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.2249321937561035, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.264360427856445, Predicted Probability: 0.9861, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1595/4000 [15:17<20:12,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.955866813659668, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7191989421844482, Predicted Probability: 0.9763, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1596/4000 [15:18<23:24,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.636843681335449, Predicted Probability: 0.0096, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.470592498779297, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1597/4000 [15:18<25:04,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0181376934051514, Predicted Probability: 0.9534, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.128392696380615, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  40%|███▉      | 1598/4000 [15:19<22:06,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.543407917022705, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.22005033493042, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 2/3:  40%|███▉      | 1599/4000 [15:19<24:19,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.6316601037979126, Predicted Probability: 0.8364, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.375709533691406, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 2/3:  40%|████      | 1600/4000 [15:20<26:05,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.570770740509033, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.023725509643555, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 2/3:  40%|████      | 1601/4000 [15:21<21:30,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.527324199676514, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.76729154586792, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  40%|████      | 1602/4000 [15:21<23:44,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.694736003875732, Predicted Probability: 0.9909, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1547737121582031, Predicted Probability: 0.7604, Prediction: 1.0

Epoch 2/3:  40%|████      | 1603/4000 [15:22<25:51,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8783656358718872, Predicted Probability: 0.2935, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.174739360809326, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 2/3:  40%|████      | 1604/4000 [15:23<27:11,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.832677364349365, Predicted Probability: 0.9921, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.669351577758789, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  40%|████      | 1605/4000 [15:24<28:47,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.994720220565796, Predicted Probability: 0.0181, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.8066253662109375, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  40%|████      | 1606/4000 [15:24<24:32,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.014777183532715, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.70236349105835, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 2/3:  40%|████      | 1607/4000 [15:25<23:42,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.813620090484619, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5349924564361572, Predicted Probability: 0.9717, Prediction: 1.0

Epoch 2/3:  40%|████      | 1608/4000 [15:25<25:48,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.840017318725586, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7750420570373535, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 2/3:  40%|████      | 1609/4000 [15:26<24:45,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.471924781799316, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.33204174041748047, Predicted Probability: 0.4177, Prediction: 0.0

Epoch 2/3:  40%|████      | 1610/4000 [15:27<26:12,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.566860198974609, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.938997745513916, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  40%|████      | 1611/4000 [15:27<24:45,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2221360206604, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.68881368637085, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  40%|████      | 1612/4000 [15:28<23:41,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.832756280899048, Predicted Probability: 0.0556, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.487822532653809, Predicted Probability: 0.0111, Prediction: 0.0

Epoch 2/3:  40%|████      | 1613/4000 [15:28<25:34,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.125640869140625, Predicted Probability: 0.0159, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7293554544448853, Predicted Probability: 0.3253, Prediction: 0.0

Epoch 2/3:  40%|████      | 1614/4000 [15:29<24:21,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8566083908081055, Predicted Probability: 0.9457, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6670882701873779, Predicted Probability: 0.3391, Prediction: 0.0

Epoch 2/3:  40%|████      | 1615/4000 [15:29<22:16,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1488776206970215, Predicted Probability: 0.1044, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.819578170776367, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  40%|████      | 1616/4000 [15:30<18:01,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.922548294067383, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.747495651245117, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  40%|████      | 1617/4000 [15:30<16:58,  2.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.492891788482666, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.868255853652954, Predicted Probability: 0.0537, Prediction: 0.0

Epoch 2/3:  40%|████      | 1618/4000 [15:31<20:57,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.451974868774414, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.494736194610596, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:  40%|████      | 1619/4000 [15:31<17:08,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.626848220825195, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.938305377960205, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  40%|████      | 1620/4000 [15:31<16:22,  2.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6950531005859375, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.779485702514648, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  41%|████      | 1621/4000 [15:32<19:43,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.525264263153076, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9313292503356934, Predicted Probability: 0.9494, Prediction: 1.0

Epoch 2/3:  41%|████      | 1622/4000 [15:33<23:10,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.455250263214111, Predicted Probability: 0.9885, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.909436225891113, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  41%|████      | 1623/4000 [15:33<20:41,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.088508605957031, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.796202659606934, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  41%|████      | 1624/4000 [15:34<24:51,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.071502208709717, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.363332748413086, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  41%|████      | 1625/4000 [15:35<26:45,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9188265800476074, Predicted Probability: 0.9805, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.748175621032715, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  41%|████      | 1626/4000 [15:35<24:58,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.839527130126953, Predicted Probability: 0.9448, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4333341121673584, Predicted Probability: 0.9687, Prediction: 1.0

Epoch 2/3:  41%|████      | 1627/4000 [15:36<22:03,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.219168663024902, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.865302562713623, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 2/3:  41%|████      | 1628/4000 [15:37<25:11,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.369800090789795, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.298537254333496, Predicted Probability: 0.9866, Prediction: 1.0

Epoch 2/3:  41%|████      | 1629/4000 [15:37<26:28,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5798521041870117, Predicted Probability: 0.9296, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.108720779418945, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 2/3:  41%|████      | 1630/4000 [15:38<25:06,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.224717140197754, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.041943073272705, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  41%|████      | 1631/4000 [15:38<22:56,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.98773193359375, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6914591789245605, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  41%|████      | 1632/4000 [15:39<25:28,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.538799285888672, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.473940849304199, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  41%|████      | 1633/4000 [15:40<23:01,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.92548131942749, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2707120180130005, Predicted Probability: 0.2191, Prediction: 0.0

Epoch 2/3:  41%|████      | 1634/4000 [15:40<24:58,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6577084064483643, Predicted Probability: 0.9345, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.152256965637207, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  41%|████      | 1635/4000 [15:41<26:05,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6056644916534424, Predicted Probability: 0.9312, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.293201446533203, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  41%|████      | 1636/4000 [15:41<22:41,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1507041454315186, Predicted Probability: 0.8957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.243936538696289, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  41%|████      | 1638/4000 [15:42<17:15,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.385959148406982, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0289764404296875, Predicted Probability: 0.9976, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 2.3394551277160645, Predicted Probability: 0.9121, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.071263313293457, Predicted Probability: 0.2552, Prediction: 0.0

Epoch 2/3:  41%|████      | 1639/4000 [15:43<20:29,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.497335433959961, Predicted Probability: 0.9240, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.951539039611816, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  41%|████      | 1640/4000 [15:43<18:43,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.770397186279297, Predicted Probability: 0.9916, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.4232683181762695, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  41%|████      | 1641/4000 [15:44<21:57,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4387726783752441, Predicted Probability: 0.8083, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.344244003295898, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 2/3:  41%|████      | 1642/4000 [15:45<23:49,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.240391254425049, Predicted Probability: 0.0377, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.240274429321289, Predicted Probability: 0.2244, Prediction: 0.0

Epoch 2/3:  41%|████      | 1643/4000 [15:45<26:00,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.6652069091796875, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.764682292938232, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:  41%|████      | 1644/4000 [15:46<27:11,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.198655128479004, Predicted Probability: 0.9852, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.276861190795898, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  41%|████      | 1645/4000 [15:47<27:34,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.795064926147461, Predicted Probability: 0.9424, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.092953681945801, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  41%|████      | 1646/4000 [15:47<23:46,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.186544418334961, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.454891681671143, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  41%|████      | 1647/4000 [15:48<23:42,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.060379981994629, Predicted Probability: 0.9830, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2798404693603516, Predicted Probability: 0.9637, Prediction: 1.0

Epoch 2/3:  41%|████      | 1648/4000 [15:48<21:42,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.670690059661865, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.911799430847168, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  41%|████      | 1649/4000 [15:49<19:36,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.57911205291748, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.371622085571289, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:  41%|████▏     | 1650/4000 [15:49<22:50,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4566450119018555, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.009382724761963, Predicted Probability: 0.9822, Prediction: 1.0

Epoch 2/3:  41%|████▏     | 1651/4000 [15:50<24:33,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8944249153137207, Predicted Probability: 0.2902, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.678675174713135, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  41%|████▏     | 1652/4000 [15:51<25:33,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9150123596191406, Predicted Probability: 0.0196, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8860341310501099, Predicted Probability: 0.2919, Prediction: 0.0

Epoch 2/3:  41%|████▏     | 1654/4000 [15:51<16:32,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.02730941772461, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.682855129241943, Predicted Probability: 0.9995, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.550210952758789, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.675293445587158, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  41%|████▏     | 1655/4000 [15:52<20:31,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.099151611328125, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1474907398223877, Predicted Probability: 0.9588, Prediction: 1.0

Epoch 2/3:  41%|████▏     | 1656/4000 [15:53<22:54,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.763598680496216, Predicted Probability: 0.9407, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.303201675415039, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  41%|████▏     | 1657/4000 [15:54<24:32,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.926573753356934, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6727840900421143, Predicted Probability: 0.9354, Prediction: 1.0

Epoch 2/3:  41%|████▏     | 1658/4000 [15:54<21:30,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6254072189331055, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.865782260894775, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  41%|████▏     | 1659/4000 [15:55<23:41,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0084455013275146, Predicted Probability: 0.0470, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.38731050491333, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1660/4000 [15:55<25:27,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.479742050170898, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1731760501861572, Predicted Probability: 0.0402, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1661/4000 [15:56<26:26,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.399702548980713, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.810611724853516, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1662/4000 [15:56<20:54,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.312307357788086, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.586238861083984, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1663/4000 [15:57<24:07,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7263178825378418, Predicted Probability: 0.6740, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.071024417877197, Predicted Probability: 0.0168, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1664/4000 [15:58<26:03,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.685492992401123, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.035736083984375, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1665/4000 [15:59<27:09,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8067169189453125, Predicted Probability: 0.9430, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.480458736419678, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1666/4000 [15:59<27:52,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.052508354187012, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.015678405761719, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1667/4000 [16:00<28:26,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6458775997161865, Predicted Probability: 0.9746, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.175748825073242, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1668/4000 [16:01<29:51,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1411919593811035, Predicted Probability: 0.0414, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.834066390991211, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1669/4000 [16:02<26:09,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.067099571228027, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.105329513549805, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1670/4000 [16:02<22:53,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.479276657104492, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.900024890899658, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1671/4000 [16:02<22:14,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.123306274414062, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1726198196411133, Predicted Probability: 0.0402, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1672/4000 [16:03<24:04,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.5115275382995605, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.575424671173096, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1673/4000 [16:04<25:18,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.756067156791687, Predicted Probability: 0.8527, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.853148937225342, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1674/4000 [16:05<27:18,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.386198997497559, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.1324300765991211, Predicted Probability: 0.5331, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1675/4000 [16:05<24:26,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.590384483337402, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.988445281982422, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1676/4000 [16:06<23:30,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9238996505737305, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.132993698120117, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1677/4000 [16:06<25:02,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9962849617004395, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.7987518310546875, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1678/4000 [16:07<26:14,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.355010509490967, Predicted Probability: 0.0337, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6095385551452637, Predicted Probability: 0.9736, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1679/4000 [16:08<28:10,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.161881446838379, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.937976837158203, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1680/4000 [16:08<24:06,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.096521854400635, Predicted Probability: 0.0164, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.582093715667725, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1681/4000 [16:09<25:16,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.692094802856445, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9753267765045166, Predicted Probability: 0.8782, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1682/4000 [16:10<21:58,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.888168811798096, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.913023471832275, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1683/4000 [16:10<23:44,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3415682315826416, Predicted Probability: 0.9123, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.327126979827881, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1684/4000 [16:11<25:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2720608711242676, Predicted Probability: 0.0365, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.6397331953048706, Predicted Probability: 0.6547, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1685/4000 [16:11<19:55,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.275338172912598, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.594273567199707, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1686/4000 [16:12<18:18,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.537117004394531, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.253487586975098, Predicted Probability: 0.9860, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1687/4000 [16:12<20:59,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0838377475738525, Predicted Probability: 0.2528, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.791985511779785, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1688/4000 [16:13<23:39,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.40562233328819275, Predicted Probability: 0.6000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.334427356719971, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1689/4000 [16:13<20:59,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.825425624847412, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.143619537353516, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1690/4000 [16:14<19:08,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.594707489013672, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.29971694946289, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1691/4000 [16:14<18:22,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.062002658843994, Predicted Probability: 0.9831, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.083755493164062, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1692/4000 [16:15<21:32,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2568061351776123, Predicted Probability: 0.0371, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.30960750579834, Predicted Probability: 0.0133, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1693/4000 [16:16<24:02,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.404537677764893, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9300795793533325, Predicted Probability: 0.7171, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1694/4000 [16:17<25:29,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.477787494659424, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.832347869873047, Predicted Probability: 0.9788, Prediction: 1.0

Epoch 2/3:  42%|████▏     | 1695/4000 [16:17<22:06,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.883062839508057, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.0449137687683105, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1696/4000 [16:18<22:22,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6711349487304688, Predicted Probability: 0.9353, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9914084672927856, Predicted Probability: 0.1201, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1697/4000 [16:18<20:02,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8127851486206055, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.808864116668701, Predicted Probability: 0.0568, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1698/4000 [16:19<23:14,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.654068470001221, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.116056442260742, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  42%|████▏     | 1699/4000 [16:19<20:26,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.857086181640625, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.778167724609375, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  42%|████▎     | 1700/4000 [16:20<22:48,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.92356014251709, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0840563774108887, Predicted Probability: 0.0438, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1701/4000 [16:20<22:10,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2078423500061035, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.84807014465332, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1702/4000 [16:21<24:28,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.308166027069092, Predicted Probability: 0.9096, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.906599044799805, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1703/4000 [16:22<27:08,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8462018966674805, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.737605094909668, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1704/4000 [16:23<27:40,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.591126441955566, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.384283542633057, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1705/4000 [16:23<24:21,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.995818138122559, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.850294589996338, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1706/4000 [16:24<21:17,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.970919132232666, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1442675590515137, Predicted Probability: 0.0413, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1707/4000 [16:24<23:26,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.100713729858398, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3463220596313477, Predicted Probability: 0.9126, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1708/4000 [16:25<18:49,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5695013999938965, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.626828670501709, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1709/4000 [16:25<21:59,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.607409954071045, Predicted Probability: 0.0687, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.855016708374023, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1710/4000 [16:26<24:15,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.18766975402832, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.241610050201416, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1711/4000 [16:26<21:32,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.611959457397461, Predicted Probability: 0.9316, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.196475505828857, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1712/4000 [16:27<19:20,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.791028022766113, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.079753875732422, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1713/4000 [16:28<21:57,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.747566223144531, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.19895076751709, Predicted Probability: 0.0148, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1714/4000 [16:28<20:35,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.449874401092529, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.169523239135742, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1715/4000 [16:28<18:37,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.348082542419434, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.289328098297119, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1716/4000 [16:29<21:04,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.42270565032959, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4413468837738037, Predicted Probability: 0.9199, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1717/4000 [16:29<18:59,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6835830211639404, Predicted Probability: 0.0245, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.044657707214355, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1718/4000 [16:30<21:42,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8891472816467285, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0092082023620605, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1719/4000 [16:30<17:30,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.823906421661377, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.418740272521973, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1720/4000 [16:31<20:34,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3858120441436768, Predicted Probability: 0.9157, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.869413375854492, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1721/4000 [16:31<16:44,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.65526294708252, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.491312980651855, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1722/4000 [16:32<15:56,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.625079154968262, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.343674182891846, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1723/4000 [16:32<13:31,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.351844787597656, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.097254753112793, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1724/4000 [16:33<18:07,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.660355567932129, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.238675594329834, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1725/4000 [16:33<21:21,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7147746086120605, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.674139976501465, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1726/4000 [16:34<23:51,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9590063095092773, Predicted Probability: 0.8764, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9397783279418945, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1727/4000 [16:35<20:54,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0866780281066895, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.483467102050781, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1728/4000 [16:35<17:01,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.096187591552734, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.731419563293457, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1729/4000 [16:36<20:31,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.343343734741211, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.049222946166992, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1730/4000 [16:36<18:34,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9078471660614014, Predicted Probability: 0.9482, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.436753034591675, Predicted Probability: 0.9688, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1731/4000 [16:37<21:17,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.505756139755249, Predicted Probability: 0.9245, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.032861709594727, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1732/4000 [16:37<19:12,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.960376501083374, Predicted Probability: 0.0492, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.007773399353027, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1733/4000 [16:38<22:13,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4134788513183594, Predicted Probability: 0.1957, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.904269695281982, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1734/4000 [16:38<17:59,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.751027584075928, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.764328002929688, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1735/4000 [16:39<21:04,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7990922927856445, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.421470642089844, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1736/4000 [16:40<23:09,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.809185028076172, Predicted Probability: 0.9783, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.747805595397949, Predicted Probability: 0.0086, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1737/4000 [16:40<24:21,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.351114511489868, Predicted Probability: 0.9130, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6161508560180664, Predicted Probability: 0.9319, Prediction: 1.0

Epoch 2/3:  43%|████▎     | 1738/4000 [16:40<19:29,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.395666122436523, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9349758625030518, Predicted Probability: 0.0505, Prediction: 0.0

Epoch 2/3:  43%|████▎     | 1739/4000 [16:41<22:36,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.366274356842041, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.839033126831055, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  44%|████▎     | 1740/4000 [16:42<20:49,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4982210397720337, Predicted Probability: 0.8173, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.449812889099121, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  44%|████▎     | 1741/4000 [16:42<18:36,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.033783912658691, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.412294387817383, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:  44%|████▎     | 1742/4000 [16:43<21:41,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0656232833862305, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.689835071563721, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  44%|████▎     | 1743/4000 [16:43<18:12,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.441288948059082, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.244672775268555, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  44%|████▎     | 1744/4000 [16:44<22:04,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.841769218444824, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.860665798187256, Predicted Probability: 0.9459, Prediction: 1.0

Epoch 2/3:  44%|████▎     | 1745/4000 [16:45<23:43,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6838247776031494, Predicted Probability: 0.8434, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.211198806762695, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  44%|████▎     | 1746/4000 [16:45<25:34,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.888410568237305, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3538224697113037, Predicted Probability: 0.0338, Prediction: 0.0

Epoch 2/3:  44%|████▎     | 1747/4000 [16:46<23:58,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.049797058105469, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.375282049179077, Predicted Probability: 0.0851, Prediction: 0.0

Epoch 2/3:  44%|████▎     | 1748/4000 [16:46<21:52,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.296903133392334, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.688750267028809, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  44%|████▎     | 1749/4000 [16:47<19:31,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.4004950523376465, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.19026517868042, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1750/4000 [16:47<19:37,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4054737091064453, Predicted Probability: 0.9679, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.963039875030518, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1751/4000 [16:48<22:15,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5840609073638916, Predicted Probability: 0.1702, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.17365837097168, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1752/4000 [16:49<23:47,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.427676677703857, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.3509016036987305, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1753/4000 [16:49<22:59,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.338059425354004, Predicted Probability: 0.9871, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.685017108917236, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1754/4000 [16:50<20:35,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.732497453689575, Predicted Probability: 0.9389, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.21742057800293, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1755/4000 [16:50<18:35,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.299553394317627, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.356006622314453, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1756/4000 [16:51<19:14,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.285192012786865, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.745283126831055, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1757/4000 [16:51<17:32,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.161775588989258, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.169870376586914, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1758/4000 [16:52<18:15,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.014364719390869, Predicted Probability: 0.9823, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.639008522033691, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1759/4000 [16:52<19:34,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.544427871704102, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.07381534576416, Predicted Probability: 0.9558, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1760/4000 [16:53<21:51,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.871886253356934, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.596334218978882, Predicted Probability: 0.9306, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1761/4000 [16:54<23:53,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.114684104919434, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.191967010498047, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1762/4000 [16:55<25:01,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8099143505096436, Predicted Probability: 0.0568, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.090468406677246, Predicted Probability: 0.0165, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1763/4000 [16:55<25:32,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9368212223052979, Predicted Probability: 0.2815, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5033278465270996, Predicted Probability: 0.9244, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1764/4000 [16:56<22:10,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.591772079467773, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.424373626708984, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1765/4000 [16:56<23:45,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.186319351196289, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2369184494018555, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1766/4000 [16:57<28:38,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.698306083679199, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1851532459259033, Predicted Probability: 0.0397, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1767/4000 [16:58<24:04,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9181082248687744, Predicted Probability: 0.0195, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.28646981716156006, Predicted Probability: 0.5711, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1768/4000 [16:58<20:52,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.275392532348633, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9176132678985596, Predicted Probability: 0.2854, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1769/4000 [16:59<18:37,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.424217700958252, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.461063861846924, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1770/4000 [16:59<17:29,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.903115272521973, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.736528396606445, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1771/4000 [17:00<20:39,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.912866115570068, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.629002332687378, Predicted Probability: 0.9327, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1772/4000 [17:00<22:43,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9974398612976074, Predicted Probability: 0.9820, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.113329887390137, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1773/4000 [17:01<24:30,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7011609077453613, Predicted Probability: 0.9371, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.755402565002441, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1774/4000 [17:02<21:13,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.257655143737793, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.008247375488281, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1775/4000 [17:02<19:02,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.4306797981262207, Predicted Probability: 0.9191, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.521109580993652, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  44%|████▍     | 1776/4000 [17:03<21:26,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6495163440704346, Predicted Probability: 0.9340, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.206133842468262, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1777/4000 [17:03<17:15,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.256162166595459, Predicted Probability: 0.9860, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.4222331047058105, Predicted Probability: 0.0119, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1778/4000 [17:04<20:23,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4790828227996826, Predicted Probability: 0.9701, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6620869636535645, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1779/4000 [17:04<22:21,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3609998226165771, Predicted Probability: 0.7959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.906691551208496, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  44%|████▍     | 1780/4000 [17:05<19:45,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3013458251953125, Predicted Probability: 0.9645, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.424312114715576, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1781/4000 [17:05<18:36,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6440320014953613, Predicted Probability: 0.0255, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.773987293243408, Predicted Probability: 0.9413, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1782/4000 [17:05<15:18,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.827343463897705, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.943266868591309, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1783/4000 [17:06<14:54,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.322049140930176, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.677071571350098, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1784/4000 [17:06<12:45,  2.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.55945873260498, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.496437072753906, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1785/4000 [17:07<17:54,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.644131660461426, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.289931297302246, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1786/4000 [17:07<16:35,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.3462815284729, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.567376613616943, Predicted Probability: 0.9897, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1787/4000 [17:08<19:51,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6318985223770142, Predicted Probability: 0.1636, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.10699462890625, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  45%|████▍     | 1788/4000 [17:08<18:52,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.605008125305176, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.391265869140625, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1789/4000 [17:09<15:29,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8630623817443848, Predicted Probability: 0.0540, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.9772170186042786, Predicted Probability: 0.2734, Prediction: 0.0

Epoch 2/3:  45%|████▍     | 1790/4000 [17:09<19:25,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.359602928161621, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.648195505142212, Predicted Probability: 0.9746, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1791/4000 [17:10<22:32,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.071003913879395, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.301687240600586, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  45%|████▍     | 1792/4000 [17:11<20:47,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.743442535400391, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.698982238769531, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1793/4000 [17:11<17:31,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.418463706970215, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.339273929595947, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1794/4000 [17:11<18:07,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.123264312744141, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.683807849884033, Predicted Probability: 0.0639, Prediction: 0.0

Epoch 2/3:  45%|████▍     | 1795/4000 [17:12<17:41,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.209799766540527, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.115787506103516, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  45%|████▍     | 1796/4000 [17:12<16:29,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.283493041992188, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.54246187210083, Predicted Probability: 0.9895, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1797/4000 [17:13<19:48,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.611878871917725, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.052420616149902, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 2/3:  45%|████▍     | 1798/4000 [17:14<22:05,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6657893657684326, Predicted Probability: 0.3394, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.620465278625488, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 2/3:  45%|████▍     | 1799/4000 [17:14<19:49,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.509058952331543, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.979265213012695, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1800/4000 [17:15<19:49,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.344277858734131, Predicted Probability: 0.9659, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.120189189910889, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1801/4000 [17:15<22:25,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.899066209793091, Predicted Probability: 0.9478, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.538211822509766, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1802/4000 [17:16<20:36,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.446005821228027, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7717394828796387, Predicted Probability: 0.9411, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1803/4000 [17:16<21:05,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.826913833618164, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1016945838928223, Predicted Probability: 0.9570, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1804/4000 [17:17<22:45,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8312296867370605, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8966684341430664, Predicted Probability: 0.7103, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1805/4000 [17:17<18:15,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.365429878234863, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.373940467834473, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1806/4000 [17:18<15:01,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.316324234008789, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.184584617614746, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1807/4000 [17:18<18:27,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.223663330078125, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6188294887542725, Predicted Probability: 0.9321, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1808/4000 [17:19<18:58,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.737548351287842, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.261191368103027, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1809/4000 [17:20<21:46,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.46129035949707, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8104259967803955, Predicted Probability: 0.9432, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1810/4000 [17:20<19:30,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.043352127075195, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.080677032470703, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1811/4000 [17:21<21:56,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.03463077545166, Predicted Probability: 0.8844, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.885066509246826, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1812/4000 [17:21<19:37,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.06811809539795, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.643867492675781, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1813/4000 [17:22<21:56,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.347692489624023, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.178044080734253, Predicted Probability: 0.8983, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1814/4000 [17:22<19:25,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.983131408691406, Predicted Probability: 0.9932, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.758312702178955, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1815/4000 [17:23<17:52,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.176443099975586, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.642279148101807, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  45%|████▌     | 1816/4000 [17:23<20:31,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7303402423858643, Predicted Probability: 0.9388, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.43055534362793, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1817/4000 [17:24<18:23,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.073514938354492, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8666069507598877, Predicted Probability: 0.0205, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1818/4000 [17:25<21:40,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.909561634063721, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.130963325500488, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  45%|████▌     | 1819/4000 [17:25<17:29,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.921914100646973, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.000665187835693, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1820/4000 [17:25<16:27,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.570559978485107, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.255592346191406, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1821/4000 [17:26<19:20,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.232402801513672, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5603456497192383, Predicted Probability: 0.1736, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1822/4000 [17:26<17:32,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.6541337966918945, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.643949508666992, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1823/4000 [17:27<20:48,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.29011058807373, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.228640079498291, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1824/4000 [17:28<19:19,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8753883838653564, Predicted Probability: 0.9466, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6536223888397217, Predicted Probability: 0.9748, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1825/4000 [17:28<22:04,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.673492431640625, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.505024433135986, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1826/4000 [17:29<23:27,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.550593376159668, Predicted Probability: 0.9895, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.001232147216797, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1827/4000 [17:30<24:26,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.284200668334961, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6801226139068604, Predicted Probability: 0.9358, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1828/4000 [17:30<24:46,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.404422283172607, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.078019380569458, Predicted Probability: 0.9560, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1829/4000 [17:31<25:30,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.562476396560669, Predicted Probability: 0.1733, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.484086036682129, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1830/4000 [17:32<25:52,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.659360408782959, Predicted Probability: 0.9906, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.613731384277344, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1831/4000 [17:32<22:10,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.9070403575897217, Predicted Probability: 0.2876, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.3795804977417, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1832/4000 [17:33<24:01,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.117834091186523, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.902623176574707, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1833/4000 [17:34<25:23,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.436079978942871, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.076118469238281, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1834/4000 [17:35<26:28,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.091232776641846, Predicted Probability: 0.9836, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.459989547729492, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1835/4000 [17:35<26:25,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.044576644897461, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7964975833892822, Predicted Probability: 0.1423, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1836/4000 [17:36<22:23,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.333741188049316, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.731039047241211, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1837/4000 [17:36<19:55,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.911062240600586, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.264103412628174, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1838/4000 [17:37<21:57,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4679179191589355, Predicted Probability: 0.9887, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.75331449508667, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1839/4000 [17:38<23:30,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4773640632629395, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.884389877319336, Predicted Probability: 0.8681, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1840/4000 [17:38<24:12,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.14639949798584, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.192909836769104, Predicted Probability: 0.2327, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1841/4000 [17:39<22:02,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4375176429748535, Predicted Probability: 0.9196, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6696083545684814, Predicted Probability: 0.6614, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1842/4000 [17:39<19:25,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5729942321777344, Predicted Probability: 0.0273, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.728800773620605, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1843/4000 [17:39<15:46,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.537790298461914, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.684196949005127, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1844/4000 [17:40<15:11,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.953531742095947, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.776264190673828, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1845/4000 [17:41<18:28,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.235542297363281, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4879844188690186, Predicted Probability: 0.9233, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1846/4000 [17:41<20:51,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9970245361328125, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.680122375488281, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 2/3:  46%|████▌     | 1847/4000 [17:42<18:33,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.650993824005127, Predicted Probability: 0.0253, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.331581115722656, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1848/4000 [17:42<20:46,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7991766929626465, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.309231996536255, Predicted Probability: 0.9096, Prediction: 1.0

Epoch 2/3:  46%|████▌     | 1849/4000 [17:43<18:26,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.467122077941895, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.229000568389893, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  46%|████▋     | 1850/4000 [17:43<18:29,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.051856517791748, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1610260009765625, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 2/3:  46%|████▋     | 1851/4000 [17:44<15:55,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.622056007385254, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.699556827545166, Predicted Probability: 0.6681, Prediction: 1.0

Epoch 2/3:  46%|████▋     | 1852/4000 [17:44<19:44,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.76485013961792, Predicted Probability: 0.0226, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.633399486541748, Predicted Probability: 0.9330, Prediction: 1.0

Epoch 2/3:  46%|████▋     | 1853/4000 [17:45<21:49,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2136640548706055, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.38793659210205, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  46%|████▋     | 1854/4000 [17:46<21:54,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.958183765411377, Predicted Probability: 0.0187, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2271599769592285, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 2/3:  46%|████▋     | 1855/4000 [17:47<23:50,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.391319751739502, Predicted Probability: 0.0326, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9357373714447021, Predicted Probability: 0.7182, Prediction: 1.0

Epoch 2/3:  46%|████▋     | 1856/4000 [17:47<25:34,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.382167816162109, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.544114112854004, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 2/3:  46%|████▋     | 1857/4000 [17:48<26:08,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.213934421539307, Predicted Probability: 0.9946, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.496378183364868, Predicted Probability: 0.0294, Prediction: 0.0

Epoch 2/3:  46%|████▋     | 1858/4000 [17:49<26:04,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.174644470214844, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9392977952957153, Predicted Probability: 0.2810, Prediction: 0.0

Epoch 2/3:  46%|████▋     | 1859/4000 [17:50<26:33,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.733350992202759, Predicted Probability: 0.9766, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.459225654602051, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  46%|████▋     | 1860/4000 [17:50<20:47,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.35802161693573, Predicted Probability: 0.2046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.418609619140625, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1861/4000 [17:51<23:03,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.2491189241409302, Predicted Probability: 0.7771, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.166947364807129, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1862/4000 [17:51<20:20,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.365767002105713, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.055819272994995, Predicted Probability: 0.9550, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1863/4000 [17:52<22:20,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.48217487335205, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.974553108215332, Predicted Probability: 0.9931, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1864/4000 [17:52<20:31,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.624062538146973, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.212685585021973, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1865/4000 [17:53<17:16,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.843838691711426, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.468638896942139, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1866/4000 [17:53<19:35,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.615173816680908, Predicted Probability: 0.9318, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.892175197601318, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1867/4000 [17:54<19:37,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.25049281120300293, Predicted Probability: 0.5623, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.529510974884033, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1868/4000 [17:55<21:34,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8149919509887695, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.958810567855835, Predicted Probability: 0.0187, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1869/4000 [17:55<19:48,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.518529415130615, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.490895748138428, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1871/4000 [17:56<17:16,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8902744054794312, Predicted Probability: 0.1312, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.343782424926758, Predicted Probability: 0.0002, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.004099369049072, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.615546226501465, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1872/4000 [17:56<14:12,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.958497047424316, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.149255752563477, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1873/4000 [17:57<15:34,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.549318313598633, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1228976249694824, Predicted Probability: 0.9578, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1875/4000 [17:57<12:57,  2.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.091956615447998, Predicted Probability: 0.9836, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.990018844604492, Predicted Probability: 0.9991, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -5.862479209899902, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.744820594787598, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1876/4000 [17:58<16:59,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.310306549072266, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.642384648323059, Predicted Probability: 0.1621, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1877/4000 [17:59<17:33,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.630019187927246, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3919177055358887, Predicted Probability: 0.9675, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1878/4000 [17:59<20:08,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.01682710647583, Predicted Probability: 0.9823, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.917402267456055, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1879/4000 [18:00<20:38,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5639299154281616, Predicted Probability: 0.1731, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.694457054138184, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1880/4000 [18:00<18:34,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.738412380218506, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.032415390014648, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1881/4000 [18:01<15:15,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.720120429992676, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.86501932144165, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1882/4000 [18:01<12:51,  2.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.456188678741455, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.675558090209961, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1883/4000 [18:01<16:38,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.266413688659668, Predicted Probability: 0.7801, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.9874749183654785, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1885/4000 [18:02<13:13,  2.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.332192420959473, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.780808925628662, Predicted Probability: 0.9996, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.615092277526855, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.911681175231934, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1886/4000 [18:03<18:03,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.871054172515869, Predicted Probability: 0.0536, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.23005199432373, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1887/4000 [18:03<16:28,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.670016765594482, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.002867221832275, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1888/4000 [18:03<13:51,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.23309326171875, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.574068069458008, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1889/4000 [18:04<17:28,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3700740337371826, Predicted Probability: 0.9668, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.025813102722168, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1890/4000 [18:05<16:04,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.292105197906494, Predicted Probability: 0.0135, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.325912475585938, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1891/4000 [18:05<19:45,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.157368659973145, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.67429780960083, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1892/4000 [18:06<18:29,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.441455841064453, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.987290382385254, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1893/4000 [18:06<17:01,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.515875816345215, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.994465827941895, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1894/4000 [18:07<19:44,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5658624172210693, Predicted Probability: 0.9725, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.869824409484863, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1895/4000 [18:08<21:50,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1734821796417236, Predicted Probability: 0.8978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.576042175292969, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1896/4000 [18:08<19:10,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.516868591308594, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.382549285888672, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  47%|████▋     | 1897/4000 [18:09<22:06,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.056869506835938, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.214717864990234, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1898/4000 [18:10<23:12,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9104009866714478, Predicted Probability: 0.8711, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.388835906982422, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  47%|████▋     | 1899/4000 [18:10<24:02,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.355903625488281, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8137569427490234, Predicted Probability: 0.9434, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1900/4000 [18:11<18:57,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.708543062210083, Predicted Probability: 0.0239, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.010821342468262, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1901/4000 [18:11<17:17,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.0165791511535645, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.533829689025879, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1902/4000 [18:12<19:45,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.789066791534424, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4440016746521, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1903/4000 [18:12<22:09,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.757505416870117, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8584606647491455, Predicted Probability: 0.9793, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1904/4000 [18:13<23:17,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.029452800750732, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8657313585281372, Predicted Probability: 0.7039, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1905/4000 [18:14<22:08,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.765556335449219, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0040080547332764, Predicted Probability: 0.0472, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1906/4000 [18:14<19:19,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.407844066619873, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8725740909576416, Predicted Probability: 0.9796, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1907/4000 [18:14<15:38,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.075288772583008, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.366582870483398, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1908/4000 [18:15<13:05,  2.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.130230903625488, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -3.15380859375, Predicted Probability: 0.0409, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1909/4000 [18:15<12:55,  2.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.813241004943848, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.517775058746338, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1910/4000 [18:16<17:18,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.09499740600586, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.400396347045898, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1911/4000 [18:16<15:53,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6952080726623535, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.573779106140137, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1912/4000 [18:17<19:15,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.509450674057007, Predicted Probability: 0.9248, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.407711982727051, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1913/4000 [18:18<21:47,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.178217887878418, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9868268966674805, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1914/4000 [18:19<24:12,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.497776031494141, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6644206047058105, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1915/4000 [18:19<25:06,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6029998064041138, Predicted Probability: 0.1676, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.630527019500732, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1916/4000 [18:20<25:48,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.276281356811523, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8911428451538086, Predicted Probability: 0.0526, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1917/4000 [18:21<25:40,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2731587886810303, Predicted Probability: 0.9066, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.091087341308594, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1919/4000 [18:22<20:03,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.824097156524658, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6706392765045166, Predicted Probability: 0.8417, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -0.5435514450073242, Predicted Probability: 0.3674, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.015528678894043, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1920/4000 [18:23<22:00,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2476913928985596, Predicted Probability: 0.9045, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.012264251708984, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1921/4000 [18:23<24:39,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.702516078948975, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.277099132537842, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1922/4000 [18:24<21:18,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 5.456688404083252, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.860401153564453, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1923/4000 [18:25<22:37,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.90863561630249, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0883398056030273, Predicted Probability: 0.1102, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1924/4000 [18:25<17:57,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.742462158203125, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.437838077545166, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1925/4000 [18:25<16:32,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.413844108581543, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.324244976043701, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1926/4000 [18:26<19:20,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.396415710449219, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.715522050857544, Predicted Probability: 0.9762, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1927/4000 [18:26<17:23,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.170198440551758, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.461020469665527, Predicted Probability: 0.0114, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1928/4000 [18:27<19:36,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.703690528869629, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1681764125823975, Predicted Probability: 0.8974, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1929/4000 [18:27<15:54,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.144144058227539, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.304869651794434, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1930/4000 [18:28<15:07,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.275374889373779, Predicted Probability: 0.9863, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.483014106750488, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1931/4000 [18:28<14:32,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.694489479064941, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.380221366882324, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1932/4000 [18:28<14:46,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.358458995819092, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.142774820327759, Predicted Probability: 0.8950, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1933/4000 [18:29<18:06,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.952129364013672, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9931973218917847, Predicted Probability: 0.1199, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1934/4000 [18:30<20:39,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.834805488586426, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3817317485809326, Predicted Probability: 0.9154, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1935/4000 [18:31<22:45,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.313839912414551, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.089928150177002, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1936/4000 [18:31<19:46,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6058902740478516, Predicted Probability: 0.0688, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.036487102508545, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1937/4000 [18:32<19:23,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.872054576873779, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2054812908172607, Predicted Probability: 0.9610, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1938/4000 [18:32<19:07,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.772592067718506, Predicted Probability: 0.9412, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.724729299545288, Predicted Probability: 0.9764, Prediction: 1.0

Epoch 2/3:  48%|████▊     | 1939/4000 [18:33<21:28,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.209806442260742, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.304841995239258, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  48%|████▊     | 1940/4000 [18:34<22:55,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1158369779586792, Predicted Probability: 0.2468, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8863129615783691, Predicted Probability: 0.8683, Prediction: 1.0

Epoch 2/3:  49%|████▊     | 1941/4000 [18:35<24:38,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.102773189544678, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.9619574546813965, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  49%|████▊     | 1942/4000 [18:35<21:09,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.69502067565918, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.829215049743652, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  49%|████▊     | 1943/4000 [18:36<22:15,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9708083868026733, Predicted Probability: 0.8777, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.252992630004883, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  49%|████▊     | 1944/4000 [18:36<23:28,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.765842437744141, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.287307739257812, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  49%|████▊     | 1945/4000 [18:37<23:58,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.911151885986328, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.61382532119751, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 2/3:  49%|████▊     | 1946/4000 [18:38<20:34,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.313364267349243, Predicted Probability: 0.9100, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.221673965454102, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  49%|████▊     | 1947/4000 [18:38<23:22,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6319446563720703, Predicted Probability: 0.0258, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.52646541595459, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  49%|████▊     | 1948/4000 [18:39<23:50,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.22416877746582, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8216149806976318, Predicted Probability: 0.8608, Prediction: 1.0

Epoch 2/3:  49%|████▊     | 1949/4000 [18:40<25:04,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.97861647605896, Predicted Probability: 0.0184, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8899688720703125, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1950/4000 [18:41<25:12,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1495695114135742, Predicted Probability: 0.2406, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.897712707519531, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1951/4000 [18:41<24:10,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.442293167114258, Predicted Probability: 0.9690, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.744226932525635, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1952/4000 [18:42<24:31,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.16741943359375, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.095139980316162, Predicted Probability: 0.8904, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1953/4000 [18:43<25:02,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.144319534301758, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.633622407913208, Predicted Probability: 0.8367, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1954/4000 [18:44<24:56,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.16153621673584, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0384492874145508, Predicted Probability: 0.7386, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1955/4000 [18:44<25:05,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.930908203125, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2580790519714355, Predicted Probability: 0.9630, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1956/4000 [18:45<21:22,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9542765617370605, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.682586669921875, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1957/4000 [18:45<18:46,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5473783016204834, Predicted Probability: 0.9274, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.039811611175537, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1958/4000 [18:46<21:39,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9240846633911133, Predicted Probability: 0.9806, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.4606194496154785, Predicted Probability: 0.0042, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1959/4000 [18:47<22:51,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.618191719055176, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6800851821899414, Predicted Probability: 0.0246, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1960/4000 [18:47<18:03,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.775070667266846, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.997529983520508, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1961/4000 [18:48<20:57,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.30288028717041, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.228599548339844, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1962/4000 [18:48<17:27,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.68381404876709, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.449472427368164, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1963/4000 [18:49<19:34,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.470108985900879, Predicted Probability: 0.9220, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.64426851272583, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1964/4000 [18:49<21:19,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.667590141296387, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.926024913787842, Predicted Probability: 0.9807, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1965/4000 [18:50<22:56,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.480550289154053, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.98790168762207, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1966/4000 [18:51<23:24,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.204547882080078, Predicted Probability: 0.9853, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.21253776550293, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1967/4000 [18:52<25:35,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.285602569580078, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.772128105163574, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1968/4000 [18:52<20:00,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.965385913848877, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.290994644165039, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1969/4000 [18:53<21:51,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.274266719818115, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.503469944000244, Predicted Probability: 0.9244, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1970/4000 [18:54<22:48,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.874113082885742, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.376484394073486, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1971/4000 [18:54<22:01,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8213155269622803, Predicted Probability: 0.9438, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.139550685882568, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1972/4000 [18:55<19:15,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.230623722076416, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.501282691955566, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1973/4000 [18:55<18:04,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.506118297576904, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.44873046875, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1974/4000 [18:55<16:38,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.56982946395874, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2365939617156982, Predicted Probability: 0.9622, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1975/4000 [18:56<19:05,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7852766513824463, Predicted Probability: 0.8563, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.993280410766602, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1976/4000 [18:57<17:11,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.553525924682617, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.141197204589844, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1977/4000 [18:57<15:45,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.485096454620361, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.789864540100098, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  49%|████▉     | 1978/4000 [18:57<14:41,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.637642860412598, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6325836181640625, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  49%|████▉     | 1979/4000 [18:58<16:30,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.435589790344238, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.513706684112549, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1980/4000 [18:59<19:15,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.30900728702545166, Predicted Probability: 0.4234, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.01257610321045, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1981/4000 [18:59<17:15,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.459737300872803, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.971843242645264, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1982/4000 [19:00<19:31,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.965340614318848, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.081094264984131, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1983/4000 [19:00<17:26,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.580782413482666, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.581284523010254, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1984/4000 [19:01<17:37,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.665566444396973, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.567721128463745, Predicted Probability: 0.9726, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1985/4000 [19:01<15:06,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.771313667297363, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.372661590576172, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1986/4000 [19:01<15:01,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.392524719238281, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.206502437591553, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1987/4000 [19:02<18:16,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8461813926696777, Predicted Probability: 0.9791, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.681154251098633, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1988/4000 [19:02<14:50,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.3661274909973145, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.027752876281738, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1989/4000 [19:03<14:05,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.999664783477783, Predicted Probability: 0.9526, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.351841926574707, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1990/4000 [19:03<15:17,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1684374809265137, Predicted Probability: 0.8974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.262021780014038, Predicted Probability: 0.0943, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1991/4000 [19:04<16:09,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0563547611236572, Predicted Probability: 0.0449, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.559464454650879, Predicted Probability: 0.9896, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1992/4000 [19:04<16:50,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.268205165863037, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.392725706100464, Predicted Probability: 0.9675, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1993/4000 [19:05<19:28,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.544492244720459, Predicted Probability: 0.9272, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.754596710205078, Predicted Probability: 0.0598, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1994/4000 [19:06<17:22,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.698596000671387, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.986874580383301, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1995/4000 [19:06<19:38,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.060629844665527, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.685730934143066, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 2/3:  50%|████▉     | 1996/4000 [19:07<17:45,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7999119758605957, Predicted Probability: 0.8581, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.211892127990723, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1997/4000 [19:07<19:54,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.880748748779297, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6407655477523804, Predicted Probability: 0.3451, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1998/4000 [19:08<22:36,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.869375228881836, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.524101257324219, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  50%|████▉     | 1999/4000 [19:09<23:46,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.5626220703125, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.3134126663208, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2000/4000 [19:10<24:30,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.394516468048096, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.184102058410645, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2001/4000 [19:11<24:22,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.420370578765869, Predicted Probability: 0.9184, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.22177267074585, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2002/4000 [19:11<25:02,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.699079513549805, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6684737801551819, Predicted Probability: 0.3388, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2003/4000 [19:12<24:46,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1847081184387207, Predicted Probability: 0.8989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.37484073638916, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2004/4000 [19:12<21:07,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.1878180503845215, Predicted Probability: 0.9850, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.620644569396973, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2005/4000 [19:13<18:30,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.835761070251465, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8163981437683105, Predicted Probability: 0.9785, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2006/4000 [19:13<17:34,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.554252624511719, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.3411970138549805, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2007/4000 [19:14<16:52,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.122967720031738, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.124546527862549, Predicted Probability: 0.9841, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2008/4000 [19:14<15:34,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.08965015411377, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7411532402038574, Predicted Probability: 0.0606, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2009/4000 [19:15<16:10,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.644733428955078, Predicted Probability: 0.9745, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.039746284484863, Predicted Probability: 0.9827, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2010/4000 [19:15<18:59,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.709588885307312, Predicted Probability: 0.1532, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.314056396484375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2011/4000 [19:16<16:59,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.352287530899048, Predicted Probability: 0.0869, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0146002769470215, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2012/4000 [19:17<19:27,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.416481018066406, Predicted Probability: 0.0119, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.05106520652771, Predicted Probability: 0.8861, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2014/4000 [19:17<15:17,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9392380714416504, Predicted Probability: 0.9498, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.393756866455078, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -3.951451539993286, Predicted Probability: 0.0189, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.417007446289062, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2015/4000 [19:18<18:24,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.18820858001709, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6893569231033325, Predicted Probability: 0.8441, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2016/4000 [19:19<20:16,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.371068477630615, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.631376266479492, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2017/4000 [19:20<22:09,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.802894592285156, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.2399396896362305, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2018/4000 [19:20<23:12,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.450571298599243, Predicted Probability: 0.9206, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.199843406677246, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  50%|█████     | 2019/4000 [19:21<19:47,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.99910306930542, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.201786994934082, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  50%|█████     | 2020/4000 [19:21<19:15,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.894477367401123, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.964597225189209, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2021/4000 [19:22<20:37,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.036701202392578, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.548288345336914, Predicted Probability: 0.9720, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2022/4000 [19:23<21:45,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.4944257736206055, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5945863723754883, Predicted Probability: 0.0267, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2023/4000 [19:23<20:43,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.1903884410858154, Predicted Probability: 0.1006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.427596092224121, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2024/4000 [19:24<19:50,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.003454685211182, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9975545406341553, Predicted Probability: 0.9525, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2025/4000 [19:25<21:23,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2085814476013184, Predicted Probability: 0.0388, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.415018558502197, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2026/4000 [19:25<18:51,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.5148797035217285, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.544515132904053, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2027/4000 [19:25<16:53,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.627689838409424, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.264339923858643, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2028/4000 [19:26<17:13,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.354100704193115, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.831872940063477, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2029/4000 [19:27<17:56,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0785882472991943, Predicted Probability: 0.9560, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.652792453765869, Predicted Probability: 0.9747, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2030/4000 [19:27<14:33,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.997451782226562, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.264276504516602, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2031/4000 [19:28<18:12,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.422793865203857, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.093962669372559, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2032/4000 [19:28<18:50,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.594440460205078, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2675232887268066, Predicted Probability: 0.0367, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2033/4000 [19:29<20:30,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.216812133789062, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.42868733406066895, Predicted Probability: 0.6056, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.122099876403809, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.045981407165527, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2035/4000 [19:30<16:50,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.951727867126465, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.625090599060059, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2036/4000 [19:30<18:49,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.328634023666382, Predicted Probability: 0.9112, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.208472728729248, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2037/4000 [19:31<20:51,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.542938709259033, Predicted Probability: 0.0105, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.4764204025268555, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2038/4000 [19:32<18:18,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.027716159820557, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.442004203796387, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2039/4000 [19:32<18:04,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.553857326507568, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.56014347076416, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2041/4000 [19:33<13:31,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.15843391418457, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.9482340812683105, Predicted Probability: 0.0004, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.894521713256836, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.17108789086341858, Predicted Probability: 0.4573, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2042/4000 [19:34<17:36,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6242473125457764, Predicted Probability: 0.8354, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.159562587738037, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2043/4000 [19:34<19:10,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.730539798736572, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7351417541503906, Predicted Probability: 0.9391, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2044/4000 [19:35<18:41,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.358040809631348, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.913408041000366, Predicted Probability: 0.9804, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2045/4000 [19:36<20:15,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.567352771759033, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.2318806648254395, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2046/4000 [19:36<22:44,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.220613479614258, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.140030860900879, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  51%|█████     | 2047/4000 [19:37<17:56,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.795602798461914, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.928923606872559, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2048/4000 [19:37<19:34,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5742697715759277, Predicted Probability: 0.0273, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4386935234069824, Predicted Probability: 0.9197, Prediction: 1.0

Epoch 2/3:  51%|█████     | 2049/4000 [19:38<21:13,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.316851615905762, Predicted Probability: 0.9868, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.570855617523193, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  51%|█████▏    | 2050/4000 [19:39<18:37,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.149188995361328, Predicted Probability: 0.0155, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.472059726715088, Predicted Probability: 0.0301, Prediction: 0.0

Epoch 2/3:  51%|█████▏    | 2051/4000 [19:39<20:13,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.830407619476318, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.726628065109253, Predicted Probability: 0.0235, Prediction: 0.0

Epoch 2/3:  51%|█████▏    | 2052/4000 [19:40<21:37,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5286552906036377, Predicted Probability: 0.9715, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.463979721069336, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  51%|█████▏    | 2053/4000 [19:41<22:49,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.28572416305542, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.923748254776001, Predicted Probability: 0.9490, Prediction: 1.0

Epoch 2/3:  51%|█████▏    | 2054/4000 [19:41<19:37,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.618138313293457, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.117471694946289, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  51%|█████▏    | 2055/4000 [19:42<21:18,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2850441932678223, Predicted Probability: 0.0361, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.698021411895752, Predicted Probability: 0.0242, Prediction: 0.0

Epoch 2/3:  51%|█████▏    | 2056/4000 [19:43<21:46,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.679229497909546, Predicted Probability: 0.9358, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2797775268554688, Predicted Probability: 0.9072, Prediction: 1.0

Epoch 2/3:  51%|█████▏    | 2057/4000 [19:43<17:17,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.294764518737793, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.489703178405762, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  51%|█████▏    | 2059/4000 [19:44<15:28,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.188453435897827, Predicted Probability: 0.8992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.988218307495117, Predicted Probability: 0.0025, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.938091278076172, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1584277153015137, Predicted Probability: 0.2390, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2060/4000 [19:45<18:03,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5030581951141357, Predicted Probability: 0.1820, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.706971645355225, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2061/4000 [19:45<19:53,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.32046127319336, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.382481336593628, Predicted Probability: 0.9155, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2062/4000 [19:46<17:40,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.89292573928833, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.034087181091309, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2063/4000 [19:46<16:09,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.326179504394531, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.435162544250488, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2064/4000 [19:47<15:43,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.868284225463867, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.012519836425781, Predicted Probability: 0.9822, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2065/4000 [19:47<18:13,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.319525718688965, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8345584869384766, Predicted Probability: 0.0212, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2066/4000 [19:48<20:09,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.2288312911987305, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1889331340789795, Predicted Probability: 0.7666, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2067/4000 [19:49<21:16,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4346749782562256, Predicted Probability: 0.9194, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8260903358459473, Predicted Probability: 0.0559, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2068/4000 [19:50<22:44,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.569523334503174, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.202149391174316, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2069/4000 [19:50<23:20,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.246383666992188, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.4083608388900757, Predicted Probability: 0.1965, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2070/4000 [19:51<19:51,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7417047023773193, Predicted Probability: 0.8509, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5379388332366943, Predicted Probability: 0.9717, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2071/4000 [19:51<19:03,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4157586097717285, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7802748680114746, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2072/4000 [19:52<20:26,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.22045373916626, Predicted Probability: 0.9855, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.939130783081055, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2073/4000 [19:52<17:54,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.682651996612549, Predicted Probability: 0.9755, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.648241996765137, Predicted Probability: 0.9905, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2074/4000 [19:53<17:50,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.581026554107666, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.78678035736084, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2075/4000 [19:54<19:56,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.63469409942627, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.397831439971924, Predicted Probability: 0.9167, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2076/4000 [19:54<21:19,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.158354759216309, Predicted Probability: 0.9846, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.991523265838623, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2077/4000 [19:55<22:15,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.330378293991089, Predicted Probability: 0.0345, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3788299560546875, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2078/4000 [19:56<22:37,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.794663429260254, Predicted Probability: 0.9918, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.938241958618164, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2079/4000 [19:56<17:49,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.745224952697754, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.33798885345459, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2081/4000 [19:57<13:02,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.578940391540527, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.426786422729492, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.2364501953125, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.446932792663574, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2082/4000 [19:57<14:15,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2830471992492676, Predicted Probability: 0.9638, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.534547328948975, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2083/4000 [19:58<18:21,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4647369384765625, Predicted Probability: 0.9216, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.677872657775879, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2084/4000 [19:59<16:28,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.316743850708008, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.307971954345703, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2085/4000 [19:59<18:13,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.865928649902344, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0876457691192627, Predicted Probability: 0.9564, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2086/4000 [20:00<19:57,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.413818836212158, Predicted Probability: 0.0319, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.208150863647461, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2087/4000 [20:01<21:24,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.138694763183594, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8396894931793213, Predicted Probability: 0.9448, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2088/4000 [20:02<21:57,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.7635016441345215, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7996196746826172, Predicted Probability: 0.3101, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2089/4000 [20:02<22:19,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.268638610839844, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.597215175628662, Predicted Probability: 0.9307, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2090/4000 [20:03<22:48,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.511049270629883, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.519639015197754, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2091/4000 [20:04<23:00,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1596312522888184, Predicted Probability: 0.8966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.28518009185791, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2093/4000 [20:05<18:01,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.973263740539551, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6012008190155029, Predicted Probability: 0.3541, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.23785400390625, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.575567722320557, Predicted Probability: 0.0102, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2094/4000 [20:05<16:19,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.009408950805664, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.54538345336914, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2095/4000 [20:06<16:33,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3067739009857178, Predicted Probability: 0.9647, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.851815223693848, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  52%|█████▏    | 2096/4000 [20:06<15:06,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.999264717102051, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.518412113189697, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2097/4000 [20:06<15:38,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.936370849609375, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.208903789520264, Predicted Probability: 0.9854, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2098/4000 [20:07<17:49,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.019343852996826, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8061089515686035, Predicted Probability: 0.9430, Prediction: 1.0

Epoch 2/3:  52%|█████▏    | 2099/4000 [20:07<14:31,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.24794375896453857, Predicted Probability: 0.4383, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.683499813079834, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  52%|█████▎    | 2100/4000 [20:08<15:23,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.475252151489258, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.789927959442139, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2101/4000 [20:08<14:10,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.462623596191406, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 7.317296028137207, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2102/4000 [20:09<17:38,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.990245819091797, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3705008029937744, Predicted Probability: 0.9146, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2103/4000 [20:10<19:04,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4906535148620605, Predicted Probability: 0.9235, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.377504348754883, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2104/4000 [20:10<15:15,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.704309463500977, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.437335014343262, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2105/4000 [20:10<14:07,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.209501266479492, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.056041717529297, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2106/4000 [20:11<14:10,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.80702543258667, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.807868003845215, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2107/4000 [20:11<13:29,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9131489992141724, Predicted Probability: 0.8714, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.571736812591553, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2108/4000 [20:12<16:16,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.469940423965454, Predicted Probability: 0.1870, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.281342506408691, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2109/4000 [20:13<18:22,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4141743183135986, Predicted Probability: 0.1956, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.137838363647461, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2110/4000 [20:13<17:54,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.535800933837891, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9357800483703613, Predicted Probability: 0.9808, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2111/4000 [20:14<17:40,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.559707164764404, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1012868881225586, Predicted Probability: 0.0431, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2112/4000 [20:14<17:26,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9636104106903076, Predicted Probability: 0.9509, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.583110809326172, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2113/4000 [20:15<19:29,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.809998512268066, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3176467418670654, Predicted Probability: 0.2112, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2114/4000 [20:15<17:11,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.655306816101074, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.948833465576172, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2115/4000 [20:16<20:00,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.326736450195312, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.870072364807129, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2116/4000 [20:17<20:40,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.373595714569092, Predicted Probability: 0.9876, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7292462587356567, Predicted Probability: 0.1507, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2117/4000 [20:18<21:28,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.710374355316162, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.060177803039551, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2118/4000 [20:18<16:55,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.904952526092529, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0612616539001465, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2119/4000 [20:18<15:54,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5253231525421143, Predicted Probability: 0.0741, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.986064910888672, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2120/4000 [20:19<17:48,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.997163772583008, Predicted Probability: 0.0180, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.232810974121094, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2121/4000 [20:20<19:37,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.077125549316406, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3509037494659424, Predicted Probability: 0.9661, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2122/4000 [20:21<20:33,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.112165451049805, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1839425563812256, Predicted Probability: 0.7657, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2123/4000 [20:21<17:47,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.562971591949463, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.067511558532715, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2124/4000 [20:22<19:24,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1886959075927734, Predicted Probability: 0.8992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.30040454864502, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2125/4000 [20:23<20:54,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.707270622253418, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.321265459060669, Predicted Probability: 0.9106, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2126/4000 [20:23<18:13,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9290876388549805, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.06358528137207, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2127/4000 [20:24<19:44,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8007326126098633, Predicted Probability: 0.9781, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.758029460906982, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2128/4000 [20:24<20:50,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.751091003417969, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7857160568237305, Predicted Probability: 0.0222, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2129/4000 [20:25<18:02,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.010319709777832, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.490996360778809, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2130/4000 [20:26<19:46,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.464668273925781, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.155893325805664, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2131/4000 [20:26<17:18,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.738992691040039, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.280123233795166, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2132/4000 [20:27<18:59,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.151977300643921, Predicted Probability: 0.1041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.519672393798828, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2134/4000 [20:27<13:56,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.259622573852539, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.278530597686768, Predicted Probability: 0.9993, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -8.872990608215332, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.947268009185791, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2135/4000 [20:28<13:20,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.053196430206299, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.164902687072754, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2136/4000 [20:28<14:20,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.504185676574707, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7970158457756042, Predicted Probability: 0.6893, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2137/4000 [20:29<16:54,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8112154006958008, Predicted Probability: 0.3076, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.6287841796875, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  53%|█████▎    | 2138/4000 [20:30<18:48,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.229930877685547, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6219868659973145, Predicted Probability: 0.9323, Prediction: 1.0

Epoch 2/3:  53%|█████▎    | 2139/4000 [20:30<20:36,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6504759788513184, Predicted Probability: 0.8390, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.659955978393555, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  54%|█████▎    | 2140/4000 [20:31<19:28,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.60191822052002, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.054331302642822, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 2/3:  54%|█████▎    | 2141/4000 [20:31<17:20,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.534626960754395, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.953609943389893, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  54%|█████▎    | 2142/4000 [20:32<15:32,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6753740310668945, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.19517707824707, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  54%|█████▎    | 2143/4000 [20:32<14:18,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.731560707092285, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.9600138664245605, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 2/3:  54%|█████▎    | 2144/4000 [20:33<13:23,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.044889450073242, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4643313884735107, Predicted Probability: 0.9697, Prediction: 1.0

Epoch 2/3:  54%|█████▎    | 2145/4000 [20:33<14:24,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.779625415802002, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1198914051055908, Predicted Probability: 0.2460, Prediction: 0.0

Epoch 2/3:  54%|█████▎    | 2146/4000 [20:34<16:59,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.711674690246582, Predicted Probability: 0.0239, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6189284324646, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  54%|█████▎    | 2147/4000 [20:35<18:53,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.304835319519043, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8827948570251465, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  54%|█████▎    | 2148/4000 [20:35<21:29,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.589824676513672, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.46373176574707, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  54%|█████▎    | 2149/4000 [20:36<16:57,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.227437019348145, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.894437789916992, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2150/4000 [20:36<15:13,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.391472816467285, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.850966453552246, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2151/4000 [20:36<13:10,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.366591453552246, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.055221557617188, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2152/4000 [20:37<14:16,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.302290678024292, Predicted Probability: 0.9645, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.824237823486328, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2153/4000 [20:37<13:22,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.038997173309326, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.6400363445281982, Predicted Probability: 0.1625, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2154/4000 [20:38<14:19,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.950764179229736, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.232088804244995, Predicted Probability: 0.9031, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2155/4000 [20:39<17:35,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.411537170410156, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.692936897277832, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2156/4000 [20:39<17:12,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.325976371765137, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.372808039188385, Predicted Probability: 0.4079, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2157/4000 [20:39<15:23,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.655614376068115, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.988564491271973, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2158/4000 [20:40<14:06,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.374979496002197, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.495504856109619, Predicted Probability: 0.0294, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2159/4000 [20:40<13:16,  2.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8978993892669678, Predicted Probability: 0.0523, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.902087211608887, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2160/4000 [20:41<15:56,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.566249847412109, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.83642053604126, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2161/4000 [20:42<18:24,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.931920051574707, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.682270050048828, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2162/4000 [20:42<17:52,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9893975257873535, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.431550979614258, Predicted Probability: 0.9687, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2163/4000 [20:43<19:31,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.352602005004883, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.867118835449219, Predicted Probability: 0.9924, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2164/4000 [20:44<19:17,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.364601135253906, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.453563690185547, Predicted Probability: 0.9693, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2165/4000 [20:44<20:31,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.453761577606201, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.037700176239014, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2166/4000 [20:45<19:22,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.0767722800374031, Predicted Probability: 0.5192, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.356922626495361, Predicted Probability: 0.9873, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2167/4000 [20:45<17:37,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.461625099182129, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7358012199401855, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2168/4000 [20:46<18:57,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.786390781402588, Predicted Probability: 0.9419, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.810285568237305, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2169/4000 [20:47<20:52,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.973085403442383, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.460135459899902, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2170/4000 [20:47<19:29,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.209009170532227, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2256693840026855, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2171/4000 [20:48<18:32,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4076390266418457, Predicted Probability: 0.9679, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.863456726074219, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2172/4000 [20:49<18:31,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9540643095970154, Predicted Probability: 0.7219, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6248955726623535, Predicted Probability: 0.0097, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2173/4000 [20:49<16:15,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.739105224609375, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2069878578186035, Predicted Probability: 0.0147, Prediction: 0.0

Epoch 2/3:  54%|█████▍    | 2174/4000 [20:49<14:40,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.123727321624756, Predicted Probability: 0.9841, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0674855709075928, Predicted Probability: 0.9555, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2175/4000 [20:50<14:16,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.866495132446289, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.426604270935059, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2176/4000 [20:50<11:50,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.977292537689209, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.106389999389648, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2178/4000 [20:51<09:54,  3.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.710522174835205, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.589635372161865, Predicted Probability: 0.0014, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -3.907857656478882, Predicted Probability: 0.0197, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.564888954162598, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  54%|█████▍    | 2179/4000 [20:51<11:48,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.804213762283325, Predicted Probability: 0.9782, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.285008430480957, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2180/4000 [20:51<10:41,  2.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.590176582336426, Predicted Probability: 0.9900, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.729550361633301, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2181/4000 [20:52<10:51,  2.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.956459999084473, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.019891738891602, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2182/4000 [20:52<10:58,  2.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.07669734954834, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.67339563369751, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2183/4000 [20:53<14:35,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1480674743652344, Predicted Probability: 0.1045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8909251689910889, Predicted Probability: 0.1311, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2184/4000 [20:53<14:08,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.307224750518799, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.918578147888184, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2186/4000 [20:54<11:05,  2.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.452790260314941, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.351604461669922, Predicted Probability: 0.9983, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.08767318725586, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.226613998413086, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2187/4000 [20:54<10:11,  2.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.939218521118164, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.654666423797607, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2188/4000 [20:55<10:32,  2.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.8971080780029297, Predicted Probability: 0.8696, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.942756652832031, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2189/4000 [20:55<14:14,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.711562156677246, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.491019248962402, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2190/4000 [20:56<16:43,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32892221212387085, Predicted Probability: 0.5815, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.717106819152832, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2191/4000 [20:57<18:35,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.473174095153809, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.171874046325684, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2192/4000 [20:57<16:23,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0260801315307617, Predicted Probability: 0.9537, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.542819976806641, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2193/4000 [20:57<13:54,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.14230728149414, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.155965805053711, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2194/4000 [20:58<17:27,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.27847957611084, Predicted Probability: 0.0363, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.111714363098145, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  55%|█████▍    | 2195/4000 [20:58<14:07,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.819864273071289, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.83971643447876, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2196/4000 [20:59<13:14,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.654001235961914, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2556023597717285, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2197/4000 [20:59<12:33,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.9176334738731384, Predicted Probability: 0.2854, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.689778327941895, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2198/4000 [21:00<13:45,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.04633617401123, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.6601386070251465, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  55%|█████▍    | 2199/4000 [21:01<16:23,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.726027250289917, Predicted Probability: 0.9385, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.056724548339844, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  55%|█████▌    | 2200/4000 [21:01<14:59,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.065459251403809, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.090426445007324, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2201/4000 [21:02<16:46,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.021754264831543, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2061524391174316, Predicted Probability: 0.9611, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2202/4000 [21:02<15:12,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.41326904296875, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.430452823638916, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2203/4000 [21:03<17:28,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0879788398742676, Predicted Probability: 0.1103, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.404118537902832, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  55%|█████▌    | 2204/4000 [21:03<15:30,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.175785541534424, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.62921667098999, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2205/4000 [21:04<17:13,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.581472873687744, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6042253971099854, Predicted Probability: 0.9311, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2206/4000 [21:04<15:34,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.07243537902832, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.559828758239746, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 2/3:  55%|█████▌    | 2207/4000 [21:05<17:22,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.594963550567627, Predicted Probability: 0.0267, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.45648497343063354, Predicted Probability: 0.6122, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2208/4000 [21:05<15:25,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4810357093811035, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.933561325073242, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2210/4000 [21:06<14:13,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.533109664916992, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.135491371154785, Predicted Probability: 0.9843, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.87783145904541, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.929115295410156, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2211/4000 [21:07<13:17,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.325131416320801, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.197153091430664, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2212/4000 [21:07<15:50,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8490471839904785, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.260209560394287, Predicted Probability: 0.9055, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2213/4000 [21:08<18:44,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.407817840576172, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.866611480712891, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  55%|█████▌    | 2214/4000 [21:09<16:40,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.177281379699707, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 4.2915873527526855, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2215/4000 [21:09<15:32,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.940638542175293, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.281302452087402, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2216/4000 [21:09<14:12,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.548243522644043, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.16816234588623, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2217/4000 [21:10<13:07,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3567681312561035, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.155093669891357, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  55%|█████▌    | 2218/4000 [21:10<13:08,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.909418106079102, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.651018142700195, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  55%|█████▌    | 2219/4000 [21:11<16:36,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1973466873168945, Predicted Probability: 0.2319, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4808168411254883, Predicted Probability: 0.0772, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2220/4000 [21:12<18:35,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8253679275512695, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3829371929168701, Predicted Probability: 0.4054, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2221/4000 [21:12<16:27,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.100526809692383, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.98048210144043, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2222/4000 [21:13<14:49,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.132857322692871, Predicted Probability: 0.9842, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.184629917144775, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2223/4000 [21:13<16:49,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.995346546173096, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.590663194656372, Predicted Probability: 0.9303, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2224/4000 [21:14<15:07,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.184242248535156, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.362900972366333, Predicted Probability: 0.0335, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2225/4000 [21:14<17:06,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6245293617248535, Predicted Probability: 0.9324, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.697790145874023, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2226/4000 [21:15<13:45,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.703469276428223, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.707327842712402, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2227/4000 [21:15<12:53,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4442620277404785, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.939025402069092, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2229/4000 [21:16<10:25,  2.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.603604793548584, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.097806453704834, Predicted Probability: 0.1093, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -7.514730453491211, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.067785263061523, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2230/4000 [21:16<12:22,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.38978385925293, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.7640156745910645, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2231/4000 [21:17<15:37,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.07431697845459, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.407993793487549, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2232/4000 [21:18<15:36,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.461546897888184, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.01947021484375, Predicted Probability: 0.9534, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2233/4000 [21:18<18:14,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.361547470092773, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.971386909484863, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2234/4000 [21:19<19:15,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.085806846618652, Predicted Probability: 0.9835, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.839180946350098, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2235/4000 [21:20<20:09,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.232969284057617, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0560996532440186, Predicted Probability: 0.8866, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2236/4000 [21:20<15:53,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.226615905761719, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.403506755828857, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2237/4000 [21:21<16:23,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1722898483276367, Predicted Probability: 0.0402, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.650270700454712, Predicted Probability: 0.0253, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2238/4000 [21:21<13:17,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.259466171264648, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.822778701782227, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2239/4000 [21:22<16:09,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.771786689758301, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7194190621376038, Predicted Probability: 0.6725, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2240/4000 [21:22<14:39,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.31713581085205, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 4.371279239654541, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2241/4000 [21:23<16:50,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7558069229125977, Predicted Probability: 0.0228, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.029715538024902, Predicted Probability: 0.9825, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2242/4000 [21:24<18:32,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.881376266479492, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.725275993347168, Predicted Probability: 0.9912, Prediction: 1.0

Epoch 2/3:  56%|█████▌    | 2243/4000 [21:24<15:22,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.926356792449951, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.95565128326416, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2244/4000 [21:25<17:10,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.150049209594727, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6923859119415283, Predicted Probability: 0.1555, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2245/4000 [21:25<18:36,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.948134422302246, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.066258430480957, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2246/4000 [21:26<19:36,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4669382572174072, Predicted Probability: 0.9697, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.134544372558594, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2247/4000 [21:27<20:25,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.071557521820068, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.18407897651195526, Predicted Probability: 0.4541, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2248/4000 [21:28<20:56,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.191612720489502, Predicted Probability: 0.8995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.317230224609375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  56%|█████▌    | 2249/4000 [21:28<17:55,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.81391716003418, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.052119731903076, Predicted Probability: 0.0451, Prediction: 0.0

Epoch 2/3:  56%|█████▋    | 2250/4000 [21:28<17:14,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0462188720703125, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8275516033172607, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 2/3:  56%|█████▋    | 2251/4000 [21:29<16:48,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.32309627532959, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1566709280014038, Predicted Probability: 0.2393, Prediction: 0.0

Epoch 2/3:  56%|█████▋    | 2252/4000 [21:29<14:58,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.512584209442139, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.824028968811035, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  56%|█████▋    | 2253/4000 [21:30<17:08,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.081998825073242, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2413530349731445, Predicted Probability: 0.9039, Prediction: 1.0

Epoch 2/3:  56%|█████▋    | 2254/4000 [21:31<16:36,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.555901527404785, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.544161081314087, Predicted Probability: 0.0728, Prediction: 0.0

Epoch 2/3:  56%|█████▋    | 2255/4000 [21:31<17:59,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5363744497299194, Predicted Probability: 0.1771, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.208200454711914, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  56%|█████▋    | 2256/4000 [21:32<18:55,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.218991279602051, Predicted Probability: 0.9855, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4563679695129395, Predicted Probability: 0.9694, Prediction: 1.0

Epoch 2/3:  56%|█████▋    | 2257/4000 [21:33<20:01,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.481391191482544, Predicted Probability: 0.0298, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.88976788520813, Predicted Probability: 0.9800, Prediction: 1.0

Epoch 2/3:  56%|█████▋    | 2258/4000 [21:34<20:45,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.945521354675293, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.2786970138549805, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  56%|█████▋    | 2259/4000 [21:34<16:18,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.783772468566895, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.719225883483887, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  56%|█████▋    | 2260/4000 [21:34<14:46,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.666351318359375, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.20632266998291, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2261/4000 [21:35<17:08,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.314505577087402, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.08629846572876, Predicted Probability: 0.9835, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2262/4000 [21:36<19:03,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.0927921533584595, Predicted Probability: 0.7489, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.755858898162842, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2263/4000 [21:36<16:33,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.723051071166992, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.301857948303223, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2264/4000 [21:37<18:20,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7071815729141235, Predicted Probability: 0.1535, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.265456676483154, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2265/4000 [21:37<14:37,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.043900489807129, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.984001159667969, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2266/4000 [21:38<15:00,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.042688846588135, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.825180530548096, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2267/4000 [21:38<12:18,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.322100639343262, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.371953010559082, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2268/4000 [21:38<12:32,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.832461833953857, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.952038288116455, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2269/4000 [21:39<15:11,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.764826774597168, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.46417760848999, Predicted Probability: 0.9886, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2270/4000 [21:40<14:01,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.534585952758789, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.190680503845215, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2271/4000 [21:40<16:40,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.423020362854004, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9608235359191895, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2272/4000 [21:41<18:02,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.758233666419983, Predicted Probability: 0.1470, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.064451217651367, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2273/4000 [21:41<15:51,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.011963844299316, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.572020530700684, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2274/4000 [21:42<14:21,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.518026828765869, Predicted Probability: 0.9254, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.447754859924316, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2275/4000 [21:43<16:28,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.452214241027832, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2056822776794434, Predicted Probability: 0.9610, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2276/4000 [21:43<16:08,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.0727631226181984, Predicted Probability: 0.4818, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8677840232849121, Predicted Probability: 0.2957, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2277/4000 [21:44<15:59,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.993227958679199, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3988821506500244, Predicted Probability: 0.9677, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2278/4000 [21:44<17:21,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.448569297790527, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3366120159626007, Predicted Probability: 0.4166, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2279/4000 [21:45<15:57,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.272944450378418, Predicted Probability: 0.0365, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.005178451538086, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2280/4000 [21:45<15:53,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6338341236114502, Predicted Probability: 0.8367, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0050368309021, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2281/4000 [21:46<17:26,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.61534595489502, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8619410991668701, Predicted Probability: 0.8655, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2282/4000 [21:47<18:37,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.841955184936523, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.015214920043945, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2283/4000 [21:47<15:23,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3211605548858643, Predicted Probability: 0.9106, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.928583145141602, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2284/4000 [21:48<14:00,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.388552188873291, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.094890594482422, Predicted Probability: 0.9836, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2285/4000 [21:48<16:25,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.032342910766602, Predicted Probability: 0.9826, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.820570468902588, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2286/4000 [21:49<18:09,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.246941328048706, Predicted Probability: 0.0374, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4000645875930786, Predicted Probability: 0.5987, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2287/4000 [21:50<19:23,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.329463958740234, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4568026065826416, Predicted Probability: 0.0306, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2288/4000 [21:51<20:08,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.754585862159729, Predicted Probability: 0.1475, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.956478118896484, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2289/4000 [21:51<20:18,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.052682638168335, Predicted Probability: 0.9549, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.15716552734375, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2290/4000 [21:52<20:45,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8738336563110352, Predicted Probability: 0.1331, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.219069480895996, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2291/4000 [21:53<20:48,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.716738700866699, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5074777603149414, Predicted Probability: 0.9247, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2292/4000 [21:53<19:13,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.009639739990234, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.058905601501465, Predicted Probability: 0.9552, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2293/4000 [21:54<19:46,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5411794185638428, Predicted Probability: 0.9270, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.12561321258545, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2294/4000 [21:55<20:10,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7420594692230225, Predicted Probability: 0.0232, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.054063320159912, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2295/4000 [21:55<17:12,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.966420650482178, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2115278244018555, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  57%|█████▋    | 2296/4000 [21:56<18:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.374784469604492, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.007455348968506, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2297/4000 [21:56<14:40,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.135396480560303, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.349595069885254, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2298/4000 [21:57<17:05,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.039676666259766, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.841902732849121, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  57%|█████▋    | 2299/4000 [21:57<15:04,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.829627990722656, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.484787940979004, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  57%|█████▊    | 2300/4000 [21:58<13:42,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5886006355285645, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.372498512268066, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2301/4000 [21:58<13:15,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.746975302696228, Predicted Probability: 0.1484, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8632848262786865, Predicted Probability: 0.9794, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2302/4000 [21:59<12:19,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.590174198150635, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.142903804779053, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2303/4000 [21:59<11:47,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.493295192718506, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.32600212097168, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2304/4000 [22:00<14:36,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.046947479248047, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7533791065216064, Predicted Probability: 0.9771, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2305/4000 [22:00<16:39,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.53078031539917, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.349325180053711, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2306/4000 [22:01<17:55,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.074430465698242, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.290992736816406, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2307/4000 [22:02<17:11,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.7003045082092285, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7970476150512695, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2308/4000 [22:02<15:24,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.151067733764648, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.53703784942627, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2309/4000 [22:03<13:56,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.250729560852051, Predicted Probability: 0.9859, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.798578262329102, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2310/4000 [22:03<12:49,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.416030883789062, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.753281831741333, Predicted Probability: 0.0229, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2311/4000 [22:04<15:04,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.062097549438477, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.846674919128418, Predicted Probability: 0.0209, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2312/4000 [22:04<16:47,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.667412757873535, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.59225594997406, Predicted Probability: 0.8309, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2313/4000 [22:05<13:27,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.422464370727539, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.670798301696777, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2314/4000 [22:05<12:30,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.692016124725342, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.052998542785645, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2315/4000 [22:06<14:58,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5343377590179443, Predicted Probability: 0.9265, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.065313339233398, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2316/4000 [22:06<13:44,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.414649486541748, Predicted Probability: 0.0120, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.330700874328613, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2317/4000 [22:06<12:50,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.275646209716797, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0299224853515625, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2318/4000 [22:07<10:47,  2.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.38021183013916, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4470601081848145, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2319/4000 [22:07<13:44,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.20262336730957, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.156959056854248, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2320/4000 [22:08<15:42,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.419377326965332, Predicted Probability: 0.9183, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.034100532531738, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2321/4000 [22:09<17:38,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.321016311645508, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.350752830505371, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2322/4000 [22:10<18:26,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.656229257583618, Predicted Probability: 0.9344, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.317750930786133, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2323/4000 [22:10<19:17,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.515730142593384, Predicted Probability: 0.9252, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.667609691619873, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2324/4000 [22:11<18:05,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.806336879730225, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.976298809051514, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2325/4000 [22:12<19:14,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.096879959106445, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7366766929626465, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2326/4000 [22:12<16:47,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.947091102600098, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.666394233703613, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2327/4000 [22:13<17:57,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4361920356750488, Predicted Probability: 0.8079, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.08866351842880249, Predicted Probability: 0.5222, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2328/4000 [22:14<18:38,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.187610626220703, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.315033197402954, Predicted Probability: 0.9101, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2329/4000 [22:15<23:37,  1.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7425581216812134, Predicted Probability: 0.1490, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.8057756423950195, Predicted Probability: 0.0081, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2330/4000 [22:15<18:12,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.696161270141602, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.582365989685059, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2331/4000 [22:16<18:50,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.633464813232422, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3475966453552246, Predicted Probability: 0.0340, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2333/4000 [22:16<13:01,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.164133071899414, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.965967178344727, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.357492446899414, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.184783458709717, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2334/4000 [22:17<15:09,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.603402853012085, Predicted Probability: 0.9311, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.036340713500977, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2335/4000 [22:18<16:39,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.80456280708313, Predicted Probability: 0.9429, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8827667236328125, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2336/4000 [22:19<17:41,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.034087896347046, Predicted Probability: 0.9541, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.952979564666748, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2337/4000 [22:19<18:37,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3682475090026855, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.063529968261719, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2338/4000 [22:20<19:43,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.842665672302246, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5886123180389404, Predicted Probability: 0.9301, Prediction: 1.0

Epoch 2/3:  58%|█████▊    | 2339/4000 [22:21<17:32,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.000598430633545, Predicted Probability: 0.9820, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.926450252532959, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  58%|█████▊    | 2340/4000 [22:21<19:16,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.70578145980835, Predicted Probability: 0.9910, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.372195243835449, Predicted Probability: 0.0125, Prediction: 0.0

Epoch 2/3:  59%|█████▊    | 2341/4000 [22:22<15:15,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.270267009735107, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.510274887084961, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  59%|█████▊    | 2342/4000 [22:22<15:05,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.8364896774292, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.188978433609009, Predicted Probability: 0.9604, Prediction: 1.0

Epoch 2/3:  59%|█████▊    | 2343/4000 [22:22<12:18,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.562274932861328, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.4340105056762695, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  59%|█████▊    | 2344/4000 [22:23<11:40,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.6939778327941895, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.363343715667725, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 2/3:  59%|█████▊    | 2346/4000 [22:24<11:31,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.460944175720215, Predicted Probability: 0.9214, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.598991394042969, Predicted Probability: 0.0002, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.459529876708984, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.455860137939453, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  59%|█████▊    | 2347/4000 [22:24<11:00,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.089584350585938, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.279709815979004, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  59%|█████▊    | 2348/4000 [22:25<13:44,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.105510234832764, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.517164707183838, Predicted Probability: 0.9253, Prediction: 1.0

Epoch 2/3:  59%|█████▊    | 2349/4000 [22:26<16:37,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.702065944671631, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.22611141204834, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2350/4000 [22:26<17:43,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.191687107086182, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3135699033737183, Predicted Probability: 0.2119, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2351/4000 [22:27<16:00,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.104552268981934, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.500690460205078, Predicted Probability: 0.9890, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2353/4000 [22:28<14:13,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.138830184936523, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.109903335571289, Predicted Probability: 0.0003, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 2.393307685852051, Predicted Probability: 0.9163, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.125897407531738, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2354/4000 [22:29<16:13,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3201422691345215, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.136260509490967, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2355/4000 [22:29<13:04,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.433184623718262, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.722822666168213, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2356/4000 [22:29<13:40,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.575112342834473, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.1607890129089355, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2357/4000 [22:30<15:44,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.693138122558594, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.606672286987305, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2358/4000 [22:30<14:36,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.745102882385254, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.502950668334961, Predicted Probability: 0.9890, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2359/4000 [22:31<13:18,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.539207458496094, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.767963409423828, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2360/4000 [22:32<15:42,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.591058731079102, Predicted Probability: 0.9900, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.202605724334717, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2361/4000 [22:32<16:57,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.208431601524353, Predicted Probability: 0.2300, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.320363521575928, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2362/4000 [22:33<14:50,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.912890911102295, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2368693351745605, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2363/4000 [22:33<12:02,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.777441501617432, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.13686415553092957, Predicted Probability: 0.5342, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2364/4000 [22:34<15:07,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.179561138153076, Predicted Probability: 0.9849, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.491613388061523, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2365/4000 [22:34<16:28,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.429736137390137, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8051576614379883, Predicted Probability: 0.6911, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2366/4000 [22:35<15:07,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.112834453582764, Predicted Probability: 0.9839, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.8906831741333, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2367/4000 [22:36<17:04,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.320557594299316, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.954051971435547, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2368/4000 [22:36<13:38,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.073609352111816, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.442183494567871, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2369/4000 [22:36<11:17,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1583356857299805, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.635326862335205, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2370/4000 [22:37<14:07,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.468398094177246, Predicted Probability: 0.9219, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.163135528564453, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2371/4000 [22:38<16:01,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5405519008636475, Predicted Probability: 0.9269, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.78537654876709, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2372/4000 [22:38<17:47,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.283378601074219, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.129511833190918, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2373/4000 [22:39<18:54,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.823329448699951, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.361520767211914, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2374/4000 [22:40<17:38,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1276965141296387, Predicted Probability: 0.7554, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.208837985992432, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2375/4000 [22:40<15:17,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.353087902069092, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.901498317718506, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2376/4000 [22:41<19:02,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.721935749053955, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.031314849853516, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  59%|█████▉    | 2377/4000 [22:42<16:26,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.673479080200195, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.676169395446777, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2378/4000 [22:42<16:00,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9600019454956055, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.626276969909668, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  59%|█████▉    | 2379/4000 [22:43<17:20,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7065131664276123, Predicted Probability: 0.0626, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1235969066619873, Predicted Probability: 0.0421, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2380/4000 [22:43<15:39,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.127937316894531, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.745335102081299, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 2/3:  60%|█████▉    | 2381/4000 [22:44<16:47,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8012101650238037, Predicted Probability: 0.9427, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.261212348937988, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2382/4000 [22:45<17:39,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7093887329101562, Predicted Probability: 0.9376, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.212282180786133, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2383/4000 [22:45<16:41,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.502312183380127, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9093565940856934, Predicted Probability: 0.0517, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2384/4000 [22:46<17:55,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8960280418395996, Predicted Probability: 0.2899, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.597745895385742, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2385/4000 [22:47<16:51,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.959777355194092, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.618409156799316, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 2/3:  60%|█████▉    | 2386/4000 [22:47<17:46,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5997705459594727, Predicted Probability: 0.9308, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4185991287231445, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2387/4000 [22:48<18:24,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.530879020690918, Predicted Probability: 0.9263, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.699670314788818, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2388/4000 [22:48<15:51,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.08181619644165, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.604670524597168, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  60%|█████▉    | 2389/4000 [22:49<16:52,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.963850498199463, Predicted Probability: 0.9509, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.129668235778809, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2390/4000 [22:50<17:48,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5509319305419922, Predicted Probability: 0.3656, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.672395706176758, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2391/4000 [22:51<18:39,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.916816711425781, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.767336845397949, Predicted Probability: 0.0226, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2392/4000 [22:51<19:15,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.777713775634766, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.543262481689453, Predicted Probability: 0.0281, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2393/4000 [22:52<19:45,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.781758785247803, Predicted Probability: 0.9917, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.513575553894043, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2394/4000 [22:53<20:04,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.268324851989746, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.89992094039917, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2395/4000 [22:53<16:12,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.598924160003662, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.914488315582275, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2396/4000 [22:54<15:40,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.494541645050049, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.213766098022461, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  60%|█████▉    | 2397/4000 [22:55<16:51,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.838085174560547, Predicted Probability: 0.9921, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.353960990905762, Predicted Probability: 0.0127, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2398/4000 [22:55<14:00,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.896793365478516, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.270711421966553, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  60%|█████▉    | 2399/4000 [22:55<12:47,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.026642799377441, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.912766456604004, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2400/4000 [22:56<11:48,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.094379425048828, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.779219150543213, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2401/4000 [22:56<14:29,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.585312843322754, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6478536128997803, Predicted Probability: 0.9339, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2402/4000 [22:57<13:01,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.885158538818359, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7491631507873535, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2403/4000 [22:57<10:46,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.637991905212402, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.659059524536133, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2404/4000 [22:58<13:16,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6395955085754395, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8279783725738525, Predicted Probability: 0.9442, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2405/4000 [22:58<12:26,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.247884750366211, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.229369878768921, Predicted Probability: 0.0381, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2406/4000 [22:59<14:52,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.152554512023926, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7016520500183105, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2407/4000 [22:59<14:48,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.463716983795166, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.969919681549072, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2408/4000 [23:00<13:20,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.308414936065674, Predicted Probability: 0.0133, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.30683708190918, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2409/4000 [23:00<10:56,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.00532341003418, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.017868041992188, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2410/4000 [23:01<13:24,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.825831413269043, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8898062705993652, Predicted Probability: 0.9800, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2411/4000 [23:01<15:40,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.388932704925537, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.195797920227051, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2412/4000 [23:02<16:55,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.741491317749023, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.681204080581665, Predicted Probability: 0.0246, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2413/4000 [23:03<14:56,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.8517427444458, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.765398025512695, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2414/4000 [23:03<13:37,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.849047660827637, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5406737327575684, Predicted Probability: 0.0282, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2415/4000 [23:03<12:25,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.43013858795166, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.116590976715088, Predicted Probability: 0.9840, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2417/4000 [23:04<12:01,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4729766845703125, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.018324375152588, Predicted Probability: 0.0066, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.735356330871582, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.636698722839355, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2418/4000 [23:05<10:03,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.133919715881348, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.51426887512207, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  60%|██████    | 2419/4000 [23:05<13:02,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.563206672668457, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.774554252624512, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:  60%|██████    | 2420/4000 [23:06<16:06,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.285982131958008, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.448596954345703, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2421/4000 [23:06<12:54,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9942097663879395, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.732213973999023, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2422/4000 [23:07<12:33,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.882171154022217, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.651907444000244, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2423/4000 [23:08<14:37,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.527528762817383, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.531360626220703, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2424/4000 [23:08<16:08,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.676980018615723, Predicted Probability: 0.0092, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.147221565246582, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2425/4000 [23:09<18:00,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7952044010162354, Predicted Probability: 0.3111, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.494640350341797, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2426/4000 [23:10<18:58,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.814861297607422, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.593574523925781, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2427/4000 [23:11<19:07,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.676905632019043, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5414652824401855, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2428/4000 [23:12<19:17,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6559252738952637, Predicted Probability: 0.9344, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.7572760581970215, Predicted Probability: 0.1471, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2429/4000 [23:12<18:13,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9833738803863525, Predicted Probability: 0.9817, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.351097822189331, Predicted Probability: 0.9661, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2430/4000 [23:12<15:42,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.8220109939575195, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.002167701721191, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2431/4000 [23:13<15:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.873631954193115, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.353981971740723, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2432/4000 [23:14<14:42,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6641976833343506, Predicted Probability: 0.9750, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.685581684112549, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2433/4000 [23:14<13:15,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.965500831604004, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.298767566680908, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2434/4000 [23:14<12:04,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.347484111785889, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.76021957397461, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2435/4000 [23:15<11:19,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.008021354675293, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.967959403991699, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2436/4000 [23:16<14:43,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4047577381134033, Predicted Probability: 0.0321, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1524128913879395, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2437/4000 [23:16<16:26,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.2622761726379395, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8466858863830566, Predicted Probability: 0.9451, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2438/4000 [23:17<13:08,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.3187837600708, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.212175369262695, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2440/4000 [23:17<12:02,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7987396717071533, Predicted Probability: 0.9426, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.062496185302734, Predicted Probability: 0.9997, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -7.407216548919678, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9981557130813599, Predicted Probability: 0.2693, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2441/4000 [23:18<11:14,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.14558744430542, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.640682220458984, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2442/4000 [23:19<13:34,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8586268424987793, Predicted Probability: 0.9458, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.910004615783691, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2443/4000 [23:19<12:20,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.784259796142578, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.484748840332031, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2444/4000 [23:20<13:13,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.92433500289917, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.112597703933716, Predicted Probability: 0.0426, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2445/4000 [23:20<15:34,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.70519495010376, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.25260746479034424, Predicted Probability: 0.5628, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2446/4000 [23:21<15:13,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.673318862915039, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.127990245819092, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2447/4000 [23:22<16:43,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.69462513923645, Predicted Probability: 0.0243, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.570029258728027, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  61%|██████    | 2448/4000 [23:22<15:54,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.42033576965332, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.104832649230957, Predicted Probability: 0.0429, Prediction: 0.0

Epoch 2/3:  61%|██████    | 2449/4000 [23:23<17:10,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5225348472595215, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.287243366241455, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  61%|██████▏   | 2450/4000 [23:24<16:12,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.803254127502441, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.10169792175293, Predicted Probability: 0.9837, Prediction: 1.0

Epoch 2/3:  61%|██████▏   | 2451/4000 [23:24<17:16,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.684571743011475, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.431490898132324, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  61%|██████▏   | 2452/4000 [23:25<17:55,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.859399795532227, Predicted Probability: 0.9923, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8726351261138916, Predicted Probability: 0.1332, Prediction: 0.0

Epoch 2/3:  61%|██████▏   | 2453/4000 [23:26<18:17,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.756717681884766, Predicted Probability: 0.9915, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1022725105285645, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  61%|██████▏   | 2454/4000 [23:26<15:42,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.696476936340332, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.913102626800537, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  61%|██████▏   | 2455/4000 [23:27<14:22,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.065662145614624, Predicted Probability: 0.9555, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.810867309570312, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  61%|██████▏   | 2456/4000 [23:27<16:12,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.335033416748047, Predicted Probability: 0.9871, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.089025974273682, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  61%|██████▏   | 2457/4000 [23:28<16:58,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.03753137588501, Predicted Probability: 0.9827, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.158018112182617, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  61%|██████▏   | 2458/4000 [23:29<16:12,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.960199356079102, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.284706115722656, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  61%|██████▏   | 2459/4000 [23:29<17:07,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.132331848144531, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3992739915847778, Predicted Probability: 0.1979, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2460/4000 [23:30<17:38,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.314510345458984, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.070691466331482, Predicted Probability: 0.2553, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2461/4000 [23:31<15:21,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.822737693786621, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.93903923034668, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2462/4000 [23:31<16:33,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.782431125640869, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.670610189437866, Predicted Probability: 0.9353, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2463/4000 [23:32<17:31,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.654328346252441, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.990591049194336, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2464/4000 [23:32<15:16,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.820324897766113, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.074056625366211, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2465/4000 [23:33<14:48,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.96668815612793, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.121540069580078, Predicted Probability: 0.9840, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2466/4000 [23:34<16:01,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0696239471435547, Predicted Probability: 0.0444, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.868231773376465, Predicted Probability: 0.9463, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2467/4000 [23:34<15:53,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.6292805671691895, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.510776996612549, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2468/4000 [23:35<13:59,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.507758140563965, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.639020919799805, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2469/4000 [23:36<15:39,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.536722183227539, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.220935821533203, Predicted Probability: 0.0054, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2470/4000 [23:36<16:59,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.265623092651367, Predicted Probability: 0.9862, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6027326583862305, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2471/4000 [23:37<14:48,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.083707809448242, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.903472423553467, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2472/4000 [23:37<15:57,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.540011405944824, Predicted Probability: 0.9269, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.145051956176758, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2473/4000 [23:38<14:27,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.922140121459961, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.553284645080566, Predicted Probability: 0.9896, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2474/4000 [23:39<16:01,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.602027177810669, Predicted Probability: 0.9735, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.170553207397461, Predicted Probability: 0.0056, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -0.7771728038787842, Predicted Probability: 0.3149, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.801787853240967, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2476/4000 [23:40<14:38,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2588014602661133, Predicted Probability: 0.0370, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.743785381317139, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2477/4000 [23:40<15:56,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.364485740661621, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.11008620262146, Predicted Probability: 0.2479, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2478/4000 [23:41<16:42,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.371025085449219, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.209199905395508, Predicted Probability: 0.9011, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2479/4000 [23:42<15:42,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.757750034332275, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.038339138031006, Predicted Probability: 0.0457, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2480/4000 [23:42<17:17,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.482831954956055, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.006416320800781, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2481/4000 [23:43<18:03,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8987669944763184, Predicted Probability: 0.0199, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.646648406982422, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2482/4000 [23:44<18:20,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.524233341217041, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.013662338256836, Predicted Probability: 0.0177, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2483/4000 [23:45<18:40,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.940476417541504, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.122382164001465, Predicted Probability: 0.0159, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2484/4000 [23:45<16:32,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.827572345733643, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.200476169586182, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2485/4000 [23:46<15:52,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.336604595184326, Predicted Probability: 0.0881, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.617691040039062, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2486/4000 [23:47<17:25,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.957066535949707, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.28316593170166, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2487/4000 [23:47<18:10,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.625555038452148, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.188876152038574, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2488/4000 [23:48<18:27,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8738880157470703, Predicted Probability: 0.0204, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.882136344909668, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.9230318069458, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.952054977416992, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2491/4000 [23:49<10:31,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.087717533111572, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.138887405395508, Predicted Probability: 0.0157, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -8.974418640136719, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.040815353393555, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2492/4000 [23:50<13:04,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.786149978637695, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9376063346862793, Predicted Probability: 0.9497, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2493/4000 [23:50<14:48,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5438389778137207, Predicted Probability: 0.9272, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.190265655517578, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2494/4000 [23:51<11:58,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.9113852977752686, Predicted Probability: 0.9804, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.737794399261475, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2495/4000 [23:51<14:16,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.829879760742188, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.744351387023926, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2496/4000 [23:52<15:33,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3932950496673584, Predicted Probability: 0.1989, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.844709396362305, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2497/4000 [23:53<13:43,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.619986534118652, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.582365989685059, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:  62%|██████▏   | 2498/4000 [23:53<16:03,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.539783477783203, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.145858764648438, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  62%|██████▏   | 2499/4000 [23:54<16:48,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.11406135559082, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.940212249755859, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  62%|██████▎   | 2500/4000 [23:55<15:47,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.318604946136475, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7476773262023926, Predicted Probability: 0.0602, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2501/4000 [23:55<16:34,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3312339782714844, Predicted Probability: 0.9114, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.122313022613525, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2502/4000 [23:56<17:09,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7053651809692383, Predicted Probability: 0.9760, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.131955146789551, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2503/4000 [23:57<15:23,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.693183422088623, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.1575422286987305, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2504/4000 [23:57<16:18,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.0280232429504395, Predicted Probability: 0.9825, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.647903442382812, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2505/4000 [23:58<13:23,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9275487661361694, Predicted Probability: 0.7166, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.378173828125, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2506/4000 [23:58<11:20,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.544063568115234, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9872968196868896, Predicted Probability: 0.9520, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2507/4000 [23:59<13:36,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6050944328308105, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.74875259399414, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2508/4000 [23:59<15:06,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.629860877990723, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.416085720062256, Predicted Probability: 0.9682, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2509/4000 [24:00<16:13,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.790514945983887, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.181906700134277, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2510/4000 [24:01<14:05,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.142757892608643, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.859704971313477, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2511/4000 [24:01<12:33,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.84577751159668, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.120084285736084, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2512/4000 [24:02<14:18,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.391266822814941, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2165566682815552, Predicted Probability: 0.7715, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2513/4000 [24:02<15:59,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7154115438461304, Predicted Probability: 0.6716, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.731169700622559, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2514/4000 [24:03<16:26,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.054410934448242, Predicted Probability: 0.0170, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.029738426208496, Predicted Probability: 0.1161, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2515/4000 [24:04<16:56,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6762161254882812, Predicted Probability: 0.9356, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.299922943115234, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2516/4000 [24:04<14:33,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.561984539031982, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.187696933746338, Predicted Probability: 0.0396, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2517/4000 [24:05<14:38,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0138773918151855, Predicted Probability: 0.9532, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.722935676574707, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2518/4000 [24:05<12:57,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.710080146789551, Predicted Probability: 0.0239, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.626723289489746, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2519/4000 [24:06<11:52,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.623279094696045, Predicted Probability: 0.9740, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.871352434158325, Predicted Probability: 0.9796, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2520/4000 [24:06<11:10,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.637728214263916, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.967152118682861, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2521/4000 [24:07<13:19,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.507221698760986, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.3391499519348145, Predicted Probability: 0.2076, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2522/4000 [24:07<11:23,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.521875381469727, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.745521068572998, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2523/4000 [24:08<14:52,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.787696838378906, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.301235198974609, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2524/4000 [24:08<11:54,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.439276695251465, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.803082466125488, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2525/4000 [24:09<11:04,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.083509922027588, Predicted Probability: 0.0166, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.211684226989746, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2526/4000 [24:09<11:50,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.280151844024658, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.31995964050293, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2527/4000 [24:09<10:59,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2993855476379395, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.292935371398926, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2528/4000 [24:10<11:42,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.768502235412598, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.068097114562988, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2529/4000 [24:10<11:06,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.411988258361816, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.026721000671387, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2530/4000 [24:11<11:42,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7014353275299072, Predicted Probability: 0.9371, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.79524040222168, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2532/4000 [24:11<09:10,  2.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.349003791809082, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.732476830482483, Predicted Probability: 0.1503, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -9.177789688110352, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.453712463378906, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2533/4000 [24:12<12:27,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.628221035003662, Predicted Probability: 0.0673, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.537750244140625, Predicted Probability: 0.0733, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2534/4000 [24:13<11:25,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.038818359375, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5595529079437256, Predicted Probability: 0.0277, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2535/4000 [24:13<10:40,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.781083106994629, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2452545166015625, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2536/4000 [24:14<12:46,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.665344715118408, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7723116874694824, Predicted Probability: 0.9412, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2537/4000 [24:14<11:51,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.091410160064697, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.019787788391113, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  63%|██████▎   | 2538/4000 [24:15<14:50,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.244747161865234, Predicted Probability: 0.0052, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7831926345825195, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  63%|██████▎   | 2539/4000 [24:15<13:09,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.352716445922852, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5406599044799805, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  64%|██████▎   | 2540/4000 [24:16<14:32,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.82582426071167, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7589304447174072, Predicted Probability: 0.9404, Prediction: 1.0

Epoch 2/3:  64%|██████▎   | 2541/4000 [24:17<12:50,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.552209854125977, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0198540687561035, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  64%|██████▎   | 2542/4000 [24:17<14:12,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0604255199432373, Predicted Probability: 0.9552, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.190892696380615, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  64%|██████▎   | 2543/4000 [24:18<11:57,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.805288553237915, Predicted Probability: 0.0218, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.286256790161133, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  64%|██████▎   | 2544/4000 [24:18<12:13,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.433258533477783, Predicted Probability: 0.9687, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.510960578918457, Predicted Probability: 0.9249, Prediction: 1.0

Epoch 2/3:  64%|██████▎   | 2545/4000 [24:19<14:17,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6445512771606445, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.240145683288574, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  64%|██████▎   | 2546/4000 [24:20<15:12,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0191855430603027, Predicted Probability: 0.9534, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.673235893249512, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  64%|██████▎   | 2547/4000 [24:20<15:58,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.3657474517822266, Predicted Probability: 0.9666, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.941603183746338, Predicted Probability: 0.9499, Prediction: 1.0

Epoch 2/3:  64%|██████▎   | 2548/4000 [24:21<16:56,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3877102136611938, Predicted Probability: 0.1998, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.679022789001465, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  64%|██████▎   | 2549/4000 [24:21<14:27,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.016420841217041, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.341165542602539, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2550/4000 [24:22<11:34,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.402716159820557, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.90085506439209, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2551/4000 [24:22<10:45,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6390180587768555, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.093584060668945, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2552/4000 [24:22<10:11,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.173311233520508, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.085675239562988, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2553/4000 [24:23<11:01,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.250744581222534, Predicted Probability: 0.9627, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.334310531616211, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2554/4000 [24:24<12:54,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5505380630493164, Predicted Probability: 0.0279, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4220850467681885, Predicted Probability: 0.9684, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2555/4000 [24:24<12:16,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.809778690338135, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9391746520996094, Predicted Probability: 0.0191, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2556/4000 [24:25<12:38,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4512768983840942, Predicted Probability: 0.8102, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.235252857208252, Predicted Probability: 0.7747, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2557/4000 [24:25<11:34,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.118880271911621, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8259193897247314, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2558/4000 [24:25<11:18,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.528997898101807, Predicted Probability: 0.0107, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.546001434326172, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2559/4000 [24:26<13:17,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.831233024597168, Predicted Probability: 0.9443, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.900432109832764, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2560/4000 [24:27<13:43,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7106826305389404, Predicted Probability: 0.9761, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1454819440841675, Predicted Probability: 0.7587, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2561/4000 [24:28<15:05,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.168718338012695, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.191746234893799, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2562/4000 [24:28<16:08,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.839113235473633, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.947129249572754, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2563/4000 [24:29<16:28,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8465615510940552, Predicted Probability: 0.3002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.470288276672363, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2564/4000 [24:30<14:20,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.813689231872559, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.865427017211914, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2565/4000 [24:30<16:06,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.777193069458008, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.306947708129883, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2566/4000 [24:31<12:45,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.37863826751709, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.660784721374512, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2567/4000 [24:31<14:10,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.584295272827148, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.123008728027344, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2568/4000 [24:32<15:29,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.351847171783447, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.47755765914917, Predicted Probability: 0.9226, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2569/4000 [24:33<14:41,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.548656463623047, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.786170244216919, Predicted Probability: 0.0581, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2570/4000 [24:33<12:53,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.547083854675293, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.836633205413818, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2571/4000 [24:34<12:47,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0954275131225586, Predicted Probability: 0.9567, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.17837905883789, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2572/4000 [24:34<11:42,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.550444602966309, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.460366249084473, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2573/4000 [24:34<10:06,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.362478256225586, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.134468674659729, Predicted Probability: 0.7567, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2574/4000 [24:35<10:53,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.454766273498535, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1266632080078125, Predicted Probability: 0.8935, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2575/4000 [24:35<13:11,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.58667516708374, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.050747871398926, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2576/4000 [24:36<14:36,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4212446212768555, Predicted Probability: 0.0316, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.582535743713379, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2577/4000 [24:37<15:22,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.538434028625488, Predicted Probability: 0.0106, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9874945282936096, Predicted Probability: 0.2714, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2578/4000 [24:38<16:43,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.246150970458984, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.752595901489258, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 2/3:  64%|██████▍   | 2579/4000 [24:38<14:23,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.10485395044088364, Predicted Probability: 0.4738, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.574311256408691, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  64%|██████▍   | 2580/4000 [24:39<12:39,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.816019535064697, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.88375473022461, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2581/4000 [24:39<14:33,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.453182220458984, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.021857261657715, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  65%|██████▍   | 2582/4000 [24:40<12:50,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4861862659454346, Predicted Probability: 0.9703, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.368533611297607, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2583/4000 [24:40<11:39,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.99239444732666, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4613890647888184, Predicted Probability: 0.0786, Prediction: 0.0

Epoch 2/3:  65%|██████▍   | 2584/4000 [24:40<10:50,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.571603298187256, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.943229675292969, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2585/4000 [24:41<13:24,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.090975761413574, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.414801597595215, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  65%|██████▍   | 2586/4000 [24:42<12:07,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.359696388244629, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.599278450012207, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2587/4000 [24:42<11:08,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.939295768737793, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.574893951416016, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2588/4000 [24:43<13:19,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.867985725402832, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.420782566070557, Predicted Probability: 0.9881, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2589/4000 [24:43<11:58,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.705902099609375, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.301753520965576, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2590/4000 [24:44<11:07,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.144108295440674, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.425717353820801, Predicted Probability: 0.0315, Prediction: 0.0

Epoch 2/3:  65%|██████▍   | 2591/4000 [24:44<11:29,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.079240560531616, Predicted Probability: 0.9560, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.413932800292969, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2592/4000 [24:45<10:42,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.82108211517334, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.669689178466797, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2593/4000 [24:45<10:07,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.932868003845215, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.111135005950928, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2594/4000 [24:45<09:45,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.59507417678833, Predicted Probability: 0.9900, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.574886322021484, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2595/4000 [24:46<12:06,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.205204010009766, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.016173362731934, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2596/4000 [24:46<11:03,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.238343715667725, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.538875579833984, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2597/4000 [24:47<12:59,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.782129287719727, Predicted Probability: 0.9917, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.820631980895996, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  65%|██████▍   | 2598/4000 [24:48<14:04,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0225422382354736, Predicted Probability: 0.9536, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.53554630279541, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  65%|██████▍   | 2599/4000 [24:49<15:49,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.388040542602539, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3917391300201416, Predicted Probability: 0.9162, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2600/4000 [24:49<16:11,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.461872577667236, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8570218086242676, Predicted Probability: 0.9457, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2601/4000 [24:50<16:29,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6862711906433105, Predicted Probability: 0.0245, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.559543132781982, Predicted Probability: 0.0104, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2602/4000 [24:51<16:49,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.889629364013672, Predicted Probability: 0.9473, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4005422592163086, Predicted Probability: 0.0323, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2603/4000 [24:52<17:00,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.87678337097168, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9086661338806152, Predicted Probability: 0.0197, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2604/4000 [24:52<17:06,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.752038955688477, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.203423976898193, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2605/4000 [24:53<17:36,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.057451248168945, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5403923988342285, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2606/4000 [24:54<16:04,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.04421615600586, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7379167079925537, Predicted Probability: 0.9392, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2607/4000 [24:54<13:47,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.644371509552002, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.876626014709473, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2608/4000 [24:55<15:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.23779296875, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6846113204956055, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2609/4000 [24:56<15:34,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5252741575241089, Predicted Probability: 0.1787, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.740307331085205, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2610/4000 [24:56<14:42,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.372430324554443, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.273167133331299, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2611/4000 [24:57<15:26,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.135120391845703, Predicted Probability: 0.9843, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.632776260375977, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2612/4000 [24:57<12:16,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.050278663635254, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.887345314025879, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2613/4000 [24:57<10:26,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.073519706726074, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.739015102386475, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2614/4000 [24:58<10:21,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.350796699523926, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.980780601501465, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2615/4000 [24:59<12:31,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.067306041717529, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1940455436706543, Predicted Probability: 0.1003, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2616/4000 [24:59<14:14,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.170231342315674, Predicted Probability: 0.0152, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.249889373779297, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2617/4000 [25:00<15:18,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.932012557983398, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.75992488861084, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 2/3:  65%|██████▌   | 2618/4000 [25:01<13:27,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.809108734130859, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.711493968963623, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  65%|██████▌   | 2619/4000 [25:01<14:42,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.395604133605957, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.971165657043457, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2620/4000 [25:02<12:48,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8052315711975098, Predicted Probability: 0.0218, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.960387229919434, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2621/4000 [25:02<12:42,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.891106605529785, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5164148807525635, Predicted Probability: 0.9253, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2623/4000 [25:03<09:23,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.449355602264404, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.930893659591675, Predicted Probability: 0.0192, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.922379493713379, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.018465995788574, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2624/4000 [25:03<09:07,  2.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.488286972045898, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.007753372192383, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2625/4000 [25:04<12:00,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.748666286468506, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.629757881164551, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2626/4000 [25:04<11:24,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.679482340812683, Predicted Probability: 0.8428, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.111917495727539, Predicted Probability: 0.9839, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2627/4000 [25:05<13:33,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5116208791732788, Predicted Probability: 0.1807, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.018245697021484, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2628/4000 [25:06<14:35,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6484518051147461, Predicted Probability: 0.3433, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.437037467956543, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2629/4000 [25:07<15:31,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.43333625793457, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.287230968475342, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2630/4000 [25:07<14:35,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1340179443359375, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.944400787353516, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2631/4000 [25:08<16:18,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.504247665405273, Predicted Probability: 0.0109, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.478758335113525, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2632/4000 [25:09<15:08,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.921590566635132, Predicted Probability: 0.9489, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.209249019622803, Predicted Probability: 0.0146, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2633/4000 [25:10<15:41,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.120767116546631, Predicted Probability: 0.0423, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6187312602996826, Predicted Probability: 0.9321, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2634/4000 [25:10<13:29,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.441571235656738, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.466552257537842, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2635/4000 [25:10<11:18,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.29686450958252, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.119149208068848, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2636/4000 [25:11<12:45,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.089602470397949, Predicted Probability: 0.9565, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.849955558776855, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2637/4000 [25:12<14:08,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8293957710266113, Predicted Probability: 0.9442, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.421793937683105, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2638/4000 [25:12<15:09,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.932628631591797, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.070444583892822, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2639/4000 [25:13<14:47,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.151285171508789, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9749860763549805, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2640/4000 [25:14<14:16,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.573705196380615, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.080102920532227, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2641/4000 [25:14<15:06,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.907106399536133, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6627228260040283, Predicted Probability: 0.9348, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2642/4000 [25:15<11:57,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.786998271942139, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.66142749786377, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2643/4000 [25:15<10:48,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.084968566894531, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.50305700302124, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2644/4000 [25:15<10:33,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5912609100341797, Predicted Probability: 0.0268, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.664526104927063, Predicted Probability: 0.3397, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2645/4000 [25:16<12:34,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.470944404602051, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0058507919311523, Predicted Probability: 0.8814, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2646/4000 [25:17<13:53,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.407980918884277, Predicted Probability: 0.0120, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3725059032440186, Predicted Probability: 0.0332, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2647/4000 [25:17<12:13,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.784089088439941, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.569794178009033, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  66%|██████▌   | 2648/4000 [25:18<13:57,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.96878719329834, Predicted Probability: 0.9815, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.782821655273438, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  66%|██████▌   | 2649/4000 [25:18<12:17,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.772247791290283, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.084622383117676, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  66%|██████▋   | 2650/4000 [25:19<11:40,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.327215194702148, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.734893798828125, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  66%|██████▋   | 2652/4000 [25:20<10:51,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.446753740310669, Predicted Probability: 0.0797, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.4779276847839355, Predicted Probability: 0.0042, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.405234336853027, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.297357559204102, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  66%|██████▋   | 2653/4000 [25:20<11:14,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.253597259521484, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.574934959411621, Predicted Probability: 0.0708, Prediction: 0.0

Epoch 2/3:  66%|██████▋   | 2654/4000 [25:21<13:32,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.37667465209961, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.436990737915039, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  66%|██████▋   | 2655/4000 [25:22<13:00,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6116509437561035, Predicted Probability: 0.9737, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.0741548538208, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  66%|██████▋   | 2656/4000 [25:22<11:36,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.734976291656494, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5429031252861023, Predicted Probability: 0.3675, Prediction: 0.0

Epoch 2/3:  66%|██████▋   | 2657/4000 [25:23<10:36,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.336340427398682, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.880295276641846, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  66%|██████▋   | 2658/4000 [25:23<09:58,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.683633804321289, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.126925945281982, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  66%|██████▋   | 2659/4000 [25:24<12:26,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.615771293640137, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.08260178565979, Predicted Probability: 0.9562, Prediction: 1.0

Epoch 2/3:  66%|██████▋   | 2660/4000 [25:24<11:08,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.7604780197143555, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.057080268859863, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2661/4000 [25:24<10:21,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0579986572265625, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.172466278076172, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2662/4000 [25:25<12:12,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.695344924926758, Predicted Probability: 0.9368, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.5396554470062256, Predicted Probability: 0.8234, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2663/4000 [25:26<12:14,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.073336124420166, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.430720806121826, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2664/4000 [25:26<10:59,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3415608406066895, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.936210632324219, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2665/4000 [25:27<12:54,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.461612701416016, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8345603942871094, Predicted Probability: 0.9445, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2666/4000 [25:28<13:13,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.613600254058838, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9328628778457642, Predicted Probability: 0.1264, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2667/4000 [25:28<14:12,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.837008476257324, Predicted Probability: 0.9446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8606481552124023, Predicted Probability: 0.0541, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2668/4000 [25:29<15:04,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.747705459594727, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3012542724609375, Predicted Probability: 0.0910, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2669/4000 [25:29<13:01,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.336825370788574, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.068357467651367, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2670/4000 [25:30<11:32,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.462698936462402, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.869095325469971, Predicted Probability: 0.9924, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2671/4000 [25:31<13:11,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.854825973510742, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.548556327819824, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2672/4000 [25:31<13:59,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.159780502319336, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9530787467956543, Predicted Probability: 0.9504, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2673/4000 [25:32<12:12,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2310879230499268, Predicted Probability: 0.0380, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.381474494934082, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2675/4000 [25:33<11:13,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.306302547454834, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.75652551651001, Predicted Probability: 0.0004, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -7.804992198944092, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.916524887084961, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2676/4000 [25:33<10:17,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.985119819641113, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.601978063583374, Predicted Probability: 0.9735, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2677/4000 [25:34<12:41,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.433429718017578, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.764495849609375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2678/4000 [25:35<14:13,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.6151893138885498, Predicted Probability: 0.1659, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.341922760009766, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2679/4000 [25:35<13:30,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.067840576171875, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.399454802274704, Predicted Probability: 0.5986, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2680/4000 [25:36<12:18,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.478476524353027, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5556682348251343, Predicted Probability: 0.3646, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2681/4000 [25:36<13:22,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.636451721191406, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4177567958831787, Predicted Probability: 0.9182, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2682/4000 [25:37<12:57,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0499050617218018, Predicted Probability: 0.1141, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.568897247314453, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2683/4000 [25:38<14:09,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.533923149108887, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.111146450042725, Predicted Probability: 0.9839, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2684/4000 [25:38<12:20,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.451981544494629, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.133866786956787, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2685/4000 [25:38<09:58,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.690655708312988, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.836429119110107, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2686/4000 [25:39<11:36,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6451616287231445, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5428719520568848, Predicted Probability: 0.9271, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2687/4000 [25:40<11:39,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.840416669845581, Predicted Probability: 0.9448, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.854221343994141, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2688/4000 [25:40<12:54,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.416395664215088, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2636502981185913, Predicted Probability: 0.2203, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2689/4000 [25:41<11:28,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.350882530212402, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4489006996154785, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2690/4000 [25:41<09:24,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.638768196105957, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.00260066986084, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2691/4000 [25:42<11:38,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3281660079956055, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.597365856170654, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2692/4000 [25:42<10:31,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.149228096008301, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.77155876159668, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2693/4000 [25:43<12:15,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.240942001342773, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.076319694519043, Predicted Probability: 0.2542, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2694/4000 [25:43<13:20,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.471277236938477, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.133391857147217, Predicted Probability: 0.9842, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2695/4000 [25:44<14:14,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.827314376831055, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.485312461853027, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2696/4000 [25:45<13:38,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.124083518981934, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6298909187316895, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  67%|██████▋   | 2697/4000 [25:45<13:37,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.424809455871582, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9694125652313232, Predicted Probability: 0.9815, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2698/4000 [25:46<10:51,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.674450874328613, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5770175457000732, Predicted Probability: 0.9728, Prediction: 1.0

Epoch 2/3:  67%|██████▋   | 2699/4000 [25:46<10:01,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.728652477264404, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.231855869293213, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2700/4000 [25:46<09:26,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.610439777374268, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.790347695350647, Predicted Probability: 0.8570, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2701/4000 [25:47<11:41,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.546710968017578, Predicted Probability: 0.0280, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.062253952026367, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2702/4000 [25:48<12:52,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.040648460388184, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.629040002822876, Predicted Probability: 0.0673, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2703/4000 [25:49<13:51,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.144892692565918, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.851527214050293, Predicted Probability: 0.9792, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2704/4000 [25:49<14:25,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.022162675857544, Predicted Probability: 0.9536, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.987119674682617, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2705/4000 [25:50<11:24,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.5178937911987305, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.674510955810547, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2706/4000 [25:50<09:41,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.754082202911377, Predicted Probability: 0.0229, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.590396404266357, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2707/4000 [25:51<11:29,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.116372108459473, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.994718074798584, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2708/4000 [25:51<11:27,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4595344066619873, Predicted Probability: 0.0787, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.785236835479736, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2710/4000 [25:51<07:47,  2.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.020812034606934, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.09871768951416, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -1.7646734714508057, Predicted Probability: 0.1462, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.525753021240234, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2711/4000 [25:52<07:47,  2.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.051933288574219, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4877671003341675, Predicted Probability: 0.6196, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2712/4000 [25:53<10:13,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9631845951080322, Predicted Probability: 0.9509, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.138741493225098, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2713/4000 [25:53<09:29,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.332650184631348, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.82167911529541, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2714/4000 [25:54<12:23,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.428055763244629, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.415672302246094, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2715/4000 [25:54<11:02,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.128024101257324, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.320432662963867, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2716/4000 [25:55<12:56,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.531996726989746, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.722908973693848, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2717/4000 [25:56<13:41,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.319940567016602, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.573340892791748, Predicted Probability: 0.9291, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2718/4000 [25:56<13:05,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.836355209350586, Predicted Probability: 0.9446, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.046805381774902, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2719/4000 [25:57<13:49,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7107489109039307, Predicted Probability: 0.9761, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.126044273376465, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2720/4000 [25:57<12:04,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.378640055656433, Predicted Probability: 0.2012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.709218502044678, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2721/4000 [25:58<10:51,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.210856437683105, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.777008533477783, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2722/4000 [25:58<10:59,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.744145393371582, Predicted Probability: 0.9769, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.94404125213623, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2723/4000 [25:59<10:04,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.149132251739502, Predicted Probability: 0.1044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.19748592376709, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2724/4000 [25:59<11:50,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.258124351501465, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3453640937805176, Predicted Probability: 0.0340, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2725/4000 [26:00<13:08,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8300912380218506, Predicted Probability: 0.9788, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.175399780273438, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2726/4000 [26:01<11:32,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.439169883728027, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.043323516845703, Predicted Probability: 0.9828, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2727/4000 [26:01<11:28,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.514073848724365, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.03538179397583, Predicted Probability: 0.9826, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2728/4000 [26:02<10:59,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.101111888885498, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.115447998046875, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2729/4000 [26:02<10:31,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.492466449737549, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6583197116851807, Predicted Probability: 0.9345, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2730/4000 [26:02<10:07,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.611036777496338, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0058693885803223, Predicted Probability: 0.8814, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2731/4000 [26:03<11:53,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.262457847595215, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.918739318847656, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2732/4000 [26:04<13:11,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.681468963623047, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.52253794670105, Predicted Probability: 0.0287, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2733/4000 [26:05<14:20,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.422692775726318, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.011945962905884, Predicted Probability: 0.0469, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2734/4000 [26:06<14:44,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.97019100189209, Predicted Probability: 0.9931, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.652126312255859, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2735/4000 [26:06<14:55,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.661172389984131, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2921360731124878, Predicted Probability: 0.5725, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2736/4000 [26:06<11:43,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.133883953094482, Predicted Probability: 0.9842, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9588675498962402, Predicted Probability: 0.9813, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2737/4000 [26:07<12:42,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6144087314605713, Predicted Probability: 0.8340, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.698294639587402, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  68%|██████▊   | 2738/4000 [26:08<12:22,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9861345291137695, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.068652629852295, Predicted Probability: 0.9937, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2739/4000 [26:08<10:57,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.365516662597656, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.008195877075195, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  68%|██████▊   | 2740/4000 [26:09<12:32,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.103143215179443, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.667882919311523, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  69%|██████▊   | 2741/4000 [26:10<13:22,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9607751369476318, Predicted Probability: 0.8766, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.015403747558594, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  69%|██████▊   | 2742/4000 [26:10<11:40,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.327910423278809, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.976028442382812, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  69%|██████▊   | 2743/4000 [26:11<13:35,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.196269989013672, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.57975959777832, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 2/3:  69%|██████▊   | 2744/4000 [26:11<12:57,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.83230209350586, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.026678562164307, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:  69%|██████▊   | 2745/4000 [26:12<10:22,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.964924812316895, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.274559020996094, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  69%|██████▊   | 2746/4000 [26:12<10:38,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.810401201248169, Predicted Probability: 0.9783, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.668056488037109, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  69%|██████▊   | 2747/4000 [26:13<12:08,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.491314888000488, Predicted Probability: 0.9889, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.068854331970215, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  69%|██████▊   | 2748/4000 [26:13<11:47,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9826557636260986, Predicted Probability: 0.9817, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.001070022583008, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  69%|██████▊   | 2749/4000 [26:14<10:38,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.23944616317749, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.092521667480469, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2750/4000 [26:14<09:44,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.64901876449585, Predicted Probability: 0.0095, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.712079048156738, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2751/4000 [26:15<09:10,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.972010612487793, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.830430030822754, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2752/4000 [26:15<11:11,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3276311159133911, Predicted Probability: 0.2096, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.560434341430664, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2753/4000 [26:16<12:26,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.618766784667969, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.029272079467773, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2754/4000 [26:17<13:32,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.338508605957031, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.97464656829834, Predicted Probability: 0.0486, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2755/4000 [26:17<11:47,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.025982856750488, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.144397735595703, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2756/4000 [26:18<10:32,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.63787841796875, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8998517990112305, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2757/4000 [26:18<12:10,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.521399199962616, Predicted Probability: 0.6275, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.4890031814575195, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2758/4000 [26:19<10:55,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.155334949493408, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.748961448669434, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2759/4000 [26:19<10:03,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.77580738067627, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.189781665802002, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2760/4000 [26:20<11:57,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5044134855270386, Predicted Probability: 0.1818, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.273928165435791, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2761/4000 [26:21<13:01,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0716872215270996, Predicted Probability: 0.9557, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.818258285522461, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2762/4000 [26:21<11:34,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.550501823425293, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.39810562133789, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2763/4000 [26:22<11:23,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.428661823272705, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4372477531433105, Predicted Probability: 0.9883, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2764/4000 [26:22<09:16,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.887913227081299, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.191161155700684, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2765/4000 [26:22<08:46,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.881722450256348, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.014867782592773, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2766/4000 [26:23<11:02,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.199867248535156, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.51799201965332, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2767/4000 [26:23<10:26,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1948461532592773, Predicted Probability: 0.1002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.010105609893799, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2768/4000 [26:24<11:58,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.609124183654785, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.910202980041504, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2769/4000 [26:25<10:35,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.320037841796875, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.130867004394531, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2770/4000 [26:25<10:43,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.816451549530029, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.753537654876709, Predicted Probability: 0.9771, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2771/4000 [26:26<10:46,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0332446098327637, Predicted Probability: 0.1158, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.431943416595459, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2772/4000 [26:26<11:57,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7930006980895996, Predicted Probability: 0.9423, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.5413079261779785, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2773/4000 [26:27<11:37,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.275853157043457, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.800594449043274, Predicted Probability: 0.1418, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2774/4000 [26:27<11:23,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.539590358734131, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3759796619415283, Predicted Probability: 0.0331, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2775/4000 [26:28<10:38,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.787834882736206, Predicted Probability: 0.0221, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.79274845123291, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  69%|██████▉   | 2776/4000 [26:28<10:43,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.704801559448242, Predicted Probability: 0.9760, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.937727451324463, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2777/4000 [26:29<09:46,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.5660829544067383, Predicted Probability: 0.9286, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.033705711364746, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  69%|██████▉   | 2778/4000 [26:29<11:22,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.373210906982422, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4840569496154785, Predicted Probability: 0.1848, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2780/4000 [26:30<09:02,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9416422843933105, Predicted Probability: 0.0190, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.724266052246094, Predicted Probability: 0.0004, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.397356986999512, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.648663520812988, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2781/4000 [26:31<08:37,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.077178955078125, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.944024562835693, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2782/4000 [26:31<10:25,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.722079277038574, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9921669960021973, Predicted Probability: 0.9522, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2783/4000 [26:32<08:32,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.096138954162598, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.684696197509766, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2784/4000 [26:32<08:20,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.938589096069336, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.606998920440674, Predicted Probability: 0.0099, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2785/4000 [26:33<10:27,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.744100570678711, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8884158134460449, Predicted Probability: 0.7086, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2786/4000 [26:33<09:37,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.0994873046875, Predicted Probability: 0.0163, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.710831642150879, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2787/4000 [26:34<10:12,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.712808609008789, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.680193901062012, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2788/4000 [26:34<11:53,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.449794292449951, Predicted Probability: 0.9885, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.903725624084473, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2789/4000 [26:35<13:20,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9347310066223145, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.995605945587158, Predicted Probability: 0.0181, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2790/4000 [26:36<11:34,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.0358076095581055, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.930552959442139, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2791/4000 [26:36<12:28,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.303244709968567, Predicted Probability: 0.7864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.721031188964844, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2792/4000 [26:37<10:58,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.51338529586792, Predicted Probability: 0.0108, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.23111629486084, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2793/4000 [26:37<09:53,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.368340492248535, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.058906555175781, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2794/4000 [26:38<11:35,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2538435459136963, Predicted Probability: 0.2220, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.426492691040039, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2795/4000 [26:38<10:21,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.267432928085327, Predicted Probability: 0.9061, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.074920177459717, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2796/4000 [26:38<08:32,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.813634872436523, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.8460817337036133, Predicted Probability: 0.3003, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2797/4000 [26:39<10:40,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.45683479309082, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.327378749847412, Predicted Probability: 0.2096, Prediction: 0.0

Epoch 2/3:  70%|██████▉   | 2798/4000 [26:40<10:05,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.100196838378906, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.320378303527832, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  70%|██████▉   | 2799/4000 [26:40<09:17,  2.15it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6140336990356445, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.347323417663574, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2801/4000 [26:41<07:17,  2.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.735723972320557, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.420346736907959, Predicted Probability: 0.9984, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.178775787353516, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.898009300231934, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2802/4000 [26:41<09:34,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.139666557312012, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.046137809753418, Predicted Probability: 0.9828, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2803/4000 [26:42<08:52,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.993415832519531, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.768356800079346, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  70%|███████   | 2804/4000 [26:42<10:41,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.269567489624023, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.799199104309082, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2805/4000 [26:43<08:46,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.3013334274292, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.73398208618164, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2806/4000 [26:43<10:30,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.33444595336914, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1412668228149414, Predicted Probability: 0.8948, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2807/4000 [26:44<11:46,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.818473815917969, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.291891098022461, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  70%|███████   | 2808/4000 [26:45<11:35,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.337922096252441, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.7306389808654785, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2809/4000 [26:46<12:57,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.849530220031738, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.446349143981934, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:  70%|███████   | 2811/4000 [26:46<08:40,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.651311874389648, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.082024574279785, Predicted Probability: 0.9992, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -7.298861980438232, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.768940448760986, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  70%|███████   | 2812/4000 [26:47<10:47,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.601288795471191, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8865966796875, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  70%|███████   | 2813/4000 [26:47<09:42,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.1878557205200195, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.555752754211426, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2814/4000 [26:48<12:33,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.764944076538086, Predicted Probability: 0.0226, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.380583763122559, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  70%|███████   | 2815/4000 [26:49<11:04,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.159109115600586, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.488126754760742, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2816/4000 [26:49<09:00,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.926903247833252, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.324275016784668, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2817/4000 [26:49<09:31,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1550867557525635, Predicted Probability: 0.9591, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.045514106750488, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2818/4000 [26:50<11:00,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.740751266479492, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.314732074737549, Predicted Probability: 0.9868, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2819/4000 [26:50<10:22,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.757583618164062, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.479169845581055, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 2/3:  70%|███████   | 2820/4000 [26:51<11:43,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.997053146362305, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.870804786682129, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2821/4000 [26:52<12:32,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5118260383605957, Predicted Probability: 0.8193, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.936309814453125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2822/4000 [26:53<13:22,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.993582725524902, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.46125656366348267, Predicted Probability: 0.3867, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2823/4000 [26:53<13:42,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.082825183868408, Predicted Probability: 0.9562, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.438627243041992, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2824/4000 [26:54<14:26,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.842347145080566, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.110578536987305, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2825/4000 [26:55<12:42,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5303263664245605, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.09391450881958, Predicted Probability: 0.9939, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2826/4000 [26:55<11:11,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.831766605377197, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.664948463439941, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2827/4000 [26:56<12:14,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5559308528900146, Predicted Probability: 0.0278, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 4.103333473205566, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2828/4000 [26:56<11:46,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.296505451202393, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3997727632522583, Predicted Probability: 0.8021, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2829/4000 [26:57<09:47,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.619976043701172, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.3831787109375, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2830/4000 [26:57<09:58,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.921574115753174, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.375972270965576, Predicted Probability: 0.9876, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2831/4000 [26:58<11:50,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.363643646240234, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.674503326416016, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2832/4000 [26:58<09:50,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.538990497589111, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.318120956420898, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2834/4000 [26:59<09:09,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.025543212890625, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7870047092437744, Predicted Probability: 0.9778, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.587283611297607, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.403759956359863, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2835/4000 [27:00<10:45,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.47164535522461, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8375015258789062, Predicted Probability: 0.0211, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2836/4000 [27:01<14:10,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.036593437194824, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9753289222717285, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2837/4000 [27:02<12:27,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.703781127929688, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.710171699523926, Predicted Probability: 0.0239, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2838/4000 [27:02<13:28,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.395233154296875, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.950741767883301, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2839/4000 [27:03<13:36,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.792269468307495, Predicted Probability: 0.9423, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.648160457611084, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2840/4000 [27:04<13:51,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.593771934509277, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.617847204208374, Predicted Probability: 0.9739, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2841/4000 [27:05<14:12,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.501899719238281, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.343836307525635, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2842/4000 [27:06<14:30,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.191679000854492, Predicted Probability: 0.0149, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.944101333618164, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2843/4000 [27:06<11:19,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.607804775238037, Predicted Probability: 0.0099, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.631511688232422, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2844/4000 [27:06<10:03,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.547171592712402, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.71203899383545, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2845/4000 [27:06<09:13,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.946293354034424, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9367825984954834, Predicted Probability: 0.0191, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2846/4000 [27:07<11:36,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.08687686920166, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.927603721618652, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 2/3:  71%|███████   | 2847/4000 [27:08<10:15,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.426539897918701, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.986923694610596, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2848/4000 [27:08<08:23,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.980506896972656, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.266918182373047, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  71%|███████   | 2849/4000 [27:09<09:59,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.774531364440918, Predicted Probability: 0.9776, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.662260055541992, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2850/4000 [27:09<11:38,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.864597797393799, Predicted Probability: 0.0205, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.096110820770264, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2851/4000 [27:10<12:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4555507302284241, Predicted Probability: 0.3880, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.167354106903076, Predicted Probability: 0.0153, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2852/4000 [27:11<12:48,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.141042232513428, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.379956007003784, Predicted Probability: 0.9153, Prediction: 1.0

Epoch 2/3:  71%|███████▏  | 2853/4000 [27:12<13:11,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.238224506378174, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5199228525161743, Predicted Probability: 0.3729, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2854/4000 [27:12<13:23,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0037901401519775, Predicted Probability: 0.2682, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.322168827056885, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2855/4000 [27:13<11:32,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.693009853363037, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.340103149414062, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  71%|███████▏  | 2856/4000 [27:13<12:13,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.425447940826416, Predicted Probability: 0.1938, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.753722190856934, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2857/4000 [27:14<13:07,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.226890563964844, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.737973690032959, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2858/4000 [27:15<13:33,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.834120988845825, Predicted Probability: 0.9445, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.870452880859375, Predicted Probability: 0.0536, Prediction: 0.0

Epoch 2/3:  71%|███████▏  | 2859/4000 [27:16<11:57,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.878880023956299, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.5172038078308105, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2860/4000 [27:16<11:27,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.451900959014893, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6643215417861938, Predicted Probability: 0.1592, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2861/4000 [27:17<11:10,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4474005699157715, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.368962287902832, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2862/4000 [27:17<09:57,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.551456928253174, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.3657097816467285, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2863/4000 [27:17<08:06,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.097196578979492, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6506028175354, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2864/4000 [27:18<07:48,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.219749450683594, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.183421611785889, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2866/4000 [27:19<08:01,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.121058464050293, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.341061592102051, Predicted Probability: 0.9982, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -4.882497310638428, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.696514129638672, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2867/4000 [27:19<09:42,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.658485412597656, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2131452560424805, Predicted Probability: 0.2291, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2868/4000 [27:20<09:58,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.161214351654053, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.011686325073242, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2869/4000 [27:21<11:03,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.121078491210938, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6240952014923096, Predicted Probability: 0.9324, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2871/4000 [27:21<09:27,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.349291801452637, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.904334783554077, Predicted Probability: 0.0198, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.532549858093262, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.049646854400635, Predicted Probability: 0.9829, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2872/4000 [27:22<07:46,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.634440422058105, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.848657608032227, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2873/4000 [27:22<07:30,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.584444999694824, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.4838160276412964, Predicted Probability: 0.8151, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2874/4000 [27:22<07:26,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.773435592651367, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.798979759216309, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2875/4000 [27:23<09:28,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.559420108795166, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.313751220703125, Predicted Probability: 0.0351, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2876/4000 [27:23<07:50,  2.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.971747398376465, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.684586524963379, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2877/4000 [27:24<07:36,  2.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.2207255363464355, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.006610870361328, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2878/4000 [27:24<07:30,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.911681652069092, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.613822937011719, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2879/4000 [27:25<08:39,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.28488540649414, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.046889305114746, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2880/4000 [27:25<09:09,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.191192626953125, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.035542011260986, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2882/4000 [27:26<07:43,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.564116954803467, Predicted Probability: 0.9285, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.480522394180298, Predicted Probability: 0.0772, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 0.5816686749458313, Predicted Probability: 0.6415, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.410304069519043, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2883/4000 [27:26<07:23,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.635591983795166, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.4716668128967285, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2884/4000 [27:27<07:13,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.97398042678833, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.702441215515137, Predicted Probability: 0.9910, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2885/4000 [27:28<09:28,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.7723541259765625, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.138525485992432, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2886/4000 [27:28<07:46,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.597544193267822, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.9117112159729, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2887/4000 [27:28<07:30,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.746952056884766, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.407176971435547, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2888/4000 [27:29<08:18,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.290447235107422, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.213008880615234, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2889/4000 [27:29<06:57,  2.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.384049415588379, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.988687515258789, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2890/4000 [27:30<09:01,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.352706909179688, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8039023876190186, Predicted Probability: 0.9429, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2891/4000 [27:30<10:35,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.561037063598633, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.647418260574341, Predicted Probability: 0.9339, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2892/4000 [27:31<11:43,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.0029127597808838, Predicted Probability: 0.7316, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.020936965942383, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2893/4000 [27:32<12:23,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.327538967132568, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3692626953125, Predicted Probability: 0.0333, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2894/4000 [27:33<12:56,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.887720108032227, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.323157787322998, Predicted Probability: 0.7897, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2895/4000 [27:34<13:31,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9640960693359375, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.844061851501465, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2896/4000 [27:34<12:29,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.794524192810059, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -2.646578788757324, Predicted Probability: 0.0662, Prediction: 0.0

Epoch 2/3:  72%|███████▏  | 2897/4000 [27:35<12:00,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.031817436218262, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.921635866165161, Predicted Probability: 0.9489, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2898/4000 [27:35<10:30,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.380607604980469, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.154047012329102, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 2/3:  72%|███████▏  | 2899/4000 [27:36<11:32,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.965961456298828, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.540599822998047, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 2/3:  72%|███████▎  | 2900/4000 [27:37<12:13,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.031698226928711, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3825089931488037, Predicted Probability: 0.9155, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2901/4000 [27:37<12:46,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9618031978607178, Predicted Probability: 0.9813, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.027884006500244, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2902/4000 [27:38<10:59,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4927964210510254, Predicted Probability: 0.9705, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.872211933135986, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2903/4000 [27:39<11:57,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.015007972717285, Predicted Probability: 0.8824, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.724155426025391, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2904/4000 [27:39<12:25,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.780134677886963, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4976177215576172, Predicted Probability: 0.1828, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2905/4000 [27:40<10:46,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.806927680969238, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.833012104034424, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2906/4000 [27:40<11:53,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9521632194519043, Predicted Probability: 0.9811, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.540825366973877, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2907/4000 [27:41<10:28,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.255318641662598, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.742589950561523, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2908/4000 [27:42<11:50,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8448822498321533, Predicted Probability: 0.0209, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.0900932252407074, Predicted Probability: 0.4775, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2909/4000 [27:42<11:15,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.000496864318848, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.851291179656982, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2910/4000 [27:43<11:55,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6429345607757568, Predicted Probability: 0.6554, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.586459159851074, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2911/4000 [27:43<10:26,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.881356716156006, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1159796714782715, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2912/4000 [27:44<09:26,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.880367279052734, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.502459168434143, Predicted Probability: 0.8179, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2913/4000 [27:44<08:42,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.33780574798584, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.362210273742676, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2914/4000 [27:45<10:10,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2866098880767822, Predicted Probability: 0.0360, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.112608909606934, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2916/4000 [27:46<08:03,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.236212730407715, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.268234729766846, Predicted Probability: 0.0007, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.800577163696289, Predicted Probability: 0.9918, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.417674541473389, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2917/4000 [27:46<06:43,  2.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.240750789642334, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.063311576843262, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2918/4000 [27:46<07:05,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.372281074523926, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2262110710144043, Predicted Probability: 0.9618, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2919/4000 [27:46<06:05,  2.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.953593254089355, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.699749946594238, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2920/4000 [27:47<06:12,  2.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.329129219055176, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.232105255126953, Predicted Probability: 0.9031, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2921/4000 [27:47<07:13,  2.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.294666290283203, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8394289016723633, Predicted Probability: 0.9789, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2922/4000 [27:48<09:05,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.712327241897583, Predicted Probability: 0.9378, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.211292266845703, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2923/4000 [27:49<08:26,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.577474117279053, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.410369873046875, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2924/4000 [27:49<09:53,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.443181037902832, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.642983436584473, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2925/4000 [27:50<11:04,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.398268699645996, Predicted Probability: 0.0121, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.613036155700684, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2926/4000 [27:51<10:39,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.253632068634033, Predicted Probability: 0.0140, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2242960929870605, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2927/4000 [27:51<11:28,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.849887728691101, Predicted Probability: 0.8641, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.564521789550781, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2928/4000 [27:52<11:55,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.000382423400879, Predicted Probability: 0.0067, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.638377666473389, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2929/4000 [27:53<12:23,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.5489959716796875, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0497281551361084, Predicted Probability: 0.9548, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2930/4000 [27:54<12:30,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.590829372406006, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7777223587036133, Predicted Probability: 0.9776, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2931/4000 [27:54<12:50,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.986771583557129, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.701572895050049, Predicted Probability: 0.9910, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2932/4000 [27:55<13:05,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.422483921051025, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.4083099365234375, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2933/4000 [27:55<11:06,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.306126594543457, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.571492671966553, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2934/4000 [27:56<12:02,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3062543869018555, Predicted Probability: 0.0354, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7734551429748535, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2935/4000 [27:57<12:22,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6924080848693848, Predicted Probability: 0.9366, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.991880416870117, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2936/4000 [27:58<11:35,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.677757740020752, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.536003589630127, Predicted Probability: 0.9717, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2937/4000 [27:58<09:34,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.927319049835205, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.607924938201904, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  73%|███████▎  | 2938/4000 [27:58<09:33,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4615776538848877, Predicted Probability: 0.8118, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3375396728515625, Predicted Probability: 0.0881, Prediction: 0.0

Epoch 2/3:  73%|███████▎  | 2939/4000 [27:59<09:32,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.735297679901123, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.370941162109375, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:  74%|███████▎  | 2940/4000 [27:59<09:38,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.736664295196533, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.935699939727783, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 2/3:  74%|███████▎  | 2941/4000 [28:00<09:37,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5577030181884766, Predicted Probability: 0.9723, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.243042945861816, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  74%|███████▎  | 2942/4000 [28:01<10:35,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.694988965988159, Predicted Probability: 0.9367, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.853757858276367, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  74%|███████▎  | 2943/4000 [28:01<09:22,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8798143267631531, Predicted Probability: 0.7068, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.549692153930664, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  74%|███████▎  | 2944/4000 [28:01<07:38,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.60177230834961, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.437580108642578, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  74%|███████▎  | 2946/4000 [28:02<06:11,  2.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.8177490234375, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.913451194763184, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.917871475219727, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.161705017089844, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  74%|███████▎  | 2947/4000 [28:02<06:21,  2.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.151856899261475, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.577357292175293, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  74%|███████▎  | 2948/4000 [28:03<07:18,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.775218486785889, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.4594815969467163, Predicted Probability: 0.6129, Prediction: 1.0

Epoch 2/3:  74%|███████▎  | 2949/4000 [28:04<09:11,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.092746734619141, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6049859523773193, Predicted Probability: 0.3532, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2950/4000 [28:04<10:21,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.07594126462936401, Predicted Probability: 0.5190, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1946330070495605, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2951/4000 [28:05<11:21,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.700875282287598, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.406498908996582, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2952/4000 [28:06<11:51,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.441413879394531, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.48867130279541, Predicted Probability: 0.9233, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2953/4000 [28:07<12:06,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.977818965911865, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7950634956359863, Predicted Probability: 0.9424, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2954/4000 [28:07<12:43,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.839282512664795, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.323295593261719, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2955/4000 [28:08<12:45,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.643160581588745, Predicted Probability: 0.9336, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.415440559387207, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2956/4000 [28:08<10:51,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8611233234405518, Predicted Probability: 0.0541, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.315484523773193, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2957/4000 [28:09<09:32,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.007149696350098, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3449506759643555, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2958/4000 [28:09<08:34,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7593674659729, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.745256423950195, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2959/4000 [28:09<07:04,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.500813484191895, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.772246360778809, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2960/4000 [28:10<08:04,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.322975158691406, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.180936336517334, Predicted Probability: 0.1015, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2961/4000 [28:11<08:28,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.61158275604248, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.40640115737915, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2962/4000 [28:11<08:16,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9822468757629395, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.600050449371338, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2963/4000 [28:12<08:42,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.149377822875977, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.331750392913818, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2964/4000 [28:12<09:49,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.417180061340332, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6029891967773438, Predicted Probability: 0.9311, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2965/4000 [28:13<08:49,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.611275672912598, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.70314884185791, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2966/4000 [28:13<10:14,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.939638137817383, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.587571859359741, Predicted Probability: 0.0699, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2967/4000 [28:14<09:05,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.293194770812988, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.110954761505127, Predicted Probability: 0.0161, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2968/4000 [28:15<10:20,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.862680435180664, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0446062088012695, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2969/4000 [28:15<11:05,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.640816688537598, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.122653484344482, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2970/4000 [28:16<08:51,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.764815330505371, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.422532081604004, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2971/4000 [28:16<10:05,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.633153915405273, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7372477054595947, Predicted Probability: 0.0233, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2972/4000 [28:17<09:58,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.6490960121154785, Predicted Probability: 0.9905, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.621461868286133, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2973/4000 [28:17<08:54,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.420318126678467, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.615119457244873, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2974/4000 [28:18<08:07,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.796591758728027, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.9399919509887695, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2975/4000 [28:18<08:37,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.064117431640625, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.919511318206787, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2976/4000 [28:19<09:55,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.665827751159668, Predicted Probability: 0.1590, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.608590126037598, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 2/3:  74%|███████▍  | 2977/4000 [28:19<07:59,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.048583507537842, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.83269214630127, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2978/4000 [28:20<07:31,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.318985939025879, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.11069393157959, Predicted Probability: 0.9839, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2979/4000 [28:20<07:12,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.510260581970215, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.126795768737793, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  74%|███████▍  | 2980/4000 [28:20<07:19,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.872617721557617, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.739740371704102, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2981/4000 [28:21<07:52,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.14078950881958, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.386204957962036, Predicted Probability: 0.9158, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2982/4000 [28:22<08:17,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.400275707244873, Predicted Probability: 0.0121, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.110400199890137, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2983/4000 [28:22<08:34,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.11556077003479, Predicted Probability: 0.2468, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.316961765289307, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2984/4000 [28:23<08:18,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.985154151916504, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.226015090942383, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2985/4000 [28:23<09:30,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5419354438781738, Predicted Probability: 0.3677, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.435510635375977, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2986/4000 [28:24<08:36,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.977550506591797, Predicted Probability: 0.0184, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.149205207824707, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2987/4000 [28:25<14:44,  1.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.7621573209762573, Predicted Probability: 0.3182, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.900974750518799, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2988/4000 [28:26<14:03,  1.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.404866099357605, Predicted Probability: 0.1970, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.642053604125977, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2989/4000 [28:27<12:32,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.274446487426758, Predicted Probability: 0.9863, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.119114398956299, Predicted Probability: 0.1073, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2990/4000 [28:27<11:59,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.331082820892334, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5493125915527344, Predicted Probability: 0.9721, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2991/4000 [28:28<10:15,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.053560733795166, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.313020706176758, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2992/4000 [28:28<10:57,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.366759300231934, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.02473521232605, Predicted Probability: 0.0463, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2993/4000 [28:29<11:29,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.962016582489014, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8881335258483887, Predicted Probability: 0.8685, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2994/4000 [28:30<09:54,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.584096431732178, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.539032220840454, Predicted Probability: 0.9268, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2995/4000 [28:30<10:37,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1908388137817383, Predicted Probability: 0.2331, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.651586532592773, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2996/4000 [28:31<10:29,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.421679496765137, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.801115989685059, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 2/3:  75%|███████▍  | 2997/4000 [28:32<10:57,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0412914752960205, Predicted Probability: 0.9544, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.065183639526367, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2998/4000 [28:32<11:19,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.8976149559021, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.666530132293701, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  75%|███████▍  | 2999/4000 [28:33<09:46,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.836827754974365, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8893576860427856, Predicted Probability: 0.1313, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3000/4000 [28:34<11:06,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.9921293258667, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.04025936126709, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3001/4000 [28:34<09:36,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.892370223999023, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7599873542785645, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3002/4000 [28:35<10:17,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.666368246078491, Predicted Probability: 0.0249, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.925269603729248, Predicted Probability: 0.9491, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3003/4000 [28:35<08:14,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.219211578369141, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.103774070739746, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3004/4000 [28:35<08:25,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.440133094787598, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.595027208328247, Predicted Probability: 0.9733, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3006/4000 [28:36<07:37,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7765979766845703, Predicted Probability: 0.9414, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.812769889831543, Predicted Probability: 0.0004, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: -1.816439151763916, Predicted Probability: 0.1399, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.288459777832031, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3007/4000 [28:37<08:24,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.07542610168457, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.394908428192139, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3008/4000 [28:38<09:59,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4206342697143555, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.702195167541504, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3009/4000 [28:38<08:46,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.311364650726318, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.595202922821045, Predicted Probability: 0.0100, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3011/4000 [28:39<07:57,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.146574974060059, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.965924263000488, Predicted Probability: 0.9991, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -3.955061435699463, Predicted Probability: 0.0188, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.537745475769043, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3012/4000 [28:39<06:35,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.2918877601623535, Predicted Probability: 0.0135, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.886696815490723, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3013/4000 [28:40<08:08,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.961677074432373, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.721022367477417, Predicted Probability: 0.9383, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3014/4000 [28:41<09:50,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7860829830169678, Predicted Probability: 0.0581, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.213342666625977, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3015/4000 [28:41<08:40,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.921234130859375, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.445013999938965, Predicted Probability: 0.0309, Prediction: 0.0

Epoch 2/3:  75%|███████▌  | 3016/4000 [28:42<09:43,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.900428771972656, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.824243545532227, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3017/4000 [28:42<08:39,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.636546611785889, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.169532299041748, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3018/4000 [28:43<09:45,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.914926052093506, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.672170400619507, Predicted Probability: 0.9354, Prediction: 1.0

Epoch 2/3:  75%|███████▌  | 3019/4000 [28:44<10:32,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.8418800234794617, Predicted Probability: 0.6989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.787837982177734, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3020/4000 [28:45<11:06,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.654419898986816, Predicted Probability: 0.9906, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.022211074829102, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3021/4000 [28:45<11:38,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.530813455581665, Predicted Probability: 0.9263, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.417971611022949, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3022/4000 [28:46<10:48,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.740536212921143, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.683055400848389, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3023/4000 [28:46<10:08,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.261213302612305, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6533682346343994, Predicted Probability: 0.9342, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3024/4000 [28:47<10:42,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.330366134643555, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3426260948181152, Predicted Probability: 0.9123, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3025/4000 [28:48<10:58,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.00339126586914, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7721691131591797, Predicted Probability: 0.1453, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3026/4000 [28:49<11:47,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.973140239715576, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.388949871063232, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3027/4000 [28:49<10:06,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.826643466949463, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.368818283081055, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3028/4000 [28:50<08:55,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.514699935913086, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.124549865722656, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3029/4000 [28:50<07:15,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.642068862915039, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 8.183837890625, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3030/4000 [28:50<06:47,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.19882583618164, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.706792831420898, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3031/4000 [28:51<09:04,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.747591972351074, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.437454223632812, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3032/4000 [28:52<10:30,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.910306930541992, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.13038444519043, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3033/4000 [28:52<09:09,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0584843158721924, Predicted Probability: 0.0449, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.730567455291748, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3034/4000 [28:53<10:00,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.493188381195068, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.499833106994629, Predicted Probability: 0.9241, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3035/4000 [28:54<11:10,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.174500465393066, Predicted Probability: 0.0151, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.925178050994873, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3036/4000 [28:55<11:28,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.791192054748535, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.355684995651245, Predicted Probability: 0.9134, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3037/4000 [28:55<11:39,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.498707294464111, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.094000816345215, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3038/4000 [28:56<09:58,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.398467063903809, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.708855628967285, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3039/4000 [28:56<10:28,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.725248336791992, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4117227792739868, Predicted Probability: 0.1960, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3040/4000 [28:57<10:48,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.446979522705078, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6083801984786987, Predicted Probability: 0.1668, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3041/4000 [28:58<10:13,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.264257907867432, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.220734596252441, Predicted Probability: 0.9855, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3042/4000 [28:58<10:39,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.917013168334961, Predicted Probability: 0.0195, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.018003463745117, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3043/4000 [28:59<10:03,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.168857574462891, Predicted Probability: 0.0152, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3225085735321045, Predicted Probability: 0.5799, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3044/4000 [28:59<08:49,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.751362323760986, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.947370529174805, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3045/4000 [29:00<09:48,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.742725372314453, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5140178203582764, Predicted Probability: 0.9711, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3046/4000 [29:01<10:21,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8008424043655396, Predicted Probability: 0.1417, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.590512275695801, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  76%|███████▌  | 3047/4000 [29:01<09:52,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.659071922302246, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.56612491607666, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  76%|███████▌  | 3049/4000 [29:02<07:17,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.426611423492432, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.130396842956543, Predicted Probability: 0.8938, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.584712028503418, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.146610260009766, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3050/4000 [29:03<07:44,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.643208503723145, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.652793884277344, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  76%|███████▋  | 3051/4000 [29:04<09:29,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.616207599639893, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.238333702087402, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3052/4000 [29:04<10:09,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.036620140075684, Predicted Probability: 0.9826, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.428531646728516, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3053/4000 [29:05<08:58,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.520174026489258, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.371782302856445, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  76%|███████▋  | 3054/4000 [29:05<09:52,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5100098848342896, Predicted Probability: 0.1809, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.754204750061035, Predicted Probability: 0.9402, Prediction: 1.0

Epoch 2/3:  76%|███████▋  | 3055/4000 [29:06<08:42,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.627151489257812, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.950894594192505, Predicted Probability: 0.9503, Prediction: 1.0

Epoch 2/3:  76%|███████▋  | 3056/4000 [29:07<09:37,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.197990417480469, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.457061767578125, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3057/4000 [29:07<10:03,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6120808124542236, Predicted Probability: 0.9316, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.242020606994629, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3058/4000 [29:08<10:30,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.449361801147461, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.718310356140137, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3059/4000 [29:08<09:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0446977615356445, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.347497463226318, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  76%|███████▋  | 3060/4000 [29:09<09:46,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9218946695327759, Predicted Probability: 0.1277, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.808992862701416, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3061/4000 [29:10<10:34,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.563020706176758, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.282549858093262, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3062/4000 [29:10<09:13,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.84440803527832, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.19182634353637695, Predicted Probability: 0.5478, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3063/4000 [29:11<10:06,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.116851806640625, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.898784637451172, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3064/4000 [29:11<08:00,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.095918655395508, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.750888824462891, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3065/4000 [29:11<06:36,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.32456111907959, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.509230613708496, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3066/4000 [29:12<06:21,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.518737316131592, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.206084251403809, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3067/4000 [29:13<08:09,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.420525074005127, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7191431522369385, Predicted Probability: 0.6724, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3068/4000 [29:13<07:26,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.027606964111328, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.112471580505371, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3069/4000 [29:14<08:02,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.494480013847351, Predicted Probability: 0.8167, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.527657985687256, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3070/4000 [29:14<08:30,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.013199806213379, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.921759128570557, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3071/4000 [29:15<09:22,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5809149742126465, Predicted Probability: 0.0704, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.288263320922852, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3072/4000 [29:15<08:16,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.613524436950684, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.13365650177002, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3073/4000 [29:16<09:31,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.315659999847412, Predicted Probability: 0.0350, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.37544059753418, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3074/4000 [29:17<10:00,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.237462997436523, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6997270584106445, Predicted Probability: 0.1545, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3075/4000 [29:17<09:28,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.422804355621338, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3138115406036377, Predicted Probability: 0.0351, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3076/4000 [29:18<10:02,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.523614883422852, Predicted Probability: 0.9893, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.44338321685791, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3077/4000 [29:19<09:03,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.929110050201416, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4007562398910522, Predicted Probability: 0.8023, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3078/4000 [29:19<08:23,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.28402042388916, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.24749231338501, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3079/4000 [29:20<09:52,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.488686561584473, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.078258991241455, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3080/4000 [29:20<08:39,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.707364082336426, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.149184465408325, Predicted Probability: 0.1044, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3081/4000 [29:21<09:23,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.117908477783203, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4600744247436523, Predicted Probability: 0.9213, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3082/4000 [29:21<08:17,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.671886444091797, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.497037887573242, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3083/4000 [29:22<09:24,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0166521072387695, Predicted Probability: 0.0467, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.087611198425293, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3084/4000 [29:23<09:03,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.114513397216797, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7519092559814453, Predicted Probability: 0.0229, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3085/4000 [29:23<08:46,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8066515922546387, Predicted Probability: 0.9783, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.726364135742188, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3086/4000 [29:24<09:43,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.954244613647461, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.332341194152832, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3087/4000 [29:25<10:07,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.695242404937744, Predicted Probability: 0.9367, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.010193824768066, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3088/4000 [29:26<10:29,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5198278427124023, Predicted Probability: 0.9255, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.063233375549316, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3089/4000 [29:26<10:41,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6514153480529785, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.328808307647705, Predicted Probability: 0.9654, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3090/4000 [29:27<09:09,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.660082817077637, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5683441162109375, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3091/4000 [29:27<09:44,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.508793830871582, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3898963928222656, Predicted Probability: 0.9161, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3092/4000 [29:28<08:30,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.864135265350342, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.465865135192871, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3093/4000 [29:28<09:12,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9528194069862366, Predicted Probability: 0.7217, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.989738464355469, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  77%|███████▋  | 3094/4000 [29:29<08:06,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.619696617126465, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.270123481750488, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3095/4000 [29:29<08:08,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.206779479980469, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.06604290008545, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3096/4000 [29:30<07:24,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.062986373901367, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.052663803100586, Predicted Probability: 0.9829, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.774012088775635, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.092807292938232, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3098/4000 [29:30<06:39,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9457564353942871, Predicted Probability: 0.7203, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1267812252044678, Predicted Probability: 0.8935, Prediction: 1.0

Epoch 2/3:  77%|███████▋  | 3099/4000 [29:31<08:11,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.655925989151001, Predicted Probability: 0.0252, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.539178848266602, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3100/4000 [29:32<09:16,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.987421989440918, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.665833473205566, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3101/4000 [29:32<08:11,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.443955421447754, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.231225967407227, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3102/4000 [29:33<09:06,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5322465896606445, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.817691802978516, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3103/4000 [29:34<09:31,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2860286831855774, Predicted Probability: 0.5710, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0159430503845215, Predicted Probability: 0.9533, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3104/4000 [29:34<08:24,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.329349517822266, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.317112922668457, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3105/4000 [29:35<09:13,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.275079727172852, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.370375871658325, Predicted Probability: 0.0855, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3106/4000 [29:36<10:01,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0419931411743164, Predicted Probability: 0.8851, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6792378425598145, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3107/4000 [29:36<08:46,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.11208711564540863, Predicted Probability: 0.5280, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.438138961791992, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3108/4000 [29:36<07:20,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.054770469665527, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.361669540405273, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3109/4000 [29:37<08:33,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.0119547843933105, Predicted Probability: 0.9822, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.845252990722656, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3110/4000 [29:38<09:15,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.051323890686035, Predicted Probability: 0.9829, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.234650611877441, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3111/4000 [29:39<08:50,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.348387241363525, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.960441589355469, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3112/4000 [29:39<09:33,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.352031707763672, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9662506580352783, Predicted Probability: 0.0186, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3113/4000 [29:40<09:58,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0666453838348389, Predicted Probability: 0.2560, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.404046058654785, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3114/4000 [29:41<10:18,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.08836030960083, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9639029502868652, Predicted Probability: 0.0186, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3115/4000 [29:42<10:25,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.391925811767578, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.318649023771286, Predicted Probability: 0.5790, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3116/4000 [29:42<09:16,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.07178783416748, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.563932418823242, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3117/4000 [29:42<08:51,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.799060821533203, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.304739475250244, Predicted Probability: 0.0907, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3118/4000 [29:43<07:52,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.114449501037598, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9482498168945312, Predicted Probability: 0.0189, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3119/4000 [29:43<07:51,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.543795108795166, Predicted Probability: 0.9719, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7827301025390625, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3120/4000 [29:44<08:42,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2685790061950684, Predicted Probability: 0.0367, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6699178218841553, Predicted Probability: 0.9352, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3121/4000 [29:45<09:22,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.133345127105713, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.00225830078125, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3122/4000 [29:45<07:27,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.316162109375, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.856006622314453, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3123/4000 [29:46<08:27,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8656697273254395, Predicted Probability: 0.9461, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.43738240003585815, Predicted Probability: 0.3924, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3124/4000 [29:46<06:48,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.714887619018555, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.298016548156738, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3125/4000 [29:47<07:56,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.821725368499756, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7310409545898438, Predicted Probability: 0.9388, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3126/4000 [29:48<08:49,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.9100022315979, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.276920318603516, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3127/4000 [29:48<07:05,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.788488388061523, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.490476608276367, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3128/4000 [29:48<07:24,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8494999408721924, Predicted Probability: 0.0208, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2348198890686035, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3129/4000 [29:49<08:33,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.066376209259033, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.716176986694336, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3130/4000 [29:49<06:53,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.038965225219727, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.938069343566895, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3131/4000 [29:50<07:57,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.317694187164307, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5291507244110107, Predicted Probability: 0.9262, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3132/4000 [29:51<09:21,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.928747177124023, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9954833984375, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3133/4000 [29:52<09:45,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.343671798706055, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.233508586883545, Predicted Probability: 0.9032, Prediction: 1.0

Epoch 2/3:  78%|███████▊  | 3134/4000 [29:52<09:10,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.858842849731445, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3006503582000732, Predicted Probability: 0.2141, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3135/4000 [29:53<08:01,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.912008285522461, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.066454887390137, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3136/4000 [29:53<07:10,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.79350757598877, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9318315982818604, Predicted Probability: 0.0506, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3137/4000 [29:54<08:35,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.773631572723389, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.017939567565918, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3138/4000 [29:54<09:23,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5310535430908203, Predicted Probability: 0.0284, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.732480049133301, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3139/4000 [29:55<09:16,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.771231174468994, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.809117794036865, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  78%|███████▊  | 3140/4000 [29:56<09:50,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.152173042297363, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.935279846191406, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  79%|███████▊  | 3141/4000 [29:57<10:07,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.53513240814209, Predicted Probability: 0.0039, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5219521522521973, Predicted Probability: 0.1792, Prediction: 0.0

Epoch 2/3:  79%|███████▊  | 3142/4000 [29:57<08:40,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9225921630859375, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.459332466125488, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 2/3:  79%|███████▊  | 3143/4000 [29:57<07:43,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.619153022766113, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.042438507080078, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  79%|███████▊  | 3144/4000 [29:58<08:27,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.8241700530052185, Predicted Probability: 0.3049, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2063043117523193, Predicted Probability: 0.0992, Prediction: 0.0

Epoch 2/3:  79%|███████▊  | 3145/4000 [29:59<07:31,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.97390365600586, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.281161308288574, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  79%|███████▊  | 3147/4000 [29:59<05:41,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.017466068267822, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.463250160217285, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.964119911193848, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.915427207946777, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 2/3:  79%|███████▊  | 3148/4000 [30:00<07:04,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.314224243164062, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.201564073562622, Predicted Probability: 0.9609, Prediction: 1.0

Epoch 2/3:  79%|███████▊  | 3149/4000 [30:01<08:15,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.43796157836914, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.819659471511841, Predicted Probability: 0.9437, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3150/4000 [30:01<07:23,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.090518951416016, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.82334566116333, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3151/4000 [30:01<06:42,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.033698558807373, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.712601661682129, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3152/4000 [30:02<06:56,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.29741096496582, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.007495403289795, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3153/4000 [30:02<07:08,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.133687496185303, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.008765697479248, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3154/4000 [30:03<06:38,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.6237154006958, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9821062088012695, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3155/4000 [30:03<06:13,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.150092601776123, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.858513355255127, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3156/4000 [30:04<07:45,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.441993713378906, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.812019348144531, Predicted Probability: 0.9919, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3157/4000 [30:05<08:31,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6446075439453125, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.920661449432373, Predicted Probability: 0.9489, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3158/4000 [30:05<07:48,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.235759735107422, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1040258407592773, Predicted Probability: 0.0429, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3159/4000 [30:06<07:48,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.131928443908691, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.842332363128662, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3160/4000 [30:06<08:06,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: 5.195432662963867, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.927154541015625, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3161/4000 [30:07<08:36,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.87037467956543, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.935783863067627, Predicted Probability: 0.9496, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3162/4000 [30:07<07:34,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.223986625671387, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.278822898864746, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3163/4000 [30:08<08:18,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0952160358428955, Predicted Probability: 0.8904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.858022689819336, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3164/4000 [30:09<08:59,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.8359479904174805, Predicted Probability: 0.9921, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.937198638916016, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3165/4000 [30:10<09:31,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.108523368835449, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.18806266784668, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3166/4000 [30:11<10:06,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.498677730560303, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.132616996765137, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3167/4000 [30:11<08:34,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.940588474273682, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.803191184997559, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3169/4000 [30:12<06:36,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.894739627838135, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0500383377075195, Predicted Probability: 0.9991, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.157471656799316, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.10245418548584, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3170/4000 [30:12<06:51,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.342372417449951, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.480922698974609, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3171/4000 [30:13<07:03,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.499199867248535, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.684017658233643, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3172/4000 [30:13<06:24,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.152359962463379, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.70780086517334, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3173/4000 [30:14<07:34,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.338510036468506, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8941144943237305, Predicted Probability: 0.9476, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3174/4000 [30:14<07:06,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.23305606842041, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.214985847473145, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3175/4000 [30:15<06:29,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4069154262542725, Predicted Probability: 0.0826, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.797221183776855, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  79%|███████▉  | 3176/4000 [30:15<07:33,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.497678279876709, Predicted Probability: 0.9240, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.931908130645752, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3177/4000 [30:16<07:36,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.666696071624756, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.49304485321045, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  79%|███████▉  | 3179/4000 [30:17<05:49,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.7029876708984375, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.633598804473877, Predicted Probability: 0.0005, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.119558334350586, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.780111789703369, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3180/4000 [30:17<07:02,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.184876441955566, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6316914558410645, Predicted Probability: 0.1636, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3181/4000 [30:18<08:14,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8247599601745605, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.552845001220703, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3182/4000 [30:18<06:51,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7669596672058105, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.314594268798828, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3183/4000 [30:19<07:44,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.727296352386475, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7739957571029663, Predicted Probability: 0.8550, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3184/4000 [30:20<08:23,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.554312705993652, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.5901930928230286, Predicted Probability: 0.3566, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3185/4000 [30:21<08:50,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.105073928833008, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6009829044342041, Predicted Probability: 0.3541, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3186/4000 [30:21<09:14,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.966169357299805, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.431929588317871, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3187/4000 [30:22<09:38,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.789989948272705, Predicted Probability: 0.9421, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3386688232421875, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3188/4000 [30:22<08:20,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.431161880493164, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.10190486907959, Predicted Probability: 0.0163, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3189/4000 [30:23<06:38,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.809429168701172, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.2775297164917, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3190/4000 [30:23<07:45,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4779961109161377, Predicted Probability: 0.9226, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.27310848236084, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3192/4000 [30:24<06:41,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.542109966278076, Predicted Probability: 0.9270, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.813053131103516, Predicted Probability: 0.0004, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.641937255859375, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.303037643432617, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3193/4000 [30:25<07:38,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.917570114135742, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9736149311065674, Predicted Probability: 0.9514, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3194/4000 [30:26<07:54,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.429243087768555, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.679426193237305, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3195/4000 [30:27<08:29,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.932942867279053, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.45835018157959, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3196/4000 [30:27<08:52,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.747912406921387, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.44395923614502, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  80%|███████▉  | 3197/4000 [30:28<09:12,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.5696821212768555, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.819813251495361, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3198/4000 [30:29<08:58,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.416789531707764, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.839491128921509, Predicted Probability: 0.9789, Prediction: 1.0

Epoch 2/3:  80%|███████▉  | 3199/4000 [30:29<09:29,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0242302417755127, Predicted Probability: 0.9537, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7643842697143555, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3200/4000 [30:30<07:29,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.962775230407715, Predicted Probability: 0.9509, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.23393440246582, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3201/4000 [30:30<06:42,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2542420029640198, Predicted Probability: 0.5632, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.911500930786133, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3202/4000 [30:30<06:09,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.011164665222168, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.420501708984375, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3203/4000 [30:31<05:44,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.87824821472168, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3837708830833435, Predicted Probability: 0.5948, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3204/4000 [30:31<06:10,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.371911525726318, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.92116117477417, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3205/4000 [30:32<07:14,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.03892183303833, Predicted Probability: 0.0457, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.135632038116455, Predicted Probability: 0.9843, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3206/4000 [30:33<08:04,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7633070945739746, Predicted Probability: 0.1464, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.755152702331543, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3207/4000 [30:33<07:26,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.418841361999512, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9159932136535645, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3208/4000 [30:34<08:37,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.202412605285645, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.750237464904785, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3209/4000 [30:34<07:26,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9970874786376953, Predicted Probability: 0.2695, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.269627571105957, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3210/4000 [30:35<07:21,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.332925796508789, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.497530221939087, Predicted Probability: 0.9706, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3211/4000 [30:35<06:41,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.304888725280762, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.30443000793457, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3212/4000 [30:36<08:13,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7218475341796875, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.791313648223877, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3213/4000 [30:37<09:10,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.858852386474609, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.486278533935547, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3214/4000 [30:38<07:51,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.286179065704346, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.480456352233887, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3215/4000 [30:38<08:26,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.687958717346191, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6492815017700195, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3216/4000 [30:39<08:44,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.354128837585449, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6468048095703125, Predicted Probability: 0.9338, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3217/4000 [30:40<09:06,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.428440093994141, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.873116493225098, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3218/4000 [30:41<09:18,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.565066814422607, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.354696273803711, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  80%|████████  | 3219/4000 [30:41<08:39,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.080756187438965, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.790042400360107, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  80%|████████  | 3220/4000 [30:42<09:15,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.722869873046875, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.518882751464844, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3221/4000 [30:42<07:56,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.767558574676514, Predicted Probability: 0.9916, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.25612211227417, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3222/4000 [30:43<06:57,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.454972267150879, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.62976598739624, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3223/4000 [30:43<06:20,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.45401930809021, Predicted Probability: 0.0306, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.139363288879395, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3224/4000 [30:44<07:20,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5786542892456055, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.175230979919434, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3225/4000 [30:45<08:05,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.609694957733154, Predicted Probability: 0.0099, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.16329288482666, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3226/4000 [30:45<07:05,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.832179069519043, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.311285972595215, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3227/4000 [30:46<07:48,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.000333786010742, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.15374755859375, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3228/4000 [30:46<06:59,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.490261077880859, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.122041702270508, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3229/4000 [30:46<05:56,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.58033561706543, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.280667304992676, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3230/4000 [30:47<07:20,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.575863838195801, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.136487007141113, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3231/4000 [30:48<06:38,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.525025367736816, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.336536407470703, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3232/4000 [30:48<07:34,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.646472454071045, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.530200242996216, Predicted Probability: 0.9262, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3233/4000 [30:48<06:06,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.100340843200684, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.73302936553955, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3234/4000 [30:49<07:14,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.339898586273193, Predicted Probability: 0.9871, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.198444366455078, Predicted Probability: 0.0999, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3235/4000 [30:50<07:46,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.371973991394043, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.789191246032715, Predicted Probability: 0.9421, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3236/4000 [30:50<06:14,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.781782388687134, Predicted Probability: 0.9417, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.722004413604736, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3237/4000 [30:51<05:46,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.781341552734375, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.471266746520996, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3238/4000 [30:51<06:32,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5215505361557007, Predicted Probability: 0.1792, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.86519193649292, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3239/4000 [30:52<07:23,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6543378829956055, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.783804893493652, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3240/4000 [30:53<08:04,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6867198944091797, Predicted Probability: 0.0638, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8116698265075684, Predicted Probability: 0.9784, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3241/4000 [30:54<08:39,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.373080253601074, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.140373945236206, Predicted Probability: 0.2423, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3242/4000 [30:54<07:32,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.92806339263916, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.219969749450684, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3243/4000 [30:55<08:04,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9215006828308105, Predicted Probability: 0.9489, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.203989028930664, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3244/4000 [30:55<08:23,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.004134178161621, Predicted Probability: 0.0179, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.500396728515625, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3245/4000 [30:56<09:00,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.403092384338379, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.122766494750977, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3246/4000 [30:57<08:58,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9188008308410645, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.035473346710205, Predicted Probability: 0.9542, Prediction: 1.0

Epoch 2/3:  81%|████████  | 3247/4000 [30:58<09:19,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.493019104003906, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.297133207321167, Predicted Probability: 0.0914, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3248/4000 [30:58<07:54,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.558731555938721, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.302154064178467, Predicted Probability: 0.0134, Prediction: 0.0

Epoch 2/3:  81%|████████  | 3249/4000 [30:59<08:19,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.166316032409668, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7201461791992188, Predicted Probability: 0.0618, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3250/4000 [31:00<08:38,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1714935302734375, Predicted Probability: 0.2366, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.017594575881958, Predicted Probability: 0.7345, Prediction: 1.0

Epoch 2/3:  81%|████████▏ | 3251/4000 [31:00<07:30,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.351935863494873, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.658504486083984, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3252/4000 [31:01<08:03,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.347308158874512, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.901786208152771, Predicted Probability: 0.7113, Prediction: 1.0

Epoch 2/3:  81%|████████▏ | 3253/4000 [31:01<08:25,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.215305805206299, Predicted Probability: 0.9614, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.992659091949463, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3254/4000 [31:02<07:59,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.583403587341309, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.257143974304199, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  81%|████████▏ | 3255/4000 [31:03<09:02,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.734287261962891, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.534908294677734, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3256/4000 [31:04<09:07,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.856738090515137, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8160831928253174, Predicted Probability: 0.1399, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3257/4000 [31:04<09:16,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.927857398986816, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.541715383529663, Predicted Probability: 0.0281, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3258/4000 [31:05<09:11,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.419856309890747, Predicted Probability: 0.1947, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.893951416015625, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  81%|████████▏ | 3259/4000 [31:06<08:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.007706880569458, Predicted Probability: 0.1184, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.268714904785156, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3260/4000 [31:06<07:59,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.078406810760498, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.156073570251465, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3261/4000 [31:07<08:20,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.070192337036133, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.776409149169922, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3262/4000 [31:08<08:48,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.318758487701416, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.606807231903076, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3263/4000 [31:08<07:31,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.921752691268921, Predicted Probability: 0.9806, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.621418952941895, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3264/4000 [31:09<08:13,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.013741970062256, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.500168323516846, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3265/4000 [31:10<08:52,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.322243690490723, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.545438766479492, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3266/4000 [31:10<08:12,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.164130210876465, Predicted Probability: 0.9847, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.926403045654297, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3267/4000 [31:11<08:37,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.559648513793945, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.465512275695801, Predicted Probability: 0.9886, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3268/4000 [31:12<08:43,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6368722915649414, Predicted Probability: 0.9743, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.728731155395508, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3269/4000 [31:13<09:02,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6558737754821777, Predicted Probability: 0.1603, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.915863990783691, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3270/4000 [31:14<09:03,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6871232986450195, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6476970911026, Predicted Probability: 0.1614, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3271/4000 [31:14<09:01,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4071133136749268, Predicted Probability: 0.1967, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.756920337677002, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3272/4000 [31:15<08:56,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6507668495178223, Predicted Probability: 0.9341, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.216492652893066, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3273/4000 [31:16<08:58,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.99324893951416, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.922651767730713, Predicted Probability: 0.9490, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3274/4000 [31:16<07:39,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.166434288024902, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9564773440361023, Predicted Probability: 0.7224, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3275/4000 [31:17<08:15,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9335784912109375, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.397284507751465, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3276/4000 [31:18<08:24,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.921585083007812, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.921309232711792, Predicted Probability: 0.7153, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3277/4000 [31:18<06:38,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.305835723876953, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.135826587677002, Predicted Probability: 0.0058, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3278/4000 [31:19<07:08,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.108687162399292, Predicted Probability: 0.1083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.03091049194336, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3279/4000 [31:19<07:40,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.512941360473633, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.405989170074463, Predicted Probability: 0.9879, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3280/4000 [31:20<06:42,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.197322845458984, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.030170917510986, Predicted Probability: 0.9935, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3281/4000 [31:20<06:43,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.495247840881348, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8156731128692627, Predicted Probability: 0.0565, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3282/4000 [31:21<06:01,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.02942180633545, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.775972366333008, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3283/4000 [31:21<05:32,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.970474720001221, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.662969589233398, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3284/4000 [31:22<06:54,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.338613033294678, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.0688018798828125, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3285/4000 [31:23<07:41,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.892999649047852, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.317873001098633, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3286/4000 [31:23<07:53,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.515946388244629, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.345823287963867, Predicted Probability: 0.9126, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3287/4000 [31:24<08:13,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.815220832824707, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.925239086151123, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3288/4000 [31:25<07:40,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8209471702575684, Predicted Probability: 0.9438, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.21582317352295, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3289/4000 [31:25<06:08,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.865075588226318, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.589653015136719, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3290/4000 [31:26<06:53,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0788605213165283, Predicted Probability: 0.2537, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.1682767868042, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3291/4000 [31:26<06:06,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.676569938659668, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.262714385986328, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3293/4000 [31:27<04:44,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.661365509033203, Predicted Probability: 0.9906, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.181455135345459, Predicted Probability: 0.9850, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.612286567687988, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.284049034118652, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3294/4000 [31:27<04:37,  2.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.254573106765747, Predicted Probability: 0.0372, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.975292682647705, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3295/4000 [31:27<04:32,  2.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.091475486755371, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.403244018554688, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  82%|████████▏ | 3296/4000 [31:28<06:03,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.274670600891113, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.00186538696289, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3297/4000 [31:29<07:09,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.153409957885742, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.965028762817383, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3298/4000 [31:30<07:42,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.236153602600098, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.172851085662842, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 2/3:  82%|████████▏ | 3299/4000 [31:30<06:45,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.430454254150391, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.053142547607422, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 2/3:  82%|████████▎ | 3300/4000 [31:30<06:00,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.670330762863159, Predicted Probability: 0.0248, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.457916736602783, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3301/4000 [31:31<05:31,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.216424942016602, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.733736991882324, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3302/4000 [31:32<06:33,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3878374099731445, Predicted Probability: 0.9159, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.33065128326416, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3303/4000 [31:32<05:55,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.3866143226623535, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.57485580444336, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3304/4000 [31:32<05:25,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.744807243347168, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.43503475189209, Predicted Probability: 0.0805, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3305/4000 [31:33<05:05,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.410138130187988, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7496161460876465, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3306/4000 [31:33<06:04,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3957265615463257, Predicted Probability: 0.1985, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.029892921447754, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3307/4000 [31:34<06:51,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.489867210388184, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.476149797439575, Predicted Probability: 0.0300, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3308/4000 [31:35<07:16,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1197826862335205, Predicted Probability: 0.2461, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3498367369174957, Predicted Probability: 0.5866, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3310/4000 [31:36<06:02,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3714549541473389, Predicted Probability: 0.2024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.692564010620117, Predicted Probability: 0.0002, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -8.67873764038086, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.387644290924072, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3311/4000 [31:37<07:07,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.401727676391602, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5513458251953125, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3312/4000 [31:37<06:49,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.967414379119873, Predicted Probability: 0.9814, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.850414276123047, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3313/4000 [31:38<07:23,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8306552171707153, Predicted Probability: 0.1382, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.067057132720947, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3314/4000 [31:38<06:30,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.958462715148926, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.853494644165039, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3315/4000 [31:39<07:18,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.83497953414917, Predicted Probability: 0.9445, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.720531463623047, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3316/4000 [31:40<07:40,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.571930408477783, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.801046371459961, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3317/4000 [31:41<07:49,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5382585525512695, Predicted Probability: 0.0282, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.429136276245117, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3318/4000 [31:41<08:06,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9859254360198975, Predicted Probability: 0.2717, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.49394166469573975, Predicted Probability: 0.3790, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3319/4000 [31:42<08:06,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.339929580688477, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5179011821746826, Predicted Probability: 0.9254, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3320/4000 [31:43<08:06,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4296796321868896, Predicted Probability: 0.0314, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5364912748336792, Predicted Probability: 0.1770, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3321/4000 [31:43<06:59,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.311117172241211, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.65440845489502, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3322/4000 [31:44<07:30,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.1973090171813965, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.572298526763916, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3323/4000 [31:45<07:49,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.378443717956543, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.846279144287109, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3324/4000 [31:45<07:17,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.59429669380188, Predicted Probability: 0.9733, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.931212902069092, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3325/4000 [31:46<06:22,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.094407081604004, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.986581325531006, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3326/4000 [31:46<05:08,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.7433443069458, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.058916091918945, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3327/4000 [31:47<06:10,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.825726509094238, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6430554389953613, Predicted Probability: 0.8380, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3328/4000 [31:47<05:33,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.764992713928223, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.529951572418213, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3329/4000 [31:48<06:26,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7298953533172607, Predicted Probability: 0.9388, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.373941421508789, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3330/4000 [31:49<06:59,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.531988143920898, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.731062412261963, Predicted Probability: 0.9388, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3331/4000 [31:49<07:19,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.807345390319824, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.704205513000488, Predicted Probability: 0.9910, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3332/4000 [31:50<05:47,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.964060306549072, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.535897254943848, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3333/4000 [31:50<05:52,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6011247634887695, Predicted Probability: 0.9734, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1729540824890137, Predicted Probability: 0.1022, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3334/4000 [31:50<05:21,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.299769878387451, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.750849723815918, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3335/4000 [31:51<06:08,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.967766284942627, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.044051170349121, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3336/4000 [31:52<06:52,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.935619354248047, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.541509628295898, Predicted Probability: 0.9895, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3337/4000 [31:52<05:42,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.2243971824646, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.856303691864014, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  83%|████████▎ | 3338/4000 [31:53<06:26,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.305782318115234, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.439820289611816, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 2/3:  83%|████████▎ | 3339/4000 [31:53<05:45,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.897168159484863, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.151151657104492, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  84%|████████▎ | 3340/4000 [31:54<06:02,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.020205020904541, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6695332527160645, Predicted Probability: 0.0648, Prediction: 0.0

Epoch 2/3:  84%|████████▎ | 3341/4000 [31:54<05:41,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.610940933227539, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.910298347473145, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 2/3:  84%|████████▎ | 3342/4000 [31:55<06:33,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.934051990509033, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8072518110275269, Predicted Probability: 0.1410, Prediction: 0.0

Epoch 2/3:  84%|████████▎ | 3343/4000 [31:56<05:46,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.708834648132324, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.881931304931641, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 2/3:  84%|████████▎ | 3345/4000 [31:56<03:55,  2.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.453329563140869, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.9685258865356445, Predicted Probability: 0.9974, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.18448257446289, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.251570701599121, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 2/3:  84%|████████▎ | 3346/4000 [31:56<03:57,  2.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.193296432495117, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.085720539093018, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  84%|████████▎ | 3347/4000 [31:57<04:30,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.067461967468262, Predicted Probability: 0.9832, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.956918716430664, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  84%|████████▎ | 3348/4000 [31:57<04:20,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.510301113128662, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.733564376831055, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  84%|████████▎ | 3349/4000 [31:58<04:48,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.971375465393066, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.374756097793579, Predicted Probability: 0.7981, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3350/4000 [31:58<04:35,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.121581077575684, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2627081871032715, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3351/4000 [31:59<05:35,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8063502311706543, Predicted Probability: 0.9430, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2707126140594482, Predicted Probability: 0.0936, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3352/4000 [32:00<06:35,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.011898040771484, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.532958984375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3353/4000 [32:01<07:24,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.551593780517578, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.193987846374512, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3354/4000 [32:01<07:28,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.828483819961548, Predicted Probability: 0.9442, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.566034317016602, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3355/4000 [32:02<06:28,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.98664665222168, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.657638549804688, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3357/4000 [32:02<04:59,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.053303718566895, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8653602600097656, Predicted Probability: 0.9795, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.7083892822265625, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1564040184021, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3358/4000 [32:03<06:08,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2007049322128296, Predicted Probability: 0.7687, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.10849380493164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3359/4000 [32:04<06:49,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6490700244903564, Predicted Probability: 0.1612, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.329592227935791, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3360/4000 [32:05<07:05,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.875682830810547, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.186068534851074, Predicted Probability: 0.8990, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3361/4000 [32:05<06:22,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.270659446716309, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5291861295700073, Predicted Probability: 0.1781, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3362/4000 [32:06<06:45,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.373100280761719, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9040793180465698, Predicted Probability: 0.1296, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3363/4000 [32:06<05:54,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.916024684906006, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.084229469299316, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3364/4000 [32:07<05:19,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.594575881958008, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.647787094116211, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3365/4000 [32:08<06:34,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.143051147460938, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.857894897460938, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3366/4000 [32:08<05:14,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.421687126159668, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.560497283935547, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3367/4000 [32:08<04:50,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.096841335296631, Predicted Probability: 0.0432, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.717706203460693, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3368/4000 [32:09<05:05,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.549136638641357, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.380746841430664, Predicted Probability: 0.0329, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3369/4000 [32:10<06:15,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.735980033874512, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.454020023345947, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3370/4000 [32:10<06:52,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.611083507537842, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.870502948760986, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3371/4000 [32:11<07:20,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.42431530356407166, Predicted Probability: 0.6045, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.535095691680908, Predicted Probability: 0.0283, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3372/4000 [32:12<07:36,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.10105037689209, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6626877784729, Predicted Probability: 0.9906, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3373/4000 [32:13<07:59,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6747965812683105, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.286336898803711, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3374/4000 [32:13<06:59,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.694323539733887, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.05741548538208, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3375/4000 [32:14<07:14,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8362269401550293, Predicted Probability: 0.9446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.3347883224487305, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3376/4000 [32:15<07:18,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.680740356445312, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.616168022155762, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3377/4000 [32:15<07:21,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8216936588287354, Predicted Probability: 0.9438, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.178474426269531, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  84%|████████▍ | 3378/4000 [32:16<07:26,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.1549787521362305, Predicted Probability: 0.0057, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4162590503692627, Predicted Probability: 0.9682, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3379/4000 [32:17<07:28,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.253215789794922, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.797475337982178, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 2/3:  84%|████████▍ | 3380/4000 [32:18<07:07,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: -5.461904048919678, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.963188648223877, Predicted Probability: 0.9509, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3381/4000 [32:18<07:32,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6478376388549805, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.047459602355957, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3382/4000 [32:19<07:41,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.433255195617676, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.1591796875, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3383/4000 [32:20<07:05,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.631162166595459, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.508454322814941, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3385/4000 [32:20<05:23,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.16140660643577576, Predicted Probability: 0.5403, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.487128257751465, Predicted Probability: 0.0111, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 5.16398811340332, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.463188171386719, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3386/4000 [32:21<05:59,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.372488498687744, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.70450496673584, Predicted Probability: 0.9373, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3387/4000 [32:22<06:39,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.18939208984375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.212547302246094, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3388/4000 [32:22<05:19,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.111107349395752, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.8380765914917, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3389/4000 [32:23<06:00,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.592844009399414, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.682312965393066, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3390/4000 [32:24<06:36,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.815340042114258, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.580591678619385, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3391/4000 [32:25<07:00,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.720305442810059, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4805582761764526, Predicted Probability: 0.1853, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3392/4000 [32:25<07:07,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.1245574951171875, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.902804374694824, Predicted Probability: 0.9480, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3393/4000 [32:26<07:15,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.723546981811523, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7590465545654297, Predicted Probability: 0.9404, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3394/4000 [32:27<07:18,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9598584175109863, Predicted Probability: 0.9813, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.630427360534668, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3395/4000 [32:28<07:29,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.061256408691406, Predicted Probability: 0.9831, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9761810302734375, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3396/4000 [32:28<07:37,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.290563583374023, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.550243377685547, Predicted Probability: 0.9276, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3397/4000 [32:29<08:00,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.160102844238281, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.59390640258789, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  85%|████████▍ | 3398/4000 [32:30<07:16,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.8202595710754395, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.964966773986816, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  85%|████████▍ | 3399/4000 [32:30<06:45,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.987478256225586, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.785199165344238, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3400/4000 [32:31<06:23,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.466529846191406, Predicted Probability: 0.9886, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.762139797210693, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3401/4000 [32:31<06:04,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7028908729553223, Predicted Probability: 0.9372, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3411896228790283, Predicted Probability: 0.0342, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3402/4000 [32:32<05:22,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.097708702087402, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.349653244018555, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3403/4000 [32:32<04:33,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.115826606750488, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.728902816772461, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3404/4000 [32:33<04:30,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.252313137054443, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.982114315032959, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  85%|████████▌ | 3405/4000 [32:33<05:23,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.411371231079102, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.824089527130127, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 2/3:  85%|████████▌ | 3406/4000 [32:34<04:53,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: 5.111656188964844, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.742190361022949, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3407/4000 [32:34<05:29,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6546756029129028, Predicted Probability: 0.8395, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.500656843185425, Predicted Probability: 0.9242, Prediction: 1.0

Epoch 2/3:  85%|████████▌ | 3408/4000 [32:35<05:25,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.392749786376953, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.531850337982178, Predicted Probability: 0.9894, Prediction: 1.0

Epoch 2/3:  85%|████████▌ | 3409/4000 [32:35<04:24,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.622542381286621, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.319879531860352, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3410/4000 [32:36<05:16,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8177742958068848, Predicted Probability: 0.9436, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.907923698425293, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3411/4000 [32:36<04:47,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.660192966461182, Predicted Probability: 0.0094, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.034629821777344, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3412/4000 [32:37<04:55,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6501624584198, Predicted Probability: 0.9747, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4813711643218994, Predicted Probability: 0.0772, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3413/4000 [32:37<05:18,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.715090036392212, Predicted Probability: 0.9379, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.155528545379639, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3414/4000 [32:38<04:30,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.101174354553223, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.421875953674316, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3415/4000 [32:38<05:20,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.06536865234375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3628672361373901, Predicted Probability: 0.2038, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3416/4000 [32:39<04:48,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.197955131530762, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.855454921722412, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  85%|████████▌ | 3417/4000 [32:40<05:50,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.527711868286133, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.846837043762207, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  85%|████████▌ | 3418/4000 [32:40<06:18,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.046193838119507, Predicted Probability: 0.1144, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.172422409057617, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3420/4000 [32:41<04:04,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.806122779846191, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -5.275744915008545, Predicted Probability: 0.0051, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.143075942993164, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.428408622741699, Predicted Probability: 0.9882, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3421/4000 [32:42<05:09,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.757646560668945, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.734820365905762, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3422/4000 [32:42<06:00,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.341153144836426, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.104587554931641, Predicted Probability: 0.0162, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3423/4000 [32:43<06:24,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.144949913024902, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.85541570186615, Predicted Probability: 0.1352, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3424/4000 [32:44<06:00,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.1248672008514404, Predicted Probability: 0.1067, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.891918420791626, Predicted Probability: 0.0200, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3425/4000 [32:44<05:44,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.981720924377441, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.38198402523994446, Predicted Probability: 0.5944, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3426/4000 [32:45<05:18,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9641243815422058, Predicted Probability: 0.7239, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.509895324707031, Predicted Probability: 0.9891, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3427/4000 [32:45<05:51,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.768198013305664, Predicted Probability: 0.1458, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.608678817749023, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3428/4000 [32:46<06:22,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.070785522460938, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.954573631286621, Predicted Probability: 0.0495, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3429/4000 [32:47<06:37,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.849363327026367, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.62640118598938, Predicted Probability: 0.9325, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3430/4000 [32:47<05:43,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.955086708068848, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.946293830871582, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3431/4000 [32:48<06:12,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7099320888519287, Predicted Probability: 0.0624, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.196017265319824, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3432/4000 [32:49<06:30,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.689430236816406, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.104901313781738, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3433/4000 [32:49<05:39,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.511696815490723, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.430398941040039, Predicted Probability: 0.8070, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3434/4000 [32:50<04:32,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.191896915435791, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.839064121246338, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3435/4000 [32:50<04:43,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.921085834503174, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.140552043914795, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3436/4000 [32:51<05:21,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.722125053405762, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4431002140045166, Predicted Probability: 0.9690, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3437/4000 [32:51<04:50,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.790475845336914, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.291864395141602, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3438/4000 [32:52<04:25,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.016801834106445, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1988911628723145, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3439/4000 [32:52<03:40,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.257951736450195, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.795818328857422, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3440/4000 [32:52<03:18,  2.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.33709716796875, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.966697692871094, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3441/4000 [32:53<04:38,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.778347969055176, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.547370910644531, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3443/4000 [32:53<03:33,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.859918117523193, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.479886054992676, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.463781356811523, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.713618755340576, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  86%|████████▌ | 3444/4000 [32:54<04:32,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.265758037567139, Predicted Probability: 0.9862, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.504190444946289, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3445/4000 [32:55<05:41,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.568896770477295, Predicted Probability: 0.0274, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.388007164001465, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3446/4000 [32:56<06:03,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.91218900680542, Predicted Probability: 0.0196, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.381033897399902, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3447/4000 [32:57<06:10,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0760438442230225, Predicted Probability: 0.9559, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.095758438110352, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3448/4000 [32:57<06:24,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.988002300262451, Predicted Probability: 0.9932, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.841970443725586, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  86%|████████▌ | 3449/4000 [32:58<05:31,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.49968957901001, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.488731622695923, Predicted Probability: 0.0767, Prediction: 0.0

Epoch 2/3:  86%|████████▋ | 3450/4000 [32:58<05:54,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.255913734436035, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.365721225738525, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:  86%|████████▋ | 3451/4000 [32:59<04:42,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.4757036566734314, Predicted Probability: 0.6167, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.039445877075195, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 2/3:  86%|████████▋ | 3452/4000 [32:59<05:20,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.12937068939209, Predicted Probability: 0.0158, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.846830368041992, Predicted Probability: 0.9452, Prediction: 1.0

Epoch 2/3:  86%|████████▋ | 3453/4000 [33:00<04:44,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.585098266601562, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9825592041015625, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 2/3:  86%|████████▋ | 3454/4000 [33:00<04:19,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.238041400909424, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.279698371887207, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  86%|████████▋ | 3455/4000 [33:01<04:01,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.192788124084473, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.306403636932373, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  86%|████████▋ | 3456/4000 [33:01<04:45,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2113595008850098, Predicted Probability: 0.2295, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.12648868560791, Predicted Probability: 0.0159, Prediction: 0.0

Epoch 2/3:  86%|████████▋ | 3457/4000 [33:02<05:24,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.582737922668457, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3484730124473572, Predicted Probability: 0.4138, Prediction: 0.0

Epoch 2/3:  86%|████████▋ | 3458/4000 [33:03<05:48,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6882576942443848, Predicted Probability: 0.9363, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.481733322143555, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  86%|████████▋ | 3459/4000 [33:03<05:07,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.2743659019470215, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.43076229095459, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  86%|████████▋ | 3460/4000 [33:04<05:36,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.753691673278809, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.68699312210083, Predicted Probability: 0.9363, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3461/4000 [33:04<04:56,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.349769592285156, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.910680770874023, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3462/4000 [33:05<05:26,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.726202011108398, Predicted Probability: 0.9912, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.398599624633789, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3463/4000 [33:06<05:48,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2522366046905518, Predicted Probability: 0.9628, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.280851364135742, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3464/4000 [33:06<05:03,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.296202182769775, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.266210079193115, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3465/4000 [33:07<04:29,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.681459426879883, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.263317108154297, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3466/4000 [33:07<05:07,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.112276077270508, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.920634746551514, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3468/4000 [33:08<03:43,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.19437313079834, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.5470757484436035, Predicted Probability: 0.0039, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.897352695465088, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.619076728820801, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3469/4000 [33:09<04:31,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.317408561706543, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.390032768249512, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3470/4000 [33:09<05:20,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.878735542297363, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.021534442901611, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3471/4000 [33:10<06:04,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.8834810256958, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.964336395263672, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3472/4000 [33:10<04:47,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.442427635192871, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.648329734802246, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3473/4000 [33:11<05:31,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.414144039154053, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.243106842041016, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3474/4000 [33:12<05:17,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.560897350311279, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.107311248779297, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3475/4000 [33:12<04:41,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.079388618469238, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.553674697875977, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3476/4000 [33:12<03:49,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.522268295288086, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.28727912902832, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3477/4000 [33:13<04:46,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.704320907592773, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.326075077056885, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3478/4000 [33:14<04:01,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.7255072593688965, Predicted Probability: 0.9912, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.843421936035156, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3479/4000 [33:14<04:49,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.596547603607178, Predicted Probability: 0.9900, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.223834991455078, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3480/4000 [33:15<04:48,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.558958530426025, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.255281925201416, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3481/4000 [33:15<04:30,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.021252632141113, Predicted Probability: 0.9824, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.305080413818359, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3482/4000 [33:15<03:41,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.233088493347168, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.425186634063721, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3483/4000 [33:16<03:34,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.814201831817627, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.304041385650635, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3484/4000 [33:17<04:46,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.690555572509766, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.821948051452637, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3485/4000 [33:17<05:14,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.771154403686523, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5422775745391846, Predicted Probability: 0.1762, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3486/4000 [33:18<04:12,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.397003173828125, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.174549102783203, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3487/4000 [33:18<03:55,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.657590866088867, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.330170631408691, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3488/4000 [33:19<04:50,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.912769794464111, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.394260883331299, Predicted Probability: 0.0325, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3489/4000 [33:20<05:21,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.947048664093018, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1601009368896484, Predicted Probability: 0.8966, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3490/4000 [33:20<04:55,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.774362087249756, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.796798229217529, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3491/4000 [33:21<05:02,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.488587379455566, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.8553571701049805, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3492/4000 [33:21<04:29,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.26013949513435364, Predicted Probability: 0.5647, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6013054847717285, Predicted Probability: 0.0099, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3493/4000 [33:22<04:07,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.406510353088379, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.076715469360352, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3494/4000 [33:22<03:48,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.437948226928711, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.57712459564209, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3495/4000 [33:22<03:48,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.3161091804504395, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.626399040222168, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3497/4000 [33:23<03:43,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.430187225341797, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.019847869873047, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.6053147315979, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.859536170959473, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  87%|████████▋ | 3498/4000 [33:24<04:25,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.3920817375183105, Predicted Probability: 0.0122, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.424478530883789, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  87%|████████▋ | 3499/4000 [33:25<05:00,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7733945846557617, Predicted Probability: 0.9412, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.935986042022705, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3500/4000 [33:26<05:22,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.281785011291504, Predicted Probability: 0.0136, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.100421905517578, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3501/4000 [33:26<04:40,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.772256374359131, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.967926025390625, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3502/4000 [33:26<04:11,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9249744415283203, Predicted Probability: 0.9806, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8385447263717651, Predicted Probability: 0.1372, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3503/4000 [33:27<03:36,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.424412727355957, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.75703239440918, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3504/4000 [33:27<03:55,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1722733974456787, Predicted Probability: 0.1023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.219974040985107, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3505/4000 [33:28<04:32,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.768753051757812, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.040492057800293, Predicted Probability: 0.9827, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3506/4000 [33:29<05:00,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0200817584991455, Predicted Probability: 0.2650, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.813070297241211, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3507/4000 [33:29<04:25,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.089109897613525, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.020924091339111, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3508/4000 [33:30<05:03,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.584681510925293, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.68781566619873, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3509/4000 [33:31<05:27,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.336725234985352, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3364599049091339, Predicted Probability: 0.5833, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3510/4000 [33:31<04:42,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.070317268371582, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.503864288330078, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3511/4000 [33:31<04:12,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7449309825897217, Predicted Probability: 0.9769, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.612342834472656, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3512/4000 [33:32<04:47,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.2071735858917236, Predicted Probability: 0.0991, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.131314754486084, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3513/4000 [33:33<05:09,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.014558553695678711, Predicted Probability: 0.4964, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.366680145263672, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3514/4000 [33:34<05:33,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.238309860229492, Predicted Probability: 0.9036, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.803277015686035, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3515/4000 [33:34<04:45,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.00322151184082, Predicted Probability: 0.0179, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.287402153015137, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3516/4000 [33:34<04:13,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9929323196411133, Predicted Probability: 0.9523, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.902390003204346, Predicted Probability: 0.0010, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 6.625059127807617, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.97365665435791, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3518/4000 [33:35<04:08,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.857828140258789, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3233587741851807, Predicted Probability: 0.9108, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3519/4000 [33:36<04:55,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.883167266845703, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.074886322021484, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3520/4000 [33:36<03:55,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.968515396118164, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.452205657958984, Predicted Probability: 0.0115, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3521/4000 [33:37<04:00,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.246729850769043, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.802983522415161, Predicted Probability: 0.0218, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3522/4000 [33:38<04:34,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.102851152420044, Predicted Probability: 0.8912, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.957404136657715, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3523/4000 [33:38<04:55,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.142245292663574, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9600361585617065, Predicted Probability: 0.1235, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3524/4000 [33:39<04:22,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3043313026428223, Predicted Probability: 0.9646, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.239444732666016, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3525/4000 [33:40<05:06,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.617082595825195, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.951800346374512, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3526/4000 [33:40<04:27,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6613546013832092, Predicted Probability: 0.3404, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.137737274169922, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3527/4000 [33:40<04:00,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.9393892288208, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.235538959503174, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3528/4000 [33:41<04:34,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.285503387451172, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7925143241882324, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3529/4000 [33:42<04:56,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.056583404541016, Predicted Probability: 0.9830, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.352365255355835, Predicted Probability: 0.9662, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3530/4000 [33:43<05:12,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0211715698242188, Predicted Probability: 0.8830, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.824222564697266, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3531/4000 [33:43<05:29,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3483357429504395, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.744966506958008, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3532/4000 [33:44<05:32,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.010090421885251999, Predicted Probability: 0.4975, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.73368501663208, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3533/4000 [33:44<04:46,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.323122978210449, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.540147304534912, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3534/4000 [33:45<04:37,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.67014217376709, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.193961143493652, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3535/4000 [33:46<05:04,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.189639091491699, Predicted Probability: 0.9851, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.022003173828125, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3536/4000 [33:47<05:16,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.815483331680298, Predicted Probability: 0.9784, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.471497535705566, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3537/4000 [33:47<05:23,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.232626438140869, Predicted Probability: 0.9031, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.166032791137695, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3538/4000 [33:48<04:38,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.851970672607422, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.64345645904541, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  88%|████████▊ | 3539/4000 [33:49<05:08,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.414626359939575, Predicted Probability: 0.9179, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.074396133422852, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  88%|████████▊ | 3540/4000 [33:49<05:18,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.350419044494629, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1082584857940674, Predicted Probability: 0.1083, Prediction: 0.0

Epoch 2/3:  89%|████████▊ | 3541/4000 [33:49<04:10,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.0110273361206055, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.186755657196045, Predicted Probability: 0.9603, Prediction: 1.0

Epoch 2/3:  89%|████████▊ | 3542/4000 [33:50<04:32,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.7245993614196777, Predicted Probability: 0.3264, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.559162139892578, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  89%|████████▊ | 3543/4000 [33:51<05:19,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2531466484069824, Predicted Probability: 0.0372, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.319051742553711, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▊ | 3544/4000 [33:52<05:23,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.3443498611450195, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.098740577697754, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  89%|████████▊ | 3545/4000 [33:52<04:37,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3130388259887695, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.013328552246094, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  89%|████████▊ | 3546/4000 [33:53<04:48,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7782235145568848, Predicted Probability: 0.9415, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.397868156433105, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▊ | 3547/4000 [33:53<04:12,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.582096099853516, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.427309036254883, Predicted Probability: 0.0044, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -5.441308498382568, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.955788254737854, Predicted Probability: 0.8761, Prediction: 1.0

Epoch 2/3:  89%|████████▊ | 3549/4000 [33:54<03:58,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.726456165313721, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6589059829711914, Predicted Probability: 0.9346, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3550/4000 [33:55<03:38,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.386327266693115, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.324015140533447, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3551/4000 [33:55<04:12,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.316469192504883, Predicted Probability: 0.9102, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.540553092956543, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3552/4000 [33:56<04:09,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.774684190750122, Predicted Probability: 0.9776, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.176126480102539, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3553/4000 [33:57<04:32,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8581382632255554, Predicted Probability: 0.7023, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.722352027893066, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3554/4000 [33:57<04:01,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.055919647216797, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.961618423461914, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3555/4000 [33:57<03:39,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.664000511169434, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.567211151123047, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3556/4000 [33:58<04:10,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.916878700256348, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.181300163269043, Predicted Probability: 0.9850, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3557/4000 [33:59<04:34,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.236824035644531, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.0344133377075195, Predicted Probability: 0.0174, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3558/4000 [34:00<04:51,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.820578932762146, Predicted Probability: 0.3056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.273509979248047, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3559/4000 [34:00<05:19,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.400819778442383, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.685667991638184, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3560/4000 [34:01<04:10,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.3539629578590393, Predicted Probability: 0.5876, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.4826436042785645, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3561/4000 [34:01<03:43,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.577380895614624, Predicted Probability: 0.9294, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.219560623168945, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3562/4000 [34:02<04:09,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.122411727905273, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.996208667755127, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3563/4000 [34:03<04:32,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.234921455383301, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2101950645446777, Predicted Probability: 0.7703, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3564/4000 [34:03<05:03,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.777030944824219, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.048664093017578, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3565/4000 [34:04<05:14,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6683454513549805, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.443103790283203, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3566/4000 [34:05<05:13,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.184004068374634, Predicted Probability: 0.9602, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0102298259735107, Predicted Probability: 0.9530, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3567/4000 [34:05<04:30,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.367156982421875, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2911815643310547, Predicted Probability: 0.9641, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3568/4000 [34:06<04:44,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.962813377380371, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8416614532470703, Predicted Probability: 0.9449, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3569/4000 [34:07<04:36,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5726115703582764, Predicted Probability: 0.9727, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.55855941772461, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3570/4000 [34:07<04:02,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.749605178833008, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.557369232177734, Predicted Probability: 0.9896, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3571/4000 [34:07<03:38,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.924570083618164, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.534778594970703, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3572/4000 [34:08<04:09,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.549335479736328, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3794894218444824, Predicted Probability: 0.2011, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3573/4000 [34:09<04:28,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.0545383095741272, Predicted Probability: 0.5136, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 1.0919272899627686, Predicted Probability: 0.7487, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3574/4000 [34:09<03:55,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.174785137176514, Predicted Probability: 0.9849, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.899691104888916, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3575/4000 [34:10<04:21,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.024097919464111, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.037845611572266, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3576/4000 [34:11<04:43,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.068120241165161, Predicted Probability: 0.8878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.671072006225586, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3577/4000 [34:12<04:48,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.190505981445312, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9643468856811523, Predicted Probability: 0.9509, Prediction: 1.0

Epoch 2/3:  89%|████████▉ | 3578/4000 [34:12<04:37,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.428938150405884, Predicted Probability: 0.9686, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.168545722961426, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  89%|████████▉ | 3579/4000 [34:13<04:11,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.203285217285156, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.642553329467773, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3580/4000 [34:13<03:42,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.132538795471191, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.498833656311035, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3581/4000 [34:13<03:32,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.185724258422852, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.125601768493652, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  90%|████████▉ | 3582/4000 [34:14<03:58,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.0249176025390625, Predicted Probability: 0.0176, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.908761978149414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3583/4000 [34:14<03:13,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.6308064460754395, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.725515365600586, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  90%|████████▉ | 3584/4000 [34:15<03:51,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.511331081390381, Predicted Probability: 0.9249, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.035919189453125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3585/4000 [34:16<04:15,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.956020355224609, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.207005977630615, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 2/3:  90%|████████▉ | 3586/4000 [34:17<04:38,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.325826644897461, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.163406372070312, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3587/4000 [34:17<04:02,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.151630401611328, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.677979469299316, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3588/4000 [34:18<04:24,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2188594341278076, Predicted Probability: 0.0385, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.12376594543457, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3589/4000 [34:18<04:18,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6927366256713867, Predicted Probability: 0.9757, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.282407760620117, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3590/4000 [34:19<04:18,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0016679763793945, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.812775135040283, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3:  90%|████████▉ | 3591/4000 [34:20<03:54,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.317236423492432, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8725648522377014, Predicted Probability: 0.2947, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3592/4000 [34:20<03:29,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.978973388671875, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.755125522613525, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3593/4000 [34:21<03:56,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.796048164367676, Predicted Probability: 0.0220, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.70023250579834, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3594/4000 [34:21<03:32,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.962118148803711, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.159056186676025, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3595/4000 [34:21<03:22,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5218210220336914, Predicted Probability: 0.9713, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9568376541137695, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  90%|████████▉ | 3596/4000 [34:22<03:51,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.678393363952637, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1794047355651855, Predicted Probability: 0.0399, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3597/4000 [34:23<04:10,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.949934005737305, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.045533180236816, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 2/3:  90%|████████▉ | 3598/4000 [34:23<03:38,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.445099353790283, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.731926918029785, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|████████▉ | 3599/4000 [34:24<04:04,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.337929725646973, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5958216190338135, Predicted Probability: 0.9733, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3600/4000 [34:24<03:37,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.430548667907715, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8620193004608154, Predicted Probability: 0.9794, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3601/4000 [34:25<03:16,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3146443367004395, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.299376964569092, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3602/4000 [34:25<03:10,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.139344692230225, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.852387428283691, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3603/4000 [34:26<03:47,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.814857482910156, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.798539161682129, Predicted Probability: 0.0082, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3604/4000 [34:26<03:22,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.993994235992432, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9791533946990967, Predicted Probability: 0.0184, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3605/4000 [34:27<02:46,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.1776509284973145, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9791687726974487, Predicted Probability: 0.8786, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3606/4000 [34:27<03:25,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7018046379089355, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.047468185424805, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3607/4000 [34:28<03:56,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.099027633666992, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.887608528137207, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3608/4000 [34:29<04:13,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.500148296356201, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.608072280883789, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3609/4000 [34:29<03:39,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.342849731445312, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.168490886688232, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3610/4000 [34:30<04:04,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.139801502227783, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.450733184814453, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3611/4000 [34:30<03:14,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.28511905670166, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.368000984191895, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3612/4000 [34:31<03:38,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.085737228393555, Predicted Probability: 0.0165, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.565323829650879, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3613/4000 [34:31<02:56,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.706615447998047, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.959897994995117, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3614/4000 [34:32<03:06,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.456324100494385, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.257891654968262, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3615/4000 [34:33<03:37,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.851369857788086, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.0736722946167, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3616/4000 [34:33<04:00,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4233269691467285, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.612424612045288, Predicted Probability: 0.8337, Prediction: 1.0

Epoch 2/3:  90%|█████████ | 3617/4000 [34:34<03:52,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.583987236022949, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.787432670593262, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3618/4000 [34:34<03:33,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.650790214538574, Predicted Probability: 0.9905, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.000001907348633, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3619/4000 [34:35<03:50,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.05224347114563, Predicted Probability: 0.9549, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.361410140991211, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  90%|█████████ | 3620/4000 [34:35<03:33,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.730276107788086, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.853496551513672, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3621/4000 [34:36<03:52,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2841572761535645, Predicted Probability: 0.9864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.466013431549072, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3622/4000 [34:37<04:11,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.111985206604004, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0995633602142334, Predicted Probability: 0.9569, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3623/4000 [34:37<03:36,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.149200439453125, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.11836838722229, Predicted Probability: 0.0424, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3624/4000 [34:38<03:14,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.882447242736816, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.89377498626709, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3625/4000 [34:38<03:39,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.052444458007812, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3749059438705444, Predicted Probability: 0.7982, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3626/4000 [34:39<03:22,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.273533344268799, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5098836421966553, Predicted Probability: 0.0290, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3627/4000 [34:40<03:49,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.142735481262207, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.401862621307373, Predicted Probability: 0.0322, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3628/4000 [34:40<04:04,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.296069860458374, Predicted Probability: 0.9086, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.29958176612854, Predicted Probability: 0.9088, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3629/4000 [34:41<04:16,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.990570545196533, Predicted Probability: 0.9521, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.587912082672119, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3630/4000 [34:42<03:40,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.3336799144744873, Predicted Probability: 0.0344, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.50823974609375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3631/4000 [34:42<03:04,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.487844944000244, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.478515625, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3632/4000 [34:42<02:48,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.56322193145752, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.813326358795166, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3633/4000 [34:43<03:20,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.090850830078125, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.265744209289551, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3634/4000 [34:44<03:40,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.710384368896484, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.567392826080322, Predicted Probability: 0.9897, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3635/4000 [34:44<03:22,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.441025257110596, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.448823928833008, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3636/4000 [34:45<03:20,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.671047687530518, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.223389625549316, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3637/4000 [34:45<03:36,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.798243045806885, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9358714818954468, Predicted Probability: 0.2817, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3638/4000 [34:46<02:53,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.03971004486084, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.156497955322266, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3639/4000 [34:46<02:40,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.9115898609161377, Predicted Probability: 0.8712, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.258030891418457, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3640/4000 [34:47<03:13,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.274104118347168, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0530271530151367, Predicted Probability: 0.9549, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3641/4000 [34:48<03:42,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.008567810058594, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6926462650299072, Predicted Probability: 0.0634, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3642/4000 [34:48<03:57,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.825779438018799, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.274605751037598, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3643/4000 [34:49<03:25,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.787189483642578, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.649007320404053, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3644/4000 [34:49<03:46,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5762341022491455, Predicted Probability: 0.9728, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.176963806152344, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3645/4000 [34:50<04:02,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.815620422363281, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8101816177368164, Predicted Probability: 0.9783, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3646/4000 [34:51<03:36,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.067790985107422, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.626450538635254, Predicted Probability: 0.9903, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3647/4000 [34:51<03:28,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.896810054779053, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.546030521392822, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 2/3:  91%|█████████ | 3648/4000 [34:52<03:04,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.969149589538574, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5542521476745605, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 2/3:  91%|█████████ | 3649/4000 [34:52<03:39,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.743033409118652, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.135926246643066, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  91%|█████████▏| 3651/4000 [34:53<02:35,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.176762580871582, Predicted Probability: 0.9849, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.468008518218994, Predicted Probability: 0.0006, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -9.333301544189453, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.343137741088867, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  91%|█████████▏| 3652/4000 [34:54<03:06,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.460960865020752, Predicted Probability: 0.9214, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.500387191772461, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  91%|█████████▏| 3653/4000 [34:55<03:36,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.12147045135498, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.015281677246094, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  91%|█████████▏| 3654/4000 [34:55<03:50,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.32590389251709, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.851734161376953, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  91%|█████████▏| 3655/4000 [34:56<03:19,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.769376754760742, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.298017978668213, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  91%|█████████▏| 3656/4000 [34:57<03:39,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.706195831298828, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.551699161529541, Predicted Probability: 0.6345, Prediction: 1.0

Epoch 2/3:  91%|█████████▏| 3657/4000 [34:57<03:11,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.7862114906311035, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.390630722045898, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  91%|█████████▏| 3658/4000 [34:58<03:30,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.117359161376953, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.203227996826172, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:  91%|█████████▏| 3659/4000 [34:58<03:04,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.447745323181152, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.568385124206543, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3660/4000 [34:59<03:22,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.699001312255859, Predicted Probability: 0.0090, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3566880226135254, Predicted Probability: 0.2048, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3661/4000 [34:59<02:59,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.336799621582031, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7625527381896973, Predicted Probability: 0.8535, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3662/4000 [35:00<02:42,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.4812202453613281, Predicted Probability: 0.1852, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.60142707824707, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3663/4000 [35:00<03:10,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.173770904541016, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.100980281829834, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3664/4000 [35:01<03:26,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.887042999267578, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.719869613647461, Predicted Probability: 0.9382, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3665/4000 [35:02<03:18,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.378432273864746, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.432774782180786, Predicted Probability: 0.9687, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3666/4000 [35:02<03:41,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.705526351928711, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.915810585021973, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3667/4000 [35:03<03:12,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3759586811065674, Predicted Probability: 0.0331, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5200186967849731, Predicted Probability: 0.1795, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3668/4000 [35:03<03:07,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.410031318664551, Predicted Probability: 0.0824, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.264302730560303, Predicted Probability: 0.0139, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3669/4000 [35:04<03:05,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.010824680328369, Predicted Probability: 0.0178, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.36987590789795, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3670/4000 [35:05<03:27,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.73752498626709, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.004702568054199, Predicted Probability: 0.9821, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3671/4000 [35:05<03:10,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.985228538513184, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.527874946594238, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3672/4000 [35:05<02:49,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.763068199157715, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.425372362136841, Predicted Probability: 0.0813, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3673/4000 [35:06<02:37,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.004448890686035, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5872201919555664, Predicted Probability: 0.0700, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3674/4000 [35:06<02:43,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9770967960357666, Predicted Probability: 0.9816, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.537794589996338, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3675/4000 [35:07<02:32,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.940797805786133, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.532687187194824, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3676/4000 [35:07<02:24,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.719264030456543, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.576824188232422, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3677/4000 [35:08<02:18,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.483856201171875, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.369730949401855, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3678/4000 [35:08<02:20,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.121977806091309, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.301165580749512, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3679/4000 [35:09<02:37,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.718211650848389, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6328461170196533, Predicted Probability: 0.0258, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3680/4000 [35:09<02:41,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.835546016693115, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9043169021606445, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3681/4000 [35:10<02:29,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8962745666503906, Predicted Probability: 0.9801, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.748183250427246, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3682/4000 [35:10<02:09,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.339665412902832, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.158016204833984, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3683/4000 [35:11<02:39,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1041340827941895, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.767820358276367, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3684/4000 [35:11<02:27,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.6710076332092285, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.796774864196777, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3685/4000 [35:12<02:55,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.705584526062012, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9593923091888428, Predicted Probability: 0.0493, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3686/4000 [35:12<02:37,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.454392433166504, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.47452974319458, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3687/4000 [35:13<03:01,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.356675624847412, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.216923713684082, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3688/4000 [35:14<03:19,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.524303436279297, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.5956300497055054, Predicted Probability: 0.3553, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3689/4000 [35:14<03:09,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.801462173461914, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.563116073608398, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3690/4000 [35:15<02:46,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.975820302963257, Predicted Probability: 0.0184, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.520967960357666, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3691/4000 [35:15<03:07,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.725299596786499, Predicted Probability: 0.9765, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.697434425354004, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3692/4000 [35:16<03:00,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.200265884399414, Predicted Probability: 0.9852, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.681448936462402, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3693/4000 [35:17<03:22,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.451807022094727, Predicted Probability: 0.0115, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.866089820861816, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3694/4000 [35:17<02:40,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.28817367553711, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.263304710388184, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3695/4000 [35:17<02:25,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.222327709197998, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.023795127868652, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3696/4000 [35:18<02:53,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.468462944030762, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8074536323547363, Predicted Probability: 0.0569, Prediction: 0.0

Epoch 2/3:  92%|█████████▏| 3697/4000 [35:19<02:50,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.775240421295166, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.826504707336426, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3698/4000 [35:19<02:32,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.707883834838867, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.297449111938477, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  92%|█████████▏| 3699/4000 [35:20<02:53,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.05567741394043, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2294182777404785, Predicted Probability: 0.2263, Prediction: 0.0

Epoch 2/3:  92%|█████████▎| 3700/4000 [35:20<02:36,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.459554672241211, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.786175727844238, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3701/4000 [35:21<02:38,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.880813598632812, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.151691913604736, Predicted Probability: 0.9845, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3702/4000 [35:21<02:57,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.971420764923096, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.159473896026611, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3703/4000 [35:22<03:13,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.096818923950195, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.757229804992676, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3704/4000 [35:22<02:33,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.241310119628906, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.219022750854492, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3705/4000 [35:23<02:06,  2.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.932980060577393, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.018078804016113, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3706/4000 [35:23<02:01,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.832270622253418, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.41862964630127, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3707/4000 [35:23<01:58,  2.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.3113954067230225, Predicted Probability: 0.9098, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.500789642333984, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3708/4000 [35:24<02:30,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.32504653930664, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3265258073806763, Predicted Probability: 0.2097, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3709/4000 [35:25<02:50,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.979710102081299, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7951221466064453, Predicted Probability: 0.9424, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3710/4000 [35:26<03:03,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4500250816345215, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.018424987792969, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3711/4000 [35:26<02:41,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.65866470336914, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.325813293457031, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3712/4000 [35:26<02:24,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.376212120056152, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7518310546875, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3713/4000 [35:27<02:13,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1201045513153076, Predicted Probability: 0.1072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.546910285949707, Predicted Probability: 0.9895, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3714/4000 [35:28<02:38,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.948193550109863, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.494904518127441, Predicted Probability: 0.9890, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3715/4000 [35:28<02:36,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.111128568649292, Predicted Probability: 0.1080, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.759111404418945, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3716/4000 [35:29<02:53,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.17055892944336, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.070059061050415, Predicted Probability: 0.9556, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3717/4000 [35:29<02:35,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.149967670440674, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.991854667663574, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3718/4000 [35:30<02:19,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.233560085296631, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.2531657218933105, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3719/4000 [35:30<02:10,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.894968032836914, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.49329948425293, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3720/4000 [35:31<02:34,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.862830638885498, Predicted Probability: 0.0540, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.959098815917969, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3721/4000 [35:32<02:56,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.751801490783691, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.757805347442627, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3722/4000 [35:32<02:20,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.955169200897217, Predicted Probability: 0.9812, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.066145896911621, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3723/4000 [35:32<02:39,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6930155754089355, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9058661460876465, Predicted Probability: 0.0519, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3724/4000 [35:33<02:21,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.120011329650879, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.411139488220215, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3725/4000 [35:34<02:41,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.582695960998535, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.961979389190674, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3726/4000 [35:34<02:22,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1989665031433105, Predicted Probability: 0.9608, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.95709228515625, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3727/4000 [35:35<02:41,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.183229446411133, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.747444152832031, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3728/4000 [35:35<02:37,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9611976146698, Predicted Probability: 0.9813, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0552659034729, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3729/4000 [35:36<02:18,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3736581802368164, Predicted Probability: 0.0852, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.341925621032715, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3730/4000 [35:36<02:22,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.064856052398682, Predicted Probability: 0.9831, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.084758758544922, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3731/4000 [35:37<02:24,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.53916072845459, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.698776721954346, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3732/4000 [35:37<02:16,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3716416358947754, Predicted Probability: 0.4081, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.991235733032227, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3733/4000 [35:38<02:11,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.322931289672852, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.488437652587891, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3734/4000 [35:38<02:29,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8001954555511475, Predicted Probability: 0.1418, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.820611000061035, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3735/4000 [35:39<02:53,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.01801872253418, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8046369552612305, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3736/4000 [35:40<02:43,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.109651803970337, Predicted Probability: 0.9573, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8019936084747314, Predicted Probability: 0.0572, Prediction: 0.0

Epoch 2/3:  93%|█████████▎| 3737/4000 [35:41<02:54,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.966859817504883, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.590023994445801, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3738/4000 [35:41<03:00,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.703924179077148, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9552831649780273, Predicted Probability: 0.9812, Prediction: 1.0

Epoch 2/3:  93%|█████████▎| 3739/4000 [35:42<03:09,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.158495903015137, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.322165489196777, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  94%|█████████▎| 3740/4000 [35:42<02:28,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.359692096710205, Predicted Probability: 0.9874, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0481085777282715, Predicted Probability: 0.9547, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3741/4000 [35:43<02:13,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.511255264282227, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.551835060119629, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3742/4000 [35:43<02:09,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.49209451675415, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.388965606689453, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3743/4000 [35:44<02:28,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.010924816131592, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.50989818572998, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  94%|█████████▎| 3744/4000 [35:45<02:47,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.670097351074219, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.021991729736328, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  94%|█████████▎| 3745/4000 [35:45<02:30,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.360297203063965, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.292506217956543, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3746/4000 [35:46<02:18,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7631871700286865, Predicted Probability: 0.9773, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.847123146057129, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3747/4000 [35:46<02:35,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.323812007904053, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.880063772201538, Predicted Probability: 0.9469, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3748/4000 [35:47<02:46,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.336783409118652, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9063992500305176, Predicted Probability: 0.9482, Prediction: 1.0

Epoch 2/3:  94%|█████████▎| 3749/4000 [35:48<02:54,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.693066596984863, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1453351974487305, Predicted Probability: 0.9844, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3750/4000 [35:48<02:17,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.485672950744629, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.831171035766602, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3751/4000 [35:49<02:03,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.813607692718506, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.187202453613281, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3752/4000 [35:49<01:41,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.384442329406738, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.611099720001221, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3753/4000 [35:49<01:39,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.179274082183838, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.098741292953491, Predicted Probability: 0.8908, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3754/4000 [35:50<02:03,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.37346887588501, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.19233226776123, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3755/4000 [35:50<01:58,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.126322031021118, Predicted Probability: 0.1066, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.187353134155273, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3756/4000 [35:51<02:18,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.345003128051758, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.785991668701172, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3757/4000 [35:51<02:03,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.200371742248535, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0331926345825195, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3758/4000 [35:52<02:21,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.902409791946411, Predicted Probability: 0.0198, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.768171310424805, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3759/4000 [35:53<02:41,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.568493843078613, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.587632656097412, Predicted Probability: 0.9731, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3760/4000 [35:54<02:52,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.278951644897461, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.173334121704102, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3761/4000 [35:55<02:55,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0133056640625, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.892181873321533, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3762/4000 [35:55<02:45,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5516173839569092, Predicted Probability: 0.8251, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.215041160583496, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3763/4000 [35:56<02:49,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4370269775390625, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.2151702642440796, Predicted Probability: 0.4464, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3764/4000 [35:57<02:37,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.364738702774048, Predicted Probability: 0.9666, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.200221061706543, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3765/4000 [35:57<02:46,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2865853309631348, Predicted Probability: 0.0360, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.81843090057373, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3766/4000 [35:58<02:23,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.390702247619629, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.913774013519287, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3767/4000 [35:58<02:07,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.968189716339111, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.697455406188965, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3768/4000 [35:59<02:26,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.552770614624023, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.541557312011719, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3769/4000 [35:59<02:12,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.615455627441406, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3066630363464355, Predicted Probability: 0.9867, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3770/4000 [36:00<01:58,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.3969144821167, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.13150691986084, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3771/4000 [36:00<01:48,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.265374183654785, Predicted Probability: 0.0139, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.232450485229492, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3772/4000 [36:01<01:40,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.87841510772705, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4419844150543213, Predicted Probability: 0.9200, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3773/4000 [36:01<02:02,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.111474990844727, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5185930728912354, Predicted Probability: 0.9712, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3774/4000 [36:02<01:39,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.665471076965332, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.602456092834473, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3775/4000 [36:02<01:35,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7153420448303223, Predicted Probability: 0.9762, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.322982788085938, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3776/4000 [36:03<02:01,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.55861759185791, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.711444854736328, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3777/4000 [36:03<01:54,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2836785316467285, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.173276424407959, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3778/4000 [36:04<01:44,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.577362537384033, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.191652297973633, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  94%|█████████▍| 3779/4000 [36:04<01:48,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.928346157073975, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.101608276367188, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  94%|█████████▍| 3780/4000 [36:05<01:40,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.818216323852539, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2584874629974365, Predicted Probability: 0.9054, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3781/4000 [36:05<01:34,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.513249397277832, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.8283185958862305, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3782/4000 [36:05<01:19,  2.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.659435272216797, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.454195976257324, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3783/4000 [36:06<01:46,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.077733993530273, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.940520763397217, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3784/4000 [36:06<01:27,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.841352939605713, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7925407886505127, Predicted Probability: 0.9780, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3785/4000 [36:06<01:25,  2.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.753595352172852, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.751253128051758, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3786/4000 [36:07<01:46,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.7818557024002075, Predicted Probability: 0.3139, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4523284435272217, Predicted Probability: 0.9207, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3787/4000 [36:08<02:04,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8022918701171875, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.060474872589111, Predicted Probability: 0.0169, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3788/4000 [36:08<01:55,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7172152996063232, Predicted Probability: 0.0620, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.89780330657959, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3789/4000 [36:09<01:44,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.3511323928833, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5407377481460571, Predicted Probability: 0.1764, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3790/4000 [36:10<02:02,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.155035972595215, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.037317752838135, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3791/4000 [36:10<01:48,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.008072853088379, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.7511568069458, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3792/4000 [36:11<01:54,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.895068883895874, Predicted Probability: 0.9801, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.76698637008667, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3793/4000 [36:11<02:06,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.226861953735352, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3675074577331543, Predicted Probability: 0.0333, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3794/4000 [36:12<02:15,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9880242347717285, Predicted Probability: 0.0480, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.28742790222168, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3795/4000 [36:13<02:21,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.848651885986328, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.0947723388671875, Predicted Probability: 0.9836, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3796/4000 [36:13<02:01,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.328495025634766, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.452429294586182, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3797/4000 [36:14<02:13,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1353955268859863, Predicted Probability: 0.0417, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.917898178100586, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  95%|█████████▍| 3798/4000 [36:15<02:05,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.523665428161621, Predicted Probability: 0.9893, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.52233362197876, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 2/3:  95%|█████████▍| 3799/4000 [36:15<02:12,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.208878517150879, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.729028582572937, Predicted Probability: 0.6746, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3800/4000 [36:16<02:19,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.050832271575928, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.113611221313477, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3801/4000 [36:17<02:20,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.105005264282227, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.469061017036438, Predicted Probability: 0.1871, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3802/4000 [36:18<02:23,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.383875370025635, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.7315568923950195, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3803/4000 [36:18<02:02,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.442386150360107, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.155754089355469, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3804/4000 [36:19<02:12,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8687238693237305, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.806949615478516, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3805/4000 [36:19<02:03,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.1478075981140137, Predicted Probability: 0.0412, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.055530548095703, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3806/4000 [36:20<01:47,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.09350431710481644, Predicted Probability: 0.4766, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.542376518249512, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3807/4000 [36:21<02:04,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.068537712097168, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.563676357269287, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3808/4000 [36:21<02:13,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.961187362670898, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.34109115600586, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3809/4000 [36:22<02:15,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.999847888946533, Predicted Probability: 0.9526, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.564182281494141, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3810/4000 [36:23<02:16,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7223877906799316, Predicted Probability: 0.9383, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.375951766967773, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3811/4000 [36:23<01:56,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.638367176055908, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.657836437225342, Predicted Probability: 0.9749, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3812/4000 [36:24<01:42,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.808181047439575, Predicted Probability: 0.9783, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.208771228790283, Predicted Probability: 0.9854, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3813/4000 [36:24<01:22,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7930923700332642, Predicted Probability: 0.1427, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.380112409591675, Predicted Probability: 0.0847, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3814/4000 [36:24<01:28,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.137858867645264, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.611295700073242, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3815/4000 [36:25<01:46,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.530421257019043, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.825336456298828, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3816/4000 [36:26<01:35,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.482263565063477, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3670501708984375, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3817/4000 [36:26<01:26,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.57763385772705, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.68776273727417, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 2/3:  95%|█████████▌| 3818/4000 [36:27<01:31,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5254926681518555, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.857994079589844, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  95%|█████████▌| 3819/4000 [36:27<01:14,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.401865005493164, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.899350166320801, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3820/4000 [36:27<01:20,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9468092918396, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.113530158996582, Predicted Probability: 0.9839, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3821/4000 [36:28<01:26,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.725095272064209, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.470785140991211, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3822/4000 [36:29<01:40,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.462057113647461, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7994794845581055, Predicted Probability: 0.9426, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3823/4000 [36:29<01:48,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.132713317871094, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7761216163635254, Predicted Probability: 0.9414, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3824/4000 [36:30<01:55,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.060094356536865, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.835502624511719, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3825/4000 [36:31<01:52,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.010484218597412, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.32891583442688, Predicted Probability: 0.9654, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3826/4000 [36:31<01:47,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.635504245758057, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.719538688659668, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3827/4000 [36:32<01:59,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.884680271148682, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.837039947509766, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3828/4000 [36:33<01:45,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.511973857879639, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.667384624481201, Predicted Probability: 0.9907, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3830/4000 [36:33<01:27,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4391345977783203, Predicted Probability: 0.0802, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9854586124420166, Predicted Probability: 0.9519, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 7.985840797424316, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.248600482940674, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3831/4000 [36:34<01:38,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.003939628601074, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9575724601745605, Predicted Probability: 0.9506, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3832/4000 [36:35<01:26,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.666318893432617, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.793033599853516, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3833/4000 [36:35<01:37,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.87899398803711, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0247070789337158, Predicted Probability: 0.2641, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3834/4000 [36:36<01:34,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.407729625701904, Predicted Probability: 0.9880, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.547301769256592, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3835/4000 [36:36<01:33,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.113587856292725, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.98882532119751, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3836/4000 [36:37<01:23,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.952836036682129, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.935543537139893, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3837/4000 [36:37<01:27,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.618192672729492, Predicted Probability: 0.9739, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.137877464294434, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3838/4000 [36:38<01:36,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.0570807456970215, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1306233406066895, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3839/4000 [36:39<01:28,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4050345420837402, Predicted Probability: 0.0321, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.76741886138916, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3840/4000 [36:39<01:19,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.25612211227417, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.267897605895996, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3841/4000 [36:40<01:33,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4411821365356445, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7189881801605225, Predicted Probability: 0.0619, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3842/4000 [36:40<01:30,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2613027095794678, Predicted Probability: 0.0369, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.973048210144043, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3843/4000 [36:41<01:44,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7253291606903076, Predicted Probability: 0.0235, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.359888076782227, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3844/4000 [36:41<01:30,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.688231945037842, Predicted Probability: 0.9909, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.437036514282227, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3845/4000 [36:42<01:19,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.100038528442383, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.250807762145996, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3846/4000 [36:42<01:07,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.751895427703857, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5047495365142822, Predicted Probability: 0.9708, Prediction: 1.0

Epoch 2/3:  96%|█████████▌| 3847/4000 [36:42<01:03,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.329163551330566, Predicted Probability: 0.9870, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9021382331848145, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3848/4000 [36:43<01:18,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.937816619873047, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.528739929199219, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▌| 3849/4000 [36:44<01:32,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.349195957183838, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.629343032836914, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3850/4000 [36:44<01:21,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9874651432037354, Predicted Probability: 0.9818, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 5.610540390014648, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 2/3:  96%|█████████▋| 3851/4000 [36:45<01:33,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.476612091064453, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.839118003845215, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3852/4000 [36:45<01:14,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.5344877243042, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.437656402587891, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3853/4000 [36:46<01:23,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.67808198928833, Predicted Probability: 0.0643, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.903639793395996, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3854/4000 [36:47<01:14,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.968306064605713, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.010247230529785, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  96%|█████████▋| 3855/4000 [36:47<01:22,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.514521837234497, Predicted Probability: 0.9252, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.911611557006836, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3856/4000 [36:48<01:16,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.31187593936920166, Predicted Probability: 0.5773, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.774709224700928, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3857/4000 [36:49<01:33,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.623706340789795, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.622291564941406, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3858/4000 [36:49<01:37,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.525237083435059, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5607330799102783, Predicted Probability: 0.9724, Prediction: 1.0

Epoch 2/3:  96%|█████████▋| 3859/4000 [36:50<01:38,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.725010395050049, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.742938041687012, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  96%|█████████▋| 3860/4000 [36:51<01:24,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.87644624710083, Predicted Probability: 0.9797, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.063304901123047, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3861/4000 [36:51<01:29,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.704839706420898, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.083475351333618, Predicted Probability: 0.9562, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3862/4000 [36:52<01:33,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3045077323913574, Predicted Probability: 0.9646, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.944061756134033, Predicted Probability: 0.0190, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3863/4000 [36:53<01:40,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.060880661010742, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5031328201293945, Predicted Probability: 0.0292, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3864/4000 [36:53<01:31,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9126031398773193, Predicted Probability: 0.1287, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.279468059539795, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3865/4000 [36:54<01:18,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.413408279418945, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.949682712554932, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3866/4000 [36:54<01:12,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.617772102355957, Predicted Probability: 0.0261, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.71484088897705, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3867/4000 [36:55<01:05,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.14625358581543, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.812170505523682, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3868/4000 [36:55<01:15,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.927956581115723, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.656353950500488, Predicted Probability: 0.9906, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3869/4000 [36:56<01:22,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1215755939483643, Predicted Probability: 0.8930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.915743827819824, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3870/4000 [36:56<01:04,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.653256416320801, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.742750644683838, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3871/4000 [36:57<01:12,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.050112247467041, Predicted Probability: 0.9548, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.714583396911621, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3872/4000 [36:58<01:11,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.623712062835693, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.886791229248047, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3873/4000 [36:58<01:04,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.480607032775879, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.230793476104736, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3874/4000 [36:58<00:52,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.880125045776367, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.569376945495605, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3875/4000 [36:59<00:50,  2.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.8165622353553772, Predicted Probability: 0.6935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.10353422164917, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3876/4000 [36:59<01:03,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.153658866882324, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.938711166381836, Predicted Probability: 0.9809, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3877/4000 [37:00<00:58,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.489025354385376, Predicted Probability: 0.9234, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.902076721191406, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3878/4000 [37:00<01:06,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.08629420399665833, Predicted Probability: 0.5216, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.765754699707031, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3879/4000 [37:01<01:05,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.875431060791016, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.458873748779297, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3880/4000 [37:01<00:59,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.718681812286377, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.479145050048828, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3881/4000 [37:02<01:08,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.126882553100586, Predicted Probability: 0.2447, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.00369644165039, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3882/4000 [37:03<01:01,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.303640365600586, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.054835319519043, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3883/4000 [37:03<00:55,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.023927211761475, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.807378768920898, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3884/4000 [37:03<00:58,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.650928497314453, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.763114929199219, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3885/4000 [37:04<01:08,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.333528518676758, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.056875228881836, Predicted Probability: 0.0170, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3886/4000 [37:05<01:12,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.2084150314331055, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.297628879547119, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3887/4000 [37:06<01:14,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8851711750030518, Predicted Probability: 0.9471, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.353060245513916, Predicted Probability: 0.9132, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3888/4000 [37:06<01:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.673916339874268, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.133505821228027, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3889/4000 [37:07<01:08,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.404092788696289, Predicted Probability: 0.9879, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4106853008270264, Predicted Probability: 0.1961, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3890/4000 [37:08<01:13,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6169193983078003, Predicted Probability: 0.8344, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.93408489227295, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3891/4000 [37:08<01:18,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.385040283203125, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.966133117675781, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3892/4000 [37:09<01:18,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.8219633102417, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9039764404296875, Predicted Probability: 0.9480, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3893/4000 [37:10<01:19,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.324921607971191, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.092988014221191, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3894/4000 [37:11<01:19,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.812507629394531, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1456098556518555, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3895/4000 [37:11<01:17,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.072320938110352, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9310187101364136, Predicted Probability: 0.1266, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3896/4000 [37:12<01:21,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.143695831298828, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.680758476257324, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3897/4000 [37:13<01:02,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.488009452819824, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.170313835144043, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  97%|█████████▋| 3898/4000 [37:13<01:05,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.14763355255127, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9211671352386475, Predicted Probability: 0.9489, Prediction: 1.0

Epoch 2/3:  97%|█████████▋| 3899/4000 [37:14<01:10,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.149718999862671, Predicted Probability: 0.9589, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.281905651092529, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3900/4000 [37:15<01:12,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.952854156494141, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.860410690307617, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3901/4000 [37:16<01:14,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.869358777999878, Predicted Probability: 0.9463, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.869645118713379, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3902/4000 [37:16<01:02,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.731366157531738, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4427080154418945, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3903/4000 [37:17<01:05,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.2601423263549805, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.280265808105469, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3904/4000 [37:18<01:06,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.660098075866699, Predicted Probability: 0.9346, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.12302017211914, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3905/4000 [37:18<01:01,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.769668579101562, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.447154998779297, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3906/4000 [37:19<01:04,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0363727807998657, Predicted Probability: 0.2619, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.556063652038574, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3907/4000 [37:19<00:50,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.788110256195068, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.994192123413086, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3908/4000 [37:19<00:44,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.06849479675293, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.795083045959473, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3909/4000 [37:20<00:41,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.953396797180176, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.495148658752441, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3910/4000 [37:21<00:49,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.109247207641602, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6639392375946045, Predicted Probability: 0.1592, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3911/4000 [37:21<00:54,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.963953971862793, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0422184467315674, Predicted Probability: 0.2607, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3912/4000 [37:22<00:52,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.621757984161377, Predicted Probability: 0.1650, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.456387042999268, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3913/4000 [37:22<00:45,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.196855306625366, Predicted Probability: 0.1000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.482872486114502, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3914/4000 [37:23<00:41,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9185051918029785, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.578645706176758, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3915/4000 [37:23<00:47,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.29507827758789, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0470266342163086, Predicted Probability: 0.8856, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3916/4000 [37:24<00:50,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.220103740692139, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.807641863822937, Predicted Probability: 0.3084, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3917/4000 [37:24<00:44,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.845028877258301, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.20561006665229797, Predicted Probability: 0.5512, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3918/4000 [37:25<00:44,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.085030555725098, Predicted Probability: 0.9835, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.815755844116211, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3919/4000 [37:26<00:48,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2836751341819763, Predicted Probability: 0.4296, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.459104061126709, Predicted Probability: 0.9886, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3920/4000 [37:26<00:47,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.910611152648926, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5879080295562744, Predicted Probability: 0.9731, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3921/4000 [37:27<00:51,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.602375030517578, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6053361892700195, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3922/4000 [37:27<00:44,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.063720941543579, Predicted Probability: 0.9554, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.789196014404297, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3923/4000 [37:28<00:47,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.966759443283081, Predicted Probability: 0.9814, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.716832160949707, Predicted Probability: 0.9763, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3924/4000 [37:28<00:37,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.854478597640991, Predicted Probability: 0.0545, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.042490005493164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3925/4000 [37:29<00:34,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.696635246276855, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.595732688903809, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3926/4000 [37:29<00:28,  2.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.313312530517578, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.475588321685791, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3927/4000 [37:30<00:33,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8893141746521, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.492380142211914, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3928/4000 [37:30<00:31,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.357410907745361, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.893832206726074, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3929/4000 [37:30<00:31,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.561405181884766, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.67940902709961, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3930/4000 [37:31<00:29,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.01803970336914, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.517798900604248, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3931/4000 [37:31<00:32,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7831854820251465, Predicted Probability: 0.9778, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.345242500305176, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3932/4000 [37:32<00:33,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.010146141052246, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5422186851501465, Predicted Probability: 0.0730, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3933/4000 [37:32<00:34,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7630820274353027, Predicted Probability: 0.9406, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.033535480499268, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3934/4000 [37:33<00:38,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9591249823570251, Predicted Probability: 0.2771, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.504660606384277, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3935/4000 [37:34<00:40,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.576600074768066, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.25031578540802, Predicted Probability: 0.2226, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3936/4000 [37:34<00:31,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.616569519042969, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.048327445983887, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3937/4000 [37:35<00:36,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.483343124389648, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.192834854125977, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  98%|█████████▊| 3938/4000 [37:35<00:31,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31990084052085876, Predicted Probability: 0.4207, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.17025089263916, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  98%|█████████▊| 3939/4000 [37:36<00:28,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4162187576293945, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.539491176605225, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 2/3:  99%|█████████▊| 3941/4000 [37:36<00:24,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.281783103942871, Predicted Probability: 0.9638, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.012306213378906, Predicted Probability: 0.0024, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.154337882995605, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.838004112243652, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  99%|█████████▊| 3942/4000 [37:37<00:31,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.366340637207031, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6154069900512695, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 2/3:  99%|█████████▊| 3943/4000 [37:38<00:34,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4982872009277344, Predicted Probability: 0.9240, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.613227844238281, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  99%|█████████▊| 3944/4000 [37:39<00:32,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.343212127685547, Predicted Probability: 0.9872, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.984450817108154, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3:  99%|█████████▊| 3945/4000 [37:39<00:28,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.779775142669678, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.630862712860107, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  99%|█████████▊| 3946/4000 [37:40<00:32,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.206993103027344, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.900145530700684, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 2/3:  99%|█████████▊| 3947/4000 [37:40<00:34,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.947680473327637, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8817873001098633, Predicted Probability: 0.0202, Prediction: 0.0

Epoch 2/3:  99%|█████████▊| 3948/4000 [37:41<00:35,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4657080173492432, Predicted Probability: 0.1876, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.04507827758789, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3:  99%|█████████▊| 3949/4000 [37:42<00:35,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.394805908203125, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.016646862030029, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3950/4000 [37:42<00:27,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.90698528289795, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.347228050231934, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3951/4000 [37:43<00:24,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.317276000976562, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.575085639953613, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3953/4000 [37:44<00:21,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8895010948181152, Predicted Probability: 0.0200, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.04748821258545, Predicted Probability: 0.0003, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.81774616241455, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.858855247497559, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3954/4000 [37:44<00:25,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.240674018859863, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0099568367004395, Predicted Probability: 0.9530, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3955/4000 [37:45<00:22,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.762758255004883, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.524740695953369, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3956/4000 [37:45<00:20,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.444550514221191, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.596170425415039, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3957/4000 [37:46<00:20,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.992403030395508, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.930926322937012, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3958/4000 [37:46<00:18,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.764915466308594, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4195563495159149, Predicted Probability: 0.3966, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3959/4000 [37:46<00:15,  2.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.374611854553223, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.455427169799805, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3961/4000 [37:47<00:12,  3.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.412650108337402, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.18539810180664, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.777250289916992, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.241629600524902, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3962/4000 [37:48<00:17,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.433768272399902, Predicted Probability: 0.0117, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.977341651916504, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3963/4000 [37:48<00:20,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.398535966873169, Predicted Probability: 0.9167, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.802045822143555, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3964/4000 [37:49<00:21,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.71492338180542, Predicted Probability: 0.9911, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.654609680175781, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3965/4000 [37:50<00:23,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.013622283935547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5798797607421875, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3966/4000 [37:51<00:23,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.000221252441406, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0523064136505127, Predicted Probability: 0.9549, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3967/4000 [37:51<00:23,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.257176399230957, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.705721855163574, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3968/4000 [37:52<00:18,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.65124225616455, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.994844436645508, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3969/4000 [37:52<00:19,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7830610275268555, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4517574906349182, Predicted Probability: 0.3889, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3970/4000 [37:53<00:19,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6012635231018066, Predicted Probability: 0.9734, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.943296432495117, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3971/4000 [37:53<00:16,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.118756294250488, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.970066070556641, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3972/4000 [37:54<00:12,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.152431488037109, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.885147094726562, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3973/4000 [37:54<00:14,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.029651641845703, Predicted Probability: 0.9539, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.529211044311523, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3974/4000 [37:55<00:15,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.689228057861328, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.40278959274292, Predicted Probability: 0.9678, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3975/4000 [37:55<00:13,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.409351825714111, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.843535423278809, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3976/4000 [37:56<00:14,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.177889823913574, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.383140563964844, Predicted Probability: 0.0046, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3977/4000 [37:57<00:15,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.675342559814453, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.399251461029053, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 2/3:  99%|█████████▉| 3978/4000 [37:57<00:12,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.057869911193848, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.956039428710938, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3:  99%|█████████▉| 3979/4000 [37:58<00:13,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.485517501831055, Predicted Probability: 0.0111, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.028952598571777, Predicted Probability: 0.9825, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3980/4000 [37:59<00:13,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.696842670440674, Predicted Probability: 0.9368, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.367374420166016, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3981/4000 [37:59<00:11,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.839414596557617, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.9059906005859375, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3982/4000 [38:00<00:09,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.711524963378906, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.792669773101807, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3983/4000 [38:00<00:09,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.579902172088623, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.106799602508545, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3984/4000 [38:01<00:10,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.369170188903809, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.976879119873047, Predicted Probability: 0.0184, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3985/4000 [38:01<00:08,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.068634986877441, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.883685827255249, Predicted Probability: 0.9798, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3986/4000 [38:02<00:08,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.908868789672852, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8899435997009277, Predicted Probability: 0.9473, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3987/4000 [38:02<00:06,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.426445960998535, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.37851333618164, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3988/4000 [38:03<00:06,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.259613513946533, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.046642303466797, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3989/4000 [38:04<00:05,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.132674694061279, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.035172462463379, Predicted Probability: 0.1156, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3990/4000 [38:04<00:06,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.60273265838623, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.985472679138184, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3991/4000 [38:05<00:04,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.867128372192383, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.668392181396484, Predicted Probability: 0.9907, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3992/4000 [38:05<00:04,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.860703468322754, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.07108211517334, Predicted Probability: 0.9832, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3993/4000 [38:06<00:04,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5584543943405151, Predicted Probability: 0.8261, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.735354423522949, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3994/4000 [38:07<00:03,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.228521347045898, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.874208450317383, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3995/4000 [38:07<00:02,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.616860389709473, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.864598274230957, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 2/3: 100%|█████████▉| 3996/4000 [38:08<00:02,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.056621551513672, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3860673904418945, Predicted Probability: 0.9158, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3997/4000 [38:09<00:01,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.406660556793213, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.076901435852051, Predicted Probability: 0.8886, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3998/4000 [38:09<00:01,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.944236993789673, Predicted Probability: 0.0500, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.618861198425293, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 2/3: 100%|█████████▉| 3999/4000 [38:10<00:00,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.040672302246094, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.741942405700684, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 2/3: 100%|██████████| 4000/4000 [38:10<00:00,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.355835437774658, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.817193031311035, Predicted Probability: 0.9999, Prediction: 1.0
Epoch 2, Loss: 0.0742, Accuracy: 0.9784

Epoch 3/3:   0%|          | 1/4000 [00:00<49:24,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.716002464294434, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9519598484039307, Predicted Probability: 0.9504, Prediction: 1.0

Epoch 3/3:   0%|          | 2/4000 [00:01<50:43,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.704787731170654, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.28856086730957, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 3/3:   0%|          | 3/4000 [00:01<33:57,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.277518272399902, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.066171646118164, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   0%|          | 4/4000 [00:02<33:03,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.43195915222168, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.407145500183105, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   0%|          | 5/4000 [00:02<30:26,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.735063552856445, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4373395442962646, Predicted Probability: 0.0311, Prediction: 0.0

Epoch 3/3:   0%|          | 6/4000 [00:03<39:25,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.215859413146973, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.573525428771973, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   0%|          | 7/4000 [00:04<45:28,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.734933853149414, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.367302894592285, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:   0%|          | 8/4000 [00:05<48:08,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.289159774780273, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.075481414794922, Predicted Probability: 0.0167, Prediction: 0.0

Epoch 3/3:   0%|          | 10/4000 [00:06<37:38,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.836148262023926, Predicted Probability: 0.9446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.482535362243652, Predicted Probability: 0.0002, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.797153949737549, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.92232608795166, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:   0%|          | 11/4000 [00:06<30:27,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.87047290802002, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.637496948242188, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   0%|          | 12/4000 [00:07<36:45,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.217039108276367, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.589854717254639, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 3/3:   0%|          | 13/4000 [00:07<40:33,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1301465034484863, Predicted Probability: 0.9581, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.539966583251953, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   0%|          | 14/4000 [00:08<45:30,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7945709228515625, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.148780345916748, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 3/3:   0%|          | 15/4000 [00:09<39:18,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.402286529541016, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.566643238067627, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:   0%|          | 16/4000 [00:09<35:27,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.953346252441406, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.384724617004395, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   0%|          | 17/4000 [00:10<40:19,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.379470825195312, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.237307548522949, Predicted Probability: 0.9622, Prediction: 1.0

Epoch 3/3:   0%|          | 18/4000 [00:10<43:31,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.327987670898438, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0663559436798096, Predicted Probability: 0.1124, Prediction: 0.0

Epoch 3/3:   0%|          | 19/4000 [00:11<46:00,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.105290412902832, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.038804054260254, Predicted Probability: 0.9827, Prediction: 1.0

Epoch 3/3:   0%|          | 20/4000 [00:12<47:18,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.211133003234863, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9080874919891357, Predicted Probability: 0.1292, Prediction: 0.0

Epoch 3/3:   1%|          | 21/4000 [00:13<49:26,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.970970153808594, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.330037117004395, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   1%|          | 22/4000 [00:14<50:11,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.135834217071533, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.507203578948975, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   1%|          | 23/4000 [00:14<50:53,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.393003940582275, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.909324884414673, Predicted Probability: 0.9483, Prediction: 1.0

Epoch 3/3:   1%|          | 24/4000 [00:15<43:04,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.152547836303711, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.18808364868164, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   1%|          | 25/4000 [00:16<45:16,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.89596176147461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2785825729370117, Predicted Probability: 0.9071, Prediction: 1.0

Epoch 3/3:   1%|          | 26/4000 [00:17<54:12,  1.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.9265618324279785, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.957036972045898, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   1%|          | 27/4000 [00:17<42:12,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.916901588439941, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.03026008605957, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:   1%|          | 28/4000 [00:18<44:08,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6437597274780273, Predicted Probability: 0.9745, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.128717422485352, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:   1%|          | 29/4000 [00:18<38:22,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.377815246582031, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.71618366241455, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   1%|          | 30/4000 [00:18<34:12,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.410593032836914, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9128713607788086, Predicted Probability: 0.0196, Prediction: 0.0

Epoch 3/3:   1%|          | 31/4000 [00:19<27:56,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.244444370269775, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.973188400268555, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   1%|          | 32/4000 [00:19<28:19,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.868040084838867, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.162868499755859, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 3/3:   1%|          | 33/4000 [00:19<27:21,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.107864379882812, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.646357536315918, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 3/3:   1%|          | 34/4000 [00:20<27:59,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.546504020690918, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.702597141265869, Predicted Probability: 0.0241, Prediction: 0.0

Epoch 3/3:   1%|          | 35/4000 [00:20<27:27,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.056653022766113, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.8035149574279785, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:   1%|          | 36/4000 [00:21<26:56,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.955774307250977, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.504135608673096, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 3/3:   1%|          | 37/4000 [00:21<26:08,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.782642364501953, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.940104365348816, Predicted Probability: 0.1256, Prediction: 0.0

Epoch 3/3:   1%|          | 38/4000 [00:22<35:18,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.928537368774414, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.309043884277344, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   1%|          | 39/4000 [00:22<35:58,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.395890235900879, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.627806186676025, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:   1%|          | 40/4000 [00:23<29:19,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.195594787597656, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.580181121826172, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   1%|          | 41/4000 [00:23<36:39,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.859318733215332, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.764278411865234, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   1%|          | 42/4000 [00:24<36:30,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.8305463790893555, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.509803056716919, Predicted Probability: 0.0290, Prediction: 0.0

Epoch 3/3:   1%|          | 43/4000 [00:24<33:11,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.835553169250488, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.614744663238525, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:   1%|          | 44/4000 [00:25<27:13,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.444622039794922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.259897232055664, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   1%|          | 45/4000 [00:25<34:02,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8393683433532715, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6854500770568848, Predicted Probability: 0.0245, Prediction: 0.0

Epoch 3/3:   1%|          | 46/4000 [00:26<42:01,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.865594387054443, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.825273036956787, Predicted Probability: 0.0080, Prediction: 0.0

Epoch 3/3:   1%|          | 47/4000 [00:26<33:43,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.253745079040527, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.490623474121094, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   1%|          | 48/4000 [00:27<38:51,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.143157958984375, Predicted Probability: 0.0156, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.085436820983887, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   1%|          | 49/4000 [00:28<41:15,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.096124649047852, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0575703382492065, Predicted Probability: 0.7422, Prediction: 1.0

Epoch 3/3:   1%|▏         | 50/4000 [00:29<45:11,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5341420769691467, Predicted Probability: 0.3696, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.105947494506836, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   1%|▏         | 51/4000 [00:29<35:37,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.614908218383789, Predicted Probability: 0.9318, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.945157051086426, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   1%|▏         | 52/4000 [00:29<33:38,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.772547960281372, Predicted Probability: 0.0588, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.382288932800293, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:   1%|▏         | 53/4000 [00:30<37:53,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.010681629180908, Predicted Probability: 0.9531, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.206005096435547, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   1%|▏         | 54/4000 [00:31<33:53,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.348758697509766, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.303097248077393, Predicted Probability: 0.0133, Prediction: 0.0

Epoch 3/3:   1%|▏         | 55/4000 [00:31<34:24,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6489436626434326, Predicted Probability: 0.0661, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.342780590057373, Predicted Probability: 0.0128, Prediction: 0.0

Epoch 3/3:   1%|▏         | 56/4000 [00:31<32:13,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.724295616149902, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.054765701293945, Predicted Probability: 0.9830, Prediction: 1.0

Epoch 3/3:   1%|▏         | 57/4000 [00:32<37:37,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.375299453735352, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.006381034851074, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:   1%|▏         | 58/4000 [00:33<42:59,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.030885696411133, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.499002456665039, Predicted Probability: 0.0110, Prediction: 0.0

Epoch 3/3:   1%|▏         | 59/4000 [00:34<45:39,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.761075019836426, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.134793281555176, Predicted Probability: 0.8942, Prediction: 1.0

Epoch 3/3:   2%|▏         | 60/4000 [00:34<39:11,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.685217380523682, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.05914831161499, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 3/3:   2%|▏         | 61/4000 [00:35<42:23,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.213471412658691, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.310349225997925, Predicted Probability: 0.9648, Prediction: 1.0

Epoch 3/3:   2%|▏         | 62/4000 [00:36<44:41,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2818721532821655, Predicted Probability: 0.7828, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.248008728027344, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   2%|▏         | 63/4000 [00:37<46:13,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.423942565917969, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.670189380645752, Predicted Probability: 0.9352, Prediction: 1.0

Epoch 3/3:   2%|▏         | 64/4000 [00:37<49:03,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.464026927947998, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.158777236938477, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:   2%|▏         | 65/4000 [00:38<45:23,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6037306785583496, Predicted Probability: 0.8325, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.074448585510254, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 66/4000 [00:39<46:02,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.141993522644043, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.763230562210083, Predicted Probability: 0.9773, Prediction: 1.0

Epoch 3/3:   2%|▏         | 67/4000 [00:39<39:44,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.387616157531738, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.69253158569336, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   2%|▏         | 68/4000 [00:39<35:31,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.065768241882324, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.729642868041992, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   2%|▏         | 69/4000 [00:40<32:08,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.153754234313965, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.966431617736816, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 3/3:   2%|▏         | 70/4000 [00:40<29:41,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.468217849731445, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.139582633972168, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   2%|▏         | 71/4000 [00:41<35:35,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6575825214385986, Predicted Probability: 0.1601, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.899658203125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 72/4000 [00:41<35:30,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.6317572593688965, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.185832023620605, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   2%|▏         | 73/4000 [00:42<28:56,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6111578941345215, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.745413780212402, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   2%|▏         | 74/4000 [00:42<24:15,  2.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.69050931930542, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.947965145111084, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:   2%|▏         | 75/4000 [00:42<20:58,  3.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.486026763916016, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.219686508178711, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   2%|▏         | 76/4000 [00:43<29:18,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.016777038574219, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.41491413116455, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 77/4000 [00:44<35:42,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.056138038635254, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.567787170410156, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 3/3:   2%|▏         | 78/4000 [00:44<32:12,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.136992454528809, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.789480686187744, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:   2%|▏         | 79/4000 [00:44<29:49,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.330262184143066, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.187617778778076, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:   2%|▏         | 80/4000 [00:45<35:48,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.066135883331299, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7728506922721863, Predicted Probability: 0.3159, Prediction: 0.0

Epoch 3/3:   2%|▏         | 81/4000 [00:46<40:24,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.211869955062866, Predicted Probability: 0.9613, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.096954345703125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 82/4000 [00:46<39:18,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.692144393920898, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.050390243530273, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   2%|▏         | 83/4000 [00:47<41:24,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6922826766967773, Predicted Probability: 0.9366, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.449451446533203, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 84/4000 [00:47<33:03,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.524604320526123, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.33734130859375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   2%|▏         | 85/4000 [00:48<30:25,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.835441589355469, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.558640480041504, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   2%|▏         | 86/4000 [00:48<28:31,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.475096702575684, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.114485263824463, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 3/3:   2%|▏         | 87/4000 [00:49<27:30,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.941643714904785, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.342263221740723, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   2%|▏         | 88/4000 [00:49<23:10,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.486019134521484, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.63386344909668, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   2%|▏         | 89/4000 [00:49<26:37,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2628497779369354, Predicted Probability: 0.5653, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.404796600341797, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 90/4000 [00:50<34:34,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9410576820373535, Predicted Probability: 0.9809, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.482097625732422, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   2%|▏         | 91/4000 [00:51<39:02,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.349661827087402, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7828292846679688, Predicted Probability: 0.1440, Prediction: 0.0

Epoch 3/3:   2%|▏         | 92/4000 [00:51<34:34,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.959453582763672, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.912635803222656, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   2%|▏         | 93/4000 [00:52<31:24,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.736089706420898, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.5673189163208, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   2%|▏         | 94/4000 [00:52<36:48,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.479057312011719, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.382220268249512, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 95/4000 [00:53<36:11,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.681429147720337, Predicted Probability: 0.0641, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.12828540802002, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   2%|▏         | 96/4000 [00:54<39:34,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3249762058258057, Predicted Probability: 0.9109, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.423653602600098, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   2%|▏         | 97/4000 [00:55<46:46,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7364006042480469, Predicted Probability: 0.1498, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.572816371917725, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:   2%|▏         | 98/4000 [00:55<47:29,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.403923034667969, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.188843727111816, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 3/3:   2%|▏         | 99/4000 [00:56<48:26,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.614333152770996, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.033927917480469, Predicted Probability: 0.0174, Prediction: 0.0

Epoch 3/3:   2%|▎         | 100/4000 [00:57<49:05,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7763278484344482, Predicted Probability: 0.9414, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.094006538391113, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   3%|▎         | 101/4000 [00:57<39:40,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.141486167907715, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.650320529937744, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:   3%|▎         | 102/4000 [00:58<34:56,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.785118103027344, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.491749286651611, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 3/3:   3%|▎         | 103/4000 [00:58<31:23,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.448723793029785, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.823210716247559, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   3%|▎         | 104/4000 [00:59<36:43,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.973211288452148, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.699423789978027, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 3/3:   3%|▎         | 105/4000 [00:59<31:05,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.265466690063477, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.690044403076172, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   3%|▎         | 106/4000 [00:59<28:48,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.915820121765137, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.612372398376465, Predicted Probability: 0.9902, Prediction: 1.0

Epoch 3/3:   3%|▎         | 107/4000 [01:00<27:22,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.891861915588379, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.927018642425537, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:   3%|▎         | 108/4000 [01:00<33:21,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.32620620727539, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.363286256790161, Predicted Probability: 0.0860, Prediction: 0.0

Epoch 3/3:   3%|▎         | 109/4000 [01:01<34:16,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.199725151062012, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.00806713104248, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   3%|▎         | 110/4000 [01:02<34:56,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.188369750976562, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.724640846252441, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:   3%|▎         | 111/4000 [01:02<31:51,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.7334160804748535, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.834630966186523, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:   3%|▎         | 112/4000 [01:02<30:41,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.776278257369995, Predicted Probability: 0.0224, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.4366631507873535, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:   3%|▎         | 113/4000 [01:03<28:36,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.139124870300293, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.317300796508789, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:   3%|▎         | 114/4000 [01:03<34:11,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.784956693649292, Predicted Probability: 0.9419, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.280741691589355, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   3%|▎         | 115/4000 [01:04<31:17,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.948606491088867, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.07440710067749, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:   3%|▎         | 116/4000 [01:04<30:18,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.669953346252441, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1994481086730957, Predicted Probability: 0.0392, Prediction: 0.0

Epoch 3/3:   3%|▎         | 117/4000 [01:05<36:05,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.993344306945801, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4345452785491943, Predicted Probability: 0.9194, Prediction: 1.0

Epoch 3/3:   3%|▎         | 118/4000 [01:05<32:36,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.89301586151123, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.608969211578369, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 3/3:   3%|▎         | 119/4000 [01:06<36:44,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6757402420043945, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5825324058532715, Predicted Probability: 0.9899, Prediction: 1.0

Epoch 3/3:   3%|▎         | 120/4000 [01:07<34:06,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.94699764251709, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.350998878479004, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 3/3:   3%|▎         | 121/4000 [01:07<38:33,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5658979415893555, Predicted Probability: 0.9725, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.669719696044922, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   3%|▎         | 122/4000 [01:08<34:12,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.107613563537598, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.456006050109863, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 3/3:   3%|▎         | 123/4000 [01:08<27:54,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.772578239440918, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.277361869812012, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   3%|▎         | 124/4000 [01:09<33:30,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.716669797897339, Predicted Probability: 0.9763, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.51110553741455, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   3%|▎         | 125/4000 [01:09<37:55,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.57772159576416, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.077019691467285, Predicted Probability: 0.9559, Prediction: 1.0

Epoch 3/3:   3%|▎         | 127/4000 [01:10<29:58,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.202532768249512, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.317428112030029, Predicted Probability: 0.9982, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -6.1100754737854, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.832826614379883, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   3%|▎         | 128/4000 [01:11<36:13,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.029912948608398, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9753165245056152, Predicted Probability: 0.9816, Prediction: 1.0

Epoch 3/3:   3%|▎         | 129/4000 [01:11<29:18,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.280561923980713, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.672059535980225, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:   3%|▎         | 130/4000 [01:12<34:33,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.276984214782715, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5713868141174316, Predicted Probability: 0.9290, Prediction: 1.0

Epoch 3/3:   3%|▎         | 131/4000 [01:12<31:24,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.354338645935059, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.436866760253906, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 3/3:   3%|▎         | 132/4000 [01:13<29:05,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.219600200653076, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.57811164855957, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:   3%|▎         | 133/4000 [01:13<30:59,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.346497535705566, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.341689109802246, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:   3%|▎         | 134/4000 [01:14<32:29,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.038861274719238, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.07109260559082, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   3%|▎         | 135/4000 [01:14<33:17,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.744475841522217, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.9699835777282715, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:   3%|▎         | 136/4000 [01:15<37:55,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.575684070587158, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7813920974731445, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   3%|▎         | 137/4000 [01:15<33:45,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.948453187942505, Predicted Probability: 0.0189, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.47728443145752, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   3%|▎         | 138/4000 [01:16<30:48,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.970622062683105, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.1571649312973022, Predicted Probability: 0.7608, Prediction: 1.0

Epoch 3/3:   3%|▎         | 139/4000 [01:16<36:09,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.536043167114258, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9077601432800293, Predicted Probability: 0.9482, Prediction: 1.0

Epoch 3/3:   4%|▎         | 140/4000 [01:17<32:41,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.313010215759277, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.4799400568008423, Predicted Probability: 0.3823, Prediction: 0.0

Epoch 3/3:   4%|▎         | 141/4000 [01:18<37:43,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4744572639465332, Predicted Probability: 0.8137, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.138498306274414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   4%|▎         | 142/4000 [01:18<33:37,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.956714630126953, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.007987976074219, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:   4%|▎         | 143/4000 [01:18<27:28,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.891548156738281, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.947298049926758, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   4%|▎         | 145/4000 [01:19<27:16,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.470661163330078, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4893999099731445, Predicted Probability: 0.9889, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.54006576538086, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.738343238830566, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   4%|▎         | 146/4000 [01:19<26:11,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.848954677581787, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.990063667297363, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   4%|▎         | 147/4000 [01:20<22:14,  2.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.52514934539795, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.114324569702148, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:   4%|▎         | 148/4000 [01:20<26:08,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.47011661529541, Predicted Probability: 0.9698, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.328429222106934, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:   4%|▎         | 149/4000 [01:20<22:10,  2.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.292385101318359, Predicted Probability: 0.9950, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.540365219116211, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   4%|▍         | 150/4000 [01:21<29:53,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.896204710006714, Predicted Probability: 0.9477, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.343813419342041, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:   4%|▍         | 151/4000 [01:21<24:55,  2.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.54448938369751, Predicted Probability: 0.0105, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.68523120880127, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   4%|▍         | 152/4000 [01:22<26:06,  2.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.665165901184082, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.608220100402832, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   4%|▍         | 153/4000 [01:22<25:41,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.05959415435791, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.982542037963867, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   4%|▍         | 154/4000 [01:23<28:40,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8874590396881104, Predicted Probability: 0.9799, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.957874298095703, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:   4%|▍         | 155/4000 [01:23<27:19,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.551606178283691, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.932740211486816, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   4%|▍         | 156/4000 [01:24<33:44,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8537750244140625, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.483108520507812, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   4%|▍         | 157/4000 [01:25<37:48,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.53805160522461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.576493263244629, Predicted Probability: 0.9293, Prediction: 1.0

Epoch 3/3:   4%|▍         | 158/4000 [01:25<33:24,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.293170928955078, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.2642333507537842, Predicted Probability: 0.2202, Prediction: 0.0

Epoch 3/3:   4%|▍         | 159/4000 [01:26<33:43,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.65337610244751, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.575363874435425, Predicted Probability: 0.0272, Prediction: 0.0

Epoch 3/3:   4%|▍         | 160/4000 [01:26<37:09,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7864766120910645, Predicted Probability: 0.1435, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.9180908203125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   4%|▍         | 161/4000 [01:27<40:09,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.388024806976318, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5407328605651855, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   4%|▍         | 162/4000 [01:27<35:27,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.044650077819824, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.206093788146973, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   4%|▍         | 164/4000 [01:28<31:43,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.601383209228516, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9235031604766846, Predicted Probability: 0.9490, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.620767593383789, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.954113006591797, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   4%|▍         | 165/4000 [01:29<29:22,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.328371047973633, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.551921844482422, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:   4%|▍         | 166/4000 [01:29<34:20,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.8806352615356445, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9254109859466553, Predicted Probability: 0.9491, Prediction: 1.0

Epoch 3/3:   4%|▍         | 167/4000 [01:30<32:38,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.921420097351074, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.446633338928223, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   4%|▍         | 169/4000 [01:31<29:28,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.776998519897461, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2750016450881958, Predicted Probability: 0.2184, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.626461029052734, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.285212516784668, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   4%|▍         | 170/4000 [01:31<27:43,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.326384544372559, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.274117469787598, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   4%|▍         | 171/4000 [01:32<34:05,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1986196041107178, Predicted Probability: 0.9608, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.917724609375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   4%|▍         | 172/4000 [01:32<30:58,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2766945362091064, Predicted Probability: 0.0931, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.105748176574707, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.367073059082031, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.758040428161621, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   4%|▍         | 174/4000 [01:33<31:31,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.900490760803223, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.061394691467285, Predicted Probability: 0.9831, Prediction: 1.0

Epoch 3/3:   4%|▍         | 175/4000 [01:34<36:30,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.327969551086426, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.806495666503906, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 3/3:   4%|▍         | 176/4000 [01:35<39:21,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.809647560119629, Predicted Probability: 0.9432, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8860578536987305, Predicted Probability: 0.0528, Prediction: 0.0

Epoch 3/3:   4%|▍         | 177/4000 [01:35<34:55,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.070595741271973, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.487911224365234, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   4%|▍         | 178/4000 [01:36<38:55,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.95688009262085, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.828134536743164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   4%|▍         | 179/4000 [01:37<42:56,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.315965175628662, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7506422996521, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   4%|▍         | 180/4000 [01:37<43:56,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.89691162109375, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.257643222808838, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 3/3:   5%|▍         | 181/4000 [01:38<39:12,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.910462379455566, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.762139320373535, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   5%|▍         | 182/4000 [01:39<41:13,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.311391830444336, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9763476848602295, Predicted Probability: 0.9515, Prediction: 1.0

Epoch 3/3:   5%|▍         | 183/4000 [01:39<42:41,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.126105308532715, Predicted Probability: 0.9580, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6030802726745605, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 3/3:   5%|▍         | 184/4000 [01:40<40:06,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.583332538604736, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.78963565826416, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   5%|▍         | 185/4000 [01:40<31:55,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.04161262512207, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.719585418701172, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   5%|▍         | 186/4000 [01:40<29:37,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.042145729064941, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.600998878479004, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 3/3:   5%|▍         | 187/4000 [01:41<30:57,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.330763816833496, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.029501914978027, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:   5%|▍         | 188/4000 [01:41<28:43,  2.21it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.623814582824707, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.247568130493164, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   5%|▍         | 189/4000 [01:44<1:19:18,  1.25s/it]

Data point 1: Actual Class: 1.0, Final Logit: 6.395407676696777, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.249253988265991, Predicted Probability: 0.0954, Prediction: 0.0

Epoch 3/3:   5%|▍         | 190/4000 [01:45<59:31,  1.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.630912780761719, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.865341186523438, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   5%|▍         | 191/4000 [01:45<56:41,  1.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.911677360534668, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.211881637573242, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   5%|▍         | 192/4000 [01:46<43:33,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.20980702340602875, Predicted Probability: 0.4477, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.03216552734375, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   5%|▍         | 193/4000 [01:46<34:21,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.984816551208496, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.073402404785156, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   5%|▍         | 194/4000 [01:47<38:12,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.09170913696289, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.197970390319824, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:   5%|▍         | 195/4000 [01:47<41:03,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6425139904022217, Predicted Probability: 0.0665, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.03229159116744995, Predicted Probability: 0.5081, Prediction: 1.0

Epoch 3/3:   5%|▍         | 196/4000 [01:48<32:38,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.755555629730225, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.493710994720459, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:   5%|▍         | 197/4000 [01:48<33:05,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3838741779327393, Predicted Probability: 0.0844, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.211803436279297, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:   5%|▍         | 198/4000 [01:49<37:23,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.004344940185547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.0840888023376465, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:   5%|▍         | 199/4000 [01:50<40:33,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.146864414215088, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.659742832183838, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 3/3:   5%|▌         | 200/4000 [01:50<42:17,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.648343563079834, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.958333969116211, Predicted Probability: 0.9507, Prediction: 1.0

Epoch 3/3:   5%|▌         | 201/4000 [01:51<36:51,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.556557655334473, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.978449821472168, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   5%|▌         | 202/4000 [01:51<34:03,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.819087028503418, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.38789963722229, Predicted Probability: 0.0327, Prediction: 0.0

Epoch 3/3:   5%|▌         | 203/4000 [01:51<27:44,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.658366203308105, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.330903053283691, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 3/3:   5%|▌         | 204/4000 [01:52<32:51,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.225191354751587, Predicted Probability: 0.9618, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.022676467895508, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   5%|▌         | 205/4000 [01:53<37:50,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.88856840133667, Predicted Probability: 0.9473, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.899572372436523, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   5%|▌         | 207/4000 [01:54<29:38,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.530549049377441, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.874444484710693, Predicted Probability: 0.9972, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -8.822423934936523, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.427513122558594, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   5%|▌         | 208/4000 [01:54<36:04,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.259693145751953, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.607591152191162, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 3/3:   5%|▌         | 209/4000 [01:55<39:00,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.776045799255371, Predicted Probability: 0.9414, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.276793479919434, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   5%|▌         | 210/4000 [01:56<42:26,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.528311729431152, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.824352264404297, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   5%|▌         | 211/4000 [01:57<43:46,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.352062225341797, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.194350719451904, Predicted Probability: 0.9851, Prediction: 1.0

Epoch 3/3:   5%|▌         | 212/4000 [01:57<44:21,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8209011554718018, Predicted Probability: 0.0562, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.143362045288086, Predicted Probability: 0.9844, Prediction: 1.0

Epoch 3/3:   5%|▌         | 213/4000 [01:58<41:36,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.189128875732422, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.398497104644775, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:   5%|▌         | 214/4000 [01:58<36:12,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.119865417480469, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.404378890991211, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   5%|▌         | 215/4000 [01:59<39:07,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.59491491317749, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.970410346984863, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   5%|▌         | 217/4000 [01:59<25:31,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.4726823568344116, Predicted Probability: 0.1865, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.95483684539795, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -7.402988433837891, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.308576583862305, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   5%|▌         | 218/4000 [02:00<31:48,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.854804039001465, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0413055419921875, Predicted Probability: 0.0456, Prediction: 0.0

Epoch 3/3:   5%|▌         | 219/4000 [02:01<37:17,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.390820026397705, Predicted Probability: 0.0839, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.607016563415527, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 3/3:   6%|▌         | 220/4000 [02:02<39:45,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6168880462646484, Predicted Probability: 0.6495, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.504678726196289, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   6%|▌         | 221/4000 [02:03<44:05,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.035791397094727, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.856677532196045, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:   6%|▌         | 222/4000 [02:03<45:18,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.5465669631958, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.069304943084717, Predicted Probability: 0.9556, Prediction: 1.0

Epoch 3/3:   6%|▌         | 223/4000 [02:04<35:38,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.955747127532959, Predicted Probability: 0.0495, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.675383567810059, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   6%|▌         | 224/4000 [02:04<41:38,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.913346290588379, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.664752960205078, Predicted Probability: 0.0093, Prediction: 0.0

Epoch 3/3:   6%|▌         | 226/4000 [02:05<28:58,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.694995880126953, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.024962425231934, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.186578750610352, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.786195755004883, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   6%|▌         | 227/4000 [02:06<30:23,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.322778701782227, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.061084032058716, Predicted Probability: 0.0447, Prediction: 0.0

Epoch 3/3:   6%|▌         | 228/4000 [02:06<28:48,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.061627388000488, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.317882537841797, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   6%|▌         | 229/4000 [02:07<34:07,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.716116189956665, Predicted Probability: 0.0238, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.418214797973633, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   6%|▌         | 230/4000 [02:08<39:09,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.510895729064941, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.007158279418945, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:   6%|▌         | 231/4000 [02:08<37:47,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.142370223999023, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.645691394805908, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 3/3:   6%|▌         | 232/4000 [02:08<33:30,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.727375984191895, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.219137191772461, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 3/3:   6%|▌         | 233/4000 [02:09<38:01,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.885892868041992, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8616862297058105, Predicted Probability: 0.0206, Prediction: 0.0

Epoch 3/3:   6%|▌         | 234/4000 [02:09<31:43,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.513521194458008, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.99529504776001, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   6%|▌         | 235/4000 [02:10<36:34,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.500431060791016, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2193503379821777, Predicted Probability: 0.0384, Prediction: 0.0

Epoch 3/3:   6%|▌         | 236/4000 [02:11<39:33,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.574404716491699, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.800917625427246, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 3/3:   6%|▌         | 237/4000 [02:12<42:11,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9042601585388184, Predicted Probability: 0.7118, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.273128032684326, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 3/3:   6%|▌         | 238/4000 [02:12<36:30,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.075089454650879, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.336867332458496, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   6%|▌         | 239/4000 [02:13<32:40,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.468024730682373, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.58362865447998, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   6%|▌         | 240/4000 [02:13<31:23,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.600586891174316, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.217998504638672, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   6%|▌         | 241/4000 [02:14<36:16,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.975183486938477, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.106585502624512, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   6%|▌         | 242/4000 [02:14<39:38,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3746602535247803, Predicted Probability: 0.9149, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.540060520172119, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   6%|▌         | 243/4000 [02:15<41:03,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8810198307037354, Predicted Probability: 0.9469, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6892402172088623, Predicted Probability: 0.0636, Prediction: 0.0

Epoch 3/3:   6%|▌         | 244/4000 [02:16<36:01,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.561245918273926, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.232172966003418, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   6%|▌         | 245/4000 [02:16<39:41,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.941126346588135, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.196134567260742, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 3/3:   6%|▌         | 246/4000 [02:17<42:00,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6585845947265625, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.054800033569336, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:   6%|▌         | 247/4000 [02:18<43:31,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.591793060302734, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.521599292755127, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 3/3:   6%|▌         | 248/4000 [02:19<46:06,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.097285270690918, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.84528923034668, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:   6%|▌         | 249/4000 [02:20<48:32,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.945746898651123, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.785741806030273, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   6%|▋         | 250/4000 [02:20<48:16,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.710846483707428, Predicted Probability: 0.6706, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.511332511901855, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   6%|▋         | 251/4000 [02:21<47:44,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.33177661895752, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0672457218170166, Predicted Probability: 0.9555, Prediction: 1.0

Epoch 3/3:   6%|▋         | 252/4000 [02:22<47:03,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.888399839401245, Predicted Probability: 0.9473, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.039413452148438, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   6%|▋         | 253/4000 [02:22<36:43,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.141098022460938, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.964406967163086, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   6%|▋         | 254/4000 [02:23<35:42,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.716615676879883, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.653046131134033, Predicted Probability: 0.9747, Prediction: 1.0

Epoch 3/3:   6%|▋         | 255/4000 [02:23<32:19,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.00829029083252, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.095892906188965, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   6%|▋         | 256/4000 [02:24<37:14,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.258297443389893, Predicted Probability: 0.0139, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.189182758331299, Predicted Probability: 0.1007, Prediction: 0.0

Epoch 3/3:   6%|▋         | 257/4000 [02:24<36:16,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.233342170715332, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.265535354614258, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   6%|▋         | 258/4000 [02:25<32:44,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.180644989013672, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.689208984375, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   6%|▋         | 259/4000 [02:25<36:56,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.724430799484253, Predicted Probability: 0.9385, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.984031677246094, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 3/3:   6%|▋         | 260/4000 [02:26<42:01,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.335845947265625, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.234919548034668, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   7%|▋         | 261/4000 [02:27<43:24,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.32208251953125, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.7057271003723145, Predicted Probability: 0.0090, Prediction: 0.0

Epoch 3/3:   7%|▋         | 262/4000 [02:27<38:55,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.673128128051758, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.881501197814941, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:   7%|▋         | 263/4000 [02:28<42:34,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.228656768798828, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.368352890014648, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   7%|▋         | 265/4000 [02:29<34:04,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.914630889892578, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7634694576263428, Predicted Probability: 0.9407, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.410294532775879, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.563362121582031, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   7%|▋         | 266/4000 [02:30<40:06,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.656444549560547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.281501770019531, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   7%|▋         | 267/4000 [02:31<38:08,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.636961460113525, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.376801490783691, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   7%|▋         | 268/4000 [02:31<40:46,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.55518913269043, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7435741424560547, Predicted Probability: 0.9395, Prediction: 1.0

Epoch 3/3:   7%|▋         | 269/4000 [02:32<42:34,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9780261516571045, Predicted Probability: 0.1215, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.813699960708618, Predicted Probability: 0.9434, Prediction: 1.0

Epoch 3/3:   7%|▋         | 270/4000 [02:32<33:37,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.477506637573242, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.3068515658378601, Predicted Probability: 0.4239, Prediction: 0.0

Epoch 3/3:   7%|▋         | 271/4000 [02:33<37:20,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.073363780975342, Predicted Probability: 0.9833, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.846646308898926, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   7%|▋         | 272/4000 [02:33<29:58,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.279068946838379, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.238615989685059, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:   7%|▋         | 273/4000 [02:34<29:07,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.531713485717773, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.312727451324463, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 3/3:   7%|▋         | 274/4000 [02:34<30:42,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3460512161254883, Predicted Probability: 0.0340, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.726081609725952, Predicted Probability: 0.9765, Prediction: 1.0

Epoch 3/3:   7%|▋         | 275/4000 [02:35<36:53,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.375505447387695, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.48892593383789, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   7%|▋         | 276/4000 [02:35<29:45,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.060691833496094, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.923710823059082, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.11836051940918, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.025976181030273, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   7%|▋         | 278/4000 [02:36<27:00,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.030466556549072, Predicted Probability: 0.9935, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.915030479431152, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   7%|▋         | 279/4000 [02:37<32:58,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.510147094726562, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.096278667449951, Predicted Probability: 0.1095, Prediction: 0.0

Epoch 3/3:   7%|▋         | 280/4000 [02:37<33:25,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.453917026519775, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.808009147644043, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   7%|▋         | 281/4000 [02:38<30:36,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.766274452209473, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.800853252410889, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:   7%|▋         | 282/4000 [02:38<35:04,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.965829610824585, Predicted Probability: 0.8772, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.695601463317871, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   7%|▋         | 283/4000 [02:39<38:24,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.533207654953003, Predicted Probability: 0.9264, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.889381408691406, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 3/3:   7%|▋         | 284/4000 [02:40<36:53,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.875764846801758, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9438629150390625, Predicted Probability: 0.9810, Prediction: 1.0

Epoch 3/3:   7%|▋         | 285/4000 [02:40<39:07,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.285873413085938, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.751502275466919, Predicted Probability: 0.9400, Prediction: 1.0

Epoch 3/3:   7%|▋         | 286/4000 [02:41<34:14,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.704643249511719, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.276844024658203, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:   7%|▋         | 287/4000 [02:41<35:27,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.387190818786621, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.925485372543335, Predicted Probability: 0.7162, Prediction: 1.0

Epoch 3/3:   7%|▋         | 288/4000 [02:42<35:04,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.33014440536499, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.506748676300049, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:   7%|▋         | 289/4000 [02:43<38:16,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.301307678222656, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.170858144760132, Predicted Probability: 0.1024, Prediction: 0.0

Epoch 3/3:   7%|▋         | 291/4000 [02:44<31:47,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.449199676513672, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8411331176757812, Predicted Probability: 0.1369, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.824223518371582, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.366375923156738, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   7%|▋         | 292/4000 [02:45<43:54,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.095197677612305, Predicted Probability: 0.9836, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.546831130981445, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   7%|▋         | 293/4000 [02:45<37:56,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.83786678314209, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.710677146911621, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   7%|▋         | 294/4000 [02:46<40:02,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.156717300415039, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.522578477859497, Predicted Probability: 0.9257, Prediction: 1.0

Epoch 3/3:   7%|▋         | 295/4000 [02:47<41:20,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.779974937438965, Predicted Probability: 0.9416, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.430864334106445, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   7%|▋         | 296/4000 [02:47<42:50,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.483232498168945, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.108041286468506, Predicted Probability: 0.1083, Prediction: 0.0

Epoch 3/3:   7%|▋         | 297/4000 [02:48<37:05,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.593742370605469, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.75117301940918, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   7%|▋         | 298/4000 [02:48<36:29,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.6477837562561035, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6848469376564026, Predicted Probability: 0.6648, Prediction: 1.0

Epoch 3/3:   7%|▋         | 299/4000 [02:49<39:46,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6404017210006714, Predicted Probability: 0.1624, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.1942720413208, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 300/4000 [02:50<34:49,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.005630493164062, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -3.211134672164917, Predicted Probability: 0.0387, Prediction: 0.0

Epoch 3/3:   8%|▊         | 301/4000 [02:50<39:14,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.713636875152588, Predicted Probability: 0.9762, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.53183364868164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 302/4000 [02:51<40:47,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.612673282623291, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.966176748275757, Predicted Probability: 0.9510, Prediction: 1.0

Epoch 3/3:   8%|▊         | 303/4000 [02:52<42:17,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5713744163513184, Predicted Probability: 0.9290, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.641284942626953, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 304/4000 [02:53<44:53,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.723690032958984, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.430807113647461, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 305/4000 [02:53<35:09,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.245724678039551, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.630563735961914, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   8%|▊         | 306/4000 [02:53<31:17,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.676517486572266, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.152886867523193, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:   8%|▊         | 307/4000 [02:54<28:50,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.971896648406982, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.6875638961792, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   8%|▊         | 308/4000 [02:54<34:10,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3937240839004517, Predicted Probability: 0.1988, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.514869689941406, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   8%|▊         | 309/4000 [02:55<38:11,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.518897533416748, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8984745740890503, Predicted Probability: 0.1303, Prediction: 0.0

Epoch 3/3:   8%|▊         | 310/4000 [02:56<42:00,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.040816307067871, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.934931755065918, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 311/4000 [02:57<43:45,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.57433795928955, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.843108177185059, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 312/4000 [02:57<37:35,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5851898193359375, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.881932258605957, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   8%|▊         | 313/4000 [02:57<33:03,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.558069229125977, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.196312427520752, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:   8%|▊         | 314/4000 [02:58<40:48,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.392923355102539, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.50948429107666, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   8%|▊         | 315/4000 [02:59<32:18,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.094229698181152, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.190262794494629, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   8%|▊         | 316/4000 [02:59<36:05,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.977913856506348, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7645487785339355, Predicted Probability: 0.9407, Prediction: 1.0

Epoch 3/3:   8%|▊         | 317/4000 [03:00<33:21,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.467103481292725, Predicted Probability: 0.0114, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.832283973693848, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:   8%|▊         | 318/4000 [03:00<27:09,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.080087661743164, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.411858558654785, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   8%|▊         | 319/4000 [03:01<33:00,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.940444946289062, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.544369220733643, Predicted Probability: 0.9895, Prediction: 1.0

Epoch 3/3:   8%|▊         | 320/4000 [03:01<36:39,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.746945858001709, Predicted Probability: 0.9397, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.473417282104492, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 321/4000 [03:02<32:31,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.10096263885498, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.615208625793457, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   8%|▊         | 322/4000 [03:03<36:39,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.891166687011719, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.974618434906006, Predicted Probability: 0.9514, Prediction: 1.0

Epoch 3/3:   8%|▊         | 323/4000 [03:03<32:34,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.930532455444336, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5645341873168945, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:   8%|▊         | 324/4000 [03:04<38:01,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.637332916259766, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.219333171844482, Predicted Probability: 0.9855, Prediction: 1.0

Epoch 3/3:   8%|▊         | 325/4000 [03:04<36:36,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4878242015838623, Predicted Probability: 0.0297, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1700968742370605, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:   8%|▊         | 326/4000 [03:05<38:47,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.924799680709839, Predicted Probability: 0.9491, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.190572261810303, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:   8%|▊         | 327/4000 [03:06<40:49,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9426507949829102, Predicted Probability: 0.1254, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.172086715698242, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 328/4000 [03:06<35:22,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.175350189208984, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.630315780639648, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:   8%|▊         | 329/4000 [03:07<31:47,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.22927474975586, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.936788558959961, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   8%|▊         | 330/4000 [03:07<27:10,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.435047149658203, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.179186820983887, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   8%|▊         | 332/4000 [03:08<24:42,  2.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.3238301277160645, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.614001750946045, Predicted Probability: 0.9738, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -8.097408294677734, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.458269119262695, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   8%|▊         | 333/4000 [03:08<24:12,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.96479320526123, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.536827564239502, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:   8%|▊         | 334/4000 [03:09<30:16,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.899999618530273, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5979728698730469, Predicted Probability: 0.1683, Prediction: 0.0

Epoch 3/3:   8%|▊         | 335/4000 [03:09<28:00,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.676855087280273, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.753538131713867, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   8%|▊         | 336/4000 [03:10<26:28,  2.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.609703063964844, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.149866580963135, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:   8%|▊         | 337/4000 [03:10<32:39,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.622756004333496, Predicted Probability: 0.0097, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.496650695800781, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   8%|▊         | 338/4000 [03:11<36:35,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.684259414672852, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8047705888748169, Predicted Probability: 0.6910, Prediction: 1.0

Epoch 3/3:   8%|▊         | 339/4000 [03:12<41:45,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.468589782714844, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.921816825866699, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:   8%|▊         | 340/4000 [03:13<43:21,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.6414031982421875, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.429543495178223, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   9%|▊         | 341/4000 [03:13<43:43,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.469720721244812, Predicted Probability: 0.1870, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.94450569152832, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:   9%|▊         | 342/4000 [03:14<43:54,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8413209915161133, Predicted Probability: 0.9449, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.234258651733398, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   9%|▊         | 343/4000 [03:15<37:31,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.88564682006836, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.371698379516602, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   9%|▊         | 344/4000 [03:15<36:06,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.600318908691406, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.365058898925781, Predicted Probability: 0.9874, Prediction: 1.0

Epoch 3/3:   9%|▊         | 345/4000 [03:16<39:27,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.936740875244141, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.284299612045288, Predicted Probability: 0.9076, Prediction: 1.0

Epoch 3/3:   9%|▊         | 346/4000 [03:16<31:18,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.495230197906494, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.971797943115234, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   9%|▊         | 347/4000 [03:16<25:44,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.617390632629395, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.027763843536377, Predicted Probability: 0.9538, Prediction: 1.0

Epoch 3/3:   9%|▊         | 348/4000 [03:17<32:48,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.373096942901611, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.41904354095459, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   9%|▊         | 349/4000 [03:17<26:38,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.289783477783203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.238191604614258, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   9%|▉         | 350/4000 [03:18<32:03,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.885854482650757, Predicted Probability: 0.0201, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.984519958496094, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:   9%|▉         | 351/4000 [03:18<29:25,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.74760913848877, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.479722023010254, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   9%|▉         | 352/4000 [03:19<28:49,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.928765296936035, Predicted Probability: 0.9807, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.33056640625, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   9%|▉         | 353/4000 [03:20<34:23,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.614814758300781, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.457327842712402, Predicted Probability: 0.9885, Prediction: 1.0

Epoch 3/3:   9%|▉         | 354/4000 [03:20<31:06,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.343470573425293, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.973396301269531, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:   9%|▉         | 355/4000 [03:20<28:38,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4507744312286377, Predicted Probability: 0.9206, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.000445365905762, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:   9%|▉         | 356/4000 [03:21<33:09,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.701657772064209, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.134291648864746, Predicted Probability: 0.9583, Prediction: 1.0

Epoch 3/3:   9%|▉         | 357/4000 [03:22<31:21,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2941646575927734, Predicted Probability: 0.7849, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.760222911834717, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:   9%|▉         | 358/4000 [03:22<28:40,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.09251594543457, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.165778636932373, Predicted Probability: 0.0153, Prediction: 0.0

Epoch 3/3:   9%|▉         | 359/4000 [03:23<33:09,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.857694625854492, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9078327417373657, Predicted Probability: 0.1292, Prediction: 0.0

Epoch 3/3:   9%|▉         | 360/4000 [03:23<30:13,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.259132385253906, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.37077522277832, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:   9%|▉         | 361/4000 [03:24<35:24,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3194379806518555, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.862706661224365, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:   9%|▉         | 362/4000 [03:25<45:31,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.681244373321533, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8159403800964355, Predicted Probability: 0.9435, Prediction: 1.0

Epoch 3/3:   9%|▉         | 363/4000 [03:26<45:05,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6443188190460205, Predicted Probability: 0.9337, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.756709098815918, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   9%|▉         | 364/4000 [03:26<38:12,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.226426601409912, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.267377853393555, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:   9%|▉         | 365/4000 [03:27<40:44,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.349872589111328, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.231513977050781, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   9%|▉         | 366/4000 [03:28<41:49,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.918792247772217, Predicted Probability: 0.9488, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.813528060913086, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:   9%|▉         | 367/4000 [03:28<39:18,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.260512828826904, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.257974624633789, Predicted Probability: 0.9860, Prediction: 1.0

Epoch 3/3:   9%|▉         | 368/4000 [03:29<41:40,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.288841247558594, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.778416633605957, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:   9%|▉         | 369/4000 [03:30<44:15,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2058058977127075, Predicted Probability: 0.7696, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.992875099182129, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:   9%|▉         | 370/4000 [03:30<38:13,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.094491958618164, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.915975093841553, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:   9%|▉         | 371/4000 [03:31<40:21,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.167417526245117, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.522800922393799, Predicted Probability: 0.0107, Prediction: 0.0

Epoch 3/3:   9%|▉         | 372/4000 [03:32<43:13,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.068817138671875, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5083823204040527, Predicted Probability: 0.9709, Prediction: 1.0

Epoch 3/3:   9%|▉         | 373/4000 [03:32<43:40,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.447084426879883, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.71724796295166, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 3/3:   9%|▉         | 374/4000 [03:33<37:17,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.753207683563232, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.819242477416992, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:   9%|▉         | 375/4000 [03:33<32:58,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.563209056854248, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.636111259460449, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 3/3:   9%|▉         | 376/4000 [03:34<36:09,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.254175186157227, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2457387447357178, Predicted Probability: 0.9625, Prediction: 1.0

Epoch 3/3:   9%|▉         | 377/4000 [03:34<31:50,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5369964838027954, Predicted Probability: 0.8230, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.889894485473633, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:   9%|▉         | 378/4000 [03:35<37:54,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.865875244140625, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.407395362854004, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -7.722448348999023, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.284280776977539, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  10%|▉         | 380/4000 [03:36<27:51,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.178600311279297, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.441372871398926, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 3/3:  10%|▉         | 381/4000 [03:36<32:32,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.41504430770874, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.591243743896484, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  10%|▉         | 383/4000 [03:37<28:44,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.077905654907227, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.673707962036133, Predicted Probability: 0.0034, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.996201515197754, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.099943161010742, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  10%|▉         | 384/4000 [03:38<26:48,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9990289211273193, Predicted Probability: 0.9525, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.194847106933594, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  10%|▉         | 385/4000 [03:38<29:00,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.8007588386535645, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7316552400588989, Predicted Probability: 0.3248, Prediction: 0.0

Epoch 3/3:  10%|▉         | 386/4000 [03:39<34:05,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.941361904144287, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.670577049255371, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  10%|▉         | 387/4000 [03:40<37:58,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.884321689605713, Predicted Probability: 0.9799, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.55455493927002, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|▉         | 388/4000 [03:41<41:33,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.141098022460938, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.620223999023438, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|▉         | 389/4000 [03:41<39:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.35141658782959, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.76310920715332, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|▉         | 390/4000 [03:41<31:12,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.324384689331055, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.409687042236328, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  10%|▉         | 391/4000 [03:42<31:40,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.781865119934082, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.184720993041992, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  10%|▉         | 392/4000 [03:42<25:50,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.3849515914917, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.442176818847656, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  10%|▉         | 393/4000 [03:42<21:45,  2.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1206914186477661, Predicted Probability: 0.2459, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.495796203613281, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|▉         | 394/4000 [03:43<21:47,  2.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.86032772064209, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.243409633636475, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 3/3:  10%|▉         | 395/4000 [03:43<21:56,  2.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.65270471572876, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.956828117370605, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  10%|▉         | 396/4000 [03:44<28:45,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.188613891601562, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5472283363342285, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:  10%|▉         | 397/4000 [03:45<32:50,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7405216693878174, Predicted Probability: 0.9768, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.400986194610596, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  10%|▉         | 398/4000 [03:45<29:38,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.030611991882324, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.46966552734375, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  10%|▉         | 399/4000 [03:46<35:36,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.003463745117188, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.274677038192749, Predicted Probability: 0.0932, Prediction: 0.0

Epoch 3/3:  10%|█         | 400/4000 [03:46<38:27,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.842055082321167, Predicted Probability: 0.0210, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.552230834960938, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|█         | 401/4000 [03:47<39:58,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.105189085006714, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.68269157409668, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|█         | 402/4000 [03:48<34:31,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9358601570129395, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5733364820480347, Predicted Probability: 0.1717, Prediction: 0.0

Epoch 3/3:  10%|█         | 403/4000 [03:48<38:03,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.840597152709961, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.118574142456055, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  10%|█         | 404/4000 [03:49<30:16,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.038737297058105, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.816725730895996, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  10%|█         | 405/4000 [03:49<36:01,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.723602294921875, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.267810344696045, Predicted Probability: 0.0138, Prediction: 0.0

Epoch 3/3:  10%|█         | 406/4000 [03:50<35:29,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6357202529907227, Predicted Probability: 0.1630, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.66051959991455, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  10%|█         | 407/4000 [03:51<38:54,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.855391502380371, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.391892433166504, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  10%|█         | 408/4000 [03:51<36:51,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.237849235534668, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.300541400909424, Predicted Probability: 0.9644, Prediction: 1.0

Epoch 3/3:  10%|█         | 409/4000 [03:52<40:17,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.481240272521973, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.616562843322754, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 3/3:  10%|█         | 410/4000 [03:52<34:47,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.40984058380127, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.663638114929199, Predicted Probability: 0.9907, Prediction: 1.0

Epoch 3/3:  10%|█         | 411/4000 [03:53<33:59,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.222752571105957, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.237199306488037, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 3/3:  10%|█         | 412/4000 [03:54<37:28,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.281441688537598, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.93342399597168, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  10%|█         | 413/4000 [03:55<40:41,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.100892066955566, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.369873523712158, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:  10%|█         | 414/4000 [03:55<41:41,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.480278491973877, Predicted Probability: 0.0112, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.903926849365234, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 3/3:  10%|█         | 415/4000 [03:56<35:56,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.248309135437012, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.37989616394043, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  10%|█         | 416/4000 [03:56<31:36,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.726208209991455, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.70175313949585, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  10%|█         | 417/4000 [03:56<28:43,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.943869590759277, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1809468269348145, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 3/3:  10%|█         | 418/4000 [03:57<29:33,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.575310468673706, Predicted Probability: 0.9728, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.284143447875977, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  10%|█         | 419/4000 [03:57<27:45,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.468310356140137, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.06501293182373, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  10%|█         | 420/4000 [03:58<26:09,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.948694229125977, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.972370624542236, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  11%|█         | 421/4000 [03:58<31:16,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.897024154663086, Predicted Probability: 0.0199, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.061272621154785, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  11%|█         | 422/4000 [03:59<28:41,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.846175670623779, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.189265251159668, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  11%|█         | 423/4000 [03:59<29:55,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.882600784301758, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.738405704498291, Predicted Probability: 0.0607, Prediction: 0.0

Epoch 3/3:  11%|█         | 424/4000 [04:00<27:36,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.8583984375, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.114676475524902, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  11%|█         | 425/4000 [04:00<26:04,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.818371772766113, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.449332237243652, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  11%|█         | 426/4000 [04:00<21:55,  2.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.358790397644043, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.0976786613464355, Predicted Probability: 0.2502, Prediction: 0.0

Epoch 3/3:  11%|█         | 427/4000 [04:01<29:57,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.448282241821289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.771585464477539, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  11%|█         | 428/4000 [04:02<35:25,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.583958148956299, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.650031089782715, Predicted Probability: 0.0253, Prediction: 0.0

Epoch 3/3:  11%|█         | 429/4000 [04:03<37:59,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6722493171691895, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.423221111297607, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 3/3:  11%|█         | 430/4000 [04:03<33:02,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.608456134796143, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.38873291015625, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  11%|█         | 431/4000 [04:04<37:14,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.390674591064453, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9744973182678223, Predicted Probability: 0.7260, Prediction: 1.0

Epoch 3/3:  11%|█         | 432/4000 [04:04<33:56,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.801694393157959, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.473613739013672, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  11%|█         | 433/4000 [04:05<30:20,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.810297012329102, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.480567932128906, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  11%|█         | 435/4000 [04:06<27:44,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.536173820495605, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.865354537963867, Predicted Probability: 0.9990, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.009272575378418, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.834482192993164, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  11%|█         | 436/4000 [04:06<32:20,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.49979019165039, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.48132187128067017, Predicted Probability: 0.3819, Prediction: 0.0

Epoch 3/3:  11%|█         | 437/4000 [04:07<32:17,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.031439781188965, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.50883150100708, Predicted Probability: 0.1811, Prediction: 0.0

Epoch 3/3:  11%|█         | 438/4000 [04:07<32:14,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.055161476135254, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.487248420715332, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 3/3:  11%|█         | 439/4000 [04:08<36:35,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.027137756347656, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.91077995300293, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  11%|█         | 440/4000 [04:09<32:13,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.84188175201416, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.7645039558410645, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 3/3:  11%|█         | 441/4000 [04:09<29:15,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.927653789520264, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.944729804992676, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  11%|█         | 443/4000 [04:10<27:08,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.621346473693848, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7640419006347656, Predicted Probability: 0.0593, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -9.630382537841797, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.354778528213501, Predicted Probability: 0.0337, Prediction: 0.0

Epoch 3/3:  11%|█         | 444/4000 [04:11<32:52,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.648584365844727, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.338438987731934, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  11%|█         | 445/4000 [04:11<32:30,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.214672565460205, Predicted Probability: 0.9854, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.899836540222168, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  11%|█         | 446/4000 [04:12<30:52,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.620643615722656, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.395450592041016, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  11%|█         | 447/4000 [04:12<26:23,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.837425947189331, Predicted Probability: 0.1374, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.230712890625, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  11%|█         | 448/4000 [04:12<22:07,  2.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.441607475280762, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.489895820617676, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  11%|█         | 449/4000 [04:13<29:03,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.734260082244873, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.011863708496094, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  11%|█▏        | 450/4000 [04:13<28:05,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9452954530715942, Predicted Probability: 0.1251, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.033750534057617, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 451/4000 [04:14<27:25,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.039823532104492, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.135368347167969, Predicted Probability: 0.9941, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 452/4000 [04:14<26:14,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.533842086791992, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.024703979492188, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 453/4000 [04:15<32:36,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.36603307723999, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.618252754211426, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 3/3:  11%|█▏        | 454/4000 [04:16<32:32,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.422249794006348, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.339962959289551, Predicted Probability: 0.9871, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 455/4000 [04:16<36:47,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.95182991027832, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.8847527503967285, Predicted Probability: 0.9925, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 456/4000 [04:17<32:20,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.509099960327148, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.823616981506348, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 457/4000 [04:17<30:41,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.120402336120605, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.999666690826416, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  11%|█▏        | 458/4000 [04:18<34:40,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.350399017333984, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2972183227539062, Predicted Probability: 0.9643, Prediction: 1.0

Epoch 3/3:  11%|█▏        | 459/4000 [04:19<36:42,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.815016746520996, Predicted Probability: 0.9784, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.473775863647461, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 460/4000 [04:19<33:31,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.079703330993652, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6975226402282715, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 461/4000 [04:19<30:05,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.245683670043945, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.619520664215088, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 462/4000 [04:20<27:34,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.486035346984863, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.024683952331543, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 463/4000 [04:21<33:51,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.150919914245605, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.63198471069336, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 464/4000 [04:21<30:24,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.486053943634033, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.259716987609863, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 465/4000 [04:21<28:11,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.493734359741211, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.010639190673828, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 466/4000 [04:22<26:19,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.7037241458892822, Predicted Probability: 0.9760, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.17043399810791, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 467/4000 [04:22<28:17,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.610153198242188, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.27195098996162415, Predicted Probability: 0.5676, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 468/4000 [04:22<23:21,  2.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.796605110168457, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.73290729522705, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 469/4000 [04:23<29:31,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.956610202789307, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5928053855896, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 470/4000 [04:24<35:04,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.7386474609375, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.296581268310547, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 471/4000 [04:24<28:27,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.556721687316895, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6158599853515625, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 472/4000 [04:25<32:36,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0963833332061768, Predicted Probability: 0.8906, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.602699279785156, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 473/4000 [04:26<32:36,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.043435573577881, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.513795375823975, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 474/4000 [04:26<29:28,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.921013355255127, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6768975257873535, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 475/4000 [04:26<30:14,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.404698371887207, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8762848377227783, Predicted Probability: 0.9797, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 476/4000 [04:27<34:36,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.504298686981201, Predicted Probability: 0.0292, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.173091888427734, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 477/4000 [04:28<30:53,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.700150489807129, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.148374557495117, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 478/4000 [04:28<31:01,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.870543956756592, Predicted Probability: 0.9796, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.441356658935547, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 479/4000 [04:29<28:15,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.718298435211182, Predicted Probability: 0.0033, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.908896446228027, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 480/4000 [04:29<26:21,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.141518592834473, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.174980640411377, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 481/4000 [04:30<31:42,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.346199035644531, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.863189697265625, Predicted Probability: 0.2967, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 482/4000 [04:30<25:53,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.64414119720459, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.163915634155273, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 483/4000 [04:30<24:43,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.7751264572143555, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.146112442016602, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 484/4000 [04:31<24:12,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.468966484069824, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.330461502075195, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 485/4000 [04:31<30:09,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0493531227111816, Predicted Probability: 0.1141, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.52309799194336, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 486/4000 [04:32<30:32,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.257017135620117, Predicted Probability: 0.9629, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.320292949676514, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 487/4000 [04:32<28:07,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3948627710342407, Predicted Probability: 0.1986, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.643735885620117, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 488/4000 [04:33<33:08,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.721662521362305, Predicted Probability: 0.9912, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.2907867431640625, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 489/4000 [04:33<29:52,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.685250759124756, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.263277053833008, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 490/4000 [04:34<30:56,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.688922882080078, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.706485748291016, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 491/4000 [04:34<29:45,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.611342906951904, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.406553745269775, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 492/4000 [04:35<33:52,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.729673385620117, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.390904188156128, Predicted Probability: 0.0326, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 493/4000 [04:36<30:19,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.457273006439209, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.896990776062012, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 494/4000 [04:36<27:54,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.605480670928955, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.882923126220703, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  12%|█▏        | 495/4000 [04:37<33:58,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.2697343826293945, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.956703186035156, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 496/4000 [04:37<33:22,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.897233009338379, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.843978881835938, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 497/4000 [04:38<38:13,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.053034782409668, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.949036121368408, Predicted Probability: 0.0026, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 498/4000 [04:39<40:02,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.577014923095703, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0682523250579834, Predicted Probability: 0.1122, Prediction: 0.0

Epoch 3/3:  12%|█▏        | 499/4000 [04:40<39:32,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3630166053771973, Predicted Probability: 0.7962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.933765888214111, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  12%|█▎        | 500/4000 [04:40<42:29,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.716758728027344, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.373899459838867, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 501/4000 [04:41<33:40,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.746068000793457, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.122183799743652, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 502/4000 [04:41<27:21,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.529095649719238, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.295246124267578, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 503/4000 [04:41<28:48,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.71728801727295, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.669389724731445, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 504/4000 [04:42<33:56,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.58599853515625, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1817004680633545, Predicted Probability: 0.9601, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 505/4000 [04:43<37:25,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1067581176757812, Predicted Probability: 0.9572, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.98645544052124, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 506/4000 [04:43<32:35,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.86341667175293, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.940510272979736, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 507/4000 [04:44<29:24,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.016377449035645, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.01832389831543, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 508/4000 [04:44<27:20,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.1797099113464355, Predicted Probability: 0.0056, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.818838596343994, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 509/4000 [04:45<33:06,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.359132289886475, Predicted Probability: 0.9874, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.585761070251465, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 510/4000 [04:46<36:31,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8352878093719482, Predicted Probability: 0.9446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.88943862915039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 511/4000 [04:46<38:34,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.695392608642578, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.668426513671875, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 512/4000 [04:47<39:46,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.851083755493164, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4174842834472656, Predicted Probability: 0.0318, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 513/4000 [04:48<41:55,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8588274717330933, Predicted Probability: 0.1348, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.124589920043945, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 514/4000 [04:49<43:11,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.727602005004883, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.104170799255371, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 515/4000 [04:50<42:51,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.1452717781066895, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.336361885070801, Predicted Probability: 0.0129, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 516/4000 [04:50<44:10,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.023417949676514, Predicted Probability: 0.0024, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.519441604614258, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 517/4000 [04:51<44:05,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.851766586303711, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7720947265625, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 518/4000 [04:52<38:34,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.496953964233398, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.548060417175293, Predicted Probability: 0.9895, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 520/4000 [04:53<31:50,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.482232093811035, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.288335800170898, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.682796478271484, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.585590362548828, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 521/4000 [04:53<34:48,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0261576175689697, Predicted Probability: 0.9537, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.476901054382324, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 522/4000 [04:54<37:45,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.998567581176758, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.962367534637451, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 523/4000 [04:55<39:32,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3097734451293945, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.59744644165039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 524/4000 [04:55<34:19,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.334792137145996, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.342313289642334, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 525/4000 [04:56<34:27,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3469040393829346, Predicted Probability: 0.0873, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.611517906188965, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 526/4000 [04:56<30:36,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.394807815551758, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.755707263946533, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 527/4000 [04:57<28:21,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.72041130065918, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.060002326965332, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 528/4000 [04:57<32:25,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.923917531967163, Predicted Probability: 0.9490, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.633413314819336, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 529/4000 [04:58<29:13,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.167332172393799, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.617685317993164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 530/4000 [04:58<32:39,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8370954990386963, Predicted Probability: 0.9446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.470169067382812, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 531/4000 [04:59<36:28,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.656144618988037, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.010046005249023, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 532/4000 [05:00<39:05,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.120151519775391, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.902171611785889, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 533/4000 [05:00<33:39,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.104773044586182, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.295384407043457, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 534/4000 [05:01<30:21,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.824875831604004, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.777270317077637, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 535/4000 [05:01<34:10,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.590806007385254, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.9226508140563965, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 536/4000 [05:02<36:51,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.69967269897461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.571888446807861, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 537/4000 [05:03<36:42,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.915731430053711, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.324963092803955, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  13%|█▎        | 538/4000 [05:03<29:11,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.115880966186523, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.819693565368652, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  13%|█▎        | 539/4000 [05:04<33:18,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.151124954223633, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.096374273300171, Predicted Probability: 0.9567, Prediction: 1.0

Epoch 3/3:  14%|█▎        | 540/4000 [05:04<32:53,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.406548500061035, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.548008918762207, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  14%|█▎        | 541/4000 [05:05<35:28,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7704466581344604, Predicted Probability: 0.8545, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.11601448059082, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  14%|█▎        | 542/4000 [05:05<32:16,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.742125511169434, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2122883796691895, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 3/3:  14%|█▎        | 543/4000 [05:06<32:18,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.096273422241211, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.929727554321289, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  14%|█▎        | 544/4000 [05:07<37:13,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.835784912109375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.288849830627441, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  14%|█▎        | 545/4000 [05:08<38:56,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.096059799194336, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.075713157653809, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.425140380859375, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.41262435913086, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  14%|█▎        | 547/4000 [05:09<34:31,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.808981418609619, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.472823143005371, Predicted Probability: 0.0778, Prediction: 0.0

Epoch 3/3:  14%|█▎        | 548/4000 [05:09<30:47,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.330872535705566, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.033981323242188, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  14%|█▎        | 549/4000 [05:09<29:05,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.428808212280273, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5821938514709473, Predicted Probability: 0.0703, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 550/4000 [05:10<26:39,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.342211723327637, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.847444534301758, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 551/4000 [05:11<33:32,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.924558639526367, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.845172882080078, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 552/4000 [05:11<29:56,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.648637771606445, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.686303615570068, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 553/4000 [05:12<30:28,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.698498249053955, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.80542278289795, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 554/4000 [05:12<24:57,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.089871406555176, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.87623929977417, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 555/4000 [05:12<26:33,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.814662456512451, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.27767276763916016, Predicted Probability: 0.4310, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 556/4000 [05:13<25:06,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.652406692504883, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.129670143127441, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 557/4000 [05:13<24:01,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.038921356201172, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.413120269775391, Predicted Probability: 0.9880, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 558/4000 [05:13<23:27,  2.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.378486633300781, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.521209716796875, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 559/4000 [05:14<19:59,  2.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.129729270935059, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.418793678283691, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 560/4000 [05:14<27:05,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.398138999938965, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.869816303253174, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 561/4000 [05:15<31:48,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.0934343338012695, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9177629947662354, Predicted Probability: 0.9487, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 562/4000 [05:16<35:25,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.341386795043945, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7082675695419312, Predicted Probability: 0.8466, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 563/4000 [05:17<38:41,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.610588073730469, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.795345306396484, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 564/4000 [05:17<39:58,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6478731632232666, Predicted Probability: 0.0254, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.031578540802002, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 565/4000 [05:18<41:06,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.656968116760254, Predicted Probability: 0.1602, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.656928062438965, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 566/4000 [05:19<35:03,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.431249141693115, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.921459197998047, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 567/4000 [05:19<31:11,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.267752647399902, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6819000244140625, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 568/4000 [05:20<34:53,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.644659042358398, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.341413497924805, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 569/4000 [05:20<37:14,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.718653678894043, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.401991844177246, Predicted Probability: 0.9879, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 570/4000 [05:21<40:23,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.605595588684082, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.484877586364746, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 571/4000 [05:22<37:53,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.752364635467529, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4435410499572754, Predicted Probability: 0.0799, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 572/4000 [05:23<39:37,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.8980488181114197, Predicted Probability: 0.2895, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.837906360626221, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 573/4000 [05:23<37:19,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.837433815002441, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.11572790145874, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 574/4000 [05:24<39:04,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.32684326171875, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.114033222198486, Predicted Probability: 0.9839, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 575/4000 [05:24<33:31,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.7823896408081055, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.894853591918945, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 576/4000 [05:25<35:37,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.492722511291504, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.072287082672119, Predicted Probability: 0.9557, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 577/4000 [05:26<37:38,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.991745948791504, Predicted Probability: 0.9522, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.662197113037109, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 3/3:  14%|█▍        | 578/4000 [05:26<30:59,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.780038833618164, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.516857147216797, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 579/4000 [05:27<35:20,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.602720260620117, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1565351486206055, Predicted Probability: 0.9592, Prediction: 1.0

Epoch 3/3:  14%|█▍        | 580/4000 [05:28<37:30,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6966493129730225, Predicted Probability: 0.9758, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.046285629272461, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 581/4000 [05:28<35:23,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.111907005310059, Predicted Probability: 0.0161, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.795042991638184, Predicted Probability: 0.9918, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 582/4000 [05:29<31:14,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.533997535705566, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.646636009216309, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 583/4000 [05:29<36:03,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.389971733093262, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.673810958862305, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 584/4000 [05:30<31:45,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.246368885040283, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.205894470214844, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 586/4000 [05:31<29:06,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.842099189758301, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.994518280029297, Predicted Probability: 0.0025, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -9.689798355102539, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.60837173461914, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 587/4000 [05:31<32:45,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.350972175598145, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7779455184936523, Predicted Probability: 0.9415, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 588/4000 [05:32<35:44,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9937357902526855, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3197455406188965, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 589/4000 [05:33<37:48,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.104135513305664, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5064215660095215, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 590/4000 [05:33<33:05,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.741904258728027, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.600409507751465, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 591/4000 [05:34<36:15,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.034530639648438, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.21470832824707, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 592/4000 [05:34<28:53,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.624835014343262, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.317511558532715, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 593/4000 [05:35<26:22,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.20095682144165, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.056973457336426, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 594/4000 [05:35<31:39,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.531988143920898, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.644230842590332, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 595/4000 [05:36<28:30,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.330669403076172, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.384478569030762, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 596/4000 [05:36<26:04,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.688074588775635, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.568516731262207, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 597/4000 [05:37<24:27,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.854151248931885, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.74897575378418, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  15%|█▍        | 598/4000 [05:37<29:30,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0285744667053223, Predicted Probability: 0.2634, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.863571643829346, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  15%|█▍        | 599/4000 [05:38<34:07,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.09595251083374023, Predicted Probability: 0.4760, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3399224281311035, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 600/4000 [05:39<36:57,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.103292465209961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6733803749084473, Predicted Probability: 0.9354, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 601/4000 [05:39<35:15,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.131299018859863, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0986647605896, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 602/4000 [05:40<30:58,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.365713596343994, Predicted Probability: 0.0125, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.7338931560516357, Predicted Probability: 0.9390, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 603/4000 [05:40<29:17,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.735628128051758, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.9782257080078125, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 604/4000 [05:41<33:30,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.753022193908691, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.635094165802002, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 605/4000 [05:41<31:05,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.136857032775879, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.679443359375, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 606/4000 [05:42<25:22,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.415474891662598, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.809309005737305, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 607/4000 [05:42<30:33,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.774569511413574, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.215160846710205, Predicted Probability: 0.9854, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 608/4000 [05:43<33:42,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.665445327758789, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3134231567382812, Predicted Probability: 0.7881, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 609/4000 [05:44<30:00,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1621387004852295, Predicted Probability: 0.8968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.485407829284668, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 610/4000 [05:44<33:45,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8226666450500488, Predicted Probability: 0.8609, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.524312973022461, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 611/4000 [05:45<36:31,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.643296003341675, Predicted Probability: 0.9336, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.662205219268799, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 612/4000 [05:45<29:00,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.316986083984375, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.631523609161377, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 613/4000 [05:45<23:49,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.30976390838623, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.138394355773926, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 614/4000 [05:46<29:21,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3394365310668945, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.57119369506836, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 615/4000 [05:47<26:38,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2752108573913574, Predicted Probability: 0.9068, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.416597366333008, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 616/4000 [05:47<32:36,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.502134323120117, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7626238465309143, Predicted Probability: 0.3181, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 617/4000 [05:48<32:26,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.403031349182129, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6363749504089355, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 3/3:  15%|█▌        | 618/4000 [05:49<35:54,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.920126914978027, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.423567295074463, Predicted Probability: 0.9882, Prediction: 1.0

Epoch 3/3:  15%|█▌        | 619/4000 [05:49<32:48,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.539278030395508, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.612354278564453, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 620/4000 [05:50<36:01,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.365803718566895, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.515636444091797, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 621/4000 [05:50<31:35,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.410440921783447, Predicted Probability: 0.0044, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.831188201904297, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 622/4000 [05:51<31:16,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.895787239074707, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9478724002838135, Predicted Probability: 0.9502, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 623/4000 [05:51<28:19,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.125483512878418, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.265581130981445, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 624/4000 [05:52<25:59,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.70397663116455, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.114394187927246, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 625/4000 [05:52<27:11,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.304291248321533, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.576451301574707, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 626/4000 [05:53<31:37,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8628857135772705, Predicted Probability: 0.0206, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7652487754821777, Predicted Probability: 0.9408, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 627/4000 [05:54<34:47,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.229944229125977, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.639415264129639, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 628/4000 [05:55<39:03,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.917478561401367, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.283576965332031, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 629/4000 [05:55<36:34,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.275468826293945, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.307736396789551, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 630/4000 [05:56<37:51,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.785411834716797, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.465585947036743, Predicted Probability: 0.0783, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 631/4000 [05:57<38:36,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0905284881591797, Predicted Probability: 0.9565, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.253937721252441, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 632/4000 [05:57<36:34,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.6623125076293945, Predicted Probability: 0.9906, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.353278636932373, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 633/4000 [05:58<38:32,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.757134437561035, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.23957633972168, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 634/4000 [05:58<30:32,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.633950233459473, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.317207932472229, Predicted Probability: 0.7887, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 635/4000 [05:59<34:28,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.618372917175293, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.779725193977356, Predicted Probability: 0.8557, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 636/4000 [05:59<27:35,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.276068687438965, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.923030853271484, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 637/4000 [06:00<28:17,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.325277328491211, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.936277389526367, Predicted Probability: 0.9496, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 638/4000 [06:00<32:32,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.3451151847839355, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.194474935531616, Predicted Probability: 0.9606, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 639/4000 [06:01<35:24,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1357741355896, Predicted Probability: 0.0157, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.985087871551514, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 640/4000 [06:02<34:14,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8769500255584717, Predicted Probability: 0.9797, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8145101070404053, Predicted Probability: 0.9435, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 641/4000 [06:02<33:13,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.270384788513184, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.954746723175049, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 642/4000 [06:03<32:39,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.113160133361816, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.301074504852295, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 643/4000 [06:03<26:24,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.152024269104004, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7436909675598145, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 644/4000 [06:04<30:55,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.526805877685547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.893285036087036, Predicted Probability: 0.0200, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 645/4000 [06:05<35:15,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.313115119934082, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.735567092895508, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 646/4000 [06:05<31:00,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.67860221862793, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.961447715759277, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 3/3:  16%|█▌        | 647/4000 [06:06<33:46,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.737058639526367, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3149452209472656, Predicted Probability: 0.2117, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 648/4000 [06:06<29:41,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.02741813659668, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.781668663024902, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▌        | 649/4000 [06:06<27:02,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.866449356079102, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.58201789855957, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  16%|█▋        | 650/4000 [06:07<25:25,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.400395393371582, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.956581115722656, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  16%|█▋        | 651/4000 [06:08<30:31,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.770281791687012, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.074615478515625, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▋        | 652/4000 [06:08<33:54,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9115681648254395, Predicted Probability: 0.0516, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.686352729797363, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  16%|█▋        | 653/4000 [06:09<36:31,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.587122917175293, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1684842109680176, Predicted Probability: 0.2371, Prediction: 0.0

Epoch 3/3:  16%|█▋        | 654/4000 [06:10<34:26,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.98974871635437, Predicted Probability: 0.0182, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.619144439697266, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  16%|█▋        | 655/4000 [06:10<33:11,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.658989906311035, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.047162055969238, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  16%|█▋        | 656/4000 [06:11<35:49,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.48134994506836, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0141327381134033, Predicted Probability: 0.1177, Prediction: 0.0

Epoch 3/3:  16%|█▋        | 657/4000 [06:12<38:30,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.331144332885742, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.084429740905762, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  16%|█▋        | 658/4000 [06:12<39:19,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0544848442077637, Predicted Probability: 0.9550, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.356888771057129, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  16%|█▋        | 659/4000 [06:13<33:34,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.824317932128906, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.609645366668701, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  16%|█▋        | 660/4000 [06:13<29:36,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.7546868324279785, Predicted Probability: 0.0085, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.936059951782227, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 661/4000 [06:13<24:09,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.857598304748535, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.185272693634033, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 662/4000 [06:14<22:55,  2.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.267792701721191, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.495755672454834, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 663/4000 [06:14<28:04,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.28163480758667, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.11744499206543, Predicted Probability: 0.9840, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 664/4000 [06:15<23:08,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.68559455871582, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.870096206665039, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 665/4000 [06:15<29:06,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.400385856628418, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.125520706176758, Predicted Probability: 0.9579, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 666/4000 [06:16<26:36,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.543623924255371, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.783353328704834, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 667/4000 [06:17<30:15,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.58642864227295, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8157790899276733, Predicted Probability: 0.3067, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 668/4000 [06:17<33:40,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1207172870635986, Predicted Probability: 0.1071, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.55907917022705, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 669/4000 [06:18<32:39,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.4118070602417, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2459588050842285, Predicted Probability: 0.9859, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 670/4000 [06:18<32:00,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.700624465942383, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.488360404968262, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 671/4000 [06:19<34:53,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5382096767425537, Predicted Probability: 0.9718, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.4209566116333, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 672/4000 [06:19<30:29,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.923594951629639, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1652727127075195, Predicted Probability: 0.9847, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 673/4000 [06:20<34:29,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.050725936889648, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.792755126953125, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 674/4000 [06:21<37:11,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.040910720825195, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.739301681518555, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 675/4000 [06:22<38:24,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.438371181488037, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4203479290008545, Predicted Probability: 0.8054, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 676/4000 [06:22<36:00,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.8181233406066895, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7345168590545654, Predicted Probability: 0.9767, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 677/4000 [06:23<37:31,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1520237922668457, Predicted Probability: 0.9590, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.788764476776123, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 678/4000 [06:24<35:26,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.020615577697754, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7902021408081055, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 679/4000 [06:24<36:47,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.892403602600098, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.891523599624634, Predicted Probability: 0.9474, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 680/4000 [06:25<31:53,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.174129486083984, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.6664557456970215, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 681/4000 [06:26<35:21,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.982357025146484, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.732087135314941, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 683/4000 [06:26<23:01,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.790311813354492, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.221712112426758, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.27736759185791, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.979170799255371, Predicted Probability: 0.0068, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 684/4000 [06:27<28:17,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.889901638031006, Predicted Probability: 0.9473, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.65771198272705, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 685/4000 [06:27<32:19,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.105281114578247, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.727753162384033, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 686/4000 [06:28<36:24,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4083170890808105, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.584251403808594, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 687/4000 [06:29<31:43,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.526119709014893, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.057812690734863, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 688/4000 [06:29<28:12,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.037110805511475, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.967543601989746, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 690/4000 [06:30<25:53,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.020256042480469, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.3275282084941864, Predicted Probability: 0.5812, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.580135345458984, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.036775588989258, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 692/4000 [06:31<22:05,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.170660972595215, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.754430294036865, Predicted Probability: 0.9915, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.384093284606934, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1133503913879395, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 693/4000 [06:31<28:15,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.609600067138672, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.39701509475708, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 694/4000 [06:32<33:24,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.43555212020874, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.473691463470459, Predicted Probability: 0.9887, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 695/4000 [06:33<35:20,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.275606155395508, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.839864730834961, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  17%|█▋        | 697/4000 [06:34<25:34,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.018986701965332, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.44369649887085, Predicted Probability: 0.9957, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.626562118530273, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.580018043518066, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 698/4000 [06:34<30:12,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.461141586303711, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.178318500518799, Predicted Probability: 0.9600, Prediction: 1.0

Epoch 3/3:  17%|█▋        | 699/4000 [06:35<34:18,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.608005046844482, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.363554954528809, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 700/4000 [06:35<27:23,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.581252098083496, Predicted Probability: 0.0704, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.073482513427734, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 701/4000 [06:36<28:13,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.904214859008789, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.890045642852783, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 702/4000 [06:36<25:48,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.0396089553833, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.649514675140381, Predicted Probability: 0.9747, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 703/4000 [06:37<27:31,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.648041248321533, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.9282732009887695, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 704/4000 [06:37<28:05,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.010860443115234, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.481555938720703, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 705/4000 [06:38<31:40,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.950674533843994, Predicted Probability: 0.9503, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.550247192382812, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 706/4000 [06:39<29:27,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.280939102172852, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.557852745056152, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 707/4000 [06:39<27:06,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.857026100158691, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.869638442993164, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 708/4000 [06:39<25:00,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6264303922653198, Predicted Probability: 0.8357, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.307992935180664, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 709/4000 [06:40<31:06,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.626677513122559, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3727684020996094, Predicted Probability: 0.9668, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 710/4000 [06:41<33:25,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.366568565368652, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.52115535736084, Predicted Probability: 0.9713, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 711/4000 [06:42<35:34,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8453612327575684, Predicted Probability: 0.9451, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.530998229980469, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 712/4000 [06:42<31:09,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.797162055969238, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.314871788024902, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 713/4000 [06:43<34:39,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.84281063079834, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.016929626464844, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 715/4000 [06:43<24:41,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.687848091125488, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.828392028808594, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.194119453430176, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.318092346191406, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 716/4000 [06:44<23:23,  2.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.48542594909668, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.516761302947998, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 717/4000 [06:44<28:12,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.462531089782715, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2841882705688477, Predicted Probability: 0.9639, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 718/4000 [06:45<28:39,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.185744285583496, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.186119318008423, Predicted Probability: 0.0397, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 719/4000 [06:46<31:44,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2503745555877686, Predicted Probability: 0.9627, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.340878486633301, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 720/4000 [06:46<34:45,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.064773559570312, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.749607563018799, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 721/4000 [06:47<31:40,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.530494689941406, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.899791717529297, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 722/4000 [06:47<28:13,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.3566365242004395, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.609122276306152, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 723/4000 [06:48<28:46,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.120901107788086, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7120187282562256, Predicted Probability: 0.0238, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 724/4000 [06:48<24:31,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.500326156616211, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.490883469581604, Predicted Probability: 0.6203, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 725/4000 [06:49<23:35,  2.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.545435905456543, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.130572319030762, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 726/4000 [06:49<28:33,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.558452606201172, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.781411170959473, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 727/4000 [06:50<26:08,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.124382972717285, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.213288307189941, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 728/4000 [06:50<32:40,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.069515228271484, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.081282615661621, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 729/4000 [06:51<31:57,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.585287094116211, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.978029727935791, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 730/4000 [06:52<35:23,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.436222076416016, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.319878578186035, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 731/4000 [06:52<28:05,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.021024703979492, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.249476432800293, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 732/4000 [06:52<25:33,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.994770050048828, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.460053443908691, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 733/4000 [06:53<24:03,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.334395408630371, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.843151569366455, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 735/4000 [06:53<20:02,  2.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.9568614959716797, Predicted Probability: 0.0188, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.646950721740723, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.800020217895508, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.638675689697266, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 736/4000 [06:54<20:16,  2.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.991253852844238, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.597689628601074, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 737/4000 [06:55<27:01,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.83615779876709, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5574337244033813, Predicted Probability: 0.1740, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 738/4000 [06:55<31:34,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.06304931640625, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0352489948272705, Predicted Probability: 0.1156, Prediction: 0.0

Epoch 3/3:  18%|█▊        | 739/4000 [06:56<31:15,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.975179195404053, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.076602458953857, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 3/3:  18%|█▊        | 740/4000 [06:56<28:01,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.500053882598877, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.556404113769531, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▊        | 741/4000 [06:57<31:18,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.096571922302246, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.009979486465454, Predicted Probability: 0.8818, Prediction: 1.0

Epoch 3/3:  19%|█▊        | 742/4000 [06:58<34:07,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.419665813446045, Predicted Probability: 0.0317, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9204587936401367, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 3/3:  19%|█▊        | 743/4000 [06:58<31:02,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.566183090209961, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.586445331573486, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 3/3:  19%|█▊        | 744/4000 [06:59<34:30,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.508109092712402, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.441880226135254, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 3/3:  19%|█▊        | 746/4000 [07:00<28:52,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.930913925170898, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.505331516265869, Predicted Probability: 0.9960, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.745351791381836, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.395302772521973, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▊        | 747/4000 [07:01<32:18,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.266337871551514, Predicted Probability: 0.0138, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.083955764770508, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  19%|█▊        | 748/4000 [07:01<34:43,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.362835884094238, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9849815368652344, Predicted Probability: 0.0183, Prediction: 0.0

Epoch 3/3:  19%|█▊        | 749/4000 [07:02<34:09,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.984827995300293, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4878623485565186, Predicted Probability: 0.9703, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 750/4000 [07:03<36:16,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.32992935180664, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.712657928466797, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 751/4000 [07:04<37:43,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.574342727661133, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4814958572387695, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 752/4000 [07:04<38:36,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.946930408477783, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.462135314941406, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 753/4000 [07:05<39:46,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.97380542755127, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.713441848754883, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 754/4000 [07:06<40:15,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.56058406829834, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.382373809814453, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 755/4000 [07:07<40:43,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.68042278289795, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.722133159637451, Predicted Probability: 0.9383, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 756/4000 [07:07<41:14,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.107823133468628, Predicted Probability: 0.8917, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.804698944091797, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 757/4000 [07:08<35:09,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.5936756134033203, Predicted Probability: 0.1689, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.829141616821289, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 758/4000 [07:08<30:48,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.437129020690918, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.958476066589355, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 759/4000 [07:09<33:36,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.997620105743408, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.445685386657715, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 760/4000 [07:10<35:39,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2388782799243927, Predicted Probability: 0.4406, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.067354202270508, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 761/4000 [07:10<36:55,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.183338165283203, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7328758239746094, Predicted Probability: 0.0234, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 762/4000 [07:11<38:40,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1299185752868652, Predicted Probability: 0.9581, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.833536148071289, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 763/4000 [07:12<39:22,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7575042247772217, Predicted Probability: 0.0228, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.260021209716797, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 764/4000 [07:12<33:30,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.267786502838135, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.182190895080566, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 765/4000 [07:13<36:20,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9230265617370605, Predicted Probability: 0.1275, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.902031898498535, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 766/4000 [07:14<37:15,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.84323787689209, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0337066650390625, Predicted Probability: 0.9541, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 767/4000 [07:15<38:08,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.261809349060059, Predicted Probability: 0.9948, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.523451328277588, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 768/4000 [07:15<39:02,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.219182968139648, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.543998718261719, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 769/4000 [07:16<36:14,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.70588493347168, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.479931831359863, Predicted Probability: 0.9888, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 770/4000 [07:16<31:14,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.735450267791748, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.809497356414795, Predicted Probability: 0.9919, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 771/4000 [07:17<34:12,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.315880298614502, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.142824172973633, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 772/4000 [07:18<37:19,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0787580013275146, Predicted Probability: 0.2537, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.724613189697266, Predicted Probability: 0.0088, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 773/4000 [07:18<32:03,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.450711727142334, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.591104507446289, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 774/4000 [07:19<28:19,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.265538215637207, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8137270212173462, Predicted Probability: 0.3071, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 775/4000 [07:19<33:05,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.957397937774658, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.832129001617432, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 776/4000 [07:20<33:19,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.396366119384766, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.937620639801025, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 777/4000 [07:21<36:04,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.824082374572754, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.954421997070312, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  19%|█▉        | 778/4000 [07:21<29:37,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.447996139526367, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.288692474365234, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  19%|█▉        | 779/4000 [07:22<26:41,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.735625267028809, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.521829605102539, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 780/4000 [07:22<30:36,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1691951751708984, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.519436836242676, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 781/4000 [07:23<30:04,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.282106399536133, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.864182949066162, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 782/4000 [07:24<33:47,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.7384033203125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.537625789642334, Predicted Probability: 0.0283, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 783/4000 [07:24<35:10,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.334245681762695, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.966676712036133, Predicted Probability: 0.9510, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 784/4000 [07:25<33:30,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.54160213470459, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.199398040771484, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 785/4000 [07:26<36:02,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.300088882446289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.121074676513672, Predicted Probability: 0.9578, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 786/4000 [07:26<36:50,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4662578105926514, Predicted Probability: 0.9217, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.535725593566895, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 787/4000 [07:27<35:35,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.852863311767578, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.650601387023926, Predicted Probability: 0.9747, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 788/4000 [07:27<30:52,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.790364265441895, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.824779987335205, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 789/4000 [07:28<27:33,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.201913833618164, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2787275314331055, Predicted Probability: 0.9863, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 790/4000 [07:28<31:02,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.055344581604004, Predicted Probability: 0.2582, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.00428581237793, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 791/4000 [07:29<33:41,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4523818492889404, Predicted Probability: 0.9693, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.596877098083496, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 792/4000 [07:30<29:38,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2601441144943237, Predicted Probability: 0.7791, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.045700073242188, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 793/4000 [07:30<32:52,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.317233085632324, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.673973083496094, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 794/4000 [07:31<29:09,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.993765830993652, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.832786560058594, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 795/4000 [07:32<33:05,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.440407752990723, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.190500259399414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 796/4000 [07:32<35:07,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6093907356262207, Predicted Probability: 0.9315, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.63707160949707, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 797/4000 [07:33<30:41,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.409156799316406, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.782838344573975, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  20%|█▉        | 798/4000 [07:33<33:11,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.617831707000732, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.873296737670898, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|█▉        | 799/4000 [07:34<32:23,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.760368347167969, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.919554710388184, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  20%|██        | 800/4000 [07:35<31:12,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.148395538330078, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.317362308502197, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  20%|██        | 801/4000 [07:35<33:32,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.1029276847839355, Predicted Probability: 0.0163, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.964049339294434, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|██        | 802/4000 [07:36<29:40,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.250123023986816, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.76883602142334, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  20%|██        | 803/4000 [07:36<29:28,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.840426445007324, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.07828426361084, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  20%|██        | 804/4000 [07:37<26:29,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.59638786315918, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.255762577056885, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  20%|██        | 805/4000 [07:37<24:44,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.110522270202637, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.941196441650391, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  20%|██        | 806/4000 [07:38<30:29,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.004344940185547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.215494632720947, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  20%|██        | 807/4000 [07:39<33:28,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.046655654907227, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.434934616088867, Predicted Probability: 0.9688, Prediction: 1.0

Epoch 3/3:  20%|██        | 808/4000 [07:39<29:22,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.251927375793457, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.315274238586426, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  20%|██        | 809/4000 [07:39<26:28,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.104687690734863, Predicted Probability: 0.9838, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.303751945495605, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  20%|██        | 811/4000 [07:40<25:53,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.828294038772583, Predicted Probability: 0.0213, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.4771623611450195, Predicted Probability: 0.0112, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.278300285339355, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.053422927856445, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  20%|██        | 812/4000 [07:41<24:56,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.835566520690918, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.643393039703369, Predicted Probability: 0.9905, Prediction: 1.0

Epoch 3/3:  20%|██        | 813/4000 [07:42<29:43,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.70605754852295, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.277337551116943, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  20%|██        | 814/4000 [07:42<32:41,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2420299053192139, Predicted Probability: 0.2241, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.564115524291992, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|██        | 815/4000 [07:43<34:46,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.893630981445312, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8516902923583984, Predicted Probability: 0.1357, Prediction: 0.0

Epoch 3/3:  20%|██        | 816/4000 [07:44<33:03,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0609519481658936, Predicted Probability: 0.0447, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.919352531433105, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|██        | 817/4000 [07:44<35:51,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.628278732299805, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.385965347290039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|██        | 818/4000 [07:45<30:58,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.085866928100586, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.588402271270752, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:  20%|██        | 819/4000 [07:46<34:16,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.337618827819824, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.903270721435547, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  20%|██        | 820/4000 [07:46<35:37,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.097198486328125, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8029024600982666, Predicted Probability: 0.9428, Prediction: 1.0

Epoch 3/3:  21%|██        | 821/4000 [07:47<36:28,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7214221954345703, Predicted Probability: 0.0236, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6418180465698242, Predicted Probability: 0.1622, Prediction: 0.0

Epoch 3/3:  21%|██        | 822/4000 [07:47<28:52,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.401998519897461, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.399664878845215, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  21%|██        | 823/4000 [07:48<32:11,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.275777816772461, Predicted Probability: 0.0364, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.972235679626465, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 3/3:  21%|██        | 824/4000 [07:49<31:27,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.551237106323242, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.830927848815918, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  21%|██        | 825/4000 [07:49<34:08,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.552196502685547, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.510059356689453, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  21%|██        | 826/4000 [07:49<27:15,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.54246711730957, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.070696830749512, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  21%|██        | 827/4000 [07:50<27:34,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.616253614425659, Predicted Probability: 0.0262, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.00986385345459, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  21%|██        | 828/4000 [07:51<27:52,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.61697006225586, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.432745933532715, Predicted Probability: 0.9883, Prediction: 1.0

Epoch 3/3:  21%|██        | 829/4000 [07:51<25:23,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.920637607574463, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.715104103088379, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  21%|██        | 830/4000 [07:52<28:59,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2823708057403564, Predicted Probability: 0.7829, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.207464218139648, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  21%|██        | 831/4000 [07:52<26:18,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.597886800765991, Predicted Probability: 0.0267, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.935230255126953, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  21%|██        | 832/4000 [07:52<24:24,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.487485885620117, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.457955360412598, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  21%|██        | 833/4000 [07:53<22:55,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0038065910339355, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.864739418029785, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  21%|██        | 834/4000 [07:54<27:42,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.490922927856445, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.422304153442383, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  21%|██        | 835/4000 [07:54<31:56,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9606597423553467, Predicted Probability: 0.9508, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.379927158355713, Predicted Probability: 0.0124, Prediction: 0.0

Epoch 3/3:  21%|██        | 836/4000 [07:55<28:26,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.042198657989502, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.067544937133789, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  21%|██        | 837/4000 [07:55<25:46,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.481812477111816, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.698036193847656, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  21%|██        | 838/4000 [07:56<26:33,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.073837757110596, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7986490726470947, Predicted Probability: 0.0574, Prediction: 0.0

Epoch 3/3:  21%|██        | 839/4000 [07:56<24:33,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.859842777252197, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.242827415466309, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  21%|██        | 840/4000 [07:57<29:22,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.487472057342529, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.933734893798828, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  21%|██        | 841/4000 [07:58<33:01,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.46293306350708, Predicted Probability: 0.9215, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.86067008972168, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  21%|██        | 842/4000 [07:58<32:01,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.234616756439209, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.040369510650635, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  21%|██        | 843/4000 [07:58<28:35,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.164596557617188, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.595015525817871, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  21%|██        | 844/4000 [07:59<25:58,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.687980651855469, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.201696872711182, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  21%|██        | 845/4000 [08:00<29:46,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.744561195373535, Predicted Probability: 0.9769, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.949409484863281, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  21%|██        | 846/4000 [08:00<28:05,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.308673858642578, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.8619232177734375, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  21%|██        | 847/4000 [08:01<33:04,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.064933776855469, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.770307540893555, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  21%|██        | 848/4000 [08:01<32:00,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.155413627624512, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.059261798858643, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 3/3:  21%|██        | 849/4000 [08:02<34:00,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.718255996704102, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.134770631790161, Predicted Probability: 0.9583, Prediction: 1.0

Epoch 3/3:  21%|██▏       | 850/4000 [08:03<35:38,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8076248168945312, Predicted Probability: 0.0217, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.539060592651367, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  21%|██▏       | 851/4000 [08:03<31:03,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.116992950439453, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7329158186912537, Predicted Probability: 0.6754, Prediction: 1.0

Epoch 3/3:  21%|██▏       | 852/4000 [08:04<27:35,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.998250961303711, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.770216464996338, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  21%|██▏       | 853/4000 [08:04<31:06,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.77773666381836, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0510127544403076, Predicted Probability: 0.9548, Prediction: 1.0

Epoch 3/3:  21%|██▏       | 854/4000 [08:05<30:32,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9879841804504395, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.807474136352539, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  21%|██▏       | 855/4000 [08:05<27:14,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.6272196769714355, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.685461044311523, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  21%|██▏       | 856/4000 [08:06<24:52,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.562664031982422, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.6601881980896, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 3/3:  21%|██▏       | 857/4000 [08:07<28:50,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6716203689575195, Predicted Probability: 0.0248, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.118062973022461, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  21%|██▏       | 858/4000 [08:07<31:40,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.878011465072632, Predicted Probability: 0.0203, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.647113800048828, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  21%|██▏       | 859/4000 [08:08<34:24,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1236753463745117, Predicted Probability: 0.8932, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.373531341552734, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 860/4000 [08:09<35:44,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.04342535138130188, Predicted Probability: 0.4891, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.901676177978516, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 861/4000 [08:09<33:19,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0699307918548584, Predicted Probability: 0.0444, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.235857963562012, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 862/4000 [08:10<30:30,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6168838143348694, Predicted Probability: 0.3505, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.929237365722656, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 863/4000 [08:10<27:23,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.928997039794922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.418999195098877, Predicted Probability: 0.0119, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 864/4000 [08:11<26:26,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.862537384033203, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.100801944732666, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 865/4000 [08:11<30:50,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.889355659484863, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.013747215270996, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 866/4000 [08:12<33:13,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.51323127746582, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4636123180389404, Predicted Probability: 0.1879, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 867/4000 [08:13<35:00,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.989812850952148, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.286001205444336, Predicted Probability: 0.9864, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 868/4000 [08:14<36:57,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.042080879211426, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.6674368381500244, Predicted Probability: 0.8412, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 869/4000 [08:14<31:37,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0863494873046875, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.599049091339111, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 870/4000 [08:15<34:27,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.39084243774414, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.970818281173706, Predicted Probability: 0.9512, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 871/4000 [08:16<35:41,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.235299110412598, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.0799641609191895, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 872/4000 [08:16<37:15,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.2482168674468994, Predicted Probability: 0.0955, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.447174072265625, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 873/4000 [08:17<32:06,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.27535629272461, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.064212799072266, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 874/4000 [08:17<33:42,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.49925422668457, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.883987426757812, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 875/4000 [08:18<29:22,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5991644859313965, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0151045322418213, Predicted Probability: 0.9533, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 876/4000 [08:18<26:24,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.367154598236084, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.77717399597168, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 877/4000 [08:19<30:14,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.781147003173828, Predicted Probability: 0.0083, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.79746150970459, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 878/4000 [08:20<33:47,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.174162864685059, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6490707397460938, Predicted Probability: 0.9746, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 879/4000 [08:20<30:46,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.346550941467285, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.879291534423828, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 880/4000 [08:21<30:07,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.806983947753906, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.346518516540527, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 881/4000 [08:22<32:46,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1413846015930176, Predicted Probability: 0.9586, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.072628021240234, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 882/4000 [08:22<31:30,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.082901954650879, Predicted Probability: 0.9562, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.788140296936035, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 883/4000 [08:23<30:18,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.550257682800293, Predicted Probability: 0.9895, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.351869583129883, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 884/4000 [08:23<25:22,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.891013145446777, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.544002532958984, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 885/4000 [08:23<23:32,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.934553146362305, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.420736312866211, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 886/4000 [08:24<25:15,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.216372966766357, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.05040168762207, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 887/4000 [08:24<23:43,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.457588195800781, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.873016357421875, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 888/4000 [08:25<30:03,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.869734287261963, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.668413162231445, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 889/4000 [08:25<27:04,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.320833206176758, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5030373334884644, Predicted Probability: 0.8180, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 890/4000 [08:26<30:33,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.104755878448486, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.203655242919922, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 891/4000 [08:27<32:39,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7491883039474487, Predicted Probability: 0.1481, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.492461204528809, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 892/4000 [08:28<34:27,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4201250076293945, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8570578694343567, Predicted Probability: 0.7020, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 893/4000 [08:28<27:22,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.082073211669922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.414708137512207, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 894/4000 [08:28<27:21,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.797473430633545, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.54252290725708, Predicted Probability: 0.9719, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 895/4000 [08:29<22:24,  2.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.99637508392334, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.589482307434082, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 896/4000 [08:29<27:58,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.315302848815918, Predicted Probability: 0.9868, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.823322296142578, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  22%|██▏       | 897/4000 [08:30<27:53,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.185646057128906, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.769285798072815, Predicted Probability: 0.8544, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 898/4000 [08:31<31:18,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.2938232421875, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.234524726867676, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  22%|██▏       | 899/4000 [08:31<33:25,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.106733322143555, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5500121116638184, Predicted Probability: 0.9276, Prediction: 1.0

Epoch 3/3:  22%|██▎       | 900/4000 [08:32<34:51,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.379016876220703, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.444335699081421, Predicted Probability: 0.0799, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 901/4000 [08:33<35:45,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5953192710876465, Predicted Probability: 0.9306, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6220850944519043, Predicted Probability: 0.0677, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 902/4000 [08:33<30:43,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.172374725341797, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.621041297912598, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 903/4000 [08:34<27:16,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.916760444641113, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.732126235961914, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 904/4000 [08:34<25:58,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5696608424186707, Predicted Probability: 0.6387, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.036923408508301, Predicted Probability: 0.9935, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 905/4000 [08:35<29:28,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.569412708282471, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.655820608139038, Predicted Probability: 0.9344, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 906/4000 [08:36<32:08,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.560876846313477, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6414730548858643, Predicted Probability: 0.9335, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 907/4000 [08:36<34:02,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.348404407501221, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.381043434143066, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 908/4000 [08:37<27:54,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.993551254272461, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.710695266723633, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 909/4000 [08:37<30:48,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1132049560546875, Predicted Probability: 0.8922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.385148048400879, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 910/4000 [08:38<27:16,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6405659317970276, Predicted Probability: 0.6549, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.249016761779785, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 911/4000 [08:38<24:44,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.974405288696289, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.262012958526611, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 912/4000 [08:38<20:29,  2.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.475646018981934, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.583036422729492, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 913/4000 [08:39<26:16,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.679306030273438, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.226229190826416, Predicted Probability: 0.0974, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 914/4000 [08:40<30:49,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.013467788696289, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.00097942352295, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 915/4000 [08:40<27:20,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0676469802856445, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.882951736450195, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 916/4000 [08:41<25:53,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.494405746459961, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.730193614959717, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 917/4000 [08:41<26:34,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.940778732299805, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.97550630569458, Predicted Probability: 0.0485, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 918/4000 [08:42<27:06,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.289719581604004, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.412112236022949, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 919/4000 [08:42<30:21,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.624946355819702, Predicted Probability: 0.9324, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.598274230957031, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 920/4000 [08:43<26:51,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.694337844848633, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.296828269958496, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 921/4000 [08:44<29:58,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.089140892028809, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3923041820526123, Predicted Probability: 0.9162, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 922/4000 [08:44<32:32,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.823015213012695, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.165704250335693, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 923/4000 [08:45<36:51,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.453371047973633, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.534536361694336, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 924/4000 [08:46<37:10,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.725308418273926, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3086559772491455, Predicted Probability: 0.9096, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 925/4000 [08:47<37:24,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.172813415527344, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.483611822128296, Predicted Probability: 0.9230, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 926/4000 [08:47<37:43,  1.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.448814868927002, Predicted Probability: 0.9205, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.352376937866211, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 927/4000 [08:48<39:12,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.141239166259766, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.659713745117188, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 928/4000 [08:49<38:44,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4096946716308594, Predicted Probability: 0.9176, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.392019271850586, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 929/4000 [08:49<30:18,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.491326332092285, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.903717994689941, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 930/4000 [08:50<26:45,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.591463088989258, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.91850471496582, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 931/4000 [08:50<24:23,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.453615188598633, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.293397426605225, Predicted Probability: 0.9950, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 932/4000 [08:51<25:22,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.5392427444458, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.676449298858643, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 933/4000 [08:51<23:22,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.747675895690918, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.660815715789795, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 934/4000 [08:51<22:02,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.580606460571289, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.143066883087158, Predicted Probability: 0.1050, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 935/4000 [08:52<23:47,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.908732414245605, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.89542293548584, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 936/4000 [08:53<27:33,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.622465133666992, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.358215808868408, Predicted Probability: 0.9874, Prediction: 1.0

Epoch 3/3:  23%|██▎       | 937/4000 [08:53<30:30,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.397054672241211, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.021594047546387, Predicted Probability: 0.0066, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 938/4000 [08:54<33:47,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.052483558654785, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.552088260650635, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:  23%|██▎       | 939/4000 [08:54<26:47,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.214076042175293, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.856236457824707, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  24%|██▎       | 940/4000 [08:55<27:00,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.069235801696777, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5131540298461914, Predicted Probability: 0.9711, Prediction: 1.0

Epoch 3/3:  24%|██▎       | 941/4000 [08:55<24:41,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1486687660217285, Predicted Probability: 0.1045, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.87388801574707, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  24%|██▎       | 942/4000 [08:56<28:47,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.775798797607422, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.86780834197998, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  24%|██▎       | 943/4000 [08:56<23:20,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.09762954711914, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.424220085144043, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  24%|██▎       | 944/4000 [08:57<28:08,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8891545534133911, Predicted Probability: 0.8687, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.920719146728516, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  24%|██▎       | 945/4000 [08:57<27:59,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.09518051147461, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.879894256591797, Predicted Probability: 0.9798, Prediction: 1.0

Epoch 3/3:  24%|██▎       | 946/4000 [08:58<25:14,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.984095573425293, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.209858417510986, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  24%|██▎       | 947/4000 [08:59<28:48,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.410367012023926, Predicted Probability: 0.0824, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.958081245422363, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  24%|██▎       | 948/4000 [08:59<28:28,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6392316818237305, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.121310234069824, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  24%|██▎       | 949/4000 [09:00<30:56,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1558995246887207, Predicted Probability: 0.1038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.541765213012695, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 950/4000 [09:01<35:16,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.287273406982422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.77546501159668, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 951/4000 [09:01<35:51,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.092708587646484, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.399984836578369, Predicted Probability: 0.9168, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 953/4000 [09:02<28:48,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4751532077789307, Predicted Probability: 0.9224, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.083130836486816, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.45585823059082, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.453172206878662, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 954/4000 [09:03<25:46,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.74162483215332, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.258232831954956, Predicted Probability: 0.9630, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 955/4000 [09:03<26:08,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.141348838806152, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.136327028274536, Predicted Probability: 0.9584, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 956/4000 [09:04<29:47,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.53996467590332, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.479615211486816, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 957/4000 [09:05<30:06,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.474766969680786, Predicted Probability: 0.9700, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.928895473480225, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 958/4000 [09:05<27:44,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.377232551574707, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.570590972900391, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 959/4000 [09:06<25:13,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.033703804016113, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.291533946990967, Predicted Probability: 0.0135, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 960/4000 [09:06<23:23,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.798252105712891, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.648377418518066, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 961/4000 [09:07<27:48,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6784827709198, Predicted Probability: 0.9357, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.215187072753906, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 962/4000 [09:07<30:40,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.735974311828613, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.677612781524658, Predicted Probability: 0.9357, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 963/4000 [09:08<27:06,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.083713531494141, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.154653549194336, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 964/4000 [09:08<27:07,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.121706008911133, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.012737274169922, Predicted Probability: 0.1179, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 965/4000 [09:09<24:32,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.96031665802002, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7726287841796875, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 966/4000 [09:09<28:12,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.737579107284546, Predicted Probability: 0.9392, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.963201522827148, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 967/4000 [09:10<28:05,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.339055061340332, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6621623039245605, Predicted Probability: 0.0094, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 968/4000 [09:10<25:07,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.559903144836426, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.432841300964355, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 969/4000 [09:11<28:51,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.595364570617676, Predicted Probability: 0.9306, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.616612434387207, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 970/4000 [09:11<24:11,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.143226623535156, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.680465698242188, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 971/4000 [09:12<27:44,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.46124204993247986, Predicted Probability: 0.3867, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.169819355010986, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 972/4000 [09:13<30:38,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.492671489715576, Predicted Probability: 0.9236, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.102524757385254, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 973/4000 [09:13<26:55,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.06540584564209, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.08722972869873, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 974/4000 [09:14<29:36,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.582352876663208, Predicted Probability: 0.9297, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.211152076721191, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 975/4000 [09:15<32:01,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.513361930847168, Predicted Probability: 0.0749, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.234439849853516, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 976/4000 [09:15<34:14,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.10453987121582, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.167868614196777, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 977/4000 [09:16<29:25,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.546923637390137, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.477924346923828, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 978/4000 [09:16<29:00,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.403555870056152, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1224365234375, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  24%|██▍       | 979/4000 [09:17<26:01,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.8628387451171875, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.057147026062012, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  24%|██▍       | 980/4000 [09:17<30:19,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.603302001953125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.09377670288086, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 981/4000 [09:18<32:36,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.307570457458496, Predicted Probability: 0.9095, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.724371910095215, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 982/4000 [09:19<33:56,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.590848922729492, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.255887985229492, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 983/4000 [09:20<32:04,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.21495246887207, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.8991475105285645, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 984/4000 [09:20<33:24,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.363095760345459, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.489963531494141, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 985/4000 [09:21<34:34,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.042320251464844, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.117914199829102, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 986/4000 [09:21<29:46,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.556737899780273, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.896957874298096, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 987/4000 [09:22<32:00,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.101771354675293, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5287625789642334, Predicted Probability: 0.0739, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 988/4000 [09:23<35:02,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.233505249023438, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.552119255065918, Predicted Probability: 0.0104, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 989/4000 [09:23<30:17,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.282029151916504, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.248225212097168, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 990/4000 [09:24<24:18,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.245450973510742, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.722758293151855, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 991/4000 [09:24<28:31,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.496635437011719, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.109282493591309, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 992/4000 [09:25<31:41,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.499078273773193, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.709527969360352, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 993/4000 [09:26<33:28,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.060821533203125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0791099071502686, Predicted Probability: 0.1111, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 994/4000 [09:26<29:00,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.124293327331543, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.778357028961182, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 995/4000 [09:27<28:35,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9723734855651855, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.926024436950684, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 996/4000 [09:28<32:37,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.385568618774414, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.834623336791992, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 997/4000 [09:28<28:42,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.75570297241211, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.288683891296387, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▍       | 998/4000 [09:29<28:15,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.158792495727539, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.423684120178223, Predicted Probability: 0.9882, Prediction: 1.0

Epoch 3/3:  25%|██▍       | 999/4000 [09:29<31:10,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.109988689422607, Predicted Probability: 0.9839, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.693674087524414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1000/4000 [09:30<33:57,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.586076736450195, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.291318893432617, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1001/4000 [09:31<39:31,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.912799835205078, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.718088150024414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1002/4000 [09:31<31:48,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.602662086486816, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.61514139175415, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1003/4000 [09:32<33:33,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.229414939880371, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.744816780090332, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1004/4000 [09:33<29:06,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.57643461227417, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.48775577545166, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1005/4000 [09:33<26:01,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.613829135894775, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.830986976623535, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1006/4000 [09:34<29:18,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.125696182250977, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.646970748901367, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1007/4000 [09:34<31:18,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.626190185546875, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.610146522521973, Predicted Probability: 0.9901, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1008/4000 [09:35<31:06,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.990424156188965, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.78276252746582, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1009/4000 [09:35<27:23,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.6625447273254395, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.599940299987793, Predicted Probability: 0.9900, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1010/4000 [09:36<25:43,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.366959571838379, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.126725673675537, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1011/4000 [09:37<29:06,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.415975570678711, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.630769729614258, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1012/4000 [09:37<26:12,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.859865188598633, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.682030200958252, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1013/4000 [09:38<26:25,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.7369599342346191, Predicted Probability: 0.1497, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.813359260559082, Predicted Probability: 0.0216, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1014/4000 [09:38<29:41,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.391423225402832, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.756210803985596, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  25%|██▌       | 1015/4000 [09:39<26:14,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.17077922821045, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.744640350341797, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1016/4000 [09:39<29:21,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5407590866088867, Predicted Probability: 0.0730, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8223986625671387, Predicted Probability: 0.6947, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1017/4000 [09:40<26:02,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.271203994750977, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.775932312011719, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1018/4000 [09:40<29:14,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.410652160644531, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6833207607269287, Predicted Probability: 0.9755, Prediction: 1.0

Epoch 3/3:  25%|██▌       | 1019/4000 [09:41<26:05,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.3044352531433105, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.619656562805176, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1020/4000 [09:41<24:34,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1192450523376465, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.226813316345215, Predicted Probability: 0.9618, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1021/4000 [09:42<29:03,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.722919940948486, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.272701263427734, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1022/4000 [09:43<31:08,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7516021728515625, Predicted Probability: 0.0600, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6154069900512695, Predicted Probability: 0.9318, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1023/4000 [09:44<32:58,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.656973838806152, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.24585455656051636, Predicted Probability: 0.5612, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1024/4000 [09:44<28:45,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.034578323364258, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.495957374572754, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1025/4000 [09:44<24:04,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.970682144165039, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.11209487915039, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1026/4000 [09:45<27:24,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2648541927337646, Predicted Probability: 0.9059, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.251372814178467, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1027/4000 [09:45<22:14,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.222653865814209, Predicted Probability: 0.0144, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.8523588180542, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1028/4000 [09:46<27:32,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.040754318237305, Predicted Probability: 0.0064, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.119312286376953, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1029/4000 [09:46<25:51,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.776518821716309, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.464367389678955, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1030/4000 [09:47<29:32,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6979924440383911, Predicted Probability: 0.3323, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2030205726623535, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1031/4000 [09:47<26:12,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.632406234741211, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.448802947998047, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1032/4000 [09:48<29:42,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.4794766902923584, Predicted Probability: 0.3824, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8835511207580566, Predicted Probability: 0.9798, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1033/4000 [09:49<31:36,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.400392770767212, Predicted Probability: 0.0831, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.435465097427368, Predicted Probability: 0.9195, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1034/4000 [09:50<33:40,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.596758842468262, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.858946800231934, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1035/4000 [09:50<29:15,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.446393013000488, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.003849983215332, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1036/4000 [09:51<31:36,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.346382141113281, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0671124458312988, Predicted Probability: 0.2560, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1037/4000 [09:51<27:38,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.827688217163086, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.618021011352539, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1038/4000 [09:52<30:19,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.861265182495117, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.212418794631958, Predicted Probability: 0.9613, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1039/4000 [09:53<32:33,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.803186893463135, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.69077205657959, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1040/4000 [09:54<33:27,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.898752212524414, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0032131671905518, Predicted Probability: 0.8811, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1041/4000 [09:54<29:16,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.8546724319458, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.53974437713623, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1042/4000 [09:54<26:13,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.667182922363281, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.712606430053711, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1043/4000 [09:55<23:46,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4002251625061035, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.413871765136719, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1044/4000 [09:55<22:02,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.543488025665283, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.295289993286133, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1045/4000 [09:56<27:04,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.23747444152832, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.945009231567383, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  26%|██▌       | 1046/4000 [09:56<21:57,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.466971397399902, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.350728034973145, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1047/4000 [09:57<23:23,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.759566307067871, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.264523506164551, Predicted Probability: 0.9861, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1048/4000 [09:57<22:08,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.28796100616455, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.371257781982422, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  26%|██▌       | 1049/4000 [09:57<20:50,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.130836486816406, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.765793800354004, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1050/4000 [09:58<24:54,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.708693742752075, Predicted Probability: 0.9375, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.526189804077148, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1051/4000 [09:59<30:07,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.215060234069824, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7444047927856445, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1052/4000 [10:00<32:06,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.074248313903809, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.687845230102539, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1053/4000 [10:00<28:57,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.431628704071045, Predicted Probability: 0.9882, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.95389175415039, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▋       | 1054/4000 [10:01<32:49,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.386528968811035, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.0897798538208, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1055/4000 [10:01<31:11,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.695691108703613, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.685553550720215, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  26%|██▋       | 1056/4000 [10:02<33:00,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.163415908813477, Predicted Probability: 0.9847, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2101542949676514, Predicted Probability: 0.9012, Prediction: 1.0

Epoch 3/3:  26%|██▋       | 1057/4000 [10:02<26:12,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.231127738952637, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.954068183898926, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  26%|██▋       | 1058/4000 [10:03<29:47,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.177545547485352, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3494393825531006, Predicted Probability: 0.0339, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1059/4000 [10:04<31:46,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4300506114959717, Predicted Probability: 0.9686, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.9972639083862305, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 3/3:  26%|██▋       | 1060/4000 [10:05<30:27,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.89737606048584, Predicted Probability: 0.9477, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.794130325317383, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1061/4000 [10:05<26:47,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.334456443786621, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.933337688446045, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1062/4000 [10:06<31:15,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.757454872131348, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.815290451049805, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1063/4000 [10:07<32:50,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.364688873291016, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7507346868515015, Predicted Probability: 0.8520, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1064/4000 [10:07<34:05,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.616848945617676, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.35923957824707, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1065/4000 [10:08<35:06,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6014564037323, Predicted Probability: 0.0690, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.256189346313477, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1066/4000 [10:09<32:53,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.775967597961426, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.859878540039062, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1067/4000 [10:09<34:10,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9567461013793945, Predicted Probability: 0.0494, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.845508575439453, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1068/4000 [10:10<34:59,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.978656768798828, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.333584308624268, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1069/4000 [10:11<35:30,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.673678398132324, Predicted Probability: 0.9355, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.156299591064453, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1070/4000 [10:11<32:44,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.478813171386719, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.8000609874725342, Predicted Probability: 0.3100, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1072/4000 [10:12<26:37,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6681108474731445, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.14011812210083, Predicted Probability: 0.9942, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.67640209197998, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.132580757141113, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1073/4000 [10:13<21:40,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.904041290283203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.742399215698242, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1074/4000 [10:13<20:32,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.213193893432617, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.889123916625977, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1075/4000 [10:14<26:28,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.867807388305664, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.789474487304688, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1076/4000 [10:15<29:59,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6751344203948975, Predicted Probability: 0.9753, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.429059982299805, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1077/4000 [10:15<31:55,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.266208171844482, Predicted Probability: 0.0138, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.285487174987793, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1078/4000 [10:16<34:32,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4560625553131104, Predicted Probability: 0.0306, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.975225448608398, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1079/4000 [10:17<35:38,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7936785221099854, Predicted Probability: 0.0577, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.716775417327881, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1080/4000 [10:18<35:51,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.850109100341797, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.139859676361084, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1081/4000 [10:18<32:51,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.202145576477051, Predicted Probability: 0.9853, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.536715507507324, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1082/4000 [10:19<29:27,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.689393520355225, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.574320793151855, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1083/4000 [10:19<25:51,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.082140922546387, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.3634672164917, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1084/4000 [10:19<23:45,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.264554023742676, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.195056915283203, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1085/4000 [10:20<27:22,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.1733174324035645, Predicted Probability: 0.9848, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.878451347351074, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1086/4000 [10:20<22:14,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.136636734008789, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.259842872619629, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1087/4000 [10:21<23:20,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.682551383972168, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7989189624786377, Predicted Probability: 0.9781, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1088/4000 [10:22<27:32,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.139714241027832, Predicted Probability: 0.0157, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.875804901123047, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1089/4000 [10:22<22:15,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.724385261535645, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 12.044333457946777, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1090/4000 [10:22<22:03,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.293416976928711, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.877534866333008, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1091/4000 [10:23<26:45,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.94883394241333, Predicted Probability: 0.0498, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.787912368774414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1092/4000 [10:23<21:40,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.737309455871582, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.864558219909668, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1093/4000 [10:24<24:16,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.426960468292236, Predicted Probability: 0.0118, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.506574630737305, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1094/4000 [10:24<20:05,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.161351203918457, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -5.629022121429443, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1095/4000 [10:25<21:47,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.7849202156066895, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8017215728759766, Predicted Probability: 0.9782, Prediction: 1.0

Epoch 3/3:  27%|██▋       | 1096/4000 [10:25<25:54,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7802140712738037, Predicted Probability: 0.9416, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.290400505065918, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1097/4000 [10:26<29:14,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.894064903259277, Predicted Probability: 0.0074, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.44715690612793, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  27%|██▋       | 1098/4000 [10:27<25:52,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.49107551574707, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.273223400115967, Predicted Probability: 0.9863, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1100/4000 [10:27<23:03,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.991683959960938, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9223146438598633, Predicted Probability: 0.7155, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -5.5185933113098145, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.208187103271484, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1101/4000 [10:28<27:07,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.3293914794921875, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.004340171813965, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1102/4000 [10:29<29:48,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.745697021484375, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.8619966506958, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1103/4000 [10:29<26:08,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.17984676361084, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.534703254699707, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1104/4000 [10:30<30:11,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.078680992126465, Predicted Probability: 0.1112, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.233451843261719, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1105/4000 [10:31<29:46,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.997915267944336, Predicted Probability: 0.9525, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.971442222595215, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1106/4000 [10:31<31:14,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.868969202041626, Predicted Probability: 0.9463, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.740811824798584, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1107/4000 [10:32<28:36,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.904881477355957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.178333282470703, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1108/4000 [10:32<25:37,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.352585792541504, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.500070571899414, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1109/4000 [10:33<20:56,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.768896102905273, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.808919906616211, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1110/4000 [10:33<22:43,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.023677825927734, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8999342918396, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1111/4000 [10:34<27:10,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.238954544067383, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7405035495758057, Predicted Probability: 0.0232, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1113/4000 [10:34<19:54,  2.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.882908821105957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.395076751708984, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.649746894836426, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.061043739318848, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1114/4000 [10:35<20:09,  2.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.4143447875976562, Predicted Probability: 0.9179, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.603904724121094, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1115/4000 [10:36<27:29,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.640791893005371, Predicted Probability: 0.9904, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.879571914672852, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1116/4000 [10:37<30:53,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.005012035369873, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.542105674743652, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1117/4000 [10:37<32:59,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.573391914367676, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.053572177886963, Predicted Probability: 0.2585, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1119/4000 [10:38<22:39,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.31668001413345337, Predicted Probability: 0.4215, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.050014495849609, Predicted Probability: 0.9829, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -4.9153151512146, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.112407684326172, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1120/4000 [10:39<26:21,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.011107444763184, Predicted Probability: 0.0178, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.819459915161133, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1121/4000 [10:39<28:59,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7605234384536743, Predicted Probability: 0.1467, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.576444387435913, Predicted Probability: 0.9293, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1122/4000 [10:40<30:41,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4209253787994385, Predicted Probability: 0.9184, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.632152557373047, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1123/4000 [10:41<31:58,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.973353385925293, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5848402976989746, Predicted Probability: 0.9299, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1124/4000 [10:41<30:10,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.616180419921875, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0879406929016113, Predicted Probability: 0.2520, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1126/4000 [10:42<24:59,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.307914733886719, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3645737171173096, Predicted Probability: 0.9141, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.954954147338867, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 4.487024784088135, Predicted Probability: 0.9889, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1127/4000 [10:43<23:49,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.59285831451416, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.576632499694824, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1128/4000 [10:43<24:34,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.202220916748047, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.890352249145508, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1129/4000 [10:44<28:01,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.4717302322387695, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.603701591491699, Predicted Probability: 0.9311, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1130/4000 [10:45<30:24,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.138859987258911, Predicted Probability: 0.8946, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.702249526977539, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1131/4000 [10:45<24:13,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.35326862335205, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.033425331115723, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1132/4000 [10:45<22:20,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.868182182312012, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.329456806182861, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1133/4000 [10:46<26:32,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.368189811706543, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8307263851165771, Predicted Probability: 0.8618, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1134/4000 [10:46<21:34,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.982780456542969, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.584671974182129, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1135/4000 [10:47<21:31,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.12976360321045, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.407114028930664, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1137/4000 [10:48<20:59,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.751482009887695, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.620071887969971, Predicted Probability: 0.9902, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -8.801018714904785, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.674004554748535, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1138/4000 [10:49<25:27,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.910783767700195, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.108159065246582, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  28%|██▊       | 1139/4000 [10:49<29:04,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.65173053741455, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9895201921463013, Predicted Probability: 0.8797, Prediction: 1.0

Epoch 3/3:  28%|██▊       | 1140/4000 [10:50<25:36,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.675987243652344, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.020773887634277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  29%|██▊       | 1141/4000 [10:50<23:22,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.346933364868164, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.26112174987793, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  29%|██▊       | 1142/4000 [10:51<24:08,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.137545585632324, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.232333660125732, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  29%|██▊       | 1143/4000 [10:51<27:18,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.131619453430176, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7540719509124756, Predicted Probability: 0.3199, Prediction: 0.0

Epoch 3/3:  29%|██▊       | 1144/4000 [10:52<24:24,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.1449613571167, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.538422584533691, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  29%|██▊       | 1145/4000 [10:52<27:56,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.1851420402526855, Predicted Probability: 0.9850, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.015252113342285, Predicted Probability: 0.0066, Prediction: 0.0

Epoch 3/3:  29%|██▊       | 1146/4000 [10:53<25:15,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.494091033935547, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.708313941955566, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  29%|██▊       | 1147/4000 [10:53<20:44,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.176504373550415, Predicted Probability: 0.1019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6199178695678711, Predicted Probability: 0.6502, Prediction: 1.0

Epoch 3/3:  29%|██▊       | 1148/4000 [10:54<25:03,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0282375812530518, Predicted Probability: 0.2634, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.420341491699219, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  29%|██▊       | 1149/4000 [10:54<23:57,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.299515724182129, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.8006076216697693, Predicted Probability: 0.6901, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1150/4000 [10:55<27:21,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.958484649658203, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1876327991485596, Predicted Probability: 0.8991, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1151/4000 [10:56<29:42,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.129654884338379, Predicted Probability: 0.8938, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.861802101135254, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1152/4000 [10:56<29:23,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.217795267701149, Predicted Probability: 0.5542, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.654519557952881, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1153/4000 [10:57<31:22,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.110072612762451, Predicted Probability: 0.8919, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.375813007354736, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1154/4000 [10:58<28:18,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.682816505432129, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.441591739654541, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1155/4000 [10:58<30:44,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3309872150421143, Predicted Probability: 0.0345, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.457359313964844, Predicted Probability: 0.9885, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1156/4000 [10:59<31:45,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.600297927856445, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2993202209472656, Predicted Probability: 0.9088, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1157/4000 [10:59<27:34,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.276741981506348, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.490740776062012, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1158/4000 [11:00<22:10,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.002829551696777, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.527615547180176, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1159/4000 [11:00<25:48,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.371627807617188, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.167849540710449, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1160/4000 [11:01<23:14,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.205984115600586, Predicted Probability: 0.0389, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.248544216156006, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1161/4000 [11:02<28:03,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.461913585662842, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.341567039489746, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1162/4000 [11:02<32:31,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.087146759033203, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.841512680053711, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1163/4000 [11:03<25:40,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.574357032775879, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.363078117370605, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1164/4000 [11:03<28:33,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.352910041809082, Predicted Probability: 0.0127, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.116029977798462, Predicted Probability: 0.0425, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1165/4000 [11:04<30:12,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.097390174865723, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2643256187438965, Predicted Probability: 0.9059, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1166/4000 [11:05<31:23,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.650473117828369, Predicted Probability: 0.0660, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.782359600067139, Predicted Probability: 0.0083, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1167/4000 [11:06<33:28,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.494668006896973, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.13386344909668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1168/4000 [11:06<26:16,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.940436363220215, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.440345764160156, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1169/4000 [11:06<26:09,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.085590124130249, Predicted Probability: 0.8895, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.972631454467773, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1170/4000 [11:07<23:38,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.972400665283203, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.73049259185791, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1171/4000 [11:07<21:42,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3461776077747345, Predicted Probability: 0.4143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.6681342124938965, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1172/4000 [11:08<26:40,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.558263778686523, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.686578273773193, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1173/4000 [11:08<23:55,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.149107933044434, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.94247817993164, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1174/4000 [11:09<27:47,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.381639003753662, Predicted Probability: 0.9154, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.494200706481934, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1175/4000 [11:09<22:22,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.010238647460938, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.183564186096191, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1176/4000 [11:10<26:24,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.629732131958008, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2406015396118164, Predicted Probability: 0.9038, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1177/4000 [11:11<29:19,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.634786605834961, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.198436737060547, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 3/3:  29%|██▉       | 1178/4000 [11:11<26:50,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.968981742858887, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1407939195632935, Predicted Probability: 0.2422, Prediction: 0.0

Epoch 3/3:  29%|██▉       | 1179/4000 [11:12<24:10,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.687205195426941, Predicted Probability: 0.1561, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.12038803100586, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1180/4000 [11:12<19:59,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.972092628479004, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.218138694763184, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1181/4000 [11:12<19:35,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.050128936767578, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.999625205993652, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1182/4000 [11:13<19:49,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.910943984985352, Predicted Probability: 0.9927, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.763598918914795, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1183/4000 [11:14<24:59,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.106128692626953, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.198503494262695, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1184/4000 [11:14<20:31,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.310235023498535, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.660150527954102, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1185/4000 [11:15<24:53,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.759453773498535, Predicted Probability: 0.0596, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.340040683746338, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  30%|██▉       | 1186/4000 [11:15<22:35,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.276202201843262, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.80569076538086, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|██▉       | 1187/4000 [11:15<21:06,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.79545783996582, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7457075119018555, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1188/4000 [11:16<22:37,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.444697380065918, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.113647937774658, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 3/3:  30%|██▉       | 1189/4000 [11:16<23:22,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.230137348175049, Predicted Probability: 0.9857, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.974225044250488, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1190/4000 [11:17<19:18,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.852608680725098, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.585775375366211, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1191/4000 [11:17<23:44,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2123208045959473, Predicted Probability: 0.9014, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.432391166687012, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|██▉       | 1192/4000 [11:18<21:42,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.622901916503906, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.473590850830078, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1193/4000 [11:18<20:15,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.599151134490967, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.700798034667969, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  30%|██▉       | 1194/4000 [11:19<24:21,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.721758842468262, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1305556297302246, Predicted Probability: 0.8938, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1195/4000 [11:19<24:34,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.251205444335938, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.514360427856445, Predicted Probability: 0.9892, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1196/4000 [11:20<27:36,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.322112560272217, Predicted Probability: 0.9869, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.363771438598633, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|██▉       | 1197/4000 [11:20<24:25,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9567785263061523, Predicted Probability: 0.8762, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.206673622131348, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1198/4000 [11:21<22:36,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.028151512145996, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.183247566223145, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  30%|██▉       | 1199/4000 [11:21<23:58,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.163181781768799, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.312563896179199, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  30%|███       | 1200/4000 [11:22<22:01,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.373556137084961, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.75861930847168, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|███       | 1201/4000 [11:22<18:16,  2.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.757616996765137, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.960823059082031, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|███       | 1202/4000 [11:23<20:36,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.885463237762451, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.035975933074951, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  30%|███       | 1203/4000 [11:23<24:32,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.164020538330078, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.813313007354736, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  30%|███       | 1204/4000 [11:24<23:22,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.018013000488281, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.917715549468994, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 3/3:  30%|███       | 1205/4000 [11:24<26:47,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6894301176071167, Predicted Probability: 0.8441, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.470749855041504, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|███       | 1206/4000 [11:25<27:32,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.709278106689453, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8191168308258057, Predicted Probability: 0.9437, Prediction: 1.0

Epoch 3/3:  30%|███       | 1207/4000 [11:26<30:55,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.0678796768188477, Predicted Probability: 0.2558, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.14039134979248, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|███       | 1208/4000 [11:27<32:06,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.237590789794922, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6026766300201416, Predicted Probability: 0.0265, Prediction: 0.0

Epoch 3/3:  30%|███       | 1209/4000 [11:27<27:28,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.320873260498047, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.50571346282959, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|███       | 1210/4000 [11:27<24:20,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.487337350845337, Predicted Probability: 0.0768, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.339848518371582, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|███       | 1211/4000 [11:28<27:38,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7185715436935425, Predicted Probability: 0.8479, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.743507385253906, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|███       | 1212/4000 [11:29<24:49,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.838786125183105, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.724048614501953, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|███       | 1213/4000 [11:29<27:58,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.475569725036621, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.162330627441406, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  30%|███       | 1214/4000 [11:29<22:23,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.728442192077637, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.976778984069824, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  30%|███       | 1215/4000 [11:30<20:56,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.02263069152832, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.490227699279785, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 3/3:  30%|███       | 1216/4000 [11:30<19:44,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.036711692810059, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.898985385894775, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  30%|███       | 1217/4000 [11:31<21:21,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.734064102172852, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3809821605682373, Predicted Probability: 0.9671, Prediction: 1.0

Epoch 3/3:  30%|███       | 1218/4000 [11:32<25:28,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.705094575881958, Predicted Probability: 0.8462, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.607457160949707, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  30%|███       | 1220/4000 [11:32<19:29,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.459918022155762, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.008953094482422, Predicted Probability: 0.9822, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 8.4857816696167, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.718396186828613, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  31%|███       | 1221/4000 [11:33<21:03,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.255340576171875, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.071687698364258, Predicted Probability: 0.9557, Prediction: 1.0

Epoch 3/3:  31%|███       | 1222/4000 [11:33<19:50,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.250885009765625, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.168439865112305, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  31%|███       | 1223/4000 [11:34<24:27,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1617250442504883, Predicted Probability: 0.8968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.552068710327148, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  31%|███       | 1224/4000 [11:34<22:37,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.142643928527832, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.562947273254395, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  31%|███       | 1225/4000 [11:35<26:16,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.009283065795898, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0318708419799805, Predicted Probability: 0.7373, Prediction: 1.0

Epoch 3/3:  31%|███       | 1226/4000 [11:36<29:20,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.897390365600586, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.496051788330078, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  31%|███       | 1227/4000 [11:37<31:04,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.906317234039307, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.507847785949707, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  31%|███       | 1228/4000 [11:37<32:40,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.420981407165527, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.275614738464355, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  31%|███       | 1229/4000 [11:38<25:49,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.909592628479004, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.337179183959961, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  31%|███       | 1230/4000 [11:38<28:29,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.803949356079102, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4634841680526733, Predicted Probability: 0.1879, Prediction: 0.0

Epoch 3/3:  31%|███       | 1231/4000 [11:39<25:02,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.330986976623535, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.400757789611816, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  31%|███       | 1232/4000 [11:39<20:32,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.7276611328125, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.84309196472168, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  31%|███       | 1233/4000 [11:39<21:51,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.231813430786133, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.905951976776123, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 3/3:  31%|███       | 1235/4000 [11:40<18:53,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.89495325088501, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.698760032653809, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -7.408896446228027, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.41276216506958, Predicted Probability: 0.0822, Prediction: 0.0

Epoch 3/3:  31%|███       | 1236/4000 [11:41<23:33,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8845558166503906, Predicted Probability: 0.0201, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5094110369682312, Predicted Probability: 0.6247, Prediction: 1.0

Epoch 3/3:  31%|███       | 1237/4000 [11:41<21:39,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.305910110473633, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.087272644042969, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  31%|███       | 1238/4000 [11:42<25:36,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.2119855880737305, Predicted Probability: 0.0054, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9226608276367188, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 3/3:  31%|███       | 1240/4000 [11:43<23:05,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.869956970214844, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6275672912597656, Predicted Probability: 0.0674, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.172968864440918, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.470725059509277, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  31%|███       | 1241/4000 [11:43<21:14,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.842259407043457, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.900686740875244, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  31%|███       | 1242/4000 [11:44<25:00,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.013824462890625, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.310260534286499, Predicted Probability: 0.0903, Prediction: 0.0

Epoch 3/3:  31%|███       | 1243/4000 [11:45<24:54,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.344350814819336, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9199609756469727, Predicted Probability: 0.9805, Prediction: 1.0

Epoch 3/3:  31%|███       | 1244/4000 [11:45<27:36,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.969139575958252, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.042072296142578, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  31%|███       | 1245/4000 [11:46<29:11,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.233125686645508, Predicted Probability: 0.9032, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.14233660697937, Predicted Probability: 0.1050, Prediction: 0.0

Epoch 3/3:  31%|███       | 1246/4000 [11:46<23:20,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.931132316589355, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.760266304016113, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  31%|███       | 1247/4000 [11:47<26:43,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.376154899597168, Predicted Probability: 0.0124, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4769442081451416, Predicted Probability: 0.0300, Prediction: 0.0

Epoch 3/3:  31%|███       | 1248/4000 [11:47<24:01,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.43112850189209, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.046387672424316, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  31%|███       | 1249/4000 [11:48<27:01,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.346146583557129, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.271648406982422, Predicted Probability: 0.9862, Prediction: 1.0

Epoch 3/3:  31%|███▏      | 1250/4000 [11:48<21:41,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.702486038208008, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.109075546264648, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  31%|███▏      | 1251/4000 [11:49<25:11,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.389410018920898, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4220877885818481, Predicted Probability: 0.1943, Prediction: 0.0

Epoch 3/3:  31%|███▏      | 1252/4000 [11:50<27:57,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.77282977104187, Predicted Probability: 0.9412, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.553934097290039, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  31%|███▏      | 1253/4000 [11:50<25:39,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.22948169708252, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.02605152130127, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  31%|███▏      | 1254/4000 [11:51<25:20,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.350464820861816, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.527041912078857, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 3/3:  31%|███▏      | 1255/4000 [11:52<28:24,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2677292823791504, Predicted Probability: 0.9062, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.052068710327148, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  31%|███▏      | 1256/4000 [11:52<22:41,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.16358757019043, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.435696601867676, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  31%|███▏      | 1257/4000 [11:53<25:31,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.63439679145813, Predicted Probability: 0.0670, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5792945623397827, Predicted Probability: 0.6409, Prediction: 1.0

Epoch 3/3:  31%|███▏      | 1258/4000 [11:53<27:52,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4338319301605225, Predicted Probability: 0.9194, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.80506706237793, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  31%|███▏      | 1259/4000 [11:54<22:22,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.180027961730957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.336814880371094, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1260/4000 [11:54<18:32,  2.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.860628128051758, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.062804222106934, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1261/4000 [11:54<17:59,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.234525203704834, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.49005126953125, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1262/4000 [11:55<23:35,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.00610065460205, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.409831523895264, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1263/4000 [11:56<26:19,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.318887710571289, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3628504276275635, Predicted Probability: 0.9140, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1264/4000 [11:56<29:40,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.322802543640137, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.208061218261719, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1265/4000 [11:57<31:01,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.056041717529297, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.46673572063446045, Predicted Probability: 0.3854, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1266/4000 [11:58<31:55,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.493758887052536, Predicted Probability: 0.3790, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.916971206665039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1267/4000 [11:59<33:08,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9881067276000977, Predicted Probability: 0.9520, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.685770034790039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1268/4000 [11:59<28:27,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.815512657165527, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.83377456665039, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1269/4000 [12:00<27:11,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.595137596130371, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.634886264801025, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1270/4000 [12:00<23:59,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4929022789001465, Predicted Probability: 0.9889, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.774317741394043, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1271/4000 [12:01<27:54,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.856281280517578, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.697094917297363, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1272/4000 [12:02<30:18,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.146939277648926, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.031866073608398, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1273/4000 [12:02<32:12,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.38734769821167, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.103006362915039, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1274/4000 [12:03<30:06,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.461990356445312, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.197307586669922, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1275/4000 [12:04<31:21,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.147497653961182, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.631326675415039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1276/4000 [12:04<27:53,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.021319389343262, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.773497104644775, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1277/4000 [12:05<26:52,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.0702338218688965, Predicted Probability: 0.9832, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.61375904083252, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1278/4000 [12:05<26:18,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.771317481994629, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.689030170440674, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1279/4000 [12:06<29:36,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.253089904785156, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.416601181030273, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1280/4000 [12:07<31:23,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.897489547729492, Predicted Probability: 0.9801, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.1419677734375, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1281/4000 [12:07<29:21,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.601259231567383, Predicted Probability: 0.0037, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.038186073303223, Predicted Probability: 0.0173, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1282/4000 [12:08<30:22,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.590093612670898, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2996602058410645, Predicted Probability: 0.9088, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1283/4000 [12:09<31:22,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.008113861083984, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.040463924407959, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1284/4000 [12:09<27:00,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.003291130065918, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.882608413696289, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1285/4000 [12:10<26:18,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.910902976989746, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.191224575042725, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1286/4000 [12:10<21:10,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.557939529418945, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.859439849853516, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1287/4000 [12:11<26:34,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4494776725769043, Predicted Probability: 0.0795, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.468125820159912, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1288/4000 [12:11<23:40,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.432894229888916, Predicted Probability: 0.9956, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.928778648376465, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1289/4000 [12:12<27:56,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.542951583862305, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.472987174987793, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1290/4000 [12:12<22:22,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.386556625366211, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.460833549499512, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1291/4000 [12:13<25:44,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7576904296875, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.014074325561523, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1292/4000 [12:13<20:44,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.1509370803833, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.88104248046875, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1293/4000 [12:14<19:34,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.70316219329834, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.978438854217529, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1294/4000 [12:14<23:22,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.112260818481445, Predicted Probability: 0.9839, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.301477432250977, Predicted Probability: 0.0050, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1295/4000 [12:15<21:23,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.721742630004883, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.325610160827637, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1296/4000 [12:15<20:05,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.8506879806518555, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.4069504737854, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  32%|███▏      | 1297/4000 [12:15<19:04,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.735641479492188, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.895153045654297, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1298/4000 [12:16<19:12,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.589498519897461, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.362656831741333, Predicted Probability: 0.9665, Prediction: 1.0

Epoch 3/3:  32%|███▏      | 1299/4000 [12:17<24:26,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.760927200317383, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.86954116821289, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  32%|███▎      | 1300/4000 [12:17<27:14,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.373170852661133, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.161710262298584, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1301/4000 [12:18<24:01,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.588244438171387, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.037249565124512, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1302/4000 [12:18<20:25,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.010428428649902, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.771465301513672, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1303/4000 [12:18<19:36,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.93043041229248, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.908965110778809, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1304/4000 [12:19<23:23,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.347983360290527, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2161030769348145, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1305/4000 [12:20<26:38,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.3256866931915283, Predicted Probability: 0.9110, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.144269943237305, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1306/4000 [12:20<24:05,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.621788024902344, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.332825660705566, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1307/4000 [12:21<27:08,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.294036865234375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2254397869110107, Predicted Probability: 0.9025, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1308/4000 [12:22<29:56,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.414907455444336, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.557353973388672, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1310/4000 [12:23<21:28,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4996981620788574, Predicted Probability: 0.9241, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.844773292541504, Predicted Probability: 0.9996, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.97423267364502, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.455402374267578, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1311/4000 [12:23<17:43,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.273017883300781, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.269570350646973, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1312/4000 [12:24<22:16,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.0364990234375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.854944229125977, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1313/4000 [12:24<20:31,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.843818187713623, Predicted Probability: 0.9790, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.054960250854492, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1314/4000 [12:25<25:43,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.569391250610352, Predicted Probability: 0.0103, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.949422836303711, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1315/4000 [12:26<28:27,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.444699287414551, Predicted Probability: 0.9202, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.800776481628418, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1316/4000 [12:26<30:09,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9787936210632324, Predicted Probability: 0.9816, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4109444618225098, Predicted Probability: 0.0320, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1317/4000 [12:27<26:56,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.655027389526367, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.556550025939941, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1318/4000 [12:27<28:29,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.145621299743652, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.634406328201294, Predicted Probability: 0.9330, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1319/4000 [12:28<29:53,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.55563497543335, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.083614349365234, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1320/4000 [12:29<28:16,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.59189224243164, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.978257417678833, Predicted Probability: 0.0184, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1321/4000 [12:29<27:01,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.550444602966309, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6340134143829346, Predicted Probability: 0.9743, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1322/4000 [12:30<24:19,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.131942749023438, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.919384956359863, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1323/4000 [12:30<24:30,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.722296714782715, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.671163558959961, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1324/4000 [12:31<22:23,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.293582916259766, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.708202362060547, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1325/4000 [12:31<25:29,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5952474474906921, Predicted Probability: 0.6446, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.90034294128418, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1326/4000 [12:32<22:50,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.038511276245117, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.549383640289307, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1327/4000 [12:33<26:15,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.86439323425293, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8506908416748047, Predicted Probability: 0.0208, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1328/4000 [12:33<27:56,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.7826361656188965, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.138397216796875, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1329/4000 [12:33<22:15,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.374017715454102, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.863710403442383, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1330/4000 [12:34<25:53,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.752205848693848, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0779805183410645, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1331/4000 [12:35<23:09,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.825608253479004, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3494133949279785, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1332/4000 [12:35<21:08,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.94705057144165, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.306946754455566, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1333/4000 [12:35<21:59,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.277999877929688, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.760833740234375, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 3/3:  33%|███▎      | 1334/4000 [12:36<25:46,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.160935401916504, Predicted Probability: 0.8967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.907541275024414, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1335/4000 [12:37<23:17,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.504526138305664, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.74480676651001, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1336/4000 [12:37<26:27,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.881159782409668, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.858396530151367, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1337/4000 [12:38<28:11,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.294451951980591, Predicted Probability: 0.9084, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.698572158813477, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1338/4000 [12:39<30:37,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.460556030273438, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.572286605834961, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  33%|███▎      | 1339/4000 [12:39<26:31,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: -5.476235389709473, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.543743133544922, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1340/4000 [12:40<25:45,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7967143058776855, Predicted Probability: 0.9780, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.364844799041748, Predicted Probability: 0.9953, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1342/4000 [12:40<18:39,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.890185356140137, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.54525375366211, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.983053207397461, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.893169403076172, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1343/4000 [12:41<15:52,  2.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.189799308776855, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.2514009475708, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1344/4000 [12:41<21:01,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.366244316101074, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7037298679351807, Predicted Probability: 0.9372, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1345/4000 [12:42<25:04,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.240825653076172, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.635686874389648, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  34%|███▎      | 1346/4000 [12:43<26:47,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.144560813903809, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.79516339302063, Predicted Probability: 0.9424, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1347/4000 [12:43<23:39,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.10175895690918, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.164337158203125, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  34%|███▎      | 1348/4000 [12:44<26:19,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.481532096862793, Predicted Probability: 0.0298, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.465189218521118, Predicted Probability: 0.9217, Prediction: 1.0

Epoch 3/3:  34%|███▎      | 1349/4000 [12:45<28:25,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6824142932891846, Predicted Probability: 0.9360, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.005582809448242, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1350/4000 [12:46<31:28,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.477517127990723, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.514147758483887, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1351/4000 [12:46<27:14,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.166574478149414, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.603279113769531, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1352/4000 [12:46<24:21,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.744001388549805, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.066291809082031, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1353/4000 [12:47<19:51,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.229612350463867, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.826272964477539, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1354/4000 [12:47<23:56,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.734314918518066, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.059678554534912, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1355/4000 [12:48<22:44,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.652419090270996, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6771066188812256, Predicted Probability: 0.0247, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1356/4000 [12:49<25:37,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.601984024047852, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3565633296966553, Predicted Probability: 0.0337, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1357/4000 [12:49<28:07,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1138510704040527, Predicted Probability: 0.0425, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.0579752922058105, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1358/4000 [12:50<29:46,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.827169418334961, Predicted Probability: 0.0079, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5984556674957275, Predicted Probability: 0.0692, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1359/4000 [12:51<30:33,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.786139011383057, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.340467929840088, Predicted Probability: 0.9122, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1360/4000 [12:52<31:30,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.690812349319458, Predicted Probability: 0.9365, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.427148818969727, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1361/4000 [12:52<24:44,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.556364059448242, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.943584442138672, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1362/4000 [12:53<27:16,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.576329231262207, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5749895572662354, Predicted Probability: 0.9292, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1363/4000 [12:53<29:12,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.452981948852539, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.819939613342285, Predicted Probability: 0.9437, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1364/4000 [12:54<26:19,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.434288024902344, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.496838569641113, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1365/4000 [12:55<28:59,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.171440124511719, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3805413246154785, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1366/4000 [12:55<31:00,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.238936901092529, Predicted Probability: 0.9947, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.736468315124512, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1367/4000 [12:56<31:13,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.855341672897339, Predicted Probability: 0.9456, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.377937078475952, Predicted Probability: 0.0330, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1368/4000 [12:57<31:15,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5570435523986816, Predicted Probability: 0.9280, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.287273406982422, Predicted Probability: 0.0136, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1369/4000 [12:58<31:22,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4690401554107666, Predicted Probability: 0.0781, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8274123668670654, Predicted Probability: 0.9441, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1370/4000 [12:58<29:16,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.654852390289307, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.795655250549316, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1371/4000 [12:58<25:22,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.452800750732422, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.158272743225098, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1372/4000 [12:59<24:50,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.463722229003906, Predicted Probability: 0.9886, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.25877571105957, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1373/4000 [12:59<23:10,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.093687057495117, Predicted Probability: 0.9836, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.796062469482422, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1374/4000 [13:00<20:59,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.9276003241539001, Predicted Probability: 0.7166, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.481564998626709, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1375/4000 [13:00<19:34,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.696950912475586, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.286709785461426, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1376/4000 [13:01<23:19,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2506178617477417, Predicted Probability: 0.2226, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.332652568817139, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1377/4000 [13:01<22:06,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.597585439682007, Predicted Probability: 0.9733, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.584429740905762, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1378/4000 [13:02<22:47,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.746936798095703, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.3970184326171875, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  34%|███▍      | 1379/4000 [13:02<20:49,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.526082992553711, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.692880630493164, Predicted Probability: 0.0243, Prediction: 0.0

Epoch 3/3:  34%|███▍      | 1380/4000 [13:03<25:32,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.138711452484131, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.175725936889648, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1381/4000 [13:04<27:37,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7353873252868652, Predicted Probability: 0.9391, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.872371673583984, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1382/4000 [13:04<24:28,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.569296836853027, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.605090141296387, Predicted Probability: 0.0037, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1383/4000 [13:05<28:47,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.784259796142578, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.163022994995117, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1384/4000 [13:06<30:19,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.433408737182617, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0934102535247803, Predicted Probability: 0.1097, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1385/4000 [13:06<26:06,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.562984943389893, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.835378646850586, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1386/4000 [13:07<23:07,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.27745246887207, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.832452774047852, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1387/4000 [13:07<26:26,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.236411094665527, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.026655197143555, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1388/4000 [13:08<28:20,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.983691215515137, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.838812828063965, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1389/4000 [13:09<24:32,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.9564127922058105, Predicted Probability: 0.0494, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.657953262329102, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1390/4000 [13:09<27:34,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.156794548034668, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.171014785766602, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1391/4000 [13:10<26:16,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.879167556762695, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9160423278808594, Predicted Probability: 0.0514, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1392/4000 [13:10<23:12,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.277820110321045, Predicted Probability: 0.9863, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.802691459655762, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1393/4000 [13:11<18:57,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.651348114013672, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.300082206726074, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1394/4000 [13:11<22:52,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.668577194213867, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.246520042419434, Predicted Probability: 0.9948, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1395/4000 [13:11<18:42,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.322107315063477, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.315912246704102, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1396/4000 [13:12<16:32,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.781851768493652, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.58505630493164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1397/4000 [13:13<21:52,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.752872467041016, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.079797744750977, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  35%|███▍      | 1398/4000 [13:13<24:41,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.112576484680176, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.456520080566406, Predicted Probability: 0.9885, Prediction: 1.0

Epoch 3/3:  35%|███▍      | 1399/4000 [13:14<22:12,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.810748100280762, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.200956344604492, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1400/4000 [13:14<20:20,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.208761215209961, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.737606048583984, Predicted Probability: 0.0087, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1401/4000 [13:15<24:19,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.555846214294434, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4268910884857178, Predicted Probability: 0.9189, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1402/4000 [13:16<27:32,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.588849067687988, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.323026657104492, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1403/4000 [13:16<29:25,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.270974636077881, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.929070949554443, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1404/4000 [13:17<25:23,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.250280380249023, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.345353126525879, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1405/4000 [13:17<22:25,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.29426908493042, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.901453971862793, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1406/4000 [13:17<20:31,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.073673248291016, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.050389289855957, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1407/4000 [13:18<19:12,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.672948360443115, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.35193157196045, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1408/4000 [13:18<19:22,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.63202953338623, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.807113647460938, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1409/4000 [13:19<20:30,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.087563514709473, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5604844093322754, Predicted Probability: 0.0276, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1411/4000 [13:20<17:32,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.933577537536621, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5041611194610596, Predicted Probability: 0.9708, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -10.181934356689453, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.965134620666504, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1412/4000 [13:20<17:00,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.231860160827637, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.111390113830566, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1413/4000 [13:21<21:28,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.879803657531738, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.992414474487305, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1414/4000 [13:21<21:03,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.137900352478027, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.374225616455078, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1415/4000 [13:22<24:05,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4770443439483643, Predicted Probability: 0.9225, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.707523345947266, Predicted Probability: 0.0089, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1416/4000 [13:22<21:40,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.936513900756836, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.469375133514404, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1417/4000 [13:23<20:00,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.30142593383789, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.502065181732178, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  35%|███▌      | 1418/4000 [13:23<23:26,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8717455863952637, Predicted Probability: 0.9464, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.625709533691406, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  35%|███▌      | 1419/4000 [13:24<25:44,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.757366180419922, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.873905658721924, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1420/4000 [13:25<27:32,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6553544998168945, Predicted Probability: 0.0657, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.222906112670898, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1421/4000 [13:25<26:23,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.669595718383789, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.642436981201172, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1422/4000 [13:26<28:08,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.487857818603516, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6699392795562744, Predicted Probability: 0.1584, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1423/4000 [13:27<29:49,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.081957817077637, Predicted Probability: 0.9938, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.952174186706543, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1424/4000 [13:27<25:32,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.5819730758667, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.620283603668213, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1425/4000 [13:28<27:11,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.42216682434082, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8342814445495605, Predicted Probability: 0.1377, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1426/4000 [13:29<28:32,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.646846294403076, Predicted Probability: 0.9905, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.582412242889404, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1427/4000 [13:29<24:50,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.729014873504639, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.682005882263184, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1428/4000 [13:30<26:29,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.426030158996582, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.984496593475342, Predicted Probability: 0.9519, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1429/4000 [13:30<21:13,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.67133903503418, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.153799057006836, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1430/4000 [13:31<24:20,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.51169490814209, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4893476963043213, Predicted Probability: 0.9234, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1431/4000 [13:32<27:08,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.433968544006348, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6875452995300293, Predicted Probability: 0.9363, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1432/4000 [13:32<25:50,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.236508369445801, Predicted Probability: 0.0143, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.949729919433594, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1433/4000 [13:33<23:46,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.08268928527832, Predicted Probability: 0.0062, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.323431015014648, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1434/4000 [13:33<21:24,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.1144914627075195, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.457898139953613, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1435/4000 [13:34<24:48,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.482490062713623, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.608390808105469, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1436/4000 [13:34<27:23,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.729935646057129, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0026116371154785, Predicted Probability: 0.8811, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1437/4000 [13:35<24:52,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.323686122894287, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.372444152832031, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1438/4000 [13:35<22:16,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.3976306915283203, Predicted Probability: 0.0324, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.180945873260498, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1439/4000 [13:36<24:48,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.342991352081299, Predicted Probability: 0.9124, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.392094612121582, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1440/4000 [13:37<26:34,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.148943901062012, Predicted Probability: 0.9845, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.105406761169434, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1442/4000 [13:37<20:32,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.086315155029297, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7675089836120605, Predicted Probability: 0.9996, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.16773509979248, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.034003257751465, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1443/4000 [13:38<24:25,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.479874610900879, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.355142593383789, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1444/4000 [13:39<28:24,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4335036277771, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.988780975341797, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1445/4000 [13:40<30:33,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5785763263702393, Predicted Probability: 0.9295, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.639007568359375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1446/4000 [13:40<26:08,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.901820182800293, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.26706600189209, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1447/4000 [13:41<23:13,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.877911567687988, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.617051124572754, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  36%|███▌      | 1448/4000 [13:41<21:17,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.255669593811035, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.775763511657715, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  36%|███▌      | 1449/4000 [13:42<21:50,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.342241287231445, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.457934379577637, Predicted Probability: 0.9885, Prediction: 1.0

Epoch 3/3:  36%|███▋      | 1450/4000 [13:42<24:32,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.889128684997559, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.961257219314575, Predicted Probability: 0.9508, Prediction: 1.0

Epoch 3/3:  36%|███▋      | 1451/4000 [13:43<21:46,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.286444664001465, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.33961009979248, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  36%|███▋      | 1452/4000 [13:43<24:32,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.829571723937988, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8209607601165771, Predicted Probability: 0.8607, Prediction: 1.0

Epoch 3/3:  36%|███▋      | 1453/4000 [13:44<26:37,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.480765342712402, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6311469078063965, Predicted Probability: 0.9328, Prediction: 1.0

Epoch 3/3:  36%|███▋      | 1454/4000 [13:44<21:14,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.102869987487793, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.76118278503418, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▋      | 1455/4000 [13:45<25:23,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.362081527709961, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.605090618133545, Predicted Probability: 0.0099, Prediction: 0.0

Epoch 3/3:  36%|███▋      | 1456/4000 [13:46<29:26,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.809370040893555, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.200000762939453, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  36%|███▋      | 1457/4000 [13:47<25:34,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.277012825012207, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.854126453399658, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  36%|███▋      | 1458/4000 [13:47<28:01,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.122881889343262, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.985578536987305, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▋      | 1459/4000 [13:48<22:20,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.345525741577148, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.511899948120117, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  36%|███▋      | 1460/4000 [13:48<24:38,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.092660665512085, Predicted Probability: 0.8902, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.656440734863281, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1461/4000 [13:49<27:06,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.399227142333984, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.069340705871582, Predicted Probability: 0.9556, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1462/4000 [13:49<22:32,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.804669380187988, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.073873519897461, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1463/4000 [13:50<25:20,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2202987670898438, Predicted Probability: 0.0384, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.573129415512085, Predicted Probability: 0.6395, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1464/4000 [13:51<27:18,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.970329284667969, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.863094806671143, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1465/4000 [13:52<29:13,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.374718189239502, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.925788640975952, Predicted Probability: 0.0193, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1466/4000 [13:52<25:08,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.388185501098633, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.572368144989014, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1467/4000 [13:53<26:55,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.10549259185791, Predicted Probability: 0.9838, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.637146949768066, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1468/4000 [13:53<26:48,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.509268760681152, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.310482025146484, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1469/4000 [13:54<21:27,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.216804504394531, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.289108276367188, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1470/4000 [13:54<17:34,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.094021797180176, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.432377815246582, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1471/4000 [13:55<21:30,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.23611307144165, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.25692081451416, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1472/4000 [13:55<24:15,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.633794784545898, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.184852361679077, Predicted Probability: 0.8989, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1473/4000 [13:56<26:19,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.91226577758789, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.734001636505127, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1474/4000 [13:57<25:23,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.271000623703003, Predicted Probability: 0.9634, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.392646789550781, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1475/4000 [13:57<24:38,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.273439407348633, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.035930633544922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.848779678344727, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.6522798538208, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1477/4000 [13:58<16:21,  2.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.685004234313965, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.02500057220459, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1478/4000 [13:58<23:17,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.619378089904785, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.553821563720703, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1479/4000 [13:59<26:25,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.694207668304443, Predicted Probability: 0.9909, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.291372299194336, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1480/4000 [14:00<28:02,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.912421941757202, Predicted Probability: 0.9485, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.435563087463379, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1481/4000 [14:00<22:11,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.279800891876221, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0015807151794434, Predicted Probability: 0.0474, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1482/4000 [14:01<20:06,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.991637229919434, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.403368949890137, Predicted Probability: 0.9879, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1483/4000 [14:01<18:48,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.401168823242188, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7026472091674805, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1484/4000 [14:02<22:35,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.4852294921875, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.694235324859619, Predicted Probability: 0.9367, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1485/4000 [14:02<24:57,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.943161010742188, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0080885887146, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1486/4000 [14:03<21:59,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.180578231811523, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5822954177856445, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1487/4000 [14:03<20:15,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.949237823486328, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.51759147644043, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1488/4000 [14:04<21:02,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.930032253265381, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.487610101699829, Predicted Probability: 0.9703, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1489/4000 [14:04<18:06,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.8591890335083, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.461405277252197, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1490/4000 [14:05<21:49,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.507499694824219, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0230824947357178, Predicted Probability: 0.2644, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1491/4000 [14:05<20:44,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.9002280235290527, Predicted Probability: 0.1301, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.885068893432617, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1492/4000 [14:06<19:20,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.992805480957031, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.136723518371582, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1493/4000 [14:06<21:16,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.122034788131714, Predicted Probability: 0.9578, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.538363456726074, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1494/4000 [14:07<25:18,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.105598449707031, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.781516075134277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1495/4000 [14:08<24:22,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.046445846557617, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.120162963867188, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1496/4000 [14:08<26:06,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.671566009521484, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.567963600158691, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  37%|███▋      | 1497/4000 [14:09<27:35,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.553908824920654, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.930769443511963, Predicted Probability: 0.0193, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1498/4000 [14:10<28:46,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.104427814483643, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.512076377868652, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  37%|███▋      | 1499/4000 [14:10<29:24,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.449676513671875, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.033997535705566, Predicted Probability: 0.9826, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1500/4000 [14:11<27:19,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.330575942993164, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.803304195404053, Predicted Probability: 0.9919, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1501/4000 [14:12<26:05,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.509336471557617, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.472810745239258, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1502/4000 [14:12<23:05,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.13320541381836, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6308794021606445, Predicted Probability: 0.0672, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1503/4000 [14:13<25:26,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.741302728652954, Predicted Probability: 0.9394, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.574350357055664, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1504/4000 [14:13<27:18,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.700750827789307, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1670002937316895, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1505/4000 [14:14<23:43,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.88004207611084, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.615274429321289, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1506/4000 [14:14<24:05,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6598429679870605, Predicted Probability: 0.9749, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.429905891418457, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1507/4000 [14:15<27:12,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5405733585357666, Predicted Probability: 0.1765, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.553356170654297, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1508/4000 [14:16<23:45,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.583339214324951, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.682902336120605, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1509/4000 [14:16<19:10,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.85760498046875, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.83059310913086, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1510/4000 [14:16<20:07,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8043298721313477, Predicted Probability: 0.0218, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.473308563232422, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1511/4000 [14:17<20:54,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.14899730682373, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.0735502243042, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1512/4000 [14:18<23:27,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.329986572265625, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8780581951141357, Predicted Probability: 0.9468, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1513/4000 [14:18<18:56,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.932965278625488, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.947942733764648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1514/4000 [14:19<22:18,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.02593731880188, Predicted Probability: 0.9537, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.734370231628418, Predicted Probability: 0.0032, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1515/4000 [14:19<20:10,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.098272323608398, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.743467330932617, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1516/4000 [14:19<18:41,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.198776245117188, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.423676013946533, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1517/4000 [14:20<23:01,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.471246719360352, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.789495468139648, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1518/4000 [14:21<20:39,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.4286980628967285, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.38953971862793, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1519/4000 [14:21<24:14,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.749250411987305, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.366718292236328, Predicted Probability: 0.9875, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1520/4000 [14:22<26:03,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2879812717437744, Predicted Probability: 0.9079, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.802515029907227, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1521/4000 [14:23<28:08,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.451791763305664, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.238726615905762, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1522/4000 [14:23<25:21,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.531499862670898, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.773118019104004, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1523/4000 [14:23<20:14,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.650897979736328, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.128480911254883, Predicted Probability: 0.0059, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1524/4000 [14:24<16:40,  2.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.32925033569336, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.07455587387084961, Predicted Probability: 0.4814, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1525/4000 [14:24<20:40,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.007814407348633, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.695587635040283, Predicted Probability: 0.9368, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1526/4000 [14:25<24:31,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.612502574920654, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.90542984008789, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1527/4000 [14:26<23:57,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.734199523925781, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.731925010681152, Predicted Probability: 0.9913, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1528/4000 [14:27<26:58,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.869359016418457, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.610054016113281, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1529/4000 [14:27<25:52,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.713397026062012, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.533435821533203, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1530/4000 [14:28<27:56,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.315997123718262, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.40869140625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1531/4000 [14:29<29:25,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.201254844665527, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.637904167175293, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1532/4000 [14:30<29:50,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.541367530822754, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4943171739578247, Predicted Probability: 0.8167, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1533/4000 [14:30<30:52,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.05543327331543, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.66846227645874, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1534/4000 [14:31<32:04,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.4974775314331055, Predicted Probability: 0.0110, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.274334907531738, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1535/4000 [14:32<32:38,  1.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.87568473815918, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.838809013366699, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  38%|███▊      | 1536/4000 [14:33<32:16,  1.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.5776753425598145, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.02216911315918, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1537/4000 [14:33<25:58,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4685094356536865, Predicted Probability: 0.9698, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.92799186706543, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1538/4000 [14:33<22:38,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.500640869140625, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.194661140441895, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1539/4000 [14:34<20:20,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.371390342712402, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.42785358428955, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  38%|███▊      | 1540/4000 [14:34<18:45,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.989341974258423, Predicted Probability: 0.9818, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6672940254211426, Predicted Probability: 0.9351, Prediction: 1.0

Epoch 3/3:  39%|███▊      | 1541/4000 [14:35<19:44,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.08752213418483734, Predicted Probability: 0.5219, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.36578369140625, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  39%|███▊      | 1542/4000 [14:35<20:34,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.420297622680664, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2526695728302, Predicted Probability: 0.9049, Prediction: 1.0

Epoch 3/3:  39%|███▊      | 1543/4000 [14:36<18:47,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.252718448638916, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.904393196105957, Predicted Probability: 0.9926, Prediction: 1.0

Epoch 3/3:  39%|███▊      | 1544/4000 [14:36<22:21,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0660524368286133, Predicted Probability: 0.1124, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.588287353515625, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  39%|███▊      | 1545/4000 [14:37<20:14,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8302202224731445, Predicted Probability: 0.1382, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.665862560272217, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  39%|███▊      | 1546/4000 [14:38<24:37,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.022705078125, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.56547737121582, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▊      | 1547/4000 [14:38<26:25,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9862323999404907, Predicted Probability: 0.1207, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.665616989135742, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  39%|███▊      | 1548/4000 [14:39<28:02,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5993943214416504, Predicted Probability: 0.1681, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.51888370513916, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▊      | 1549/4000 [14:40<25:10,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.90761661529541, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.994345664978027, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1550/4000 [14:40<22:08,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.176389694213867, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.076200008392334, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1551/4000 [14:41<24:49,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.714179992675781, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9577841758728027, Predicted Probability: 0.9506, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1552/4000 [14:41<21:58,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.371769905090332, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.37891674041748, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1553/4000 [14:42<24:58,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.202974319458008, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.992815017700195, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1554/4000 [14:42<24:03,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.498896598815918, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.764822483062744, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1555/4000 [14:43<21:22,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.668551445007324, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.904855728149414, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1556/4000 [14:43<20:21,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.230823040008545, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.487832546234131, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1558/4000 [14:44<17:16,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.840051651000977, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.055711269378662, Predicted Probability: 0.9991, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.436214447021484, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.711252212524414, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1559/4000 [14:45<18:45,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.127304077148438, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4677456617355347, Predicted Probability: 0.1873, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1560/4000 [14:45<17:48,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.078150749206543, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.747740745544434, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1561/4000 [14:45<17:04,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.18727970123291, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.343684196472168, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1562/4000 [14:46<15:13,  2.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.75987434387207, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.415237426757812, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1563/4000 [14:46<15:12,  2.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.944841384887695, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2646093368530273, Predicted Probability: 0.9632, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1564/4000 [14:46<17:23,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.866082191467285, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.16726303100586, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1565/4000 [14:47<14:38,  2.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.464707374572754, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.786986351013184, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1566/4000 [14:47<19:35,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.200385093688965, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.597576141357422, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1567/4000 [14:48<18:35,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.519798278808594, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.270084381103516, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1568/4000 [14:48<17:27,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7627763748168945, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.495454788208008, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1569/4000 [14:49<22:06,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.458925247192383, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.596254348754883, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1570/4000 [14:50<25:20,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.824932098388672, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.92708683013916, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1571/4000 [14:50<23:13,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.258246421813965, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.362007141113281, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1572/4000 [14:51<25:48,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.665670394897461, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.601570129394531, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1573/4000 [14:52<27:47,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.619499206542969, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.954558849334717, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1574/4000 [14:52<21:57,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.246980667114258, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.065701484680176, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  39%|███▉      | 1575/4000 [14:53<22:00,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.348816871643066, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.797537803649902, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1576/4000 [14:53<24:42,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.43925666809082, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.733042240142822, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1577/4000 [14:54<21:56,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.555906295776367, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.966867446899414, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1578/4000 [14:54<19:51,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.702541351318359, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.53547191619873, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  39%|███▉      | 1579/4000 [14:55<18:25,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.782618522644043, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.300490856170654, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  40%|███▉      | 1580/4000 [14:55<21:50,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.077075958251953, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7303653955459595, Predicted Probability: 0.8495, Prediction: 1.0

Epoch 3/3:  40%|███▉      | 1581/4000 [14:56<19:46,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.08992862701416, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.631897926330566, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  40%|███▉      | 1582/4000 [14:56<23:14,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.749841690063477, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.664142608642578, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1583/4000 [14:57<25:17,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.5536820888519287, Predicted Probability: 0.3650, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.512099266052246, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1584/4000 [14:58<26:25,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6510343551635742, Predicted Probability: 0.1610, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.815574645996094, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1585/4000 [14:58<24:57,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.146657943725586, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.7479050159454346, Predicted Probability: 0.0602, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1586/4000 [14:59<21:53,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.133905410766602, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.672557830810547, Predicted Probability: 0.0034, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1587/4000 [15:00<24:04,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.181956768035889, Predicted Probability: 0.0150, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.116066932678223, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1588/4000 [15:00<26:02,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.805052280426025, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.311809539794922, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1589/4000 [15:01<22:57,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.071404457092285, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.42934513092041, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  40%|███▉      | 1590/4000 [15:01<20:41,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.441954612731934, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.689906120300293, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  40%|███▉      | 1591/4000 [15:02<23:12,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.806613445281982, Predicted Probability: 0.0081, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.814471244812012, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1592/4000 [15:02<20:50,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.821196556091309, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.67061710357666, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1593/4000 [15:03<19:01,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.0930304527282715, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.547293663024902, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1594/4000 [15:03<23:29,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.416353225708008, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.674362182617188, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1595/4000 [15:04<25:22,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.116179943084717, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.408018112182617, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1596/4000 [15:05<24:34,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.322839736938477, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.76042366027832, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  40%|███▉      | 1597/4000 [15:06<27:42,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.741447448730469, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.914403915405273, Predicted Probability: 0.0073, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1598/4000 [15:06<29:51,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.877081394195557, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.3947172164917, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|███▉      | 1599/4000 [15:07<28:11,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.306392192840576, Predicted Probability: 0.9867, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.507370948791504, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  40%|████      | 1600/4000 [15:08<28:30,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1946001052856445, Predicted Probability: 0.9606, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.798056602478027, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  40%|████      | 1601/4000 [15:08<24:27,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.470676898956299, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.664071083068848, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  40%|████      | 1602/4000 [15:09<25:26,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.171435594558716, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.701763153076172, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  40%|████      | 1603/4000 [15:10<26:40,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.510808944702148, Predicted Probability: 0.9891, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.188831329345703, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  40%|████      | 1604/4000 [15:10<27:23,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.133894443511963, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.484821319580078, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  40%|████      | 1605/4000 [15:11<27:44,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2110469341278076, Predicted Probability: 0.9612, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.506237030029297, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|████      | 1606/4000 [15:12<29:14,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.324970245361328, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.971271514892578, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|████      | 1607/4000 [15:13<28:54,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.621809482574463, Predicted Probability: 0.1650, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.015027046203613, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 3/3:  40%|████      | 1608/4000 [15:13<29:42,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3051271438598633, Predicted Probability: 0.0907, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.327604293823242, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|████      | 1609/4000 [15:14<29:47,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.89332389831543, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.41047412157058716, Predicted Probability: 0.3988, Prediction: 0.0

Epoch 3/3:  40%|████      | 1610/4000 [15:14<25:27,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.218111991882324, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.652938842773438, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|████      | 1611/4000 [15:15<22:08,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.716231346130371, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.835416793823242, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  40%|████      | 1612/4000 [15:15<19:59,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.130374908447266, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.595880508422852, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  40%|████      | 1613/4000 [15:16<23:06,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.355306625366211, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.633599281311035, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 3/3:  40%|████      | 1614/4000 [15:17<24:47,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.931432247161865, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.627944946289062, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|████      | 1615/4000 [15:17<26:13,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.047409057617188, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.869783401489258, Predicted Probability: 0.9463, Prediction: 1.0

Epoch 3/3:  40%|████      | 1616/4000 [15:18<27:05,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.607864379882812, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.723245859146118, Predicted Probability: 0.9384, Prediction: 1.0

Epoch 3/3:  40%|████      | 1617/4000 [15:19<23:28,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.407561302185059, Predicted Probability: 0.0045, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.735147476196289, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  40%|████      | 1618/4000 [15:19<21:00,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.489202499389648, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.758079528808594, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  40%|████      | 1619/4000 [15:20<24:49,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.497518539428711, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.534175872802734, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  40%|████      | 1620/4000 [15:21<26:07,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.337661743164062, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.131862163543701, Predicted Probability: 0.0158, Prediction: 0.0

Epoch 3/3:  41%|████      | 1621/4000 [15:21<27:51,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.624361038208008, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.526226043701172, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  41%|████      | 1622/4000 [15:22<21:59,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.723515510559082, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.593472480773926, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  41%|████      | 1623/4000 [15:22<24:37,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.08870792388916, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.163696765899658, Predicted Probability: 0.9594, Prediction: 1.0

Epoch 3/3:  41%|████      | 1624/4000 [15:23<27:04,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.439355850219727, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.266317367553711, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1625/4000 [15:24<28:03,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.054267883300781, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.923599243164062, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1627/4000 [15:24<18:18,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.120986938476562, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.6132173538208, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -10.597528457641602, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.28316593170166, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1628/4000 [15:25<17:05,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.049798965454102, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.712065696716309, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1629/4000 [15:25<20:29,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.815654754638672, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.536940336227417, Predicted Probability: 0.9267, Prediction: 1.0

Epoch 3/3:  41%|████      | 1630/4000 [15:26<16:49,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.265375137329102, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.677932739257812, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  41%|████      | 1631/4000 [15:26<20:59,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.742769241333008, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.512238502502441, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  41%|████      | 1632/4000 [15:27<23:15,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.0591139793396, Predicted Probability: 0.0170, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.298577308654785, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  41%|████      | 1633/4000 [15:28<25:08,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.458710193634033, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.07373046875, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1634/4000 [15:29<26:57,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.182878494262695, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.102954864501953, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  41%|████      | 1635/4000 [15:29<27:58,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.451414108276367, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.857400894165039, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 3/3:  41%|████      | 1636/4000 [15:30<28:12,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.712753295898438, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.997382402420044, Predicted Probability: 0.9820, Prediction: 1.0

Epoch 3/3:  41%|████      | 1637/4000 [15:31<24:15,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.607025623321533, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.86440658569336, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1638/4000 [15:31<23:20,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.646217346191406, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3876495361328125, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:  41%|████      | 1639/4000 [15:32<20:42,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.262824058532715, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.946395874023438, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  41%|████      | 1640/4000 [15:32<19:05,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.509047508239746, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.983789443969727, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  41%|████      | 1641/4000 [15:33<22:03,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3773093223571777, Predicted Probability: 0.9670, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.37878131866455, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████      | 1642/4000 [15:33<24:30,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.506558418273926, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.635362148284912, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  41%|████      | 1643/4000 [15:34<25:41,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.784568786621094, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.845071315765381, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 3/3:  41%|████      | 1644/4000 [15:35<26:49,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.947056770324707, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.160861015319824, Predicted Probability: 0.9593, Prediction: 1.0

Epoch 3/3:  41%|████      | 1645/4000 [15:35<25:03,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.082119941711426, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.106070518493652, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 3/3:  41%|████      | 1646/4000 [15:36<20:41,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.3986010551452637, Predicted Probability: 0.0833, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.547994613647461, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  41%|████      | 1647/4000 [15:36<23:18,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.03995132446289, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.552942752838135, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 3/3:  41%|████      | 1648/4000 [15:37<24:53,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.024005889892578, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.644486904144287, Predicted Probability: 0.1619, Prediction: 0.0

Epoch 3/3:  41%|████      | 1649/4000 [15:38<25:59,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1061244010925293, Predicted Probability: 0.9571, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.567908763885498, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 3/3:  41%|████▏     | 1650/4000 [15:39<27:32,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.563620567321777, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.424039840698242, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████▏     | 1651/4000 [15:39<24:22,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.338655471801758, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.577569484710693, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  41%|████▏     | 1652/4000 [15:40<25:56,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.531205654144287, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.836892127990723, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 3/3:  41%|████▏     | 1653/4000 [15:40<23:21,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.784437656402588, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.707971572875977, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  41%|████▏     | 1654/4000 [15:41<22:48,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.29011344909668, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.305464744567871, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  41%|████▏     | 1655/4000 [15:41<20:23,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.061319351196289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.107591152191162, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  41%|████▏     | 1656/4000 [15:42<23:41,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.893779754638672, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0449323654174805, Predicted Probability: 0.9546, Prediction: 1.0

Epoch 3/3:  41%|████▏     | 1657/4000 [15:43<26:19,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.614568710327148, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.192020416259766, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  41%|████▏     | 1658/4000 [15:43<23:03,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1525115966796875, Predicted Probability: 0.1041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.35713005065918, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  41%|████▏     | 1659/4000 [15:44<21:15,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.016037464141846, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.449240684509277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1660/4000 [15:44<23:22,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.508474349975586, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.737442970275879, Predicted Probability: 0.9767, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1661/4000 [15:45<24:48,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.696925163269043, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.296644687652588, Predicted Probability: 0.9643, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1662/4000 [15:46<21:39,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.964046478271484, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6372222900390625, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1663/4000 [15:46<19:31,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.435613632202148, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.453776359558105, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1664/4000 [15:47<22:25,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.839687824249268, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.963630676269531, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1665/4000 [15:47<24:58,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.986865997314453, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.815913200378418, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1666/4000 [15:48<26:30,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.06273889541626, Predicted Probability: 0.0063, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.255462646484375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1667/4000 [15:49<27:33,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.990808963775635, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.158001899719238, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1668/4000 [15:49<23:41,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.386649131774902, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.8893585205078125, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1669/4000 [15:50<24:57,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.107438564300537, Predicted Probability: 0.9572, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.359595775604248, Predicted Probability: 0.0126, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1670/4000 [15:51<26:05,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.112159729003906, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.272805690765381, Predicted Probability: 0.0138, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1671/4000 [15:52<28:02,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.533435821533203, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.760847091674805, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1672/4000 [15:52<22:02,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.89933967590332, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.954726219177246, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1673/4000 [15:53<23:55,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.525609016418457, Predicted Probability: 0.0741, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.114870071411133, Predicted Probability: 0.1077, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1674/4000 [15:53<25:38,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4079513549804688, Predicted Probability: 0.9680, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.912797927856445, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1675/4000 [15:54<26:36,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9206032752990723, Predicted Probability: 0.1278, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.719719886779785, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1676/4000 [15:55<27:39,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.98546028137207, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.2343034744262695, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1677/4000 [15:56<27:54,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.727628707885742, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.124567031860352, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1678/4000 [15:56<25:54,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.626635551452637, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.662449836730957, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1679/4000 [15:56<20:32,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.285365581512451, Predicted Probability: 0.0136, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.54213809967041, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1680/4000 [15:57<24:48,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.617956161499023, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.613119125366211, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1681/4000 [15:58<24:13,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.692453622817993, Predicted Probability: 0.9757, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.353471755981445, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1682/4000 [15:59<25:23,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.21178913116455, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7622137069702148, Predicted Probability: 0.1465, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1683/4000 [15:59<24:02,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.561521530151367, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.037477493286133, Predicted Probability: 0.0173, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1684/4000 [16:00<21:10,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.100820064544678, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.3197106719017029, Predicted Probability: 0.5793, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1685/4000 [16:00<23:38,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.235329627990723, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.124574661254883, Predicted Probability: 0.9579, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1686/4000 [16:01<25:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.358569860458374, Predicted Probability: 0.0336, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.374031066894531, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1687/4000 [16:01<21:59,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.21844482421875, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.314031600952148, Predicted Probability: 0.0018, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1688/4000 [16:02<21:48,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.227142333984375, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.88259506225586, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1689/4000 [16:03<23:34,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.65690803527832, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.050676345825195, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1690/4000 [16:03<20:44,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.554237365722656, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.011112689971924, Predicted Probability: 0.0066, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1691/4000 [16:04<23:44,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.47281265258789, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.559802055358887, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1692/4000 [16:04<21:38,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7579026222229, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.069811820983887, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1693/4000 [16:05<20:25,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.402268409729004, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.568978309631348, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  42%|████▏     | 1694/4000 [16:05<20:35,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.263355255126953, Predicted Probability: 0.9861, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.395360946655273, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1695/4000 [16:06<23:40,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.249370574951172, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.149740219116211, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1696/4000 [16:07<25:01,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9860687255859375, Predicted Probability: 0.0068, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.289310455322266, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1697/4000 [16:08<25:58,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.265458106994629, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.399309158325195, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1698/4000 [16:08<26:32,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.972414970397949, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.834383010864258, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  42%|████▏     | 1699/4000 [16:09<27:18,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.515105247497559, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7179741859436035, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 3/3:  42%|████▎     | 1700/4000 [16:10<27:27,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.921510219573975, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.34876823425293, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1701/4000 [16:11<27:48,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.621427536010742, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1628847122192383, Predicted Probability: 0.1031, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1702/4000 [16:11<25:49,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.563530921936035, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.067859649658203, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1703/4000 [16:12<25:00,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1116015911102295, Predicted Probability: 0.9574, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.746729850769043, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1704/4000 [16:13<26:56,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.826720237731934, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.919940948486328, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1705/4000 [16:13<25:50,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.613532781600952, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.820667266845703, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1706/4000 [16:14<22:15,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.221196174621582, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.906530380249023, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1707/4000 [16:14<24:37,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.754308700561523, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.841119766235352, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1708/4000 [16:15<26:09,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.673717498779297, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.805973052978516, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1710/4000 [16:16<21:28,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: -3.2555274963378906, Predicted Probability: 0.0371, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.694866180419922, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 1.4338226318359375, Predicted Probability: 0.8075, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.999561309814453, Predicted Probability: 0.9526, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1711/4000 [16:16<17:21,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.340848922729492, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.671148300170898, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1712/4000 [16:17<20:43,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.072725296020508, Predicted Probability: 0.1118, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.662960052490234, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1713/4000 [16:17<18:50,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.102391242980957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.99344539642334, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1714/4000 [16:18<21:34,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.313299179077148, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9820916652679443, Predicted Probability: 0.9518, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1715/4000 [16:19<21:22,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.266016006469727, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.631162643432617, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1716/4000 [16:19<23:45,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.233800888061523, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6932454109191895, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1717/4000 [16:20<24:57,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.727738380432129, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.538208961486816, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1718/4000 [16:21<21:46,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.287442207336426, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.935752868652344, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1719/4000 [16:22<26:22,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.304841995239258, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0129051208496094, Predicted Probability: 0.1179, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1720/4000 [16:22<22:47,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.071439266204834, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.209708213806152, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1722/4000 [16:23<19:59,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1761960983276367, Predicted Probability: 0.2357, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.276811599731445, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.7979736328125, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.143725395202637, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1723/4000 [16:24<22:27,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2056164741516113, Predicted Probability: 0.9610, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.092926025390625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1724/4000 [16:24<20:43,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5273308753967285, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.410746574401855, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1725/4000 [16:25<18:48,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.013774871826172, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.219940662384033, Predicted Probability: 0.0145, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1726/4000 [16:25<21:59,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.0953545570373535, Predicted Probability: 0.0164, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.959848403930664, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1727/4000 [16:26<21:35,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.940232276916504, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.789764404296875, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1728/4000 [16:27<23:16,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.554080963134766, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.36568546295166, Predicted Probability: 0.0858, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1729/4000 [16:27<25:27,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5711565017700195, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.610001564025879, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1730/4000 [16:28<22:12,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.346077919006348, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.520943641662598, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1731/4000 [16:28<19:40,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.669496536254883, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.385923385620117, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1732/4000 [16:28<16:51,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.244805335998535, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.066505432128906, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1733/4000 [16:29<16:05,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.912354469299316, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7350109815597534, Predicted Probability: 0.6759, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1734/4000 [16:30<19:48,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.822363376617432, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.997102737426758, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1735/4000 [16:30<18:02,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.3087158203125, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.137022018432617, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1736/4000 [16:30<17:05,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.073304176330566, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.312456130981445, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1737/4000 [16:31<18:17,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.391059875488281, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.791167259216309, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  43%|████▎     | 1738/4000 [16:31<15:05,  2.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.844427585601807, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.163071632385254, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  43%|████▎     | 1739/4000 [16:32<16:50,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.866182327270508, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.514993667602539, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  44%|████▎     | 1740/4000 [16:32<19:53,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8920272588729858, Predicted Probability: 0.1310, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.19314908981323242, Predicted Probability: 0.4519, Prediction: 0.0

Epoch 3/3:  44%|████▎     | 1741/4000 [16:33<23:09,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.280651569366455, Predicted Probability: 0.9864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.229269981384277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▎     | 1742/4000 [16:34<23:10,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.8984334468841553, Predicted Probability: 0.9801, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.769704818725586, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  44%|████▎     | 1744/4000 [16:35<19:20,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.76866626739502, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.8612470626831055, Predicted Probability: 0.9972, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.632366180419922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.97767162322998, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  44%|████▎     | 1745/4000 [16:35<19:46,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.365880966186523, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.540325164794922, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  44%|████▎     | 1746/4000 [16:35<16:47,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.635553359985352, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.668283462524414, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▎     | 1747/4000 [16:36<17:59,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.997025489807129, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.333425521850586, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  44%|████▎     | 1748/4000 [16:37<18:40,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.560345649719238, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7241570949554443, Predicted Probability: 0.9384, Prediction: 1.0

Epoch 3/3:  44%|████▎     | 1749/4000 [16:37<21:52,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.645774841308594, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7438409328460693, Predicted Probability: 0.9769, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1750/4000 [16:38<23:52,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.503508567810059, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.438255310058594, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1751/4000 [16:39<24:50,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.295981407165527, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.12573504447937, Predicted Probability: 0.1066, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1752/4000 [16:40<25:52,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5645875930786133, Predicted Probability: 0.8270, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.383648872375488, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1753/4000 [16:40<26:57,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.385578155517578, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.79970932006836, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1754/4000 [16:41<21:08,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.619928359985352, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.972275733947754, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1755/4000 [16:41<23:10,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.734705924987793, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.540869235992432, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1756/4000 [16:42<25:45,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.953079223632812, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.474519729614258, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1757/4000 [16:43<22:08,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.449690818786621, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.4776697158813477, Predicted Probability: 0.0774, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1758/4000 [16:43<23:47,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.21615219116211, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.56288480758667, Predicted Probability: 0.1732, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1759/4000 [16:44<22:45,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.611234188079834, Predicted Probability: 0.0036, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.331809997558594, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1760/4000 [16:45<26:35,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.438715934753418, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.322826385498047, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1761/4000 [16:46<27:50,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.233526229858398, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.9332776069641113, Predicted Probability: 0.9808, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1762/4000 [16:46<27:45,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.209808349609375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.934469223022461, Predicted Probability: 0.1263, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1763/4000 [16:47<28:05,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.810000419616699, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.07532787322998, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1764/4000 [16:47<21:56,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.820272445678711, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.855088233947754, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1765/4000 [16:48<24:15,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.158984184265137, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.56248664855957, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1766/4000 [16:49<25:16,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.219669342041016, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.326892375946045, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1767/4000 [16:49<24:24,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3374457359313965, Predicted Probability: 0.9657, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.964935302734375, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1768/4000 [16:50<22:11,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.969376564025879, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.265462875366211, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1769/4000 [16:50<17:49,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.021151542663574, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.714046478271484, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1770/4000 [16:51<20:51,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.316442012786865, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.98352336883545, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1771/4000 [16:51<20:46,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.496944427490234, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.448886871337891, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1772/4000 [16:52<22:44,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.180675983428955, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.14084243774414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1773/4000 [16:53<26:33,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5009078979492188, Predicted Probability: 0.9707, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.970096588134766, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1774/4000 [16:54<26:53,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.632455825805664, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.410313129425049, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 3/3:  44%|████▍     | 1775/4000 [16:55<26:59,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.995428085327148, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.585146188735962, Predicted Probability: 0.1701, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1776/4000 [16:55<25:00,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.40552043914795, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.488543510437012, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1777/4000 [16:56<26:34,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.64162540435791, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.110681533813477, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1778/4000 [16:56<22:41,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.017420768737793, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.580648899078369, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1779/4000 [16:57<24:22,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.411672592163086, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.368302345275879, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  44%|████▍     | 1780/4000 [16:58<26:05,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.277193069458008, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1151604652404785, Predicted Probability: 0.0425, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1781/4000 [16:59<26:31,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4050657749176025, Predicted Probability: 0.9679, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.142072677612305, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1782/4000 [16:59<27:00,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.561831474304199, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.929110527038574, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1783/4000 [17:00<27:09,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.761087417602539, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.504903316497803, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1784/4000 [17:01<27:30,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.094694137573242, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.712897300720215, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1785/4000 [17:01<24:06,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.589982032775879, Predicted Probability: 0.0269, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.43132209777832, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1786/4000 [17:02<21:04,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: 8.107061386108398, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.763446807861328, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1787/4000 [17:03<22:58,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.967219352722168, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.743191242218018, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1788/4000 [17:03<24:35,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.15558910369873, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.126278877258301, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1789/4000 [17:04<26:06,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.208641052246094, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8792173862457275, Predicted Probability: 0.0202, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1790/4000 [17:05<26:28,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.182292938232422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.007744312286377, Predicted Probability: 0.1184, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1791/4000 [17:06<26:44,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.774841547012329, Predicted Probability: 0.1449, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5465173721313477, Predicted Probability: 0.9720, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1792/4000 [17:06<27:01,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.772626876831055, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.465371131896973, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1793/4000 [17:07<27:00,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.80213737487793, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5251646041870117, Predicted Probability: 0.9259, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1794/4000 [17:07<21:17,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.50943374633789, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.616048812866211, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1795/4000 [17:08<17:09,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.699773788452148, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.49121379852295, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  45%|████▍     | 1796/4000 [17:08<20:12,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.075486898422241, Predicted Probability: 0.1115, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.12006950378418, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1797/4000 [17:09<22:27,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.9446845054626465, Predicted Probability: 0.0071, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8731549978256226, Predicted Probability: 0.1332, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1798/4000 [17:10<23:46,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.82388973236084, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.320108413696289, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  45%|████▍     | 1799/4000 [17:11<25:25,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.88597297668457, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.55385971069336, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1800/4000 [17:11<21:47,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.436952590942383, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.564209938049316, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1801/4000 [17:11<19:23,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.106548547744751, Predicted Probability: 0.9572, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.253990650177002, Predicted Probability: 0.9860, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1802/4000 [17:12<19:43,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.502110004425049, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.753235816955566, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1803/4000 [17:12<17:47,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.516168117523193, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.544054985046387, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1804/4000 [17:13<20:56,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.055746078491211, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.839722633361816, Predicted Probability: 0.0078, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1805/4000 [17:14<23:03,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.425077438354492, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.647996425628662, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1806/4000 [17:14<23:58,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1463751792907715, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.41915225982666, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1807/4000 [17:15<24:44,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.908492088317871, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3757598400115967, Predicted Probability: 0.7983, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1808/4000 [17:16<21:19,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.555700302124023, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.547881126403809, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1809/4000 [17:16<18:57,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.459067344665527, Predicted Probability: 0.9886, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.67921781539917, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1810/4000 [17:17<21:18,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.968620300292969, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.244865655899048, Predicted Probability: 0.9625, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1811/4000 [17:17<20:49,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.131779193878174, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.538064002990723, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1812/4000 [17:18<19:35,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.19840669631958, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.421226501464844, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1813/4000 [17:18<18:32,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.399963855743408, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8918800354003906, Predicted Probability: 0.9474, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1814/4000 [17:19<21:14,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.516963005065918, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5007853507995605, Predicted Probability: 0.9242, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1815/4000 [17:20<23:06,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.75935173034668, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9482269287109375, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1816/4000 [17:20<24:31,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.823383092880249, Predicted Probability: 0.9439, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.02525806427002, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1817/4000 [17:21<21:12,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1563583612442017, Predicted Probability: 0.7607, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.10922815650701523, Predicted Probability: 0.4727, Prediction: 0.0

Epoch 3/3:  45%|████▌     | 1818/4000 [17:21<22:59,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.110054016113281, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1824941635131836, Predicted Probability: 0.9602, Prediction: 1.0

Epoch 3/3:  45%|████▌     | 1819/4000 [17:22<18:22,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.071159362792969, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.654369354248047, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1820/4000 [17:22<21:02,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.379205703735352, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.6391282081604, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1821/4000 [17:23<19:02,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.552796840667725, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.393923759460449, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1822/4000 [17:24<21:25,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.090059757232666, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.723999977111816, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1823/4000 [17:24<22:47,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1509416103363037, Predicted Probability: 0.8958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.375694274902344, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1824/4000 [17:25<24:05,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.217744827270508, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.685816287994385, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1825/4000 [17:26<24:34,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.615485191345215, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.28171059489250183, Predicted Probability: 0.5700, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1826/4000 [17:27<25:23,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9899889230728149, Predicted Probability: 0.2709, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.944652557373047, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1827/4000 [17:27<25:42,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.934279441833496, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8621456623077393, Predicted Probability: 0.8655, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1828/4000 [17:28<26:35,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.833841323852539, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.160885810852051, Predicted Probability: 0.9593, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1829/4000 [17:29<26:41,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.386823654174805, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.685675621032715, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1830/4000 [17:30<28:05,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.018436431884766, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.02421760559082, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1831/4000 [17:30<27:44,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.893072128295898, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.829758167266846, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1832/4000 [17:31<23:30,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.456239700317383, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.764463901519775, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1833/4000 [17:31<20:43,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.924280166625977, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.380354881286621, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1834/4000 [17:32<22:31,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.523027181625366, Predicted Probability: 0.9713, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.79263973236084, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1835/4000 [17:33<24:06,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.955041885375977, Predicted Probability: 0.9930, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.62666130065918, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1836/4000 [17:33<21:00,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.239232063293457, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.123493194580078, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1837/4000 [17:34<23:05,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.771968841552734, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.365598678588867, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1838/4000 [17:34<20:12,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.26655912399292, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.010241985321045, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1839/4000 [17:35<18:49,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.478344440460205, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.841577529907227, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1840/4000 [17:35<21:00,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.331646919250488, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4208905696868896, Predicted Probability: 0.9684, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1841/4000 [17:36<16:56,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.584361553192139, Predicted Probability: 0.0101, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.096105575561523, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1842/4000 [17:36<15:48,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.878547668457031, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.530895233154297, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 3/3:  46%|████▌     | 1843/4000 [17:37<19:13,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.626161575317383, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.728833198547363, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1844/4000 [17:38<25:00,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.270468711853027, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.985334396362305, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1845/4000 [17:38<21:25,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.122227668762207, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.527689933776855, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1846/4000 [17:39<23:02,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.5761895179748535, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.581681251525879, Predicted Probability: 0.0101, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1847/4000 [17:39<22:00,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.737689018249512, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.2798609733581543, Predicted Probability: 0.4305, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1848/4000 [17:41<33:36,  1.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5323429107666016, Predicted Probability: 0.9716, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.54634952545166, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  46%|████▌     | 1849/4000 [17:42<27:34,  1.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.662878513336182, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.26801872253418, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1850/4000 [17:42<27:11,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.722362041473389, Predicted Probability: 0.0088, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.266915500164032, Predicted Probability: 0.4337, Prediction: 0.0

Epoch 3/3:  46%|████▋     | 1851/4000 [17:43<23:11,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.569425582885742, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.230681419372559, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1852/4000 [17:43<24:23,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.21241158246994019, Predicted Probability: 0.4471, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.10293197631836, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  46%|████▋     | 1853/4000 [17:44<25:34,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.194827556610107, Predicted Probability: 0.0148, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.653398513793945, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  46%|████▋     | 1854/4000 [17:45<23:50,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.329096794128418, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.472749710083008, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1855/4000 [17:45<22:28,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.913488388061523, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.227015495300293, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1856/4000 [17:46<21:31,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4135587215423584, Predicted Probability: 0.0319, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.736075401306152, Predicted Probability: 0.9913, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1857/4000 [17:47<23:07,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.154170989990234, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.906938552856445, Predicted Probability: 0.9927, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1858/4000 [17:47<24:07,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7012134790420532, Predicted Probability: 0.1543, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.6966962814331055, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  46%|████▋     | 1859/4000 [17:48<24:38,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.112411499023438, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3944129943847656, Predicted Probability: 0.9675, Prediction: 1.0

Epoch 3/3:  46%|████▋     | 1860/4000 [17:49<23:00,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.728404998779297, Predicted Probability: 0.9912, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.353278160095215, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1861/4000 [17:49<23:46,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.375863552093506, Predicted Probability: 0.9669, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.657098770141602, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1862/4000 [17:50<24:36,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.954364538192749, Predicted Probability: 0.9812, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.888745307922363, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1863/4000 [17:50<21:14,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.3202543258667, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.975851535797119, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1864/4000 [17:51<20:48,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.19020476937294006, Predicted Probability: 0.5474, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.995376586914062, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1865/4000 [17:52<23:02,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.165583610534668, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.666429281234741, Predicted Probability: 0.9751, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1866/4000 [17:53<25:23,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.267884254455566, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.427489280700684, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1867/4000 [17:53<22:33,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.827041625976562, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.946123123168945, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1868/4000 [17:53<18:38,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.990509986877441, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.817942142486572, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1869/4000 [17:54<21:14,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.796258926391602, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.45041275024414, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1870/4000 [17:55<18:55,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.182587623596191, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.068775177001953, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1871/4000 [17:55<19:02,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.3920722007751465, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7892282009124756, Predicted Probability: 0.9779, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1872/4000 [17:56<21:12,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.620889663696289, Predicted Probability: 0.9903, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.843190670013428, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1874/4000 [17:56<15:57,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.962333679199219, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.783584117889404, Predicted Probability: 0.0083, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.401915550231934, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.673101425170898, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1875/4000 [17:57<18:45,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6141061782836914, Predicted Probability: 0.9738, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.491493225097656, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1876/4000 [17:58<22:02,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.572504043579102, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.648933410644531, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1877/4000 [17:59<21:17,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5109903812408447, Predicted Probability: 0.0290, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.460345268249512, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1878/4000 [17:59<17:05,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.931013107299805, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.190176963806152, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1879/4000 [18:00<19:47,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.13327407836914, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1758251190185547, Predicted Probability: 0.1019, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1880/4000 [18:00<17:48,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.7134108543396, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.708370208740234, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1881/4000 [18:01<20:18,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.434835195541382, Predicted Probability: 0.0806, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.09812593460083, Predicted Probability: 0.8907, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1882/4000 [18:01<23:02,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.273080825805664, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.049010753631592, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1883/4000 [18:02<23:59,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.262462615966797, Predicted Probability: 0.0943, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.691009521484375, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1884/4000 [18:03<22:33,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.474923133850098, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.3446370363235474, Predicted Probability: 0.7933, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1885/4000 [18:04<24:31,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.483880996704102, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.833778381347656, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1886/4000 [18:04<25:07,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.945152282714844, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.203939437866211, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1887/4000 [18:05<26:16,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.566362380981445, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.3941969871521, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1888/4000 [18:06<24:06,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.186403274536133, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.002617835998535, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1889/4000 [18:06<24:59,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.235750675201416, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.247786521911621, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1890/4000 [18:07<22:02,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3480024337768555, Predicted Probability: 0.9953, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.657859802246094, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1891/4000 [18:07<19:13,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.706130027770996, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.29051685333252, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1892/4000 [18:08<21:23,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.576358437538147, Predicted Probability: 0.1713, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.117483139038086, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1893/4000 [18:08<18:57,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.569694519042969, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.229315757751465, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1894/4000 [18:09<15:24,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.24988842010498, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.813993453979492, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1895/4000 [18:09<19:55,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.015776634216309, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.894418716430664, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1896/4000 [18:10<21:50,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.954095840454102, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.396195888519287, Predicted Probability: 0.9955, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1897/4000 [18:11<23:02,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6977105140686035, Predicted Probability: 0.1548, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.064472198486328, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  47%|████▋     | 1898/4000 [18:11<20:02,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.131719589233398, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.192831993103027, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  47%|████▋     | 1899/4000 [18:12<17:56,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.030769348144531, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.150214195251465, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  48%|████▊     | 1900/4000 [18:12<16:22,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.574189186096191, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.834222316741943, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  48%|████▊     | 1901/4000 [18:13<16:05,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0117387771606445, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.518545150756836, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  48%|████▊     | 1902/4000 [18:13<15:20,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.59158992767334, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.335553169250488, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  48%|████▊     | 1903/4000 [18:13<13:36,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.254993438720703, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.832984924316406, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  48%|████▊     | 1904/4000 [18:14<17:00,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.501923084259033, Predicted Probability: 0.9707, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.1894354820251465, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2102/4000 [20:01<18:03,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.12537145614624, Predicted Probability: 0.9941, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.019587516784668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2103/4000 [20:02<19:37,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.631279468536377, Predicted Probability: 0.9742, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.101341247558594, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2104/4000 [20:02<20:45,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.852085590362549, Predicted Probability: 0.9454, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.01125431060791, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2105/4000 [20:03<21:31,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.28576374053955, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6151180267333984, Predicted Probability: 0.9738, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2106/4000 [20:04<18:43,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.764313697814941, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.480134963989258, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2107/4000 [20:04<18:21,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.138065338134766, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.235363483428955, Predicted Probability: 0.9947, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2108/4000 [20:04<14:46,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.991374015808105, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.02066707611084, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2109/4000 [20:05<17:48,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.605934143066406, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.516162395477295, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2110/4000 [20:06<19:23,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.136274337768555, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.691715717315674, Predicted Probability: 0.9757, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2111/4000 [20:07<21:45,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.793697357177734, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.451571464538574, Predicted Probability: 0.0115, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2112/4000 [20:07<22:36,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.193049430847168, Predicted Probability: 0.9851, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.511073112487793, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2113/4000 [20:08<22:56,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.97337532043457, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.812114715576172, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2114/4000 [20:09<23:18,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.372733116149902, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.102998733520508, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2115/4000 [20:10<23:00,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7173563241958618, Predicted Probability: 0.1522, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.7681884765625, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2116/4000 [20:10<23:11,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.737977981567383, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0271100997924805, Predicted Probability: 0.1164, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2117/4000 [20:11<23:40,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1021575927734375, Predicted Probability: 0.9570, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.287981986999512, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2118/4000 [20:12<23:59,  1.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.3613708019256592, Predicted Probability: 0.7960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.81824779510498, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2119/4000 [20:12<20:18,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.72354507446289, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.585318565368652, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2120/4000 [20:13<17:46,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.349620819091797, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.63905143737793, Predicted Probability: 0.9987, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2121/4000 [20:13<19:18,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.974786758422852, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.981613874435425, Predicted Probability: 0.9517, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2122/4000 [20:14<17:05,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.042330265045166, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.736428260803223, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2123/4000 [20:14<15:30,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.415066719055176, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.63859748840332, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2125/4000 [20:15<11:54,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.623857021331787, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.422743320465088, Predicted Probability: 0.0016, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -9.100621223449707, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.857641220092773, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2127/4000 [20:16<11:16,  2.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5265355110168457, Predicted Probability: 0.9260, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.292709350585938, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.870098114013672, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.400676727294922, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2128/4000 [20:16<15:02,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.349656105041504, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.529534339904785, Predicted Probability: 0.0005, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -11.250596046447754, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2130/4000 [20:17<10:32,  2.96it/s]

Data point 2: Actual Class: 0.0, Final Logit: -10.527922630310059, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 11.095111846923828, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.087886810302734, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2131/4000 [20:18<14:49,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.486230850219727, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.0365071296691895, Predicted Probability: 0.9935, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2132/4000 [20:18<12:17,  2.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.955008506774902, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.446722030639648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2133/4000 [20:18<12:00,  2.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.389477729797363, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.663506507873535, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2134/4000 [20:19<15:30,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.188668251037598, Predicted Probability: 0.0055, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6397557258605957, Predicted Probability: 0.9334, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2135/4000 [20:20<18:03,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.931567192077637, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.508086681365967, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2136/4000 [20:20<19:49,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.960954189300537, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.569232940673828, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  53%|█████▎    | 2137/4000 [20:21<17:28,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.468233108520508, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4877321720123291, Predicted Probability: 0.6196, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2138/4000 [20:21<15:46,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.35295295715332, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.049081802368164, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  53%|█████▎    | 2139/4000 [20:22<18:10,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1306383609771729, Predicted Probability: 0.2440, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.800333976745605, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2140/4000 [20:23<19:31,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.991264343261719, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4312376976013184, Predicted Probability: 0.9687, Prediction: 1.0

Epoch 3/3:  54%|█████▎    | 2141/4000 [20:23<20:36,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.031482696533203, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4160547256469727, Predicted Probability: 0.9682, Prediction: 1.0

Epoch 3/3:  54%|█████▎    | 2142/4000 [20:24<17:55,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.8494343757629395, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.902191162109375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2143/4000 [20:24<16:29,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.599002838134766, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.200400352478027, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2144/4000 [20:25<16:44,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.746129989624023, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.282437324523926, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2145/4000 [20:25<18:14,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.155810832977295, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2829937934875488, Predicted Probability: 0.2170, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2146/4000 [20:26<14:38,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.053627967834473, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.823494911193848, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  54%|█████▎    | 2147/4000 [20:26<15:28,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.006421089172363, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.659729957580566, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2148/4000 [20:27<18:01,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.689602851867676, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.598209023475647, Predicted Probability: 0.1682, Prediction: 0.0

Epoch 3/3:  54%|█████▎    | 2149/4000 [20:27<16:11,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.883959770202637, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.623000621795654, Predicted Probability: 0.9903, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2150/4000 [20:28<18:20,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.590789318084717, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.901346206665039, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2151/4000 [20:29<20:40,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.378423690795898, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0355395078659058, Predicted Probability: 0.2620, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2152/4000 [20:29<17:57,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.025236129760742, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.997704029083252, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2153/4000 [20:30<19:44,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9167383909225464, Predicted Probability: 0.2856, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.011475563049316, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2154/4000 [20:31<18:54,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.541974067687988, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.026576519012451, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2155/4000 [20:31<18:12,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.867123603820801, Predicted Probability: 0.9462, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.834930658340454, Predicted Probability: 0.9445, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2156/4000 [20:32<16:49,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.020500183105469, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.804876804351807, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2157/4000 [20:32<18:25,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.292699098587036, Predicted Probability: 0.9642, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.94375228881836, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2158/4000 [20:33<16:23,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.571506023406982, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.55105209350586, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2159/4000 [20:34<18:07,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4427573680877686, Predicted Probability: 0.9690, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.132936477661133, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2160/4000 [20:34<19:27,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.702136993408203, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9577438831329346, Predicted Probability: 0.9506, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2161/4000 [20:35<17:39,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.971745014190674, Predicted Probability: 0.9931, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.89422082901001, Predicted Probability: 0.0074, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2162/4000 [20:36<20:09,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.70728874206543, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.65614128112793, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2163/4000 [20:36<21:35,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.548919677734375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2600581645965576, Predicted Probability: 0.9055, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2164/4000 [20:37<22:24,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.197030067443848, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.8185418844223022, Predicted Probability: 0.8604, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2165/4000 [20:38<22:13,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.11406421661377, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3808536529541016, Predicted Probability: 0.9671, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2166/4000 [20:38<19:11,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.9604926109313965, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.96076774597168, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2167/4000 [20:39<16:49,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.218789100646973, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.271279335021973, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2168/4000 [20:39<18:38,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.938200950622559, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.769164085388184, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2169/4000 [20:40<19:41,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.23465895652771, Predicted Probability: 0.9621, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.404858589172363, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2170/4000 [20:41<20:59,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.130290508270264, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.002817153930664, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2171/4000 [20:41<18:45,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.656576633453369, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.925111293792725, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2172/4000 [20:42<16:30,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.721917152404785, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.410138130187988, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2173/4000 [20:43<18:43,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.329532623291016, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7203667163848877, Predicted Probability: 0.1518, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2174/4000 [20:43<19:52,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8412036895751953, Predicted Probability: 0.9449, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.579082489013672, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2175/4000 [20:44<18:01,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.146587371826172, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.124917984008789, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2176/4000 [20:44<19:32,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.64763355255127, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.821183204650879, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 3/3:  54%|█████▍    | 2177/4000 [20:45<17:41,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.5772705078125, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.644526958465576, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2178/4000 [20:45<17:30,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.23787260055542, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.174549102783203, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  54%|█████▍    | 2179/4000 [20:46<19:13,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.032256126403809, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.538024425506592, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2180/4000 [20:47<16:41,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.227474212646484, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.761309623718262, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2181/4000 [20:47<18:10,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.073349952697754, Predicted Probability: 0.1117, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.237417221069336, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2182/4000 [20:48<19:28,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.739471435546875, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.597067832946777, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2183/4000 [20:49<20:34,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.759034156799316, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.235811471939087, Predicted Probability: 0.9034, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2184/4000 [20:50<21:06,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.62721061706543, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.408698081970215, Predicted Probability: 0.9680, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2185/4000 [20:50<18:48,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5550537109375, Predicted Probability: 0.0278, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.03158187866211, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2186/4000 [20:50<16:35,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.908979415893555, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.437969207763672, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2187/4000 [20:51<18:09,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.421608924865723, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.46541166305542, Predicted Probability: 0.9697, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2188/4000 [20:52<16:08,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.606314182281494, Predicted Probability: 0.9901, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.243658065795898, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2189/4000 [20:52<18:37,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.47842025756836, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.35781478881836, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2190/4000 [20:53<16:24,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.045008182525635, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.4959716796875, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2191/4000 [20:53<15:25,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.838322639465332, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.767938613891602, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2192/4000 [20:54<17:36,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.61749267578125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.865983009338379, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2193/4000 [20:55<18:50,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.943532943725586, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.057905912399292, Predicted Probability: 0.1133, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2194/4000 [20:55<19:46,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.153975486755371, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.050658941268921, Predicted Probability: 0.1140, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2195/4000 [20:57<24:28,  1.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.592547416687012, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.01542854309082, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2196/4000 [20:57<19:00,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.36034870147705, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.421965599060059, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2197/4000 [20:57<18:41,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9287785291671753, Predicted Probability: 0.1269, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.773736000061035, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▍    | 2198/4000 [20:58<19:39,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.961432456970215, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.866525173187256, Predicted Probability: 0.9462, Prediction: 1.0

Epoch 3/3:  55%|█████▍    | 2199/4000 [20:59<20:40,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.00189208984375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.456629753112793, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2200/4000 [20:59<19:24,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.726174354553223, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.872987747192383, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2201/4000 [21:00<16:55,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.445755958557129, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.456149101257324, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2202/4000 [21:01<18:57,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.190635681152344, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.63969612121582, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2203/4000 [21:01<19:40,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.54831314086914, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.320706367492676, Predicted Probability: 0.9651, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2204/4000 [21:02<20:45,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1941332817077637, Predicted Probability: 0.9606, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.440130233764648, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2205/4000 [21:03<21:16,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7041513919830322, Predicted Probability: 0.9373, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.340351104736328, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2206/4000 [21:03<16:46,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.046079635620117, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.836498260498047, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2207/4000 [21:04<17:18,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.124687194824219, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.578702926635742, Predicted Probability: 0.0038, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2208/4000 [21:04<18:50,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.948668479919434, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.668776035308838, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2209/4000 [21:05<19:52,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.712044715881348, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6265945434570312, Predicted Probability: 0.0259, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2210/4000 [21:06<20:21,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8998992443084717, Predicted Probability: 0.1301, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9622355699539185, Predicted Probability: 0.1232, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2211/4000 [21:06<17:29,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.28037166595459, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.257015228271484, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2212/4000 [21:07<18:48,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.333882808685303, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.086761474609375, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2213/4000 [21:08<20:09,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.6772141456604, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.164485931396484, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2214/4000 [21:08<20:27,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.54231071472168, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.864658832550049, Predicted Probability: 0.9461, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2215/4000 [21:09<21:09,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.934028387069702, Predicted Probability: 0.9495, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.908466339111328, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2216/4000 [21:10<19:39,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.357687950134277, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1702380180358887, Predicted Probability: 0.9597, Prediction: 1.0

Epoch 3/3:  55%|█████▌    | 2217/4000 [21:10<15:34,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.386480331420898, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.357874870300293, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2218/4000 [21:11<17:23,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1944282054901123, Predicted Probability: 0.9606, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.671894073486328, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  55%|█████▌    | 2219/4000 [21:11<18:36,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.91457748413086, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.762247562408447, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2220/4000 [21:12<16:31,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.10697078704834, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.115070343017578, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2222/4000 [21:12<12:08,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.460860013961792, Predicted Probability: 0.9696, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.508635520935059, Predicted Probability: 0.9960, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.461751937866211, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.543963432312012, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2223/4000 [21:13<11:42,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.14517879486084, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.937373161315918, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2224/4000 [21:14<15:22,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.858283996582031, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.67385196685791, Predicted Probability: 0.9908, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2225/4000 [21:14<12:35,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.792532920837402, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.360878944396973, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2226/4000 [21:14<15:10,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.119264602661133, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.6978800296783447, Predicted Probability: 0.8453, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2227/4000 [21:15<14:01,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.9819917678833, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.921931266784668, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2228/4000 [21:15<13:07,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.798400402069092, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.528175354003906, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2229/4000 [21:16<15:37,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2729034423828125, Predicted Probability: 0.9635, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.372039794921875, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2230/4000 [21:17<18:35,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.238513946533203, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.529314994812012, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2231/4000 [21:18<19:27,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.558210372924805, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6197657585144043, Predicted Probability: 0.9321, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2232/4000 [21:18<20:31,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.951259613037109, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.37240982055664, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2233/4000 [21:19<16:09,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.280608177185059, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.49997329711914, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2234/4000 [21:19<17:44,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.337442398071289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.9335715770721436, Predicted Probability: 0.2822, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2235/4000 [21:20<15:47,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.755009651184082, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.974114894866943, Predicted Probability: 0.0025, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2236/4000 [21:20<17:36,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.2504706382751465, Predicted Probability: 0.5623, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.210503578186035, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2237/4000 [21:21<14:07,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.466082572937012, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.718632698059082, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2238/4000 [21:21<11:40,  2.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.164106369018555, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.368528366088867, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2239/4000 [21:21<10:00,  2.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.379264831542969, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.302689552307129, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2240/4000 [21:21<10:18,  2.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.927477836608887, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7110496759414673, Predicted Probability: 0.8470, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2241/4000 [21:22<12:04,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.617145538330078, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.414806842803955, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2242/4000 [21:23<14:50,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.540178298950195, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.390235424041748, Predicted Probability: 0.9674, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2243/4000 [21:23<13:48,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.103362560272217, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.310500144958496, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2244/4000 [21:23<13:04,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.789064407348633, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.86476993560791, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2245/4000 [21:24<15:34,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.100886344909668, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4365439414978027, Predicted Probability: 0.9196, Prediction: 1.0

Epoch 3/3:  56%|█████▌    | 2246/4000 [21:25<14:09,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.039477348327637, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.118108749389648, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2247/4000 [21:25<16:15,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3610482215881348, Predicted Probability: 0.9665, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.520971298217773, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2248/4000 [21:26<17:43,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.931027889251709, Predicted Probability: 0.0072, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.907185554504395, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▌    | 2249/4000 [21:26<15:43,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3899002075195312, Predicted Probability: 0.9674, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.740004539489746, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  56%|█████▋    | 2250/4000 [21:27<14:10,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.758929252624512, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6188883781433105, Predicted Probability: 0.0036, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2251/4000 [21:28<16:55,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.226938247680664, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.893142700195312, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2252/4000 [21:28<16:41,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.661238670349121, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.562265396118164, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  56%|█████▋    | 2253/4000 [21:29<18:15,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.923008918762207, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.108743667602539, Predicted Probability: 0.0060, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2254/4000 [21:30<19:33,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.196386337280273, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.823530197143555, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2255/4000 [21:30<16:59,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.88076114654541, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.778707027435303, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  56%|█████▋    | 2256/4000 [21:31<18:24,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6433892250061035, Predicted Probability: 0.9745, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.534221649169922, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2257/4000 [21:31<19:36,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.913179636001587, Predicted Probability: 0.1286, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.180719375610352, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2258/4000 [21:32<18:28,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.94972038269043, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.261247634887695, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2259/4000 [21:33<19:57,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.094509124755859, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.446453094482422, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 3/3:  56%|█████▋    | 2260/4000 [21:34<19:59,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.599899291992188, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8468666076660156, Predicted Probability: 0.9791, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2261/4000 [21:34<20:33,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4471282958984375, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.70629596710205, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2262/4000 [21:35<20:50,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.944725036621094, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.315208435058594, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2263/4000 [21:35<17:46,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.677265167236328, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.754270076751709, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2264/4000 [21:36<19:02,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1591293811798096, Predicted Probability: 0.1035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.890270709991455, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2265/4000 [21:37<19:33,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3338940143585205, Predicted Probability: 0.9656, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.510866165161133, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2266/4000 [21:38<20:35,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.022467613220214844, Predicted Probability: 0.4944, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.027870178222656, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2267/4000 [21:38<20:56,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.770691871643066, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.021657466888428, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2268/4000 [21:39<21:07,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.053382873535156, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.749642372131348, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2269/4000 [21:40<21:18,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.026864051818848, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.024007797241211, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2270/4000 [21:40<19:30,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.084609985351562, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3119025230407715, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2271/4000 [21:41<15:24,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.688400268554688, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.499486923217773, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2272/4000 [21:41<14:01,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.241649150848389, Predicted Probability: 0.0053, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.328438758850098, Predicted Probability: 0.0130, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2273/4000 [21:42<16:12,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.358156204223633, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.506326675415039, Predicted Probability: 0.1815, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2274/4000 [21:43<18:10,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.848406195640564, Predicted Probability: 0.1361, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.725401878356934, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2275/4000 [21:43<15:58,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.670373916625977, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.481627464294434, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2276/4000 [21:43<14:22,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.577714920043945, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.487584114074707, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2277/4000 [21:44<16:27,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.161386489868164, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6123485565185547, Predicted Probability: 0.9737, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2278/4000 [21:45<17:37,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.889572143554688, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7050070762634277, Predicted Probability: 0.9760, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2279/4000 [21:45<15:41,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.085871696472168, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.250268936157227, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2280/4000 [21:46<17:26,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.724485397338867, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.31854248046875, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2281/4000 [21:47<19:16,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.843482971191406, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.582174301147461, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2282/4000 [21:47<15:51,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.914017677307129, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.03893756866455, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2283/4000 [21:48<17:21,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.580113410949707, Predicted Probability: 0.9729, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.307149887084961, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2284/4000 [21:49<18:50,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6812238693237305, Predicted Probability: 0.9754, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.668062210083008, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2285/4000 [21:49<19:45,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6005747318267822, Predicted Probability: 0.9734, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.815340042114258, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2286/4000 [21:50<20:54,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.973653316497803, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.269030570983887, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2287/4000 [21:51<19:25,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.813843727111816, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.014810562133789, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2288/4000 [21:51<19:44,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.157779693603516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.691328287124634, Predicted Probability: 0.9757, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2289/4000 [21:52<19:55,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.359142303466797, Predicted Probability: 0.9664, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.644719123840332, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2290/4000 [21:53<18:34,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8433279991149902, Predicted Probability: 0.0210, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.862639427185059, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2291/4000 [21:53<16:08,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.44370174407959, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.742384910583496, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2292/4000 [21:54<17:30,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.504161357879639, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6433313488960266, Predicted Probability: 0.3445, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2293/4000 [21:54<15:33,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.589448928833008, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.04481315612793, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2294/4000 [21:55<17:10,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.477863311767578, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7211053371429443, Predicted Probability: 0.6729, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2295/4000 [21:56<18:04,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.619152545928955, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.538954257965088, Predicted Probability: 0.9718, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2296/4000 [21:56<17:20,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.505244731903076, Predicted Probability: 0.9891, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.087404251098633, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2297/4000 [21:57<15:17,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.403682231903076, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.597097396850586, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  57%|█████▋    | 2298/4000 [21:57<17:01,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.928629398345947, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.615310668945312, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  57%|█████▋    | 2299/4000 [21:58<18:24,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.3797494173049927, Predicted Probability: 0.4062, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.994158744812012, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  57%|█████▊    | 2300/4000 [21:58<14:37,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.851973533630371, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.677526473999023, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2301/4000 [21:59<16:43,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.471028804779053, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.34054183959961, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2302/4000 [21:59<13:24,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.688626289367676, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.445206642150879, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2303/4000 [22:00<12:35,  2.25it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.161940574645996, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.385682582855225, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2304/4000 [22:00<12:00,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.45427131652832, Predicted Probability: 0.9885, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.781192302703857, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2305/4000 [22:00<11:33,  2.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.214600563049316, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.503966331481934, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2306/4000 [22:01<12:40,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.896697998046875, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.462405204772949, Predicted Probability: 0.0785, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2308/4000 [22:02<11:03,  2.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.491743087768555, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.912692546844482, Predicted Probability: 0.9927, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.163010597229004, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.994671821594238, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2309/4000 [22:02<09:58,  2.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.791304588317871, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.872568130493164, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2310/4000 [22:03<13:46,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.940014660358429, Predicted Probability: 0.7191, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.165213584899902, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2311/4000 [22:03<15:59,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.24067211151123, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.740556716918945, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2312/4000 [22:04<13:25,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.794682502746582, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.337475776672363, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2313/4000 [22:04<15:42,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.433990478515625, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.1167893409729, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2314/4000 [22:05<18:10,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.366250991821289, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.611790180206299, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2315/4000 [22:06<19:41,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.615203857421875, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.59041976928711, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2316/4000 [22:07<20:11,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.473691940307617, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9298598766326904, Predicted Probability: 0.9493, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2317/4000 [22:08<20:18,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.3981648683547974, Predicted Probability: 0.1981, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.179767608642578, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2318/4000 [22:08<15:57,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.78836441040039, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.125595569610596, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2319/4000 [22:09<18:02,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.283056259155273, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.680086135864258, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2320/4000 [22:09<18:35,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3065192699432373, Predicted Probability: 0.2131, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.970715522766113, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2321/4000 [22:10<16:42,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.324007987976074, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.584839820861816, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2322/4000 [22:10<14:52,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.118971824645996, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.322999000549316, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2323/4000 [22:11<16:28,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6943564414978027, Predicted Probability: 0.9367, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.8402557373046875, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2324/4000 [22:12<17:32,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.0542445182800293, Predicted Probability: 0.8864, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.150406837463379, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2325/4000 [22:12<15:26,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.194872856140137, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.919315338134766, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2326/4000 [22:13<16:54,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9050917625427246, Predicted Probability: 0.1295, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.906742811203003, Predicted Probability: 0.9482, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2327/4000 [22:13<15:30,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.43917465209961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.507120132446289, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2328/4000 [22:14<17:49,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.236162185668945, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.901089668273926, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2329/4000 [22:15<18:35,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.839933156967163, Predicted Probability: 0.9448, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.078612327575684, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2330/4000 [22:15<15:17,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.338306427001953, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.693595886230469, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2331/4000 [22:16<18:04,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.532384872436523, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.042390823364258, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2332/4000 [22:17<18:55,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.6027822494506836, Predicted Probability: 0.9310, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.613631248474121, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2333/4000 [22:17<19:18,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.956338882446289, Predicted Probability: 0.9506, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.856992721557617, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2334/4000 [22:18<16:42,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.878961563110352, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.186040878295898, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2335/4000 [22:18<14:51,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.814039707183838, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.351078033447266, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2336/4000 [22:19<17:24,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.475889205932617, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.860544204711914, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2337/4000 [22:20<18:10,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.746725559234619, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.387751340866089, Predicted Probability: 0.0841, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2338/4000 [22:20<19:11,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.018203735351562, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0688977241516113, Predicted Probability: 0.9556, Prediction: 1.0

Epoch 3/3:  58%|█████▊    | 2339/4000 [22:21<19:36,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.223217487335205, Predicted Probability: 0.9617, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.351016998291016, Predicted Probability: 0.0127, Prediction: 0.0

Epoch 3/3:  58%|█████▊    | 2340/4000 [22:22<16:50,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.498700141906738, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.571352243423462, Predicted Probability: 0.0273, Prediction: 0.0

Epoch 3/3:  59%|█████▊    | 2341/4000 [22:22<18:25,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.548418998718262, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.248703002929688, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  59%|█████▊    | 2342/4000 [22:23<18:44,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.527588844299316, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.15106201171875, Predicted Probability: 0.1042, Prediction: 0.0

Epoch 3/3:  59%|█████▊    | 2343/4000 [22:24<19:37,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.077595710754395, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.577888488769531, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  59%|█████▊    | 2344/4000 [22:24<18:07,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.74209213256836, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.369865417480469, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:  59%|█████▊    | 2345/4000 [22:25<15:56,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.620057106018066, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.240964889526367, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  59%|█████▊    | 2346/4000 [22:25<15:46,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.164204597473145, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.844214916229248, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  59%|█████▊    | 2347/4000 [22:26<12:44,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.329390525817871, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.432909965515137, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  59%|█████▊    | 2348/4000 [22:26<11:57,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.933899879455566, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.533151626586914, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:  59%|█████▊    | 2349/4000 [22:27<12:56,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.790137767791748, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.209773063659668, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2350/4000 [22:27<15:01,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.74741268157959, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0564544200897217, Predicted Probability: 0.9551, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2351/4000 [22:28<16:28,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.051570415496826, Predicted Probability: 0.9549, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.666299819946289, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2352/4000 [22:28<15:18,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.344659805297852, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.53984546661377, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2353/4000 [22:29<15:17,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.374015808105469, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.884065628051758, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2354/4000 [22:29<13:39,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.836212158203125, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.09122371673584, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2355/4000 [22:30<15:36,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.226551055908203, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.305579662322998, Predicted Probability: 0.9646, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2356/4000 [22:31<16:52,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.321258783340454, Predicted Probability: 0.9652, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.58031940460205, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2357/4000 [22:31<15:05,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.188272476196289, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.597080230712891, Predicted Probability: 0.9963, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2358/4000 [22:32<17:35,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7238826751708984, Predicted Probability: 0.0236, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.833175659179688, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2359/4000 [22:33<18:33,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.730342864990234, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.6151762008667, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2360/4000 [22:34<19:11,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.0339994430542, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.986667513847351, Predicted Probability: 0.1206, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2361/4000 [22:34<17:50,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.981429100036621, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.3853864669799805, Predicted Probability: 0.0123, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2362/4000 [22:35<18:31,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.299466133117676, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.883615255355835, Predicted Probability: 0.9470, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2363/4000 [22:36<19:06,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.645803451538086, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.590670108795166, Predicted Probability: 0.0697, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2364/4000 [22:36<20:08,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.988037109375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.583131790161133, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2365/4000 [22:37<20:29,  1.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1845455169677734, Predicted Probability: 0.9602, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.985406875610352, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2366/4000 [22:38<20:19,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.51625919342041, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4169013500213623, Predicted Probability: 0.0318, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2367/4000 [22:39<20:17,  1.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.984394073486328, Predicted Probability: 0.9519, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.585979461669922, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2368/4000 [22:39<17:54,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.307178020477295, Predicted Probability: 0.9867, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.976423263549805, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2369/4000 [22:40<18:17,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7686285972595215, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.894240379333496, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2370/4000 [22:41<18:50,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.498917579650879, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.169738531112671, Predicted Probability: 0.1025, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2371/4000 [22:41<14:52,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.867682456970215, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.30068302154541, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2372/4000 [22:41<13:24,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.583806991577148, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.079041481018066, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2373/4000 [22:42<12:27,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.852578163146973, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2347670793533325, Predicted Probability: 0.7747, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2374/4000 [22:42<11:44,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.479499816894531, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.702172756195068, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2375/4000 [22:42<12:39,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.984586715698242, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8427321910858154, Predicted Probability: 0.9790, Prediction: 1.0

Epoch 3/3:  59%|█████▉    | 2376/4000 [22:43<15:45,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.336647033691406, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.250917434692383, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2378/4000 [22:44<13:37,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.631470680236816, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1176095008850098, Predicted Probability: 0.1074, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.690162658691406, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.427667617797852, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  59%|█████▉    | 2379/4000 [22:45<15:50,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.922037124633789, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.5148950815200806, Predicted Probability: 0.1802, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2380/4000 [22:46<17:16,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.80243968963623, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2067654132843018, Predicted Probability: 0.9611, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2381/4000 [22:46<16:42,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.794275760650635, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.602595329284668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2383/4000 [22:47<14:13,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.73703384399414, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.233241558074951, Predicted Probability: 0.9621, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -7.280777931213379, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.43982982635498, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2384/4000 [22:48<16:00,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5286169052124023, Predicted Probability: 0.9261, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.173813819885254, Predicted Probability: 0.0402, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2385/4000 [22:49<17:45,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.524639129638672, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.429786682128906, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2386/4000 [22:50<18:48,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.570413112640381, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.564774513244629, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2387/4000 [22:51<19:29,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.570936679840088, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.375500679016113, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2388/4000 [22:51<19:38,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2803298234939575, Predicted Probability: 0.2175, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.68954849243164, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2389/4000 [22:52<16:52,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.611675262451172, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.686936855316162, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2390/4000 [22:52<17:47,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.0540051460266113, Predicted Probability: 0.1136, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.078786849975586, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2391/4000 [22:53<18:50,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.582979202270508, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.42290210723877, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2392/4000 [22:53<15:22,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.834474563598633, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7700347900390625, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2393/4000 [22:54<17:06,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.45090913772583, Predicted Probability: 0.9693, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.85472297668457, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2394/4000 [22:55<14:59,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.114261627197266, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.45447063446045, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2395/4000 [22:55<16:23,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.903443336486816, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.61892318725586, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2396/4000 [22:56<17:23,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.236628532409668, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7235175371170044, Predicted Probability: 0.1514, Prediction: 0.0

Epoch 3/3:  60%|█████▉    | 2397/4000 [22:57<17:57,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.406938552856445, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4504594802856445, Predicted Probability: 0.9692, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2398/4000 [22:57<15:33,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.220571517944336, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.783438205718994, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  60%|█████▉    | 2399/4000 [22:58<13:50,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.332995414733887, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.740375518798828, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2400/4000 [22:58<14:00,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.778251647949219, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.311902046203613, Predicted Probability: 0.9868, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2401/4000 [22:59<15:31,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.285747528076172, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.683520555496216, Predicted Probability: 0.9755, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2402/4000 [22:59<13:58,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.67297077178955, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.048734664916992, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2403/4000 [23:00<14:02,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4840171337127686, Predicted Probability: 0.0298, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.417628288269043, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2404/4000 [23:00<15:51,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.75949764251709, Predicted Probability: 0.9772, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.497507095336914, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2405/4000 [23:01<16:50,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.526113510131836, Predicted Probability: 0.9893, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.324004650115967, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2406/4000 [23:02<17:42,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.129581451416016, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.689838886260986, Predicted Probability: 0.0091, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2407/4000 [23:02<15:20,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.894797325134277, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.049661636352539, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2408/4000 [23:03<17:04,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.707151412963867, Predicted Probability: 0.0240, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2733099460601807, Predicted Probability: 0.9635, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2409/4000 [23:04<17:45,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.615331649780273, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.724846601486206, Predicted Probability: 0.9765, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2410/4000 [23:04<14:04,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.692428588867188, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.157631874084473, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2411/4000 [23:05<15:41,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.8728911876678467, Predicted Probability: 0.1332, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.688881874084473, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2412/4000 [23:05<15:18,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.298473358154297, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.355970859527588, Predicted Probability: 0.9873, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2413/4000 [23:06<13:40,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.593953132629395, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.641067981719971, Predicted Probability: 0.0096, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2414/4000 [23:07<16:11,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.028858184814453, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.137752532958984, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2415/4000 [23:07<17:25,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.561784744262695, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4043595790863037, Predicted Probability: 0.9678, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2416/4000 [23:08<18:00,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.263684272766113, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.076510906219482, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2417/4000 [23:08<15:32,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.932546138763428, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.619235038757324, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  60%|██████    | 2418/4000 [23:09<15:18,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.245831489562988, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.206855297088623, Predicted Probability: 0.9009, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2419/4000 [23:09<13:36,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.566677093505859, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.549849510192871, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  60%|██████    | 2420/4000 [23:10<13:58,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.400032997131348, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.405462265014648, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2421/4000 [23:11<16:05,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3553261756896973, Predicted Probability: 0.9663, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.8199920654296875, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2422/4000 [23:11<17:20,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.981184005737305, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.404557704925537, Predicted Probability: 0.9678, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2423/4000 [23:12<18:01,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.051219940185547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.558353424072266, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2424/4000 [23:13<18:28,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.27425479888916, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5292692184448242, Predicted Probability: 0.1781, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2425/4000 [23:14<19:05,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.111702919006348, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.371309280395508, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2426/4000 [23:14<19:02,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.564035415649414, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5092463493347168, Predicted Probability: 0.1811, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2427/4000 [23:15<14:55,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.182619094848633, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.253118515014648, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2428/4000 [23:15<13:29,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.812193870544434, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.334680557250977, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2429/4000 [23:16<15:07,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.972170829772949, Predicted Probability: 0.0069, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.322101593017578, Predicted Probability: 0.9652, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2430/4000 [23:16<14:50,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.273885250091553, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.713274955749512, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2431/4000 [23:17<16:14,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9785096645355225, Predicted Probability: 0.2732, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.1491918563842773, Predicted Probability: 0.1044, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2432/4000 [23:17<14:24,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.26784610748291, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.586834907531738, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2433/4000 [23:18<16:23,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1639724969863892, Predicted Probability: 0.7621, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.761028289794922, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2434/4000 [23:19<15:38,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.170836448669434, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.0905251502990723, Predicted Probability: 0.0435, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2435/4000 [23:20<17:20,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.798924446105957, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.5069451332092285, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2436/4000 [23:20<15:02,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.513001441955566, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.948911190032959, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2437/4000 [23:20<13:19,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.355751991271973, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.411458015441895, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2438/4000 [23:21<15:29,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.880336761474609, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.41805362701416, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2439/4000 [23:22<16:31,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5840630531311035, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.181499481201172, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2440/4000 [23:22<14:23,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.73261833190918, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.113115310668945, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2441/4000 [23:23<13:38,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.880329132080078, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.409951210021973, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2442/4000 [23:24<15:58,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.667959213256836, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9986106157302856, Predicted Probability: 0.1193, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2443/4000 [23:24<17:20,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.332651138305664, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.004586696624756, Predicted Probability: 0.0179, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2444/4000 [23:25<13:45,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.62247085571289, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.624014854431152, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2445/4000 [23:25<13:48,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.419772624969482, Predicted Probability: 0.9881, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.450496673583984, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2446/4000 [23:26<15:36,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.511570930480957, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.168734550476074, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  61%|██████    | 2447/4000 [23:27<16:51,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.560835361480713, Predicted Probability: 0.1735, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.980962753295898, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2448/4000 [23:27<17:47,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8640708923339844, Predicted Probability: 0.0540, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.803253173828125, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  61%|██████    | 2449/4000 [23:28<16:34,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.197136402130127, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.718148231506348, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2450/4000 [23:29<17:27,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.414257049560547, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.151709079742432, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2451/4000 [23:29<16:25,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.029308319091797, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.078640937805176, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2452/4000 [23:30<15:02,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.101882934570312, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.35356616973877, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2453/4000 [23:30<14:44,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.65046215057373, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.084863662719727, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2454/4000 [23:31<13:08,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.336482524871826, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.608156204223633, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  61%|██████▏   | 2455/4000 [23:31<14:44,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4706549644470215, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5349910259246826, Predicted Probability: 0.9717, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2456/4000 [23:32<13:13,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.943016052246094, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.95370101928711, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2457/4000 [23:32<12:10,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.111660957336426, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.585493326187134, Predicted Probability: 0.9299, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2458/4000 [23:32<11:34,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.347318649291992, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.105234146118164, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  61%|██████▏   | 2459/4000 [23:33<09:40,  2.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.416592597961426, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.000833511352539, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2460/4000 [23:33<09:41,  2.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.142243385314941, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.385992050170898, Predicted Probability: 0.0123, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2461/4000 [23:34<12:27,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9716776609420776, Predicted Probability: 0.1222, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.111655235290527, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2462/4000 [23:35<14:45,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.951004981994629, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.081637382507324, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2463/4000 [23:35<14:27,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.489789962768555, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.925029754638672, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2464/4000 [23:35<12:57,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.502485275268555, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.063784599304199, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2465/4000 [23:36<10:37,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.266145706176758, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.334773063659668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2466/4000 [23:36<13:20,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.132463455200195, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.142096519470215, Predicted Probability: 0.9942, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2467/4000 [23:37<12:17,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.237344741821289, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.397664070129395, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2468/4000 [23:38<14:28,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.338052272796631, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.511690139770508, Predicted Probability: 0.0290, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2469/4000 [23:38<15:30,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4418528079986572, Predicted Probability: 0.9200, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.025533676147461, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2470/4000 [23:39<14:14,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.507696151733398, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.275609016418457, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2471/4000 [23:39<12:44,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.876373291015625, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.45805549621582, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2472/4000 [23:39<11:48,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.519397258758545, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.900434494018555, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2473/4000 [23:40<12:23,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.041539192199707, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.746688842773438, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2474/4000 [23:40<11:34,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.847909927368164, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.6631441116333, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2475/4000 [23:41<11:02,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.610257148742676, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.783137321472168, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2476/4000 [23:42<13:42,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.184190034866333, Predicted Probability: 0.9602, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.31952953338623, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2477/4000 [23:42<11:07,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.385172843933105, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.174485206604004, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2478/4000 [23:43<13:26,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.147356033325195, Predicted Probability: 0.0058, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.016210556030273, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2479/4000 [23:43<15:46,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.7173662185668945, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.96080207824707, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2480/4000 [23:44<16:45,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9170596599578857, Predicted Probability: 0.9487, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.253631591796875, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2481/4000 [23:45<17:29,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.170358180999756, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.416206359863281, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2482/4000 [23:45<15:20,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.082611083984375, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.799737930297852, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2483/4000 [23:46<18:50,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.267733097076416, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.422880172729492, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2484/4000 [23:47<18:49,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.495454788208008, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.846749305725098, Predicted Probability: 0.9922, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2485/4000 [23:48<18:43,  1.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0166096687316895, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.395000457763672, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2486/4000 [23:48<14:41,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.72866678237915, Predicted Probability: 0.0032, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.470704078674316, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2487/4000 [23:48<13:35,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.094058990478516, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1327667236328125, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2488/4000 [23:49<15:16,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.66459059715271, Predicted Probability: 0.9750, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.071685791015625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2489/4000 [23:50<17:03,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.924190521240234, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.923732757568359, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2490/4000 [23:51<16:07,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.494904518127441, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.101553916931152, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2491/4000 [23:51<16:55,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.159103393554688, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.834910869598389, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2492/4000 [23:52<14:47,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.207300186157227, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.924525260925293, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2493/4000 [23:52<12:24,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.214700698852539, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.297144889831543, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2494/4000 [23:53<14:44,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.099766731262207, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.984203338623047, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2495/4000 [23:53<13:06,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.774723052978516, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.27374267578125, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2496/4000 [23:54<14:54,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.446834564208984, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.835281848907471, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2497/4000 [23:55<16:22,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.866365909576416, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.106527328491211, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  62%|██████▏   | 2498/4000 [23:55<14:15,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.575535774230957, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.653419494628906, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▏   | 2499/4000 [23:56<15:33,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.112651824951172, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.0547456741333, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  62%|██████▎   | 2500/4000 [23:56<15:03,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.512289047241211, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2100929021835327, Predicted Probability: 0.2297, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2501/4000 [23:57<16:05,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.456565856933594, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.665305137634277, Predicted Probability: 0.9965, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2502/4000 [23:58<17:25,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.613016128540039, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.67790412902832, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2503/4000 [23:58<15:04,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.222299575805664, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.006112098693848, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2504/4000 [23:59<13:14,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.982117652893066, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.662522315979004, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2505/4000 [23:59<13:50,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.462271690368652, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4106545448303223, Predicted Probability: 0.0824, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2506/4000 [24:00<15:09,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.050116539001465, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.440584182739258, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2507/4000 [24:01<13:59,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.90152359008789, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.080719947814941, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2508/4000 [24:01<13:51,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4659067392349243, Predicted Probability: 0.1876, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.270462036132812, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2509/4000 [24:02<15:00,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.908677101135254, Predicted Probability: 0.9803, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.140130996704102, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2510/4000 [24:02<13:18,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.824080944061279, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.688069343566895, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2511/4000 [24:03<13:29,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.552046775817871, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.069695949554443, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2512/4000 [24:03<12:12,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.508240699768066, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9273762702941895, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2513/4000 [24:03<10:29,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.603118896484375, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.374951362609863, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2514/4000 [24:04<12:45,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0623526573181152, Predicted Probability: 0.9553, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.582889556884766, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2516/4000 [24:05<11:50,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.339251518249512, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.866460800170898, Predicted Probability: 0.9972, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.783012390136719, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.923423767089844, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2517/4000 [24:06<12:24,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.247162818908691, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.649219036102295, Predicted Probability: 0.9905, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2518/4000 [24:06<11:27,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.198156833648682, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.618728637695312, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2519/4000 [24:07<14:17,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.8384428024292, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.511039733886719, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2520/4000 [24:07<13:14,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.565124988555908, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.425374031066895, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2521/4000 [24:08<12:03,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.353423118591309, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.0904541015625, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2522/4000 [24:08<11:17,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.682937622070312, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.539304733276367, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2523/4000 [24:09<11:09,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.224691390991211, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.869282245635986, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2524/4000 [24:09<11:50,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.371835231781006, Predicted Probability: 0.0853, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.284229278564453, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2525/4000 [24:09<11:04,  2.22it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.137950897216797, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.844151496887207, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2526/4000 [24:10<13:16,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.818611145019531, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.010863780975342, Predicted Probability: 0.9531, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2527/4000 [24:11<14:55,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.654422760009766, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6036722660064697, Predicted Probability: 0.0689, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2528/4000 [24:12<14:30,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.262630462646484, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.00161075592041, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2529/4000 [24:12<14:07,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.948637008666992, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.319108009338379, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2530/4000 [24:13<13:47,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.839625358581543, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7647504806518555, Predicted Probability: 0.9915, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2531/4000 [24:13<13:30,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.458532333374023, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.42227554321289, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2532/4000 [24:14<12:25,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.78244400024414, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.430092811584473, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2533/4000 [24:14<14:34,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.7630720138549805, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.003894805908203, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2534/4000 [24:15<12:09,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.838205337524414, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.224431991577148, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2535/4000 [24:15<14:22,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.189438819885254, Predicted Probability: 0.9604, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.610599517822266, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2536/4000 [24:16<15:42,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.291228294372559, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.47451400756836, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2537/4000 [24:17<16:44,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.772392272949219, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.711721420288086, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  63%|██████▎   | 2538/4000 [24:18<17:01,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3304672241210938, Predicted Probability: 0.0886, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.216324806213379, Predicted Probability: 0.9614, Prediction: 1.0

Epoch 3/3:  63%|██████▎   | 2539/4000 [24:18<14:39,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.875702857971191, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.444378852844238, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  64%|██████▎   | 2540/4000 [24:19<15:54,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.3256754875183105, Predicted Probability: 0.9110, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.20164680480957, Predicted Probability: 0.0055, Prediction: 0.0

Epoch 3/3:  64%|██████▎   | 2541/4000 [24:19<14:03,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.880318641662598, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.612017631530762, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  64%|██████▎   | 2542/4000 [24:20<15:20,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.991056442260742, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2235939502716064, Predicted Probability: 0.9617, Prediction: 1.0

Epoch 3/3:  64%|██████▎   | 2543/4000 [24:21<16:38,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.055319786071777, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.213979721069336, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  64%|██████▎   | 2544/4000 [24:21<16:04,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.755039691925049, Predicted Probability: 0.0598, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.070842742919922, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  64%|██████▎   | 2545/4000 [24:22<13:57,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.812886238098145, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.565269470214844, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  64%|██████▎   | 2546/4000 [24:22<12:30,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.073787689208984, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.761250019073486, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 3/3:  64%|██████▎   | 2547/4000 [24:23<14:09,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.419515609741211, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.4400811195373535, Predicted Probability: 0.1915, Prediction: 0.0

Epoch 3/3:  64%|██████▎   | 2548/4000 [24:23<13:52,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.397722244262695, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.493073463439941, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  64%|██████▎   | 2549/4000 [24:24<14:57,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.146070718765259, Predicted Probability: 0.9588, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.05155444145202637, Predicted Probability: 0.4871, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2550/4000 [24:25<13:08,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.261922836303711, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.03515338897705, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2551/4000 [24:25<14:42,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.272796154022217, Predicted Probability: 0.0138, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.335338592529297, Predicted Probability: 0.0048, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2552/4000 [24:26<13:06,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.138208389282227, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.484885215759277, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2553/4000 [24:27<16:06,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.408618927001953, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.132768630981445, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2554/4000 [24:27<16:41,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.73609733581543, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.693564414978027, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2555/4000 [24:28<17:28,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.705327033996582, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.036121845245361, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2556/4000 [24:29<14:52,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.134093284606934, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.380512237548828, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2557/4000 [24:29<13:03,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.709806442260742, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.015727996826172, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2558/4000 [24:29<11:01,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.391610145568848, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.119034767150879, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2559/4000 [24:30<13:24,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.173337936401367, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.135279655456543, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2560/4000 [24:31<14:34,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.803627967834473, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0442898273468018, Predicted Probability: 0.9545, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2561/4000 [24:32<16:35,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.047914028167725, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.639856338500977, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2562/4000 [24:32<17:14,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.933698654174805, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.91746711730957, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2563/4000 [24:33<18:07,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.902815818786621, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.970421314239502, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2564/4000 [24:34<18:37,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.945527076721191, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.032755374908447, Predicted Probability: 0.0065, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2565/4000 [24:35<18:26,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.174145698547363, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.69558048248291, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2566/4000 [24:36<18:07,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.706218719482422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.568037271499634, Predicted Probability: 0.9288, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2567/4000 [24:36<18:19,  1.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.571897506713867, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.009820938110352, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2568/4000 [24:37<18:25,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.414772033691406, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.22487211227417, Predicted Probability: 0.9946, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2569/4000 [24:38<15:32,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.6866984367370605, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.6629815101623535, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2570/4000 [24:38<16:18,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.681818962097168, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5691585540771484, Predicted Probability: 0.8277, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2571/4000 [24:39<14:05,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.325681686401367, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.757391929626465, Predicted Probability: 0.0031, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2572/4000 [24:39<15:09,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.344151496887207, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.136441230773926, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2573/4000 [24:40<15:53,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0200600624084473, Predicted Probability: 0.9535, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.331686019897461, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2574/4000 [24:40<12:38,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.20045658946037292, Predicted Probability: 0.5499, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.45549488067627, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2575/4000 [24:41<14:06,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.887619018554688, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1316335201263428, Predicted Probability: 0.9582, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2576/4000 [24:41<12:31,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.049718856811523, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.39108142256736755, Predicted Probability: 0.4035, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2577/4000 [24:42<14:11,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.00418472290039, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9157662391662598, Predicted Probability: 0.9486, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2578/4000 [24:43<12:36,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.774009704589844, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.831018447875977, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  64%|██████▍   | 2579/4000 [24:43<12:33,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.607943058013916, Predicted Probability: 0.0686, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.388660430908203, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  64%|██████▍   | 2580/4000 [24:43<11:26,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.83287239074707, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.759185791015625, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2581/4000 [24:44<11:46,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.047573089599609, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.30343246459961, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2582/4000 [24:44<10:48,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.333034515380859, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.919302940368652, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2583/4000 [24:45<11:28,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.078438758850098, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.763209342956543, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2584/4000 [24:46<13:14,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9086997509002686, Predicted Probability: 0.9483, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8712959289550781, Predicted Probability: 0.1334, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2585/4000 [24:46<14:13,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2198965549468994, Predicted Probability: 0.9616, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.41433048248291, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2586/4000 [24:47<12:38,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.508309841156006, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.989981651306152, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2587/4000 [24:47<12:39,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.558079719543457, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.758691787719727, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2588/4000 [24:48<11:57,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.7589030265808105, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.215231895446777, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2589/4000 [24:48<13:26,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.343215227127075, Predicted Probability: 0.9659, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.232396125793457, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2590/4000 [24:49<14:53,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.466246604919434, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.905684947967529, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2591/4000 [24:50<15:56,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.232124328613281, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.252213478088379, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2592/4000 [24:51<16:11,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.790274143218994, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2011451721191406, Predicted Probability: 0.9609, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2593/4000 [24:51<12:45,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.142810821533203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.077119827270508, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2594/4000 [24:52<14:31,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.476484298706055, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4984302520751953, Predicted Probability: 0.0760, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2595/4000 [24:52<12:48,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1192784309387207, Predicted Probability: 0.1072, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.580236434936523, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2596/4000 [24:53<14:28,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.074765205383301, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.347024917602539, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  65%|██████▍   | 2597/4000 [24:53<13:10,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.900460720062256, Predicted Probability: 0.0198, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.265811920166016, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2598/4000 [24:54<11:45,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.674515724182129, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.227690696716309, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  65%|██████▍   | 2599/4000 [24:54<13:47,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.795598983764648, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.854249954223633, Predicted Probability: 0.0077, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2600/4000 [24:55<14:39,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.361137866973877, Predicted Probability: 0.0047, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0358357429504395, Predicted Probability: 0.1155, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2601/4000 [24:56<14:05,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6015523672103882, Predicted Probability: 0.1678, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.468745231628418, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2602/4000 [24:57<15:37,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.091087341308594, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.548887729644775, Predicted Probability: 0.0105, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2603/4000 [24:57<16:00,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.558645248413086, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4572372436523438, Predicted Probability: 0.9694, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2604/4000 [24:58<15:08,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.18489933013916, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.895483016967773, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2605/4000 [24:58<14:35,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.979353904724121, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.00804615020752, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2606/4000 [24:59<12:50,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.536134719848633, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.313591003417969, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2607/4000 [24:59<12:40,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.152244567871094, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.71816349029541, Predicted Probability: 0.9911, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2608/4000 [25:00<11:26,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.256156921386719, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.18025016784668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2609/4000 [25:00<11:44,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.341560363769531, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.35365104675293, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2610/4000 [25:01<10:47,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.948641777038574, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.830536365509033, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2611/4000 [25:01<10:05,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.359280109405518, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.980890274047852, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2612/4000 [25:02<12:28,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.322925090789795, Predicted Probability: 0.9652, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.842235565185547, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2613/4000 [25:03<13:47,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.4618306159973145, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.072024345397949, Predicted Probability: 0.0168, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2614/4000 [25:03<12:18,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.868121147155762, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.944891929626465, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2615/4000 [25:04<14:04,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.40191325545310974, Predicted Probability: 0.5991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.767858505249023, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2616/4000 [25:04<13:35,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.478941917419434, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.862552165985107, Predicted Probability: 0.9923, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2617/4000 [25:05<14:35,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.446442604064941, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.345302581787109, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 3/3:  65%|██████▌   | 2618/4000 [25:06<15:21,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.343379974365234, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4139184951782227, Predicted Probability: 0.9681, Prediction: 1.0

Epoch 3/3:  65%|██████▌   | 2619/4000 [25:07<16:20,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.135644912719727, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.11647891998291, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2621/4000 [25:07<10:19,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.922470092773438, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.603655815124512, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -10.818066596984863, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.823526382446289, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2622/4000 [25:08<12:20,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.3246283531188965, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.101696968078613, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2623/4000 [25:08<13:43,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.167379379272461, Predicted Probability: 0.0021, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.04244613647461, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2624/4000 [25:09<12:15,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.0530548095703125, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.978955268859863, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2625/4000 [25:09<12:54,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.760719299316406, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.343225955963135, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2626/4000 [25:10<10:27,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.19130802154541, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.067667961120605, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2627/4000 [25:10<08:43,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.077542304992676, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.248674392700195, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2628/4000 [25:11<11:56,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.445678234100342, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.894191741943359, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2629/4000 [25:12<14:10,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.75198221206665, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.740633964538574, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2630/4000 [25:12<12:29,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.896421432495117, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.473006725311279, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2631/4000 [25:12<11:24,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.915349006652832, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.569036483764648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2632/4000 [25:13<10:40,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.24856948852539, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.803600311279297, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2633/4000 [25:13<12:48,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.409708023071289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7544258832931519, Predicted Probability: 0.3199, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2634/4000 [25:14<13:55,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.169555187225342, Predicted Probability: 0.9597, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.095470428466797, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2635/4000 [25:15<14:44,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.583913564682007, Predicted Probability: 0.0702, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.340014457702637, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2636/4000 [25:16<15:20,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.458614349365234, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.444886684417725, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2637/4000 [25:16<14:30,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.04976749420166, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.88045597076416, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2638/4000 [25:17<15:22,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.51918363571167, Predicted Probability: 0.0040, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.333421230316162, Predicted Probability: 0.9656, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2639/4000 [25:18<14:24,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.017801284790039, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.5628814697265625, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2640/4000 [25:18<15:01,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.57077407836914, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.194132089614868, Predicted Probability: 0.9606, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2641/4000 [25:19<14:18,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.169157028198242, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.29534912109375, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2642/4000 [25:19<12:38,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.117387771606445, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.1796875, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2643/4000 [25:20<12:38,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: 4.495218276977539, Predicted Probability: 0.9890, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.432191848754883, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2644/4000 [25:20<11:23,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.294404029846191, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.16247844696045, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2645/4000 [25:21<10:32,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.893611907958984, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.092741966247559, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2646/4000 [25:21<09:57,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.52747106552124, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.235358238220215, Predicted Probability: 0.0053, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2647/4000 [25:21<09:27,  2.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.172078132629395, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.928171157836914, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  66%|██████▌   | 2648/4000 [25:22<12:11,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.669914245605469, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.813358306884766, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  66%|██████▌   | 2649/4000 [25:23<12:12,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.48298168182373, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.546454906463623, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:  66%|██████▋   | 2650/4000 [25:23<11:01,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.37617015838623, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.21470832824707, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  66%|██████▋   | 2651/4000 [25:24<12:52,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.145328521728516, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.0609130859375, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  66%|██████▋   | 2652/4000 [25:24<13:53,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7291752099990845, Predicted Probability: 0.1507, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.137054443359375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  66%|██████▋   | 2653/4000 [25:25<15:16,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.939762115478516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.425989151000977, Predicted Probability: 0.0044, Prediction: 0.0

Epoch 3/3:  66%|██████▋   | 2654/4000 [25:26<15:34,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.461867332458496, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.57155704498291, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  66%|██████▋   | 2655/4000 [25:26<13:31,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.481780052185059, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.230454444885254, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▋   | 2656/4000 [25:27<11:59,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.74400520324707, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.410634994506836, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  66%|██████▋   | 2657/4000 [25:28<13:35,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.13812255859375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0436856746673584, Predicted Probability: 0.9545, Prediction: 1.0

Epoch 3/3:  66%|██████▋   | 2658/4000 [25:28<13:05,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.196950435638428, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.656957149505615, Predicted Probability: 0.9906, Prediction: 1.0

Epoch 3/3:  66%|██████▋   | 2659/4000 [25:28<11:39,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.0902419090271, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.678506851196289, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  66%|██████▋   | 2660/4000 [25:29<10:40,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.785395622253418, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.929784774780273, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2661/4000 [25:29<09:55,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.544130802154541, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.01535415649414, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2662/4000 [25:30<11:57,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.388108730316162, Predicted Probability: 0.9955, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.05221939086914, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2663/4000 [25:30<10:53,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.963688850402832, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.564776420593262, Predicted Probability: 0.0103, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2664/4000 [25:31<10:08,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.9960525631904602, Predicted Probability: 0.7303, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.254018783569336, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2665/4000 [25:31<12:04,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.278430938720703, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.279303550720215, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2666/4000 [25:32<10:56,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.85526704788208, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.885187149047852, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2667/4000 [25:32<10:10,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.1333589553833, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.66597318649292, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2668/4000 [25:33<09:36,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.849127769470215, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.757177352905273, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2669/4000 [25:33<11:28,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.291790246963501, Predicted Probability: 0.9641, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -3.5080769062042236, Predicted Probability: 0.0291, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2670/4000 [25:34<10:28,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.963315010070801, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.088990211486816, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2671/4000 [25:34<10:59,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.6199629306793213, Predicted Probability: 0.3498, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.360569953918457, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2672/4000 [25:35<13:07,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.215593338012695, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.789013385772705, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2673/4000 [25:35<10:30,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.388604164123535, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.2417573928833, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2674/4000 [25:36<09:49,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.440084457397461, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.519983768463135, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2675/4000 [25:37<12:42,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.524930953979492, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.844118118286133, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2676/4000 [25:37<14:00,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.293610095977783, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.616680145263672, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2677/4000 [25:38<13:26,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.749321937561035, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.9689359664917, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2678/4000 [25:38<13:06,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.730189323425293, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.388381004333496, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2679/4000 [25:39<11:37,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.336758613586426, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.504388809204102, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2680/4000 [25:39<09:34,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.813837051391602, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.091166496276855, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2681/4000 [25:40<11:31,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.351688385009766, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.7877197265625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2682/4000 [25:40<09:29,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.886332511901855, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.906367301940918, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2683/4000 [25:40<09:06,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.948057174682617, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0753936767578125, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2684/4000 [25:41<11:31,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.509523391723633, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.6534013748168945, Predicted Probability: 0.0035, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2685/4000 [25:42<10:42,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.832973003387451, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.562700271606445, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2686/4000 [25:42<12:20,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.505868911743164, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9094746112823486, Predicted Probability: 0.1290, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2687/4000 [25:43<12:12,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9163894653320312, Predicted Probability: 0.9805, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.115007400512695, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2688/4000 [25:43<11:26,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7744083404541016, Predicted Probability: 0.9776, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.260656356811523, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2689/4000 [25:44<10:50,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.470571517944336, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.7671834826469421, Predicted Probability: 0.6829, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2690/4000 [25:44<10:05,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.451149940490723, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.890327453613281, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2691/4000 [25:45<11:46,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.355400800704956, Predicted Probability: 0.9134, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.63665771484375, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.575743675231934, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2692/4000 [25:45<09:33,  2.28it/s]

Data point 2: Actual Class: 1.0, Final Logit: 12.003552436828613, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2693/4000 [25:46<11:28,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.869125366210938, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5258820056915283, Predicted Probability: 0.0741, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2694/4000 [25:46<12:46,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.746702671051025, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.24866771697998, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2695/4000 [25:47<11:26,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2639918327331543, Predicted Probability: 0.0368, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.109489440917969, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2696/4000 [25:48<13:00,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.642590045928955, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.814110279083252, Predicted Probability: 0.0080, Prediction: 0.0

Epoch 3/3:  67%|██████▋   | 2697/4000 [25:48<11:27,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.943059921264648, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.310580253601074, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2698/4000 [25:48<09:24,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.765571594238281, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.471924781799316, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  67%|██████▋   | 2699/4000 [25:49<08:59,  2.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.718988418579102, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.190512180328369, Predicted Probability: 0.0149, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2700/4000 [25:49<07:36,  2.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.905854225158691, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.604199409484863, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2701/4000 [25:49<10:13,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.992720603942871, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.092628479003906, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2702/4000 [25:50<11:46,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.491884231567383, Predicted Probability: 0.9236, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.898368835449219, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2703/4000 [25:51<10:37,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.162930488586426, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.403386116027832, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2704/4000 [25:51<12:06,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.1597903966903687, Predicted Probability: 0.7613, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.996772766113281, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2705/4000 [25:52<13:27,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.19532299041748, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2040491104125977, Predicted Probability: 0.0390, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2706/4000 [25:53<14:11,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.784850597381592, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.967081069946289, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2707/4000 [25:53<12:21,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.409382343292236, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9947458505630493, Predicted Probability: 0.8802, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2708/4000 [25:54<11:02,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.362883567810059, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.348162651062012, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2709/4000 [25:54<12:26,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.258700132369995, Predicted Probability: 0.9054, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.360030174255371, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2710/4000 [25:55<13:33,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.11350154876709, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.125823020935059, Predicted Probability: 0.9978, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2711/4000 [25:55<10:48,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.65805435180664, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.82076358795166, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2712/4000 [25:56<09:54,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.742133140563965, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.354294300079346, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2713/4000 [25:56<10:30,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.314824104309082, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.435988903045654, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2714/4000 [25:57<12:52,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.043299674987793, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.761371612548828, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2715/4000 [25:57<11:29,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9997854232788086, Predicted Probability: 0.9526, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.588984489440918, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2716/4000 [25:58<12:42,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.495017051696777, Predicted Probability: 0.9959, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.706256866455078, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2717/4000 [25:58<11:11,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.413864135742188, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.777804374694824, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2718/4000 [25:59<11:14,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.337449550628662, Predicted Probability: 0.0343, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.349628925323486, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2719/4000 [26:00<12:59,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1994686126708984, Predicted Probability: 0.2316, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.530038833618164, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2720/4000 [26:00<10:23,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.557417869567871, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 2.304220676422119, Predicted Probability: 0.9092, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2721/4000 [26:01<12:21,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.708057403564453, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.824466228485107, Predicted Probability: 0.9920, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2722/4000 [26:02<13:40,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.139448165893555, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.010329246520996, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2723/4000 [26:02<14:26,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.834144592285156, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.112884521484375, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2724/4000 [26:03<11:27,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.185306549072266, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.122627258300781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2725/4000 [26:03<13:29,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.869339942932129, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.689877986907959, Predicted Probability: 0.8442, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2726/4000 [26:04<11:57,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.294139862060547, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.688472747802734, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2727/4000 [26:05<13:14,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.111908912658691, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.654098510742188, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2728/4000 [26:05<12:42,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.800711631774902, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.220159530639648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2729/4000 [26:06<11:13,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.358603477478027, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.06019401550293, Predicted Probability: 0.0170, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2730/4000 [26:06<10:12,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.52750301361084, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.069447040557861, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2731/4000 [26:07<12:06,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.091320991516113, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.125998497009277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2732/4000 [26:07<13:10,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.291109085083008, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.5454370975494385, Predicted Probability: 0.8243, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2733/4000 [26:08<11:34,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.810865879058838, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.331569194793701, Predicted Probability: 0.9870, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2734/4000 [26:09<13:02,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.592411994934082, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2790462970733643, Predicted Probability: 0.9071, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2735/4000 [26:09<14:14,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.633123397827148, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.856619834899902, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2736/4000 [26:10<12:23,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.767282962799072, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.38089656829834, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2737/4000 [26:11<13:19,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.519408702850342, Predicted Probability: 0.9255, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.412664413452148, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2738/4000 [26:11<13:59,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1322951316833496, Predicted Probability: 0.8940, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.64452838897705, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  68%|██████▊   | 2739/4000 [26:12<14:13,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0279762744903564, Predicted Probability: 0.0462, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.687272071838379, Predicted Probability: 0.9756, Prediction: 1.0

Epoch 3/3:  68%|██████▊   | 2740/4000 [26:13<14:47,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2814724445343018, Predicted Probability: 0.9073, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.380945205688477, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  69%|██████▊   | 2741/4000 [26:14<15:20,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9082014560699463, Predicted Probability: 0.9803, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.999366760253906, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▊   | 2742/4000 [26:14<13:08,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.416036605834961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.805602073669434, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▊   | 2743/4000 [26:15<14:42,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.234557151794434, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.19461727142334, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  69%|██████▊   | 2744/4000 [26:15<13:41,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.677770614624023, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1399126052856445, Predicted Probability: 0.9843, Prediction: 1.0

Epoch 3/3:  69%|██████▊   | 2745/4000 [26:16<10:51,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1188275814056396, Predicted Probability: 0.8927, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.067972183227539, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▊   | 2746/4000 [26:16<12:14,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.296047210693359, Predicted Probability: 0.9866, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.093843460083008, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▊   | 2747/4000 [26:16<09:51,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.86234188079834, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.702879905700684, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▊   | 2748/4000 [26:17<11:32,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4315977096557617, Predicted Probability: 0.9192, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.830951690673828, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  69%|██████▊   | 2749/4000 [26:18<12:46,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.346110343933105, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.6127699613571167, Predicted Probability: 0.6486, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2750/4000 [26:19<13:28,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.101990699768066, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.107358932495117, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2751/4000 [26:19<14:14,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.28048324584961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -1.402185320854187, Predicted Probability: 0.1975, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2752/4000 [26:20<11:17,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.723461151123047, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.117060661315918, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2753/4000 [26:20<12:43,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.018519878387451, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.405064582824707, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2754/4000 [26:21<14:09,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.682952404022217, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.887870788574219, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2755/4000 [26:22<14:53,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.89482593536377, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3328773975372314, Predicted Probability: 0.9116, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2756/4000 [26:23<14:56,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.7774770259857178, Predicted Probability: 0.0586, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.33053970336914, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2757/4000 [26:24<15:09,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.614184856414795, Predicted Probability: 0.0098, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.717449188232422, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2759/4000 [26:25<12:14,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.642892837524414, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.126787185668945, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.2171630859375, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.019877433776855, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2760/4000 [26:25<13:31,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.900421142578125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.041000366210938, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2761/4000 [26:26<11:51,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.757171630859375, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.935373306274414, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2762/4000 [26:26<11:42,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.779517650604248, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.2888922691345215, Predicted Probability: 0.9865, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2763/4000 [26:27<10:32,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.693748474121094, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.485297203063965, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2764/4000 [26:27<09:41,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.32533597946167, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.885141372680664, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2765/4000 [26:28<11:46,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.686373710632324, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.455512523651123, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2766/4000 [26:29<13:15,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.285362720489502, Predicted Probability: 0.0361, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.889902114868164, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2767/4000 [26:29<11:37,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.74821662902832, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.4574969708919525, Predicted Probability: 0.6124, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2768/4000 [26:30<12:47,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.032747745513916, Predicted Probability: 0.0065, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.34367561340332, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2769/4000 [26:30<11:19,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.464909553527832, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.313860893249512, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2770/4000 [26:31<13:10,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.729789733886719, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.383973121643066, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2771/4000 [26:32<12:43,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.27918815612793, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.302963256835938, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2772/4000 [26:32<10:35,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.06124496459961, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.2957763671875, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2773/4000 [26:32<09:47,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.52980899810791, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.354066848754883, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2774/4000 [26:33<09:14,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.585122108459473, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.183854579925537, Predicted Probability: 0.9850, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2775/4000 [26:34<11:18,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.527517557144165, Predicted Probability: 0.9715, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.377798080444336, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2776/4000 [26:34<09:35,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.075319290161133, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.515101432800293, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2777/4000 [26:35<11:04,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.276314735412598, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2497401237487793, Predicted Probability: 0.0954, Prediction: 0.0

Epoch 3/3:  69%|██████▉   | 2778/4000 [26:35<10:12,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.769862174987793, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.032784461975098, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  69%|██████▉   | 2779/4000 [26:36<11:28,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.957691192626953, Predicted Probability: 0.9506, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.55075454711914, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2780/4000 [26:36<11:55,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.18898344039917, Predicted Probability: 0.9945, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.953427314758301, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2782/4000 [26:37<10:30,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.587126731872559, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.124208450317383, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 7.683737754821777, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.6327948570251465, Predicted Probability: 0.9904, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2783/4000 [26:38<09:34,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.507450580596924, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.986828804016113, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2784/4000 [26:38<11:07,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.571563243865967, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.4337334632873535, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2785/4000 [26:39<11:01,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.86606764793396, Predicted Probability: 0.9795, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.8190226554870605, Predicted Probability: 0.9970, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2786/4000 [26:39<09:59,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.40836238861084, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.514072418212891, Predicted Probability: 0.9960, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2787/4000 [26:40<11:24,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.838672161102295, Predicted Probability: 0.0553, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.074361801147461, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2788/4000 [26:41<12:29,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6864519119262695, Predicted Probability: 0.0638, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.085089683532715, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2789/4000 [26:41<13:09,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.920344114303589, Predicted Probability: 0.9488, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.875215530395508, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2790/4000 [26:42<11:24,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.517691612243652, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.700539588928223, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2791/4000 [26:43<12:30,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.85363483428955, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.4295549392700195, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2792/4000 [26:43<09:58,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.851839065551758, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.960668563842773, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2793/4000 [26:44<11:26,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.989473342895508, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0009589195251465, Predicted Probability: 0.9526, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2794/4000 [26:44<10:12,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.96921443939209, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.226190090179443, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2795/4000 [26:45<14:11,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.544629096984863, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.81605339050293, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2796/4000 [26:46<14:19,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.514812469482422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.7479546070098877, Predicted Probability: 0.8517, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2797/4000 [26:47<14:26,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.759331703186035, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.912276029586792, Predicted Probability: 0.0516, Prediction: 0.0

Epoch 3/3:  70%|██████▉   | 2798/4000 [26:47<13:26,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.816564559936523, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.34505558013916, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  70%|██████▉   | 2799/4000 [26:48<12:39,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9371466636657715, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5111029148101807, Predicted Probability: 0.9249, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2800/4000 [26:48<11:01,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.650004386901855, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.224618911743164, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2801/4000 [26:49<11:57,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.080361366271973, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.2037880420684814, Predicted Probability: 0.7692, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2802/4000 [26:49<12:55,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.048120498657227, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.85921311378479, Predicted Probability: 0.9458, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2803/4000 [26:50<13:50,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.550920009613037, Predicted Probability: 0.0104, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.876263380050659, Predicted Probability: 0.9797, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2804/4000 [26:51<14:32,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.352238655090332, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.702182769775391, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2805/4000 [26:52<14:31,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.42034912109375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2046000957489014, Predicted Probability: 0.9007, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2806/4000 [26:53<14:47,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.794177055358887, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.097917556762695, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2807/4000 [26:53<15:09,  1.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.085079193115234, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.51686954498291, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2808/4000 [26:54<14:00,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.708513259887695, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2606382369995117, Predicted Probability: 0.9056, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2809/4000 [26:55<14:10,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.648719549179077, Predicted Probability: 0.0661, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.640265941619873, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2810/4000 [26:55<13:08,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.882633209228516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.5829193592071533, Predicted Probability: 0.0270, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2811/4000 [26:56<11:22,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.860197067260742, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -7.005642414093018, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2812/4000 [26:56<12:16,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7114246487617493, Predicted Probability: 0.6707, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.788240432739258, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2813/4000 [26:57<13:16,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.7675697803497314, Predicted Probability: 0.6830, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.260838508605957, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2814/4000 [26:58<11:37,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.360447883605957, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.905900001525879, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2815/4000 [26:58<12:23,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.153956174850464, Predicted Probability: 0.9591, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.460920333862305, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2816/4000 [26:59<10:58,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.792265892028809, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.046116828918457, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2817/4000 [26:59<12:03,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6281373500823975, Predicted Probability: 0.0673, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.871337890625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2818/4000 [27:00<10:37,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.10163402557373, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.558361053466797, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  70%|███████   | 2819/4000 [27:00<11:48,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2972793579101562, Predicted Probability: 0.9643, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.533553600311279, Predicted Probability: 0.0039, Prediction: 0.0

Epoch 3/3:  70%|███████   | 2820/4000 [27:01<10:29,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.750813484191895, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.90242862701416, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2821/4000 [27:01<09:38,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.278400421142578, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.714967727661133, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2822/4000 [27:02<10:00,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5661492347717285, Predicted Probability: 0.9897, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.919930458068848, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2823/4000 [27:02<09:11,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.618976593017578, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 3.4675958156585693, Predicted Probability: 0.9698, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2824/4000 [27:03<10:51,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.350801467895508, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.220177173614502, Predicted Probability: 0.9616, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2825/4000 [27:03<08:47,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.936473846435547, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.160297393798828, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2826/4000 [27:03<08:15,  2.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.97943115234375, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7687426805496216, Predicted Probability: 0.1457, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2827/4000 [27:04<10:05,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.43282413482666, Predicted Probability: 0.9687, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.313507080078125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2828/4000 [27:05<11:20,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.749284744262695, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2255287170410156, Predicted Probability: 0.9618, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2829/4000 [27:05<10:12,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.364310264587402, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.765202522277832, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2830/4000 [27:06<11:23,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.55974006652832, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.829770803451538, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2831/4000 [27:06<10:08,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.360688209533691, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.706565856933594, Predicted Probability: 0.0090, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.253266334533691, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2832/4000 [27:07<08:16,  2.35it/s]

Data point 2: Actual Class: 0.0, Final Logit: -10.601820945739746, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2833/4000 [27:07<09:24,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.07423210144043, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.426569938659668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2834/4000 [27:08<11:00,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.21236801147461, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.7451558113098145, Predicted Probability: 0.9914, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2835/4000 [27:08<09:15,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.644367218017578, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.938220977783203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.766622543334961, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2836/4000 [27:08<07:38,  2.54it/s]

Data point 2: Actual Class: 0.0, Final Logit: -9.409429550170898, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2837/4000 [27:09<07:35,  2.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.405876159667969, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.282350540161133, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2838/4000 [27:09<07:32,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.635994911193848, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.13147258758545, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2839/4000 [27:10<09:30,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.859210968017578, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.65053939819336, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2840/4000 [27:11<10:53,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.420166969299316, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4113898277282715, Predicted Probability: 0.9681, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2841/4000 [27:11<10:11,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.712828636169434, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.943343162536621, Predicted Probability: 0.0071, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2842/4000 [27:11<08:42,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.55064582824707, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.748554229736328, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2843/4000 [27:12<08:17,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.294699668884277, Predicted Probability: 0.0050, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5899338722229004, Predicted Probability: 0.9731, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2844/4000 [27:12<08:57,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.08377456665039, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.46061897277832, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2845/4000 [27:13<10:40,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2194191813468933, Predicted Probability: 0.4454, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.84444808959961, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████   | 2846/4000 [27:14<10:06,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.83092737197876, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.258957862854004, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2847/4000 [27:14<09:09,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.296968460083008, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.70294189453125, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2848/4000 [27:15<10:40,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.325013160705566, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.644477367401123, Predicted Probability: 0.9905, Prediction: 1.0

Epoch 3/3:  71%|███████   | 2849/4000 [27:15<11:50,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1956026554107666, Predicted Probability: 0.2323, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.752603530883789, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████▏  | 2850/4000 [27:16<10:49,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.109744548797607, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.647095680236816, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 3/3:  71%|███████▏  | 2851/4000 [27:16<09:46,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.451525688171387, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.372150421142578, Predicted Probability: 0.9954, Prediction: 1.0

Epoch 3/3:  71%|███████▏  | 2852/4000 [27:17<11:04,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.70155668258667, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.28606128692627, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  71%|███████▏  | 2853/4000 [27:18<12:08,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.161779403686523, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.9946746826171875, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  71%|███████▏  | 2854/4000 [27:18<10:39,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.413546562194824, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.123689651489258, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████▏  | 2855/4000 [27:19<09:37,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.780920028686523, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.724681854248047, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  71%|███████▏  | 2856/4000 [27:19<11:04,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.094815254211426, Predicted Probability: 0.0164, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.013506889343262, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  71%|███████▏  | 2857/4000 [27:20<12:21,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.351644515991211, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.29916763305664, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  71%|███████▏  | 2858/4000 [27:21<12:45,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.33975887298584, Predicted Probability: 0.0129, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2068490982055664, Predicted Probability: 0.9611, Prediction: 1.0

Epoch 3/3:  71%|███████▏  | 2859/4000 [27:22<13:08,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.531005859375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.041511058807373, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2860/4000 [27:22<13:26,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1095693111419678, Predicted Probability: 0.9573, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.5189208984375, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2861/4000 [27:23<14:05,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.956019401550293, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.71587610244751, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2862/4000 [27:24<11:58,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.76081371307373, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.570971488952637, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2863/4000 [27:24<11:28,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.386098861694336, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.4653544425964355, Predicted Probability: 0.9886, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2864/4000 [27:25<12:22,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.863287448883057, Predicted Probability: 0.0077, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.9495722055435181, Predicted Probability: 0.7210, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2865/4000 [27:25<10:49,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.472325325012207, Predicted Probability: 0.0301, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.194670677185059, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2866/4000 [27:26<09:46,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.240659713745117, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.449131965637207, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2867/4000 [27:26<08:57,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.0485600233078003, Predicted Probability: 0.2595, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.38017463684082, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2868/4000 [27:27<10:19,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7747411727905273, Predicted Probability: 0.9413, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.972938537597656, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2869/4000 [27:27<09:45,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.417365074157715, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.829254627227783, Predicted Probability: 0.9921, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2870/4000 [27:28<08:55,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.567391872406006, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.22472858428955, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2871/4000 [27:28<08:20,  2.26it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.394404411315918, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.087876319885254, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2872/4000 [27:28<07:59,  2.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.434772491455078, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.97612476348877, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2873/4000 [27:29<10:17,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.136355876922607, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.095029830932617, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2874/4000 [27:30<11:24,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.99638557434082, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5729339122772217, Predicted Probability: 0.0709, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2875/4000 [27:30<11:26,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.457713603973389, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.11367130279541, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2876/4000 [27:31<12:44,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5399065017700195, Predicted Probability: 0.9894, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.643072128295898, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2877/4000 [27:32<13:02,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.9151811599731445, Predicted Probability: 0.8716, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5306148529052734, Predicted Probability: 0.9715, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2878/4000 [27:32<11:37,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.05943775177002, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.271855354309082, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2879/4000 [27:33<12:24,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.854063034057617, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.048670530319214, Predicted Probability: 0.9547, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2880/4000 [27:33<09:51,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.831768989562988, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.980761528015137, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2881/4000 [27:34<11:06,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8154544830322266, Predicted Probability: 0.9435, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.86923885345459, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2882/4000 [27:34<08:55,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.380273818969727, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 12.065223693847656, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2883/4000 [27:35<10:24,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7590107917785645, Predicted Probability: 0.1469, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.674298286437988, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2884/4000 [27:36<09:20,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.458436012268066, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.325045585632324, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2885/4000 [27:36<10:47,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.952719211578369, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.257164001464844, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2886/4000 [27:37<11:37,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.561732292175293, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.444608211517334, Predicted Probability: 0.0309, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2887/4000 [27:38<12:28,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.681673049926758, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.430583477020264, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2888/4000 [27:38<11:20,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7305908203125, Predicted Probability: 0.9388, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.66347599029541, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2889/4000 [27:39<12:09,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4162039756774902, Predicted Probability: 0.9682, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.833690643310547, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2890/4000 [27:40<11:35,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.237957954406738, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.996845245361328, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2891/4000 [27:40<11:14,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.174528121948242, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.400566101074219, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2892/4000 [27:41<11:20,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.972921371459961, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.029283046722412, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2893/4000 [27:42<12:45,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.593378067016602, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.474306106567383, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2894/4000 [27:42<11:59,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.557153224945068, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.991060256958008, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2895/4000 [27:43<12:42,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.8072357177734375, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.4380059242248535, Predicted Probability: 0.9957, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2896/4000 [27:43<10:59,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.12158203125, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8122897148132324, Predicted Probability: 0.0216, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2897/4000 [27:44<08:49,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.509923934936523, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.588888168334961, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  72%|███████▏  | 2898/4000 [27:44<10:11,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.310019493103027, Predicted Probability: 0.9951, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.137062072753906, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  72%|███████▏  | 2899/4000 [27:45<11:11,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.5839412212371826, Predicted Probability: 0.0702, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.15803861618042, Predicted Probability: 0.0408, Prediction: 0.0

Epoch 3/3:  72%|███████▎  | 2900/4000 [27:46<11:53,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.331090927124023, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.68349838256836, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2901/4000 [27:47<12:25,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.636239528656006, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.282791137695312, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2902/4000 [27:47<11:41,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9134321212768555, Predicted Probability: 0.9804, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.948346138000488, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2903/4000 [27:47<10:16,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.776456594467163, Predicted Probability: 0.0224, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.336701393127441, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2904/4000 [27:48<11:18,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.85479736328125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.188636302947998, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2905/4000 [27:48<09:02,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.8338518142700195, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.485851287841797, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2906/4000 [27:49<07:25,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.770676612854004, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.413140296936035, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2907/4000 [27:49<06:39,  2.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.017853736877441, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -3.633152484893799, Predicted Probability: 0.0258, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2908/4000 [27:50<08:59,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.223958969116211, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.006597518920898, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2909/4000 [27:51<10:40,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.803780555725098, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7973291873931885, Predicted Probability: 0.0219, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2910/4000 [27:51<08:57,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.777206420898438, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.74301528930664, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2911/4000 [27:51<08:16,  2.19it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.495703220367432, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.286532402038574, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2912/4000 [27:52<10:00,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.470546245574951, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.6465585231781006, Predicted Probability: 0.0662, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2913/4000 [27:53<11:21,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.0699663162231445, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.927759647369385, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2914/4000 [27:53<09:26,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.18886947631836, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.214320182800293, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2915/4000 [27:54<10:46,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.365502834320068, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.921074390411377, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2916/4000 [27:54<09:33,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.865788459777832, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.052152633666992, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2917/4000 [27:54<08:37,  2.09it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.043709754943848, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.296029090881348, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2918/4000 [27:55<10:21,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.086952209472656, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4716644287109375, Predicted Probability: 0.0779, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2919/4000 [27:56<08:21,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7755563259124756, Predicted Probability: 0.0224, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.042609214782715, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2920/4000 [27:56<10:08,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.938505172729492, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.787286639213562, Predicted Probability: 0.6872, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2921/4000 [27:57<09:03,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.747614860534668, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.825390815734863, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2922/4000 [27:57<10:33,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.290569305419922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.591423988342285, Predicted Probability: 0.0100, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2923/4000 [27:58<11:37,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.588686943054199, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.907071113586426, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2924/4000 [27:59<13:00,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.307347297668457, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.996820449829102, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2925/4000 [28:00<13:54,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.49056625366211, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.031890869140625, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2926/4000 [28:00<11:43,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4471306800842285, Predicted Probability: 0.9884, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.872796058654785, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2927/4000 [28:01<10:14,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.3704195022583, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.581092834472656, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2928/4000 [28:02<11:15,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.4846817255020142, Predicted Probability: 0.8153, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.066591739654541, Predicted Probability: 0.0168, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2929/4000 [28:02<11:44,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.230819702148438, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0908639430999756, Predicted Probability: 0.9565, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2930/4000 [28:03<11:25,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.600581169128418, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.8930318355560303, Predicted Probability: 0.0525, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2931/4000 [28:04<12:00,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.974496841430664, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.42943811416626, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2932/4000 [28:04<11:14,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.61906909942627, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.688317775726318, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2933/4000 [28:05<12:08,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.89292573928833, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.339662551879883, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2934/4000 [28:06<12:16,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.235001564025879, Predicted Probability: 0.0020, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5963220596313477, Predicted Probability: 0.0694, Prediction: 0.0

Epoch 3/3:  73%|███████▎  | 2935/4000 [28:06<10:30,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.776901245117188, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.181498527526855, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2936/4000 [28:06<09:23,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.834150314331055, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.783886909484863, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2937/4000 [28:07<09:31,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.81218433380127, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.659368515014648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2938/4000 [28:08<09:29,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6001105308532715, Predicted Probability: 0.0100, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.00179386138916, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  73%|███████▎  | 2939/4000 [28:08<08:36,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.080851554870605, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.888606071472168, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  74%|███████▎  | 2940/4000 [28:08<08:05,  2.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.905339241027832, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.840034484863281, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  74%|███████▎  | 2941/4000 [28:09<09:41,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.780728340148926, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.008150100708008, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  74%|███████▎  | 2942/4000 [28:10<10:44,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9387779235839844, Predicted Probability: 0.9497, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.52903938293457, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  74%|███████▎  | 2943/4000 [28:11<11:20,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3437659740448, Predicted Probability: 0.0876, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.997368812561035, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  74%|███████▎  | 2944/4000 [28:11<10:51,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.873181343078613, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.5775766372680664, Predicted Probability: 0.0706, Prediction: 0.0

Epoch 3/3:  74%|███████▎  | 2945/4000 [28:11<09:36,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.583151340484619, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.678757667541504, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  74%|███████▎  | 2946/4000 [28:12<10:48,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.207000732421875, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.196899890899658, Predicted Probability: 0.9852, Prediction: 1.0

Epoch 3/3:  74%|███████▎  | 2947/4000 [28:13<11:58,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.8439784049987793, Predicted Probability: 0.0550, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.071669578552246, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  74%|███████▎  | 2948/4000 [28:14<12:27,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.434633255004883, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.970996856689453, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  74%|███████▎  | 2949/4000 [28:15<12:45,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5459699630737305, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.49400520324707, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2950/4000 [28:15<10:02,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.25240421295166, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 11.087308883666992, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2951/4000 [28:15<09:54,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.671542167663574, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.43435525894165, Predicted Probability: 0.0043, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2952/4000 [28:16<08:52,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.120922088623047, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.344382286071777, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2953/4000 [28:16<10:09,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.10734224319458, Predicted Probability: 0.9572, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 3.406926155090332, Predicted Probability: 0.9679, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2954/4000 [28:17<11:22,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.13973617553711, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.7918424606323242, Predicted Probability: 0.1428, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2955/4000 [28:18<11:58,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.2425537109375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.498994827270508, Predicted Probability: 0.0041, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2956/4000 [28:18<10:15,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.565662860870361, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.69621753692627, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2957/4000 [28:19<09:09,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.281261444091797, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.05952262878418, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2958/4000 [28:19<07:28,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.794090270996094, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.205320358276367, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2959/4000 [28:19<07:04,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.818943977355957, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.58573055267334, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2960/4000 [28:20<08:08,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.282361030578613, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.802027702331543, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2961/4000 [28:21<09:56,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.528570175170898, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.456453323364258, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2962/4000 [28:21<09:15,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.04685115814209, Predicted Probability: 0.9936, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.806838035583496, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2963/4000 [28:21<07:31,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.886935234069824, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.773178100585938, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2964/4000 [28:22<09:07,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.16562888026237488, Predicted Probability: 0.4587, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.56549072265625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2965/4000 [28:23<08:20,  2.07it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.072324752807617, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.294036865234375, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2966/4000 [28:23<07:42,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.926458358764648, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.994545936584473, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2967/4000 [28:24<09:07,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.883270740509033, Predicted Probability: 0.9470, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.683696746826172, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2968/4000 [28:24<10:22,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.847971439361572, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.963853120803833, Predicted Probability: 0.9509, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2969/4000 [28:25<11:08,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.795005798339844, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.252543449401855, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2970/4000 [28:26<11:27,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.663473129272461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.102844476699829, Predicted Probability: 0.9570, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2971/4000 [28:26<10:48,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.10327540338039398, Predicted Probability: 0.5258, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8447940349578857, Predicted Probability: 0.9791, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2972/4000 [28:27<11:21,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.762271404266357, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.695753574371338, Predicted Probability: 0.9909, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2973/4000 [28:28<09:50,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.304743766784668, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.217118263244629, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2974/4000 [28:28<09:57,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6862428188323975, Predicted Probability: 0.9755, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.173912048339844, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2975/4000 [28:28<08:01,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.14621353149414, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.53720474243164, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2976/4000 [28:29<07:27,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.452577590942383, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.371400833129883, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2977/4000 [28:29<07:09,  2.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.635784149169922, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.600203037261963, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  74%|███████▍  | 2978/4000 [28:30<08:54,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.176290988922119, Predicted Probability: 0.9599, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.927963256835938, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2979/4000 [28:31<10:33,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.535796165466309, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.879630088806152, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 3/3:  74%|███████▍  | 2980/4000 [28:31<11:14,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.582647800445557, Predicted Probability: 0.9899, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.86468505859375, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2981/4000 [28:32<08:59,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.714481353759766, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.0286028385162354, Predicted Probability: 0.1162, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2982/4000 [28:32<09:05,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.418269157409668, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.66071605682373, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2983/4000 [28:33<10:01,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.285569667816162, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.982847213745117, Predicted Probability: 0.9518, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2984/4000 [28:33<08:02,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.23482608795166, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1547887325286865, Predicted Probability: 0.8961, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2985/4000 [28:34<07:25,  2.28it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.560968399047852, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.983058452606201, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2986/4000 [28:34<08:50,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.958763599395752, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.23652444779872894, Predicted Probability: 0.4411, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2987/4000 [28:35<08:03,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.48344898223877, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.59869384765625, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2988/4000 [28:35<09:18,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.542278528213501, Predicted Probability: 0.0281, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1777751445770264, Predicted Probability: 0.9600, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2989/4000 [28:36<10:14,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1648519039154053, Predicted Probability: 0.9595, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.19118881225586, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2990/4000 [28:37<10:17,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.881270885467529, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.22274398803711, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2991/4000 [28:37<10:54,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.098762035369873, Predicted Probability: 0.9568, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.625650882720947, Predicted Probability: 0.0097, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2992/4000 [28:38<11:12,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.677677154541016, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1952431201934814, Predicted Probability: 0.9607, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2993/4000 [28:39<11:31,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.047126770019531, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2710354328155518, Predicted Probability: 0.9634, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2994/4000 [28:40<11:46,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.751370906829834, Predicted Probability: 0.9968, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.96900463104248, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2995/4000 [28:40<10:30,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.035686492919922, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.981483459472656, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2996/4000 [28:40<09:10,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.393082618713379, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.834670066833496, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▍  | 2997/4000 [28:41<10:13,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1066911220550537, Predicted Probability: 0.9572, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.168050765991211, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2998/4000 [28:42<11:01,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.5780205726623535, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.051965713500977, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  75%|███████▍  | 2999/4000 [28:42<09:57,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.206468105316162, Predicted Probability: 0.0147, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.568169593811035, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3000/4000 [28:43<10:28,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4521281719207764, Predicted Probability: 0.9693, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.919709205627441, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  75%|███████▌  | 3001/4000 [28:43<09:10,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.699041366577148, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.603534698486328, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3002/4000 [28:44<10:13,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.773919105529785, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.178991317749023, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 3/3:  75%|███████▌  | 3003/4000 [28:44<08:12,  2.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.46371078491211, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.329824447631836, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3004/4000 [28:45<08:30,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.819586277008057, Predicted Probability: 0.9920, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.460343360900879, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3005/4000 [28:45<07:47,  2.13it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.49929141998291, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.991997718811035, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  75%|███████▌  | 3006/4000 [28:46<06:27,  2.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.810919761657715, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.330069541931152, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3007/4000 [28:46<05:33,  2.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.564518928527832, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.65792465209961, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3008/4000 [28:47<07:37,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.528779983520508, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.386418342590332, Predicted Probability: 0.9673, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3009/4000 [28:47<06:20,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.7062406539917, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.290191650390625, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3010/4000 [28:47<06:36,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.108504772186279, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.510460376739502, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3011/4000 [28:48<08:36,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.556306838989258, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.08094310760498, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  75%|███████▌  | 3012/4000 [28:48<07:06,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.006582260131836, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.24775505065918, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3013/4000 [28:49<08:36,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.412120819091797, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.782871246337891, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3014/4000 [28:50<08:48,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.287959098815918, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.255541801452637, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3015/4000 [28:50<08:02,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.48917293548584, Predicted Probability: 0.9985, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.993067741394043, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3016/4000 [28:50<07:46,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.473127365112305, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.039879322052002, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3017/4000 [28:51<07:34,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2587313652038574, Predicted Probability: 0.9054, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.918994426727295, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3018/4000 [28:51<08:04,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.565305709838867, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.35634922981262207, Predicted Probability: 0.5882, Prediction: 1.0

Epoch 3/3:  75%|███████▌  | 3019/4000 [28:52<08:21,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.783090591430664, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.803735733032227, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3020/4000 [28:53<09:21,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.836542129516602, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.988551139831543, Predicted Probability: 0.8796, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3021/4000 [28:53<10:17,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.213129997253418, Predicted Probability: 0.9946, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7477128505706787, Predicted Probability: 0.0230, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3022/4000 [28:54<10:46,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.53902530670166, Predicted Probability: 0.0014, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3999230861663818, Predicted Probability: 0.1978, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3023/4000 [28:55<11:15,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3780384063720703, Predicted Probability: 0.9670, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.16644287109375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3024/4000 [28:55<09:44,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.815032005310059, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.74781322479248, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3025/4000 [28:56<08:41,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.415830612182617, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.726536750793457, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3026/4000 [28:56<09:36,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.658291816711426, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.3354668617248535, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3027/4000 [28:57<10:29,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.22122859954834, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.5869293212890625, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3028/4000 [28:58<11:04,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.436829566955566, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.740975856781006, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3029/4000 [28:58<09:31,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.997377395629883, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.684861183166504, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3030/4000 [28:59<10:29,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.070884943008423, Predicted Probability: 0.9557, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.853524208068848, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3031/4000 [29:00<09:56,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.82125186920166, Predicted Probability: 0.9786, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.740588188171387, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3032/4000 [29:00<08:46,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.81038236618042, Predicted Probability: 0.9432, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.663311004638672, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3033/4000 [29:01<09:49,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.870643615722656, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.558563232421875, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3034/4000 [29:02<10:46,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.19239020347595215, Predicted Probability: 0.5479, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.138126373291016, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3035/4000 [29:02<11:02,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.994197845458984, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9170546531677246, Predicted Probability: 0.1282, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3036/4000 [29:03<11:31,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1499643325805664, Predicted Probability: 0.9589, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -4.650521278381348, Predicted Probability: 0.0095, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3037/4000 [29:03<09:55,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.19357681274414, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.391481399536133, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3038/4000 [29:04<10:58,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.044209480285645, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.065939903259277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3039/4000 [29:05<08:40,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: 3.2591471672058105, Predicted Probability: 0.9630, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.847023010253906, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3040/4000 [29:05<09:57,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.82763147354126, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.411081314086914, Predicted Probability: 0.9956, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3041/4000 [29:06<08:17,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.7904052734375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.804052352905273, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3042/4000 [29:06<09:24,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.077007293701172, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.885071039199829, Predicted Probability: 0.0529, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3043/4000 [29:07<10:08,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.365633964538574, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.638253688812256, Predicted Probability: 0.9333, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3044/4000 [29:07<09:00,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.050122261047363, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.167013168334961, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3045/4000 [29:08<08:10,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.740833282470703, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.031867027282715, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  76%|███████▌  | 3046/4000 [29:08<07:49,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.777268886566162, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.219541311264038, Predicted Probability: 0.0384, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3047/4000 [29:09<07:15,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.941244125366211, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.053362846374512, Predicted Probability: 0.0063, Prediction: 0.0

Epoch 3/3:  76%|███████▌  | 3048/4000 [29:09<06:04,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: -2.651019334793091, Predicted Probability: 0.0659, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.427413940429688, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3050/4000 [29:10<06:19,  2.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.405088424682617, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8976333141326904, Predicted Probability: 0.1304, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.268052101135254, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.301562309265137, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  76%|███████▋  | 3051/4000 [29:10<07:02,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.896783828735352, Predicted Probability: 0.9926, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.27536243200302124, Predicted Probability: 0.4316, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3052/4000 [29:11<07:26,  2.12it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.344561576843262, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.373631238937378, Predicted Probability: 0.0331, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3053/4000 [29:12<08:49,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.339103698730469, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.187666893005371, Predicted Probability: 0.0021, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3054/4000 [29:12<09:41,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.9113099575042725, Predicted Probability: 0.2867, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.8038740158081055, Predicted Probability: 0.1414, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3055/4000 [29:13<10:18,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4628283977508545, Predicted Probability: 0.9696, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.581398010253906, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3056/4000 [29:14<11:18,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.596523284912109, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.283390998840332, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3057/4000 [29:15<11:17,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.183713436126709, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.695509433746338, Predicted Probability: 0.9368, Prediction: 1.0

Epoch 3/3:  76%|███████▋  | 3058/4000 [29:16<11:22,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.395716667175293, Predicted Probability: 0.9676, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6997438669204712, Predicted Probability: 0.1545, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3059/4000 [29:16<11:35,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.881726264953613, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.893118858337402, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  76%|███████▋  | 3060/4000 [29:17<09:51,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.211170196533203, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.32050895690918, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3061/4000 [29:17<08:46,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.032959938049316, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.521315574645996, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3062/4000 [29:18<09:25,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6268527507781982, Predicted Probability: 0.9741, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.1889824867248535, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3063/4000 [29:18<07:49,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.716464042663574, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.469517707824707, Predicted Probability: 0.0113, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3064/4000 [29:18<07:11,  2.17it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.6218862533569336, Predicted Probability: 0.0260, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.50351619720459, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3065/4000 [29:19<07:33,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.01901388168335, Predicted Probability: 0.9934, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.235681533813477, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3066/4000 [29:20<08:43,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.137010097503662, Predicted Probability: 0.1056, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.39350700378418, Predicted Probability: 0.0017, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3067/4000 [29:20<09:28,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2334697246551514, Predicted Probability: 0.9621, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.382473945617676, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3068/4000 [29:21<08:21,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.545676231384277, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.243606567382812, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3069/4000 [29:21<07:34,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.95220947265625, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.714793682098389, Predicted Probability: 0.9967, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3070/4000 [29:22<08:48,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.157464981079102, Predicted Probability: 0.9943, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.653756141662598, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3071/4000 [29:23<09:54,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.961941242218018, Predicted Probability: 0.0026, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.044610023498535, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3072/4000 [29:23<08:38,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.782596588134766, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.523724555969238, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3073/4000 [29:24<09:34,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.130051612854004, Predicted Probability: 0.9581, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.042328834533691, Predicted Probability: 0.0064, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3074/4000 [29:25<10:02,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.1135518550872803, Predicted Probability: 0.8922, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.7279205322265625, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3075/4000 [29:25<10:25,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.648895502090454, Predicted Probability: 0.0254, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.571067810058594, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3076/4000 [29:26<10:39,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0354599952697754, Predicted Probability: 0.9542, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1556525230407715, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3077/4000 [29:27<10:46,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.057790517807007, Predicted Probability: 0.9551, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.138235092163086, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3078/4000 [29:27<09:35,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.934113025665283, Predicted Probability: 0.0192, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.757818698883057, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3079/4000 [29:28<09:14,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.202663421630859, Predicted Probability: 0.0147, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.098998546600342, Predicted Probability: 0.0061, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3080/4000 [29:28<09:54,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.61812686920166, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.5352129936218262, Predicted Probability: 0.1772, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3081/4000 [29:29<08:35,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.290393352508545, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.585036277770996, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3082/4000 [29:29<07:40,  1.99it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.338943004608154, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.270526885986328, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3083/4000 [29:30<07:49,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.7870985269546509, Predicted Probability: 0.1434, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.886184692382812, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3084/4000 [29:30<08:56,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.13376522064209, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.055531024932861, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3085/4000 [29:31<07:58,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.352276802062988, Predicted Probability: 0.9873, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.181710720062256, Predicted Probability: 0.9944, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3086/4000 [29:32<11:26,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.310207366943359, Predicted Probability: 0.0049, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.162460803985596, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3087/4000 [29:33<11:33,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.878744125366211, Predicted Probability: 0.0075, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.00811767578125, Predicted Probability: 0.0178, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3088/4000 [29:34<11:33,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.662246227264404, Predicted Probability: 0.9906, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.613607406616211, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3089/4000 [29:35<15:34,  1.03s/it]

Data point 1: Actual Class: 0.0, Final Logit: -8.029088973999023, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.3346701860427856, Predicted Probability: 0.2084, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3090/4000 [29:36<14:26,  1.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.908766746520996, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.703414916992188, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3091/4000 [29:37<13:31,  1.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8214962482452393, Predicted Probability: 0.9438, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.980502605438232, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3092/4000 [29:38<12:48,  1.18it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5551629066467285, Predicted Probability: 0.9961, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.867596626281738, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3093/4000 [29:38<09:54,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.858548641204834, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.712860107421875, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3094/4000 [29:38<08:36,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.26924467086792, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.908539295196533, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3095/4000 [29:39<09:24,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.811065673828125, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7495133876800537, Predicted Probability: 0.9399, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3096/4000 [29:39<08:14,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.868090629577637, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.90632438659668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3097/4000 [29:40<07:00,  2.15it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.596013069152832, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.696645736694336, Predicted Probability: 0.0033, Prediction: 0.0

Epoch 3/3:  77%|███████▋  | 3098/4000 [29:40<08:09,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.4433465003967285, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.613063335418701, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:  77%|███████▋  | 3099/4000 [29:41<09:22,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.688595294952393, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.375095367431641, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3100/4000 [29:42<09:53,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.387244701385498, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.760817527770996, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3102/4000 [29:42<06:56,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.1563917398452759, Predicted Probability: 0.2393, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.859796524047852, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.416816711425781, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.447782516479492, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3103/4000 [29:43<06:29,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.33298110961914, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.522496223449707, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3104/4000 [29:44<07:49,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.98048734664917, Predicted Probability: 0.9517, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.68153190612793, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3105/4000 [29:44<08:42,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.71652364730835, Predicted Probability: 0.0089, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.402533531188965, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3106/4000 [29:45<07:44,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.084117412567139, Predicted Probability: 0.9834, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.512277126312256, Predicted Probability: 0.0040, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3107/4000 [29:45<07:04,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.295266151428223, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.460635185241699, Predicted Probability: 0.9984, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3108/4000 [29:45<06:41,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.472604751586914, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.280684471130371, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3109/4000 [29:46<06:21,  2.33it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.189017295837402, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.2628755569458, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3110/4000 [29:47<08:13,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.219202995300293, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.820765495300293, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3111/4000 [29:47<09:19,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.004492282867432, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.828009605407715, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3112/4000 [29:48<08:10,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.2537994384765625, Predicted Probability: 0.0019, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.167284965515137, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3113/4000 [29:48<07:24,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.330574035644531, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.270139217376709, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3114/4000 [29:49<06:48,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.709782600402832, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.500876426696777, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3115/4000 [29:49<07:50,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.379714012145996, Predicted Probability: 0.0847, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.374695777893066, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3116/4000 [29:50<09:14,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.8529863357543945, Predicted Probability: 0.0208, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.392031192779541, Predicted Probability: 0.9675, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3117/4000 [29:51<09:09,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.926295280456543, Predicted Probability: 0.9491, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3167569637298584, Predicted Probability: 0.9650, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3118/4000 [29:51<09:36,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.647830963134766, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8730762004852295, Predicted Probability: 0.9465, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3119/4000 [29:52<10:09,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.465584754943848, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.4398193359375, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3120/4000 [29:53<08:51,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.315516471862793, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.02021598815918, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3121/4000 [29:53<07:06,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.617133140563965, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.281722068786621, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3122/4000 [29:53<06:50,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.881258010864258, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.5784382820129395, Predicted Probability: 0.9898, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3123/4000 [29:54<08:04,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.466524124145508, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.592080593109131, Predicted Probability: 0.9304, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3124/4000 [29:54<07:18,  2.00it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.734879016876221, Predicted Probability: 0.0087, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.469734191894531, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3125/4000 [29:55<08:23,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.804055690765381, Predicted Probability: 0.0081, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.272948265075684, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3126/4000 [29:55<06:48,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.372265815734863, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.766374588012695, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3127/4000 [29:56<05:54,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.225543022155762, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.305438995361328, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3128/4000 [29:56<05:44,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.1017165184021, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.529431343078613, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3129/4000 [29:56<05:09,  2.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.339398384094238, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.463738441467285, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3130/4000 [29:57<06:51,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.621557235717773, Predicted Probability: 0.9964, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.779377460479736, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3131/4000 [29:58<08:02,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1467127799987793, Predicted Probability: 0.9588, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.879329681396484, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3132/4000 [29:58<07:57,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.438770294189453, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.874730110168457, Predicted Probability: 0.1330, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3133/4000 [29:59<09:02,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.953518867492676, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.397354125976562, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3134/4000 [30:00<08:13,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.464712142944336, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.306964874267578, Predicted Probability: 0.0905, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3135/4000 [30:00<08:59,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.563535690307617, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.655328750610352, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3136/4000 [30:01<09:34,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9185200929641724, Predicted Probability: 0.1280, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.703851699829102, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3137/4000 [30:01<08:18,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.866560935974121, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.047445297241211, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3138/4000 [30:02<07:22,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9853196144104, Predicted Probability: 0.0025, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.95732593536377, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  78%|███████▊  | 3139/4000 [30:02<07:46,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.96201229095459, Predicted Probability: 0.9813, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.776358127593994, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  78%|███████▊  | 3140/4000 [30:03<09:04,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.70179557800293, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.433645248413086, Predicted Probability: 0.0117, Prediction: 0.0

Epoch 3/3:  79%|███████▊  | 3141/4000 [30:04<09:32,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.391953945159912, Predicted Probability: 0.9878, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.943340301513672, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  79%|███████▊  | 3142/4000 [30:05<10:29,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.780516624450684, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.391524791717529, Predicted Probability: 0.0045, Prediction: 0.0

Epoch 3/3:  79%|███████▊  | 3143/4000 [30:05<09:43,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.884696006774902, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.334922790527344, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  79%|███████▊  | 3144/4000 [30:06<10:01,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.9185864925384521, Predicted Probability: 0.8720, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.374625205993652, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  79%|███████▊  | 3145/4000 [30:07<09:19,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.591270923614502, Predicted Probability: 0.9732, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.070279121398926, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  79%|███████▊  | 3146/4000 [30:07<08:29,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.744552135467529, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.404570579528809, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  79%|███████▊  | 3147/4000 [30:08<09:13,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8842554092407227, Predicted Probability: 0.9471, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.002352714538574, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  79%|███████▊  | 3148/4000 [30:09<09:50,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.2911285161972046, Predicted Probability: 0.7843, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.449016571044922, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3150/4000 [30:09<07:14,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.796473503112793, Predicted Probability: 0.9780, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.494038581848145, Predicted Probability: 0.0002, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 8.818511009216309, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.920821189880371, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3152/4000 [30:10<05:32,  2.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.037055969238281, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.547440528869629, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.916316032409668, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.229503631591797, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3153/4000 [30:11<06:13,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.949575424194336, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.122200965881348, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3154/4000 [30:11<07:24,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.909995079040527, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.284754753112793, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3155/4000 [30:12<06:47,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5899763107299805, Predicted Probability: 0.1694, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.39561653137207, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3156/4000 [30:12<07:23,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.805426597595215, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.780002117156982, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3157/4000 [30:13<08:25,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.326279163360596, Predicted Probability: 0.9952, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.086915969848633, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3158/4000 [30:14<08:07,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.289412021636963, Predicted Probability: 0.9641, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7549682855606079, Predicted Probability: 0.3197, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3159/4000 [30:14<08:50,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.802009582519531, Predicted Probability: 0.0030, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.719198226928711, Predicted Probability: 0.9381, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3160/4000 [30:15<09:31,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.28951644897461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.272473335266113, Predicted Probability: 0.9862, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3161/4000 [30:16<09:47,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.094695568084717, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.051254749298096, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3162/4000 [30:16<08:26,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.593466758728027, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.959445476531982, Predicted Probability: 0.9930, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3163/4000 [30:17<07:24,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.74763011932373, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.620207786560059, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3164/4000 [30:18<08:33,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.475096702575684, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.2646169662475586, Predicted Probability: 0.9059, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3165/4000 [30:18<08:15,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.955645561218262, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.096826553344727, Predicted Probability: 0.9836, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3166/4000 [30:18<06:39,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.710074424743652, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.046759605407715, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3167/4000 [30:19<07:50,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.869190216064453, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.867347717285156, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3168/4000 [30:20<08:32,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.832364797592163, Predicted Probability: 0.9444, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.605838775634766, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3169/4000 [30:20<07:33,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7676379680633545, Predicted Probability: 0.0226, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.038553714752197, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3170/4000 [30:21<06:49,  2.03it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.4590163230896, Predicted Probability: 0.9886, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.501672744750977, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3171/4000 [30:21<06:19,  2.19it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.965400695800781, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.057561874389648, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3172/4000 [30:21<06:19,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.098718643188477, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.9023284912109375, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3173/4000 [30:22<05:16,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: -0.2697051167488098, Predicted Probability: 0.4330, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.534401893615723, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3174/4000 [30:22<05:16,  2.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.19880199432373, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.833351135253906, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3175/4000 [30:22<04:33,  3.02it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.344199180603027, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.43129825592041, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3176/4000 [30:23<04:40,  2.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.218860626220703, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.889554023742676, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  79%|███████▉  | 3177/4000 [30:23<05:35,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.27506685256958, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.301107406616211, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3178/4000 [30:24<06:55,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4508461952209473, Predicted Probability: 0.1899, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.24964714050293, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  79%|███████▉  | 3179/4000 [30:25<07:53,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.438995361328125, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.348376989364624, Predicted Probability: 0.2061, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3180/4000 [30:25<08:45,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.0459718704223633, Predicted Probability: 0.0454, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.26793098449707, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3181/4000 [30:26<09:14,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.833717346191406, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.397990703582764, Predicted Probability: 0.9878, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3182/4000 [30:27<09:59,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.786799430847168, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.686619758605957, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3184/4000 [30:28<07:49,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.522422790527344, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.477117538452148, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -10.218803405761719, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.173554420471191, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3185/4000 [30:29<08:31,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4097275733947754, Predicted Probability: 0.1963, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.086153030395508, Predicted Probability: 0.1104, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3186/4000 [30:29<06:47,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.317842483520508, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7170939445495605, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3187/4000 [30:29<05:36,  2.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.441237449645996, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.0179443359375, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3188/4000 [30:30<06:24,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.984128475189209, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.459811210632324, Predicted Probability: 0.9958, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3189/4000 [30:30<07:33,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.736194610595703, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: 0.8370941877365112, Predicted Probability: 0.6979, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3190/4000 [30:31<08:16,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.00291633605957, Predicted Probability: 0.0179, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.3883209228515625, Predicted Probability: 0.0841, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3192/4000 [30:32<05:26,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.494702339172363, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 0.048522867262363434, Predicted Probability: 0.5121, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.648282051086426, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.258169174194336, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3193/4000 [30:32<06:49,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.049107074737549, Predicted Probability: 0.9547, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.683959007263184, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3194/4000 [30:33<07:48,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.48151683807373, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.2651760578155518, Predicted Probability: 0.0940, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3195/4000 [30:34<08:28,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.897186279296875, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.265298843383789, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3196/4000 [30:35<09:00,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.5418927669525146, Predicted Probability: 0.1763, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.64323616027832, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  80%|███████▉  | 3197/4000 [30:35<07:45,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.570054054260254, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.885356903076172, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  80%|███████▉  | 3198/4000 [30:36<08:27,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.268804550170898, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.622800827026367, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3200/4000 [30:37<06:57,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.472028732299805, Predicted Probability: 0.0042, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.233520984649658, Predicted Probability: 0.0053, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.17138957977295, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.678825378417969, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3201/4000 [30:37<07:55,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.378523826599121, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.806167602539062, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3202/4000 [30:38<07:02,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.5511579513549805, Predicted Probability: 0.9896, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.45852279663086, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3203/4000 [30:38<06:23,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.21448278427124, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.38737964630127, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3204/4000 [30:39<05:56,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.72789192199707, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.846717834472656, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3205/4000 [30:39<05:38,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.539416313171387, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.659182071685791, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3206/4000 [30:39<05:43,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.854256629943848, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.828746318817139, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3207/4000 [30:40<06:56,  1.90it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.138507843017578, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.503467082977295, Predicted Probability: 0.9959, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3208/4000 [30:41<07:43,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.147073268890381, Predicted Probability: 0.9588, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.625772476196289, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3209/4000 [30:41<06:58,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.738625526428223, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.148903846740723, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3210/4000 [30:42<08:15,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.168516635894775, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.58082389831543, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3211/4000 [30:43<07:31,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.961737632751465, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.999934673309326, Predicted Probability: 0.9933, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3212/4000 [30:43<06:49,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.677267074584961, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.903121471405029, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3213/4000 [30:44<08:02,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.6920429468154907, Predicted Probability: 0.8445, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.360642910003662, Predicted Probability: 0.0047, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3214/4000 [30:45<09:01,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.723278045654297, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.081554412841797, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3215/4000 [30:45<09:26,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.267070770263672, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.075701713562012, Predicted Probability: 0.9938, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3216/4000 [30:46<09:25,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.157248616218567, Predicted Probability: 0.2392, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.338425636291504, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3217/4000 [30:47<08:19,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4733619689941406, Predicted Probability: 0.9223, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.616358757019043, Predicted Probability: 0.0098, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3218/4000 [30:47<08:41,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.749238967895508, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1969354152679443, Predicted Probability: 0.9607, Prediction: 1.0

Epoch 3/3:  80%|████████  | 3219/4000 [30:48<07:32,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.551499366760254, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -2.9501893520355225, Predicted Probability: 0.0497, Prediction: 0.0

Epoch 3/3:  80%|████████  | 3220/4000 [30:48<07:23,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.944090843200684, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.396305084228516, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3221/4000 [30:49<06:53,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.454534530639648, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.596282482147217, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3222/4000 [30:49<07:37,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.9926886558532715, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.992806434631348, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3223/4000 [30:50<06:22,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.441553115844727, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.939006328582764, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3224/4000 [30:50<07:11,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.690249443054199, Predicted Probability: 0.9756, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.4732844829559326, Predicted Probability: 0.8136, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3225/4000 [30:51<07:14,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.883767127990723, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.805083274841309, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3226/4000 [30:51<07:09,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.971782684326172, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.10342912375926971, Predicted Probability: 0.4742, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3227/4000 [30:52<07:54,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.751115798950195, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.718381881713867, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3228/4000 [30:53<07:38,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.809237480163574, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.732599258422852, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3229/4000 [30:53<07:40,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.797207832336426, Predicted Probability: 0.9781, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.207883358001709, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3230/4000 [30:54<07:49,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.89180850982666, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.753527641296387, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3231/4000 [30:55<08:32,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.140351295471191, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.961986541748047, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3232/4000 [30:55<07:24,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.56840705871582, Predicted Probability: 0.0038, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.47004222869873, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3233/4000 [30:56<07:14,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.084485054016113, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.702536582946777, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3234/4000 [30:56<06:27,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.007183978799730539, Predicted Probability: 0.4982, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9724958539009094, Predicted Probability: 0.2744, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3235/4000 [30:57<07:15,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.80050277709961, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.109867811203003, Predicted Probability: 0.9573, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3236/4000 [30:57<05:51,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: 5.367727756500244, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.051067352294922, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3237/4000 [30:58<06:12,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.12176513671875, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.788376808166504, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3238/4000 [30:58<07:03,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.9947748184204102, Predicted Probability: 0.1198, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.237241268157959, Predicted Probability: 0.9622, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3239/4000 [30:59<06:58,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.788563251495361, Predicted Probability: 0.0031, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.774456024169922, Predicted Probability: 0.9776, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3240/4000 [31:00<07:44,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.11128568649292, Predicted Probability: 0.9574, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.754317283630371, Predicted Probability: 0.0085, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3241/4000 [31:00<08:39,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.635030746459961, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.597646713256836, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3242/4000 [31:01<08:45,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.060084581375122, Predicted Probability: 0.1130, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.674970626831055, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3243/4000 [31:02<08:26,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8302041292190552, Predicted Probability: 0.8618, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.012954711914062, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3244/4000 [31:03<08:50,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.541964530944824, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.7240183353424072, Predicted Probability: 0.9384, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3245/4000 [31:03<09:06,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.138950824737549, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.2628173828125, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3246/4000 [31:04<09:14,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.451484680175781, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.955178260803223, Predicted Probability: 0.0070, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3247/4000 [31:05<09:05,  1.38it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.640552043914795, Predicted Probability: 0.9334, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.46416088938713074, Predicted Probability: 0.3860, Prediction: 0.0

Epoch 3/3:  81%|████████  | 3248/4000 [31:06<09:11,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.552513122558594, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.146159648895264, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  81%|████████  | 3249/4000 [31:06<08:04,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.15952205657959, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.239641189575195, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 3/3:  81%|████████▏ | 3250/4000 [31:06<07:01,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.5649862289428711, Predicted Probability: 0.6376, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.894011497497559, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  81%|████████▏ | 3251/4000 [31:07<07:42,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.876567363739014, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4279303550720215, Predicted Probability: 0.0811, Prediction: 0.0

Epoch 3/3:  81%|████████▏ | 3252/4000 [31:08<07:26,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2097086906433105, Predicted Probability: 0.9980, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.559379577636719, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████▏ | 3253/4000 [31:08<08:16,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.108274459838867, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.622451782226562, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████▏ | 3254/4000 [31:09<08:44,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.005897521972656, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.5090640187263489, Predicted Probability: 0.6246, Prediction: 1.0

Epoch 3/3:  81%|████████▏ | 3255/4000 [31:10<07:33,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.317036628723145, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.254174709320068, Predicted Probability: 0.0052, Prediction: 0.0

Epoch 3/3:  81%|████████▏ | 3256/4000 [31:10<07:34,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: -1.721773386001587, Predicted Probability: 0.1516, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.200185775756836, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████▏ | 3257/4000 [31:11<06:57,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.6758036613464355, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.795060157775879, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  81%|████████▏ | 3259/4000 [31:12<06:08,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.410623073577881, Predicted Probability: 0.9176, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.224159240722656, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -5.090081214904785, Predicted Probability: 0.0061, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.875070571899414, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3260/4000 [31:12<05:43,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.883596897125244, Predicted Probability: 0.9798, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.542649269104004, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3261/4000 [31:12<05:21,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.570267677307129, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.138726234436035, Predicted Probability: 0.8946, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3262/4000 [31:13<05:04,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.746280670166016, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1040730476379395, Predicted Probability: 0.9838, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3263/4000 [31:14<06:17,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8830466270446777, Predicted Probability: 0.9470, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.523015022277832, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3265/4000 [31:15<05:49,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.784211158752441, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7270395755767822, Predicted Probability: 0.9765, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 5.681318283081055, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.8761749267578125, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3266/4000 [31:15<06:41,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.899141311645508, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.1984594166278839, Predicted Probability: 0.4505, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3267/4000 [31:16<06:16,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.32281357049942017, Predicted Probability: 0.5800, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.949934959411621, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3268/4000 [31:16<05:47,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.250790119171143, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.817468166351318, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3269/4000 [31:16<05:24,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.044262886047363, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3486833572387695, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3271/4000 [31:17<04:18,  2.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.883847713470459, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.142919063568115, Predicted Probability: 0.9992, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 6.540156364440918, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.733199596405029, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3272/4000 [31:18<05:54,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.477949142456055, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.233711242675781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3273/4000 [31:19<06:50,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.36575984954834, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.153510093688965, Predicted Probability: 0.9943, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3274/4000 [31:19<07:25,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2749507427215576, Predicted Probability: 0.9068, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.373340606689453, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3275/4000 [31:19<05:57,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.787712097167969, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.011543273925781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3276/4000 [31:20<05:44,  2.10it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.711310863494873, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.21669864654541, Predicted Probability: 0.9017, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3277/4000 [31:21<06:47,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.1036770343780518, Predicted Probability: 0.1087, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.067012310028076, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3278/4000 [31:21<05:28,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.894899368286133, Predicted Probability: 0.9801, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.577120780944824, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3279/4000 [31:21<04:34,  2.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.654566764831543, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.18835362792015076, Predicted Probability: 0.4531, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3281/4000 [31:22<04:49,  2.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.433202743530273, Predicted Probability: 0.9883, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.321398735046387, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 11.208006858825684, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.073665618896484, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3282/4000 [31:22<04:04,  2.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.0794477462768555, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.818572998046875, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3283/4000 [31:23<05:31,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.116821765899658, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.061750411987305, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3284/4000 [31:24<06:35,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.364709854125977, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.041597366333008, Predicted Probability: 0.1149, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3285/4000 [31:24<06:31,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5022308826446533, Predicted Probability: 0.0292, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.626487731933594, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3286/4000 [31:24<05:18,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.900664329528809, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.703991889953613, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3288/4000 [31:25<05:12,  2.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.901983261108398, Predicted Probability: 0.0010, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.644718647003174, Predicted Probability: 0.9745, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.745484352111816, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.026081085205078, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3289/4000 [31:26<06:24,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.4417664706707001, Predicted Probability: 0.6087, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.629444122314453, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3290/4000 [31:27<06:29,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.063153266906738, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.925314426422119, Predicted Probability: 0.9928, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3291/4000 [31:27<06:29,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.635454177856445, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.174931526184082, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3293/4000 [31:28<05:15,  2.24it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.442700386047363, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.465601444244385, Predicted Probability: 0.9994, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.1089448928833, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.886919975280762, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3294/4000 [31:29<05:54,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.57421875, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.031408309936523, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3295/4000 [31:30<06:58,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.848430156707764, Predicted Probability: 0.0029, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.8952713012695312, Predicted Probability: 0.0199, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3296/4000 [31:30<06:11,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.398704528808594, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.1868205070495605, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3297/4000 [31:31<07:07,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.657095909118652, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.543418884277344, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  82%|████████▏ | 3298/4000 [31:31<06:21,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.857321739196777, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.097583770751953, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  82%|████████▏ | 3299/4000 [31:31<05:10,  2.26it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.893256187438965, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.703824996948242, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  82%|████████▎ | 3300/4000 [31:32<06:09,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.673053741455078, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.464463710784912, Predicted Probability: 0.9697, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3301/4000 [31:33<06:49,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1226773262023926, Predicted Probability: 0.9578, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.96967077255249, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3302/4000 [31:33<06:20,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.43726634979248, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.524324417114258, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3303/4000 [31:34<07:16,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.167624473571777, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.706080913543701, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3304/4000 [31:35<07:53,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.463388442993164, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.937400817871094, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3305/4000 [31:35<06:50,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.065605640411377, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.994208812713623, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3307/4000 [31:36<05:58,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.81386947631836, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.548773765563965, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.298745155334473, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.189752101898193, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3308/4000 [31:37<06:01,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.8858962059021, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.22100305557251, Predicted Probability: 0.9855, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3309/4000 [31:37<05:32,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.747330665588379, Predicted Probability: 0.0086, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.422816276550293, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3310/4000 [31:38<06:25,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.191648244857788, Predicted Probability: 0.2330, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2200911045074463, Predicted Probability: 0.9616, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3311/4000 [31:38<05:44,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.600483894348145, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.9742655754089355, Predicted Probability: 0.0184, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3312/4000 [31:39<06:40,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.918356895446777, Predicted Probability: 0.0073, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6496210098266602, Predicted Probability: 0.3431, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3313/4000 [31:40<07:26,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.37243938446045, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.775840759277344, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3314/4000 [31:40<06:29,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.864413738250732, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.401028633117676, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3315/4000 [31:41<07:14,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.16103199124336243, Predicted Probability: 0.5402, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.299591064453125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3316/4000 [31:42<07:33,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.943180561065674, Predicted Probability: 0.9810, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.597815036773682, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3317/4000 [31:42<07:54,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.976539611816406, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7880961894989014, Predicted Probability: 0.0221, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3318/4000 [31:43<07:58,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.640967607498169, Predicted Probability: 0.9744, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.081911087036133, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3319/4000 [31:44<08:04,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.840134143829346, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.340544700622559, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3320/4000 [31:44<06:55,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.2263729572296143, Predicted Probability: 0.2268, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.987850666046143, Predicted Probability: 0.9932, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3321/4000 [31:45<06:19,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.663830757141113, Predicted Probability: 0.0093, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.954424858093262, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3322/4000 [31:46<07:22,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.973702430725098, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.665077209472656, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3323/4000 [31:46<05:51,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.145047187805176, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.759055137634277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3324/4000 [31:47<06:50,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.540811538696289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.023918628692627, Predicted Probability: 0.9976, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3325/4000 [31:47<06:34,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.099221229553223, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.15278434753418, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3326/4000 [31:48<05:51,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.847479820251465, Predicted Probability: 0.0078, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.957106590270996, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3327/4000 [31:48<05:51,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7260336875915527, Predicted Probability: 0.9765, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.541643142700195, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3328/4000 [31:49<06:49,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.029468536376953, Predicted Probability: 0.9539, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.181868553161621, Predicted Probability: 0.0150, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3329/4000 [31:49<06:05,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.437648773193359, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.254959106445312, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3330/4000 [31:50<05:47,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.031805992126465, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.269279718399048, Predicted Probability: 0.9634, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3331/4000 [31:50<05:16,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.47214412689209, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.511001586914062, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3332/4000 [31:50<04:53,  2.27it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.633853912353516, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6451884508132935, Predicted Probability: 0.1618, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3333/4000 [31:51<06:04,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.495384216308594, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.065308570861816, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3334/4000 [31:52<05:31,  2.01it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.989877700805664, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.62033748626709, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  83%|████████▎ | 3335/4000 [31:52<06:27,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.066197872161865, Predicted Probability: 0.0023, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.707611560821533, Predicted Probability: 0.0625, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3336/4000 [31:53<06:52,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.385349750518799, Predicted Probability: 0.9672, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -0.9780577421188354, Predicted Probability: 0.2733, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3337/4000 [31:54<06:37,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.213668823242188, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.971701145172119, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3338/4000 [31:55<07:22,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.970596313476562, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.8933563232421875, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  83%|████████▎ | 3339/4000 [31:55<07:45,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.624670028686523, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3988773822784424, Predicted Probability: 0.9677, Prediction: 1.0

Epoch 3/3:  84%|████████▎ | 3340/4000 [31:56<06:41,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.016807556152344, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.68980598449707, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  84%|████████▎ | 3341/4000 [31:56<05:22,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.403584957122803, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.207626342773438, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  84%|████████▎ | 3342/4000 [31:57<06:23,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.33887243270874, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3364412784576416, Predicted Probability: 0.9657, Prediction: 1.0

Epoch 3/3:  84%|████████▎ | 3343/4000 [31:57<05:40,  1.93it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.211496829986572, Predicted Probability: 0.9946, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.957799911499023, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  84%|████████▎ | 3344/4000 [31:57<04:37,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.736393928527832, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.872933387756348, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  84%|████████▎ | 3345/4000 [31:58<05:51,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.846101760864258, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.974481582641602, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▎ | 3346/4000 [31:59<06:35,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.533705711364746, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.526668071746826, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  84%|████████▎ | 3347/4000 [32:00<07:08,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0348849296569824, Predicted Probability: 0.9541, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.465923309326172, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▎ | 3348/4000 [32:00<07:25,  1.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9828438758850098, Predicted Probability: 0.9518, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.841100692749023, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  84%|████████▎ | 3349/4000 [32:01<07:33,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.989586591720581, Predicted Probability: 0.9521, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.170740127563477, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3350/4000 [32:02<07:55,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.582269668579102, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.57181978225708, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3351/4000 [32:02<06:45,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.323688507080078, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.777375221252441, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3352/4000 [32:03<05:59,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.7772765159606934, Predicted Probability: 0.9414, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.037245750427246, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3353/4000 [32:03<06:37,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.848028182983398, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: -0.3849702775478363, Predicted Probability: 0.4049, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3354/4000 [32:04<05:47,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.052013397216797, Predicted Probability: 0.9829, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.479528427124023, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3355/4000 [32:05<06:26,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.518533706665039, Predicted Probability: 0.8203, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.264334678649902, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3356/4000 [32:05<05:41,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.08993376791477203, Predicted Probability: 0.5225, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.380216598510742, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3357/4000 [32:06<06:21,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.559863805770874, Predicted Probability: 0.0277, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.07932186126709, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3358/4000 [32:06<06:11,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.5570650100708, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9341483116149902, Predicted Probability: 0.0505, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3360/4000 [32:07<04:06,  2.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.370486259460449, Predicted Probability: 0.9875, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.976786613464355, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 4.358120441436768, Predicted Probability: 0.9874, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.256382465362549, Predicted Probability: 0.9052, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3361/4000 [32:07<04:03,  2.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.417376518249512, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.469941139221191, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3362/4000 [32:08<05:20,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.267282962799072, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.973628997802734, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3363/4000 [32:08<04:34,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.858759880065918, Predicted Probability: 0.0028, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.079999923706055, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3364/4000 [32:09<05:09,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.082607746124268, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.797006607055664, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3365/4000 [32:09<05:00,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.03649616241455, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.498316764831543, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3366/4000 [32:09<04:39,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.203763961791992, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.089154243469238, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3367/4000 [32:10<04:28,  2.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.713334560394287, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.942386150360107, Predicted Probability: 0.9929, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3368/4000 [32:10<04:30,  2.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.13236898183822632, Predicted Probability: 0.4670, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.419563293457031, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3369/4000 [32:11<05:53,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.1844565868377686, Predicted Probability: 0.9602, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.560563087463379, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3370/4000 [32:11<05:19,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.24998664855957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.171946048736572, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3371/4000 [32:12<06:31,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.668497085571289, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.427451133728027, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3372/4000 [32:13<07:03,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.27797269821167, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.561687469482422, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3373/4000 [32:14<07:11,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.471080780029297, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.0775156021118164, Predicted Probability: 0.2540, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3374/4000 [32:15<07:33,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.71731948852539, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.516552448272705, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3375/4000 [32:15<06:30,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.821735382080078, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1003947257995605, Predicted Probability: 0.9939, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3376/4000 [32:16<06:26,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.956915378570557, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.203903675079346, Predicted Probability: 0.9853, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3377/4000 [32:16<05:42,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.908304691314697, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.505718231201172, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  84%|████████▍ | 3378/4000 [32:17<06:28,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.920248031616211, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.910627365112305, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3379/4000 [32:18<07:09,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.152017593383789, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.816346168518066, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  84%|████████▍ | 3380/4000 [32:18<06:42,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4852850437164307, Predicted Probability: 0.0297, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.258123397827148, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3382/4000 [32:19<05:04,  2.03it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.424727439880371, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.6865074634552, Predicted Probability: 0.0244, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -9.586849212646484, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.120141983032227, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3383/4000 [32:20<05:13,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.61384391784668, Predicted Probability: 0.9902, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.191801071166992, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3384/4000 [32:20<05:02,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.739187240600586, Predicted Probability: 0.9913, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.318376541137695, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3385/4000 [32:20<04:42,  2.17it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.024463653564453, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.991528034210205, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3386/4000 [32:21<05:31,  1.85it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.140987396240234, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3542728424072266, Predicted Probability: 0.0338, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3387/4000 [32:22<04:58,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.072908401489258, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.860562324523926, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3388/4000 [32:22<06:06,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.218067169189453, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.480886459350586, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3389/4000 [32:23<04:53,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.435906410217285, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.150450706481934, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3390/4000 [32:23<05:06,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.115675449371338, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.24216890335083, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3391/4000 [32:24<05:56,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.045194625854492, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4566023349761963, Predicted Probability: 0.9694, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3392/4000 [32:25<06:44,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.612981796264648, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.956768035888672, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3393/4000 [32:25<06:23,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.252476215362549, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.2952789068222046, Predicted Probability: 0.5733, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3394/4000 [32:26<06:21,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.42647123336792, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.95569372177124, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3395/4000 [32:27<06:53,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.229898452758789, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.210572719573975, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3396/4000 [32:27<07:04,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.106367111206055, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.887133836746216, Predicted Probability: 0.9472, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3397/4000 [32:28<07:06,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.9140872955322266, Predicted Probability: 0.9485, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.343585014343262, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  85%|████████▍ | 3398/4000 [32:29<07:12,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.002765655517578, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.916378498077393, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  85%|████████▍ | 3399/4000 [32:30<07:19,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.098533630371094, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.591730117797852, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3400/4000 [32:30<06:17,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.313526153564453, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.990809440612793, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3401/4000 [32:31<06:42,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.417463302612305, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.852526664733887, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3402/4000 [32:32<06:59,  1.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.845242500305176, Predicted Probability: 0.9971, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.10446548461914, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3403/4000 [32:32<06:01,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.241118907928467, Predicted Probability: 0.9858, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.743487358093262, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3404/4000 [32:33<06:23,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.741960525512695, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 0.5014304518699646, Predicted Probability: 0.6228, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3405/4000 [32:34<06:47,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.1396384239196777, Predicted Probability: 0.0415, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.001728057861328, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3406/4000 [32:34<07:10,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.544036865234375, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.445522785186768, Predicted Probability: 0.9884, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3407/4000 [32:35<06:38,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.460137367248535, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1147050857543945, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3408/4000 [32:36<07:09,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.7065229415893555, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.9305161237716675, Predicted Probability: 0.7172, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3409/4000 [32:37<07:25,  1.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.720378875732422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.91486930847168, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3410/4000 [32:37<07:20,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.630979537963867, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.15549761056900024, Predicted Probability: 0.5388, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3411/4000 [32:38<06:27,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.970097541809082, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.657708168029785, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3412/4000 [32:39<06:49,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.769880294799805, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.091850519180298, Predicted Probability: 0.8901, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3413/4000 [32:39<06:19,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.5160651206970215, Predicted Probability: 0.9960, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.982585906982422, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3414/4000 [32:39<05:31,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.605342864990234, Predicted Probability: 0.9963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.136945724487305, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3415/4000 [32:40<05:40,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.926178932189941, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.469852924346924, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3416/4000 [32:41<06:07,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.694869995117188, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.313228130340576, Predicted Probability: 0.9951, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3417/4000 [32:41<05:24,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.193821907043457, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.678799629211426, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  85%|████████▌ | 3418/4000 [32:42<05:56,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.039095878601074, Predicted Probability: 0.1152, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.657995223999023, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  85%|████████▌ | 3419/4000 [32:42<05:18,  1.82it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.99349308013916, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.77174186706543, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3420/4000 [32:43<05:54,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3387725353240967, Predicted Probability: 0.9657, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.83276081085205, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3421/4000 [32:43<04:44,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.437647819519043, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.116791725158691, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3422/4000 [32:44<04:27,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.532624244689941, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.02377986907959, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3423/4000 [32:44<05:16,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6111879348754883, Predicted Probability: 0.9737, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.831724166870117, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3424/4000 [32:45<05:43,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.323898196220398, Predicted Probability: 0.7898, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.962089538574219, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3425/4000 [32:46<06:02,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.417184829711914, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3872158527374268, Predicted Probability: 0.9673, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3426/4000 [32:47<06:24,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.365129470825195, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.837639808654785, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3427/4000 [32:47<05:04,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.821955680847168, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.284173965454102, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3428/4000 [32:47<05:19,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.627859115600586, Predicted Probability: 0.9987, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.8145170211792, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3429/4000 [32:48<05:58,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.644437074661255, Predicted Probability: 0.9745, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.128474235534668, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3430/4000 [32:49<05:56,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.2834439277648926, Predicted Probability: 0.0361, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.039308071136475, Predicted Probability: 0.0024, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3431/4000 [32:50<06:21,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.889003276824951, Predicted Probability: 0.9473, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.7329740524292, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3432/4000 [32:50<06:35,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.570836067199707, Predicted Probability: 0.9726, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.331437110900879, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3433/4000 [32:51<06:49,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.367765426635742, Predicted Probability: 0.9667, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.747396469116211, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3434/4000 [32:52<07:07,  1.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.3010945320129395, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.988774299621582, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3435/4000 [32:52<05:34,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.809728622436523, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.7577880620956421, Predicted Probability: 0.3191, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3436/4000 [32:53<06:05,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.758742570877075, Predicted Probability: 0.9772, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.25772762298584, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3437/4000 [32:54<06:18,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.390691757202148, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.250868797302246, Predicted Probability: 0.9627, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3438/4000 [32:54<05:42,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.794184684753418, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.68995475769043, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3440/4000 [32:55<04:03,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.871922492980957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.191031455993652, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 9.428197860717773, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1036550998687744, Predicted Probability: 0.9570, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3441/4000 [32:55<03:24,  2.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.127440452575684, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.507383346557617, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3442/4000 [32:56<04:34,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.124875545501709, Predicted Probability: 0.0059, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.687847137451172, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  86%|████████▌ | 3443/4000 [32:57<05:17,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.977006912231445, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.152770519256592, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3444/4000 [32:57<04:17,  2.16it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.903053283691406, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.285556316375732, Predicted Probability: 0.9864, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3445/4000 [32:57<04:03,  2.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.812747955322266, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.94474983215332, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3446/4000 [32:57<03:50,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.65798282623291, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.178439140319824, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3447/4000 [32:58<04:40,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.761155605316162, Predicted Probability: 0.9915, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.491501569747925, Predicted Probability: 0.9704, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3448/4000 [32:59<04:18,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.838778495788574, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.593748092651367, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  86%|████████▌ | 3449/4000 [32:59<05:15,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.000078201293945, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.677398681640625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3450/4000 [33:00<05:08,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.4832942485809326, Predicted Probability: 0.0298, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.717392921447754, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3451/4000 [33:01<05:35,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.344705581665039, Predicted Probability: 0.0875, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.620298385620117, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3452/4000 [33:01<05:56,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.292705535888672, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.683060646057129, Predicted Probability: 0.9966, Prediction: 1.0

Epoch 3/3:  86%|████████▋ | 3453/4000 [33:02<06:15,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.804109573364258, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.90377426147461, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3454/4000 [33:03<06:25,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.037178039550781, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.729196548461914, Predicted Probability: 0.9912, Prediction: 1.0

Epoch 3/3:  86%|████████▋ | 3455/4000 [33:04<06:28,  1.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.053371906280518, Predicted Probability: 0.9829, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.892119407653809, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3456/4000 [33:04<06:42,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.137899398803711, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.820541381835938, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3457/4000 [33:05<05:41,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.07431697845459, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.512799263000488, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3458/4000 [33:06<06:09,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.959305763244629, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.041107177734375, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  86%|████████▋ | 3459/4000 [33:06<05:46,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.9347586631774902, Predicted Probability: 0.9808, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.701332092285156, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  86%|████████▋ | 3460/4000 [33:07<06:00,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.628093719482422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1914305686950684, Predicted Probability: 0.9605, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3461/4000 [33:08<06:18,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.483232498168945, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.507946729660034, Predicted Probability: 0.0291, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3462/4000 [33:08<05:24,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.012246131896973, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.426641464233398, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3463/4000 [33:08<04:43,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.370841979980469, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0776426792144775, Predicted Probability: 0.8887, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3464/4000 [33:09<03:51,  2.31it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.25074577331543, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.923445701599121, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3465/4000 [33:09<04:43,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.395830154418945, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.705862283706665, Predicted Probability: 0.8463, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3466/4000 [33:10<05:15,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.56533432006836, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.052997350692749, Predicted Probability: 0.1137, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3467/4000 [33:11<05:08,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: 1.608431339263916, Predicted Probability: 0.8332, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.540214538574219, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3468/4000 [33:11<05:34,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.27869987487793, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.767603397369385, Predicted Probability: 0.0084, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3469/4000 [33:12<04:54,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.5250958800315857, Predicted Probability: 0.6283, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.598435401916504, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3470/4000 [33:13<05:24,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: 2.157132148742676, Predicted Probability: 0.8963, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7043585777282715, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3471/4000 [33:13<05:13,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.566314697265625, Predicted Probability: 0.0713, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.372966766357422, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3472/4000 [33:13<04:12,  2.09it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.7487073540687561, Predicted Probability: 0.6789, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.243826866149902, Predicted Probability: 0.0019, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3473/4000 [33:14<05:01,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.380687713623047, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.039007663726807, Predicted Probability: 0.9936, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3474/4000 [33:15<05:28,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.126907348632812, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.15946364402771, Predicted Probability: 0.1035, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3475/4000 [33:16<05:45,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.3967885971069336, Predicted Probability: 0.9676, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.65418815612793, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3477/4000 [33:16<04:38,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.364292860031128, Predicted Probability: 0.9666, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.842306137084961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 3.6876678466796875, Predicted Probability: 0.9756, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.022345542907715, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3478/4000 [33:17<04:45,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.878092765808105, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.20770525932312, Predicted Probability: 0.9611, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3479/4000 [33:17<04:26,  1.96it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.518123626708984, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.7463483810424805, Predicted Probability: 0.9968, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3480/4000 [33:18<04:03,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: -4.285330295562744, Predicted Probability: 0.0136, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.311185836791992, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3481/4000 [33:18<03:22,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.019742965698242, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.676027297973633, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3482/4000 [33:19<04:17,  2.02it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.505114555358887, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.701987266540527, Predicted Probability: 0.9910, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3483/4000 [33:20<04:51,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.146224975585938, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.6252896785736084, Predicted Probability: 0.1645, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3484/4000 [33:20<05:19,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.234893321990967, Predicted Probability: 0.0967, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.000391006469727, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3485/4000 [33:21<05:35,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.91939926147461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.434983253479004, Predicted Probability: 0.0117, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3486/4000 [33:21<04:52,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.206353187561035, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.21628475189209, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3487/4000 [33:22<04:20,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.8440049886703491, Predicted Probability: 0.8634, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.7455472946167, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3488/4000 [33:22<03:57,  2.16it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.951247215270996, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.795025825500488, Predicted Probability: 0.0030, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3489/4000 [33:23<04:48,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.057682037353516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.821557998657227, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3490/4000 [33:24<05:16,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.195333480834961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.2522478103637695, Predicted Probability: 0.0140, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3491/4000 [33:24<05:40,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4215800762176514, Predicted Probability: 0.9684, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.046123504638672, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3492/4000 [33:25<05:49,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.500485420227051, Predicted Probability: 0.9707, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.195239067077637, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3493/4000 [33:26<05:56,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.031310081481934, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.546199381351471, Predicted Probability: 0.6333, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3494/4000 [33:26<04:49,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.457907676696777, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.285869598388672, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3495/4000 [33:27<05:31,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.24913215637207, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.680116176605225, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3496/4000 [33:28<05:43,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.486173629760742, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4380605220794678, Predicted Probability: 0.9197, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3497/4000 [33:28<05:23,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.8716402053833, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1289186477661133, Predicted Probability: 0.9581, Prediction: 1.0

Epoch 3/3:  87%|████████▋ | 3498/4000 [33:29<05:40,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.801766395568848, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.036948204040527, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  87%|████████▋ | 3499/4000 [33:30<05:48,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.17490291595459, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.025270938873291, Predicted Probability: 0.1166, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3500/4000 [33:31<06:02,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.519306182861328, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.496295928955078, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3501/4000 [33:31<05:09,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.2438383102417, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1579487323760986, Predicted Probability: 0.9592, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3502/4000 [33:32<05:37,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.452493667602539, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.429794788360596, Predicted Probability: 0.0118, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3503/4000 [33:32<05:29,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.4591064453125, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.17773151397705, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3504/4000 [33:33<05:47,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.119733810424805, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.8141450881958, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3505/4000 [33:34<04:58,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.591731071472168, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.069833755493164, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3506/4000 [33:34<05:32,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.362173557281494, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.533640384674072, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3507/4000 [33:35<05:42,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.61827278137207, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9927747249603271, Predicted Probability: 0.1200, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3508/4000 [33:36<05:47,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.270520806312561, Predicted Probability: 0.7808, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.242498397827148, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3509/4000 [33:36<05:23,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.8874090909957886, Predicted Probability: 0.7084, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2409632205963135, Predicted Probability: 0.9623, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3510/4000 [33:37<05:37,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.666003942489624, Predicted Probability: 0.9350, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.02733039855957, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3511/4000 [33:37<04:25,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.719514846801758, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.1519136428833, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3512/4000 [33:38<04:50,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.2168235778808594, Predicted Probability: 0.9018, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.4274749755859375, Predicted Probability: 0.0016, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3513/4000 [33:39<04:17,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.200207710266113, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.594820499420166, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3514/4000 [33:39<04:52,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.883768081665039, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.3675436973571777, Predicted Probability: 0.0333, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3515/4000 [33:40<05:12,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0643393993377686, Predicted Probability: 0.9554, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.532808303833008, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3516/4000 [33:41<05:24,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.95760726928711, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3832907676696777, Predicted Probability: 0.9672, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3517/4000 [33:41<04:17,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.239104270935059, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.8041410446167, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3518/4000 [33:42<05:01,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.757522583007812, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.845541954040527, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3519/4000 [33:43<05:16,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.2042236328125, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.7224949598312378, Predicted Probability: 0.3268, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3521/4000 [33:44<04:20,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.8183512687683105, Predicted Probability: 0.9437, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.7337188720703125, Predicted Probability: 0.9968, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.769610404968262, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.241275787353516, Predicted Probability: 0.9858, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3522/4000 [33:44<04:23,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.164125442504883, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 1.0879287719726562, Predicted Probability: 0.7480, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3523/4000 [33:45<05:01,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.166259765625, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.00677490234375, Predicted Probability: 0.9934, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3524/4000 [33:46<05:15,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.441171646118164, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.231606960296631, Predicted Probability: 0.9620, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3525/4000 [33:46<05:01,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.709442138671875, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.631827354431152, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3526/4000 [33:47<04:24,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.292916297912598, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.435887336730957, Predicted Probability: 0.0117, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3527/4000 [33:47<04:51,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.525517463684082, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.68854284286499, Predicted Probability: 0.0091, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3528/4000 [33:48<05:19,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.121200561523438, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.771562099456787, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3529/4000 [33:49<05:32,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.9437255859375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.996970176696777, Predicted Probability: 0.0067, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3530/4000 [33:50<05:35,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.91593074798584, Predicted Probability: 0.0004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9890650510787964, Predicted Probability: 0.1204, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3531/4000 [33:50<04:23,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.83825969696045, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9807000160217285, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3532/4000 [33:50<04:18,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.103266716003418, Predicted Probability: 0.9940, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.592714309692383, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3533/4000 [33:51<03:53,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.228446960449219, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.407710552215576, Predicted Probability: 0.9880, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3534/4000 [33:51<03:57,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.0672197341918945, Predicted Probability: 0.9937, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.452415466308594, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3535/4000 [33:52<03:37,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.032238960266113, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.984718322753906, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3536/4000 [33:52<04:14,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.0352954864501953, Predicted Probability: 0.9541, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.275087356567383, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  88%|████████▊ | 3537/4000 [33:53<04:40,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.385970115661621, Predicted Probability: 0.0046, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.853982448577881, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3538/4000 [33:54<05:06,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.875327110290527, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.016677856445312, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3539/4000 [33:55<05:17,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.800235748291016, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.565664768218994, Predicted Probability: 0.9962, Prediction: 1.0

Epoch 3/3:  88%|████████▊ | 3540/4000 [33:55<04:19,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.11530590057373, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.121658325195312, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  89%|████████▊ | 3541/4000 [33:56<04:39,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.789947986602783, Predicted Probability: 0.9421, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.360143661499023, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  89%|████████▊ | 3542/4000 [33:56<04:08,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.932729721069336, Predicted Probability: 0.9928, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.113893508911133, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  89%|████████▊ | 3543/4000 [33:57<04:43,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.771039962768555, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.762260437011719, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  89%|████████▊ | 3544/4000 [33:57<03:47,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.396750450134277, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.21811580657959, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  89%|████████▊ | 3545/4000 [33:58<04:20,  1.75it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.544482231140137, Predicted Probability: 0.9895, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.759186744689941, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  89%|████████▊ | 3546/4000 [33:59<04:46,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.018939971923828, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.513947010040283, Predicted Probability: 0.0108, Prediction: 0.0

Epoch 3/3:  89%|████████▊ | 3547/4000 [33:59<04:10,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.878622055053711, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.320921421051025, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  89%|████████▊ | 3548/4000 [33:59<03:23,  2.23it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.672404289245605, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.542691707611084, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  89%|████████▊ | 3549/4000 [34:00<03:59,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.802194595336914, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3200316429138184, Predicted Probability: 0.9651, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3550/4000 [34:00<04:00,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.33231258392334, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.957596778869629, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3551/4000 [34:01<04:22,  1.71it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.801603078842163, Predicted Probability: 0.9782, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.093876838684082, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3552/4000 [34:02<04:47,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.350350856781006, Predicted Probability: 0.0017, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.1554718017578125, Predicted Probability: 0.9846, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3554/4000 [34:03<05:09,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.6834728717803955, Predicted Probability: 0.0640, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.06683349609375, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3555/4000 [34:04<05:13,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.319141387939453, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.274211883544922, Predicted Probability: 0.0933, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3556/4000 [34:04<04:06,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.694278717041016, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.931264877319336, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3557/4000 [34:05<04:31,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.695803165435791, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.82783317565918, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3558/4000 [34:06<04:50,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.452484130859375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8989994525909424, Predicted Probability: 0.9801, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3559/4000 [34:07<05:01,  1.46it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.689495086669922, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 1.9468750953674316, Predicted Probability: 0.8751, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3560/4000 [34:07<05:10,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.38717269897461, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.176478862762451, Predicted Probability: 0.9979, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3561/4000 [34:08<04:03,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.036372661590576, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.08456039428711, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3562/4000 [34:08<03:41,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.904571533203125, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.997320175170898, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3563/4000 [34:09<04:12,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.293405532836914, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.424694538116455, Predicted Probability: 0.9685, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3564/4000 [34:09<04:37,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.794219017028809, Predicted Probability: 0.0082, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.266708374023438, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3565/4000 [34:10<04:02,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.055992126464844, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.098968505859375, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3566/4000 [34:11<04:23,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.86419677734375, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.0813610553741455, Predicted Probability: 0.9561, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3567/4000 [34:11<04:50,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.113776206970215, Predicted Probability: 0.9839, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.768672943115234, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3568/4000 [34:12<04:41,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.359919786453247, Predicted Probability: 0.9664, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.742416381835938, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3569/4000 [34:13<04:30,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.713622093200684, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.422384262084961, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3570/4000 [34:13<04:18,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.611200332641602, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.920614004135132, Predicted Probability: 0.0194, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3571/4000 [34:13<03:51,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.8266401290893555, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.693305015563965, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3572/4000 [34:14<04:16,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.6884565353393555, Predicted Probability: 0.0091, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.869482040405273, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3573/4000 [34:15<03:46,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.461430549621582, Predicted Probability: 0.9214, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.264815330505371, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3574/4000 [34:15<03:13,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.904685974121094, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.1743879318237305, Predicted Probability: 0.0056, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3575/4000 [34:16<03:56,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.250495910644531, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.888370990753174, Predicted Probability: 0.0075, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3576/4000 [34:16<03:31,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.070621967315674, Predicted Probability: 0.9977, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.921189308166504, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3577/4000 [34:17<04:01,  1.75it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.678268551826477, Predicted Probability: 0.1573, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.230378150939941, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  89%|████████▉ | 3578/4000 [34:17<03:36,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.302237510681152, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.287609100341797, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  89%|████████▉ | 3579/4000 [34:18<03:20,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.169292449951172, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.35990571975708, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3580/4000 [34:18<02:46,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.626439094543457, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.769941329956055, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3581/4000 [34:19<03:58,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.337844848632812, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.605567932128906, Predicted Probability: 0.0014, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3582/4000 [34:20<04:34,  1.52it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.244197845458984, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.470029830932617, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3583/4000 [34:20<04:28,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1812286376953125, Predicted Probability: 0.9944, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.1489572525024414, Predicted Probability: 0.9589, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3584/4000 [34:21<04:43,  1.47it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.281496047973633, Predicted Probability: 0.9638, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.793996810913086, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3585/4000 [34:22<04:53,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.578078269958496, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.449329376220703, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3586/4000 [34:22<04:58,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.311628341674805, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.927918434143066, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3587/4000 [34:23<05:05,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.036197662353516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.770256042480469, Predicted Probability: 0.9916, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3588/4000 [34:24<04:18,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.172725200653076, Predicted Probability: 0.9848, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.43068528175354, Predicted Probability: 0.9686, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3589/4000 [34:24<04:34,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.3907824754714966, Predicted Probability: 0.1993, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.232722520828247, Predicted Probability: 0.9620, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3590/4000 [34:25<03:58,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.532042503356934, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.848241329193115, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3591/4000 [34:26<04:22,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.295961380004883, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9104697704315186, Predicted Probability: 0.1289, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3592/4000 [34:26<03:36,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.477058410644531, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.253530502319336, Predicted Probability: 0.0372, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3593/4000 [34:26<03:17,  2.06it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.526176929473877, Predicted Probability: 0.0107, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.051955223083496, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3594/4000 [34:27<03:43,  1.81it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.48477840423584, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.770845651626587, Predicted Probability: 0.8546, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3595/4000 [34:28<04:06,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.3437395095825195, Predicted Probability: 0.0048, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.14973258972168, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3596/4000 [34:28<04:29,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.761651039123535, Predicted Probability: 0.9915, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.564228057861328, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  90%|████████▉ | 3597/4000 [34:29<03:55,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.921829223632812, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.453229904174805, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3598/4000 [34:30<04:26,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.69198226928711, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9618592262268066, Predicted Probability: 0.9508, Prediction: 1.0

Epoch 3/3:  90%|████████▉ | 3599/4000 [34:30<03:50,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.942630290985107, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.231640815734863, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3600/4000 [34:31<03:45,  1.78it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.095072269439697, Predicted Probability: 0.9939, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.015727996826172, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3601/4000 [34:31<04:09,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5032527446746826, Predicted Probability: 0.9244, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.278226852416992, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3602/4000 [34:32<04:28,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.31129264831543, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2948505878448486, Predicted Probability: 0.9643, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3603/4000 [34:33<03:50,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.588133811950684, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.159287452697754, Predicted Probability: 0.0057, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3604/4000 [34:33<03:33,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.704870700836182, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.427833557128906, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3605/4000 [34:33<03:20,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.672214031219482, Predicted Probability: 0.9907, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.352837562561035, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3606/4000 [34:34<03:03,  2.14it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.009549140930176, Predicted Probability: 0.9997, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.490361213684082, Predicted Probability: 0.9985, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3607/4000 [34:35<03:40,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.335668563842773, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.967530250549316, Predicted Probability: 0.0069, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3608/4000 [34:35<02:57,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4621403217315674, Predicted Probability: 0.9214, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.828245162963867, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3609/4000 [34:35<02:55,  2.23it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.163365364074707, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.492623329162598, Predicted Probability: 0.0111, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3610/4000 [34:36<03:29,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.043195724487305, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2597813606262207, Predicted Probability: 0.0370, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3612/4000 [34:37<02:34,  2.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.231294631958008, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.384902954101562, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 10.572134017944336, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.286589622497559, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3613/4000 [34:37<02:32,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.837220191955566, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.734657287597656, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3614/4000 [34:38<03:15,  1.98it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.29178237915039, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8375039100646973, Predicted Probability: 0.9447, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3615/4000 [34:38<02:40,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.455377578735352, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.99534797668457, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3616/4000 [34:39<03:16,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.482757568359375, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.1151018142700195, Predicted Probability: 0.9940, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3617/4000 [34:39<03:44,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.578871726989746, Predicted Probability: 0.0102, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.946320533752441, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3618/4000 [34:40<03:23,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.809945106506348, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.7880024909973145, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  90%|█████████ | 3619/4000 [34:40<03:04,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.678028106689453, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.904834747314453, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  90%|█████████ | 3620/4000 [34:40<02:31,  2.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.118021965026855, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.707955360412598, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3621/4000 [34:41<03:09,  2.00it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.119564056396484, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.607278823852539, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3622/4000 [34:42<03:33,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.922481060028076, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.84131145477295, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3623/4000 [34:42<03:12,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.38010835647583, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.763547897338867, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3624/4000 [34:42<02:47,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.564607620239258, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.587162971496582, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3625/4000 [34:43<02:27,  2.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.821663856506348, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.451268196105957, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3626/4000 [34:43<02:32,  2.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.330524921417236, Predicted Probability: 0.9870, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -1.3906214237213135, Predicted Probability: 0.1993, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3627/4000 [34:44<03:12,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.193128824234009, Predicted Probability: 0.1004, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.021479606628418, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3628/4000 [34:45<03:48,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.293371200561523, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.906533241271973, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3629/4000 [34:45<03:21,  1.84it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.171690940856934, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.385315895080566, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3630/4000 [34:46<04:00,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.822332382202148, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.970727443695068, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3631/4000 [34:47<04:10,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.386104583740234, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.786401271820068, Predicted Probability: 0.9969, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3632/4000 [34:47<03:35,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.985331058502197, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.746616840362549, Predicted Probability: 0.9988, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3633/4000 [34:48<03:53,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.167220115661621, Predicted Probability: 0.9596, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.104225158691406, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3634/4000 [34:49<03:49,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 0.2225259244441986, Predicted Probability: 0.5554, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.02316665649414, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3635/4000 [34:49<04:04,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.16457462310791, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.410096168518066, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3636/4000 [34:50<03:40,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.948939323425293, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.716115951538086, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3637/4000 [34:51<03:56,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5632786750793457, Predicted Probability: 0.9724, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.085227012634277, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3638/4000 [34:51<04:04,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.347499370574951, Predicted Probability: 0.9660, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.808035850524902, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3639/4000 [34:51<03:13,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.517388343811035, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.174505233764648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3640/4000 [34:52<03:36,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5130727291107178, Predicted Probability: 0.9711, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.937825202941895, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3641/4000 [34:53<03:49,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.9070963859558105, Predicted Probability: 0.0027, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.840916156768799, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3642/4000 [34:54<04:03,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.845270156860352, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.289255142211914, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3643/4000 [34:55<04:22,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.657928466796875, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.309176445007324, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3644/4000 [34:55<03:31,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.327237129211426, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.942173480987549, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3645/4000 [34:56<03:46,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4121417999267578, Predicted Probability: 0.1959, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.976426124572754, Predicted Probability: 0.0485, Prediction: 0.0

Epoch 3/3:  91%|█████████ | 3646/4000 [34:56<03:24,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.797658920288086, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.923158645629883, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3647/4000 [34:57<03:43,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.560007095336914, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.846824645996094, Predicted Probability: 0.9971, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3648/4000 [34:57<03:14,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.260244369506836, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.141898155212402, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  91%|█████████ | 3649/4000 [34:58<03:34,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.698594570159912, Predicted Probability: 0.9967, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.553929328918457, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  91%|█████████▏| 3650/4000 [34:59<03:53,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.44647741317749, Predicted Probability: 0.0016, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.8844146728515625, Predicted Probability: 0.0028, Prediction: 0.0

Epoch 3/3:  91%|█████████▏| 3651/4000 [34:59<03:29,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.754497528076172, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8038170337677, Predicted Probability: 0.9782, Prediction: 1.0

Epoch 3/3:  91%|█████████▏| 3652/4000 [35:00<03:03,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.60128402709961, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.145406723022461, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████▏| 3653/4000 [35:00<02:46,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.094816207885742, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.013075828552246, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  91%|█████████▏| 3654/4000 [35:00<02:42,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.430569648742676, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.136985778808594, Predicted Probability: 0.0022, Prediction: 0.0

Epoch 3/3:  91%|█████████▏| 3655/4000 [35:01<02:14,  2.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.52718448638916, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.671895027160645, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  91%|█████████▏| 3656/4000 [35:01<02:21,  2.43it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.657217025756836, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.9404296875, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  91%|█████████▏| 3657/4000 [35:02<02:35,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.825338363647461, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.634721755981445, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  91%|█████████▏| 3658/4000 [35:02<02:28,  2.31it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.963522911071777, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.230749130249023, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  91%|█████████▏| 3659/4000 [35:03<03:01,  1.88it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.88351058959961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 0.7741277813911438, Predicted Probability: 0.6844, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3660/4000 [35:03<03:21,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.516817092895508, Predicted Probability: 0.9712, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.446825981140137, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3661/4000 [35:04<03:32,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.81263542175293, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7817797660827637, Predicted Probability: 0.9777, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3662/4000 [35:05<03:24,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.164509773254395, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.118362426757812, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3663/4000 [35:05<03:00,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.345565795898438, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.5697455406188965, Predicted Probability: 0.9986, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3664/4000 [35:06<03:27,  1.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.973697662353516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7260019779205322, Predicted Probability: 0.9765, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3665/4000 [35:07<03:51,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.632604598999023, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.168243408203125, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3666/4000 [35:07<03:55,  1.42it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.331025123596191, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.531156063079834, Predicted Probability: 0.9961, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3667/4000 [35:08<04:08,  1.34it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.66024112701416, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.596850395202637, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3668/4000 [35:09<03:30,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.242000102996826, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.035161018371582, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3669/4000 [35:09<03:20,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.889598369598389, Predicted Probability: 0.9925, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.824450492858887, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3670/4000 [35:10<02:56,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.990326881408691, Predicted Probability: 0.9975, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.170480728149414, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3671/4000 [35:10<02:39,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.785980224609375, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.523368835449219, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3672/4000 [35:10<02:27,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.2903618812561035, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.357885360717773, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3673/4000 [35:11<02:18,  2.35it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.118678092956543, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.868868827819824, Predicted Probability: 0.0076, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3674/4000 [35:11<02:53,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.111219882965088, Predicted Probability: 0.9978, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.1145524978637695, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3675/4000 [35:12<02:45,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.344972610473633, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.630913734436035, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3676/4000 [35:13<03:06,  1.74it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4635733366012573, Predicted Probability: 0.1879, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.524259567260742, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3677/4000 [35:13<02:30,  2.14it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.706074714660645, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.991753578186035, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3678/4000 [35:13<02:20,  2.29it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.819361686706543, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.2403347492218018, Predicted Probability: 0.0377, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3679/4000 [35:14<02:55,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.648855209350586, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.477451801300049, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3680/4000 [35:15<03:13,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.727764844894409, Predicted Probability: 0.9765, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.347494125366211, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3681/4000 [35:15<02:56,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.247998237609863, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.982663869857788, Predicted Probability: 0.0482, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3682/4000 [35:16<03:13,  1.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.1437883377075195, Predicted Probability: 0.9942, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.916168212890625, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3683/4000 [35:16<02:50,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9846038818359375, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.378800392150879, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3684/4000 [35:17<03:10,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.5686614513397217, Predicted Probability: 0.9726, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.697338104248047, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3685/4000 [35:18<03:30,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.712079048156738, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.522222518920898, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3686/4000 [35:18<02:45,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.830310821533203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.647733688354492, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3687/4000 [35:19<03:06,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.369524002075195, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.0776824951171875, Predicted Probability: 0.8887, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3688/4000 [35:20<03:21,  1.55it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.64981746673584, Predicted Probability: 0.9747, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.86231803894043, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3690/4000 [35:20<02:20,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.952453136444092, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.159197807312012, Predicted Probability: 0.9999, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.72206974029541, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.014915466308594, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3691/4000 [35:20<01:57,  2.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.099745750427246, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.14526081085205, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3692/4000 [35:21<02:13,  2.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.645723342895508, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.714687824249268, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3693/4000 [35:22<02:29,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.34625244140625, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: 2.4524943828582764, Predicted Probability: 0.9207, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3694/4000 [35:22<03:03,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.560055255889893, Predicted Probability: 0.9962, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.092543125152588, Predicted Probability: 0.0023, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3695/4000 [35:23<03:14,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.01035213470459, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.6020309925079346, Predicted Probability: 0.3539, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3696/4000 [35:24<03:25,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.5927658081054688, Predicted Probability: 0.0268, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.027227401733398, Predicted Probability: 0.0009, Prediction: 0.0

Epoch 3/3:  92%|█████████▏| 3697/4000 [35:24<02:42,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.148838996887207, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.851058006286621, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  92%|█████████▏| 3698/4000 [35:25<03:10,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.124990940093994, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.503791809082031, Predicted Probability: 0.0006, Prediction: 0.0

Epoch 3/3:  92%|█████████▎| 3700/4000 [35:26<02:36,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.6962075233459473, Predicted Probability: 0.9758, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.487403869628906, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 11.071526527404785, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.07069730758667, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3701/4000 [35:26<02:37,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.577146530151367, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.251501560211182, Predicted Probability: 0.9860, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3702/4000 [35:27<02:57,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.504382848739624, Predicted Probability: 0.9708, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.255072593688965, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3703/4000 [35:28<03:08,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.816765308380127, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.092256546020508, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3704/4000 [35:29<03:18,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.711996078491211, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.173652648925781, Predicted Probability: 0.9848, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3705/4000 [35:29<03:24,  1.44it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.520979881286621, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.606842041015625, Predicted Probability: 0.9313, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3706/4000 [35:30<03:13,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.63700008392334, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.145522117614746, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3707/4000 [35:31<03:19,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.562738418579102, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.4514684677124023, Predicted Probability: 0.9207, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3708/4000 [35:31<03:25,  1.42it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.490572929382324, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.401253700256348, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3709/4000 [35:32<02:55,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.436402320861816, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.623686790466309, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3710/4000 [35:33<03:05,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.20180606842041, Predicted Probability: 0.9609, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.007011413574219, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3711/4000 [35:33<02:42,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.437341690063477, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.051704406738281, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3712/4000 [35:34<02:57,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.657841205596924, Predicted Probability: 0.9965, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.948678970336914, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3713/4000 [35:34<02:37,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.138827800750732, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.434191703796387, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3714/4000 [35:35<02:50,  1.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.833937644958496, Predicted Probability: 0.9445, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.271411895751953, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3715/4000 [35:36<03:02,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.726581573486328, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.261585235595703, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3716/4000 [35:36<02:30,  1.88it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.497183799743652, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.290419578552246, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3717/4000 [35:37<02:47,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.804497718811035, Predicted Probability: 0.9919, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.873520851135254, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3718/4000 [35:37<02:43,  1.73it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.100338459014893, Predicted Probability: 0.0022, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.361546516418457, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3719/4000 [35:38<03:00,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.109502792358398, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.236177444458008, Predicted Probability: 0.0007, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3720/4000 [35:38<02:41,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.933953285217285, Predicted Probability: 0.9974, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.970617294311523, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3721/4000 [35:39<02:58,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.843078136444092, Predicted Probability: 0.0210, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.364277839660645, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3722/4000 [35:39<02:21,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.061443328857422, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.179839134216309, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3723/4000 [35:40<02:42,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.485180854797363, Predicted Probability: 0.0111, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.698319435119629, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3724/4000 [35:41<02:56,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.821794509887695, Predicted Probability: 0.0080, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.094274520874023, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3725/4000 [35:41<02:34,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.197931289672852, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.641173362731934, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3726/4000 [35:41<02:04,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.735891342163086, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.536602020263672, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3727/4000 [35:42<02:24,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.52627182006836, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.2470319271087646, Predicted Probability: 0.2232, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3728/4000 [35:43<02:40,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7049078941345215, Predicted Probability: 0.9760, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.9998180866241455, Predicted Probability: 0.9526, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3729/4000 [35:43<02:21,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.017918586730957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.291706085205078, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3730/4000 [35:44<02:41,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.688868522644043, Predicted Probability: 0.9966, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.232828140258789, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3731/4000 [35:44<02:24,  1.87it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.376496315002441, Predicted Probability: 0.9954, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.299897193908691, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3732/4000 [35:45<02:10,  2.06it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.064723014831543, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.859494209289551, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3733/4000 [35:45<02:06,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.094520568847656, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 4.353670120239258, Predicted Probability: 0.9873, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3734/4000 [35:46<02:28,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.00627613067627, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.9642205238342285, Predicted Probability: 0.9974, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3735/4000 [35:47<02:44,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.432939052581787, Predicted Probability: 0.9687, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: -0.6567662358283997, Predicted Probability: 0.3415, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3736/4000 [35:47<02:52,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.590662717819214, Predicted Probability: 0.9303, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.132502555847168, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3737/4000 [35:48<02:59,  1.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.383659362792969, Predicted Probability: 0.0123, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.291797637939453, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  93%|█████████▎| 3738/4000 [35:49<02:34,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.702295303344727, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.083662986755371, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  93%|█████████▎| 3739/4000 [35:49<02:23,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.138251304626465, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.689292907714844, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  94%|█████████▎| 3740/4000 [35:50<02:41,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.842130661010742, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.916328430175781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▎| 3742/4000 [35:50<01:54,  2.25it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.429448127746582, Predicted Probability: 0.8068, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.980299949645996, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.064543724060059, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.633509635925293, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▎| 3743/4000 [35:51<02:24,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.278103351593018, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.60947322845459, Predicted Probability: 0.9964, Prediction: 1.0

Epoch 3/3:  94%|█████████▎| 3744/4000 [35:52<02:39,  1.60it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.283881187438965, Predicted Probability: 0.0136, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.344724655151367, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▎| 3745/4000 [35:52<02:21,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.85170841217041, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.185736656188965, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  94%|█████████▎| 3746/4000 [35:53<01:54,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.321128845214844, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.39795970916748, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▎| 3748/4000 [35:53<01:34,  2.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.548545837402344, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.533534049987793, Predicted Probability: 0.9998, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.768162727355957, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.8181002140045166, Predicted Probability: 0.9785, Prediction: 1.0

Epoch 3/3:  94%|█████████▎| 3749/4000 [35:54<01:33,  2.68it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.484628677368164, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.984739303588867, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3750/4000 [35:54<02:02,  2.04it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.377182960510254, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.195705890655518, Predicted Probability: 0.9945, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3751/4000 [35:55<01:53,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.44683313369751, Predicted Probability: 0.0043, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.509303092956543, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3752/4000 [35:56<02:14,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.74766731262207, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.518290996551514, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3753/4000 [35:56<02:27,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.920539379119873, Predicted Probability: 0.1278, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.788080215454102, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3754/4000 [35:57<02:37,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.881583213806152, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.4926908016204834, Predicted Probability: 0.0295, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3755/4000 [35:58<02:45,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.894309043884277, Predicted Probability: 0.9973, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.279088020324707, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3756/4000 [35:59<02:53,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.598893165588379, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.225261688232422, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3757/4000 [35:59<02:57,  1.37it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.019532203674316, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.153679847717285, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3758/4000 [36:00<02:42,  1.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.459145545959473, Predicted Probability: 0.9958, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.117494583129883, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3759/4000 [36:00<02:20,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.956645965576172, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.3947434425354, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3760/4000 [36:01<01:57,  2.04it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.13175106048584, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.242671966552734, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3761/4000 [36:01<01:48,  2.20it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.3211669921875, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6720945835113525, Predicted Probability: 0.9752, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3762/4000 [36:02<02:08,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.231783866882324, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.6610214710235596, Predicted Probability: 0.9749, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3763/4000 [36:02<02:11,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.595693588256836, Predicted Probability: 0.9900, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 3.82708740234375, Predicted Probability: 0.9787, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3764/4000 [36:03<02:25,  1.63it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.864630222320557, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.218908309936523, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3765/4000 [36:03<02:07,  1.84it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.370793342590332, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.758665561676025, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3766/4000 [36:04<02:25,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.690618515014648, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.527782917022705, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3767/4000 [36:04<02:06,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.81157112121582, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.533528327941895, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3768/4000 [36:05<01:53,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.789673805236816, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.396797180175781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3769/4000 [36:06<02:15,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.493091583251953, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.347938537597656, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3770/4000 [36:07<02:33,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.299739837646484, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.701544761657715, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3771/4000 [36:07<02:37,  1.45it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4785847663879395, Predicted Probability: 0.9701, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.668386459350586, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3772/4000 [36:08<02:48,  1.35it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.296561241149902, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.830323219299316, Predicted Probability: 0.0029, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3773/4000 [36:09<02:23,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.448055744171143, Predicted Probability: 0.9984, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.297130584716797, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3774/4000 [36:09<02:30,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.486286163330078, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.1005007028579712, Predicted Probability: 0.2496, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3775/4000 [36:10<02:10,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.598037242889404, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.004467964172363, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3776/4000 [36:10<01:44,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.169264793395996, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.344380855560303, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3777/4000 [36:10<01:38,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.053348541259766, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.315025329589844, Predicted Probability: 0.0049, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3778/4000 [36:11<01:57,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.3348307609558105, Predicted Probability: 0.0883, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.329097747802734, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  94%|█████████▍| 3779/4000 [36:11<01:58,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.699208974838257, Predicted Probability: 0.0241, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.91714096069336, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  94%|█████████▍| 3780/4000 [36:12<01:36,  2.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.5343017578125, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.41822624206543, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3781/4000 [36:12<01:31,  2.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.38059139251709, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.062994956970215, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  95%|█████████▍| 3782/4000 [36:12<01:27,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.7051420211792, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.70334243774414, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3783/4000 [36:13<01:52,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.738396644592285, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.919774055480957, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3784/4000 [36:14<01:53,  1.90it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.8764142990112305, Predicted Probability: 0.9924, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.83890438079834, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3785/4000 [36:15<02:15,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.293591022491455, Predicted Probability: 0.0018, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.715707778930664, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3786/4000 [36:15<02:25,  1.48it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.952432632446289, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.907926559448242, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3787/4000 [36:16<02:31,  1.41it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.988964080810547, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.9274208545684814, Predicted Probability: 0.0508, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3788/4000 [36:17<02:03,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.940837860107422, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.600735664367676, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  95%|█████████▍| 3789/4000 [36:17<02:14,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.287355422973633, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.3012566566467285, Predicted Probability: 0.0134, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3790/4000 [36:18<01:56,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.301916122436523, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.90661096572876, Predicted Probability: 0.9990, Prediction: 1.0

Epoch 3/3:  95%|█████████▍| 3791/4000 [36:18<01:45,  1.97it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.017578125, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.712986946105957, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  95%|█████████▍| 3792/4000 [36:18<01:26,  2.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.083932876586914, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.800626754760742, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  95%|█████████▍| 3794/4000 [36:19<01:09,  2.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.303601264953613, Predicted Probability: 0.9982, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.206778526306152, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -8.46068286895752, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.563840866088867, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  95%|█████████▍| 3795/4000 [36:20<01:38,  2.08it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.106573581695557, Predicted Probability: 0.0162, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.196067810058594, Predicted Probability: 0.0020, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3796/4000 [36:20<01:53,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.5583117008209229, Predicted Probability: 0.8261, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.308012008666992, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3797/4000 [36:21<02:04,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.769193649291992, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -5.084195137023926, Predicted Probability: 0.0062, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3798/4000 [36:21<01:49,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.57351541519165, Predicted Probability: 0.9898, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.469243049621582, Predicted Probability: 0.0015, Prediction: 0.0

Epoch 3/3:  95%|█████████▍| 3799/4000 [36:22<02:00,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.635151863098145, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.4062352180480957, Predicted Probability: 0.9679, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3800/4000 [36:23<01:58,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.210364818572998, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.586919784545898, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3801/4000 [36:24<02:06,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.7384300231933594, Predicted Probability: 0.8505, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.904828071594238, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3802/4000 [36:24<02:11,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.046517848968506, Predicted Probability: 0.9546, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.1693642139434814, Predicted Probability: 0.0403, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3803/4000 [36:25<02:04,  1.58it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.319584846496582, Predicted Probability: 0.9993, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.824917793273926, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3804/4000 [36:25<01:50,  1.77it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.734672546386719, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.604708671569824, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3805/4000 [36:26<01:49,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.428783416748047, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.1181182861328125, Predicted Probability: 0.8927, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3806/4000 [36:26<01:38,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.510743141174316, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -3.292707681655884, Predicted Probability: 0.0358, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3807/4000 [36:27<01:53,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.888872146606445, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.899396896362305, Predicted Probability: 0.0010, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3808/4000 [36:27<01:30,  2.12it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.225217819213867, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.512856483459473, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3809/4000 [36:28<01:44,  1.83it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.471623420715332, Predicted Probability: 0.9699, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.160850524902344, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3810/4000 [36:29<01:55,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.52815055847168, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -0.1490681767463684, Predicted Probability: 0.4628, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3811/4000 [36:29<02:05,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.84002685546875, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.751195907592773, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3812/4000 [36:30<02:09,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.4977991580963135, Predicted Probability: 0.1828, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.120716094970703, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3813/4000 [36:31<02:17,  1.36it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.485479354858398, Predicted Probability: 0.0041, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.164656639099121, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3814/4000 [36:31<01:56,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.956587791442871, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.715387344360352, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3815/4000 [36:32<01:41,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.708591461181641, Predicted Probability: 0.9988, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.01522159576416, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3816/4000 [36:33<02:03,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.683646202087402, Predicted Probability: 0.0012, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.247042655944824, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  95%|█████████▌| 3817/4000 [36:33<02:05,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.98767375946045, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.511531352996826, Predicted Probability: 0.9710, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3818/4000 [36:34<01:47,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.544044494628906, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.899407386779785, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  95%|█████████▌| 3819/4000 [36:34<01:54,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.981607437133789, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5699853897094727, Predicted Probability: 0.9726, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3820/4000 [36:35<02:01,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.127001762390137, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9262261390686035, Predicted Probability: 0.1272, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3821/4000 [36:36<02:06,  1.41it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.679880142211914, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.690417289733887, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3822/4000 [36:37<02:14,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.459457397460938, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3575146198272705, Predicted Probability: 0.9664, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3823/4000 [36:37<01:45,  1.68it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.789590835571289, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.165189266204834, Predicted Probability: 0.0405, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3824/4000 [36:38<01:33,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.692771911621094, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.179263114929199, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3825/4000 [36:38<01:25,  2.05it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.013172149658203, Predicted Probability: 0.9976, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.079628944396973, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3826/4000 [36:39<01:39,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.846619129180908, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.418233871459961, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3827/4000 [36:39<01:29,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.647161483764648, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.623955726623535, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3828/4000 [36:39<01:21,  2.10it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.880033493041992, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.341755390167236, Predicted Probability: 0.9952, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3829/4000 [36:40<01:20,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.833867073059082, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.93362045288086, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3830/4000 [36:41<01:34,  1.80it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.90498161315918, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.531115531921387, Predicted Probability: 0.9893, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3831/4000 [36:41<01:25,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.279750347137451, Predicted Probability: 0.9981, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.7803874015808105, Predicted Probability: 0.9989, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3832/4000 [36:42<01:39,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.082874298095703, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.352986335754395, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3833/4000 [36:43<01:47,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.791917324066162, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.6014404296875, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3834/4000 [36:43<01:32,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.331038475036621, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.493169784545898, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3835/4000 [36:44<01:47,  1.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.45060920715332, Predicted Probability: 0.9957, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.74168586730957, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3836/4000 [36:45<01:57,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.628687858581543, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -3.7854206562042236, Predicted Probability: 0.0222, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3837/4000 [36:45<01:58,  1.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.14749813079834, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.014193296432495, Predicted Probability: 0.8823, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3838/4000 [36:46<01:40,  1.61it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.9420881271362305, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.548863410949707, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3839/4000 [36:46<01:28,  1.82it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.421210289001465, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.806403636932373, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3841/4000 [36:47<00:58,  2.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.294072151184082, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.566146850585938, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 0.0, Final Logit: -10.125399589538574, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.23469066619873, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3842/4000 [36:47<01:06,  2.38it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.80860710144043, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.054572105407715, Predicted Probability: 0.0170, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3843/4000 [36:48<01:20,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.647385358810425, Predicted Probability: 0.9338, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.76462459564209, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3844/4000 [36:49<01:30,  1.72it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.162306070327759, Predicted Probability: 0.9594, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.946441650390625, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3845/4000 [36:49<01:38,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.546055257320404, Predicted Probability: 0.3668, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.388547897338867, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3846/4000 [36:50<01:26,  1.78it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.779567241668701, Predicted Probability: 0.0011, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.116623878479004, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3847/4000 [36:50<01:17,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.9073028564453125, Predicted Probability: 0.9990, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.252579689025879, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▌| 3848/4000 [36:51<01:13,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.354661464691162, Predicted Probability: 0.0127, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.577425956726074, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  96%|█████████▌| 3849/4000 [36:51<01:16,  1.98it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.7479329109191895, Predicted Probability: 0.9914, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 9.014162063598633, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3850/4000 [36:52<01:17,  1.94it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.850381851196289, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.225479602813721, Predicted Probability: 0.9856, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3851/4000 [36:52<01:03,  2.36it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.607413291931152, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.130558013916016, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3852/4000 [36:52<01:00,  2.46it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.16029167175293, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.5884928703308105, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3854/4000 [36:53<01:02,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.260339736938477, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.84728717803955, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 9.154158592224121, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.521397590637207, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3855/4000 [36:54<01:15,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.497164726257324, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.26448917388916, Predicted Probability: 0.9949, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3856/4000 [36:55<01:16,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.099047660827637, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.173065185546875, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3857/4000 [36:55<01:24,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.681312561035156, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -1.9319345951080322, Predicted Probability: 0.1265, Prediction: 0.0

Epoch 3/3:  96%|█████████▋| 3858/4000 [36:56<01:14,  1.91it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.73853588104248, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.776680946350098, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  96%|█████████▋| 3859/4000 [36:56<01:10,  2.01it/s]

Data point 1: Actual Class: 0.0, Final Logit: -3.7231056690216064, Predicted Probability: 0.0236, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.987361907958984, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3861/4000 [36:57<00:53,  2.62it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.421538352966309, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.878512859344482, Predicted Probability: 0.9924, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -8.605597496032715, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.644729614257812, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3862/4000 [36:57<00:55,  2.47it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.277307510375977, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.756063461303711, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3863/4000 [36:57<00:54,  2.53it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.335543632507324, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 2.6897382736206055, Predicted Probability: 0.9364, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3864/4000 [36:58<00:52,  2.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.418659210205078, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.088337421417236, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3865/4000 [36:59<01:08,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.528151035308838, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.219348907470703, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3866/4000 [36:59<01:21,  1.64it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.035526275634766, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.497119903564453, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3867/4000 [37:00<01:21,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.7168309688568115, Predicted Probability: 0.9763, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.88387393951416, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3868/4000 [37:00<01:11,  1.86it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.876178741455078, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.25271224975586, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3869/4000 [37:01<01:03,  2.05it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.996477127075195, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -6.794283866882324, Predicted Probability: 0.0011, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3870/4000 [37:01<00:58,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.61568832397461, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.462409019470215, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3871/4000 [37:02<00:55,  2.33it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.633522987365723, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.351752281188965, Predicted Probability: 0.9983, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3872/4000 [37:02<01:07,  1.89it/s]

Data point 1: Actual Class: 0.0, Final Logit: -0.5906170010566711, Predicted Probability: 0.3565, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.80870246887207, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3874/4000 [37:03<01:00,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.4370784759521484, Predicted Probability: 0.9688, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.749053001403809, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.76253604888916, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.107605457305908, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3875/4000 [37:04<00:59,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.496957302093506, Predicted Probability: 0.0015, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.999212265014648, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3877/4000 [37:05<00:50,  2.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.971732139587402, Predicted Probability: 0.9991, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.475818634033203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 0.0, Final Logit: -11.956483840942383, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -9.640731811523438, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3878/4000 [37:05<01:05,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.364437103271484, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.766136169433594, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3879/4000 [37:06<00:58,  2.07it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.063864231109619, Predicted Probability: 0.0009, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 12.049560546875, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3880/4000 [37:06<01:06,  1.79it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.445683479309082, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.313999652862549, Predicted Probability: 0.9868, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3881/4000 [37:07<01:00,  1.96it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.694090843200684, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.299903869628906, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3882/4000 [37:08<01:09,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.646446228027344, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.539863586425781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3883/4000 [37:08<01:04,  1.83it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.034614562988281, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.860146522521973, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3884/4000 [37:09<01:10,  1.66it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.223075866699219, Predicted Probability: 0.9946, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.931822776794434, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3885/4000 [37:10<01:13,  1.56it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.036914825439453, Predicted Probability: 0.1154, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.623790740966797, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3886/4000 [37:10<01:16,  1.49it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.4945478439331055, Predicted Probability: 0.0006, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.764505386352539, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3887/4000 [37:11<01:06,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.357163429260254, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.1293253898620605, Predicted Probability: 0.9992, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3888/4000 [37:11<00:52,  2.13it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.378417491912842, Predicted Probability: 0.9670, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.611832618713379, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3889/4000 [37:12<01:04,  1.71it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.644606590270996, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.590919494628906, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3890/4000 [37:12<00:57,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.914360046386719, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.682450294494629, Predicted Probability: 0.0092, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3891/4000 [37:13<01:04,  1.70it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.480533599853516, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.8817925453186035, Predicted Probability: 0.9469, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3892/4000 [37:13<00:51,  2.11it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.810037612915039, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.303215980529785, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3893/4000 [37:14<00:59,  1.81it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.206034660339355, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.70634651184082, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3894/4000 [37:14<00:55,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -4.955941677093506, Predicted Probability: 0.0070, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.5731987953186035, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3895/4000 [37:15<00:49,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.184678077697754, Predicted Probability: 0.9979, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.010497093200684, Predicted Probability: 0.9991, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3896/4000 [37:15<00:57,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.5847373008728027, Predicted Probability: 0.9299, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.92298698425293, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  97%|█████████▋| 3897/4000 [37:16<00:51,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.15248966217041, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.864946365356445, Predicted Probability: 0.9972, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3898/4000 [37:16<00:58,  1.76it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.7890625, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.5690934658050537, Predicted Probability: 0.9288, Prediction: 1.0

Epoch 3/3:  97%|█████████▋| 3899/4000 [37:17<01:03,  1.60it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.945752143859863, Predicted Probability: 0.9929, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.634771347045898, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3900/4000 [37:18<01:06,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.848134994506836, Predicted Probability: 0.9922, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.706088542938232, Predicted Probability: 0.0012, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3901/4000 [37:19<01:08,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.96295166015625, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 4.3450422286987305, Predicted Probability: 0.9872, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3902/4000 [37:19<01:03,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.136487007141113, Predicted Probability: 0.0008, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.982964038848877, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3903/4000 [37:20<01:05,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.761602401733398, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.4924330711364746, Predicted Probability: 0.0764, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3904/4000 [37:21<01:07,  1.43it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.444465637207031, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.040247678756714, Predicted Probability: 0.9544, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3905/4000 [37:22<01:08,  1.39it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.769809722900391, Predicted Probability: 0.9969, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.930496215820312, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3906/4000 [37:22<00:59,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.111084938049316, Predicted Probability: 0.0060, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.279522895812988, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3907/4000 [37:22<00:51,  1.80it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.257353782653809, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 6.213260173797607, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3908/4000 [37:23<00:56,  1.64it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.2367610931396484, Predicted Probability: 0.9622, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.517440795898438, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3910/4000 [37:23<00:36,  2.49it/s]

Data point 1: Actual Class: 1.0, Final Logit: 12.343652725219727, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.24712085723877, Predicted Probability: 0.0000, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.469185829162598, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.5625739097595215, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3911/4000 [37:24<00:45,  1.97it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.306151866912842, Predicted Probability: 0.9094, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.38436222076416, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3912/4000 [37:25<00:46,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.27624225616455, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.42845630645752, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3913/4000 [37:26<00:52,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.456048965454102, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.187111854553223, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3914/4000 [37:26<00:50,  1.70it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.513705730438232, Predicted Probability: 0.9892, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.158125877380371, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3915/4000 [37:26<00:44,  1.92it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.252720832824707, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.72806453704834, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3916/4000 [37:27<00:50,  1.67it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.308210372924805, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.962759017944336, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3917/4000 [37:28<00:52,  1.59it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.581428289413452, Predicted Probability: 0.9729, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.736886024475098, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3918/4000 [37:28<00:49,  1.66it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.546533584594727, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.2406110763549805, Predicted Probability: 0.9981, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3919/4000 [37:29<00:51,  1.56it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.186539649963379, Predicted Probability: 0.9603, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.841865539550781, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3920/4000 [37:29<00:40,  1.95it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.829339981079102, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.779138565063477, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3921/4000 [37:30<00:45,  1.72it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.4073903560638428, Predicted Probability: 0.0826, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.751789093017578, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3922/4000 [37:31<00:40,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.740068435668945, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.251907348632812, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3923/4000 [37:31<00:36,  2.11it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.548367023468018, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 5.93043851852417, Predicted Probability: 0.9973, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3924/4000 [37:31<00:33,  2.27it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.446646690368652, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -2.34666109085083, Predicted Probability: 0.0873, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3925/4000 [37:32<00:31,  2.40it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.582589149475098, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.232141494750977, Predicted Probability: 0.9997, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3926/4000 [37:32<00:38,  1.92it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.044621467590332, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 5.969954967498779, Predicted Probability: 0.9975, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3927/4000 [37:33<00:35,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.651700019836426, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.975476264953613, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3928/4000 [37:33<00:32,  2.24it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.511625289916992, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.470966339111328, Predicted Probability: 0.9994, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3929/4000 [37:34<00:43,  1.65it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.434152603149414, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 2.3943586349487305, Predicted Probability: 0.9164, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3930/4000 [37:35<00:46,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.71031379699707, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.04461669921875, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3931/4000 [37:35<00:43,  1.59it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.488340377807617, Predicted Probability: 0.0002, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.235309600830078, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3933/4000 [37:36<00:35,  1.91it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.279934883117676, Predicted Probability: 0.9949, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.200396537780762, Predicted Probability: 0.0001, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: -0.9767349362373352, Predicted Probability: 0.2735, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.498270034790039, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3934/4000 [37:37<00:39,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.529530048370361, Predicted Probability: 0.9893, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.339049339294434, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3935/4000 [37:38<00:42,  1.53it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.673659801483154, Predicted Probability: 0.0005, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2118308544158936, Predicted Probability: 0.9613, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3936/4000 [37:38<00:36,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.996771335601807, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.716246604919434, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  98%|█████████▊| 3937/4000 [37:39<00:28,  2.18it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.500253677368164, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 10.24483871459961, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3938/4000 [37:39<00:26,  2.30it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.5413126945495605, Predicted Probability: 0.9986, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.319465637207031, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3939/4000 [37:40<00:32,  1.87it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.312217712402344, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.3471522331237793, Predicted Probability: 0.9660, Prediction: 1.0

Epoch 3/3:  98%|█████████▊| 3940/4000 [37:41<00:37,  1.62it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.820832252502441, Predicted Probability: 0.9970, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.699474811553955, Predicted Probability: 0.0005, Prediction: 0.0

Epoch 3/3:  99%|█████████▊| 3941/4000 [37:41<00:39,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.93916130065918, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 8.700990676879883, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  99%|█████████▊| 3942/4000 [37:42<00:33,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.441858768463135, Predicted Probability: 0.9994, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.782917976379395, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  99%|█████████▊| 3943/4000 [37:42<00:36,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.712013244628906, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 7.717876434326172, Predicted Probability: 0.9996, Prediction: 1.0

Epoch 3/3:  99%|█████████▊| 3944/4000 [37:43<00:40,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -6.6378254890441895, Predicted Probability: 0.0013, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.305534362792969, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▊| 3945/4000 [37:44<00:39,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.549492835998535, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.7347424030303955, Predicted Probability: 0.9767, Prediction: 1.0

Epoch 3/3:  99%|█████████▊| 3946/4000 [37:45<00:39,  1.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.274085998535156, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 1.9438302516937256, Predicted Probability: 0.8748, Prediction: 1.0

Epoch 3/3:  99%|█████████▊| 3947/4000 [37:46<00:40,  1.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.67727279663086, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -7.7382001876831055, Predicted Probability: 0.0004, Prediction: 0.0

Epoch 3/3:  99%|█████████▊| 3948/4000 [37:46<00:40,  1.29it/s]

Data point 1: Actual Class: 0.0, Final Logit: -8.210550308227539, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.0592851638793945, Predicted Probability: 0.9977, Prediction: 1.0

Epoch 3/3:  99%|█████████▊| 3949/4000 [37:47<00:39,  1.30it/s]

Data point 1: Actual Class: 0.0, Final Logit: 0.6150908470153809, Predicted Probability: 0.6491, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.119002819061279, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3950/4000 [37:48<00:39,  1.28it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.473152160644531, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.597265243530273, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3951/4000 [37:48<00:32,  1.52it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.587138652801514, Predicted Probability: 0.9995, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.116948127746582, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3952/4000 [37:49<00:32,  1.48it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.663294792175293, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.490074872970581, Predicted Probability: 0.9704, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3953/4000 [37:50<00:30,  1.57it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.9974446296691895, Predicted Probability: 0.9933, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.3681001663208, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3954/4000 [37:50<00:30,  1.50it/s]

Data point 1: Actual Class: 1.0, Final Logit: 1.287308692932129, Predicted Probability: 0.7837, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.057815551757812, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3955/4000 [37:51<00:25,  1.73it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.893328666687012, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.354415893554688, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3956/4000 [37:51<00:22,  1.94it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.074939727783203, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -7.100342750549316, Predicted Probability: 0.0008, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3957/4000 [37:51<00:18,  2.37it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.515972137451172, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.286274909973145, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3958/4000 [37:52<00:17,  2.34it/s]

Data point 1: Actual Class: 1.0, Final Logit: 2.4146883487701416, Predicted Probability: 0.9179, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -4.828603744506836, Predicted Probability: 0.0079, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3959/4000 [37:53<00:22,  1.85it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.792903900146484, Predicted Probability: 0.9996, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.583919525146484, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3960/4000 [37:53<00:25,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.737990379333496, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.003890991210938, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3961/4000 [37:54<00:21,  1.79it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.39566421508789, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -6.6172685623168945, Predicted Probability: 0.0013, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3962/4000 [37:54<00:19,  1.99it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.956750869750977, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.359461784362793, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3963/4000 [37:55<00:21,  1.69it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.181514739990234, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.334792613983154, Predicted Probability: 0.9982, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3964/4000 [37:56<00:23,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.079686164855957, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2985472679138184, Predicted Probability: 0.9644, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3965/4000 [37:56<00:19,  1.77it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.593762397766113, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.65618896484375, Predicted Probability: 0.9995, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3966/4000 [37:57<00:21,  1.61it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.645979881286621, Predicted Probability: 0.0035, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -2.097834587097168, Predicted Probability: 0.1093, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3967/4000 [37:58<00:21,  1.51it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.059380531311035, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.5389111042022705, Predicted Probability: 0.9718, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3968/4000 [37:58<00:22,  1.40it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.620149612426758, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.962800979614258, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3970/4000 [37:59<00:13,  2.21it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.53987979888916, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.567918300628662, Predicted Probability: 0.0038, Prediction: 0.0
Data point 1: Actual Class: 1.0, Final Logit: 10.839887619018555, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.47985553741455, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3971/4000 [37:59<00:10,  2.65it/s]

Data point 1: Actual Class: 1.0, Final Logit: 11.039207458496094, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -5.905582427978516, Predicted Probability: 0.0027, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3972/4000 [37:59<00:10,  2.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 8.682838439941406, Predicted Probability: 0.9998, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.358154296875, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3973/4000 [38:00<00:13,  1.95it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.982364654541016, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.247146606445312, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3974/4000 [38:01<00:13,  1.93it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.560014009475708, Predicted Probability: 0.0718, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 9.242342948913574, Predicted Probability: 0.9999, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3975/4000 [38:02<00:15,  1.63it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.293512344360352, Predicted Probability: 0.0007, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.137724876403809, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3976/4000 [38:02<00:15,  1.54it/s]

Data point 1: Actual Class: 1.0, Final Logit: 5.866522789001465, Predicted Probability: 0.9972, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.959403991699219, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3977/4000 [38:03<00:15,  1.50it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.767189979553223, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 3.2346010208129883, Predicted Probability: 0.9621, Prediction: 1.0

Epoch 3/3:  99%|█████████▉| 3978/4000 [38:04<00:15,  1.44it/s]

Data point 1: Actual Class: 1.0, Final Logit: 4.719555377960205, Predicted Probability: 0.9912, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.334364891052246, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3:  99%|█████████▉| 3979/4000 [38:04<00:12,  1.67it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.385066032409668, Predicted Probability: 0.9983, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.954480171203613, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3980/4000 [38:04<00:09,  2.08it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.848841667175293, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.493148803710938, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3981/4000 [38:05<00:08,  2.22it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.365250587463379, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 8.460936546325684, Predicted Probability: 0.9998, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3982/4000 [38:05<00:07,  2.32it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.746438026428223, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -9.428067207336426, Predicted Probability: 0.0001, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3983/4000 [38:06<00:09,  1.86it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.674424171447754, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 6.205128192901611, Predicted Probability: 0.9980, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3984/4000 [38:07<00:10,  1.57it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.26876449584961, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.931350708007812, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3985/4000 [38:08<00:09,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.386035203933716, Predicted Probability: 0.9673, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -8.187237739562988, Predicted Probability: 0.0003, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3986/4000 [38:08<00:09,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.980393409729004, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.170815467834473, Predicted Probability: 0.0152, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3987/4000 [38:09<00:07,  1.69it/s]

Data point 1: Actual Class: 1.0, Final Logit: 9.332917213439941, Predicted Probability: 0.9999, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 10.991153717041016, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3988/4000 [38:09<00:07,  1.58it/s]

Data point 1: Actual Class: 0.0, Final Logit: -1.6035923957824707, Predicted Probability: 0.1675, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.11545467376709, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3989/4000 [38:10<00:07,  1.51it/s]

Data point 1: Actual Class: 1.0, Final Logit: 3.48191499710083, Predicted Probability: 0.9702, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -10.382726669311523, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3990/4000 [38:11<00:06,  1.45it/s]

Data point 1: Actual Class: 0.0, Final Logit: -7.967061996459961, Predicted Probability: 0.0003, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -4.9255852699279785, Predicted Probability: 0.0072, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3991/4000 [38:12<00:06,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.379852294921875, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.687514305114746, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3992/4000 [38:12<00:05,  1.39it/s]

Data point 1: Actual Class: 0.0, Final Logit: -2.435732841491699, Predicted Probability: 0.0805, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -10.752401351928711, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3994/4000 [38:13<00:02,  2.20it/s]

Data point 1: Actual Class: 0.0, Final Logit: -11.467401504516602, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.476027488708496, Predicted Probability: 1.0000, Prediction: 1.0
Data point 1: Actual Class: 1.0, Final Logit: 11.48853874206543, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 11.278984069824219, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3995/4000 [38:13<00:02,  2.32it/s]

Data point 1: Actual Class: 0.0, Final Logit: -5.667007923126221, Predicted Probability: 0.0034, Prediction: 0.0
Data point 2: Actual Class: 1.0, Final Logit: 11.684208869934082, Predicted Probability: 1.0000, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3996/4000 [38:14<00:02,  1.89it/s]

Data point 1: Actual Class: 1.0, Final Logit: 6.832483291625977, Predicted Probability: 0.9989, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.351924896240234, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3997/4000 [38:15<00:01,  1.54it/s]

Data point 1: Actual Class: 0.0, Final Logit: -9.619072914123535, Predicted Probability: 0.0001, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -8.609504699707031, Predicted Probability: 0.0002, Prediction: 0.0

Epoch 3/3: 100%|█████████▉| 3998/4000 [38:15<00:01,  1.76it/s]

Data point 1: Actual Class: 1.0, Final Logit: 10.957890510559082, Predicted Probability: 1.0000, Prediction: 1.0
Data point 2: Actual Class: 1.0, Final Logit: 7.329133987426758, Predicted Probability: 0.9993, Prediction: 1.0

Epoch 3/3: 100%|█████████▉| 3999/4000 [38:16<00:00,  1.55it/s]

Data point 1: Actual Class: 0.0, Final Logit: -10.090389251708984, Predicted Probability: 0.0000, Prediction: 0.0
Data point 2: Actual Class: 0.0, Final Logit: -11.176041603088379, Predicted Probability: 0.0000, Prediction: 0.0

Epoch 3/3: 100%|██████████| 4000/4000 [38:16<00:00,  1.74it/s]

Data point 1: Actual Class: 1.0, Final Logit: 7.1493940353393555, Predicted Probability: 0.9992, Prediction: 1.0
Data point 2: Actual Class: 0.0, Final Logit: -11.234585762023926, Predicted Probability: 0.0000, Prediction: 0.0
Epoch 3, Loss: 0.0478, Accuracy: 0.9865
Saving the ensemble model

Model saved as 'ensemble_model_epoch.pth'

In [37]:
from sklearn.metrics import classification_report, accuracy_score

# Evaluation function
def evaluate_model(model, test_loader, criterion):
    model.eval()  # Set the model to evaluation mode
    all_labels = []
    all_predictions = []
    total_loss = 0.0

    with torch.no_grad():
        for texts, labels in tqdm(test_loader, desc="Evaluating"):
            texts = list(texts)  # Convert batch of texts to a list
            labels = labels.to("cuda").float().view(-1, 1)

            # Forward pass through the ensemble model
            distil_logits, t5_logits, final_logits = model(texts)
            final_logits = final_logits.view(-1, 1)

            # Compute the loss
            loss = criterion(final_logits, labels)
            total_loss += loss.item()

            # Make predictions
            predictions = (final_logits > 0).float()

            # Store the true labels and predictions
            all_labels.extend(labels.cpu().numpy())
            all_predictions.extend(predictions.cpu().numpy())

    # Compute average loss over the test set
    avg_loss = total_loss / len(test_loader)

    # Compute accuracy
    accuracy = accuracy_score(all_labels, all_predictions)

    # Generate classification report
    report = classification_report(all_labels, all_predictions, target_names=["Class 0", "Class 1"])

    print(f"Test Loss: {avg_loss:.4f}")
    print(f"Test Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(report)

    return avg_loss, accuracy, report

# Call the evaluation function
criterion = nn.BCEWithLogitsLoss()
test_loss, test_accuracy, classification_report = evaluate_model(ensemble_model, test_loader, criterion)

Evaluating: 100%|██████████| 1000/1000 [03:59<00:00,  4.17it/s]

Test Loss: 0.0935
Test Accuracy: 0.9740
Classification Report:
              precision    recall  f1-score   support

     Class 0       0.98      0.96      0.97       975
     Class 1       0.97      0.98      0.97      1025

    accuracy                           0.97      2000
   macro avg       0.97      0.97      0.97      2000
weighted avg       0.97      0.97      0.97      2000

# testing on other datasets

## base paper dataset(10k datapoints)

In [38]:
df_base_paper_dataset = pd.read_csv('/kaggle/input/humanllm/Final_dataset.csv')
df_base_paper_dataset = df_base_paper_dataset[:10000]
df_base_paper_dataset.drop(columns=['uid'], inplace=True)

In [39]:
df_base_paper_dataset.head()

                                                text  label
0  Italy's President Sergio Mattarella has dissol...      1
1  Brendan Gallagher's piano career was abruptly ...      1
2  The concept for Wetsleeve(tm) was born out of ...      0
3  Police officers in the United States had a tou...      1
4  A woman has filed a lawsuit seeking more than ...      1

In [40]:
class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
# train_dataset = TextDataset(train_df)
test_dataset = TextDataset(df_base_paper_dataset)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [41]:
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report

# Load the saved model weights
ensemble_model = EnsembleModel(distil_model, t5_model, distil_tokenizer, t5_tokenizer)
# ensemble_model.load_state_dict(torch.load('/kaggle/input/2_epoch_mix_model/other/default/1/our_ensemble_model.pth'))
# ensemble_model.cuda()
ensemble_model.eval()

# DataLoader for the test dataset
# test_loader = DataLoader(df_base_paper_dataset, batch_size=2, shuffle=False)

# Function to test the model on the test data
def test_model(model, dataloader):
    model.eval()
    predictions = []
    true_labels = []
    with torch.no_grad():
        for texts, labels in tqdm(dataloader, desc="Testing"):
            texts = list(texts)
            labels = labels.to("cuda").float()

            # Forward pass through the ensemble model
            _, _, final_logits = model(texts)
            final_probs = torch.sigmoid(final_logits).squeeze().cpu().numpy()

            # Convert probabilities to binary predictions (threshold at 0.5)
            predicted_classes = (final_probs >= 0.5).astype(int)

            # Store predictions and true labels
            predictions.extend(predicted_classes)
            true_labels.extend(labels.cpu().numpy())

    return predictions, true_labels

# Test the model and get predictions
predictions, true_labels = test_model(ensemble_model, test_loader)

# Generate the classification report
report = classification_report(true_labels, predictions, target_names=["Class 0", "Class 1"])
print(report)

Testing: 100%|██████████| 5000/5000 [11:27<00:00,  7.27it/s]

              precision    recall  f1-score   support

     Class 0       1.00      0.86      0.92      4952
     Class 1       0.88      1.00      0.93      5048

    accuracy                           0.93     10000
   macro avg       0.94      0.93      0.93     10000
weighted avg       0.94      0.93      0.93     10000

## HC3 dataset from hugging face(5k datapoints)

In [42]:
# !pip install datasets
from datasets import load_dataset

ds = load_dataset("Hello-SimpleAI/HC3", "all")

# Concatenate inner lists into a single string for each element
concatenated = [' '.join(text_list) for text_list in ds['train']['human_answers']]

# Create a DataFrame with a single column named 'text'
df_human_hc3 = pd.DataFrame(concatenated, columns=['text'])
df_human_hc3['label'] = 0
df_human_hc3 = df_human_hc3[:2500]


concatenated_ = [' '.join(text_list) for text_list in ds['train']['chatgpt_answers']]

# Create a DataFrame with a single column named 'text'
df_ai_hc3 = pd.DataFrame(concatenated_, columns=['text'])
df_ai_hc3['label'] = 1
df_ai_hc3 = df_ai_hc3[:2500]



df_HC3 = pd.concat([df_ai_hc3, df_human_hc3], ignore_index=True)
# df_HC3 = df_HC3[:100]

class TextDataset(Dataset):
    def __init__(self, dataframe):
        self.dataframe = dataframe

    def __len__(self):
        return len(self.dataframe)

    def __getitem__(self, idx):
        text = self.dataframe.iloc[idx, 0]  # assuming 'text' is the first column
        label = int(self.dataframe.iloc[idx, 1])  # convert label to integer
        return text, label

# Data Loaders
# train_dataset = TextDataset(train_df)
test_dataset = TextDataset(df_HC3)

# train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True)  # Single datapoint per batch
test_loader = DataLoader(test_dataset, batch_size=2, shuffle=False)

In [ ]:
import torch
from torch.utils.data import DataLoader
from sklearn.metrics import classification_report

# Load the saved model weights
ensemble_model = EnsembleModel(distil_model, t5_model, distil_tokenizer, t5_tokenizer)
# ensemble_model.load_state_dict(torch.load('/kaggle/input/2_epoch_mix_model/other/default/1/our_ensemble_model.pth'))
# ensemble_model.cuda()
ensemble_model.eval()

# DataLoader for the test dataset
# test_loader = DataLoader(df_HC3, batch_size=2, shuffle=False)

# Function to test the model on the test data
def test_model(model, dataloader):
    model.eval()
    predictions = []
    true_labels = []
    with torch.no_grad():
        for texts, labels in tqdm(dataloader, desc="Testing"):
            texts = list(texts)
            labels = labels.to("cuda").float()

            # Forward pass through the ensemble model
            _, _, final_logits = model(texts)
            final_probs = torch.sigmoid(final_logits).squeeze().cpu().numpy()

            # Convert probabilities to binary predictions (threshold at 0.5)
            predicted_classes = (final_probs >= 0.5).astype(int)

            # Store predictions and true labels
            predictions.extend(predicted_classes)
            true_labels.extend(labels.cpu().numpy())

    return predictions, true_labels

# Test the model and get predictions
predictions, true_labels = test_model(ensemble_model, test_loader)

# Generate the classification report
report = classification_report(true_labels, predictions, target_names=["Class 0", "Class 1"], labels=[0, 1])
print(report)

Testing:  78%|███████▊  | 1938/2500 [02:34<00:52, 10.77it/s]

# LIMA dataset

In [ ]:
from datasets import load_dataset

# Login using e.g. `huggingface-cli login` to access this dataset
ds = load_dataset("GAIR/lima")